Repository hashicorp/vault, pull requests merged in 2019-08, with the labels that each got.

#7120 Fix GCP docs formatting
  website/source/docs/secrets/gcp/index.html.md
Labels: ecosystem

#7236 Add docs for OIDC verbose_oidc_logging
  website/source/api/auth/jwt/index.html.md.erb
  website/source/docs/auth/jwt.html.md
Labels: ecosystem

#7226 move replication-actions into core addon so that secondary recovery works
  ui/lib/core/addon/components/replication-action-demote.js
  ui/lib/core/addon/components/replication-action-disable.js
  ui/lib/core/addon/components/replication-action-promote.js
  ui/lib/core/addon/components/replication-action-recover.js
  ui/lib/core/addon/components/replication-action-reindex.js
  ui/lib/core/addon/components/replication-action-update-primary.js
  ui/lib/core/addon/components/replication-actions-single.js
  ui/lib/core/addon/components/replication-actions.js
  ui/lib/core/addon/helpers/replication-action-for-mode.js
  ui/lib/core/addon/mixins/replication-actions.js
  ui/lib/core/addon/templates/components/replication-action-demote.hbs
  ui/lib/core/addon/templates/components/replication-action-disable.hbs
  ui/lib/core/addon/templates/components/replication-action-promote.hbs
  ui/lib/core/addon/templates/components/replication-action-recover.hbs
  ui/lib/core/addon/templates/components/replication-action-reindex.hbs
  ui/lib/core/addon/templates/components/replication-action-update-primary.hbs
  ui/lib/core/addon/templates/components/replication-actions.hbs
  ui/lib/core/app/components/replication-action-demote.js
  ui/lib/core/app/components/replication-action-disable.js
  ui/lib/core/app/components/replication-action-promote.js
  ui/lib/core/app/components/replication-action-recover.js
  ui/lib/core/app/components/replication-action-reindex.js
  ui/lib/core/app/components/replication-action-update-primary.js
  ui/lib/core/app/components/replication-actions-single.js
  ui/lib/core/app/components/replication-actions.js
  ui/lib/core/app/helpers/replication-action-for-mode.js
  ui/lib/core/app/mixins/replication-actions.js
  ui/lib/replication/addon/components/replication-action-demote.js
  ui/lib/replication/addon/components/replication-action-disable.js
  ui/lib/replication/addon/components/replication-action-promote.js
  ui/lib/replication/addon/components/replication-action-recover.js
  ui/lib/replication/addon/components/replication-action-reindex.js
  ui/lib/replication/addon/components/replication-action-update-primary.js
  ui/lib/replication/addon/components/replication-summary.js
  ui/lib/replication/addon/templates/components/replication-actions.hbs
  ui/tests/integration/components/replication-actions-test.js
Labels: 🍒 :pick: :+1:

#7224 Fix create token sudo non-root namespace check
  vault/dynamic_system_view.go
Labels: 🍒 :pick: :+1:

#7241 Follow what documentation says we should do we're a perf standby and perfstandbyok=true
  http/sys_health.go
  website/source/api/system/health.html.md
Labels: 🍒 :pick: :+1:

#7233 Handle TokenType serialized as string or as uint8.
  builtin/credential/approle/path_role_test.go
  sdk/logical/token.go
  sdk/logical/token_test.go
Labels: 🍒 :pick: :+1:

#7193 doc: add k8s vault-helm doc
  website/data/docs_basic_categories.yml
  website/data/docs_detailed_categories.yml
  website/source/docs/platform/index.html.md
  website/source/docs/platform/k8s/helm.html.md
  website/source/docs/platform/k8s/index.html.md
  website/source/docs/platform/k8s/run.html.md
  website/source/layouts/docs.erb
Labels: ecosystem

#7307 kv v2 display bugs
  ui/app/components/secret-link.js
  ui/app/lib/attach-capabilities.js
  ui/app/models/auth-method.js
  ui/app/styles/components/toolbar.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/components/secret-link.hbs
  ui/app/templates/components/secret-version-menu.hbs
Labels: bug, ui, 🍒 :pick: :+1:

#7290 Fix regression that causes panic when logging in via Radius.
  builtin/credential/radius/path_login.go
Labels: bug, 🍒 :pick: :+1:

#7273 sdk/logical: handle empty token type string values as TokenTypeDefault
  builtin/credential/approle/path_role_test.go
  sdk/logical/token.go
  sdk/logical/token_test.go
Labels: 🍒 :pick: :+1:

#5720 Add some more detail for the root generation process
  website/source/api/system/generate-root.html.md
Labels: docs

#6366 Add section for consul 1.4+
  website/source/guides/operations/deployment-guide.html.md
Labels: docs

#7254 change input to textarea and use autosize on them
  ui/lib/core/addon/components/string-list.js
  ui/lib/core/addon/templates/components/string-list.hbs
  ui/tests/acceptance/settings/configure-secret-backends/pki/section-urls-test.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/pages/components/form-field.js
  ui/tests/pages/secrets/backend/pki/edit-role.js
Labels: 🍒 :pick: :+1:

#7199 Store less data in Cassandra prefix buckets
  physical/cassandra/cassandra.go
Labels: ecosystem, enhancement

#7336 README: add command for building enterprise binary
  README.md
Labels: docs

#7337 Ui/dismiss status menu click
  ui/app/services/auth.js
  ui/app/templates/components/status-menu.hbs
Labels: bug, ui

#6789 secret/aws: Pass policy ARNs to AssumedRole and FederationToken roles
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/path_roles.go
  builtin/logical/aws/path_roles_test.go
  builtin/logical/aws/path_user.go
  builtin/logical/aws/secret_access_keys.go
  website/source/api/secret/aws/index.html.md
  website/source/docs/secrets/aws/index.html.md
Labels: ecosystem

#7344 Add docs for Vault Agent Auto-auth Certificate Method
  website/source/docs/agent/autoauth/methods/cert.html.md
  website/source/layouts/docs.erb
Labels: docs

#7275 Allow setting file mode on vault agent sink file
  command/agent/sink/file/file_sink.go
  command/agent/sink/file/file_sink_test.go
  website/source/docs/agent/autoauth/sinks/file.html.md
Labels: ecosystem

#7338 Ui search select fix
  ui/app/components/identity/edit-form.js
  ui/app/components/search-select.js
  ui/package.json
  ui/tests/integration/components/search-select-test.js
  ui/yarn.lock
Labels: bug, ui

#7333 fix namespace picker so that it always expands into an object when co…
  ui/app/lib/path-to-tree.js
  ui/tests/unit/lib/path-to-tree-test.js
Labels: bug, ui

#7377 Ui/fix component story generators
  ui/README.md
  ui/blueprints/component/files/__root__/__path__/__name__.js
  ui/blueprints/component/index.js
  ui/lib/story-md.hbs
Labels: ui

#7391 [Typo] Auto-Auth doc
  website/source/docs/agent/index.html.md
Labels: docs
