Repository hashicorp/vault, pull requests merged in 2019-10, with the labels that each got.

#7504 do not swallow ControlGroupErrors when viewing or editing kvv2 secrets
  ui/app/adapters/secret-v2-version.js
  ui/app/lib/control-group-error.js
  ui/app/models/identity/entity.js
  ui/app/routes/vault/cluster/logout.js
  ui/app/services/control-group.js
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/redirect-to-test.js
  ui/tests/pages/auth.js
Labels: bug, ui

#7587 UI - namespace fixes
  ui/app/services/auth.js
  ui/lib/core/addon/components/edit-form.js
Labels: bug, ui

#7549 Cache whether we've been initialized to reduce load on storage
  go.mod
  go.sum
  vault/barrier_aes_gcm.go
  vendor/go.uber.org/atomic/.travis.yml
  vendor/go.uber.org/atomic/Makefile
  vendor/go.uber.org/atomic/README.md
  vendor/go.uber.org/atomic/error.go
  vendor/modules.txt
Labels: 🍒 :pick: :+1:

#7602 don't abort transitions if you're already on that route
  ui/app/mixins/cluster-route.js
  ui/tests/acceptance/enterprise-namespaces-test.js
Labels: ui

#7542 pgp list fix
  ui/app/components/pgp-file.js
  ui/app/components/pgp-list.js
  ui/app/templates/components/pgp-list.hbs
  ui/tests/integration/components/pgp-list-test.js
Labels: bug, ui

#7617 Update vault-plugin-ad-secrets to get check-out feature
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/backend.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/checkout_handler.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_checkout_sets.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_checkouts.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_config.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_creds.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_roles.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_rotate_root_creds.go
  vendor/modules.txt
Labels: ecosystem

#7589 Don't continue in a few places in pki tidy if value is nil
  builtin/logical/pki/path_tidy.go
Labels: 🍒 :pick: :+1:

#7633 Docs: File Audit Device
  website/source/docs/audit/file.html.md
Labels: docs

#7520 Docs: update Oracle Database Secrets Engine API
  website/source/api/secret/databases/oracle.html.md
Labels: docs

#7439 Adding the known issue section
  website/source/docs/upgrading/upgrade-to-1.1.0.html.md
  website/source/docs/upgrading/upgrade-to-1.1.1.html.md
  website/source/docs/upgrading/upgrade-to-1.1.2.html.md
  website/source/layouts/docs.erb
Labels: docs

#7676 Add document for sealwrap/rewrap endpoint
  website/source/api/system/sealwrap-rewrap.html.md
  website/source/layouts/api.erb
Labels: docs

#7664 Add docs for Active Directory secret check-out
  website/source/api/secret/ad/index.html.md
  website/source/docs/secrets/ad/index.html.md
Labels: docs, ecosystem

#7513 Enable generated items for more auth methods
  builtin/credential/cert/path_certs.go
  builtin/credential/ldap/path_groups.go
  builtin/credential/ldap/path_users.go
  builtin/credential/okta/path_config.go
  builtin/credential/okta/path_groups.go
  builtin/credential/okta/path_users.go
  builtin/credential/radius/path_config.go
  builtin/credential/radius/path_users.go
  builtin/credential/userpass/path_users.go
  sdk/framework/path.go
  sdk/helper/tokenutil/tokenutil.go
  ui/.storybook/preview-head.html
  ui/app/adapters/generated-item-list.js
  ui/app/components/generated-item.js
  ui/app/helpers/supported-managed-auth-backends.js
  ui/app/helpers/tabs-for-auth-section.js
  ui/app/routes/vault/cluster/access/method/index.js
  ui/app/routes/vault/cluster/access/method/item.js
  ui/app/routes/vault/cluster/access/method/item/edit.js
  ui/app/routes/vault/cluster/access/method/item/list.js
  ui/app/routes/vault/cluster/access/method/item/show.js
  ui/app/routes/vault/cluster/access/method/section.js
  ui/app/services/path-help.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/components/generated-item.hbs
  ui/app/templates/components/text-file.hbs
  ui/app/templates/vault/cluster/access/method/item/edit.hbs
  ui/app/templates/vault/cluster/access/method/item/list.hbs
  ui/app/templates/vault/cluster/access/method/item/show.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/utils/openapi-to-attrs.js
  ui/lib/core/addon/templates/components/field-group-show.hbs
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/tests/acceptance/settings/auth/configure/section-test.js
  ui/tests/unit/utils/openapi-to-attrs-test.js
Labels: ui

#7652 Vault Agent Template
  command/agent.go
  command/agent/README.md
  command/agent/auth/auth.go
  command/agent/auth/auth_test.go
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template-full.hcl
  command/agent/config/test-fixtures/config-template-many.hcl
  command/agent/config/test-fixtures/config-template-min.hcl
  command/agent/doc.go
  command/agent/template/template.go
  command/agent/template/template_test.go
  go.mod
  go.sum
  sdk/helper/pointerutil/pointer.go
  website/source/docs/agent/index.html.md
  website/source/docs/agent/template/index.html.md
Labels: beta, ecosystem, enhancement

#7685 Show versions that are active when delete_version_after is configured
  ui/app/models/secret-v2-version.js
  ui/tests/unit/models/secret-v2-version-test.js
Labels: ui

#7714 Mark secret version as deleted in history dropdown
  ui/app/templates/components/secret-edit.hbs
Labels: ui

#7731 update yarn to 1.19.1
  scripts/cross/Dockerfile
  ui/package.json
Labels: ui

#7553 allows emails@sign to be within the aws secrets engine path
  builtin/logical/aws/path_roles.go
  builtin/logical/aws/path_user.go
Labels: ecosystem, enhancement

#7620 UI - replication path filtering
  ui/app/adapters/path-filter-config.js
  ui/app/models/path-filter-config.js
  ui/app/serializers/path-filter-config.js
  ui/app/styles/components/hs-icon.scss
  ui/app/styles/components/radio-card.scss
  ui/app/styles/components/search-select.scss
  ui/app/styles/core.scss
  ui/lib/core/addon/components/icon.js
  ui/lib/core/addon/components/search-select-placeholder.js
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/templates/components/search-select-placeholder.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/lib/core/app/components/search-select-placeholder.js
  ui/lib/core/app/components/search-select.js
  ui/lib/core/package.json
  ui/lib/core/stories/icon.md
  ui/lib/core/stories/search-select.md
  ui/lib/core/stories/search-select.stories.js
  ui/lib/replication/addon/components/mount-filter-config-list.js
  ui/lib/replication/addon/components/path-filter-config-list.js
  ui/lib/replication/addon/controllers/application.js
  ui/lib/replication/addon/controllers/mode/secondaries/config-edit.js
  ui/lib/replication/addon/routes/mode/secondaries/add.js
  ui/lib/replication/addon/routes/mode/secondaries/config-create.js
  ui/lib/replication/addon/routes/mode/secondaries/config-edit.js
  ui/lib/replication/addon/routes/mode/secondaries/config-show.js
  ui/lib/replication/addon/routes/replication-base.js
  ui/lib/replication/addon/templates/components/mount-filter-config-list.hbs
  ui/lib/replication/addon/templates/components/path-filter-config-list.hbs
  ui/lib/replication/addon/templates/mode/secondaries/add.hbs
  ui/lib/replication/addon/templates/mode/secondaries/config-create.hbs
  ui/lib/replication/addon/templates/mode/secondaries/config-edit.hbs
  ui/public/file-error.svg
  ui/public/file-success.svg
  ui/stories/search-select.stories.js
  ui/tests/integration/components/mount-filter-config-list-test.js
  ui/tests/integration/components/path-filter-config-list-test.js
Labels: ui

#7757 fix security alerts
  ui/package.json
  ui/yarn.lock
Labels: ui

#7758 fix security alerts (#7757)
  ui/package.json
  ui/yarn.lock
Labels: ui

#7667 Add recovery mode docs.
  website/data/api_detailed_categories.yml
  website/data/docs_detailed_categories.yml
  website/source/api/system/generate-recovery-token.html.md
  website/source/docs/commands/operator/generate-root.html.md
  website/source/docs/concepts/recovery-mode.html.md
  website/source/layouts/docs.erb
Labels: docs

#7755 Fix incorrect env vars example
  website/source/docs/platform/k8s/helm.html.md
Labels: docs, ecosystem

#7590 Only link to nav items that user has access to
  ui/app/helpers/has-permission.js
  ui/app/services/permissions.js
  ui/tests/unit/services/permissions-test.js
Labels: bug, ui

#7751 Rabbitmq topic permissions
  builtin/logical/rabbitmq/backend_test.go
  builtin/logical/rabbitmq/path_role_create.go
  builtin/logical/rabbitmq/path_roles.go
  go.mod
  go.sum
  website/source/api/secret/rabbitmq/index.html.md
  website/source/docs/secrets/rabbitmq/index.html.md
Labels: ecosystem, enhancement

#7767 Backport 1.3: Only link to nav items that user has access to (#7590)
  ui/app/helpers/has-permission.js
  ui/app/services/permissions.js
  ui/tests/unit/services/permissions-test.js
Labels: ui
