Repository hashicorp/vault, pull requests merged in 2020-10, with the labels that each got.

#10035 Ui/transform handle delete
  ui/app/components/transform-edit-base.js
  ui/app/components/transform-role-edit.js
  ui/app/components/transformation-edit.js
Labels: ui

#10049 Ui/pricing metrics page setup
  ui/app/adapters/metrics/activity.js
  ui/app/adapters/metrics/config.js
  ui/app/controllers/vault/cluster/metrics-config.js
  ui/app/models/metrics/activity.js
  ui/app/models/metrics/config.js
  ui/app/router.js
  ui/app/routes/vault/cluster/metrics-config.js
  ui/app/routes/vault/cluster/metrics.js
  ui/app/routes/vault/cluster/metrics/http-requests.js
  ui/app/routes/vault/cluster/metrics/index.js
  ui/app/serializers/metrics/activity.js
  ui/app/serializers/metrics/config.js
  ui/app/templates/vault/cluster/metrics-config.hbs
  ui/app/templates/vault/cluster/metrics.hbs
  ui/app/templates/vault/cluster/metrics/http-requests.hbs
  ui/app/templates/vault/cluster/metrics/index.hbs
Labels: ui

#10064 Reworded disable_mlock docs
  website/pages/docs/configuration/index.mdx
Labels: docs-cherrypick

#10071 Adding an UG note on primary_cluster_addr behavior
  website/pages/docs/upgrading/upgrade-to-1.4.0.mdx
  website/pages/partials/primary-cluster-addr-change.mdx
Labels: docs-cherrypick

#10055 Pull latest raft updates
  go.mod
  go.sum
  vendor/github.com/hashicorp/raft/raft.go
  vendor/github.com/hashicorp/raft/replication.go
  vendor/modules.txt
  website/pages/docs/internals/telemetry.mdx
Labels: storage/raft

#10070 Test Fix: test for default TTL instead of date timestamp
  ui/tests/acceptance/enterprise-replication-test.js
Labels: ui

#10083 Ui/pricing metrics params
  ui/app/adapters/metrics/activity.js
  ui/app/adapters/metrics/entity.js
  ui/app/adapters/metrics/http-requests.js
  ui/app/adapters/metrics/token.js
  ui/app/components/pricing-metrics-dates.js
  ui/app/controllers/vault/cluster/metrics.js
  ui/app/helpers/parse-date-string.js
  ui/app/models/metrics/entity.js
  ui/app/models/metrics/http-requests.js
  ui/app/models/metrics/token.js
  ui/app/routes/vault/cluster/metrics.js
  ui/app/serializers/metrics.js
  ui/app/serializers/metrics/config.js
  ui/app/serializers/metrics/entity.js
  ui/app/serializers/metrics/token.js
  ui/app/services/permissions.js
  ui/app/styles/components/pricing-metrics-dates.scss
  ui/app/styles/core.scss
  ui/app/templates/components/pricing-metrics-dates.hbs
  ui/app/templates/partials/status/cluster.hbs
  ui/app/templates/vault/cluster.hbs
  ui/app/templates/vault/cluster/metrics.hbs
  ui/config/environment.js
  ui/lib/core/addon/components/form-error.js
  ui/lib/core/addon/templates/components/form-error.hbs
  ui/lib/core/app/components/form-error.js
  ui/tests/integration/components/form-error-test.js
  ui/tests/integration/components/pricing-metrics-dates-test.js
  ui/tests/unit/helpers/parse-date-string-test.js
Labels: ui

#10089 Backport: Pull latest raft updates
  go.mod
  go.sum
  vendor/github.com/hashicorp/raft/CHANGELOG.md
  vendor/github.com/hashicorp/raft/raft.go
  vendor/github.com/hashicorp/raft/replication.go
  vendor/modules.txt
  website/pages/docs/internals/telemetry.mdx
Labels: backport

#10087 Mask LDAP bindpass while typing
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/integration/components/masked-input-test.js
  ui/tests/pages/components/masked-input.js
Labels: ui

#9968 Add API docs for sys/monitor
  website/data/api-navigation.js
  website/pages/api-docs/system/monitor.mdx
Labels: docs-cherrypick

#10102 Ui/pricing metric config
  ui/app/adapters/metrics/config.js
  ui/app/components/pricing-metrics-config.js
  ui/app/components/selectable-card-container.js
  ui/app/controllers/vault/cluster/metrics-config.js
  ui/app/controllers/vault/cluster/metrics/index.js
  ui/app/models/metrics/config.js
  ui/app/router.js
  ui/app/routes/vault/cluster/metrics/config.js
  ui/app/routes/vault/cluster/metrics/edit.js
  ui/app/routes/vault/cluster/metrics/index.js
  ui/app/serializers/metrics/config.js
  ui/app/styles/components/selectable-card-container.scss
  ui/app/templates/components/pricing-metrics-config.hbs
  ui/app/templates/components/selectable-card-container.hbs
  ui/app/templates/vault/cluster/metrics/config.hbs
  ui/app/templates/vault/cluster/metrics/edit.hbs
  ui/app/templates/vault/cluster/metrics/index.hbs
  ui/stories/selectable-card-container.md
  ui/stories/selectable-card-container.stories.js
  ui/tests/integration/components/pricing-metrics-config-test.js
  ui/tests/integration/components/selectable-card-container-test.js
Labels: ui

#10098 Adding note about commands that are root only
  website/pages/docs/enterprise/namespaces/index.mdx
Labels: docs, website

#10119 Ui/pricing metric sparkle
  ui/app/components/pricing-metrics-dates.js
  ui/app/models/metrics/config.js
  ui/app/templates/vault/cluster/metrics/config.hbs
  ui/app/templates/vault/cluster/metrics/index.hbs
  ui/lib/core/addon/templates/components/form-error.hbs
  ui/tests/integration/components/pricing-metrics-dates-test.js
Labels: ui

#10105 [Website] Add new HashiStackMenu
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/style.css
Labels: docs-cherrypick, website

#10123 backport: fix password_policy key in secrets/ad
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/config.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/passwords.go
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_config.go
  vendor/github.com/hashicorp/vault/sdk/database/dbplugin/database.pb.go
  vendor/github.com/hashicorp/vault/sdk/logical/identity.pb.go
  vendor/github.com/hashicorp/vault/sdk/logical/plugin.pb.go
  vendor/github.com/hashicorp/vault/sdk/plugin/pb/backend.pb.go
  vendor/modules.txt
Labels: backport

#10126 docs/ssh: update algorithm_signer param after #9824
  website/pages/api-docs/secret/ssh/index.mdx
Labels: docs-cherrypick

#10139 Add GCS storage change to 1.5.0 upgrade guide
  website/pages/docs/upgrading/upgrade-to-1.5.0.mdx
Labels: docs-cherrypick

#10149 [Website] Bump HSM version
  website/package-lock.json
  website/package.json
Labels: docs, docs-cherrypick, website

#10145 Adds note that it requires a PEM-encoded file
  website/pages/docs/configuration/listener/tcp.mdx
Labels: docs-cherrypick

#10154 [Website] Update HSM version w/ waypoint
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, website

#10158 database/test: use vault.TestWaitActive when starting up a test cluster
  builtin/logical/database/backend_test.go
Labels: secret/database

#10159 backport 1.6.0: database/test: use vault.TestWaitActive when starting up a test cluster (#10158)
  builtin/logical/database/backend_test.go
Labels: backport

#10010 Rate Limit Quotas: Allow Exempt Paths to be Configurable
  vault/core.go
  vault/external_tests/quotas/quotas_test.go
  vault/logical_system_quotas.go
  vault/quotas/quotas.go
  vault/quotas/quotas_rate_limit.go
  website/pages/api-docs/system/quotas-config.mdx
  website/pages/docs/concepts/resource-quotas.mdx
Labels: core

#10133 Set default IMDS timeouts to match AWS SDK
  go.sum
  sdk/helper/awsutil/generate_credentials.go
  vendor/github.com/hashicorp/vault/sdk/helper/awsutil/generate_credentials.go
Labels: auth/aws, core/seal, secret/aws

#10166 backport 1.6.0: approle: Include role_name in alias metadata (#9529)
  builtin/credential/approle/path_login.go
  builtin/credential/approle/path_login_test.go
Labels: backport

#10167 backport 1.6: Set default IMDS timeouts to match AWS SDK (#10133)
  sdk/helper/awsutil/generate_credentials.go
  vendor/github.com/hashicorp/vault/sdk/helper/awsutil/generate_credentials.go
Labels: backport

#10152 Fix for broken link docs platform/k8s/injector/annotations
  website/pages/docs/platform/k8s/injector/annotations.mdx
Labels: docs-cherrypick

#10168 backport 1.5: Set default IMDS timeouts to match AWS SDK (#10133)
  sdk/helper/awsutil/generate_credentials.go
  vendor/github.com/hashicorp/vault/sdk/helper/awsutil/generate_credentials.go
Labels: backport

#10169 Fix press kit
  website/public/files/press-kit.zip
Labels: docs-cherrypick

#10155 Bug fix: Update Shamir Modal to clarify dr operation token command
  ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
Labels: ui

#10122 fix by returning apiPath from the model
  ui/app/adapters/generated-item-list.js
  ui/app/services/path-help.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: backport, ui

#10179 Backport 1.6.x: Auth list fix by returning dynamicApiPath from the model (#10122)
  ui/app/adapters/generated-item-list.js
  ui/app/services/path-help.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: ui

#10178 Backport 1.5.x: Auth list fix by returning dynamicApiPath from the model (#10122)
  ui/app/adapters/generated-item-list.js
  ui/app/services/path-help.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: ui

#10177 Backport 1.6.x: update dr promote modal text to clarify action (#10155)
  ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
Labels: ui

#10182 DBPW - Remove AutoMTLS option from DB plugin opts
  sdk/database/dbplugin/v5/plugin_client.go
  sdk/database/newdbplugin/plugin_client.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  vendor/github.com/hashicorp/vault/sdk/database/dbplugin/v5/plugin_client.go
  vendor/github.com/hashicorp/vault/sdk/helper/pluginutil/run_config.go
Labels: secret/database

#10187 Clarify prometheus_retention_time to 0
  website/pages/docs/configuration/telemetry.mdx
Labels: docs-cherrypick

#10186 k8s/injector: update docs for 0.6.0
  website/pages/docs/platform/k8s/injector/annotations.mdx
Labels: docs-cherrypick

#10190 docs: update helm to 0.8.0
  website/pages/docs/platform/k8s/helm/configuration.mdx
  website/pages/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/pages/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/pages/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/pages/docs/platform/k8s/helm/index.mdx
  website/pages/docs/platform/k8s/helm/openshift.mdx
  website/pages/docs/platform/k8s/helm/run.mdx
Labels: docs-cherrypick

#10196 Ui/pricing metrics api hookup
  ui/app/adapters/metrics/activity.js
  ui/app/components/pricing-metrics-dates.js
  ui/app/serializers/metrics/config.js
  ui/app/templates/components/pricing-metrics-dates.hbs
  ui/app/templates/vault/cluster/metrics/index.hbs
Labels: ui

#10205 Backport 1.6.0: Pricing Metrics UI updates for API
  ui/app/adapters/metrics/activity.js
  ui/app/components/pricing-metrics-dates.js
  ui/app/serializers/metrics/config.js
  ui/app/templates/components/pricing-metrics-dates.hbs
  ui/app/templates/vault/cluster/metrics/index.hbs
Labels: ui

#10142 Update HanaDb to v5 Database interface
  plugins/database/hana/hana.go
  plugins/database/hana/hana_test.go
Labels: secret/database

#10208 Updating latest version to 1.5.5 on website
  website/data/version.js
Labels: docs-cherrypick

#10213 Backport 1.6.0: Improve errors for aws login with an unbound ARN (#10036)
  builtin/credential/aws/path_login.go
Labels: backport

#10215 Update auth/jwt to latest release/vault-1.5.x
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
  vendor/modules.txt
Labels: auth/jwt-oidc, backport

#10214 Update auth/jwt to latest master
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
  vendor/modules.txt
Labels: auth/jwt-oidc

#10217 UI: Update replication secondaries language
  ui/lib/replication/addon/templates/components/known-secondaries-card.hbs
Labels: ui

#10218 UI: Fix error on OIDC/JWT auth enable or config
  ui/app/utils/openapi-to-attrs.js
Labels: bug, ui

#10209 Add info about aws timeouts to docs
  website/pages/docs/auth/aws.mdx
  website/pages/docs/configuration/seal/awskms.mdx
  website/pages/docs/configuration/storage/dynamodb.mdx
  website/pages/docs/configuration/storage/s3.mdx
  website/pages/docs/secrets/aws/index.mdx
  website/pages/docs/upgrading/upgrade-to-1.4.0.mdx
  website/pages/docs/upgrading/upgrade-to-1.5.0.mdx
  website/pages/partials/aws-imds-timeout-upgrade.mdx
  website/pages/partials/aws-imds-timeout.mdx
Labels: docs, docs-cherrypick

#7154 Add omitempty's to MountEntry and MountConfig
  vault/mount.go
Labels: core, waiting-for-response

#8457 Return logical.StatusBadRequest on requests with missing token
  http/handler_test.go
  vault/request_handling.go
Labels: bug

#7885 auth: store period value on tokens created via login
  CHANGELOG.md
  vault/request_handling.go
  vault/request_handling_test.go
  vault/token_store_test.go
Labels: core/auth

#10171 UI/OIDC: allow passing namespace in state
  ui/app/components/auth-jwt.js
  website/pages/api-docs/auth/jwt/index.mdx
  website/pages/docs/auth/jwt.mdx
Labels: auth/jwt-oidc, ecosystem, ui

#10240 Backport 1.6.0: Update replication secondaries language
  ui/lib/replication/addon/templates/components/known-secondaries-card.hbs
Labels: ui

#10175 backport 1.6.0: Fix robots.txt to disallow indexing of all paths (#10150)
  ui/public/robots.txt
Labels: backport, ui

#10257 docs: fix k8s helm configuration rendering
  website/pages/docs/platform/k8s/helm/configuration.mdx
Labels: docs-cherrypick

#10254 Add Learn More Here link to vault learn pricing metrics tutorial
  ui/app/templates/components/pricing-metrics-dates.hbs
Labels: ui

#10266 Updating to jwt plugin@master
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/cli.go
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_config.go
  vendor/github.com/hashicorp/vault-plugin-auth-jwt/path_oidc.go
  vendor/modules.txt
Labels: auth/jwt-oidc, ecosystem

#10284 Backport 1.6.0: mod: update vault plugins (#10283)
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-alicloud/go.mod
  vendor/github.com/hashicorp/vault-plugin-auth-alicloud/go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-centrify/go.mod
  vendor/github.com/hashicorp/vault-plugin-auth-centrify/go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-cf/go.mod
  vendor/github.com/hashicorp/vault-plugin-auth-cf/go.sum
  vendor/github.com/hashicorp/vault-plugin-auth-gcp/plugin/path_login.go
  vendor/github.com/hashicorp/vault-plugin-secrets-alicloud/go.mod
  vendor/github.com/hashicorp/vault-plugin-secrets-alicloud/go.sum
  vendor/github.com/hashicorp/vault-plugin-secrets-alicloud/renovate.json
  vendor/github.com/hashicorp/vault-plugin-secrets-azure/client.go
  vendor/github.com/hashicorp/vault-plugin-secrets-gcp/plugin/rollback.go
  vendor/github.com/hashicorp/vault-plugin-secrets-mongodbatlas/README.md
  vendor/github.com/hashicorp/vault-plugin-secrets-mongodbatlas/backend.go
  vendor/github.com/hashicorp/vault-plugin-secrets-mongodbatlas/client.go
  vendor/github.com/hashicorp/vault-plugin-secrets-mongodbatlas/go.mod
  vendor/github.com/hashicorp/vault-plugin-secrets-mongodbatlas/go.sum
  vendor/github.com/hashicorp/vault-plugin-secrets-mongodbatlas/secret_programmatic_api_keys.go
  vendor/github.com/hashicorp/vault-plugin-secrets-openldap/go.mod
  vendor/github.com/hashicorp/vault-plugin-secrets-openldap/go.sum
  vendor/modules.txt
Labels: backport

#10289 Backport 1.6.0: mod: update database-couchbase to v0.2.1 (#10286)
  go.mod
  go.sum
  vendor/modules.txt
Labels: backport

#10291 Backport 1.6.0: Reintroduce a feature flag to disable the activity log entirely. (#10288)
  vault/activity_log.go
Labels: backport

#10293 Backport 1.6.0: Vault 814 Invalidation for Activity Log (#10292)
  helper/timeutil/timeutil.go
  helper/timeutil/timeutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
Labels: backport
