Repository hashicorp/vault, pull requests merged in 2020-12, with the labels that each got.

#10424 Fix license caching issue
  changelog/10424.txt
  sdk/physical/cache.go
  vendor/github.com/hashicorp/vault/sdk/physical/cache.go
Labels: core/ha

#10483 clarify secret revoke during mount disable
  website/pages/docs/commands/secrets/disable.mdx
Labels: docs, docs-cherrypick, website

#10466 Backport ParseACLPolicy fix (#10156) to 1.6.1
  CHANGELOG.md
  go.mod
  go.sum
  vault/acl_test.go
  vendor/github.com/hashicorp/hcl/hcl/ast/ast.go
  vendor/modules.txt
Labels: backport

#10495 docs: fix auth/k8s broken link
  website/pages/docs/auth/kubernetes.mdx
Labels: docs-cherrypick

#10501 website: fix broken link to api docs
  website/pages/docs/secrets/ad/index.mdx
Labels: docs-cherrypick

#10422 Docs: Correct AES256 key length in Transit storage limits
  website/pages/docs/internals/limits.mdx
Labels: docs, docs-cherrypick

#10491 No 'v' in version HTML anchor
  changelog/10491.txt
  ui/lib/core/addon/helpers/changelog-url-for.js
  ui/tests/integration/helpers/changelog-url-for-test.js
Labels: backport, bug

#10513 Correct key length in Transit storage limits (#10422)
  website/pages/docs/internals/limits.mdx
Labels: docs

#10470 Add details on Consul token ttl
  website/pages/docs/secrets/consul/index.mdx
Labels: docs, docs/learn, secret/consul

#10521 Fix link to autosnap api docs.
  website/pages/docs/enterprise/automated-integrated-storage-snapshots/index.mdx
Labels: docs-cherrypick

#10528 Changelog updates for transform fixes (ENT)
  changelog/_1622.txt
  changelog/_1637.txt
Labels: backport

#10542 Backport influxdb bugfix changelog entries
  changelog/10384.txt
Labels: secret/database/influxdb

#10553 website: redirect raft snapshot url to automated storage snapshots
  website/_redirects
Labels: docs-cherrypick

#10574 Update index.mdx
  website/pages/docs/plugin-portal/index.mdx
Labels: docs-cherrypick

#10485 core: add warning when disabling activity
  vault/logical_system_activity.go
Labels: core

#10580 Update to add the newly released Couchbase DB SE
  website/pages/docs/plugin-portal/index.mdx
Labels: docs-cherrypick

#10586 Bug Fix: allow click of label and box for box-radio component
  ui/app/styles/components/box-radio.scss
  ui/lib/core/addon/components/box-radio.js
  ui/lib/core/addon/templates/components/box-radio.hbs
Labels: bug, ui

#10520 Send a test message before committing a new audit device.
  audit/audit.go
  audit/format.go
  builtin/audit/file/backend.go
  builtin/audit/socket/backend.go
  builtin/audit/syslog/backend.go
  changelog/10520.txt
  command/audit_enable_test.go
  sdk/helper/salt/salt.go
  vault/audit.go
  vault/testing.go
  vendor/github.com/hashicorp/vault/sdk/helper/salt/salt.go
Labels: core/audit

#10566 Updating version to 1.6.1
  website/data/version.js
Labels: docs-cherrypick

#10601 Add Ember upgrade to changelog
  changelog/9972.txt
Labels: ui

#10609 Add log gathering to debug command.
  changelog/10609.txt
  command/debug.go
  command/debug_test.go
Labels: backport
