Repository hashicorp/vault, pull requests merged in 2020-03, with the labels that each got.

#8312 adding prometheus info to make more self-service
  website/pages/docs/configuration/telemetry.mdx
Labels: docs

#8250 docs: add audit non-hmac-* flags to command docs
  website/pages/docs/commands/auth/enable.mdx
  website/pages/docs/commands/auth/tune.mdx
  website/pages/docs/commands/secrets/enable.mdx
  website/pages/docs/commands/secrets/tune.mdx
Labels: docs, docs-cherrypick

#8401 Add Core Usage Metrics Components to Storybook
  ui/app/components/http-requests-bar-chart-simple.js
  ui/app/components/selectable-card-container.js
  ui/app/components/selectable-card.js
  ui/app/styles/components/selectable-card.scss
  ui/app/templates/components/http-requests-bar-chart-simple.hbs
  ui/app/templates/components/selectable-card-container.hbs
  ui/stories/http-requests-bar-chart-simple.md
  ui/stories/http-requests-bar-chart-simple.stories.js
  ui/stories/http-requests-bar-chart.stories.js
  ui/stories/selectable-card-container.md
  ui/stories/selectable-card-container.stories.js
  ui/stories/selectable-card.md
  ui/stories/selectable-card.stories.js
  ui/tests/integration/components/http-requests-bar-chart-simple-test.js
Labels: ui

#8372 skip go tests on ui and doc branches
  .circleci/config.yml
  .circleci/config/commands/check-branch-name.yml
  .circleci/config/jobs/test-go.yml
  .circleci/config/workflows/ci.yml
Labels: docs, release/build, ui

#8452 Backport 1.4.x: Add Core Usage Metrics Components to Storybook (#8401)
  ui/app/components/http-requests-bar-chart-simple.js
  ui/app/components/selectable-card-container.js
  ui/app/components/selectable-card.js
  ui/app/styles/components/selectable-card.scss
  ui/app/templates/components/http-requests-bar-chart-simple.hbs
  ui/app/templates/components/selectable-card-container.hbs
  ui/stories/http-requests-bar-chart-simple.md
  ui/stories/http-requests-bar-chart-simple.stories.js
  ui/stories/http-requests-bar-chart.stories.js
  ui/stories/selectable-card-container.md
  ui/stories/selectable-card-container.stories.js
  ui/stories/selectable-card.md
  ui/stories/selectable-card.stories.js
  ui/tests/integration/components/http-requests-bar-chart-simple-test.js
Labels: backport, ui

#8454 Correct GCP auth permissions list
  website/pages/docs/auth/gcp.mdx
Labels: docs-cherrypick

#8451 Backport 1.4.x: Sanitize Vault version strings for Kubernetes
  serviceregistration/kubernetes/client/client.go
  serviceregistration/kubernetes/client/client_test.go
  serviceregistration/kubernetes/service_registration.go
  serviceregistration/kubernetes/service_registration_test.go
Labels: backport

#8468 Backport 1.3.x: Fix for missing License nav item in menu (#8230)
  ui/app/templates/partials/status/cluster.hbs
Labels: bug, ui

#8470 Backport 1.3.x: show kmip in wizard
  ui/app/templates/components/wizard/kmip-engine.hbs
Labels: ui

#8462 Ui/transit key actions textareas
  ui/.eslintignore
  ui/app/components/transit-key-actions.js
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/verify.hbs
  ui/tests/acceptance/transit-test.js
  ui/tests/integration/components/transit-key-actions-test.js
Labels: ui

#8474 Backport 1.4.x: Transit Key Actions Textareas
  ui/.eslintignore
  ui/app/components/transit-key-actions.js
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/verify.hbs
  ui/tests/acceptance/transit-test.js
  ui/tests/integration/components/transit-key-actions-test.js
Labels: backport, ui

#8479 docs: update vault k8s to 0.3.0
  website/data/docs-navigation.js
  website/pages/docs/platform/k8s/injector/annotations.mdx
  website/pages/docs/platform/k8s/injector/index.mdx
Labels: docs-cherrypick

#8480 Ui/transit key versions update
  ui/app/styles/components/list-item-row.scss
  ui/app/templates/partials/transit-form-show.hbs
Labels: ui

#8442 Improvement: give option to refresh namespace dropdown
  ui/app/components/namespace-picker.js
  ui/app/styles/components/namespace-picker.scss
  ui/app/templates/components/namespace-picker.hbs
Labels: ui

#8483 Backport: For PR 8442 into 1.4.x
  ui/app/components/namespace-picker.js
  ui/app/styles/components/namespace-picker.scss
  ui/app/templates/components/namespace-picker.hbs
Labels: backport, ui

#8485 Fix migrating away from raft storage
  command/operator_migrate.go
Labels: storage/raft

#8495 [website] update dependency lockfile
  website/package-lock.json
Labels: website

#7738 feat: replace the way AWS sessions are created and added a new WebIdentity provider to the credentials chain
  sdk/helper/awsutil/generate_credentials.go
Labels: ecosystem, enhancement

#8488 Fix potential nil-pointer panic
  builtin/logical/pki/path_intermediate.go
Labels: bug

#8484 Rename raft configuration command to list-peers and make output easier to read
  CHANGELOG.md
  command/commands.go
  command/operator_raft.go
  command/operator_raft_configuration.go
  command/operator_raft_listpeers.go
Labels: storage/raft

#8506 Document MSSQL revocation behaviour
  website/pages/docs/secrets/databases/mssql.mdx
Labels: docs, secret/database

#8500 Bug Fix: Show Error messages on Auth Configuration page
  ui/app/components/auth-config-form/options.js
  ui/app/templates/components/auth-config-form/options.hbs
Labels: bug, ui

#8515 Backport: Show Error messages on Auth Configuration page (#8500) into 1.4.x
  ui/app/components/auth-config-form/options.js
  ui/app/templates/components/auth-config-form/options.hbs
Labels: backport, bug, ui

#8519 Bug Fix: remove duplicate form inputs on GitHub auth config page
  ui/app/models/auth-config/github.js
Labels: bug, ui

#8526 Backport: 1.4.x remove duplicate form inputs for the github config
  ui/app/models/auth-config/github.js
Labels: backport, ui

#8520 Fix SRV Lookups
  api/client.go
  api/client_test.go
  api/request.go
  website/pages/docs/commands/index.mdx
Labels: bug, core/api, core/cli

#8528 Bug Fix: capitalization of HMAC consistency on transit engine
  ui/app/templates/partials/transit-form-show.hbs
  ui/app/templates/vault/cluster/secrets/backend/transit-actions-layout.hbs
Labels: bug, ui

#8532 Backport into 1.4.x. Bug fix capitalization of HMAC
  ui/app/templates/partials/transit-form-show.hbs
  ui/app/templates/vault/cluster/secrets/backend/transit-actions-layout.hbs
Labels: backport, ui

#8533 Backport into 1.4.x. Fix SRV Lookups
  api/client.go
  api/client_test.go
  api/request.go
Labels: backport, bug, core/api, core/cli

#8555 Bug fix: add in missing curly braces to demote danger message
  ui/lib/core/addon/templates/components/replication-action-demote.hbs
Labels: bug, ui

#8557 Fixes reported missing link
  website/pages/docs/partnerships/index.mdx
Labels: docs

#8564 Website release process clarification
  website/README.md
  website/pages/downloads/index.jsx
Labels: website

#8542 Add docs for Kerb field
  website/pages/docs/agent/autoauth/methods/kerberos.mdx
  website/pages/docs/auth/kerberos.mdx
Labels: auth/kerberos, docs, ecosystem

#8559 Backport 1.4.x: add in missing curly braces to demote danger message (#8555)
  ui/lib/core/addon/templates/components/replication-action-demote.hbs
Labels: backport, bug, ui

#8571 Website Deps Upgrade
  website/package-lock.json
  website/package.json
  website/pages/downloads/index.jsx
Labels: website

#8556 Add debug logging for client selection
  builtin/credential/aws/client.go
Labels: auth/aws

#8575 Ui/transit modal
  ui/app/components/modal.js
  ui/app/components/transit-key-actions.js
  ui/app/styles/components/modal.scss
  ui/app/styles/components/transit-card.scss
  ui/app/styles/core.scss
  ui/app/templates/components/modal.hbs
  ui/app/templates/components/transit-key-action/datakey.hbs
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/export.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/sign.hbs
  ui/app/templates/components/transit-key-action/verify.hbs
  ui/app/templates/components/transit-key-actions.hbs
  ui/package.json
  ui/tests/acceptance/transit-test.js
  ui/tests/integration/components/modal-test.js
  ui/tests/integration/components/transit-key-actions-test.js
  ui/yarn.lock
Labels: ui

#8548 Raft cli docs
  command/operator_raft.go
  command/operator_raft_join.go
  command/operator_raft_listpeers.go
  command/operator_raft_remove_peer.go
  command/operator_raft_snapshot.go
  command/operator_raft_snapshot_save.go
  website/data/docs-navigation.js
  website/pages/docs/commands/operator/raft.mdx
Labels: docs, storage/raft

#8579 Backport 1.4.x: Ui/transit key versions update (#8480)
  ui/app/styles/components/list-item-row.scss
  ui/app/templates/partials/transit-form-show.hbs
Labels: backport, ui

#8573 Bug Fix: allow certificates to be copy/pasted on LDAP auth config
  ui/app/models/auth-config/ldap.js
Labels: bug, ui

#8581 Backport: for PR 8573, fix certificates field on LDAP config
  ui/app/models/auth-config/ldap.js
Labels: backport, ui

#8584 Backport 1.4.x: Fix potential nil-pointer panic
  builtin/logical/pki/path_intermediate.go
Labels: bug, secret/pki

#8583 Ui/transit modal (#8575)
  ui/app/components/modal.js
  ui/app/components/transit-key-actions.js
  ui/app/styles/components/modal.scss
  ui/app/styles/components/transit-card.scss
  ui/app/styles/core.scss
  ui/app/templates/components/modal.hbs
  ui/app/templates/components/transit-key-action/datakey.hbs
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/export.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/sign.hbs
  ui/app/templates/components/transit-key-action/verify.hbs
  ui/app/templates/components/transit-key-actions.hbs
  ui/package.json
  ui/tests/acceptance/transit-test.js
  ui/tests/integration/components/modal-test.js
  ui/tests/integration/components/transit-key-actions-test.js
  ui/yarn.lock
Labels: backport, ui

#8512 Postgres: Correct parsing of multiline statements
  plugins/database/postgresql/postgresql.go
  plugins/database/postgresql/postgresql_test.go
Labels: bug, secret/database

#8550 Raft telemetry
  website/pages/docs/internals/telemetry.mdx
Labels: storage/raft

#8574 Upgrade deps for security
  ui/package.json
  ui/yarn.lock
Labels: ui

#8521 API Docs: Secrets/OpenLDAP
  website/pages/api-docs/secret/openldap/index.mdx
Labels: secret/openldap

#8593 fix extensions name in client signing example
  website/pages/docs/secrets/ssh/signed-ssh-certificates.mdx
Labels: docs

#8610 Ui/toggle component
  ui/app/components/toggle.js
  ui/app/styles/core.scss
  ui/app/styles/core/toggle.scss
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/components/toggle.hbs
  ui/stories/toggle.md
  ui/stories/toggle.stories.js
  ui/tests/integration/components/secret-edit-test.js
  ui/tests/integration/components/toggle-test.js
  ui/tests/pages/secrets/backend/kv/edit-secret.js
Labels: ui

#8565 Add browser support chart to website readme
  website/README.md
Labels: website

#7971 Fix grammar error in deploy.html.md
  website/pages/intro/getting-started/deploy.mdx
Labels: docs

#8614 Add missing API doc for DR secondary disable
  website/pages/api-docs/system/replication/replication-dr.mdx
Labels: docs

#8618 Bug: Add in missing license features
  ui/app/helpers/all-features.js
Labels: bug, ui

#8624 Backport to 1.4.x: add missing license features (#8618)
  ui/app/helpers/all-features.js
Labels: backport, ui

#8625 Added links to Learn and certification exams to the README
  README.md
Labels: docs

#8619 Rabbitmq: surface errors from responses
  builtin/logical/rabbitmq/backend_test.go
  builtin/logical/rabbitmq/path_role_create.go
Labels: bug, secret/rabbitmq

#8596 Add doc for Venafi Secrets Engine
  website/data/docs-navigation.js
  website/pages/docs/secrets/venafi/index.mdx
Labels: docs, ecosystem

#8633 Overtabed example corrected.
  website/pages/docs/secrets/aws/index.mdx
Labels: docs, secret/aws

#8549 Use Head Component
  website/components/default-head-tags/index.jsx
  website/components/docs-page/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/_document.js
  website/pages/community/index.jsx
  website/pages/downloads/index.jsx
Labels: website

#8587 Update SubNav component
  website/package-lock.json
  website/package.json
Labels: website

#8629 Backport 1.4.x: Rabbitmq: surface errors from responses (#8619)
  builtin/logical/rabbitmq/backend_test.go
  builtin/logical/rabbitmq/path_role_create.go
Labels: bug, secret/rabbitmq

#8632 Updates the k8s helm platform docs
  website/data/docs-navigation.js
  website/pages/docs/platform/k8s/helm/examples/development.mdx
  website/pages/docs/platform/k8s/helm/examples/external.mdx
  website/pages/docs/platform/k8s/helm/examples/index.mdx
  website/pages/docs/platform/k8s/helm/index.mdx
  website/pages/docs/platform/k8s/helm/run.mdx
  website/pages/docs/platform/k8s/index.mdx
  website/pages/docs/platform/k8s/injector/index.mdx
Labels: docs

#8635 In the KV metadata put CLI, allow delete-version-after to be reset to 0
  command/kv_metadata_put.go
  command/kv_metadata_put_test.go
Labels: bug, core/cli, secret/kv

#8630 ui/provide otp
  ui/app/templates/components/shamir-flow.hbs
Labels: bug, ui

#8641 Backport 1.4.x: In the KV metadata put CLI, allow delete-version-after to be reset to 0
  command/kv_metadata_put.go
  command/kv_metadata_put_test.go
Labels: bug, core/cli, secret/kv

#8572 Anchor Link Fixes
  website/.npm-upgrade.json
  website/components/before-after-diagram/style.css
  website/components/subnav/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/api-docs/secret/azure/index.mdx
  website/pages/api-docs/secret/gcp/index.mdx
  website/pages/api-docs/secret/identity/index.mdx
  website/pages/api-docs/secret/pki/index.mdx
  website/pages/docs/auth/azure.mdx
  website/pages/docs/auth/gcp.mdx
  website/pages/docs/auth/jwt.mdx
  website/pages/docs/auth/kerberos.mdx
  website/pages/docs/auth/oci.mdx
  website/pages/docs/commands/index.mdx
  website/pages/docs/commands/operator/migrate.mdx
  website/pages/docs/configuration/entropy-augmentation/index.mdx
  website/pages/docs/configuration/telemetry.mdx
  website/pages/docs/enterprise/mfa/index.mdx
  website/pages/docs/internals/integrated-storage.mdx
  website/pages/docs/platform/aws-mp/index.mdx
  website/pages/docs/platform/k8s/helm/run.mdx
  website/pages/docs/secrets/azure/index.mdx
  website/pages/docs/secrets/kmip/index.mdx
  website/pages/docs/upgrading/upgrade-to-0.6.0.mdx
  website/pages/docs/upgrading/upgrade-to-0.6.1.mdx
  website/pages/docs/upgrading/upgrade-to-0.9.3.mdx
  website/pages/docs/what-is-vault/index.mdx
  website/pages/guides/encryption/spring-demo.mdx
  website/pages/guides/identity/authentication.mdx
  website/pages/guides/operations/deployment-guide.mdx
  website/pages/guides/operations/disaster-recovery.mdx
  website/pages/guides/operations/index.mdx
  website/pages/guides/operations/mount-filter.mdx
  website/pages/guides/operations/replication.mdx
Labels: website

#8642 ui/provide otp (#8630)
  ui/app/templates/components/shamir-flow.hbs
Labels: backport, ui

#8535 token/renewal: return full set of token and identity policies in the …
  vault/external_tests/policy/policy_test.go
  vault/request_handling.go
Labels: auth/token

#8645 fixed some grammar issue
  website/pages/docs/secrets/index.mdx
Labels: docs
