Repository hashicorp/vault, pull requests merged in 2021-12, with the labels that each got.

#13321 Use real version of auth modules in root go.mod
  go.mod
Labels: pr/no-changelog

#13000 UI/kv codemirror diff
  changelog/13000.txt
  ui/app/adapters/secret-v2-version.js
  ui/app/components/diff-version-selector.js
  ui/app/components/json-editor.js
  ui/app/controllers/vault/cluster/secrets/backend/diff.js
  ui/app/router.js
  ui/app/routes/vault/cluster/secrets/backend/diff.js
  ui/app/styles/components/diff-version-selector.scss
  ui/app/styles/components/toolbar.scss
  ui/app/styles/core.scss
  ui/app/templates/components/diff-version-selector.hbs
  ui/app/templates/components/json-editor.hbs
  ui/app/templates/components/secret-version-menu.hbs
  ui/app/templates/vault/cluster/secrets/backend/diff.hbs
  ui/ember-cli-build.js
  ui/package.json
  ui/tests/acceptance/secrets/backend/kv/diff-test.js
  ui/tests/integration/components/diff-version-selector-test.js
  ui/yarn.lock
Labels: ui

#13323 aws/logical: fix backend test
  builtin/logical/aws/backend_test.go
Labels: test, pr/no-changelog

#13155 update custom headers to mention 1.9 is required
  website/content/docs/configuration/listener/tcp.mdx
Labels: docs-cherrypick, pr/no-changelog

#13198 Unhide or remove docs sidebar elements
  website/content/docs/secrets/cassandra.mdx
  website/content/docs/vs.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#13329 Fix docs build
  website/content/docs/commands/help.mdx
Labels: docs-cherrypick, pr/no-changelog

#13330 Vault documentation: updated client count FAQ document
  website/content/docs/concepts/client-count/faq.mdx
Labels: docs-cherrypick, pr/no-changelog

#13334 Backport 1.8.6: Disable 'You will not be able to access these later' warning for static db creds
  ui/app/templates/components/generate-credentials-database.hbs
Labels: ui, backport, bug

#12894 website: fix print styles by bumping deps
  website/package-lock.json
  website/package.json
  website/pages/print.css
Labels: docs-cherrypick, website, pr/no-changelog

#13336 GetCredentials Bug fix
  ui/app/components/get-credentials-card.js
  ui/app/templates/components/get-credentials-card.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
Labels: ui, backport, bug, pr/no-changelog

#13337 Backport: 1.9.x GetCredentials Card bug fix
  ui/app/components/get-credentials-card.js
  ui/app/templates/components/get-credentials-card.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
Labels: backport

#12463 improve "x_forwarded_for_hop_skips" example
  website/content/docs/configuration/listener/tcp.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#13088 adding CRT to main branch
  .circleci/config.yml
  .circleci/config/@build-release.yml
  .github/workflows/build.yml
  .gitignore
  .release/ci.hcl
  .release/docker/docker-entrypoint.sh
  .release/linux/package/etc/vault.d/vault.env
  .release/linux/package/etc/vault.d/vault.hcl
  .release/linux/package/usr/lib/systemd/system/vault.service
  .release/linux/postinst
  .release/linux/postrm
  .release/linux/preinst
  Dockerfile
  Makefile
  packages-oss.lock/.gitattributes
  packages-oss.lock/Makefile
  packages-oss.lock/build.mk
  packages-oss.lock/config.mk
  packages-oss.lock/layer.mk
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
  packagespec.mk
  scripts/upgrade-packagespec
  scripts/version.sh
Labels: pr/no-changelog

#13085 CRT Onboarding for release/1.6.x
  .circleci/config/@build-release.yml
  .github/workflows/build.yml
  .gitignore
  .release/ci.hcl
  .release/docker/docker-entrypoint.sh
  .release/linux/package/etc/vault.d/vault.env
  .release/linux/package/etc/vault.d/vault.hcl
  .release/linux/package/usr/lib/systemd/system/vault.service
  .release/linux/postinst
  .release/linux/postrm
  .release/linux/preinst
  Dockerfile
  Makefile
  packages-oss.lock/.gitattributes
  packages-oss.lock/Makefile
  packages-oss.lock/build.mk
  packages-oss.lock/config.mk
  packages-oss.lock/layer.mk
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
  packagespec.mk
  scripts/version.sh
Labels: pr/no-changelog

#13307 Update SDK in go.mod for 1.8.6
  go.mod
Labels: pr/no-changelog

#13306 Go get and go mod vendor for 1.7.7
  go.mod
  vendor/github.com/hashicorp/vault/sdk/version/version_base.go
  vendor/modules.txt
Labels: pr/no-changelog

#13355 Fix typo
  website/content/docs/agent/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#13352 Add kms_library configuration stanza
  command/server/config.go
  command/server/config_oss_test.go
  command/server/config_test_helpers.go
  website/content/docs/configuration/kms-library.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#13351 Vault documentation: Update note about tokens
  website/content/docs/concepts/tokens.mdx
Labels: docs-cherrypick, pr/no-changelog

#13280 docs: winsvc update recommendations
  website/content/docs/agent/winsvc.mdx
Labels: docs-cherrypick, pr/no-changelog

#13211 docs: update custom database sample code
  website/content/docs/secrets/databases/custom.mdx
Labels: docs-cherrypick, pr/no-changelog

#12586 Docs: Clarify more sink options
  website/content/docs/agent/autoauth/sinks/file.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#13354 website: Upgrade <HashiStackMenu /> to latest
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, website, pr/no-changelog

#13275 Docs to clarify k8s auth options with short-lived tokens
  website/content/docs/auth/jwt/oidc_providers.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: docs-cherrypick, pr/no-changelog

#13367 Adds support for SHA-3 to transit
  builtin/logical/transit/path_hash.go
  builtin/logical/transit/path_hash_test.go
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_hmac_test.go
  builtin/logical/transit/path_sign_verify.go
  builtin/logical/transit/path_sign_verify_test.go
  changelog/13367.txt
  sdk/helper/keysutil/consts.go
  sdk/helper/keysutil/policy.go
  vault/logical_system.go
  vault/logical_system_test.go
  website/content/api-docs/secret/transit.mdx
  website/content/api-docs/system/tools.mdx
Labels: secret/transit, cryptosec

#13362 agent/cache: differentiate open log messages
  command/agent.go
Labels: core/agent, pr/no-changelog

#13366 Warn user supplying nonce values in FIPS mode for transit encryption requests
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_rewrap.go
  helper/constants/fips.go
Labels: pr/no-changelog

#13370 [VAULT-3252] Add entity-alias behavior change to docs
  website/content/docs/concepts/identity.mdx
  website/content/docs/upgrading/upgrade-to-1.7.x.mdx
  website/content/docs/upgrading/upgrade-to-1.8.x.mdx
  website/content/docs/upgrading/upgrade-to-1.9.x.mdx
  website/content/partials/entity-alias-mapping.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#13375 Update alert banner
  website/data/alert-banner.js
Labels: website

#13379 Updating version in SDK for 1.7.8
  sdk/version/version_base.go
Labels: pr/no-changelog

#13380 bump version to 1.8.7
  sdk/version/version_base.go
Labels: pr/no-changelog

#13384 go sdk version upgrade
  go.mod
Labels: pr/no-changelog

#13383 Update SDK in go.mod for 1.7.8
  go.mod
  vendor/github.com/hashicorp/vault/sdk/version/version_base.go
  vendor/modules.txt
Labels: pr/no-changelog

#13378 Updating website for 1.9.1
  website/data/version.js
Labels: docs-cherrypick, pr/no-changelog

#13389 Use os.Hostname instead of a dependency that doesn't work on OpenBSD.
  vault/logical_system.go
Labels: pr/no-changelog

#13390 Remove another use gopsutil/host.
  vault/request_forwarding_rpc.go
Labels: pr/no-changelog

#13255 CLI changes for new mount tune config parameter allowed_managed_keys
  command/commands.go
  command/secrets_enable.go
  command/secrets_enable_test.go
  command/secrets_tune.go
  command/secrets_tune_test.go
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/commands/secrets/tune.mdx
Labels: pr/no-changelog

#13392 auth/jwt: update changelog for pkce improvement
  changelog/13365.txt
Labels: pr/no-changelog

#13371 Fix test validating convergent encryption behaviour across key types
  builtin/logical/transit/backend_test.go
Labels: pr/no-changelog

#13361 UI/ horizontal bar chart component
  ui/app/components/clients/dashboard.js
  ui/app/components/clients/horizontal-bar-charts.js
  ui/app/styles/components/horizontal-bar-charts.scss
  ui/app/styles/core.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/horizontal-bar-charts.hbs
  ui/app/templates/components/clients/total-client-usage.hbs
  ui/package.json
  ui/tests/integration/components/horizontal-bar-chart-tests.js
  ui/yarn.lock
Labels: pr/no-changelog

#13394 Fix managed namespace test
  ui/app/routes/vault/cluster.js
  ui/tests/acceptance/managed-namespace-test.js
Labels: ui, pr/no-changelog

#13385 Some changelog tidying for 1.10 preview
  changelog/12792.txt
  changelog/12795.txt
  changelog/13022.txt
  changelog/13178.txt
  changelog/13202.txt
Labels: pr/no-changelog

#13396 UI/fix client count partial
  changelog/13396.txt
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/history.hbs
  ui/tests/integration/components/clients-current-test.js
Labels: ui, backport, bug

#13400 Backport 1.9.2: UI/fix client count partial (#13396)
  changelog/13396.txt
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/history.hbs
  ui/tests/integration/components/clients-current-test.js
Labels: ui, bug

#13399 Docs: fix invalid link in the kubernetes auth api doc.
  website/content/api-docs/auth/kubernetes.mdx
Labels: pr/no-changelog

#13405 auth/azure: add note about debug env
  website/content/docs/auth/azure.mdx
Labels: docs-cherrypick, pr/no-changelog

#13407 Fix logging statement using formatting args
  vault/core.go
Labels: pr/no-changelog

#13397 UI/tooltip
  ui/app/components/clients/total-client-usage.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/horizontal-bar-charts.hbs
  ui/app/templates/components/clients/total-client-usage.hbs
  ui/package.json
  ui/yarn.lock
Labels: ui

#13413 Add docs about path param restrictions
  website/content/api-docs/auth/userpass.mdx
  website/content/api-docs/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#13412 Update raftautosnapshots.mdx
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: docs-cherrypick, pr/no-changelog

#13420 Bump yarn cache key version so that it uses the new disk layout we've…
  .circleci/config.yml
  .circleci/config/commands/@caches.yml
Labels: pr/no-changelog

#13398 UI/ Double horizontal bar charts
  ui/app/components/clients/horizontal-bar-charts.js
  ui/app/styles/components/horizontal-bar-charts.scss
  ui/app/styles/core.scss
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/horizontal-bar-charts.hbs
  ui/app/templates/components/clients/total-client-usage.hbs
Labels: ui, pr/no-changelog

#13435 Add paths filter doc
  website/content/docs/enterprise/replication.mdx
  website/public/img/replication-overview.png
  website/public/img/vault-mount-filter-7.png
Labels: docs-cherrypick, pr/no-changelog

#10249 Add allowed_uri_sans_template
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_roles_test.go
  changelog/10249.txt
  website/content/api-docs/secret/pki.mdx
Labels: ecosystem, secret/pki

#13428 Fix for `main`: Add vault revision to --version cmd
  .github/workflows/build.yml
  .release/ci.hcl
  Makefile
  sdk/version/version.go
Labels: pr/no-changelog

#13372 Update openshift.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
Labels: docs, pr/no-changelog

#13446 Fix for `1.7.x`: Add vault revision to --version cmd
  .github/workflows/build.yml
  Makefile
  sdk/version/version.go
  vendor/github.com/hashicorp/vault/sdk/version/version.go
Labels: pr/no-changelog

#13454 Update docs with new images
  website/content/docs/concepts/identity.mdx
  website/public/img/vault-identity-doc-1.png
  website/public/img/vault-identity-doc-4.png
  website/public/img/vault-identity-doc-5.png
Labels: docs-cherrypick, pr/no-changelog

#13445 Fix for `1.6.x`: Add vault revision to --version cmd
  .circleci/Makefile
  .circleci/config.yml
  .github/workflows/build.yml
  Makefile
  sdk/version/version.go
Labels: pr/no-changelog

#13449 auth/github: document organization id param
  website/content/api-docs/auth/github.mdx
Labels: pr/no-changelog

#13441 website: Update Nomad-related text
  website/content/docs/secrets/nomad.mdx
Labels: docs-cherrypick, website, pr/no-changelog

#13458 website: Disable alert banner
  website/data/alert-banner.js
Labels: docs-cherrypick, website, pr/no-changelog

#13457 auth/gcp: update to v0.11.3
  go.mod
  go.sum
Labels: pr/no-changelog

#13463 Move KmsLibrary code to the ent side of config parsing
  command/server/config.go
  command/server/config_oss_test.go
  command/server/config_test_helpers.go
Labels: pr/no-changelog

#13461 Splitting backport-asst GH action
  .github/workflows/backport-docs.yml
  .github/workflows/backport.yml
Labels: pr/no-changelog

#13464 Backport 1.9.x: auth/gcp: update to v0.11.3 (#13457)
  go.mod
  go.sum
Labels: backport

#13123 feat(website): versioned-docs
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/api-docs/[[...page]].jsx
  website/pages/docs/[[...page]].jsx
  website/pages/intro/[[...page]].jsx
Labels: pr/no-changelog, backport/website

#13468 Replace '-' with ':' when listing certificate serial numbers
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/util.go
Labels: pr/no-changelog

#13339 add `entity-alias` parameter description
  website/content/docs/commands/token/create.mdx
Labels: docs, pr/no-changelog

#10873 Update index.mdx
  website/content/docs/secrets/databases/index.mdx
Labels: docs/learn, pr/no-changelog

#12804 adjustment of order of options
  website/content/docs/enterprise/license/autoloading.mdx
Labels: docs, pr/no-changelog

#13327 Upgrade guidance updates from VLT-172
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/docs/internals/replication.mdx
  website/content/docs/upgrading/index.mdx
Labels: pr/no-changelog, backport/website

#13345 Fix typo in policies.mdx
  website/content/docs/concepts/policies.mdx
Labels: docs-cherrypick, pr/no-changelog

#11629 Update entity-alias.mdx
  website/content/api-docs/secret/identity/entity-alias.mdx
Labels: docs, pr/no-changelog, backport/website

#12344 Improve databases documentation
  website/content/api-docs/secret/databases/cassandra.mdx
  website/content/api-docs/secret/databases/elasticdb.mdx
  website/content/api-docs/secret/databases/hanadb.mdx
  website/content/api-docs/secret/databases/index.mdx
  website/content/api-docs/secret/databases/influxdb.mdx
  website/content/api-docs/secret/databases/mongodb.mdx
  website/content/api-docs/secret/databases/mongodbatlas.mdx
  website/content/api-docs/secret/databases/mssql.mdx
  website/content/api-docs/secret/databases/mysql-maria.mdx
  website/content/api-docs/secret/databases/oracle.mdx
  website/content/api-docs/secret/databases/postgresql.mdx
  website/content/api-docs/secret/databases/redshift.mdx
  website/content/api-docs/secret/databases/snowflake.mdx
Labels: pr/no-changelog, backport/website

#13482 One small diff between ENT and OSS managed key config
  vault/logical_system.go
Labels: pr/no-changelog

#13483 Fixes some flaky enterprise tests
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/ssh-test.js
Labels: ui, pr/no-changelog

#13415 add tencentCloud Secrets&Auth Plugins
  website/content/docs/plugin-portal.mdx
Labels: pr/no-changelog, backport/website

#13135 fix consul tls error checking
  physical/consul/consul.go
Labels: pr/no-changelog

#13475 Adding upgrade note about 1.7.8 go version
  website/content/docs/upgrading/upgrade-to-1.7.x.mdx
  website/data/version.js
Labels: pr/no-changelog, backport/website

#13496 Fiddling with changelog formatting
  changelog/13024.txt
  changelog/13367.txt
Labels: pr/no-changelog

#13488 fix(backport-docs): always run 2nd step
  .github/workflows/backport-docs.yml
Labels: pr/no-changelog

#13492 auth/oidc: update plugin to v0.11.4
  changelog/13492.txt
  go.mod
  go.sum
Labels: backport/1.9.x

#13451 docs: add a note regarding the backend => storage config key aliasing
  website/content/docs/upgrading/upgrade-to-0.7.0.mdx
Labels: docs, pr/no-changelog, backport/website

#13491 Update example code links, remove unneeded comments
  README.md
  api/README.md
  website/content/api-docs/libraries.mdx
  website/content/docs/auth/approle.mdx
  website/content/docs/auth/aws.mdx
  website/content/docs/auth/azure.mdx
  website/content/docs/auth/gcp.mdx
  website/content/docs/auth/kubernetes.mdx
  website/content/docs/concepts/auth.mdx
Labels: pr/no-changelog, backport/website

#13470 website: Upgrade <Subnav /> & <ProductDownloadsPage />
  website/package-lock.json
  website/package.json
Labels: website, pr/no-changelog, backport/website

#13516 fix: algolia-index CircleCI test
  .circleci/config.yml
  .circleci/config/jobs/algolia-index.yml
Labels: pr/no-changelog, backport/website

#13509 update vault and auth submodules to api v1.3.1
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  go.mod
Labels: pr/no-changelog

#13524 Add enterprise downloads page
  website/components/downloads-props/img/vault-logo.svg
  website/components/downloads-props/index.jsx
  website/pages/downloads/enterprise.jsx
  website/pages/downloads/index.jsx
  website/pages/downloads/style.module.css
Labels: website, backport/website
