Repository hashicorp/vault, pull requests merged in 2021-05, with the labels that each got.

#11506 Use correct mount accessor when refreshing external group memberships
  changelog/11506.txt
  vault/expiration.go
  vault/external_tests/identity/identity_test.go
  vault/identity_store_util.go
  vault/request_handling.go
Labels: backport

#11496 Add to the contribution guidelines.
  CONTRIBUTING.md
Labels: docs-cherrypick

#11518 docs: add missing csi mount config
  website/content/docs/platform/k8s/csi/configurations.mdx
Labels: docs-cherrypick

#11521 disable alert banner
  website/data/alert-banner.js
Labels: docs-cherrypick

#11524 Fix Broken Link to FF3-1 Tweak Details
  website/content/docs/secrets/transform/index.mdx
Labels: docs, docs-cherrypick

#11523 Update UI audit dependencies
  ui/lib/core/addon/components/ttl-picker.js
  ui/lib/core/addon/components/ttl-picker2.js
  ui/lib/core/package.json
  ui/package.json
  ui/yarn.lock
Labels: ui

#11529 docs: remove duplicate config from csi
  website/content/docs/platform/k8s/csi/configurations.mdx
Labels: docs-cherrypick

#11535 Update Try Cloud CTAs to go direct to the portal
  website/components/subnav/index.jsx
  website/pages/home/index.jsx
Labels: docs-cherrypick, website

#11538 Document the `sync` option for revoke/revoke-prefix.
  website/content/api-docs/system/leases.mdx
  website/content/docs/commands/lease/revoke.mdx
Labels: docs-cherrypick

#11500 Updated code mirror component for consistency
  changelog/11500.txt
  ui/app/components/json-editor.js
  ui/app/models/role-aws.js
  ui/app/templates/components/console/log-json.hbs
  ui/app/templates/components/control-group-success.hbs
  ui/app/templates/components/json-editor.hbs
  ui/app/templates/components/secret-edit-display.hbs
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/sign.hbs
  ui/app/templates/components/transit-key-action/verify.hbs
  ui/app/templates/partials/form-field-from-model.hbs
  ui/app/templates/partials/secret-form-show.hbs
  ui/app/templates/partials/tools/unwrap.hbs
  ui/app/templates/partials/tools/wrap.hbs
  ui/app/templates/vault/cluster/policies/create.hbs
  ui/app/templates/vault/cluster/policy/edit.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/tests/integration/components/json-editor-test.js
  ui/tests/pages/components/json-editor.js
Labels: ui

#11532 UI/database mysql
  changelog/11532 | MySQL Database UI.txt
  ui/app/components/database-connection.js
  ui/app/components/database-role-setting-form.js
  ui/app/models/database/connection.js
  ui/app/serializers/database/connection.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/integration/components/database-role-setting-form-test.js
Labels: ui

#11442 UI/okta duo push notification
  changelog/11442.txt
  ui/app/components/auth-form.js
  ui/app/styles/core/message.scss
  ui/app/templates/components/auth-form-options.hbs
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-jwt.hbs
  ui/lib/core/addon/components/alert-inline.js
  ui/tests/acceptance/auth-test.js
Labels: ui

#11263 Add functional to logical description
  website/content/docs/concepts/response-wrapping.mdx
Labels: docs-cherrypick

#11587 website: add redirect for /trial
  website/redirects.next.js
Labels: docs-cherrypick, website

#11586 UI: Regex validation on transform templates
  changelog/11586.txt
  ui/app/components/regex-validator.hbs
  ui/app/components/regex-validator.js
  ui/app/models/transform/template.js
  ui/app/styles/components/regex-validator.scss
  ui/app/styles/core.scss
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/tests/integration/components/regex-validator-test.js
Labels: ui

#11595 Skip flaky control group test
  ui/tests/acceptance/enterprise-control-groups-test.js
Labels: ui

#11597 Fix: link on database role item goes to correct URL
  changelog/11597.txt
  ui/app/templates/components/database-list-item.hbs
Labels: backport, ui

#11599 Backport 1.7.2: UI database role item link goes to correct URL (#11597)
  changelog/11597.txt
  ui/app/templates/components/database-list-item.hbs
Labels: ui

#11585 Check ErrPluginStaticUnsupported for fallback to RotateRootCredentials
  builtin/logical/database/version_wrapper.go
  builtin/logical/database/version_wrapper_test.go
Labels: bug, secret/database

#11602 Backport 1.7.2: agent/cert: properly return the cached client on AuthClient (#11576)
  changelog/11576.txt
  command/agent/auth/cert/cert.go
  command/agent/auth/cert/cert_test.go
  command/agent/auth/cert/test-fixtures/keys/cert.pem
  command/agent/auth/cert/test-fixtures/keys/key.pem
  command/agent/auth/cert/test-fixtures/keys/pkioutput
  command/agent/auth/cert/test-fixtures/root/pkioutput
  command/agent/auth/cert/test-fixtures/root/root.crl
  command/agent/auth/cert/test-fixtures/root/rootcacert.pem
  command/agent/auth/cert/test-fixtures/root/rootcakey.pem
Labels: core/agent

#11596 core: updates to password policy generator
  changelog/11596.txt
  vault/dynamic_system_view.go
  vault/dynamic_system_view_test.go
  vault/password_policy_util.go
Labels: backport

#11603 Backport 1.7: Fix plugin password policy bug not supporting namespaces
  changelog/11596.txt
  vault/dynamic_system_view.go
  vault/dynamic_system_view_test.go
  vault/password_policy_util.go
Labels: backport

#11604 Backport 1.6: Fix plugin password policy bug not supporting namespaces
  changelog/11596.txt
  vault/dynamic_system_view.go
  vault/dynamic_system_view_test.go
  vault/password_policy_util.go
Labels: backport

#11605 Backport 1.7: Add ServerName to Vault Agent template config
  changelog/11288.txt
  command/agent/template/template.go
Labels: backport

#11495 Add support for templated values in SSH CA DefaultExtensions.
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_roles.go
  builtin/logical/ssh/path_sign.go
  changelog/11495.txt
Labels: secret/ssh, waiting-for-response

#11635 Backport 1.6.x UI: Add null check before getting userRootNamespace from storage
  changelog/11094.txt
  ui/app/routes/vault/cluster.js
Labels: ui

#11633 Backport 1.6.x: UI/namespace bug (#11182)
  changelog/11182.txt
  ui/app/components/namespace-link.js
Labels: ui

#11634 Backport 1.6.x: Bug fix namespace issues (#11186)
  ui/app/components/namespace-picker.js
Labels: ui

#11637 Backport 1.7.x: Add ability to customize some timeouts in MongoDB database plugin
  builtin/logical/database/path_rotate_credentials.go
  changelog/11600.txt
  plugins/database/mongodb/connection_producer.go
  plugins/database/mongodb/connection_producer_test.go
  plugins/database/mongodb/mongodb.go
Labels: backport

#11489 Minor fix to the raft docs
  website/content/api-docs/system/storage/raft.mdx
Labels: docs-cherrypick

#11639 Backport (1.7.x): #11638 - AWS Auth: Update error message to include underlying error
  builtin/credential/aws/path_login.go
  changelog/11638.txt
Labels: backport

#11641 UI/fix identity model
  changelog/11641.txt
  ui/app/models/identity/group.js
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/identity/item-details.hbs
  ui/app/templates/components/identity/item-groups.hbs
  ui/app/templates/components/identity/item-members.hbs
  ui/app/templates/components/identity/item-metadata.hbs
  ui/app/templates/components/identity/item-parent-groups.hbs
  ui/app/templates/components/identity/item-policies.hbs
  ui/app/templates/vault/cluster/access/identity/show.hbs
  ui/tests/acceptance/access/identity/_shared-tests.js
  ui/tests/pages/components/identity/edit-form.js
Labels: backport, bug, ui

#11642 Backport 1.7.2: UI fix identity model (#11641)
  changelog/11641.txt
  ui/app/models/identity/group.js
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/identity/item-details.hbs
  ui/app/templates/components/identity/item-groups.hbs
  ui/app/templates/components/identity/item-members.hbs
  ui/app/templates/components/identity/item-metadata.hbs
  ui/app/templates/components/identity/item-parent-groups.hbs
  ui/app/templates/components/identity/item-policies.hbs
  ui/app/templates/vault/cluster/access/identity/show.hbs
  ui/tests/acceptance/access/identity/_shared-tests.js
  ui/tests/pages/components/identity/edit-form.js
Labels: bug, ui

#11640 [Website] Add HashiConf info to alert banner
  website/data/alert-banner.js
Labels: docs-cherrypick, website

#11618 Update policies.mdx
  website/content/docs/concepts/policies.mdx
Labels: docs, docs-cherrypick

#11648 chore(website): 'overview' nav item links to homepage
  website/data/subnav.js
Labels: docs-cherrypick, website

#11520 Backport 11259 changes 1.7.x
  builtin/logical/pki/cert_util.go
  changelog/11259.txt
Labels: backport

#11530 KV 2 Toolbar delete redesign
  changelog/11530.txt
  ui/app/adapters/secret-v2-version.js
  ui/app/components/secret-delete-menu.js
  ui/app/components/secret-edit.js
  ui/app/components/secret-version-menu.js
  ui/app/styles/components/masked-input.scss
  ui/app/styles/components/modal.scss
  ui/app/templates/components/secret-delete-menu.hbs
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/components/secret-version-menu.hbs
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/pages/secrets/backend/kv/show.js
Labels: ui

#11647 Tokenutil: Perform num uses check earlier
  builtin/credential/approle/backend_test.go
  changelog/11647.txt
  sdk/helper/tokenutil/tokenutil.go
  vendor/github.com/hashicorp/vault/sdk/helper/tokenutil/tokenutil.go
Labels: auth/approle

#11592 website: add Exoscale plugins to the list of partner plugins
  website/content/docs/plugin-portal.mdx
Labels: docs, docs-cherrypick

#11679 docs: small fixes in k8s docs
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs, docs-cherrypick, k8s

#11685 Update website version
  website/data/version.js
Labels: docs-cherrypick

#11686 Fix ent version filtering on downloads page
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, website

#11644 Typos
  website/content/docs/platform/k8s/csi/index.mdx
Labels: docs-cherrypick

#11655 Changes role/roles
  website/content/docs/secrets/terraform.mdx
Labels: docs-cherrypick

#11672 UI/tools partial
  changelog/11672.txt
  ui/app/components/tool-actions-form.js
  ui/app/components/tool-hash.js
  ui/app/components/tool-lookup.js
  ui/app/components/tool-random.js
  ui/app/components/tool-rewrap.js
  ui/app/components/tool-unwrap.js
  ui/app/components/tool-wrap.js
  ui/app/templates/components/tool-actions-form.hbs
  ui/app/templates/components/tool-hash.hbs
  ui/app/templates/components/tool-lookup.hbs
  ui/app/templates/components/tool-random.hbs
  ui/app/templates/components/tool-rewrap.hbs
  ui/app/templates/components/tool-unwrap.hbs
  ui/app/templates/components/tool-wrap.hbs
  ui/app/templates/partials/tools/lookup.hbs
Labels: ui

#11700 Replace auth-form/* partials
  ui/app/components/auth-form.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/partials/auth-form/github.hbs
  ui/app/templates/partials/auth-form/ldap.hbs
  ui/app/templates/partials/auth-form/okta.hbs
  ui/app/templates/partials/auth-form/radius.hbs
  ui/app/templates/partials/auth-form/token.hbs
  ui/app/templates/partials/auth-form/userpass.hbs
  ui/app/templates/partials/userpass-form.hbs
Labels: ui

#11702 UI/partials replace partials/role-ssh partials/role-aws partials/role-pki
  ui/app/templates/components/role-aws-edit.hbs
  ui/app/templates/components/role-pki-edit.hbs
  ui/app/templates/components/role-ssh-edit.hbs
  ui/app/templates/partials/role-aws/form.hbs
  ui/app/templates/partials/role-aws/popup-menu.hbs
  ui/app/templates/partials/role-aws/show.hbs
  ui/app/templates/partials/role-pki/form.hbs
  ui/app/templates/partials/role-pki/popup-menu.hbs
  ui/app/templates/partials/role-pki/show.hbs
  ui/app/templates/partials/role-ssh/form.hbs
  ui/app/templates/partials/role-ssh/popup-menu.hbs
  ui/app/templates/partials/role-ssh/show.hbs
  ui/app/templates/partials/secret-list/aws-role-item.hbs
  ui/app/templates/partials/secret-list/pki-role-item.hbs
  ui/app/templates/partials/secret-list/ssh-role-item.hbs
Labels: ui

#11705 UI unseal screen updates
  changelog/11705.txt
  ui/app/controllers/vault/cluster/unseal.js
  ui/app/styles/components/empty-state.scss
  ui/app/styles/components/splash-page.scss
  ui/app/templates/vault/cluster/unseal.hbs
  ui/lib/core/addon/components/empty-state.js
  ui/lib/core/addon/components/shamir-flow.js
  ui/lib/core/addon/templates/components/shamir-flow.hbs
Labels: backport, ui

#11709 Backport 1.7.3: UI message on unseal fail due to license
  changelog/11705.txt
  ui/app/controllers/vault/cluster/unseal.js
  ui/app/styles/components/empty-state.scss
  ui/app/styles/components/splash-page.scss
  ui/app/templates/vault/cluster/unseal.hbs
  ui/lib/core/addon/components/empty-state.js
  ui/lib/core/addon/components/shamir-flow.js
  ui/lib/core/addon/templates/components/shamir-flow.hbs
Labels: backport, ui

#11680 Update cluster status partial to component
  changelog/11680.txt
  ui/app/components/auth-info.js
  ui/app/components/cluster-info.js
  ui/app/components/status-menu.js
  ui/app/templates/components/auth-info.hbs
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/components/status-menu.hbs
  ui/app/templates/partials/status/user.hbs
Labels: ui

#11696 api/client: provide the ability to set a logger on retryablehttp.Client
  api/client.go
  api/client_test.go
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  vendor/github.com/hashicorp/go-hclog/intlogger.go
  vendor/github.com/hashicorp/go-hclog/logger.go
  vendor/github.com/hashicorp/vault/api/client.go
  vendor/github.com/hashicorp/vault/api/go.mod
  vendor/github.com/hashicorp/vault/api/go.sum
  vendor/modules.txt
Labels: core/api

#11561 Clarify the accuracy of estimated encryption counts wrt cluster nodes
  website/content/api-docs/system/key-status.mdx
Labels: docs-cherrypick

#11708 UI: reset database json fields
  changelog/11708.txt
  ui/app/models/database/connection.js
  ui/app/models/database/role.js
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/tests/integration/components/form-field-test.js
  ui/tests/pages/components/form-field.js
Labels: ui

#11724 Update architecture.mdx
  website/content/docs/internals/architecture.mdx
Labels: docs-cherrypick

#11725 Update security.mdx
  website/content/docs/internals/security.mdx
Labels: docs-cherrypick
