Repository hashicorp/vault, pull requests merged in 2021-10, with the labels that each got.

#12677 [VAULT-3472] Cap Client `id_token_ttl` field to associated Key's `verification_ttl`
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#12697 docs: add plugin limits and lifecycle sections
  website/content/docs/internals/limits.mdx
  website/content/docs/internals/plugins.mdx
Labels: docs-cherrypick, pr/no-changelog

#12413 Upgrade pq to fix connection failure cleanup bug (v1.8.0 => v1.10.3)
  changelog/12413.txt
  go.mod
  go.sum
Labels: ecosystem

#12646 Edit form should be valid by default
  changelog/12646.txt
  ui/app/components/generated-item.js
Labels: ui, backport, bug

#12691 Fix a Deadlock on HA leadership transfer
  changelog/12691.txt
  vault/request_forwarding.go
Labels: backport

#12541 UI/ PKI UI Redesign
  changelog/12541.txt
  ui/app/adapters/pki-ca-certificate.js
  ui/app/helpers/parse-pki-cert.js
  ui/app/models/pki-ca-certificate.js
  ui/app/models/pki-certificate.js
  ui/app/serializers/pki-certificate.js
  ui/app/styles/components/info-table-row.scss
  ui/app/templates/components/config-pki-ca.hbs
  ui/app/templates/components/pki-cert-show.hbs
  ui/lib/core/addon/helpers/date-format.js
  ui/package-lock.json
  ui/package.json
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
  ui/tests/integration/helpers/date-format-test.js
  ui/tests/pages/components/config-pki-ca.js
  ui/yarn.lock
Labels: ui

#12732 Backport 1.8.4: UI Auth method role edit form should be valid by default (#12646)
  changelog/12646.txt
  ui/app/components/generated-item.js
Labels: ui, bug

#12733 builtin/logical/consul: fix dropped test error
  builtin/logical/consul/backend_test.go
Labels: pr/no-changelog

#12709 Update builder base image
  .circleci/config.yml
  .circleci/config/@build-release.yml
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
Labels: pr/no-changelog

#11780 Add support for ed25519
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_roles.go
  changelog/11780.txt
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
  ui/app/models/pki-ca-certificate.js
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki, cryptosec

#12740 Add links to vault-examples repo
  README.md
  api/README.md
  website/content/api-docs/libraries.mdx
Labels: docs-cherrypick, pr/no-changelog

#12748 Updating SDK version for 1.8.4
  sdk/version/version_base.go
Labels: pr/no-changelog

#12751 Updating website for 1.8.4
  website/data/version.js
Labels: docs-cherrypick, pr/no-changelog

#12904 UI/Remove token_type field from token auth method
  changelog/12904.txt
  ui/app/components/auth-config-form/options.js
  ui/app/helpers/supported-managed-auth-backends.js
  ui/app/models/auth-method.js
  ui/app/templates/components/auth-config-form/options.hbs
  ui/app/templates/vault/cluster/access/method/section.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/settings/auth/configure/section.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: ui

#12964 On bar chart selection replace search component with HTML
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/history.hbs
  ui/lib/core/addon/components/search-select.js
Labels: ui, pr/no-changelog

#12955 UI/OIDC namespace support
  ui/app/components/nav-header.js
  ui/app/components/token-expire-warning.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/controllers/vault/cluster/oidc-provider-ns.js
  ui/app/controllers/vault/cluster/oidc-provider.js
  ui/app/mixins/cluster-route.js
  ui/app/router.js
  ui/app/routes/vault/cluster/oidc-provider-ns.js
  ui/app/routes/vault/cluster/oidc-provider.js
  ui/app/styles/core/forms.scss
  ui/app/templates/vault/cluster/auth.hbs
  ui/app/templates/vault/cluster/oidc-provider-ns.hbs
  ui/app/templates/vault/cluster/oidc-provider.hbs
Labels: ui, backport, pr/no-changelog

#12971 Backport 1.9.0: On bar chart selection replace search component with HTML (#12964)
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/history.hbs
  ui/lib/core/addon/components/search-select.js
Labels: ui, pr/no-changelog

#12974 Backport 1.9.0: Added date range to client count csv filename (#12960)
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/history.hbs
Labels: ui, pr/no-changelog

#12977 Break line if words are long in flash messages
  ui/app/styles/components/global-flash.scss
Labels: ui, pr/no-changelog

#12967 Backport 1.9.0: UI/Remove token_type field from token auth method (#12904)
  changelog/12904.txt
  ui/app/components/auth-config-form/options.js
  ui/app/helpers/supported-managed-auth-backends.js
  ui/app/models/auth-method.js
  ui/app/templates/components/auth-config-form/options.hbs
  ui/app/templates/vault/cluster/access/method/section.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/settings/auth/configure/section.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: ui, pr/no-changelog

#12966 Backport 1.9.0: UI/ Add PostgreSQL DB (#12945)
  changelog/12945.txt
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/transformation-edit.hbs
  ui/app/utils/database-helpers.js
  ui/lib/core/addon/components/confirmation-modal.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
Labels: ui

#12973 Fix reported error - what is client
  website/content/docs/concepts/client-count.mdx
Labels: docs, docs-cherrypick, pr/no-changelog
