Repository hashicorp/vault, pull requests merged in 2021-09, with the labels that each got.

#12472 Document some missing http status codes.
  website/content/api-docs/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#12477 adding ARN in description
  website/content/docs/configuration/seal/awskms.mdx
Labels: docs-cherrypick, pr/no-changelog

#12298 Clarify on overview page that audit is default replicated
  website/content/api-docs/system/audit.mdx
  website/content/docs/audit/index.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12474 command: fix dropped test error
  command/debug_test.go
Labels: pr/no-changelog

#12480 Make necessary OSS changes for contexts in quotas
  vault/core_util.go
  vault/request_handling.go
Labels: pr/no-changelog

#11198 fix: update injector resources requirements
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs-cherrypick

#11984 UI: Show day of month instead of day of year in the expiration warning dialog
  changelog/11984.txt
  ui/app/templates/components/auth-info.hbs
Labels: ui, backport, bug

#12484 Fix isues 12397
  website/content/api-docs/system/auth.mdx
  website/content/docs/commands/auth/tune.mdx
Labels: docs-cherrypick, pr/no-changelog

#12482 Remove deprecated reauth function from docs
  website/content/docs/agent/autoauth/methods/jwt.mdx
Labels: docs-cherrypick, pr/no-changelog

#12476 fix(website): `start` script reloads app on save
  website/package.json
Labels: docs-cherrypick, website, pr/no-changelog

#12464 KV custom metadata test coverage
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-edit-metadata.hbs
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/lib/core/addon/templates/components/info-table-row.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/integration/components/secret-edit-test.js
  ui/tests/pages/secrets/backend/kv/edit-secret.js
Labels: ui, pr/no-changelog

#12488 Backport 1.8.x: UI Show day of month instead of day of year in the expiration warning
  changelog/11984.txt
  ui/app/templates/components/auth-info.hbs
Labels: ui, bug

#12478 UI: Fix missing nav links on namespace login
  changelog/12478.txt
  ui/app/routes/vault/cluster.js
  ui/app/templates/vault/cluster.hbs
Labels: ui, backport, bug

#12489 Backport 1.8.x: UI Fix missing nav links on namespace login (#12478)
  changelog/12478.txt
  ui/app/routes/vault/cluster.js
  ui/app/templates/vault/cluster.hbs
Labels: ui, backport, bug

#12481 feature: OIDC discovery endpoint
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#12437 UI/bar chart horizontal
  changelog/12437.txt
  ui/app/styles/components/bar-chart.scss
  ui/app/styles/core.scss
  ui/lib/core/addon/components/bar-chart.js
  ui/lib/core/addon/templates/components/bar-chart.hbs
  ui/lib/core/app/components/bar-chart.js
  ui/lib/core/stories/bar-chart.md
  ui/lib/core/stories/bar-chart.stories.js
  ui/package.json
  ui/tests/integration/components/bar-chart-test.js
  ui/yarn.lock
Labels: ui

#12500 Update kv input documentation with edge case
  website/content/docs/commands/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#12333 Update examples.mdx
  website/content/docs/platform/k8s/csi/examples.mdx
Labels: pr/no-changelog

#12504 audit page tweaks based on customer feedback
  website/content/docs/commands/audit/enable.mdx
Labels: docs, docs-cherrypick

#12495 docs: provide clarifications for github auth method and ssh secrets engine
  website/content/docs/auth/github.mdx
  website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
Labels: docs, auth/github, docs-cherrypick, pr/no-changelog

#12459 docs: update packaging
  website/content/docs/configuration/entropy-augmentation.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/hsm/index.mdx
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/secrets/key-management/index.mdx
  website/content/docs/secrets/transform/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#10256 Update Auto Unseal info to say KMS instead of EKS
  website/content/docs/platform/k8s/helm/run.mdx
Labels: pr/no-changelog

#12516 Update installation.mdx
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs-cherrypick, pr/no-changelog

#12518 Update 1.8 upgrade guide
  website/content/docs/upgrading/upgrade-to-1.8.0.mdx
Labels: docs-cherrypick, pr/no-changelog

#12521 Update CODEOWNERS
  CODEOWNERS
Labels: pr/no-changelog

#12506 docs: k8s auth issuer lookup
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
  website/content/docs/platform/k8s/csi/index.mdx
Labels: docs, auth/k8s, docs-cherrypick, pr/no-changelog

#12501 Add link to integrated storage docs page for learn tutorial
  website/content/api-docs/system/storage/raftautopilot.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12527 docs: update packaging
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/enterprise/replication.mdx
Labels: docs-cherrypick, pr/no-changelog

#12503 add example for secret tuning
  website/content/docs/commands/secrets/tune.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12531 identity: fix identity token introspect doc
  website/content/api-docs/secret/identity/tokens.mdx
Labels: docs, pr/no-changelog

#10679 Add link to go-discover README to raft documentation
  website/content/docs/configuration/storage/raft.mdx
Labels: waiting-for-response, pr/no-changelog

#12532 Fixing a flaky test TestQuotas_RateLimitQuota_ExemptPaths
  vault/external_tests/quotas/quotas_test.go
Labels: pr/no-changelog

#12529 UI: Remove options used only on kv-v2 from mount call
  ui/app/serializers/secret-engine.js
Labels: ui, pr/no-changelog

#12534 vault-agent: copy values retrieved from bolt
  changelog/12534.txt
  command/agent/cache/cacheboltdb/bolt.go
Labels: backport, core/agent

#10651 Fix typo in lease renew documentation
  website/content/docs/commands/lease/renew.mdx
Labels: waiting-for-response, pr/no-changelog

#12528 Added Artifactory secrets plugin
  website/content/docs/plugin-portal.mdx
Labels: pr/no-changelog

#12550 Bug fix: allow forward slash in paths for delete menu
  changelog/12550.txt
  ui/app/components/secret-delete-menu.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui, backport

#12552 Backport: 1.8.x fix delete menu on KV with permissions
  changelog/12550.txt
  ui/app/components/secret-delete-menu.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui

#12525 feature: OIDC keys endpoint
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#12498 KV: handle permissions on config and mount/sys when enabling a KV engine
  ui/app/adapters/secret-engine.js
  ui/app/components/mount-backend-form.js
  ui/app/controllers/vault/cluster/settings/mount-secret-backend.js
  ui/app/models/secret-engine.js
  ui/app/routes/vault/cluster/secrets/backend/configuration.js
  ui/app/serializers/secret-engine.js
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/app/templates/vault/cluster/settings/mount-secret-backend.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/pages/settings/mount-secret-backend.js
Labels: ui, pr/no-changelog

#12561 identity: fix bug and increase logging for jwks cache control max age test
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#12557 Upgrade go-limiter to v0.7.1 to fix build failure in go1.17.1
  go.mod
  go.sum
Labels: pr/no-changelog

#12542 Some docs notes (seal migration + go discover link)
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/storage/raft.mdx
Labels: docs-cherrypick, pr/no-changelog

#12425 Expose secret_id_accessor as WrappedAccessor when wrapping secret-id creation.
  changelog/12425.txt
  sdk/helper/wrapping/wrapinfo.go
  vault/external_tests/approle/wrapped_secretid_test.go
  vault/wrapping.go
Labels: waiting-for-response

#12555 Backport 1.7.x: Handle api explorer routing error (#12354)
  changelog/12354.txt
  ui/app/components/console/ui-panel.js
Labels: ui

#12573 docs: vault-k8s 0.13.0 and vault-helm 0.16.0
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12572 Update token renew docs
  command/token_renew.go
  website/content/api-docs/auth/token.mdx
  website/content/docs/commands/token/renew.mdx
Labels: docs-cherrypick, pr/no-changelog

#9621 Update example responses for /sys/seal-status
  website/content/api-docs/system/seal-status.mdx
Labels: pr/no-changelog

#12574 OIDC provider: show success message in CLI
  vault/identity_store_oidc_provider.go
Labels: pr/no-changelog

#12578 Add code snippet to demonstrate GCP auth in Go
  website/content/docs/auth/gcp.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12588 Fix build tag
  command/config/validate_listener.go
Labels: pr/no-changelog

#12593 namespace api docs typos
  website/content/api-docs/system/namespaces.mdx
Labels: docs-cherrypick, pr/no-changelog

#12587 Vault documentation: added browser support
  website/content/docs/browser-support.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#11341 Backport pr 11161 1.7.1: Extract replication state before go routine for initQueue (#11161) - again
  builtin/logical/database/backend.go
  builtin/logical/database/rotation.go
Labels: pr/no-changelog

#12571 Revert "Update installation.mdx"
  website/content/docs/platform/servicenow/installation.mdx
Labels: pr/no-changelog

#12611 Update telemetry docs to include HA forwarding metrics.
  website/content/docs/internals/telemetry.mdx
Labels: docs-cherrypick, pr/no-changelog

#12608 Fix client.go
  api/client.go
Labels: pr/no-changelog

#12522 Add additional info on v1 KV engine
  website/content/docs/concepts/dev-server.mdx
Labels: pr/no-changelog

#12530 Docs: Seal pkcs11 updated example with actual hex slot reference and …
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: pr/no-changelog

#12615 fix writing back the Filename into unusedKeys in ParseConfig
  command/server/config.go
Labels: pr/no-changelog

#11192 Docs: Add AWS secret rotate-root cli
  website/content/docs/secrets/aws.mdx
Labels: docs, secret/aws, pr/no-changelog

#12585 Update production hardening guidelines
  website/content/guides/operations/production.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12567 docs : Update GoLang library link in docs, typo
  website/content/api-docs/libraries.mdx
Labels: pr/no-changelog

#12636 test: pin docker image on postgres to 13.4-buster
  builtin/logical/database/backend_test.go
  builtin/logical/database/rotation_test.go
  plugins/database/postgresql/postgresql_test.go
Labels: pr/no-changelog

#12632 Use durations for ID and access token TTLs
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#12623 Adds additional OIDC discovery metadata
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#12538 Adds OIDC Authorization Endpoint to OIDC providers
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_test.go
  vault/identity_store_schema.go
  vault/identity_store_structs.go
  vault/identity_store_util.go
  vault/logical_system_test.go
  vault/policy_store.go
  vault/router.go
Labels: pr/no-changelog

#12628 Update flaky expiration test
  vault/expiration_test.go
Labels: pr/no-changelog

#12619 Fix typo in command
  website/content/docs/auth/kubernetes.mdx
Labels: pr/no-changelog

#12627 move from static sleep to timed loop waiting for lease revocation
  vault/expiration_test.go
Labels: pr/no-changelog

#12622 UI/bar chart updates
  changelog/12622.txt
  ui/lib/core/addon/components/bar-chart.js
  ui/lib/core/addon/templates/components/bar-chart.hbs
  ui/tests/integration/components/bar-chart-test.js
Labels: ui

#12630 [VAULT-3248] Check api and sdk dirs in go_test
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  api/go.sum
Labels: pr/no-changelog

#12653 Update the SDK version for 1.7.5
  sdk/version/version_base.go
Labels: pr/no-changelog

#12654 Updating SDK version for 1.8.3
  sdk/version/version_base.go
Labels: pr/no-changelog

#12657 SDK bump for 1.7.5
  go.mod
  vendor/github.com/hashicorp/vault/sdk/version/version_base.go
  vendor/modules.txt
Labels: pr/no-changelog

#12652 Add missing read unlock calls in transit backend code
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_cache_config.go
  changelog/12418.txt
Labels: pr/no-changelog

#12655 Documentation update: Added tuner parameters to the Sensitive information section
  website/content/docs/audit/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#12663 UI/kv creation time
  changelog/12663.txt
  ui/app/styles/components/info-table-row.scss
  ui/app/styles/components/list-item-row.scss
  ui/app/styles/components/tool-tip.scss
  ui/app/templates/components/secret-form-show.hbs
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui

#12454 docs: Remove permissive policies in Consul ACL examples
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/storage/consul.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12667 docs: updated enterprise package name
  website/content/docs/enterprise/sealwrap.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12629 Update Azure secrets engine to use MS Graph
  changelog/12629.txt
  go.mod
  go.sum
  website/content/api-docs/secret/azure.mdx
  website/content/docs/secrets/azure.mdx
Labels: docs, dependencies, secret/azure

#12664 Document transform batch reference field
  website/content/api-docs/secret/transform.mdx
Labels: pr/no-changelog

#12671 Updating website latest to 1.8.3
  website/data/version.js
Labels: docs-cherrypick, pr/no-changelog

#12626 KV search box when no list access to metadata
  changelog/12626.txt
  ui/app/components/get-credentials-card.js
  ui/app/components/secret-create-or-update.js
  ui/app/components/secret-edit.js
  ui/app/routes/vault/cluster/secrets/backend/configuration.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/metadata.js
  ui/app/templates/components/get-credentials-card.hbs
  ui/app/templates/components/input-search.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/integration/components/get-credentials-card-test.js
  ui/tests/pages/secrets/backend/kv/edit-secret.js
Labels: ui

#12676 Fix changelogs
  changelog/12008.txt
  changelog/12478.txt
Labels: pr/no-changelog

#12674 Update changelog checker
  .github/workflows/changelog-checker.yml
Labels: pr/no-changelog

#12679 Update protobuf & grpc libraries and protoc plugins
  Makefile
  go.mod
  go.sum
  helper/identity/mfa/types.pb.go
  helper/identity/mfa/types.proto
  helper/identity/types.pb.go
  helper/identity/types.proto
  helper/storagepacker/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/database_grpc.pb.go
  sdk/database/dbplugin/grpc_transport.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/database/dbplugin/v5/proto/database_grpc.pb.go
  sdk/logical/identity.pb.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_storage.go
  sdk/plugin/grpc_system.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend_grpc.pb.go
  tools/tools.go
  vault/activity/activity_log.pb.go
  vault/cluster/cluster.go
  vault/core.go
  vault/request_forwarding_rpc.go
  vault/request_forwarding_service.pb.go
  vault/request_forwarding_service_grpc.pb.go
Labels: pr/no-changelog

#12680 docs: vault-k8s-0.13.1 and vault-helm-0.16.1
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12692 Highlight that password policies are defined in a namespace
  website/content/docs/enterprise/namespaces.mdx
Labels: docs-cherrypick, pr/no-changelog

#12693 Updated documentation: added new code example and reference
  website/content/docs/concepts/auth.mdx
  website/content/docs/concepts/lease.mdx
Labels: docs-cherrypick, pr/no-changelog

#12681 Update plugin-portal.mdx
  website/content/docs/plugin-portal.mdx
Labels: docs-cherrypick, pr/no-changelog

#12695 Update CODEOWNERS
  CODEOWNERS
Labels: pr/no-changelog
