Repository hashicorp/vault, pull requests merged in 2021-08, with the labels that each got.

#12224 website: upgrade consent-manager
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, pr/no-changelog

#12240 Adding upgrade note about arm64
  website/content/docs/upgrading/upgrade-to-1.8.0.mdx
Labels: docs-cherrypick, pr/no-changelog

#12236 Recommended TOC change: Vault documentation
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#12212 UI/TTL helperEnabled/DisabledText fix
  changelog/12212.txt
  ui/app/models/database/role.js
  ui/lib/core/addon/templates/components/form-field.hbs
Labels: ui

#12149 docs: add barrier key auto-rotation to internals/rotation
  website/content/docs/internals/rotation.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12043 Add link to plugin upgrade instructions
  website/content/docs/internals/plugins.mdx
Labels: docs-cherrypick, pr/no-changelog

#11199 Add link to Learn's usage tutorial
  website/content/docs/commands/operator/usage.mdx
Labels: docs, docs-cherrypick, website

#12245 Updating go version to 1.16.6 for security fix
  .circleci/config.yml
  .circleci/config/@build-release.yml
  .circleci/config/executors/@executors.yml
  Makefile
  changelog/12245.txt
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: backport

#12246 Updating SDK version for 1.9 dev
  sdk/version/version_base.go
Labels: pr/no-changelog

#12247 Updating SDK version for 1.8.1
  sdk/version/version_base.go
Labels: pr/no-changelog

#12252 Backport 1.8.x: Cap AWS Token TTL based on Default Lease TTL (#12026)
  builtin/credential/aws/path_role.go
  builtin/credential/aws/path_role_test.go
  changelog/12026.txt
Labels: pr/no-changelog

#12256 changelog: remove 12251 entry
  changelog/12251.txt
Labels: pr/no-changelog

#12257 Backport 1.8.1: identity: allow creating a role with a non-existent key (#12251)
  vault/identity_store_oidc.go
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#12259 Replaced RNs changelog link to point to main
  website/content/docs/release-notes/1.8.0.mdx
Labels: docs-cherrypick, pr/no-changelog

#12269 update CL
  CHANGELOG.md
Labels: pr/no-changelog

#12271 Updating latest to 1.8.1 on website
  website/data/version.js
Labels: docs-cherrypick, pr/no-changelog

#12273 auth/oidc: documents redirect URI for UI login with form_post response_mode
  website/content/docs/auth/jwt/index.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12281 docs: vault-k8s and cert-manager
  website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
  website/data/docs-nav-data.json
Labels: docs, docs-cherrypick, pr/no-changelog

#12286 Master -> Main on CL links
  website/content/docs/release-notes/1.5.0.mdx
  website/content/docs/release-notes/1.6.0.mdx
  website/content/docs/release-notes/1.7.0.mdx
  website/content/docs/upgrading/upgrade-to-1.1.0.mdx
  website/content/docs/upgrading/upgrade-to-1.1.1.mdx
  website/content/docs/upgrading/upgrade-to-1.1.2.mdx
  website/content/guides/operations/production.mdx
Labels: docs-cherrypick, pr/no-changelog

#12307 Agent template static secrets docs update
  website/content/docs/agent/template.mdx
Labels: docs-cherrypick, pr/no-changelog

#12310 [Docs] Add documentation for username_template feature in AWS Secrets Engine
  website/content/api-docs/secret/aws.mdx
Labels: docs, pr/no-changelog

#12311 database/cassandra: pin bitnami/cassandra docker image to 3.11 in test
  plugins/database/cassandra/connection_producer_test.go
Labels: pr/no-changelog

#12308 [VAULT-2822] Sort client count response
  vault/activity_log.go
Labels: pr/no-changelog

#12312 Backport 1.7.x: database/cassandra: pin bitnami/cassandra docker image to 3.11 in tes…
  plugins/database/cassandra/connection_producer_test.go
Labels: pr/no-changelog

#12313 Backport 1.8.x: database/cassandra: pin bitnami/cassandra docker image to 3.11 in tes…
  plugins/database/cassandra/connection_producer_test.go
Labels: pr/no-changelog

#12316 Add AWS EC2 Auth known issue
  website/content/docs/upgrading/upgrade-to-1.8.0.mdx
Labels: docs-cherrypick

#12302 [Docs] Add code example
  website/content/docs/auth/approle.mdx
  website/content/docs/auth/aws.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12332 Add draft upgrade guide
  website/content/docs/upgrading/upgrade-to-1.9.0.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#12295 UI/StatText Component
  changelog/12295.txt
  ui/README.md
  ui/app/styles/components/stat-text.scss
  ui/app/styles/core.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/lib/core/addon/components/stat-text.js
  ui/lib/core/addon/templates/components/stat-text.hbs
  ui/lib/core/app/components/stat-text.js
  ui/lib/core/stories/stat-text.md
  ui/lib/core/stories/stat-text.stories.js
  ui/tests/integration/components/stat-text-test.js
Labels: ui

#12324 Vault Documentation: Added Glossary
  website/content/docs/glossary.mdx
  website/content/docs/internals/architecture.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#12337 docs: draft update guide for identity token roles
  website/content/docs/upgrading/upgrade-to-1.9.0.mdx
Labels: pr/no-changelog

#12296 Fix a tokenization docs link fix
  website/content/api-docs/secret/transform.mdx
Labels: docs-cherrypick, pr/no-changelog

#12266 feature: OIDC provider scope API
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#12348 UI: Allow metrics view without config read
  changelog/12348.txt
  ui/app/templates/vault/cluster/metrics/index.hbs
  ui/tests/acceptance/usage-metrics-test.js
Labels: ui, backport, bug

#12244 Docs: k8s annotations for static_secret_render_interval
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: docs-cherrypick, pr/no-changelog

#12278 Add docs for metrics from #11472.
  website/content/docs/internals/telemetry.mdx
Labels: docs-cherrypick, pr/no-changelog

#12353 Removing line about consul consistency
  website/content/docs/enterprise/consistency.mdx
Labels: docs-cherrypick, pr/no-changelog

#12297 Add agent approle method example
  website/content/docs/agent/autoauth/methods/approle.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12355 Backport1.8.x: dbplugin: fix error message in DeleteUser (#12351)
  changelog/12351.txt
  sdk/database/dbplugin/v5/grpc_client.go
Labels: pr/no-changelog

#12364 Backport 1.6.6: UI Allow metrics view without config read (#12348)
  changelog/12348.txt
  ui/app/templates/vault/cluster/metrics/index.hbs
  ui/tests/acceptance/usage-metrics-test.js
Labels: ui, bug

#12362 Backport 1.7.4: UI Allow metrics view without config read (#12348)
  changelog/12348.txt
  ui/app/templates/vault/cluster/metrics/index.hbs
  ui/tests/acceptance/usage-metrics-test.js
Labels: ui, bug

#12357 Fixed overflowing text of flash message container
  changelog/12357.txt
  ui/app/styles/components/global-flash.scss
Labels: ui

#12354 Handle api explorer routing error
  changelog/12354.txt
  ui/app/components/console/ui-panel.js
Labels: ui

#12379 Updates vault-plugin-secrets-gcp to v0.10.2
  changelog/12379.txt
  go.mod
  go.sum
Labels: backport

#12378 plugin/snowflake: update gosnowflake to v1.6.1
  changelog/12378.txt
  go.mod
  go.sum
  physical/azure/azure.go
Labels: backport

#12167 Upgrade global styles
  website/components/footer/index.jsx
  website/components/footer/style.css
  website/components/hcp-callout-section/index.jsx
  website/components/homepage-hero/index.jsx
  website/components/use-case-cta-section/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/community/index.jsx
  website/pages/community/style.css
  website/pages/community/style.module.css
  website/pages/downloads/style.module.css
  website/pages/home/content.json
  website/pages/home/index.jsx
  website/pages/home/style.css
  website/pages/not-found/index.jsx
  website/pages/print.css
  website/pages/style.css
  website/pages/use-cases/data-encryption/index.jsx
  website/pages/use-cases/identity-based-access/content.json
  website/pages/use-cases/identity-based-access/index.jsx
  website/pages/use-cases/secrets-management/content.json
  website/pages/use-cases/secrets-management/index.jsx
Labels: docs, docs-cherrypick, website, pr/no-changelog

#12389 Backport 1.8.2: update snowflake plugin to v0.2.1
  changelog/12378.txt
  go.mod
  go.sum
  physical/azure/azure.go
Labels: backport

#12385 Backport 1.8.2: Handle api explorer routing error (#12354)
  changelog/12354.txt
  ui/app/components/console/ui-panel.js
Labels: ui

#12356 Fixed a slight grammar mistake
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, docs-cherrypick, website, pr/no-changelog

#12361 Backport: Add support for DSA signature verification for EC2 (#12340)
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/pkcs7/README.md
  builtin/credential/aws/pkcs7/ber.go
  builtin/credential/aws/pkcs7/ber_test.go
  builtin/credential/aws/pkcs7/decrypt.go
  builtin/credential/aws/pkcs7/decrypt_test.go
  builtin/credential/aws/pkcs7/encrypt.go
  builtin/credential/aws/pkcs7/encrypt_test.go
  builtin/credential/aws/pkcs7/pkcs7.go
  builtin/credential/aws/pkcs7/pkcs7_test.go
  builtin/credential/aws/pkcs7/sign.go
  builtin/credential/aws/pkcs7/sign_test.go
  builtin/credential/aws/pkcs7/verify.go
  builtin/credential/aws/pkcs7/verify_test_dsa.go
  changelog/12340.txt
  go.mod
  go.sum
Labels: backport

#12363 Backport 1.8.2: UI Allow metrics view without config read (#12348)
  changelog/12348.txt
  ui/app/templates/vault/cluster/metrics/index.hbs
  ui/tests/acceptance/usage-metrics-test.js
Labels: ui, bug

#12272 feature: OIDC provider client API
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#12398 Upgrading packagespec to 0.2.7 on 1.6.x branch
  .circleci/config.yml
  .circleci/config/@build-release.yml
  packages-oss.lock/pkgs.yml
Labels: pr/no-changelog

#12373 docs: updates for vault-helm-0.15.0 and vault-k8s-0.12.0
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
Labels: docs-cherrypick, pr/no-changelog

#12291 website: update alert banner
  website/data/alert-banner.js
Labels: docs-cherrypick, pr/no-changelog

#12392 OIDC Client API: add more test coverage
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#12405 Lease count quotas does not apply to root tokens
  website/content/docs/enterprise/lease-count-quotas.mdx
Labels: docs-cherrypick, pr/no-changelog

#12288 add known issue for dr secondary lease count quota invalidation
  website/content/docs/upgrading/upgrade-to-1.6.0.mdx
  website/content/docs/upgrading/upgrade-to-1.7.0.mdx
  website/content/partials/lease-count-quota-upgrade.mdx
Labels: pr/no-changelog

#12409 Bug Fix: tab on MaskedInput for GeneratedItems it was clearing the value
  changelog/12409.txt
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/masked-input.js
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/integration/components/masked-input-test.js
Labels: ui, bug

#12416 Backport 1.8.x: UI bug fix clearing maskedinput on tab
  changelog/12409.txt
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/masked-input.js
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/integration/components/masked-input-test.js
Labels: backport

#12404 Bump `go-discover` to fix broken dep tree
  go.mod
  go.sum
Labels: pr/no-changelog

#12345 Upgrade note for RedHat package issue
  website/content/docs/upgrading/upgrade-to-1.8.0.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#12401 docs: fix exit flag reference on agent
  website/content/docs/agent/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#12433 packagespec upgrade -version 0.2.8
  packages-oss.lock/pkgs.yml
Labels: pr/no-changelog

#12434 packagespec upgrade -version 0.2.8
  packages-oss.lock/pkgs.yml
Labels: pr/no-changelog

#12432 packagespec upgrade -version 0.2.8
  packages-oss.lock/pkgs.yml
Labels: pr/no-changelog

#12400 Remove the old license instructions from the Enterprise index page.
  website/content/docs/enterprise/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#12365 Add notes re dangers of identity write endpoints.
  website/content/api-docs/secret/identity/entity-alias.mdx
  website/content/api-docs/secret/identity/group.mdx
  website/content/docs/secrets/identity.mdx
Labels: docs-cherrypick, pr/no-changelog

#12455 Tiny typo
  ui/lib/core/addon/components/confirmation-modal.js
Labels: ui, pr/no-changelog

#12376 fix struct tags and test in ldaputil
  sdk/helper/ldaputil/config.go
  sdk/helper/ldaputil/config_test.go
Labels: pr/no-changelog

#12461 Refactor usages of Core in IdentityStore so they can be decoupled.
  sdk/helper/consts/replication.go
  vault/core.go
  vault/dynamic_system_view.go
  vault/identity_store.go
  vault/identity_store_aliases.go
  vault/identity_store_aliases_test.go
  vault/identity_store_entities.go
  vault/identity_store_entities_test.go
  vault/identity_store_group_aliases.go
  vault/identity_store_groups.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oss.go
  vault/identity_store_structs.go
  vault/identity_store_util.go
  vault/mount.go
  vault/namespaces.go
  vault/namespaces_oss.go
  vault/router.go
Labels: pr/no-changelog

#12460 [VAULT-3347] Ensure Deduplication in Provider and Client APIs in OIDC Provider
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#12169 UI add custom metadata to KV2
  changelog/12169.txt
  ui/app/adapters/secret-engine.js
  ui/app/components/kv-object-editor.js
  ui/app/components/mount-backend-form.js
  ui/app/components/secret-create-or-update.js
  ui/app/components/secret-delete-menu.js
  ui/app/components/secret-edit-metadata.js
  ui/app/components/secret-edit-toolbar.js
  ui/app/components/secret-edit.js
  ui/app/controllers/vault/cluster/secrets/backend/metadata.js
  ui/app/helpers/split-object.js
  ui/app/models/secret-engine.js
  ui/app/models/secret-v2.js
  ui/app/router.js
  ui/app/routes/vault/cluster/secrets/backend/configuration.js
  ui/app/routes/vault/cluster/secrets/backend/create-root.js
  ui/app/routes/vault/cluster/secrets/backend/edit-metadata.js
  ui/app/routes/vault/cluster/secrets/backend/metadata.js
  ui/app/styles/components/form-section.scss
  ui/app/styles/core/box.scss
  ui/app/styles/core/forms.scss
  ui/app/templates/components/kv-object-editor.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-delete-menu.hbs
  ui/app/templates/components/secret-edit-display.hbs
  ui/app/templates/components/secret-edit-metadata.hbs
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/components/secret-list/item.hbs
  ui/app/templates/vault/cluster/secrets/backend/edit-metadata.hbs
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/integration/components/secret-edit-test.js
  ui/tests/pages/secrets/backend/kv/edit-secret.js
Labels: ui
