Repository hashicorp/vault, pull requests merged in 2021-07, with the labels that each got.

#11748 Add link to newish learn upgrade guide
  website/content/docs/upgrading/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#11981 fix vault version string injection
  .circleci/config.yml
  .circleci/config/@build-release.yml
  packages-oss.lock/pkgs.yml
  packages-oss.yml
Labels: pr/no-changelog

#11994 docs: fix link rendering for Oracle
  website/content/docs/secrets/databases/oracle.mdx
Labels: docs-cherrypick, pr/no-changelog

#11977 Vault-2713: Retry Irrevocable Lease Revocation Periodically
  vault/expiration.go
Labels: pr/no-changelog

#11999 [VAULT-1981] Add OSS changes
  vault/expiration_testing_util_common.go
Labels: pr/no-changelog

#12006 docs: add SSL connection example to oracle
  website/content/docs/secrets/databases/oracle.mdx
Labels: docs-cherrypick, pr/no-changelog

#12008 Reverting fix on KV 2 for duplicate paths
  changelog/12008.txt
  ui/app/components/secret-edit.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui

#12000 Update key icons in Transit secret engine
  ui/app/templates/components/secret-list/item.hbs
Labels: pr/no-changelog, ui

#11967 Diagnose warns if HTTPS is not used for ha-storage-tls-consul [VAULT-2773]
  command/operator_diagnose_test.go
  physical/consul/consul.go
  serviceregistration/consul/consul_service_registration.go
Labels: pr/no-changelog

#12007 Update vault-plugin-secrets-kv to 0.9.0
  go.mod
  go.sum
Labels: pr/no-changelog

#12010 UI KV validation fix
  ui/app/components/secret-edit.js
Labels: pr/no-changelog, ui

#12003 Adds transform secrets engine to feature
  changelog/12003.txt
  ui/app/helpers/all-features.js
Labels: ui

#12013 builtin/logical/pki: fix dropped test errors
  builtin/logical/pki/backend_test.go
Labels: pr/no-changelog

#11995 Truncate Secret Engine Description Text
  changelog/11995.txt
  ui/app/styles/components/linkable-item.scss
  ui/app/styles/components/read-more.scss
  ui/app/styles/core.scss
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/linkable-item.js
  ui/lib/core/addon/components/linkable-item/content.js
  ui/lib/core/addon/components/linkable-item/menu.js
  ui/lib/core/addon/components/read-more.js
  ui/lib/core/addon/templates/components/linkable-item.hbs
  ui/lib/core/addon/templates/components/linkable-item/content.hbs
  ui/lib/core/addon/templates/components/linkable-item/menu.hbs
  ui/lib/core/addon/templates/components/read-more.hbs
  ui/lib/core/app/components/linkable-item.js
  ui/lib/core/app/components/linkable-item/content.js
  ui/lib/core/app/components/linkable-item/menu.js
  ui/lib/core/app/components/read-more.js
  ui/lib/core/stories/linkable-item.md
  ui/lib/core/stories/linkable-item.stories.js
  ui/lib/core/stories/read-more.stories.js
  ui/package.json
  ui/tests/acceptance/secrets/backend/alicloud/secret-test.js
  ui/tests/integration/components/linkable-item-test.js
  ui/tests/integration/components/read-more-test.js
  ui/tests/pages/secrets/backends.js
  ui/yarn.lock
Labels: ui

#12014 OSS parts of Autopilot in DR secondaries
  vault/logical_system.go
  vault/logical_system_raft.go
  vault/raft.go
Labels: pr/no-changelog

#12023 secrets/gcp: update to v0.10.1 for static accounts
  changelog/12023.txt
  go.mod
  go.sum
Labels: secret/gcp

#12033 changed name from faqs to faq
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/enterprise/license/index.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#11998 UI: Exit test process if vault fails to initialize
  ui/scripts/start-vault.js
Labels: pr/no-changelog, ui

#12036 Update plugin dependencies for 1.8
  go.mod
  go.sum
Labels: pr/no-changelog

#11512 cockroachdb: Fix either incorrect or outdated info
  website/content/docs/configuration/storage/cockroachdb.mdx
Labels: docs-cherrypick

#11909 Diagnose Language Pass
  command/operator_diagnose.go
  command/operator_diagnose_test.go
  command/server/test-fixtures/diagnose_seal_transit_tls_check.hcl
  vault/diagnose/constants.go
  vault/diagnose/file_checks_test.go
  vault/diagnose/helpers.go
  vault/diagnose/helpers_test.go
  vault/diagnose/os_common.go
  vault/diagnose/os_openbsd_arm.go
  vault/diagnose/os_unix.go
  vault/diagnose/os_windows.go
  vault/diagnose/output.go
  vault/diagnose/raft_checks.go
  vault/diagnose/storage_checks.go
  vault/diagnose/tls_verification.go
  vault/diagnose/tls_verification_test.go
Labels: pr/no-changelog

#12040 Add replication example to upgrade docs
  website/content/docs/upgrading/index.mdx
  website/public/img/vault-replication-upgrade.png
Labels: docs-cherrypick, pr/no-changelog

#12042 [VAULT-2825] Fix erroneous 500 resp for field validation errors
  changelog/12042.txt
  sdk/framework/backend.go
  sdk/framework/backend_test.go
Labels: bug

#12024 UI/control group db cred
  changelog/12024.txt
  ui/app/adapters/database/credential.js
  ui/app/adapters/secret-v2-version.js
  ui/app/components/generate-credentials-database.js
  ui/app/components/secret-list-header-tab.js
  ui/app/models/database/credential.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/serializers/database/credential.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/generate-credentials-database.hbs
  ui/app/templates/components/get-credentials-card.hbs
  ui/app/templates/components/secret-list/database-list-item.hbs
  ui/app/templates/vault/cluster/secrets/backend/credentials.hbs
Labels: bug, ui

#12047 [Website] Bump hashi-stack-menu
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, website

#12046 skip seal check for manual sealing
  command/operator_diagnose.go
  command/operator_diagnose_test.go
Labels: pr/no-changelog

#12052 builtin/logical/nomad: fix dropped test errors
  builtin/logical/nomad/backend_test.go
Labels: pr/no-changelog

#12027 Update Documentation for GCP Static Account
  changelog/12023.txt
  website/content/api-docs/secret/gcp.mdx
  website/content/docs/secrets/gcp.mdx
Labels: docs, pr/no-changelog

#12045 Remove Key validation on KV2
  ui/app/components/secret-edit.js
  ui/app/templates/components/secret-edit-display.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: pr/no-changelog, ui

#12058 docs: fix formatting in azure secrets overview
  website/content/docs/secrets/azure.mdx
Labels: docs-cherrypick, pr/no-changelog

#12063 InfluxDB - Update API docs
  website/content/api-docs/secret/databases/influxdb.mdx
Labels: docs-cherrypick, pr/no-changelog

#11963 Handle form validation for open api form
  changelog/11963.txt
  ui/app/components/generated-item.js
  ui/app/components/mount-backend-form.js
  ui/app/models/auth-method.js
  ui/app/services/path-help.js
  ui/app/styles/core/message.scss
  ui/app/templates/components/generated-item.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/utils/build-api-validators.js
  ui/lib/core/addon/components/form-field-groups.js
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/templates/components/form-field-groups.hbs
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: ui

#12069 Update Vault main to new API/SDK Tags.
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog

#12070 Re-update SDK/API against release branch HEAD
  go.mod
  go.sum
Labels: pr/no-changelog

#12035 UI: Automatically refresh page on logout
  changelog/12035.txt
  ui/app/routes/vault/cluster/logout.js
Labels: backport, ui

#12075 Upgrade packagespec to 0.2.7 on the 1.8.x release branch
  .circleci/config.yml
  .circleci/config/@build-release.yml
  packages-oss.lock/Makefile
  packages-oss.lock/pkgs.yml
Labels: pr/no-changelog

#12076 Removed sentence from intro per PM's request
  website/content/docs/enterprise/license/faq.mdx
Labels: docs-cherrypick, pr/no-changelog

#12077 Clarify step-down functionality in docs
  website/content/docs/commands/operator/step-down.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12065 [docs] secrets/identity - grammar and punctuation fixes
  website/content/docs/secrets/identity.mdx
Labels: pr/no-changelog

#12079 Fix KV Version History queryParams on the component LinkedBlock
  changelog/12079.txt
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
  ui/lib/core/addon/components/linked-block.js
  ui/lib/core/addon/components/list-item.js
  ui/lib/core/addon/templates/components/list-item.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: bug, ui

#12088 Swap out sdk/helper libs with implementations in go-secure-stdlib
  api/go.mod
  api/go.sum
  builtin/logical/transit/path_encrypt_test.go
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/base62/base62.go
  sdk/helper/base62/base62_test.go
  sdk/helper/mlock/mlock.go
  sdk/helper/mlock/mlock_unavail.go
  sdk/helper/mlock/mlock_unix.go
  sdk/helper/parseutil/parseutil.go
  sdk/helper/parseutil/parseutil_test.go
  sdk/helper/password/password.go
  sdk/helper/password/password_solaris.go
  sdk/helper/password/password_test.go
  sdk/helper/password/password_unix.go
  sdk/helper/password/password_windows.go
  sdk/helper/strutil/strutil.go
  sdk/helper/strutil/strutil_test.go
  sdk/helper/tlsutil/tlsutil.go
  sdk/helper/tlsutil/tlsutil_test.go
Labels: pr/no-changelog

#12030 Typo fix: period rotation -> periodic rotation (in transit docs)
  website/content/docs/secrets/transit.mdx
Labels: pr/no-changelog

#12093 Revert #12061 due to failures in TestLogical_RequestSizeLimit
  api/response.go
  changelog/12061.txt
  http/handler.go
  sdk/logical/response_util.go
  vault/logical_system.go
Labels: pr/no-changelog

#12086 Clarify KV 2 API docs
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: docs-cherrypick, pr/no-changelog

#12085 Backport 1.7.4: UI Database control group access
  changelog/12024.txt
  ui/app/adapters/database/credential.js
  ui/app/adapters/secret-v2-version.js
  ui/app/components/generate-credentials-database.js
  ui/app/components/secret-list-header-tab.js
  ui/app/models/database/credential.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/serializers/database/credential.js
  ui/app/templates/components/database-list-item.hbs
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/generate-credentials-database.hbs
  ui/app/templates/components/get-credentials-card.hbs
  ui/app/templates/vault/cluster/secrets/backend/credentials.hbs
Labels: bug, ui

#12080 Backport 1.6.6: Automatically refresh UI page on logout (#12035)
  changelog/12035.txt
  ui/app/routes/vault/cluster/logout.js
Labels: ui

#12094 UI/Clarifies error message for exit test process
  ui/scripts/start-vault.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: pr/no-changelog, ui

#12095 secrets/ad: change improvement to feature in changelog
  changelog/11942.txt
Labels: backport, pr/no-changelog

#12099 Backport: secrets/ad: change improvement to feature in changelog (#12095)
  changelog/11942.txt
Labels: backport

#12081 Backport 1.7.4: Automatically refresh UI page on logout (#12035)
  changelog/12035.txt
  ui/app/routes/vault/cluster/logout.js
Labels: ui

#12087 secrets/database: fixes external plugin reconnect after shutdown for v4 and v5 interface
  builtin/logical/database/backend.go
  builtin/logical/database/path_creds_create.go
  changelog/12087.txt
Labels: bug, secret/database

#12098 mongodbatlas: update changelog for username customization
  changelog/11956.txt
Labels: pr/no-changelog

#12029 docs: fix heading number in SSH
  website/content/api-docs/secret/ssh.mdx
Labels: pr/no-changelog

#12101 Suppress logging during a diagnose run
  command/operator_diagnose.go
Labels: pr/no-changelog

#12106 Clarify token create policies behavior
  website/content/api-docs/auth/token.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12105 Add advice as a trace option to spot checks
  command/operator_diagnose.go
  vault/diagnose/os_common.go
  vault/diagnose/os_unix.go
  vault/diagnose/output.go
Labels: pr/no-changelog

#12103 Backport 1.7.x: secrets/database: fixes external plugin reconnect after shutdown for v4 and v5 interface (#12087)
  builtin/logical/database/backend.go
  builtin/logical/database/path_creds_create.go
  changelog/12087.txt
Labels: backport

#12104 Backport 1.6.x: secrets/database: fixes external plugin reconnect after shutdown for v4 and v5 interface (#12087)
  builtin/logical/database/backend.go
  builtin/logical/database/path_creds_create.go
  changelog/12087.txt
Labels: backport

#12102 Backport 1.8.x: secrets/database: fixes external plugin reconnect after shutdown for v4 and v5 interface (#12087)
  builtin/logical/database/backend.go
  builtin/logical/database/path_creds_create.go
  changelog/12087.txt
Labels: backport

#11996 Add ServiceNow credential resolver docs
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/platform/servicenow/index.mdx
  website/content/docs/platform/servicenow/installation.mdx
  website/content/docs/platform/servicenow/troubleshooting.mdx
  website/data/docs-nav-data.json
  website/public/img/servicenow-vault-credential-resolver-diagram.png
Labels: docs, pr/no-changelog, website

#12110 Updating changelog link to main
  website/data/version.js
Labels: docs-cherrypick, pr/no-changelog

#12057 Add support for testing Azure storage backend in CI using Azurite.
  physical/azure/azure.go
  physical/azure/azure_test.go
Labels: pr/no-changelog

#12074 Upgrade packagespec to v0.2.7
  .circleci/config.yml
  .circleci/config/@build-release.yml
  packages-oss.lock/Makefile
  packages-oss.lock/pkgs.yml
Labels: pr/no-changelog

#12082 Backport 1.8.0: Automatically refresh UI page on logout (#12035)
  changelog/12035.txt
  ui/app/routes/vault/cluster/logout.js
Labels: ui

#12107 Document bolt metrics
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog

#11931 Docs: Add link to more sentinel examples
  website/content/docs/enterprise/sentinel/examples.mdx
Labels: docs, docs-cherrypick, pr/no-changelog, website

#12112 Change changelog type for openldap bug fix
  changelog/12019.txt
Labels: backport, pr/no-changelog

#12114 Backport: Change changelog type for openldap bug fix (#12112)
  changelog/12019.txt
Labels: backport, pr/no-changelog

#12120 changelog: update feature formatting for gcp and key management secrets
  changelog/11958.txt
  changelog/12023.txt
Labels: backport, pr/no-changelog

#12119 Elaborating on telemetry persistence
  website/content/docs/internals/telemetry.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12122 Update telemetry docs
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog

#12125 Fix license expiration metric name in docs.
  website/content/docs/internals/telemetry.mdx
Labels: docs-cherrypick, pr/no-changelog

#12113 Fix minor typo in Internals/Plugins documentation
  builtin/logical/database/path_config_connection.go
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/internals/limits.mdx
  website/content/docs/internals/plugins.mdx
  website/content/docs/internals/telemetry.mdx
  website/content/docs/upgrading/upgrade-to-0.6.1.mdx
Labels: docs, docs-cherrypick, docs/learn, pr/no-changelog

#12111 UI/database cg read role
  changelog/12111.txt
  ui/app/adapters/database/credential.js
  ui/app/adapters/database/role.js
  ui/app/components/database-role-edit.js
  ui/app/controllers/vault/cluster/secrets/backend/credentials.js
  ui/app/controllers/vault/cluster/secrets/backend/show.js
  ui/app/helpers/secret-query-params.js
  ui/app/models/database/role.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/secret-list/database-list-item.hbs
Labels: backport, bug, ui

#12089 Migrate stepwise references out to the separate repo
  builtin/credential/userpass/stepwise_test.go
  builtin/logical/aws/stepwise_test.go
  builtin/logical/transit/stepwise_test.go
  go.mod
  go.sum
  sdk/testing/stepwise/environments/docker/environment.go
  sdk/testing/stepwise/environments/docker/runner.go
  sdk/testing/stepwise/helpers.go
  sdk/testing/stepwise/stepwise.go
  sdk/testing/stepwise/stepwise_test.go
Labels: pr/no-changelog

#12123 builtin/logical/database: fix dropped test errors
  builtin/logical/database/path_roles_test.go
Labels: pr/no-changelog

#12129 docs: remove username_template until after Vault 1.8
  website/content/api-docs/secret/aws.mdx
Labels: pr/no-changelog

#12132 Document raft bootstrap API.
  website/content/api-docs/system/storage/raft.mdx
Labels: docs-cherrypick

#12128 Move awsutil over to the go-secure-stdlib version
  api/go.mod
  api/go.sum
  builtin/credential/aws/backend.go
  builtin/credential/aws/cli.go
  builtin/credential/aws/client.go
  builtin/credential/aws/path_config_rotate_root.go
  builtin/credential/aws/path_config_rotate_root_test.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_role_test.go
  builtin/logical/aws/client.go
  builtin/logical/aws/secret_access_keys.go
  command/agent/auth/aws/aws.go
  go.mod
  go.sum
  physical/dynamodb/dynamodb.go
  physical/s3/s3.go
  physical/s3/s3_test.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/awsutil/error.go
  sdk/helper/awsutil/error_test.go
  sdk/helper/awsutil/generate_credentials.go
  sdk/helper/awsutil/mocks.go
  sdk/helper/awsutil/region.go
  sdk/helper/awsutil/region_test.go
Labels: pr/no-changelog

#12096 Backport: 1.8.x Fix KV version history linkedblock
  changelog/12079.txt
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
  ui/lib/core/addon/components/linked-block.js
  ui/lib/core/addon/components/list-item.js
  ui/lib/core/addon/templates/components/list-item.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: backport, ui

#12136 Backport: 1.8.x UI/database cg read role (#12111)
  changelog/12111.txt
  ui/app/adapters/database/credential.js
  ui/app/adapters/database/role.js
  ui/app/components/database-role-edit.js
  ui/app/controllers/vault/cluster/secrets/backend/credentials.js
  ui/app/controllers/vault/cluster/secrets/backend/show.js
  ui/app/helpers/secret-query-params.js
  ui/app/models/database/role.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/secret-list/database-list-item.hbs
Labels: backport, bug, ui

#12137 Backport 1.7.x: UI/database cg read role (#12111)
  changelog/12111.txt
  ui/app/adapters/database/credential.js
  ui/app/adapters/database/role.js
  ui/app/components/database-role-edit.js
  ui/app/controllers/vault/cluster/secrets/backend/credentials.js
  ui/app/controllers/vault/cluster/secrets/backend/show.js
  ui/app/helpers/secret-query-params.js
  ui/app/models/database/role.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/database/role.js
  ui/app/templates/components/database-list-item.hbs
  ui/app/templates/components/database-role-edit.hbs
Labels: backport, bug, ui

#12130 docs: Update Database Capabilities to include username customization
  website/content/docs/secrets/databases/index.mdx
Labels: pr/no-changelog

#12140 Document timeout setting for raft snapshots
  website/content/api-docs/system/storage/raft.mdx
  website/content/partials/raft-large-snapshots.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12084 Improve Secret Empty States
  changelog/12084.txt
  ui/app/styles/components/info-table-row.scss
  ui/app/templates/components/secret-form-show.hbs
  ui/lib/core/addon/templates/components/info-table-row.hbs
  ui/tests/integration/components/info-table-row-test.js
Labels: ui

#12143 Fix a couple of broken links to api docs.
  website/content/api-docs/system/license.mdx
  website/content/docs/enterprise/license/autoloading.mdx
Labels: docs-cherrypick, pr/no-changelog

#12141 Re-adding deleted changelog note
  changelog/_2021Jul21_license.txt
Labels: pr/no-changelog

#12147 docs/update replication seal table
  website/content/docs/enterprise/replication.mdx
Labels: pr/no-changelog

#12139 Clarify sudo req'd for remount
  website/content/api-docs/system/remount.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12153 [VAULT-2807] Count entity tokens on use
  vault/activity_log.go
  vault/request_handling.go
  vault/token_store.go
Labels: pr/no-changelog

#12049 Update node to latest stable version
  .circleci/config.yml
  .circleci/config/@build-release.yml
  .circleci/config/executors/@executors.yml
  changelog/12049.txt
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
  scripts/cross/Dockerfile
  scripts/docker/Dockerfile.ui
  ui/.nvmrc
  ui/package.json
Labels: ui

#12154 Backport 1.8.x: Update node to latest stable version (#12049)
  .circleci/config.yml
  .circleci/config/@build-release.yml
  .circleci/config/executors/@executors.yml
  changelog/12049.txt
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
  scripts/cross/Dockerfile
  scripts/docker/Dockerfile.ui
  ui/.nvmrc
  ui/package.json
Labels: backport, ui

#12155 Backport 1.7.x: Update node to latest stable version (#12049)
  .circleci/config.yml
  .circleci/config/@build-release.yml
  .circleci/config/executors/@executors.yml
  changelog/12049.txt
  packages-oss.lock/layers/layers.mk
  packages-oss.lock/pkgs.yml
  packages-oss.yml
  scripts/cross/Dockerfile
  scripts/docker/Dockerfile.ui
  ui/.nvmrc
  ui/package.json
Labels: backport, ui

#12145 website: fix release notes link
  website/pages/downloads/index.jsx
Labels: docs-cherrypick, pr/no-changelog, website

#12152 Add fallback font for masked-input
  ui/app/styles/app.scss
  ui/app/styles/core/forms.scss
  ui/public/fonts/text-security-square.woff2
Labels: pr/no-changelog, ui

#12158 Backport: 1.8.x add fallback font to masked-input
  ui/app/styles/app.scss
  ui/app/styles/core/forms.scss
  ui/public/fonts/text-security-square.woff2
Labels: backport, pr/no-changelog, ui

#12160 Tweak creation of vault.db file, take 2
  physical/raft/snapshot.go
Labels: pr/no-changelog

#12159 Diagnose docs + changelog
  changelog/diagnose.txt
  website/content/docs/commands/operator/diagnose.mdx
Labels: docs

#12174 Pin RabbitMQ and Cassandra docker image versions
  builtin/logical/rabbitmq/backend_test.go
  plugins/database/cassandra/cassandra_test.go
Labels: pr/no-changelog

#12164 Removes grey shadow/line beneath secret form key/value input fields
  ui/app/styles/components/info-table-row.scss
  ui/app/templates/components/secret-edit-display.hbs
Labels: pr/no-changelog, ui

#12172 docs: Update Database Capabilities to include username customization
  website/content/docs/secrets/databases/cassandra.mdx
  website/content/docs/secrets/databases/couchbase.mdx
  website/content/docs/secrets/databases/elasticdb.mdx
  website/content/docs/secrets/databases/influxdb.mdx
  website/content/docs/secrets/databases/mongodb.mdx
  website/content/docs/secrets/databases/mongodbatlas.mdx
  website/content/docs/secrets/databases/mssql.mdx
  website/content/docs/secrets/databases/mysql-maria.mdx
  website/content/docs/secrets/databases/oracle.mdx
  website/content/docs/secrets/databases/postgresql.mdx
  website/content/docs/secrets/databases/redshift.mdx
  website/content/docs/secrets/databases/snowflake.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#12179 Correct changelog re log shipper buffer size config
  CHANGELOG.md
Labels: pr/no-changelog

#12181 UI: minor typo changes/fixes
  ui/app/styles/components/linkable-item.scss
  ui/lib/core/addon/components/linkable-item/content.js
  ui/lib/core/stories/read-more.stories.js
Labels: pr/no-changelog, ui

#12118 web: migrate to web platform- packages
  website/.eslintrc.js
  website/.stylelintrc.js
  website/components/before-after-diagram/server.js
  website/components/subnav/index.jsx
  website/next-env.d.ts
  website/next.config.js
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/_error.jsx
  website/pages/home/index.jsx
  website/pages/style.css
  website/pages/use-cases/data-encryption/index.jsx
  website/pages/use-cases/identity-based-access/index.jsx
  website/pages/use-cases/secrets-management/index.jsx
  website/prettier.config.js
Labels: docs-cherrypick, pr/no-changelog, website

#12186 Add 1.8 upgrade guide
  website/content/docs/upgrading/upgrade-to-1.8.0.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#12187 Update website download link
  website/data/version.js
Labels: pr/no-changelog

#12195 Add website redirect to fix faqs -> faq issue
  website/redirects.next.js
Labels: docs-cherrypick, pr/no-changelog

#10841 Clarify license doesnt replicate to PR
  website/content/api-docs/system/license.mdx
Labels: docs, docs-cherrypick, pr/no-changelog, website

#11913 Update template.mdx
  website/content/docs/agent/template.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12184 builtin/credential/cert: fix dropped test error
  builtin/credential/cert/backend_test.go
Labels: pr/no-changelog

#12171 [NO-TICKET] Upgrade protoc-gen-go to 1.26, upgrade protoc to 3.17.3
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/request_forwarding_service.pb.go
Labels: pr/no-changelog

#12097 Update docs to reflect support for autopilot DR
  website/content/docs/concepts/integrated-storage/autopilot.mdx
Labels: pr/no-changelog

#12182 Match KV key value to kv-object-editor component
  ui/app/styles/core/forms.scss
  ui/app/templates/components/kv-object-editor.hbs
  ui/app/templates/components/secret-edit-display.hbs
Labels: pr/no-changelog, ui

#12197 [VAULT-2852] deprecate req counters in oss
  sdk/logical/error.go
  sdk/logical/response_util.go
  vault/core.go
  vault/core_metrics.go
  vault/counters.go
  vault/counters_test.go
  vault/logical_system.go
  vault/request_handling.go
  vault/testing.go
  website/content/api-docs/system/internal-counters.mdx
Labels: pr/no-changelog

#12188 Set no_output_timeout for build-ui layer
  .circleci/config.yml
  .circleci/config/@build-release.yml
Labels: pr/no-changelog

#12206 docs: updating for vault-helm v0.14.0
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12209 docs: updates for vault-k8s v0.11.0
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12210 Add settled() to failing browserstack tests
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: pr/no-changelog, ui

#12216 add visible note about being enterprise
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: docs, docs-cherrypick, pr/no-changelog

#12200 Improve "Integrated Storage" documentation
  website/content/docs/concepts/ha.mdx
  website/content/docs/concepts/integrated-storage/index.mdx
  website/content/docs/configuration/storage/raft.mdx
Labels: pr/no-changelog
