Repository hashicorp/vault, pull requests merged in 2021-06, with the labels that each got.

#11710 secret-list/item partial removed
  ui/app/components/secret-list/database-list-item.js
  ui/app/components/secret-list/transform-list-item.js
  ui/app/helpers/options-for-backend.js
  ui/app/templates/components/secret-list/aws-role-item.hbs
  ui/app/templates/components/secret-list/database-list-item.hbs
  ui/app/templates/components/secret-list/item.hbs
  ui/app/templates/components/secret-list/pki-cert-item.hbs
  ui/app/templates/components/secret-list/pki-role-item.hbs
  ui/app/templates/components/secret-list/ssh-role-item.hbs
  ui/app/templates/components/secret-list/transform-list-item.hbs
  ui/app/templates/components/secret-list/transform-transformation-item.hbs
  ui/app/templates/partials/secret-list/database-list-item.hbs
  ui/app/templates/partials/secret-list/transform-list-item.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/tests/integration/components/transform-list-item-test.js
Labels: ui

#11750 chore: upgrades `text-split-with-logo-grid`
  website/content/api-docs/system/leases.mdx
  website/package-lock.json
  website/package.json
  website/pages/home/content.json
  website/pages/use-cases/identity-based-access/content.json
  website/pages/use-cases/secrets-management/content.json
Labels: docs-cherrypick, website

#11753 Update replication status docs
  website/content/api-docs/system/replication/index.mdx
Labels: docs-cherrypick

#11759 UI/license banners
  changelog/11759.txt
  ui/app/components/license-banners.js
  ui/app/models/cluster.js
  ui/app/styles/components/license-banners.scss
  ui/app/styles/core.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/core/message.scss
  ui/app/templates/components/license-banners.hbs
  ui/app/templates/vault/cluster.hbs
  ui/lib/core/addon/components/alert-banner.js
  ui/mirage/config.js
  ui/tests/acceptance/enterprise-license-banner-test.js
  ui/tests/integration/components/license-banners-test.js
Labels: ui

#11739 Removing all secret-form-*
  ui/app/components/secret-edit.js
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/components/secret-form-show.hbs
  ui/app/templates/partials/secret-form-create.hbs
  ui/app/templates/partials/secret-form-edit.hbs
Labels: ui

#11737 Partials Transit removal
  ui/app/templates/components/transit-edit.hbs
  ui/app/templates/components/transit-form-create.hbs
  ui/app/templates/components/transit-form-edit.hbs
  ui/app/templates/components/transit-form-show.hbs
Labels: ui

#11703 Rotate Algolia API Key
  website/.env
Labels: docs-cherrypick, website

#11779 errwrap.Wrapf() mop-up
  serviceregistration/consul/consul_service_registration.go
  shamir/shamir.go
Labels: waiting-for-response

#11781 Fix SpotSkipped call on openbsd/arm
  vault/diagnose/os_openbsd_arm.go
Labels: core/diagnose

#11778 UI/license autoload
  changelog/11778.txt
  ui/app/adapters/license.js
  ui/app/components/license-info.js
  ui/app/controllers/vault/cluster/license.js
  ui/app/models/license.js
  ui/app/routes/vault/cluster/license.js
  ui/app/serializers/license.js
  ui/app/templates/components/license-info.hbs
  ui/app/templates/vault/cluster/license.hbs
  ui/app/templates/vault/cluster/unseal.hbs
  ui/config/environment.js
  ui/mirage/config.js
  ui/tests/integration/components/license-info-test.js
  ui/tests/pages/components/license-info.js
Labels: ui

#11782 docs: clarify purposes in KMS for AWS
  website/content/api-docs/secret/key-management/index.mdx
Labels: docs-cherrypick

#11765 replace last two partials
  ui/app/components/form-field-groups-loop.js
  ui/app/templates/components/config-pki-ca.hbs
  ui/app/templates/components/form-field-from-model.hbs
  ui/app/templates/components/form-field-groups-loop.hbs
  ui/app/templates/components/generate-credentials.hbs
  ui/app/templates/components/role-pki-edit.hbs
  ui/app/templates/components/role-ssh-edit.hbs
  ui/app/templates/partials/backend-details.hbs
  ui/app/templates/partials/form-field-from-model.hbs
  ui/app/templates/partials/form-field-groups-loop.hbs
  ui/app/templates/vault/cluster/secrets/backend/sign.hbs
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/ssh-test.js
Labels: ui

#11776 moved client content from cloud to vault
  website/content/docs/concepts/client-count.mdx
Labels: docs-cherrypick, website

#11741 chore: updates alert banner data
  website/data/alert-banner.js
Labels: do-not-merge, docs-cherrypick, website

#11754 Add note about JSON encoding to password policies docs
  website/content/docs/concepts/password-policies.mdx
Labels: docs, docs-cherrypick

#11755 Password policies: Fix link from API docs to password policy syntax
  website/content/api-docs/system/policies-password.mdx
Labels: docs, docs-cherrypick

#11794 UI/update license serializer
  ui/app/models/license.js
  ui/app/serializers/license.js
  ui/mirage/config.js
Labels: bug, ui

#11801 website: update alert banner
  website/data/alert-banner.js
Labels: docs-cherrypick, website

#11796 InfluxDB - Add username customization
  plugins/database/influxdb/influxdb.go
  plugins/database/influxdb/influxdb_test.go
Labels: secret/database/influxdb

#11792 fix typo in vault operator init cmd
  command/operator_init.go
  website/content/intro/getting-started/deploy.mdx
Labels: docs, docs-cherrypick

#11814 website: fix incorrect content
  website/pages/home/index.jsx
Labels: docs-cherrypick

#11823 database/cassandra: Docs: Add known issue warning to `pem_bundle` field
  website/content/api-docs/secret/databases/cassandra.mdx
Labels: docs, docs-cherrypick

#11828 plugins/cassandra: add tls_server_name (#11820)
  changelog/11820.txt
  plugins/database/cassandra/connection_producer.go
  website/pages/api-docs/secret/databases/cassandra.mdx
Labels: backport

#11829 plugins/cassandra: add tls_server_name (#11820)
  changelog/11820.txt
  plugins/database/cassandra/connection_producer.go
  website/content/api-docs/secret/databases/cassandra.mdx
Labels: backport

#11734 Include note about `ManageOwnAccessKeys` stanza
  website/content/docs/auth/aws.mdx
Labels: docs-cherrypick

#11836 mod: update vault-plugin-secrets-ad@v0.9.1
  changelog/11836.txt
  go.mod
  go.sum
  vendor/github.com/hashicorp/vault-plugin-secrets-ad/plugin/path_creds.go
  vendor/modules.txt
Labels: backport

#11844 docs: add permissions required for cassandra
  website/content/docs/secrets/databases/cassandra.mdx
Labels: docs-cherrypick

#11807 Updated transit key action to components
  ui/app/components/transit-key-action/export.js
  ui/app/templates/components/transit-key-action/datakey.hbs
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/export.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/sign.hbs
  ui/app/templates/components/transit-key-action/verify.hbs
  ui/app/templates/components/transit-key-actions.hbs
Labels: ui

#11825 fix(website): update node version to latest LTS
  website/Dockerfile
Labels: docs-cherrypick

#11713 Support tls-skip-verify for output-curl-string
  api/client.go
  api/output_string.go
Labels: merge

#11698 login instructions not correct for Radius auth method documentation
  website/content/docs/auth/radius.mdx
Labels: merge

#11839 Add more detailed documentation on setting issuer for CSI provider
  website/content/docs/platform/k8s/csi/configurations.mdx
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
Labels: docs-cherrypick

#11858 docs: add troubleshooting sub-section on plugins
  website/content/docs/internals/plugins.mdx
Labels: docs, docs-cherrypick

#11795 Displays Auth Method description on Vault UI login page
  changelog/11795.txt
  ui/app/components/auth-form.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth-form-test.js
  ui/tests/pages/components/auth-form.js
Labels: ui

#11787 Removes space on overview page with empty state
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
Labels: ui

#11785 Implement ember-cp-validations on KV secret engine
  changelog/11785.txt
  ui/app/components/mount-backend-form.js
  ui/app/components/secret-edit.js
  ui/app/models/secret-engine.js
  ui/app/models/secret-v2.js
  ui/app/styles/core/forms.scss
  ui/app/styles/core/message.scss
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/secret-edit-display.hbs
  ui/app/templates/components/secret-edit.hbs
  ui/lib/core/addon/components/alert-inline.js
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/templates/components/form-field-groups.hbs
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/package.json
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/yarn.lock
Labels: ui

#11868 Remove a broken link
  website/content/docs/secrets/transform/tokenization.mdx
Labels: docs, docs-cherrypick

#11809 Added new folder and files for Vault License FAQs
  website/content/docs/enterprise/license/faqs.mdx
  website/content/docs/enterprise/license/index.mdx
  website/data/docs-nav-data.json
Labels: do-not-merge, docs-cherrypick, website

#11880 Update website latest version
  website/data/version.js
Labels: docs-cherrypick

#11873 Fix error log typo for failing to decrypt keys
  vault/seal.go
Labels: waiting-for-response

#11848 docs: vault-helm license support for enterprise
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/data/docs-nav-data.json
Labels: docs, docs-cherrypick

#11890 docs: update for vault-helm v0.13.0
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
Labels: docs, docs-cherrypick

#11884 UI/fix safari oidc login
  changelog/11884.txt
  ui/app/components/auth-jwt.js
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth-jwt-test.js
Labels: backport, bug, ui

#11892 License FAQs Updated 'plus' > 'pro'
  website/content/docs/enterprise/license/faqs.mdx
Labels: docs, docs-cherrypick

#11894 Adding github action to check for changelog file
  .github/workflows/changelog-checker.yml
Labels: pr/no-changelog

#11886 Docs for license autoloading.
  website/content/api-docs/system/config-reload.mdx
  website/content/api-docs/system/license.mdx
  website/content/docs/commands/index.mdx
  website/content/docs/commands/license/get.mdx
  website/content/docs/commands/license/index.mdx
  website/content/docs/commands/license/inspect.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick

#11897 Rename some references from master to main
  .circleci/config.yml
  .circleci/config/commands/exit-if-branch-does-not-need-test-ui.yml
  .circleci/config/workflows/ci.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/stable-website.yaml
  scripts/dist.sh
  scripts/update_plugin_modules.sh
Labels: pr/no-changelog

#11881 Clarify upgrade steps and shutdown behavior
  website/content/docs/upgrading/index.mdx
Labels: docs-cherrypick

#11860 Tls check client certs [VAULT-2117]
  command/operator_diagnose.go
  vault/diagnose/test-fixtures/chain.crt.pem
  vault/diagnose/test-fixtures/intermediateCert.pem
  vault/diagnose/test-fixtures/selfSignedCert.pem
  vault/diagnose/test-fixtures/twoRootCA.pem
  vault/diagnose/tls_verification.go
  vault/diagnose/tls_verification_test.go
Labels: pr/no-changelog

#11869 feat(website): A11y updates
  website/components/before-after-diagram/index.jsx
  website/components/before-after-diagram/style.module.css
  website/components/footer/style.css
  website/components/hcp-callout-section/index.jsx
  website/components/use-case-cta-section/index.jsx
  website/package-lock.json
  website/package.json
  website/pages/_app.js
  website/pages/_document.js
  website/pages/community/index.jsx
  website/pages/downloads/index.jsx
  website/pages/home/content.json
  website/pages/home/index.jsx
  website/pages/not-found/index.jsx
  website/pages/use-cases/data-encryption/content.json
  website/pages/use-cases/data-encryption/index.jsx
  website/pages/use-cases/identity-based-access/content.json
  website/pages/use-cases/identity-based-access/index.jsx
  website/pages/use-cases/secrets-management/content.json
  website/pages/use-cases/secrets-management/index.jsx
Labels: docs-cherrypick, pr/no-changelog, website

#11861 Cassandra: Refactor PEM parsing logic
  changelog/11861.txt
  helper/testhelpers/cassandra/cassandrahelper.go
  plugins/database/cassandra/cassandra_test.go
  plugins/database/cassandra/connection_producer.go
  plugins/database/cassandra/connection_producer_test.go
  plugins/database/cassandra/test-fixtures/with_tls/bad_ca.pem
  plugins/database/cassandra/test-fixtures/with_tls/ca.pem
  plugins/database/cassandra/test-fixtures/with_tls/ca.pem.json
  plugins/database/cassandra/test-fixtures/with_tls/cassandra.yaml
  plugins/database/cassandra/test-fixtures/with_tls/cqlshrc
  plugins/database/cassandra/test-fixtures/with_tls/gencert.sh
  plugins/database/cassandra/test-fixtures/with_tls/keystore.jks
  plugins/database/cassandra/test-fixtures/with_tls/stores/keystore
  plugins/database/cassandra/test-fixtures/with_tls/stores/server.p12
  plugins/database/cassandra/test-fixtures/with_tls/stores/truststore
  plugins/database/cassandra/tls.go
  website/content/api-docs/secret/databases/cassandra.mdx
Labels: bug, secret/database/cassandra

#11893 approle: convert Callbacks to Operations
  builtin/credential/approle/path_login.go
Labels: pr/no-changelog

#11900 Updates license state copy and link
  ui/app/templates/components/license-info.hbs
  ui/tests/integration/components/license-info-test.js
Labels: ui

#11775 agent: restart template runner on retry for unlimited retries
  changelog/11775.txt
  command/agent/cache/api_proxy.go
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template_config-empty.hcl
  command/agent/config/test-fixtures/config-template_config.hcl
  command/agent/template/template.go
  command/agent/template/template_test.go
  command/agent_test.go
  website/content/docs/agent/index.mdx
  website/content/docs/agent/template-config.mdx
  website/content/docs/agent/template.mdx
  website/data/docs-nav-data.json
Labels: core/agent

#11878 UI/cp validations kv duplicate path
  changelog/11878.txt
  ui/app/components/secret-edit.js
  ui/app/models/secret-engine.js
  ui/app/models/secret-v2.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui

#11918 Remove Lingering Print Statements in Diagnose
  vault/diagnose/file_checks.go
Labels: pr/no-changelog

#11917 Update contributing guidelines
  CONTRIBUTING.md
Labels: pr/no-changelog

#11919 Document vault.core.expiration_time_epoch metric.
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog

#11899 RabbitMQ - Add username customization
  builtin/logical/rabbitmq/path_config_connection.go
  builtin/logical/rabbitmq/path_config_connection_test.go
  builtin/logical/rabbitmq/path_role_create.go
  builtin/logical/rabbitmq/path_role_create_test.go
  changelog/11899.txt
  website/content/api-docs/secret/rabbitmq.mdx
Labels: secret/rabbitmq

#11883 Checking Validity of all Certs in the chain [VAULT-2114]
  vault/diagnose/test-fixtures/selfSignedCertKey.pem
  vault/diagnose/tls_verification.go
  vault/diagnose/tls_verification_test.go
Labels: pr/no-changelog

#11905 Backport 1.6.6: UI/fix safari oidc login (#11884)
  changelog/11884.txt
  ui/app/components/auth-jwt.js
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth-jwt-test.js
Labels: bug, ui

#11906 Backport 1.7.3: UI/fix safari oidc login (#11884)
  changelog/11884.txt
  ui/app/components/auth-jwt.js
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth-jwt-test.js
Labels: bug, ui

#11903 website: upgrade code-block
  website/package-lock.json
  website/package.json
  website/pages/style.css
Labels: docs, docs-cherrypick, pr/no-changelog, website

#11924 docs: corrects JSON and issuer for identity tokens
  website/content/api-docs/secret/identity/tokens.mdx
  website/content/docs/secrets/identity.mdx
Labels: docs, docs-cherrypick

#11930 website: bump use-cases to latest
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, pr/no-changelog, website

#11928 Remove fragile link to docs from code.
  physical/raft/raft.go
Labels: pr/no-changelog

#11921 Backport [1.7.x]: Cassandra: Refactor PEM parsing logic (#11861)
  changelog/11861.txt
  helper/testhelpers/cassandra/cassandrahelper.go
  plugins/database/cassandra/cassandra_test.go
  plugins/database/cassandra/connection_producer.go
  plugins/database/cassandra/connection_producer_test.go
  plugins/database/cassandra/test-fixtures/with_tls/bad_ca.pem
  plugins/database/cassandra/test-fixtures/with_tls/ca.pem
  plugins/database/cassandra/test-fixtures/with_tls/ca.pem.json
  plugins/database/cassandra/test-fixtures/with_tls/cassandra.yaml
  plugins/database/cassandra/test-fixtures/with_tls/cqlshrc
  plugins/database/cassandra/test-fixtures/with_tls/gencert.sh
  plugins/database/cassandra/test-fixtures/with_tls/keystore.jks
  plugins/database/cassandra/test-fixtures/with_tls/stores/keystore
  plugins/database/cassandra/test-fixtures/with_tls/stores/server.p12
  plugins/database/cassandra/test-fixtures/with_tls/stores/truststore
  plugins/database/cassandra/tls.go
  website/content/api-docs/secret/databases/cassandra.mdx
Labels: bug, secret/database/cassandra

#11932 Fix diagnose panic when configuration file does not exist
  command/operator_diagnose.go
  internalshared/configutil/config.go
Labels: pr/no-changelog

#11929 update content param for improved attribution
  website/components/subnav/index.jsx
Labels: docs-cherrypick, pr/no-changelog, website

#11923 Diagnose Storage Panic Bugfixes
  command/operator_diagnose.go
  command/operator_diagnose_test.go
  command/server/test-fixtures/config_diagnose_ok.hcl
  command/server/test-fixtures/config_raft.hcl
  command/server/test-fixtures/diagnose_raft_no_bolt_folder.hcl
  physical/raft/raft.go
Labels: pr/no-changelog

#11864 Fix for Issue 11863 - Panic when creating/updating approle role with token_type
  builtin/credential/approle/path_role.go
  builtin/credential/approle/path_role_test.go
  changelog/11864.txt
Labels: waiting-for-response

#11872 Mongo doesnt allow periods in usernames
  changelog/11872.txt
  plugins/database/mongodb/mongodb.go
  plugins/database/mongodb/mongodb_test.go
  website/content/api-docs/secret/databases/mongodb.mdx
Labels: secret/database/mongodb, waiting-for-response

#11910 TLS Verification Bugfixes
  command/operator_diagnose.go
  vault/diagnose/helpers_test.go
  vault/diagnose/output.go
  vault/diagnose/tls_verification.go
  vault/diagnose/tls_verification_test.go
  vault/init.go
Labels: pr/no-changelog

#11922 diagnose: Add seal transit tls check
  command/operator_diagnose.go
  command/operator_diagnose_test.go
  command/server/test-fixtures/diagnose_seal_trasit_tls_check.hcl
  vault/diagnose/tls_verification.go
Labels: pr/no-changelog

#11938 website: upgrade react-head
  website/package-lock.json
  website/package.json
Labels: docs-cherrypick, pr/no-changelog, website

#11911 docs: vault-helm add license update steps
  website/content/docs/platform/k8s/helm/enterprise.mdx
Labels: docs, pr/no-changelog

#11935 ci: cache go modules
  .circleci/config.yml
  .circleci/config/commands/@caches.yml
  .circleci/config/commands/@yarn-cache.yml
  .circleci/config/commands/configure-git.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/commands/setup-go.yml
  .circleci/config/jobs/build-go-dev.yml
  .circleci/config/jobs/pre-flight-checks.yml
  .circleci/config/jobs/test-go-nightly.yml
  api/go.sum
Labels: pr/no-changelog

#11939 Diagnose License Check (OSS)
  command/operator_diagnose.go
  helper/constants/constants_oss.go
  helper/testhelpers/testhelpers_oss.go
  vault/core_util.go
  vault/diagnose/constants.go
  vault/external_tests/raft/raft_test.go
Labels: pr/no-changelog

#11944 Adding changelog for #11502
  changelog/11502.txt
Labels: pr/no-changelog

#11951 ci: update go_test to match one from ent
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
Labels: pr/no-changelog

#11888 Require special privileges to list irrevocable leases
  sdk/framework/backend.go
  vault/logical_system.go
  vault/logical_system_test.go
Labels: pr/no-changelog

#11947 fix dropped errors in external_tests
  vault/external_tests/identity/identity_test.go
  vault/external_tests/token/token_test.go
Labels: pr/no-changelog

#11958 docs: AWS KMS updates for key management secrets engine
  changelog/11958.txt
  website/content/api-docs/secret/key-management/awskms.mdx
  website/content/docs/secrets/key-management/awskms.mdx
  website/content/docs/secrets/key-management/index.mdx
Labels: docs

#11964 Add overlooked 1.7 agent cache eventual consistency options.
  website/content/docs/agent/caching/index.mdx
Labels: docs-cherrypick, pr/no-changelog

#11965 update oss files with changes from ent PR #1928
  vault/expiration_test.go
  vault/expiration_testing_util_common.go
  vault/external_tests/expiration/expiration_test.go
Labels: pr/no-changelog

#11959 remove trailing / on leases API endpoint
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
Labels: pr/no-changelog

#11954 Augment lease revocation metrics
  vault/expiration.go
  vault/expiration_test.go
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog
