Repository hashicorp/vault, pull requests merged in 2022-10, with the labels that each got.

#17375 Updating the VIP..again
  website/content/docs/interoperability-matrix.mdx
  website/content/docs/partnerships.mdx
  website/data/docs-nav-data.json
Labels: docs, website, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17380 Backport of Updating the VIP..again into release/1.11.x
  website/content/docs/interoperability-matrix.mdx
  website/content/docs/partnerships.mdx
  website/data/docs-nav-data.json
Labels: docs, website, pr/no-changelog

#17384 PKI: Do not read revoked certificates if CRL is disabled
  builtin/logical/pki/crl_util.go
  changelog/17384.txt
Labels: bug, secret/pki

#17385 PKI: Do not load revoked certificates if CRL has been disabled
  builtin/logical/pki/crl_util.go
  changelog/17385.txt
Labels: bug, secret/pki, backport/1.12.x

#17237 Vault documentation: release notes for 1.12
  website/content/docs/release-notes/1.12.0.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#17379 auth/oidc: fix documentation link anchors for Google Workspace integration
  website/content/docs/auth/jwt/oidc-providers/google.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#17388 PKI: Add support for signature_bits param to the intermediate/generate api
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/integation_test.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/test_helpers.go
  changelog/17388.txt
  sdk/helper/certutil/helpers.go
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: secret/pki, backport/1.12.x

#17294 Add documentation for KMIP features implemented in 1.12
  website/content/docs/secrets/kmip-profiles.mdx
  website/content/docs/secrets/kmip.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#17312 docs: Add docs for PKCS#11 provider
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.12.x

#16872 fix incorrect use of loop variable
  changelog/16872.txt
  command/agent/approle_end_to_end_test.go
  command/kv_test.go
  command/operator_diagnose.go
  command/server.go
Labels: agent

#17404 Replace query-params helper with hash
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/components/pki/role-pki-edit.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/app/templates/components/secret-list/transform-list-item.hbs
  ui/app/templates/components/secret-list/transform-transformation-item.hbs
  ui/app/templates/components/transit-form-show.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/app/templates/vault/cluster/secrets/backend/transit-actions-layout.hbs
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
Labels: ui

#17397 Raft index telemetry and docs
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/concepts/integrated-storage/autopilot.mdx
Labels: pr/no-changelog

#17408 changelog: fix 1.12.0-rc1, 1.11.4, 1.10.7, 1.9.10
  CHANGELOG.md
Labels: pr/no-changelog

#17407 Bug Fix for Kymgmt keyType on default
  changelog/17407.txt
  ui/app/models/keymgmt/key.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
Labels: ui, bug, backport/1.11.x, backport/1.12.x

#17377 Update Vault version verification integration test
  .github/workflows/build.yml
  .github/workflows/enos-run.yml
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/get_local_metadata/main.tf
  enos/modules/get_local_metadata/scripts/build_date.sh
  enos/modules/get_local_metadata/scripts/version.sh
  enos/modules/get_local_version_from_make/main.tf
  enos/modules/vault_verify_version/main.tf
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
Labels: pr/no-changelog

#17419 Update plugin consul template v0.29.5
  changelog/17419.txt
  go.mod
  go.sum
Labels: agent

#17403 Plugins: Tighten requirements for multiplexing
  sdk/plugin/mock/backend.go
  vault/external_plugin_test.go
  vault/plugin_catalog.go
  vault/plugin_catalog_test.go
  vault/testing.go
Labels: bug, core/plugin, pr/no-changelog, backport/1.12.x

#17186 Fix unsafe access to perf standby status from systemview
  changelog/17186.txt
  vault/dynamic_system_view.go
  vault/mount_util.go
  vault/policy_store.go
  vault/testing.go
Labels: core, core/replication

#17421 Remove LinkTo positional params
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/components/generated-item.hbs
  ui/app/templates/components/identity/entity-nav.hbs
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/app/templates/vault/cluster/access/control-group-accessor.hbs
  ui/app/templates/vault/cluster/access/control-groups.hbs
  ui/app/templates/vault/cluster/access/identity/aliases/show.hbs
  ui/app/templates/vault/cluster/access/identity/show.hbs
  ui/app/templates/vault/cluster/access/method/section.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/details.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/details.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/index.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key/details.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/index.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider/details.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/scope/details.hbs
  ui/app/templates/vault/cluster/policies/index.hbs
  ui/app/templates/vault/cluster/policy/edit.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/app/templates/vault/cluster/secrets/backend/configuration.hbs
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/app/templates/vault/cluster/settings/auth/configure.hbs
  ui/app/templates/vault/cluster/settings/configure-secret-backend.hbs
  ui/lib/core/addon/components/toolbar-actions.js
  ui/lib/core/addon/components/toolbar-link.hbs
  ui/lib/core/addon/components/toolbar-link.js
  ui/lib/core/addon/templates/components/replication-summary-card.hbs
  ui/lib/kmip/addon/templates/configuration.hbs
  ui/lib/kmip/addon/templates/credentials/index.hbs
  ui/lib/kmip/addon/templates/credentials/show.hbs
  ui/lib/kmip/addon/templates/role.hbs
  ui/lib/kmip/addon/templates/scope/roles.hbs
  ui/lib/kmip/addon/templates/scopes/index.hbs
  ui/lib/replication/addon/templates/components/known-secondaries-card.hbs
  ui/lib/replication/addon/templates/mode/secondaries/config-show.hbs
  ui/lib/replication/addon/templates/mode/secondaries/index.hbs
  ui/package.json
  ui/tests/integration/components/toolbar-link-test.js
  ui/yarn.lock
Labels: ui

#17401 Update oracle.mdx
  website/content/docs/secrets/databases/oracle.mdx
Labels: pr/no-changelog, backport/1.11.x

#17431 Fix Vault version verification for ent editions
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
Labels: pr/no-changelog

#17220 Core: Persist Mount Table. One cicle
  vault/audit.go
  vault/auth.go
  vault/mount.go
Labels: waiting-for-response, pr/no-changelog

#17433 docs/ldap: rename openldap secrets to ldap secrets
  website/content/api-docs/secret/ldap.mdx
  website/content/docs/deprecation/faq.mdx
  website/content/docs/plugins/plugin-portal.mdx
  website/content/docs/secrets/databases/db2.mdx
  website/content/docs/secrets/ldap.mdx
  website/content/docs/upgrading/plugins.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, pr/no-changelog, backport/1.12.x

#17432 Template lint warning clean up
  ui/.template-lintrc.js
  ui/app/components/diff-version-selector.js
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/configure-aws-secret.hbs
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/database-role-setting-form.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/templates/components/diff-version-selector.hbs
  ui/app/templates/components/file-to-array-buffer.hbs
  ui/app/templates/components/generate-credentials-database.hbs
  ui/app/templates/components/namespace-link.hbs
  ui/app/templates/components/pgp-file.hbs
  ui/app/templates/components/pki/config-pki-ca.hbs
  ui/app/templates/components/raft-storage-overview.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/text-file.hbs
  ui/app/templates/components/transit-form-show.hbs
  ui/app/templates/vault/cluster/access/identity/aliases/show.hbs
  ui/app/templates/vault/cluster/access/identity/show.hbs
  ui/app/templates/vault/cluster/access/leases/list.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/lib/core/addon/templates/components/navigate-input.hbs
  ui/lib/core/addon/templates/components/shamir-flow.hbs
  ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
  ui/lib/replication/addon/templates/components/replication-summary.hbs
  ui/lib/replication/addon/templates/mode.hbs
Labels: ui

#17436 Fix RevocationSigAlgo support in OCSP
  builtin/logical/pki/ocsp.go
  builtin/logical/pki/path_fetch_issuers.go
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: bug, secret/pki, pr/no-changelog, backport/1.12.x

#17439 Don't allow write perms to plugins in test
  vault/external_plugin_test.go
Labels: pr/no-changelog, backport/1.12.x

#17428 Add warning on missing entity information
  builtin/logical/ssh/path_issue_sign.go
Labels: bug, secret/ssh, pr/no-changelog

#17378 only enable undo logs if all cluster members support it
  physical/raft/raft.go
  physical/raft/raft_autopilot.go
  vault/core.go
  vault/core_metrics.go
  vault/core_util.go
  vault/external_tests/raft/raft_autopilot_test.go
  vault/external_tests/raft/raft_test.go
  vault/ha.go
  vault/logical_system.go
  vault/raft.go
  vault/request_forwarding_rpc.go
  vault/testing.go
Labels: pr/no-changelog, backport/1.12.x

#17445 website: upgrade next version
  website/package-lock.json
  website/package.json
Labels: website, pr/no-changelog

#17443 Better docs on PKI key stuff
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.12.x

#17449 Fix RevocationSigAlg provisioning in GCP
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
Labels: bug, secret/pki, pr/no-changelog, backport/1.12.x

#17455 Add 'note' for surpassing dead server threshold time
  website/content/docs/commands/operator/raft.mdx
Labels: docs, pr/no-changelog

#17448 secrets/ldap: updates API documentation
  website/content/api-docs/secret/ldap.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#17454 Plugins: Add -version flag to 'vault plugin info'
  api/sys_plugins.go
  api/sys_plugins_test.go
  command/plugin_deregister_test.go
  command/plugin_info.go
  command/plugin_info_test.go
  command/plugin_reload_test.go
  command/plugin_test.go
  vault/logical_system.go
Labels: core/cli, core/api, pr/no-changelog, backport/1.12.x

#17453 disable undo logs by default for 1.12.0
  vault/raft.go
Labels: pr/no-changelog, backport/1.12.x

#16700 Fix for duplicate SANs in signed certificates
  builtin/logical/pki/backend_test.go
  changelog/16700.txt
  sdk/helper/certutil/helpers.go
Labels: bug, secret/pki, cryptosec

#17463 Don't include issuers on delta CRLs
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
Labels: bug, secret/pki, pr/no-changelog, backport/1.12.x

#17457 Fix off by one err in current month client count computation
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, backport/1.12.x

#17467 Delete empty test
  sdk/plugin/grpc_system_test.go
Labels: pr/no-changelog

#17183 Docs: What is Vault missing 'S' resolves: #16587
  website/content/docs/what-is-vault.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17476 Fix transform secrets flaky test
  ui/tests/acceptance/enterprise-transform-test.js
Labels: ui, pr/no-changelog

#17477 Docs: Update Transform API documentation
  website/content/api-docs/secret/transform.mdx
Labels: docs, secret/transit, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17481 secrets/ldap: updates documentation
  website/content/docs/secrets/ldap.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#17480 Remove Async-HVAC from recommended libraries list
  website/content/api-docs/libraries.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#17487 bump sdk to 1.12.0
  sdk/version/version_base.go
Labels: pr/no-changelog

#17488 import new sdk
  go.mod
Labels: pr/no-changelog

#17482 Enable Iron Bank integration
  .release/ci.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17474 docs: Update retry_join Known Issue versions
  website/content/partials/raft-retry-join-failure.mdx
Labels: docs, storage/raft, website, pr/no-changelog

#17496 VAULT-1603 add sys/quotas to root-only api path docs
  website/content/docs/enterprise/namespaces.mdx
Labels: docs, pr/no-changelog

#17460 Docs: Plugin versioning documentation
  website/content/api-docs/secret/databases/index.mdx
  website/content/api-docs/system/auth.mdx
  website/content/api-docs/system/mounts.mdx
  website/content/api-docs/system/plugins-catalog.mdx
  website/content/docs/commands/auth/enable.mdx
  website/content/docs/commands/auth/list.mdx
  website/content/docs/commands/auth/tune.mdx
  website/content/docs/commands/plugin/index.mdx
  website/content/docs/commands/plugin/info.mdx
  website/content/docs/commands/plugin/register.mdx
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/commands/secrets/list.mdx
  website/content/docs/commands/secrets/tune.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/upgrading/plugins.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#17497 Fix tidy-status, tidy-cancel on PR Secondaries
  builtin/logical/pki/path_tidy.go
  changelog/17497.txt
Labels: bug, secret/pki, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17468 The 2 year temporary disabling of this test has come to an end
  builtin/logical/database/rotation_test.go
Labels: pr/no-changelog

#17508 Update SDK to 1.12.1
  sdk/version/version_base.go
Labels: pr/no-changelog

#17305 Add pki zlint tests
  builtin/logical/pki/zlint_test.go
  helper/testhelpers/docker/testhelpers.go
Labels: secret/pki, test, pr/no-changelog

#17501 doc: fix broken link in transit api
  website/content/api-docs/secret/transit.mdx
Labels: docs, bug, pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17506 VAULT-8242 Add automerge functionality to backport
  .github/workflows/backport.yml
Labels: pr/no-changelog

#17393 PKI role non-default options
  ui/app/adapters/pki/pki-role-engine.js
  ui/app/models/pki/pki-role-engine.js
  ui/app/serializers/pki/pki-role-engine.js
  ui/app/styles/core/helpers.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/lib/core/addon/components/form-field-groups-loop.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/string-list.hbs
  ui/lib/core/addon/components/string-list.js
  ui/lib/pki/addon/components/pki-key-usage.hbs
  ui/lib/pki/addon/components/pki-key-usage.js
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/app/components/pki-key-usage.js
Labels: ui, pr/no-changelog

#17513 CODEOWNER - Remove Loann
  CODEOWNERS
Labels: pr/no-changelog

#17519 Docs/fix interoperability 2
  website/content/docs/interoperability-matrix.mdx
  website/content/docs/partnerships.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#17520 Update httpguts for GO-2022-0236 fix
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17518 fix formatting of telemetry
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/1.12.x

#17387 Fix a data race with rollbackPeriod.
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_tidy_test.go
  vault/core.go
  vault/core_util.go
  vault/rollback.go
  vault/testing.go
Labels: pr/no-changelog, backport/1.12.x

#17529 Add note about transit BYOK key formats
  website/content/docs/secrets/transit/index.mdx
Labels: docs, secret/transit, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17526 PKI: Fix small routing issues with SecretListHeader
  ui/lib/pki/addon/controllers/issuers/index.js
  ui/lib/pki/addon/controllers/keys/index.js
  ui/lib/pki/addon/routes/certificates.js
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/configuration/details.js
  ui/lib/pki/addon/routes/configuration/edit.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/configuration/tidy.js
  ui/lib/pki/addon/routes/issuers.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/keys.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/templates/certificates.hbs
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/lib/pki/addon/templates/issuers.hbs
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/keys.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
  ui/lib/pki/app/components/pki-key-usage.js
Labels: ui, pr/no-changelog

#17543 Upgrade Clean Up
  ui/app/initializers/deprecation-filter.js
  ui/app/styles/components/modal.scss
  ui/config/deprecation-workflow.js
  ui/ember-cli-build.js
  ui/package.json
  ui/yarn.lock
Labels: ui

#17544 Document the deletion_allowed transform flag
  website/content/api-docs/secret/transform.mdx
Labels: pr/no-changelog

#16622 Evaluate ssh validprincipals user template before splitting
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_issue_sign.go
  changelog/16622.txt
Labels: secret/ssh, cryptosec

#17547 core: move rollback period init to NewCore
  vault/core.go
  vault/core_util.go
Labels: pr/no-changelog, backport/1.12.x

#17539 Add storage check upgrade notes
  website/content/docs/concepts/storage.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/partials/ent-supported-storage.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.12.x

#17532 prevent memory leak when using control group factors in a policy
  changelog/17532.txt
  vault/acl.go
  vault/policy.go
Labels: backport/1.9.x, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17554 docs: add a missing letter to the upgrade guide
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17568 fix language in license changelog entry for 1.12
  CHANGELOG.md
Labels: pr/no-changelog

#17353 Add Artifactory build to the matrix
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  .github/enos-run-matrices/ent.json
  .github/enos-run-matrices/oss.json
  .github/workflows/build.yml
  .github/workflows/enos-run.yml
  .github/workflows/enos-verify-stable.yml
  .release/ci.hcl
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
  enos/modules/vault_artifactory_artifact/outputs.tf
  enos/modules/vault_artifactory_artifact/variables.tf
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_verify_unsealed/main.tf
Labels: pr/no-changelog

#17577 CLI: Fix secrets list -detailed headings
  changelog/17577.txt
  command/secrets_list.go
Labels: bug, core/cli, backport/1.12.x

#17566 docs: fix broken link to transit key wrap
  website/content/docs/secrets/transform/index.mdx
Labels: docs, secret/transit, pr/no-changelog, backport/1.12.x

#17581 Fix format strings missing an argument
  helper/testhelpers/docker/testhelpers.go
Labels: pr/no-changelog

#17574 website: fixes redirected links
  website/content/api-docs/secret/azure.mdx
  website/content/api-docs/secret/consul.mdx
  website/content/api-docs/secret/databases/cassandra.mdx
  website/content/api-docs/secret/databases/elasticdb.mdx
  website/content/api-docs/secret/databases/hanadb.mdx
  website/content/api-docs/secret/databases/influxdb.mdx
  website/content/api-docs/secret/databases/mongodb.mdx
  website/content/api-docs/secret/databases/mongodbatlas.mdx
  website/content/api-docs/secret/databases/mssql.mdx
  website/content/api-docs/secret/databases/mysql-maria.mdx
  website/content/api-docs/secret/databases/oracle.mdx
  website/content/api-docs/secret/databases/postgresql.mdx
  website/content/api-docs/secret/databases/redis.mdx
  website/content/api-docs/secret/databases/redshift.mdx
  website/content/api-docs/secret/databases/snowflake.mdx
  website/content/api-docs/secret/gcp.mdx
  website/content/docs/concepts/integrated-storage/autopilot.mdx
  website/content/docs/concepts/storage.mdx
  website/content/docs/configuration/sentinel.mdx
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/configuration/storage/index.mdx
  website/content/docs/faq/ssct.mdx
  website/content/docs/internals/integrated-storage.mdx
  website/content/docs/internals/limits.mdx
  website/content/docs/partnerships.mdx
  website/content/docs/release-notes/1.10.0.mdx
  website/content/docs/release-notes/1.12.0.mdx
  website/content/docs/secrets/consul.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
  website/content/docs/secrets/nomad.mdx
  website/content/docs/secrets/terraform.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: website, pr/no-changelog, backport/1.12.x

#17582 Fixed typo in USAGE line for kv metadata put/patch
  command/kv_metadata_patch.go
  command/kv_metadata_put.go
Labels: pr/no-changelog

#17586 Enos verify updates
  .github/workflows/enos-verify-stable.yml
Labels: pr/no-changelog

#17589 chore: Update Digital Team Files
  website/Makefile
  website/scripts/should-build.sh
  website/scripts/website-build.sh
  website/scripts/website-start.sh
Labels: pr/no-changelog, backport/1.12.x

#17585 website: reset redirects array
  website/redirects.js
Labels: website, pr/no-changelog, backport/1.12.x

#17593 database/snowflake: update plugin to v0.6.1
  changelog/17593.txt
  go.mod
  go.sum
Labels: backport/1.12.x

#16075 Update aws.mdx
  website/content/docs/auth/aws.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15507 Updated Name reported by k8s auth
  website/content/docs/concepts/identity.mdx
Labels: docs, enhancement, auth/k8s, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17592 website: fixes more broken links
  website/content/docs/agent/index.mdx
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/release-notes/1.12.0.mdx
Labels: website, pr/no-changelog, backport/1.12.x

#17597 [Release Notes] Add a note about storage support for VE
  website/content/docs/deprecation/index.mdx
  website/content/docs/release-notes/1.12.0.mdx
Labels: pr/no-changelog, backport/1.12.x

#17603 Download Enos test artifact only for CRT runs
  .github/workflows/enos-run.yml
Labels: pr/no-changelog

#17515 Add an enos scenario to test vault docker images using k8s/kind/helm
  .github/workflows/build.yml
  .github/workflows/enos-run-k8s.yml
  .gitignore
  enos/k8s/enos-modules-k8s.hcl
  enos/k8s/enos-providers-k8s.hcl
  enos/k8s/enos-scenario-k8s.hcl
  enos/k8s/enos-terraform-k8s.hcl
  enos/k8s/enos-variables-k8s.hcl
  enos/modules/build_local/main.tf
  enos/modules/k8s_deploy_vault/main.tf
  enos/modules/k8s_deploy_vault/raft-config.hcl
  enos/modules/k8s_deploy_vault/variables.tf
  enos/modules/k8s_vault_verify_build_date/main.tf
  enos/modules/k8s_vault_verify_build_date/variables.tf
  enos/modules/k8s_vault_verify_replication/main.tf
  enos/modules/k8s_vault_verify_replication/scripts/smoke-verify-replication.sh
  enos/modules/k8s_vault_verify_replication/variables.tf
  enos/modules/k8s_vault_verify_ui/main.tf
  enos/modules/k8s_vault_verify_ui/scripts/smoke-verify-ui.sh
  enos/modules/k8s_vault_verify_ui/variables.tf
  enos/modules/k8s_vault_verify_version/main.tf
  enos/modules/k8s_vault_verify_version/scripts/get-status.sh
  enos/modules/k8s_vault_verify_version/scripts/smoke-verify-version.sh
  enos/modules/k8s_vault_verify_version/variables.tf
  enos/modules/k8s_vault_verify_write_data/main.tf
  enos/modules/k8s_vault_verify_write_data/variables.tf
  enos/modules/load_docker_image/main.tf
  enos/modules/local_kind_cluster/main.tf
Labels: pr/no-changelog

#17611 Create remove-labels.yml
  .github/workflows/remove-labels.yml
Labels: pr/no-changelog

#17605 Add Enos scenarios and workflows for testing 1.12.x
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  .github/workflows/build.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/enos-run.yml
  .github/workflows/enos-verify-stable.yml
  .gitignore
  .release/ci.hcl
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/k8s/enos-modules-k8s.hcl
  enos/k8s/enos-providers-k8s.hcl
  enos/k8s/enos-scenario-k8s.hcl
  enos/k8s/enos-terraform-k8s.hcl
  enos/k8s/enos-variables-k8s.hcl
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/get_local_metadata/main.tf
  enos/modules/get_local_metadata/scripts/build_date.sh
  enos/modules/get_local_metadata/scripts/version.sh
  enos/modules/k8s_deploy_vault/main.tf
  enos/modules/k8s_deploy_vault/raft-config.hcl
  enos/modules/k8s_deploy_vault/variables.tf
  enos/modules/k8s_vault_verify_build_date/main.tf
  enos/modules/k8s_vault_verify_build_date/variables.tf
  enos/modules/k8s_vault_verify_replication/main.tf
  enos/modules/k8s_vault_verify_replication/scripts/smoke-verify-replication.sh
  enos/modules/k8s_vault_verify_replication/variables.tf
  enos/modules/k8s_vault_verify_ui/main.tf
  enos/modules/k8s_vault_verify_ui/scripts/smoke-verify-ui.sh
  enos/modules/k8s_vault_verify_ui/variables.tf
  enos/modules/k8s_vault_verify_version/main.tf
  enos/modules/k8s_vault_verify_version/scripts/get-status.sh
  enos/modules/k8s_vault_verify_version/scripts/smoke-verify-version.sh
  enos/modules/k8s_vault_verify_version/variables.tf
  enos/modules/k8s_vault_verify_write_data/main.tf
  enos/modules/k8s_vault_verify_write_data/variables.tf
  enos/modules/load_docker_image/main.tf
  enos/modules/local_kind_cluster/main.tf
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
  enos/modules/vault_artifactory_artifact/outputs.tf
  enos/modules/vault_artifactory_artifact/variables.tf
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_verify_unsealed/main.tf
  enos/modules/vault_verify_version/main.tf
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
Labels: pr/no-changelog

#17612 Intercept key_id from generic configmap and turn it into a wrapperv2 option
  changelog/17612.txt
  internalshared/configutil/kms.go
Labels: backport/1.12.x

#17613 PKI role create: fix issue with setting default key_bits on init and when key_type changes
  ui/app/models/pki/pki-role-engine.js
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/lib/pki/addon/components/pki-key-parameters.js
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
Labels: ui, pr/no-changelog

#17617 Add plugin versioning to 1.12.0 release notes
  CHANGELOG.md
Labels: docs, pr/no-changelog

#17620 UI: cleanup from sonarqube scan
  ui/app/services/replication-mode.js
  ui/app/styles/components/info-table-row.scss
  ui/app/styles/core/generic.scss
  ui/lib/core/addon/components/info-table-item-array.js
Labels: ui, pr/no-changelog

#17610 [CI-only] Update RedHat registry tag
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17618 Enos verify stable needs Artifactory variables
  .github/workflows/enos-run.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17516 Update vault to v1.8.1
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  go.mod
Labels: pr/no-changelog, backport/1.12.x

#17540 auth/azure: documents auth support for VMSS flexible orchestration
  changelog/17540.txt
  website/content/docs/auth/azure.mdx
Labels: docs

#17629 [QT-182] Fix broken k8s workflow for vault-enterprise
  .github/workflows/enos-run-k8s.yml
Labels: pr/no-changelog

#17596 added note regarding persistence for log level changes
  website/content/api-docs/system/loggers.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#17633 [QT-182] Fix broken k8s workflow for vault-enterprise (#17629)
  .github/workflows/enos-run-k8s.yml
Labels: pr/no-changelog

#17634 [QT-182] Fix broken k8s workflow for vault-enterprise (#17629)
  .github/workflows/enos-run-k8s.yml
Labels: pr/no-changelog

#17635 [QT-182] Fix broken k8s workflow for vault-enterprise (#17629)
  .github/workflows/enos-run-k8s.yml
Labels: pr/no-changelog

#17631 VAULT-9451 Fix data race in entity merge
  vault/identity_store_entities.go
  vault/identity_store_util.go
Labels: pr/no-changelog

#17638 Add AD mode to Transit's AEAD ciphers
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_decrypt.go
  builtin/logical/transit/path_encrypt.go
  changelog/17638.txt
  sdk/helper/keysutil/policy.go
  website/content/api-docs/secret/transit.mdx
Labels: enhancement, secret/transit

#17573 Backport pr 17294 1.11.x - Add documentation for KMIP features
  website/content/docs/secrets/kmip-profiles.mdx
  website/content/docs/secrets/kmip.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#17644 [API doc] Fix a broken link in KV v2 doc
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, backport/1.12.x

#17646 [docs] Added 'Manually Revocable' to the table
  website/content/docs/concepts/tokens.mdx
Labels: pr/no-changelog, backport/1.12.x

#17609 UI/vault 9268/pki component tests
  ui/app/models/pki/pki-role-engine.js
  ui/lib/core/addon/components/radio-select-ttl-or-string.hbs
  ui/lib/core/addon/components/radio-select-ttl-or-string.js
  ui/lib/core/addon/helpers/is-active-route.js
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/lib/pki/addon/components/pki-key-usage.hbs
  ui/lib/pki/addon/components/pki-key-usage.js
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/tests/helpers/pki-engine.js
  ui/tests/integration/components/pki/pki-key-parameters-test.js
  ui/tests/integration/components/pki/pki-key-usage-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/integration/components/pki/radio-select-ttl-or-string-test.js
Labels: ui, pr/no-changelog

#17651 docs/vault-helm: update cert-manager example
  website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17652 Fix rendering of custom response headers
  website/content/docs/configuration/listener/tcp.mdx
Labels: pr/no-changelog

#17650 Add PATCH support to Vault CLI
  changelog/17650.txt
  command/commands.go
  command/patch.go
  command/patch_test.go
  command/write.go
  website/content/docs/commands/patch.mdx
Labels: enhancement, core/cli

#17657 Clean up dev cert construction
  command/server/tls_util.go
Labels: core/dev, pr/no-changelog

#17677 UI: add labels to file inputs
  ui/app/templates/components/file-to-array-buffer.hbs
  ui/app/templates/components/pgp-file.hbs
  ui/app/templates/components/text-file.hbs
Labels: ui, pr/no-changelog

#17040 Store login MFA secret with tokenhelper
  changelog/17040.txt
  command/base.go
  command/login.go
  command/login_test.go
  command/write.go
  helper/testhelpers/testhelpers.go
  vault/external_tests/identity/aliases_test.go
  vault/external_tests/identity/login_mfa_totp_test.go
Labels: backport/1.11.x, backport/1.12.x

#17661 OIDC Alternate Path Bug
  changelog/17661.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/components/okta-number-challenge.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/okta-number-challenge.hbs
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/pages/components/auth-form.js
  ui/tests/unit/components/auth-form-test.js
Labels: ui, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17636 Add support for PKCSv1_5_NoOID signatures
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_sign_verify.go
  builtin/logical/transit/path_sign_verify_test.go
  changelog/17636.txt
  sdk/helper/keysutil/consts.go
  sdk/helper/keysutil/policy_test.go
  website/content/api-docs/secret/transit.mdx
Labels: enhancement, secret/transit

#17692 Tweak totp test to fix race failures
  helper/testhelpers/testhelpers.go
  vault/external_tests/identity/login_mfa_totp_test.go
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#17693 Default crl expiry
  builtin/logical/pki/storage.go
Labels: bug, secret/pki

#17694 Update POST /ssh/issue/:name in website/content/api-docs/secret/ssh.mdx
  website/content/api-docs/secret/ssh.mdx
Labels: docs, secret/ssh, pr/no-changelog

#17701 Add empty expiry crlConfig upgrade test
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/storage.go
  changelog/17693.txt
Labels: bug, secret/pki, pr/no-changelog

#16748 Docs: API overview text clarity & kv2 mention... #16746
  website/content/api-docs/index.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#17688 Backport of OIDC Alternate Path Bug into release/1.12.x
  changelog/17661.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/components/okta-number-challenge.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/okta-number-challenge.hbs
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/pages/components/auth-form.js
  ui/tests/unit/components/auth-form-test.js
Labels: bug

#17676 Add mTLS and Load Balancers section to Enterprise Replication Documentation
  website/content/docs/enterprise/replication.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17689 Backport of OIDC Alternate Path Bug into release/1.10.x
  changelog/17661.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/pages/components/auth-form.js
  ui/tests/unit/components/auth-form-test.js
Labels: bug

#17687 Backport of OIDC Alternate Path Bug into release/1.11.x
  changelog/17661.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/pages/components/auth-form.js
  ui/tests/unit/components/auth-form-test.js
Labels: bug

#17662 Fix tests - Update MongoDB driver
  helper/testhelpers/mongodb/mongodbhelper.go
  plugins/database/mongodb/connection_producer_test.go
  plugins/database/mongodb/mongodb_test.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#17033 Docs: API secret/ssh clarity on Create & Update
  website/content/api-docs/secret/ssh.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#17695 Update documentation for vault-helm v0.22.1 release
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#17728 Docs: Remove patch from 1.10.x docs
  website/data/docs-nav-data.json
Labels: docs, website, pr/no-changelog

#17727 Docs: Remove patch from 1.11.x docs
  website/data/docs-nav-data.json
Labels: docs, website, pr/no-changelog

#17725 Docs: Patch command ordering
  website/data/docs-nav-data.json
Labels: docs, website, pr/no-changelog

#17726 Docs: Remove patch from 1.12.x docs
  website/data/docs-nav-data.json
Labels: docs, website, pr/no-changelog

#14945 Vault Raw Read Support (CLI & Client)
  api/logical.go
  changelog/14945.txt
  command/format.go
  command/read.go
Labels: core/cli, core/client

#17730 Fix raw format for other commands, add to docs!
  command/base.go
  command/base_helpers.go
  command/format.go
  command/read.go
  command/util.go
  website/content/docs/commands/read.mdx
Labels: bug, core/cli, pr/no-changelog

#15869 don't create leases for AWS STS secrets
  builtin/logical/aws/secret_access_keys.go
  changelog/15869.txt
Labels: ecosystem, enhancement, secret/aws

#17740 Bump validity period check to satisfy CircleCI
  builtin/logical/pki/backend_test.go
Labels: secret/pki, pr/no-changelog

#17729 Add container's executor to host's group for copy
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#17705 Backport of Add empty expiry crlConfig upgrade test into release/1.12.x
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/storage.go
  changelog/17693.txt
Labels: bug, secret/pki

#17736 Update AWS secrets tests
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/stepwise_test.go
Labels: pr/no-changelog
