Repository hashicorp/vault, pull requests merged in 2022-03, with the labels that each got.

#14196 Fix autoseal health check race by passing metrics sink in CoreConfig
  vault/seal_autoseal_test.go
Labels: pr/no-changelog

#14320 Mirage clean up
  ui/mirage/factories/metrics/activity.js
  ui/mirage/factories/metrics/config.js
  ui/mirage/handlers/base.js
  ui/tests/pages/metrics.js
Labels: ui, pr/no-changelog

#14323 SSCT Optimizations (OSS)
  command/login_test.go
  helper/namespace/namespace.go
  vault/core_test.go
  vault/expiration_test.go
  vault/logical_system_test.go
  vault/request_handling_test.go
  vault/router.go
  vault/token_store.go
Labels: pr/no-changelog

#14327 Backport: SSCT Optimizations (OSS)
  command/login_test.go
  helper/namespace/namespace.go
  vault/core_test.go
  vault/expiration_test.go
  vault/logical_system_test.go
  vault/request_handling_test.go
  vault/router.go
  vault/token_store.go
Labels: pr/no-changelog

#13943 Correcting API documentation to show status is unauthenticated
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
Labels: pr/no-changelog, backport/website

#14326 update MFA changelog
  changelog/14025.txt
Labels: pr/no-changelog, backport/1.10.x

#14329 Logout with wrapped token
  changelog/14329.txt
  ui/app/routes/vault/cluster/logout.js
Labels: ui, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14313 UI/ Client count permissions empty states
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/error.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/vault/cluster/clients/error.hbs
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
Labels: ui, pr/no-changelog, backport/1.10.x

#14342 Backport of Logout with wrapped token into release/1.10.x
  changelog/14329.txt
  ui/app/routes/vault/cluster/logout.js
Labels: ui

#14346 specify LIST method in version-history API doc example
  website/content/api-docs/system/version-history.mdx
Labels: docs, website, pr/no-changelog

#14345 Backport of UI/ Client count permissions empty states into release/1.10.x
  ui/app/components/clients/history.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/error.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/vault/cluster/clients/error.hbs
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
Labels: ui

#14347 UI/Add error status
  ui/app/templates/components/clients/error.hbs
  ui/app/templates/vault/cluster/clients/error.hbs
Labels: ui, pr/no-changelog, backport/1.10.x

#14349 Backport of UI/Add error status into release/1.10.x
  ui/app/templates/components/clients/error.hbs
  ui/app/templates/vault/cluster/clients/error.hbs
Labels: ui

#14330 db plugin multiplexing: add test coverage
  builtin/logical/database/backend_test.go
  builtin/logical/database/mockv5.go
  builtin/logical/database/versioning_large_test.go
Labels: pr/no-changelog

#14348 Remove duplicated certificates from chains
  builtin/logical/pki/path_fetch.go
Labels: bug, secret/pki, pr/no-changelog, backport/1.10.x

#14353 Backport of Remove duplicated certificates from chains into release/1.10.x
  builtin/logical/pki/path_fetch.go
Labels: bug, secret/pki, cryptosec

#14336 update `vault login` docs to cover stdin default
  website/content/docs/commands/login.mdx
Labels: pr/no-changelog, backport/website

#14364 OSS side changes of PKI HSM key type handling fix
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/managed_key_util.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/util.go
Labels: pr/no-changelog

#14366 docs: fix typo in CF auth ca maintenance
  website/content/docs/auth/cf.mdx
Labels: pr/no-changelog, backport/website

#14373 Updating website for 1.9.4
  website/data/version.js
Labels: pr/no-changelog, backport/website

#14379 UI/ Fix version check typo
  ui/app/routes/vault/cluster.js
Labels: ui, pr/no-changelog, backport/1.10.x

#14370 Only create new batch tokens if we're on at least 1.10.0
  vault/core_test.go
  vault/token_store.go
  vault/version_store.go
  vault/version_store_test.go
Labels: pr/no-changelog

#14314 [VAULT-5268] Add mount move docs
  website/content/api-docs/system/remount.mdx
  website/content/docs/commands/auth/move.mdx
  website/content/docs/commands/secrets/move.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x

#14384 Backport 1.10.0: Only create new batch tokens if we're on at least 1.10.0
  vault/core_test.go
  vault/token_store.go
  vault/version_store.go
  vault/version_store_test.go
Labels: pr/no-changelog

#14387 Backport/web UI gitkeep
  http/web_ui/.gitkeep
Labels: pr/no-changelog

#14302 MFA docs for config endpoints
  website/content/api-docs/secret/identity/index.mdx
  website/content/api-docs/secret/identity/mfa/duo.mdx
  website/content/api-docs/secret/identity/mfa/index.mdx
  website/content/api-docs/secret/identity/mfa/login-enforcement.mdx
  website/content/api-docs/secret/identity/mfa/okta.mdx
  website/content/api-docs/secret/identity/mfa/pingid.mdx
  website/content/api-docs/secret/identity/mfa/totp.mdx
  website/data/api-docs-nav-data.json
Labels: pr/no-changelog

#14378 Vault-4964: Update Managed Key documentation for AWS KMS
  website/content/api-docs/system/managed-keys.mdx
  website/content/docs/enterprise/managed-keys.mdx
Labels: pr/no-changelog, backport/1.10.x

#14317 Login MFA docs
  website/content/api-docs/secret/identity/mfa/index.mdx
  website/content/api-docs/system/mfa/validate.mdx
  website/content/docs/auth/login-mfa.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#14396 [QTI-188] Update the UI tests to be able to run against a cluster on a separate host.
  ui/package.json
  ui/scripts/enos-test-ember.js
  ui/scripts/start-vault.js
  ui/scripts/test-helper.js
  ui/testem.enos.js
  ui/tests/acceptance/unseal-test.js
  ui/tests/pages/auth.js
Labels: pr/no-changelog

#14395 Fix version check
  vault/token_store.go
  vault/version_store.go
Labels: pr/no-changelog

#14401 Backport 1.10: Fix version check
  vault/token_store.go
  vault/version_store.go
Labels: pr/no-changelog

#14403 [QTI-188] Add test-ember-enos Makefile target, update enos-test-ember script to accept additional parameters
  Makefile
  ui/scripts/enos-test-ember.js
Labels: pr/no-changelog

#13540 Add support for PROXY protocol v2 in TCP listener
  changelog/13540.txt
  command/server/listener_tcp_test.go
  command/server/listener_test.go
  go.mod
  go.sum
  helper/proxyutil/proxyutil.go
Labels: core, backport/1.10.x

#14318 fix spelling of identity
  website/content/docs/concepts/identity.mdx
Labels: pr/no-changelog, backport/website

#14385 Set systemd service type to notify
  .release/linux/package/usr/lib/systemd/system/vault.service
  changelog/14385.txt
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14406 remove mount accessor from MFA config
  helper/proxyutil/proxyutil.go
  vault/external_tests/identity/login_mfa_duo_test.go
  vault/identity_store.go
  vault/login_mfa.go
  website/content/api-docs/secret/identity/mfa/duo.mdx
  website/content/api-docs/secret/identity/mfa/okta.mdx
  website/content/api-docs/secret/identity/mfa/pingid.mdx
  website/content/docs/auth/login-mfa.mdx
Labels: pr/no-changelog, backport/1.10.x

#14423 Remove unneeded comments
  command/kv_put.go
Labels: pr/no-changelog

#14161 Update index.mdx
  website/content/api-docs/index.mdx
Labels: docs, pr/no-changelog, backport/website

#14426 identity/oidc: prevent key rotation on performance secondary clusters
  changelog/14426.txt
  vault/identity_store_oidc.go
Labels: backport/1.10.x

#14369 rename Dockerfile build-arg VERSION to PRODUCT_VERSION
  Dockerfile
  Makefile
Labels: pr/no-changelog

#14422 UI/add managed ns redirect prefix
  changelog/14422.txt
  ui/app/routes/vault/cluster.js
  ui/tests/acceptance/managed-namespace-test.js
Labels: ui, bug, backport/1.9.x, backport/1.10.x

#14430 MfaForm Update
  ui/app/templates/components/mfa-form.hbs
Labels: ui, pr/no-changelog, backport/1.10.x

#14436 Backport of UI/add managed ns redirect prefix into release/1.10.x
  changelog/14422.txt
  ui/app/routes/vault/cluster.js
  ui/tests/acceptance/managed-namespace-test.js
Labels: ui, backport, bug

#14440 Backport of UI/add managed ns redirect prefix into release/1.9.x
  changelog/14422.txt
  ui/app/routes/vault/cluster.js
  ui/tests/acceptance/managed-namespace-test.js
Labels: ui, backport, bug

#14442 Revert "Remove docs changes from CODEOWNERS"
  CODEOWNERS
Labels: pr/no-changelog

#14414 Add a place for us to link to external plugin examples/guides.
  website/content/docs/internals/plugins.mdx
Labels: backport/website

#14445 Fixing typo from "fo" to "of"
  website/content/docs/concepts/client-count/faq.mdx
Labels: pr/no-changelog, backport/website

#14447 Update error codes that are retried.
  website/content/docs/commands/index.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: backport/website, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14389 Add Enigma Vault secret plugin to community plugin list
  changelog/14389.txt
  website/content/docs/internals/plugins.mdx
Labels: enhancement, ecosystem/plugin, backport/website, backport/1.10.x

#14457 added add_basic_constraints parameter to PKI API docs
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/website

#14363 add tip for how to force a secrets engine disable
  website/content/api-docs/system/mounts.mdx
  website/content/docs/commands/secrets/disable.mdx
Labels: docs, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14471 UI/fix flaky clients current test
  ui/tests/acceptance/client-current-test.js
Labels: ui, pr/no-changelog, backport/1.10.x

#14400 UI/Hide empty masked PKI row values
  changelog/14400.txt
  ui/app/templates/components/config-pki-ca.hbs
  ui/app/templates/components/generate-credentials.hbs
  ui/app/templates/components/pki-cert-show.hbs
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/secrets/backend/pki/cert-test.js
  ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
  ui/tests/helpers/pki.js
  ui/tests/pages/components/config-pki-ca.js
Labels: ui, backport/1.10.x

#14476 Document the managed key PKCS#11 parameter key_id.
  website/content/api-docs/system/managed-keys.mdx
Labels: pr/no-changelog, backport/1.10.x

#14479 stable-website Backport: added add_basic_constraints parameter to PKI API docs (#14457)
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki

#14478 1.10 Backport: added add_basic_constraints parameter to PKI API docs (#14457)
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki

#14480 1.9 backport: added add_basic_constraints parameter to PKI API docs (#14457)
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki

#14466 Turn nvd security scanning off temporarily
  .release/security-scan.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14473 Backport of UI/Hide empty masked PKI row values into release/1.10.x
  changelog/14400.txt
  ui/app/templates/components/config-pki-ca.hbs
  ui/app/templates/components/generate-credentials.hbs
  ui/app/templates/components/pki-cert-show.hbs
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/secrets/backend/pki/cert-test.js
  ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
  ui/tests/helpers/pki.js
  ui/tests/pages/components/config-pki-ca.js
Labels: ui, backport

#14439 Fix description of StringSliceVar options
  command/auth_enable.go
  command/auth_tune.go
  command/secrets_enable.go
  command/secrets_tune.go
Labels: core/cli, pr/no-changelog

#14425 add MFA validation support to vault login command
  command/base.go
  command/login.go
  command/write.go
  vault/login_mfa.go
Labels: pr/no-changelog, backport/1.10.x

#14324 auth/ldap: add username_as_alias configurable
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_login.go
  changelog/14324.txt
  sdk/helper/ldaputil/config.go
  sdk/helper/ldaputil/config_test.go
  website/content/api-docs/auth/ldap.mdx
  website/content/docs/auth/ldap.mdx
Labels: backport/1.9.x, backport/1.10.x

#14495 Introduce fips version-agnostic build tag
  helper/constants/fips.go
  helper/constants/fips_build_check.go
  helper/constants/fips_cgo_check.go
Labels: pr/no-changelog, backport/1.10.x

#14492 Fixes from mount move testing
  changelog/mount-migration.txt
  vault/logical_system.go
  vault/logical_system_test.go
  website/content/docs/commands/auth/move.mdx
Labels: pr/no-changelog, backport/1.10.x

#14488 oss port: semgrep fixes
  sdk/plugin/grpc_storage.go
  vault/ui.go
Labels: pr/no-changelog

#14482 Addition to security model
  website/content/docs/internals/security.mdx
Labels: pr/no-changelog, backport/website

#14507 Handle the empty mount accessor case in client counts
  vault/activity_log.go
Labels: pr/no-changelog, backport/1.10.x

#14508 UI: Parse OpenAPI response correctly if schema includes $ref
  changelog/14508.txt
  ui/app/services/path-help.js
Labels: ui, enhancement, pr/no-changelog

#11584 Update mholt/archiver to v3.5.1
  command/debug.go
  command/debug_test.go
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog

#14519 vault/external_tests/raft: fix dropped test error
  vault/external_tests/raft/raft_test.go
Labels: pr/no-changelog

#14489 UI/fix kv data cache
  changelog/14489.txt
  ui/app/adapters/secret-v2-version.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/tests/acceptance/access/identity/_shared-alias-tests.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/pages/components/identity/edit-form.js
Labels: ui, bug, backport/1.9.x, backport/1.10.x

#14392 Server Side Consistency Docs
  CHANGELOG.md
  changelog/14109.txt
  website/content/docs/configuration/replication.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: docs, pr/no-changelog

#14533 Backport 1.9.5: UI/fix kv data cache (#14489)
  changelog/14489.txt
  ui/app/adapters/secret-v2-version.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/tests/acceptance/access/identity/_shared-alias-tests.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/pages/components/identity/edit-form.js
Labels: ui, backport, bug

#14493 UI/d3 DOM cleanup hover issue
  changelog/14493.txt
  ui/app/components/clients/horizontal-bar-chart.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
Labels: ui, bug, backport/1.10.x

#14536 Update gitignore
  .gitignore
Labels: pr/no-changelog, devex, backport/1.9.x, backport/1.10.x

#14537 Backport: UI/d3 DOM cleanup hover issue
  changelog/14493.txt
  ui/app/components/clients/horizontal-bar-chart.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
Labels: ui, bug

#14539 Backport of Update gitignore into release/1.9.x
  .gitignore
Labels: backport, pr/no-changelog

#14546 New Vault docs for 1.10
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/auth/login-mfa/index.mdx
  website/content/docs/concepts/client-count/faq.mdx
  website/content/docs/deprecation/faq.mdx
  website/content/docs/deprecation/index.mdx
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/faq/index.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x

#14548 New agent injector doc for vault 1.10
  website/content/docs/platform/k8s/injector-csi.mdx
  website/data/docs-nav-data.json
  website/public/img/comparison-table.png
  website/public/img/k8s-auth-workflow.png
  website/public/img/vault-csi-workflow.png
  website/public/img/vault-sidecar-inject-workflow.png
Labels: pr/no-changelog, backport/1.10.x

#14532 Addressing various Ember depreciations required for 4.0
  ui/app/components/link-to.js
  ui/app/styles/components/sidebar.scss
  ui/app/styles/components/tabs.scss
  ui/app/styles/core/navbar.scss
  ui/app/templates/components/configure-pki-secret.hbs
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/components/secret-list-header-tab.hbs
  ui/app/templates/components/secret-list-header.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/config/environment.js
  ui/lib/replication/addon/templates/mode.hbs
  ui/package.json
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/acceptance/not-found-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/helpers/clients.js
  ui/tests/pages/access/methods.js
Labels: ui, pr/no-changelog

#14543 identity/oidc: fix duplicate keys in well-known
  changelog/14543.txt
  vault/identity_store_oidc.go
  vault/identity_store_oidc_test.go
Labels: backport/1.9.x, backport/1.10.x

#14542 Rename master key -> root key in docs
  website/content/api-docs/secret/totp.mdx
  website/content/api-docs/system/generate-recovery-token.mdx
  website/content/api-docs/system/generate-root.mdx
  website/content/api-docs/system/init.mdx
  website/content/api-docs/system/rekey.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/unseal.mdx
  website/content/docs/commands/operator/init.mdx
  website/content/docs/commands/operator/rekey.mdx
  website/content/docs/commands/operator/seal.mdx
  website/content/docs/commands/operator/unseal.mdx
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/index.mdx
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/hsm/behavior.mdx
  website/content/docs/enterprise/hsm/index.mdx
  website/content/docs/enterprise/hsm/security.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/glossary.mdx
  website/content/docs/internals/architecture.mdx
  website/content/docs/internals/rotation.mdx
  website/content/docs/internals/security.mdx
  website/content/intro/getting-started/deploy.mdx
Labels: pr/no-changelog, backport/1.10.x

#14514 Backport of oss port: semgrep fixes into release/1.10.x
  sdk/plugin/grpc_storage.go
  vault/ui.go
Labels: pr/no-changelog

#14556 Vault documentation: added new note for AWS KMS doc
  website/content/docs/secrets/key-management/awskms.mdx
Labels: pr/no-changelog, backport/website

#14550 New server side consistent token faq for vault 1.10
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/auth/login-mfa/index.mdx
  website/content/docs/configuration/replication.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/faq/ssct.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x

#14515 Update docs for change to kms_key
  website/content/api-docs/system/managed-keys.mdx
Labels: pr/no-changelog, backport/1.10.x

#14540 Backport of Update gitignore into release/1.10.x
  .gitignore
Labels: backport, pr/no-changelog

#14544 Add mount move concepts page, update api docs
  website/content/api-docs/system/remount.mdx
  website/content/docs/concepts/mount-migration.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x

#14557 Ember deprecations cont.
  ui/app/components/auth-form.js
  ui/app/helpers/dot-to-dash.js
  ui/app/helpers/format-duration.js
  ui/app/helpers/format-ttl.js
  ui/app/helpers/format-utc.js
  ui/app/helpers/parse-date-string.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/transit-form-show.hbs
  ui/tests/integration/helpers/format-duration-test.js
  ui/tests/integration/helpers/format-ttl-test.js
  ui/tests/integration/helpers/format-utc-test.js
  ui/tests/unit/helpers/dot-to-dash-test.js
  ui/tests/unit/helpers/parse-date-string-test.js
Labels: ui, pr/no-changelog

#14571 LinkTo Updates
  ui/app/components/secret-link.js
  ui/app/services/permissions.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/components/secret-link.hbs
  ui/app/templates/components/secret-version-menu.hbs
  ui/app/templates/components/section-tabs.hbs
  ui/app/templates/vault/cluster.hbs
  ui/app/templates/vault/cluster/access/leases/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/error.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/lib/core/addon/components/form-save-buttons.js
  ui/lib/core/addon/components/list-item.js
  ui/lib/core/addon/components/list-pagination.js
  ui/lib/core/addon/templates/components/form-save-buttons.hbs
  ui/lib/core/addon/templates/components/list-item.hbs
  ui/lib/core/addon/templates/components/list-pagination.hbs
  ui/lib/kmip/addon/components/edit-form-kmip-role.js
  ui/lib/kmip/addon/templates/components/edit-form-kmip-role.hbs
  ui/tests/unit/services/permissions-test.js
Labels: ui, pr/no-changelog

#14545 OIDC Logout Bug
  changelog/14545.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/helpers/oidc-window-stub.js
  ui/tests/integration/components/auth-jwt-test.js
Labels: ui, bug, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14578 Backport of OIDC Logout Bug into release/1.9.x
  changelog/14545.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/helpers/oidc-window-stub.js
  ui/tests/integration/components/auth-jwt-test.js
Labels: backport

#14577 Backport of OIDC Logout Bug into release/1.8.x
  changelog/14545.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/helpers/oidc-window-stub.js
  ui/tests/integration/components/auth-jwt-test.js
Labels: backport

#14566 sys/mfa/validate should forward
  vault/login_mfa.go
Labels: pr/no-changelog, backport/1.10.x

#14576 Backport of OIDC Logout Bug into release/1.10.x
  changelog/14545.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/helpers/oidc-window-stub.js
  ui/tests/integration/components/auth-jwt-test.js
Labels: backport

#14579 website: add api -> api-docs redirect
  website/redirects.next.js
Labels: website, pr/no-changelog, backport/website

#14513 Add Semgrep Rules to OSS
  .circleci/config.yml
  .circleci/config/commands/setup-semgrep.yml
  .circleci/config/jobs/semgrep.yml
  .circleci/config/workflows/ci.yml
  Makefile
  scripts/semgrep_plugin_repos.sh
  tools/semgrep/ci/atomic.yml
  tools/semgrep/ci/bad-multierror-append.yml
  tools/semgrep/ci/bad-nil-guard.yml
  tools/semgrep/ci/error-shadowing.yml
  tools/semgrep/ci/hashsum.yml
  tools/semgrep/ci/hmac-bytes.yml
  tools/semgrep/ci/hmac-hash.yml
  tools/semgrep/ci/logger-format-string.yml
  tools/semgrep/ci/no-nil-check.yml
  tools/semgrep/ci/oddifsequence.yml
  tools/semgrep/ci/return-nil-error.yml
  tools/semgrep/ci/return-nil.yml
  tools/semgrep/ci/wrongerrcall.yml
  tools/semgrep/ci/wronglock.yml
  tools/semgrep/hostport.yml
  tools/semgrep/joinpath.yml
  tools/semgrep/lock-not-unlocked-on-return.yml
  tools/semgrep/logger-sprintf.yml
  tools/semgrep/paths-with-callbacks-and-operations.yml
  tools/semgrep/paths-with-callbacks.yml
  tools/semgrep/physical-storage.yml
  tools/semgrep/self-equals.yml
  vault/ui.go
Labels: pr/no-changelog

#14590 Minor format updates
  website/content/docs/internals/plugins/plugin-architecture.mdx
Labels: pr/no-changelog

#14377 Documentation changes in /sys/managed-keys
  website/content/api-docs/system/managed-keys.mdx
Labels: pr/no-changelog, backport/1.10.x

#14593 Use FieldData.GetOkError() to access required Transit parameters.
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_hash.go
  builtin/logical/transit/path_hash_test.go
  builtin/logical/transit/path_trim.go
  changelog/14074.txt
Labels: pr/no-changelog, backport/1.10.x

#14595 OIDC Test Fix
  ui/tests/integration/components/auth-jwt-test.js
Labels: ui, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14555 oidc provider: add test case for clients sharing keys
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#14584 Remove record.toJSON()
  ui/app/adapters/policy.js
Labels: ui, pr/no-changelog

#14551 UI/Wrong sentinel error message for auth methods
  changelog/14551.txt
  ui/app/adapters/secret-engine.js
  ui/app/components/config-pki-ca.js
  ui/app/components/config-pki.js
  ui/app/components/mount-backend-form.js
  ui/app/mixins/policy-edit-controller.js
  ui/app/models/policy.js
  ui/app/templates/components/config-pki-ca.hbs
  ui/app/templates/components/config-pki.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/vault/cluster/policies/create.hbs
  ui/lib/core/addon/components/message-error.js
  ui/lib/core/addon/templates/components/message-error.hbs
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/settings/configure-secret-backends/pki/section-urls-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/ttl-picker-test.js
  ui/tests/pages/components/auth-form.js
Labels: ui, backport, bug, backport/1.9.x, backport/1.10.x

#14610 Double the timeout for requests in the dbplugin test helpers to avoid sporadic test failures.
  sdk/database/dbplugin/v5/testing/test_helpers.go
Labels: pr/no-changelog, backport/1.10.x

#14614 Logout Auth Method Test Update
  ui/tests/acceptance/logout-auth-method-test.js
Labels: ui, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14618 Run UI tests in backport/ui/ prefixed branches
  .circleci/config.yml
  .circleci/config/commands/exit-if-branch-does-not-need-test-ui.yml
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14616 Backport of Logout Auth Method Test Update into release/1.8.x
  ui/tests/acceptance/logout-auth-method-test.js
Labels: ui, backport

#14617 Backport of Logout Auth Method Test Update into release/1.10.x
  ui/tests/acceptance/logout-auth-method-test.js
Labels: ui, backport

#14627 Sync license deletion docs from Enterprise
  website/content/api-docs/system/license.mdx
Labels: docs, pr/no-changelog, backport/website, backport/1.10.x

#14626 Remove defaultSerializer
  ui/app/adapters/role-ssh.js
  ui/app/adapters/ssh.js
Labels: ui, pr/no-changelog

#14597 Ember With to Let
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/components/identity/popup-alias.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/secret-list-header.hbs
  ui/app/templates/components/section-tabs.hbs
  ui/app/templates/components/wizard/init-unseal.hbs
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
Labels: ui, pr/no-changelog

#14623 Backport: UI/Wrong sentinel error message for auth methods #14551
  changelog/14551.txt
  ui/app/adapters/secret-engine.js
  ui/app/components/mount-backend-form.js
  ui/app/templates/components/mount-backend-form.hbs
  ui/tests/acceptance/settings/mount-secret-backend-test.js
Labels: ui, backport, bug

#14596 Runloop/Computed Dot Access Removal
  ui/app/components/auth-info.js
  ui/app/components/console/ui-panel.js
  ui/app/models/secret-engine.js
  ui/stories/auth-config-form/config.stories.js
  ui/stories/auth-config-form/options.stories.js
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/integration/components/control-group-success-test.js
  ui/tests/integration/components/edit-form-kmip-role-test.js
  ui/tests/integration/components/edit-form-test.js
  ui/tests/integration/components/mfa-form-test.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/unit/components/auth-jwt-test.js
Labels: ui, pr/no-changelog

#14632 Backport: UI/Wrong sentinel error message for auth methods #14551
  changelog/14551.txt
  ui/app/adapters/secret-engine.js
  ui/app/components/mount-backend-form.js
  ui/app/templates/components/mount-backend-form.hbs
  ui/tests/acceptance/settings/mount-secret-backend-test.js
Labels: ui, backport, bug

#14608 Vault documentation: added new client count faqs for vault 1.10
  website/content/docs/concepts/client-count/faq.mdx
  website/public/img/vault-usage-metrics-1-10.png
Labels: pr/no-changelog, backport/1.10.x

#14605 Vault documentation: added release notes for vault 1.10
  website/content/docs/release-notes/1.10.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x

#14646 Route renderTemplate Deprecation
  ui/app/routes/loading.js
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/app/templates/components/oidc-callback-splash.hbs
  ui/app/templates/loading.hbs
  ui/app/templates/vault/cluster/oidc-callback.hbs
  ui/lib/core/addon/components/masked-input.js
Labels: ui, pr/no-changelog

#14509 docs/multiplexing: overhaul plugin documentation
  website/content/docs/auth/azure.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/internals/limits.mdx
  website/content/docs/internals/plugins.mdx
  website/content/docs/partnerships.mdx
  website/content/docs/plugin.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/docs/plugins/plugin-development.mdx
  website/content/docs/plugins/plugin-management.mdx
  website/content/docs/plugins/plugin-portal.mdx
  website/content/docs/secrets/databases/custom.mdx
  website/content/docs/secrets/venafi.mdx
  website/content/docs/upgrading/plugins.mdx
  website/data/docs-nav-data.json
  website/redirects.next.js
Labels: docs, pr/no-changelog, backport/1.10.x

#14649 docs: provide mfa configuration guidance
  website/content/docs/auth/login-mfa/index.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#14654 docs/ssct: change service side to server side
  website/content/docs/configuration/replication.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/faq/ssct.mdx
  website/content/docs/release-notes/1.10.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#14647 Update website for 1.10.0
  website/data/version.js
Labels: pr/no-changelog

#14311 Create OpenApi spec w/ dynamically generated plugins
  scripts/gen_openapi.sh
Labels: pr/no-changelog

#14655 docs/db2: adds documentation reference to db2 learn tutorial
  website/content/docs/secrets/databases/db2.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, backport/website

#14636 identity/oidc: updates documentation for PKCE, client types, and default resources
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/docs/concepts/oidc-provider.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: docs, pr/no-changelog, backport/website

#14641 crt: use the latest version of actions-packaging-linux@v1
  .github/workflows/build.yml
Labels: pr/no-changelog

#14642 crt: use the latest version of actions-packaging-linux@v1
  .github/workflows/build.yml
Labels: pr/no-changelog

#14661 PKI: Add missing default cases within switch statements
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_root.go
Labels: pr/no-changelog

#14674 Backport: identity/oidc: updates documentation for PKCE, client types, and default resources (#14636)
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/docs/concepts/oidc-provider.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: docs, pr/no-changelog

#14676 Backport: identity/oidc: updates documentation for PKCE, client types, and default resources (#14636)
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/docs/concepts/oidc-provider.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: docs, pr/no-changelog

#14680 Vault documentation: fixed release note version for 1.10.0
  website/content/docs/release-notes/1.10.0.mdx
  website/data/docs-nav-data.json
  website/redirects.next.js
Labels: pr/no-changelog, backport/website

#14684 Vault documentation: add link to AAD document from Deprecation notice table
  website/content/docs/deprecation/index.mdx
Labels: pr/no-changelog, backport/website

#14685 Vault documentation: added known issues to 1.10.x upgrade guide
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: pr/no-changelog, backport/website

#14683 Vault documentation: fixed broken links in release notes 1.10.0
  website/content/docs/release-notes/1.10.0.mdx
Labels: pr/no-changelog, backport/website

#14693 Update to 1.10.1
  sdk/version/version_base.go
Labels: pr/no-changelog

#14692 Vault documentation: addressed recent feedback for client count faq
  website/content/docs/concepts/client-count/faq.mdx
Labels: pr/no-changelog, backport/website

#14675 Computed Property Overridability
  ui/app/services/auth.js
  ui/app/services/store.js
Labels: ui, pr/no-changelog

#14699 Add a note that PKI with RSA keys only currently supports PKCS#1 v1.5 signatures
  website/content/api-docs/secret/pki.mdx
Labels: pr/no-changelog, backport/website, backport/1.10.x

#14677 Replace http method strings with net/http constants
  api/auth_token.go
  api/client_test.go
  api/help.go
  api/logical.go
  api/output_string.go
  api/ssh.go
  api/ssh_agent.go
  api/sys_audit.go
  api/sys_auth.go
  api/sys_capabilities.go
  api/sys_config_cors.go
  api/sys_generate_root.go
  api/sys_hastatus.go
  api/sys_health.go
  api/sys_init.go
  api/sys_leader.go
  api/sys_leases.go
  api/sys_monitor.go
  api/sys_mounts.go
  api/sys_plugins.go
  api/sys_policy.go
  api/sys_raft.go
  api/sys_rekey.go
  api/sys_rotate.go
  api/sys_seal.go
  api/sys_stepdown.go
Labels: pr/no-changelog

#14705 Vault documentation: fixed spelling error in deprecation notice
  website/content/docs/deprecation/faq.mdx
Labels: pr/no-changelog, backport/website

#14704 Vault-4010 Unauthenticated panic when processing "help" requests
  changelog/14704.txt
  http/help.go
  http/help_test.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14708 docs: adds known issue for UI sign in using OIDC auth method
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: docs, pr/no-changelog, backport/website

#14670 Warn on upper case in policy name
  changelog/14670.txt
  command/policy_write.go
  vault/logical_system.go
Labels: backport/1.10.x

#14679 [RelAPI Onboarding] Add release API metadata file
  .release/release-metadata.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14717 Vault documentation: added new vault lambda extension doc
  website/content/docs/platform/aws/index.mdx
  website/content/docs/platform/aws/lambda-extension-cache.mdx
  website/content/docs/platform/aws/run.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/website

#14522 Fix panic caused by parsing `json.Number` values for TypeCommaStringSlice fields
  api/go.mod
  api/go.sum
  changelog/14522.txt
  go.mod
  go.sum
  sdk/framework/field_data_test.go
  sdk/go.mod
  sdk/go.sum
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14718 Update Vault to use api/v1.5.0
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  go.mod
  go.sum
Labels: pr/no-changelog

#14747 Remove Unknown Arguments From Builtin Components
  ui/app/templates/components/auth-info.hbs
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/components/secret-version-menu.hbs
Labels: ui, pr/no-changelog

#12965 cockroachdb: add high-availability support
  changelog/12965.txt
  physical/cockroachdb/cockroachdb.go
  physical/cockroachdb/cockroachdb_ha.go
  physical/cockroachdb/cockroachdb_test.go
Labels: enhancement, core/storage, backport/1.10.x

#14758 Vault documentation: removed extra entry in the telemetry doc
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/website
