Repository hashicorp/vault, pull requests merged in 2022-07, with the labels that each got.

#15968 Docs/ekm sql provider corrections
  website/content/docs/platform/mssql/installation.mdx
  website/content/docs/platform/mssql/troubleshooting.mdx
Labels: pr/no-changelog, backport/1.11.x

#16058 Adding Vault HydrantID Pki Plugin
  website/content/docs/plugins/plugin-portal.mdx
Labels: ecosystem/plugin, pr/no-changelog, backport/1.11.x

#16220 Seal/Unseal docs: Improve readability, fix master key occurrence and typos
  website/content/docs/concepts/seal.mdx
Labels: pr/no-changelog, backport/1.11.x

#16175 vault documentation: updated examples to use volumes
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
  website/content/docs/platform/k8s/helm/run.mdx
Labels: pr/no-changelog, backport/1.11.x

#16157 VAULT-6614 Enable role based quotas for lease-count quotas (OSS)
  builtin/plugin/backend.go
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  http/util.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/core.go
  vault/core_util.go
  vault/expiration.go
  vault/expiration_test.go
  vault/logical_system_quotas.go
  vault/logical_system_test.go
  vault/login_mfa.go
  vault/quotas/quotas.go
  vault/request_forwarding_service.pb.go
  vault/request_handling.go
  vault/request_handling_util.go
  vault/token_store_test.go
  vault/tokens/token.pb.go
  vault/wrapping.go
Labels: pr/no-changelog

#16211 Minor grammar correction in help for login command
  command/login.go
  website/content/docs/commands/login.mdx
Labels: pr/no-changelog

#16226 Update 'master key' -> 'root key'
  website/content/docs/concepts/seal.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16242 Vault documentation: added content for network guidance for KMIP
  website/content/docs/secrets/kmip.mdx
Labels: pr/no-changelog, backport/1.11.x

#16244 Vault documentation: added info about new policy flag
  website/content/docs/commands/index.mdx
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog, backport/1.11.x

#16246 pki: When a role sets key_type to any ignore key_bits value when signing a csr
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_roles.go
  changelog/16246.txt
  website/content/api-docs/secret/pki.mdx
Labels: bug, secret/pki, backport/1.10.x, backport/1.11.x

#16251 secrets/k8s: updates API docs for kubernetes_host env var
  website/content/api-docs/secret/kubernetes.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16263 remove GetCoreConfigInternal from logger API tests
  vault/logical_system_test.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16262 Backport pki test_helpers to reduce backport friction to 1.10
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/test_helpers.go
Labels: pr/no-changelog

#16270 Throw SSCT Error In Some Cases
  vault/request_handling.go
Labels: pr/no-changelog

#16202 docs/configuration: document CockroachDB HA mode
  website/content/docs/configuration/storage/cockroachdb.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16274 auth/oidc: Adds documentation for SecureAuth IdP
  changelog/16274.txt
  website/content/api-docs/auth/jwt.mdx
  website/content/docs/auth/jwt/oidc-providers/index.mdx
  website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
  website/data/docs-nav-data.json
Labels: docs

#16276 Implement error handling and screens for okta number challenge
  ui/app/components/auth-form.js
  ui/app/components/okta-number-challenge.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/okta-number-challenge.hbs
  ui/tests/integration/components/okta-number-challenge-test.js
Labels: ui, pr/no-changelog

#16243 Back out panic message, add new warning to FIPS docs
  website/content/docs/enterprise/fips/fips1402.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x, fips

#16239 update changelog with recent advisories
  CHANGELOG.md
Labels: pr/no-changelog

#16291 Vault documentation: updated sys-mfa api doc
  website/content/api-docs/system/mfa/index.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16297 Update the policy examples
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog, backport/1.11.x

#16301 Update localhost:3000 links to be correct
  website/content/docs/concepts/client-count/faq.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#15260 Cherry-Picked Community PR: append slash to consul path in doc
  website/content/docs/commands/operator/migrate.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/run.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16312 Update policies.mdx
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog, backport/1.11.x

#16313 Fix agent use_auto_auth_token force test
  command/agent/config/config_test.go
Labels: pr/no-changelog

#16329 Update to use latest api version in api/auth submodules
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
Labels: pr/no-changelog

#16304 Fix docs consul feature version
  website/content/api-docs/secret/consul.mdx
Labels: pr/no-changelog

#16324 Vault 6773/raft rejoin nonvoter
  changelog/16324.txt
  helper/testhelpers/teststorage/teststorage.go
  helper/testhelpers/teststorage/teststorage_reusable.go
  vault/raft.go
Labels: bug, backport/1.9.x, backport/1.10.x, backport/1.11.x

#15671 AutoMTLS for secrets/auth plugins
  api/plugin_helpers.go
  builtin/plugin/backend.go
  builtin/plugin/backend_lazyLoad_test.go
  changelog/15671.txt
  sdk/helper/pluginutil/env.go
  sdk/helper/pluginutil/multiplexing.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  sdk/helper/pluginutil/runner.go
  sdk/plugin/backend.go
  sdk/plugin/plugin.go
  sdk/plugin/serve.go
  vault/logical_system_integ_test.go
  vault/plugin_catalog.go
Labels: backport/1.11.x

#16344 Fix the contribution guide link
  website/content/docs/what-is-vault.mdx
Labels: pr/no-changelog, backport/1.11.x

#16320 Add Harbor Robot Account secrets plugin
  website/content/docs/plugins/plugin-portal.mdx
Labels: pr/no-changelog, backport/1.11.x

#16346 docs/plugin-portal: adds missing HashiCorp supported plugins
  website/content/docs/plugins/plugin-portal.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16326 Docs: Add release notes for MSSQL TDE
  website/content/docs/platform/mssql/changelog.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.11.x

#16240 [Kubernetes Secret Engine]: Role namespace configuration possible via LabelSelector
  changelog/16240.txt
  website/content/api-docs/secret/kubernetes.mdx
  website/content/docs/secrets/kubernetes.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16253 Information about aws_s3_server_side_encryption
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: docs, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16150 Add HashiBox to community tools
  website/content/api-docs/relatedtools.mdx
Labels: docs, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16352 formatting issue - missing list bullet
  website/content/docs/commands/secrets/tune.mdx
Labels: pr/no-changelog, backport/1.11.x

#16372 Vault documentation: updated note about MFA feature
  website/content/docs/enterprise/mfa/index.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16341 VAULT-6727 Adjust cert and approle role resolution, add more tests
  builtin/credential/approle/path_login.go
  builtin/credential/approle/path_login_test.go
  builtin/credential/cert/path_login.go
  builtin/credential/cert/path_login_test.go
Labels: pr/no-changelog

#16377 Revert "AutoMTLS for secrets/auth plugins (#15671)"
  api/plugin_helpers.go
  builtin/plugin/backend.go
  builtin/plugin/backend_lazyLoad_test.go
  changelog/15671.txt
  sdk/helper/pluginutil/env.go
  sdk/helper/pluginutil/multiplexing.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  sdk/helper/pluginutil/runner.go
  sdk/plugin/backend.go
  sdk/plugin/plugin.go
  sdk/plugin/serve.go
  vault/logical_system_integ_test.go
  vault/plugin_catalog.go
Labels: pr/no-changelog

#16269 Missing word
  website/content/docs/secrets/databases/mssql.mdx
Labels: pr/no-changelog, backport/1.11.x

#16380 Fix replication test failure
  ui/tests/acceptance/enterprise-replication-test.js
Labels: ui, bug, pr/no-changelog

#16327 Increase the allowed concurrent gRPC streams
  changelog/16327.txt
  vault/cluster/cluster.go
Labels: backport/1.9.x, backport/1.10.x, backport/1.11.x

#16331 UI/vault 6655/OIDC create view
  ui/app/components/oidc/assignment-form.js
  ui/app/decorators/model-validations.js
  ui/app/models/oidc/assignment.js
  ui/app/models/oidc/scope.js
  ui/app/routes/vault/cluster/access/oidc/assignments/assignment.js
  ui/app/routes/vault/cluster/access/oidc/assignments/create.js
  ui/app/templates/components/mfa/mfa-login-enforcement-form.hbs
  ui/app/templates/components/oidc/assignment-form.hbs
  ui/app/templates/components/oidc/scope-form.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/details.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/create.hbs
  ui/tests/integration/components/oidc/assignment-form-test.js
  ui/tests/integration/components/oidc/scope-form-test.js
  ui/tests/unit/adapters/oidc/assignment-test.js
Labels: ui, pr/no-changelog

#16321 Update gopsutil to v3 to fix MacOS deprecation warnings
  go.mod
  go.sum
  helper/hostutil/hostinfo.go
  helper/hostutil/hostinfo_util.go
  physical/raft/bolt_linux.go
  vault/diagnose/os_common.go
Labels: pr/no-changelog

#15206 Change AWS to Azure in Tutorial section
  website/content/docs/secrets/azure.mdx
Labels: pr/no-changelog, backport/1.11.x

#14381 Add documentation for KV Engine V2 API requests
  website/content/api-docs/index.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#14207 Update reload.mdx
  website/content/docs/commands/plugin/reload.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#13630 Update s3.mdx
  website/content/docs/configuration/storage/s3.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16323 Fix typo in the docs
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16392 Add next-step warning on import without AIA URLs
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
Labels: enhancement, secret/pki, pr/no-changelog

#16388 auth/oidc: fix changelog entry for SecureAuth groups parsing
  changelog/16274.txt
Labels: pr/no-changelog

#16401 Add paths for transit import endpoints
  website/content/api-docs/secret/transit.mdx
Labels: pr/no-changelog, backport/1.11.x

#16403 auth/oidc: documents the client_nonce parameter
  website/content/api-docs/auth/jwt.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16407 [VAULT-6622] oss changes
  vault/identity_store.go
  vault/request_handling.go
  vault/request_handling_util.go
Labels: pr/no-changelog

#16405 deps: updates google.golang.org/api via plugins
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog

#16406 Add an "Important Note" regarding EKS CSR approval.
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
Labels: pr/no-changelog, backport/1.11.x

#16410 Transform tokenization key auto-rotate docs
  website/content/api-docs/secret/transform.mdx
  website/content/docs/secrets/transform/tokenization.mdx
Labels: docs, pr/no-changelog

#16420 update semgrep to 0.106.0
  .circleci/config.yml
  .circleci/config/commands/setup-semgrep.yml
Labels: pr/no-changelog

#16425 Add changelog for #15933
  changelog/15933.txt
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x

#16366 Fix linter issues in policy.go & acl.go
  vault/acl.go
  vault/acl_test.go
  vault/policy.go
Labels: pr/no-changelog

#11969 First pass at JWT auto-deletion flag
  changelog/11969.txt
  command/agent/auth/jwt/jwt.go
  command/agent/auth/jwt/jwt_test.go
  website/content/docs/agent/autoauth/methods/jwt.mdx
Labels: ecosystem, agent

#16440 Leverage upstream docker image returntocorp/semgrep in CircleCI
  .circleci/config.yml
  .circleci/config/commands/setup-semgrep.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/semgrep.yml
Labels: pr/no-changelog

#16444 Add a note referring to automated upgrade
  website/content/docs/concepts/integrated-storage/autopilot.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
Labels: pr/no-changelog, backport/1.11.x

#16434 Minor documentation changes for vault operator init
  website/content/api-docs/system/init.mdx
  website/content/docs/commands/operator/init.mdx
Labels: pr/no-changelog

#16433 Docs: Add table documenting compatible k8s versions for agent injector
  website/content/docs/platform/k8s/injector/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#16454 Added list view for keys
  ui/app/routes/vault/cluster/access/oidc/keys/index.js
  ui/app/templates/vault/cluster/access/oidc/keys/index.hbs
Labels: ui, pr/no-changelog

#16442 Added list view for providers
  ui/app/routes/vault/cluster/access/oidc/providers/index.js
  ui/app/templates/vault/cluster/access/oidc/providers/index.hbs
Labels: ui, pr/no-changelog

#16121 docs/k8s: adding terraform config examples
  website/content/docs/platform/k8s/helm/terraform.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.11.x

#16459 Fixed grammar errors
  README.md
Labels: pr/no-changelog

#16463 Correct the Transit HMAC key source in docs
  website/content/api-docs/secret/transit.mdx
Labels: website, pr/no-changelog

#16469 Added list view for application
  ui/app/routes/vault/cluster/access/oidc/clients/index.js
  ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
Labels: ui, pr/no-changelog

#16466 UI: fix jwt auth failure
  changelog/16466.txt
  ui/app/components/auth-form.js
  ui/tests/acceptance/jwt-auth-method-test.js
  ui/tests/acceptance/secrets/backend/pki/cert-test.js
Labels: ui, bug, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16456 UI/vault 7196/search select with modal
  ui/app/utils/validators.js
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/components/search-select-with-modal.js
  ui/lib/core/app/components/search-select-with-modal.js
  ui/tests/integration/components/search-select-with-modal-test.js
  ui/tests/unit/utils/validators-test.js
Labels: ui, pr/no-changelog

#16470 UI/remove has many relationship
  ui/app/components/oidc/assignment-form.js
  ui/app/models/oidc/assignment.js
  ui/app/models/oidc/client.js
  ui/app/models/oidc/key.js
  ui/app/models/oidc/provider.js
  ui/app/templates/components/oidc/assignment-form.hbs
  ui/tests/integration/components/oidc/assignment-form-test.js
Labels: ui

#16480 changelog: Add entry for AD secrets engine bug fix
  changelog/16140.txt
Labels: pr/no-changelog, backport/1.11.x

#16340 Assignment list view
  ui/app/routes/vault/cluster/access/oidc/assignments/index.js
  ui/app/styles/components/list-item-row.scss
  ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs
Labels: ui, pr/no-changelog

#16485 Fix a panic at cleanup time in an expiration restore lease benchmark.
  vault/expiration_test.go
Labels: pr/no-changelog

#16464 move custom metadata validation logic to its own package
  sdk/helper/custommetadata/custom_metadata.go
  sdk/helper/custommetadata/custom_metadata_test.go
  vault/identity_store_aliases.go
Labels: pr/no-changelog

#16181 identity/oidc: allow filtering the list providers response by an allowed_client_id
  changelog/16181.txt
  http/logical.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  website/content/api-docs/secret/identity/oidc-provider.mdx
Labels: identity/oidc

#16478 Backport UI: Fix JWT Auth login to 1.9.
  changelog/16466.txt
  ui/app/components/auth-form.js
  ui/tests/acceptance/jwt-auth-method-test.js
Labels: ui, backport, bug

#16477 Backport UI: Fix JWT Auth login into 1.10.6
  changelog/16466.txt
  ui/app/components/auth-form.js
  ui/tests/acceptance/jwt-auth-method-test.js
Labels: ui, backport, bug

#16489 Lookup, wrap, rewrap and unwrap token rename with description
  changelog/16489.txt
  ui/app/templates/components/tool-lookup.hbs
  ui/app/templates/components/tool-rewrap.hbs
  ui/app/templates/components/tool-unwrap.hbs
  ui/app/templates/components/tool-wrap.hbs
  ui/app/templates/components/wizard/tools-unwrapped.hbs
Labels: ui

#16476 Backport of UI: fix jwt auth failure into release/1.11.x
  changelog/16466.txt
  ui/app/components/auth-form.js
  ui/tests/acceptance/jwt-auth-method-test.js
Labels: ui, backport, bug

#16131 UI/OIDC client form
  ui/app/components/oidc/assignment-form.js
  ui/app/components/oidc/client-form.js
  ui/app/decorators/model-validations.js
  ui/app/models/oidc/assignment.js
  ui/app/models/oidc/client.js
  ui/app/models/oidc/scope.js
  ui/app/routes/vault/cluster/access/oidc/clients/client.js
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/oidc/assignment-form.hbs
  ui/app/templates/components/oidc/client-form.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/create.hbs
  ui/lib/core/addon/components/form-field-groups.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/radio-button.hbs
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/templates/components/readonly-form-field.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/tests/integration/components/oidc/assignment-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
Labels: ui, pr/no-changelog

#16479 agent: add disable_keep_alives configurable
  api/client.go
  changelog/16479.txt
  command/agent.go
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/bad-config-disable-keep-alives.hcl
  command/agent/config/test-fixtures/config-disable-keep-alives-all.hcl
  command/agent/config/test-fixtures/config-disable-keep-alives-auto-auth.hcl
  command/agent/config/test-fixtures/config-disable-keep-alives-caching.hcl
  command/agent/config/test-fixtures/config-disable-keep-alives-empty.hcl
  command/agent/config/test-fixtures/config-disable-keep-alives-templating.hcl
  command/agent/template/template.go
  website/content/docs/agent/index.mdx
Labels: backport/1.11.x

#16492 docs/vault-k8s: updated for v0.17.0 release
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: docs, k8s, pr/no-changelog, backport/1.11.x

#16351 Allow identity templates in ssh backend `default_user` field
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/ssh/path_roles.go
  changelog/16351.txt
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, secret/ssh, cryptosec

#16491 VAULT-7256 - Add CustomMetadata to Namespace type
  helper/namespace/namespace.go
  sdk/helper/custommetadata/custom_metadata.go
  sdk/helper/custommetadata/custom_metadata_test.go
Labels: pr/no-changelog

#16505 secret/ssh: Return errors for bad templates in roles as we did previously
  builtin/logical/ssh/path_issue_sign.go
Labels: secret/ssh, pr/no-changelog

#16495 UI/glimmerize info table item array
  ui/lib/core/addon/components/info-table-item-array.hbs
  ui/lib/core/addon/components/info-table-item-array.js
  ui/lib/core/addon/templates/components/info-table-item-array.hbs
  ui/tests/integration/components/info-table-row-test.js
Labels: ui, pr/no-changelog
