Repository hashicorp/vault, pull requests merged in 2022-04, with the labels that each got.

#14806 Vault documentation: updated ssct faq page
  website/content/docs/faq/ssct.mdx
Labels: pr/no-changelog, backport/website

#14814 VAULT-4240 time.After() in a select statement can lead to memory leak
  changelog/14814.txt
  helper/fairshare/jobmanager.go
  physical/raft/raft.go
  vault/raft.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14752 Vault-4279 reporting redundant/unused keys in config
  changelog/14752.txt
  command/server.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14795 docs: add plugin definitions to the glossary
  website/content/docs/glossary.mdx
  website/content/docs/plugins/plugin-architecture.mdx
Labels: pr/no-changelog, backport/website

#14791 Fixing excessive unix file permissions
  changelog/14791.txt
  command/agent.go
  command/operator_raft_snapshot_save.go
  command/server.go
  physical/raft/raft.go
  physical/raft/snapshot.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14816 Remove ember-basic-dropdown-hover Addon
  ui/lib/core/addon/components/tool-tip.hbs
  ui/lib/core/addon/components/tool-tip.js
  ui/lib/core/addon/templates/components/tool-tip.hbs
  ui/lib/core/package.json
  ui/package.json
  ui/tests/integration/components/tool-tip-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog

#14844 Vault documentation: changing references from learn to tutorial
  website/content/api-docs/system/storage/raftautopilot.mdx
  website/content/docs/commands/operator/usage.mdx
  website/content/docs/install.mdx
  website/content/docs/platform/aws/run.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/plugins/plugin-portal.mdx
  website/content/docs/what-is-vault.mdx
Labels: do-not-merge, pr/no-changelog, backport/website

#14794 UI/Only show form values if have read access
  changelog/14794.txt
  ui/app/components/secret-create-or-update.js
Labels: ui, bug, backport/1.9.x, backport/1.10.x

#14854 Vault documentation: modified storage support section
  website/content/docs/concepts/ha.mdx
Labels: pr/no-changelog, backport/website

#14850 Vault documentation: fixed a link issue
  website/content/docs/platform/k8s/helm/examples/index.mdx
  website/content/docs/what-is-vault.mdx
Labels: pr/no-changelog, backport/website

#14859 docs: add known issue to 1.10 release notes
  website/content/docs/release-notes/1.10.0.mdx
Labels: docs, pr/no-changelog, backport/website

#14846 Vault 3999 Change permissions for directory/archive created by debug command
  changelog/14846.txt
  command/debug.go
  command/debug_test.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14817 Vault 3992 ToB Config and Plugins Permissions
  changelog/14817.txt
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  helper/osutil/fileinfo.go
  helper/osutil/fileinfo_test.go
  helper/osutil/fileinfo_unix.go
  helper/osutil/fileinfo_unix_test.go
  helper/osutil/fileinfo_windows.go
  http/plugin_test.go
  http/sys_config_state_test.go
  sdk/helper/consts/consts.go
  vault/auth.go
  vault/core.go
  vault/diagnose/file_checks_unix.go
  vault/logical_system.go
  vault/logical_system_integ_test.go
  vault/mount.go
  vault/plugin_catalog.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14868 Vault documentation: batch4--changing references from learn to tutorial
  website/content/docs/agent/caching/index.mdx
  website/content/docs/auth/approle.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/configuration/storage/index.mdx
  website/content/docs/configuration/storage/raft.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/secrets/ad.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
  website/content/docs/secrets/kv/kv-v2.mdx
  website/content/docs/secrets/transform/index.mdx
Labels: pr/no-changelog, backport/website

#14875 Fix handling of default zero SignatureBits value with Any key type in PKI Secrets Engine
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  changelog/14875.txt
  sdk/helper/certutil/helpers.go
Labels: bug, secret/pki, cryptosec, backport/1.10.x

#14889 Subtle docs change for allow_store_key
  website/content/api-docs/system/managed-keys.mdx
Labels: pr/no-changelog, backport/1.10.x

#14851 Adds Vault version prerelease and metadata to logical.PluginEnvironment
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/plugin.proto
  sdk/plugin/grpc_system_test.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/dynamic_system_view.go
  vault/request_forwarding_service.pb.go
  vault/tokens/token.pb.go
Labels: sdk, pr/no-changelog

#14756 Docs improvements for Managed Keys
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/secrets/pki.mdx
Labels: pr/no-changelog, backport/1.10.x

#14911 Replace mount-filter with path-filter
  ui/lib/replication/addon/templates/mode/secondaries/index.hbs
  ui/tests/acceptance/enterprise-replication-test.js
Labels: ui, pr/no-changelog

#14910 website: fix usages of img tag
  website/.gitignore
  website/Makefile
  website/content/docs/partnerships.mdx
  website/next.config.js
  website/package.json
  website/redirects.js
  website/scripts/website-build.sh
  website/scripts/website-start.sh
Labels: pr/no-changelog, backport/website

#14927 remove mount_accessor from the docs
  website/content/api-docs/secret/identity/mfa/duo.mdx
  website/content/api-docs/secret/identity/mfa/okta.mdx
  website/content/api-docs/secret/identity/mfa/pingid.mdx
Labels: pr/no-changelog, backport/website, backport/1.10.x

#14767 Add extra test coverage to PKI
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
Labels: pr/no-changelog

#14836 Respect increment value in grace period calculations (api/LifetimeWatcher)
  api/lifetime_watcher.go
  api/renewer_test.go
  changelog/14836.txt
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#14922 Implement PKI storage migration.
  builtin/logical/pki/backend.go
  builtin/logical/pki/config_util.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/storage_test.go
Labels: secret/pki, pr/no-changelog, rotation

#14835 KMSE Enable/Config
  ui/app/components/mount-backend-form.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/helpers/supported-secret-backends.js
  ui/app/models/secret-engine.js
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/secret-list-header.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/helpers/has-feature.js
Labels: ui, pr/no-changelog

#14923 Update vault-plugin-auth-gcp to pseudo-version on main
  go.mod
  go.sum
Labels: pr/no-changelog

#14928 docs: added hello-vault-spring repo link to developer-qs.mdx.
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog, backport/website

#14916 OIDC Login Bug
  changelog/14916.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
Labels: ui

#14943 Fix handling of SignatureBits for ECDSA issuers
  builtin/logical/pki/backend_test.go
  changelog/14943.txt
  sdk/helper/certutil/helpers.go
  website/content/api-docs/secret/pki.mdx
Labels: bug, secret/pki, cryptosec, backport/1.10.x

#14941 Bug Fix and Glimmerize secret-edit component
  changelog/14941.txt
  ui/app/components/secret-edit-toolbar.js
  ui/app/components/secret-edit.js
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/app/templates/components/secret-edit.hbs
Labels: ui

#14424 Agent error log level is mismatched
  changelog/14424.txt
  command/agent/template/template.go
  command/agent/template/template_test.go
Labels: backport/1.10.x

#14942 UI/Add months to activity serializer
  ui/app/models/clients/activity.js
  ui/app/serializers/clients/activity.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
Labels: ui, pr/no-changelog

#14958 Add disable file permissions check to fix nightly failures
  command/operator_diagnose_test.go
Labels: pr/no-changelog

#14893 Backport - Fix handling of default zero SignatureBits value with Any key type in PKI Secrets Engine #14875
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  changelog/14875.txt
  sdk/helper/certutil/helpers.go
Labels: bug, secret/pki, cryptosec

#14953 Fix dead link for JWT supported algorithms
  website/content/api-docs/auth/jwt.mdx
Labels: website, pr/no-changelog, backport/website

#14961 Backport of OIDC Login Bug into release/1.10.x
  changelog/14916.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/tests/acceptance/logout-auth-method-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
Labels: ui, pr/no-changelog

#14977 Ensure initialMmapSize is 0 on Windows
  changelog/14977.txt
  physical/raft/vars_32bit.go
  physical/raft/vars_64bit.go
Labels: backport/1.10.x

#14918 Vault 3992 documentation changes
  website/content/docs/configuration/index.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/partials/plugin-file-permissions-check.mdx
Labels: pr/no-changelog

#14954 aws auth displayName
  builtin/credential/aws/path_login.go
  changelog/14954.txt
Labels: ecosystem, auth/aws

#14982 Update Release Notes with Windows Error
  website/content/docs/release-notes/1.10.0.mdx
Labels: pr/no-changelog, backport/website

#14991 Model Validations
  ui/app/components/generated-item.js
  ui/app/components/mount-backend-form.js
  ui/app/components/secret-edit-metadata.js
  ui/app/decorators/model-validations.js
  ui/app/models/auth-method.js
  ui/app/models/secret-engine.js
  ui/app/models/secret-v2.js
  ui/app/services/path-help.js
  ui/app/utils/build-api-validators.js
  ui/app/utils/validators.js
  ui/package.json
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/unit/decorators/model-validations-test.js
  ui/tests/unit/utils/validators-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog

#14966 Fix edit capabilities call in auth method
  changelog/14966.txt
  ui/app/models/auth-method.js
Labels: ui

#14993 flight-icons
  ui/package.json
  ui/yarn.lock
Labels: pr/no-changelog

#14994 Fix handling of SignatureBits for ECDSA issuers (#14943)
  builtin/logical/pki/backend_test.go
  changelog/14943.txt
  sdk/helper/certutil/helpers.go
  website/content/api-docs/secret/pki.mdx
Labels: bug, secret/pki, cryptosec

#15001 Remove ModelWrap Component
  ui/lib/core/addon/components/model-wrap.js
  ui/lib/core/addon/templates/components/model-wrap.hbs
  ui/lib/core/app/components/model-wrap.js
  ui/lib/kmip/addon/controllers/credentials/show.js
  ui/lib/kmip/addon/controllers/role.js
  ui/lib/kmip/addon/templates/credentials/show.hbs
  ui/lib/kmip/addon/templates/role.hbs
  ui/tests/acceptance/enterprise-kmip-test.js
Labels: ui, pr/no-changelog

#14970 Fix nightly tests and debug
  command/debug.go
  command/server_test.go
  helper/osutil/fileinfo_unix.go
  helper/osutil/fileinfo_windows.go
Labels: pr/no-changelog

#14967 UI/Client count running totals component
  ui/app/components/clients/history.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/routes/vault/cluster/clients/history.js
  ui/app/serializers/clients/activity.js
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/lib/core/addon/utils/date-formatters.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
Labels: ui, pr/no-changelog

#15008 Backport of Fix edit capabilities call in auth method into release/1.9.x
  changelog/14966.txt
  ui/app/models/auth-method.js
Labels: ui

#15003 Introduce defaultRef constant within PKI
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_sign_issuers.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
Labels: pr/no-changelog, rotation

#15011 Run `make fmt`
  sdk/framework/backend_test.go
Labels: pr/no-changelog

#15012 UI/Clients monthly usage component
  ui/app/components/clients/attribution.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/monthly-usage.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/usage-stats.hbs
  ui/mirage/handlers/clients.js
Labels: ui, pr/no-changelog

#14569 Update socket entry
  website/content/docs/audit/socket.mdx
Labels: website, pr/no-changelog, backport/1.10.x

#14978 chore: remove `backport-docs.yml`
  .github/workflows/backport-docs.yml
Labels: pr/no-changelog

#15010 Typo fixes; numbering fixes.
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/storage/raft.mdx
  website/content/docs/secrets/cubbyhole.mdx
  website/content/docs/secrets/kv/kv-v2.mdx
Labels: pr/no-changelog, backport/1.10.x

#15023 Fix docs typo
  website/content/docs/agent/autoauth/methods/approle.mdx
Labels: pr/no-changelog, backport/1.10.x

#15013 Rework PKI test TestBackend_Root_Idempotency
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/storage.go
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
Labels: rotation

#15026 Form Field Glimmer
  ui/app/components/generated-item.js
  ui/app/components/mount-backend-form.js
  ui/app/components/secret-edit-metadata.js
  ui/app/templates/components/generated-item.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/secret-edit-metadata.hbs
  ui/lib/core/addon/components/form-field-groups.hbs
  ui/lib/core/addon/components/form-field-groups.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/templates/components/form-field-groups.hbs
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/lib/core/stories/form-field-groups.md
  ui/lib/core/stories/form-field.md
Labels: ui, pr/no-changelog

#15025 UI: Masked inputs always look the same when value is hidden
  changelog/15025.txt
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/integration/components/masked-input-test.js
Labels: ui, bug, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15031 Update CODEOWNERS
  CODEOWNERS
Labels: pr/no-changelog

#15018 Update default value of agent-cache-listener-port
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: pr/no-changelog, backport/1.10.x

#15038 Fix vault debug for windows 1.9.x
  command/debug.go
  helper/osutil/fileinfo_unix.go
  helper/osutil/fileinfo_windows.go
Labels: pr/no-changelog

#14864 VAULT-5422: Add rate limit for TOTP passcode attempts
  changelog/14864.txt
  helper/identity/mfa/types.pb.go
  helper/identity/mfa/types.proto
  vault/core.go
  vault/external_tests/identity/login_mfa_totp_test.go
  vault/external_tests/mfa/login_mfa_test.go
  vault/identity_store.go
  vault/login_mfa.go
  website/content/api-docs/secret/identity/mfa/totp.mdx
  website/content/api-docs/system/mfa/totp.mdx
  website/content/docs/auth/login-mfa/index.mdx
Labels: backport/1.10.x

#15043 Update to Go 1.17.9
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/executors/@executors.yml
  .github/workflows/build.yml
  Makefile
  README.md
  changelog/15043.txt
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: release/build

#15045 Update to Go 1.17.9
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/executors/@executors.yml
  .github/workflows/build.yml
  Makefile
  README.md
  changelog/15045.txt
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: release/build

#15044 Update to Go 1.17.9
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/executors/@executors.yml
  .github/workflows/build.yml
  Makefile
  README.md
  changelog/15044.txt
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: release/build

#15034 Backport 1.8.10: UI Masked inputs always look the same when value is hidden (#15025)
  changelog/15025.txt
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/integration/components/masked-input-test.js
Labels: ui, backport, bug

#15027 fix regression on Core.pluginDirectory when backend is builtin
  vault/auth.go
  vault/auth_test.go
  vault/mount.go
  vault/testing.go
Labels: pr/no-changelog

#15046 Custom tooltip for Generated Token Policies form field on auth methods
  changelog/15046.txt
  ui/app/components/generated-item.js
  ui/lib/core/addon/templates/components/info-tooltip.hbs
  ui/tests/acceptance/auth-list-test.js
Labels: ui, bug, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15033 Backport 1.9.5: UI Masked inputs always look the same when value is hidden (#15025)
  changelog/15025.txt
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/integration/components/masked-input-test.js
Labels: ui, backport, bug

#15037 Fix vault debug windows1.10.x
  command/debug.go
  helper/osutil/fileinfo_unix.go
  helper/osutil/fileinfo_windows.go
Labels: pr/no-changelog

#15032 Backport 1.10.1: UI Masked inputs always look the same when value is hidden (#15025)
  changelog/15025.txt
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/integration/components/masked-input-test.js
Labels: ui, backport, bug

#15058 UI: fix blank selection on search select field
  changelog/15058.txt
  ui/README.md
  ui/lib/core/addon/components/search-select.js
Labels: ui, bug, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15059 mv changelog/15043.txt -> changelog/go-ver-1110.txt
  changelog/go-ver-1110.txt
Labels: pr/no-changelog

#15060 Update changelog checker for validating Go toolchain updates
  .github/workflows/changelog-checker.yml
Labels: pr/no-changelog

#15035 UI/Add double attribution chart to current
  ui/app/components/clients/attribution.js
  ui/app/components/clients/current.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/models/clients/monthly.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/horizontal-bar-chart.hbs
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients/attribution-test.js
Labels: ui, pr/no-changelog

#15065 Backport 1.8.10: UI fix blank selection on search select field (#15058)
  changelog/15058.txt
  ui/README.md
  ui/lib/core/addon/components/search-select.js
Labels: ui, backport, bug

#15063 Backport of UI: fix blank selection on search select field into release/1.10.x
  changelog/15058.txt
  ui/README.md
  ui/lib/core/addon/components/search-select.js
Labels: ui, backport, bug

#15066 Backport 1.9.5: UI fix blank selection on search select field (#15058)
  changelog/15058.txt
  ui/README.md
  ui/lib/core/addon/components/search-select.js
Labels: ui, backport, bug

#15064 Update Go version to 1.16.15
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/executors/@executors.yml
  .github/workflows/build.yml
  Makefile
  README.md
  changelog/go-ver-1810.txt
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: release/build

#15052 Backport of Custom tooltip for Generated Token Policies form field on auth methods into release/1.8.x
  changelog/15046.txt
  ui/app/components/generated-item.js
Labels: ui

#14973 Update gocql to resolve #12878
  changelog/14973.txt
  go.mod
  go.sum
Labels: dependencies, storage/cassandra

#15073 sort list of unrecognized params in response warning
  sdk/framework/backend.go
Labels: pr/no-changelog

#15072 fix TypeCommaIntSlice panic caused by json.Number input
  changelog/15072.txt
  sdk/framework/field_data.go
  sdk/framework/field_data_test.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15084 docs/secrets/ad: remove case_sensitive_names from API docs
  website/content/api-docs/secret/ad.mdx
Labels: docs, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15040 Fix vault debug for windows 1.8.x
  command/debug.go
  helper/osutil/fileinfo_unix.go
  helper/osutil/fileinfo_windows.go
Labels: pr/no-changelog

#14972 website: remove `/intro` content moved to learn
  website/content/intro/getting-started/apis.mdx
  website/content/intro/getting-started/authentication.mdx
  website/content/intro/getting-started/deploy.mdx
  website/content/intro/getting-started/dev-server.mdx
  website/content/intro/getting-started/dynamic-secrets.mdx
  website/content/intro/getting-started/first-secret.mdx
  website/content/intro/getting-started/help.mdx
  website/content/intro/getting-started/index.mdx
  website/content/intro/getting-started/next-steps.mdx
  website/content/intro/getting-started/policies.mdx
  website/content/intro/getting-started/secrets-engines.mdx
  website/content/intro/index.mdx
  website/data/intro-nav-data.json
  website/pages/intro/[[...page]].jsx
Labels: pr/no-changelog

#15095 Update CODEOWNERS
  CODEOWNERS
Labels: pr/no-changelog

#15092 Upgrade hashicorp/consul-template dependency
  changelog/15092.txt
  command/agent/config/config_test.go
  command/agent/template/template_test.go
  go.mod
  go.sum
Labels: backport/1.10.x

#15091 PKI migration writes out empty migration log entry
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_migrations_test.go
Labels: secret/pki, pr/no-changelog, rotation

#15093 VAULT-5827 Update mongodb, brotli
  builtin/logical/database/rotation_test.go
  go.mod
  go.sum
Labels: pr/no-changelog

#15097 Update CODEOWNERS
  CODEOWNERS
Labels: pr/no-changelog

#15083 UI/Add upgrade indicator client charts
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/monthly-usage.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/models/clients/activity.js
  ui/app/models/clients/monthly.js
  ui/app/routes/vault/cluster/clients.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/utils/date-formatters.js
  ui/mirage/handlers/clients.js
  ui/tests/integration/components/calendar-widget-test.js
Labels: ui, pr/no-changelog

#15102 Refactor enterprise PKI managed key code (OSS)
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/managed_key_util.go
  builtin/logical/pki/util.go
Labels: pr/no-changelog

#15036 Key Management Secrets Engine Phase 1
  ui/app/adapters/keymgmt/key.js
  ui/app/adapters/keymgmt/provider.js
  ui/app/components/keymgmt/distribute.js
  ui/app/components/keymgmt/key-edit.js
  ui/app/components/keymgmt/provider-edit.js
  ui/app/components/mount-backend-form.js
  ui/app/components/pagination-controls.js
  ui/app/controllers/vault/cluster/secrets/backend/edit.js
  ui/app/controllers/vault/cluster/secrets/backend/show.js
  ui/app/decorators/model-validations.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/helpers/options-for-backend.js
  ui/app/helpers/secret-query-params.js
  ui/app/helpers/sub.js
  ui/app/helpers/supported-secret-backends.js
  ui/app/models/keymgmt/key.js
  ui/app/models/keymgmt/provider.js
  ui/app/models/secret-engine.js
  ui/app/routes/vault/cluster/secrets/backend/create-root.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/keymgmt/key.js
  ui/app/serializers/keymgmt/provider.js
  ui/app/styles/components/doc-link.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/forms.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/core/title.scss
  ui/app/templates/components/keymgmt/distribute.hbs
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/pagination-controls.hbs
  ui/app/templates/components/secret-list-header.hbs
  ui/app/templates/components/secret-list/item.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/helpers/has-feature.js
  ui/lib/core/addon/templates/components/alert-inline.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/mirage/handlers/index.js
  ui/mirage/handlers/kms.js
  ui/stories/pagination-controls.md
  ui/tests/integration/components/info-table-row-test.js
  ui/tests/integration/components/keymgmt/distribute-test.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
  ui/tests/integration/components/keymgmt/provider-edit-test.js
  ui/tests/integration/components/pagination-controls-test.js
  ui/tests/integration/components/search-select-test.js
Labels: ui, pr/no-changelog

#15105 Add back metadata.json
  ui/metadata.json
Labels: pr/no-changelog

#15110 Modified explanation on >=1 audit devices and successful requests
  website/content/docs/audit/index.mdx
Labels: pr/no-changelog, backport/1.10.x

#15106 Disabling LinkTo Component
  ui/app/styles/components/toolbar.scss
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/components/secret-link.hbs
  ui/app/templates/components/toolbar-secret-link.hbs
  ui/app/templates/vault/cluster/init.hbs
  ui/scripts/codemods/transform-deprecated-args.js
Labels: ui, pr/no-changelog

#15056 Elaborate the correlation between CLI and API
  website/content/docs/commands/delete.mdx
  website/content/docs/commands/index.mdx
  website/content/docs/commands/list.mdx
  website/content/docs/commands/read.mdx
  website/content/docs/commands/write.mdx
Labels: pr/no-changelog, backport/1.10.x

#15114 Correct the unit type for mount_table.size.
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/1.10.x

#15116 Cherry pick PR 15056
  website/content/docs/commands/delete.mdx
  website/content/docs/commands/index.mdx
  website/content/docs/commands/list.mdx
  website/content/docs/commands/read.mdx
  website/content/docs/commands/write.mdx
Labels: docs, pr/no-changelog

#15117 docs/agent: merge template and template config
  website/content/docs/agent/template-config.mdx
  website/content/docs/agent/template.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.10.x

#14896 remove mount-filter endpoint from replication docs
  website/content/api-docs/system/replication/replication-performance.mdx
Labels: pr/no-changelog

#14913 remove references to sys/license endpoint in docs
  website/content/api-docs/system/license.mdx
  website/content/docs/enterprise/namespaces.mdx
  website/data/api-docs-nav-data.json
Labels: pr/no-changelog

#15126 Add new PKI key prefix to seal wrapped storage
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
Labels: rotation

#15125 Update golang.org/x/crypto/ssh
  changelog/15125.txt
  go.mod
  go.sum
Labels: secret/ssh, cryptosec

#15123 Clone things to prevent races.
  changelog/15123.txt
  vault/identity_store_entities.go
  vault/identity_store_util.go
Labels: backport/1.10.x

#15128 change action to pull v1 instead of main
  .github/workflows/build.yml
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15132 UI/ Fix test selector
  ui/lib/core/addon/templates/components/alert-banner.hbs
  ui/tests/acceptance/client-history-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/integration/components/replication-dashboard-test.js
Labels: ui, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15137 Update to 1.10.2
  sdk/version/version_base.go
Labels: pr/no-changelog

#15138 Update to 1.9.6
  sdk/version/version_base.go
Labels: pr/no-changelog

#15139 Update to 1.8.11
  sdk/version/version_base.go
Labels: pr/no-changelog

#15140 Import SDK for 1.10.2 version
  go.mod
Labels: pr/no-changelog

#15104 [VAULT-5887] TypeInt64 support added to OpenApi Spec generation
  changelog/15104.txt
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
  sdk/framework/testdata/operations.json
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15122 Vault documentation: changed the word objects to bytes
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/1.8.x

#15103 Client Count banner warnings for upgraded of minor 9 or 10
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/components/clients/line-chart.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/integration/components/replication-dashboard-test.js
Labels: ui, pr/no-changelog

#15165 Don't show the signature for git commits in the build_date script
  scripts/build_date.sh
Labels: pr/no-changelog

#15158 Vault documentation: changed the word objects to bytes for telemetry doc
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog

#15156 fix raft tls key rotation panic when rotation time in past
  changelog/15156.txt
  vault/raft.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15143 KMSE Capabilities & Phase 1 Cleanup
  ui/app/adapters/keymgmt/key.js
  ui/app/components/keymgmt/distribute.js
  ui/app/components/keymgmt/key-edit.js
  ui/app/models/keymgmt/key.js
  ui/app/models/keymgmt/provider.js
  ui/app/templates/components/keymgmt/distribute.hbs
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/tests/integration/components/keymgmt/distribute-test.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
  ui/tests/integration/components/keymgmt/provider-edit-test.js
Labels: ui, pr/no-changelog

#15067 When tainting a route during setup, pre-calculate the namespace specific path
  changelog/15067.txt
  helper/namespace/namespace.go
  vault/auth.go
  vault/rollback_test.go
  vault/router.go
  vault/router_test.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15172 Vault documentation: updated docs to include a note about seal requirement
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/alicloudkms.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/azurekeyvault.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/seal/ocikms.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: pr/no-changelog, backport/1.10.x

#15171 KMSE Wizard Steps
  ui/app/components/keymgmt/distribute.js
  ui/app/components/wizard/secrets-keymgmt.js
  ui/app/controllers/vault/cluster/settings/mount-secret-backend.js
  ui/app/helpers/wizard-constants.js
  ui/app/machines/secrets-machine.js
  ui/app/routes/vault/cluster/secrets/backend/create-root.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/components/wizard/keymgmt-engine.hbs
  ui/app/templates/components/wizard/mounts-wizard.hbs
  ui/app/templates/components/wizard/secrets-details.hbs
  ui/app/templates/components/wizard/secrets-display.hbs
  ui/app/templates/components/wizard/secrets-enable.hbs
  ui/app/templates/components/wizard/secrets-idle.hbs
  ui/app/templates/components/wizard/secrets-keymgmt.hbs
Labels: ui, pr/no-changelog

#15178 Add warning on keyless default issuer
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_manage_issuers.go
Labels: secret/pki, pr/no-changelog, rotation

#15191 Vault documentation: applied new guidelines to code blocks
  website/content/docs/auth/approle.mdx
  website/content/docs/auth/aws.mdx
  website/content/docs/auth/azure.mdx
  website/content/docs/auth/gcp.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: pr/no-changelog, backport/1.10.x

#15180 Update PKI to new Operations framework
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_config_urls.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_sign_issuers.go
Labels: secret/pki, pr/no-changelog, rotation

#15199 fix: upgrade vault-plugin-database-snowflake to v0.4.1
  go.mod
  go.sum
Labels: pr/no-changelog

#15202 Vault documentation: updated upgrade guide to include a raft-related known issue
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/docs/upgrading/upgrade-to-1.8.x.mdx
  website/content/docs/upgrading/upgrade-to-1.9.x.mdx
Labels: pr/no-changelog, backport/1.10.x

#15150 Kitography/vault 5474 rebase
  builtin/logical/pki/backend.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_fetch_keys.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/storage_test.go
  builtin/logical/pki/util.go
  sdk/framework/backend_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
Labels: rotation

#15054 Add AWS_DYNAMODB_REGION Environment variable
  changelog/15054.txt
  physical/dynamodb/dynamodb.go
Labels: ecosystem, storage/dynamodb

#15042 Raft: use a larger initial heartbeat/election timeout
  changelog/15042.txt
  go.mod
  go.sum
  helper/testhelpers/testhelpers.go
  physical/raft/fsm.go
  physical/raft/raft.go
  vault/external_tests/raft/raft_autopilot_test.go
  vault/external_tests/sealmigration/seal_migration_test.go
Labels: backport/1.10.x

#15224 Fix/gh 15210/sockaddr template parsing when needed
  changelog/15224.txt
  internalshared/configutil/listener.go
  internalshared/configutil/listener_test.go
  sdk/go.sum
Labels: backport/1.9.x, backport/1.10.x

#15219 Add enterprise sudo paths to api.SudoPaths map
  api/plugin_helpers.go
  vault/external_tests/api/sudo_paths_test.go
Labels: pr/no-changelog

#15211 Add alternative proposal PKI aliased paths
  builtin/logical/pki/backend.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_sign_issuers.go
Labels: secret/pki, pr/no-changelog, rotation

#15231 Fix sentence under Integrated Storage (Raft) Autopilot docs
  website/content/docs/internals/telemetry.mdx
Labels: docs, pr/no-changelog

#15215 Upgrade CircleCI machine image
  .circleci/config.yml
  .circleci/config/commands/setup-go.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/pre-flight-checks.yml
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15227 Handle issuer, keys locking
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_fetch_keys.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_root.go
Labels: secret/pki, pr/no-changelog, rotation

#15195 docs: update agent sections around auto-auth, caching, and templating
  website/content/docs/agent/autoauth/index.mdx
  website/content/docs/agent/autoauth/methods/approle.mdx
  website/content/docs/agent/caching/index.mdx
  website/content/docs/agent/caching/persistent-caches/index.mdx
  website/content/docs/agent/index.mdx
  website/content/docs/agent/template.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15217 Allow looking up mount entries by their backend UUIDs
  vault/mount.go
  vault/mount_test.go
Labels: pr/no-changelog, rotation

#15240 Backport 1.10.x: docs: update agent sections around auto-auth, caching, and templating…
  website/content/docs/agent/autoauth/index.mdx
  website/content/docs/agent/autoauth/methods/approle.mdx
  website/content/docs/agent/caching/index.mdx
  website/content/docs/agent/caching/persistent-caches/index.mdx
  website/content/docs/agent/index.mdx
  website/content/docs/agent/template.mdx
Labels: docs

#15241 Update SDK to 1.8.12
  sdk/version/version_base.go
Labels: pr/no-changelog

#15242 Update SDK to 1.9.7
  sdk/version/version_base.go
Labels: pr/no-changelog

#15243 Update sdk to 1.10.3
  sdk/version/version_base.go
Labels: pr/no-changelog
