Repository hashicorp/vault, pull requests merged in 2022-08, with the labels that each got.

#16515 Add KMIP CSPs + initial Seal Wrap list
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/sealwrap.mdx
Labels: docs, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16520 oidc provider: use identity store's storage view in test
  vault/identity_store_oidc_provider_test.go
Labels: pr/no-changelog

#16509 Fix last sample request
  website/content/api-docs/secret/identity/mfa/totp.mdx
Labels: pr/no-changelog

#16514 Make PKI tests run in parallel
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_test.go
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/integation_test.go
  builtin/logical/pki/path_manage_keys_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/storage_test.go
Labels: secret/pki, pr/no-changelog

#16422 VAULT-7065 move lease-quota updating to process restore
  vault/expiration.go
Labels: pr/no-changelog

#16528 Update Go version changelog checker to indicate underscore is required
  .github/workflows/changelog-checker.yml
Labels: pr/no-changelog

#16530 add merkle.flushDirty.outstanding_pages metric to docs
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/1.11.x

#16507 UI/ OIDC Application (client) details view
  ui/app/controllers/vault/cluster/access/oidc/clients/client.js
  ui/app/controllers/vault/cluster/access/oidc/clients/client/details.js
  ui/app/models/oidc/client.js
  ui/app/router.js
  ui/app/routes/vault/cluster/access/oidc/clients/client/details.js
  ui/app/routes/vault/cluster/access/oidc/clients/client/providers.js
  ui/app/templates/components/oidc/provider-list.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/details.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/providers.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/index.hbs
  ui/lib/core/addon/components/info-table-item-array.js
  ui/lib/core/addon/components/info-table-row.hbs
  ui/mirage/handlers/oidc-config.js
  ui/tests/integration/components/oidc/assignment-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
Labels: ui, pr/no-changelog

#16522 Update Go to 1.18
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/executors/@executors.yml
  .github/workflows/build.yml
  Makefile
  README.md
  changelog/_go-ver-1120.txt
  go.mod
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: pr/no-changelog

#16534 secrets/gcp: adds changelog entry for bug fixes in release branches
  changelog/16534.txt
Labels: backport/1.10.x, backport/1.11.x

#16498 Vault documentation: updated install and ha files
  website/content/docs/install.mdx
  website/content/docs/internals/high-availability.mdx
Labels: pr/no-changelog, backport/1.11.x

#16381 VAULT-6615 Update docs for 1.12 quota changes
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/rate-limit-quotas.mdx
  website/content/docs/concepts/resource-quotas.mdx
  website/content/docs/enterprise/lease-count-quotas.mdx
Labels: docs, pr/no-changelog

#16541 Move the IS Autopilot note from 1.11 upgrade guide
  website/content/docs/upgrading/index.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
Labels: pr/no-changelog, backport/1.11.x

#16494 Allow old certs to be cross-signed
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/path_sign_issuers.go
  changelog/16494.txt
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
  website/content/api-docs/secret/pki.mdx
Labels: enhancement, secret/pki

#16540 Docs/vault 7338 retry join known issue
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
  website/content/partials/raft-retry-join-failure.mdx
Labels: pr/no-changelog, backport/1.11.x

#16548 Docs/vault 7338 retry join known issue (#16540)
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/partials/raft-retry-join-failure.mdx
Labels: docs

#16546 Address test flakiness in TestLogical_AuditPort
  http/logical_test.go
Labels: pr/no-changelog

#16555 fix(docs): typos
  website/content/docs/concepts/client-count/faq.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16519 Add PSS support to PKI Secrets Engine
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_sign_issuers.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/test_helpers.go
  changelog/16519.txt
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
  website/content/api-docs/secret/pki.mdx
Labels: enhancement, secret/pki

#16558 updating changelog for vault-951
  changelog/16379.txt
Labels: pr/no-changelog

#15216 Use %q for quoted strings where appropriate
  api/client_test.go
  audit/format_json_test.go
  audit/format_jsonx_test.go
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_role.go
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/backend_test.go
  builtin/logical/aws/path_roles.go
  builtin/logical/aws/path_user.go
  builtin/logical/database/versioning_large_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/rabbitmq/backend_test.go
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_hmac_test.go
  builtin/logical/transit/path_restore_test.go
  command/agent.go
  command/agent_test.go
  command/operator_migrate.go
  command/operator_raft_join.go
  helper/metricsutil/metricsutil.go
  helper/testhelpers/logical/testing.go
  http/sys_raft.go
  physical/foundationdb/foundationdb.go
  physical/postgresql/postgresql_test.go
  physical/raft/raft.go
  physical/swift/swift_test.go
  plugins/database/hana/hana_test.go
  sdk/helper/pathmanager/pathmanager_test.go
  vault/counters_test.go
  vault/logical_raw.go
  vault/logical_system_test.go
  vault/token_store_test.go
Labels: pr/no-changelog

#16560 Update Consul bootstrap test case to conditionally add token to config
  builtin/logical/consul/backend_test.go
  helper/testhelpers/consul/consulhelper.go
Labels: pr/no-changelog

#16285 Add vkv to related tools list
  website/content/api-docs/relatedtools.mdx
Labels: docs, pr/no-changelog

#15392 refactor: replace strings.Replace with strings.ReplaceAll
  api/output_string.go
  builtin/logical/cassandra/path_creds_create.go
  builtin/logical/cassandra/util.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/rollback_test.go
  builtin/logical/mssql/util.go
  builtin/logical/mysql/secret_creds.go
  builtin/logical/mysql/util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/util.go
  builtin/logical/postgresql/query.go
  builtin/logical/ssh/util.go
  builtin/logical/transit/path_hmac_test.go
  command/agent/alicloud_end_to_end_test.go
  command/server_test.go
  command/token/helper_external.go
  helper/pgpkeys/flag_test.go
  physical/foundationdb/foundationdb.go
  physical/spanner/spanner.go
  plugins/database/hana/hana.go
  plugins/database/mysql/mysql.go
  plugins/database/postgresql/postgresql.go
  sdk/database/dbplugin/databasemiddleware.go
  sdk/database/dbplugin/v5/middleware.go
  sdk/database/helper/dbutil/dbutil.go
  sdk/database/helper/dbutil/quoteidentifier.go
  sdk/framework/openapi.go
  sdk/helper/dbtxn/dbtxn.go
  sdk/helper/keysutil/policy.go
  vault/diagnose/tls_verification.go
  vault/login_mfa.go
  vault/request_handling.go
  vault/rollback.go
  vault/router.go
Labels: enhancement

#16565 storage/raft: Make raftInfo atomic
  vault/core.go
  vault/raft.go
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16550 Vault 7338/fix retry join
  changelog/16550.txt
  helper/testhelpers/testhelpers.go
  vault/external_tests/raft/raft_test.go
  vault/external_tests/raftha/raft_ha_test.go
  vault/raft.go
Labels: bug, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16578 Fix typo in managed-keys.mdx
  website/content/docs/enterprise/managed-keys.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x

#16545 Document how replication uses cluster addresses.
  website/content/docs/internals/replication.mdx
Labels: pr/no-changelog, backport/1.11.x

#16579 Update raft.mdx
  website/content/docs/commands/operator/raft.mdx
Labels: pr/no-changelog, backport/1.11.x

#16568 UI/vault 7312/fix vault enterprise error for okta number challenge
  ui/app/components/auth-form.js
  ui/app/services/auth.js
  ui/app/templates/vault/cluster/auth.hbs
Labels: ui, pr/no-changelog

#16588 fix typo in certificate
  website/content/docs/commands/operator/raft.mdx
Labels: pr/no-changelog, backport/1.11.x

#16567 identity/oidc: adds detailed listing capability for clients and providers
  changelog/16567.txt
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  website/content/api-docs/secret/identity/oidc-provider.mdx
Labels: identity/oidc

#16569 vault documentation: updated architecture doc page
  website/content/docs/internals/architecture.mdx
  website/content/docs/internals/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#16594 auth/kerberos: add remove_instance_name config
  changelog/16594.txt
  go.mod
  go.sum
  website/content/api-docs/auth/kerberos.mdx
  website/content/docs/auth/kerberos.mdx
Labels: backport/1.11.x

#16607 Fix Link: OIDC Provider Config - Okta
  website/content/docs/auth/jwt/oidc-providers/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#16599 identity/oidc: change the state parameter to optional
  changelog/16599.txt
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/docs/concepts/oidc-provider.mdx
Labels: backport/1.10.x, backport/1.11.x

#16600 identity/oidc: fixes validation of the request and request_uri parameters
  changelog/16600.txt
  ui/app/controllers/vault/cluster/oidc-provider.js
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
Labels: backport/1.10.x, backport/1.11.x

#16613 Adding PGX change to release & upgrade notes
  website/content/docs/release-notes/1.11.0.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
  website/content/docs/upgrading/upgrade-to-1.8.x.mdx
  website/content/partials/pgx-params.mdx
  website/content/partials/raft-panic-old-tls-key.mdx
  website/content/partials/raft-retry-join-failure.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16598 identity/oidc: adds client_secret_post token endpoint authentication method
  changelog/16598.txt
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/docs/concepts/oidc-provider.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
Labels: backport/1.10.x, backport/1.11.x

#16328 introduces the post publish website event
  .release/ci.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16601 identity/oidc: reorder authorization endpoint validation for invalid redirect uris
  changelog/16601.txt
  vault/identity_store_oidc_provider.go
Labels: backport/1.10.x, backport/1.11.x

#16398 Add warning when generate_lease=true on PKI roles
  builtin/logical/pki/path_roles.go
Labels: enhancement, secret/pki, pr/no-changelog

#16638 identity/oidc: minor fixes to the API documentation
  website/content/api-docs/secret/identity/oidc-provider.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x

#16640 VAULT-7256: Add custom_metadata to namespaces
  command/commands.go
  command/namespace.go
  command/namespace_create.go
  command/namespace_patch.go
  helper/namespace/namespace.go
  sdk/helper/custommetadata/custom_metadata.go
Labels: pr/no-changelog

#16641 fix typo in Discovering the service account issuer
  website/content/docs/auth/kubernetes.mdx
Labels: docs, bug, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16633 Add custom metadata to namespace API and CLI docs
  website/content/api-docs/system/namespaces.mdx
  website/content/docs/commands/namespace.mdx
Labels: pr/no-changelog

#16634 update license FAQ docs with termination changes
  website/content/docs/enterprise/license/faq.mdx
Labels: pr/no-changelog

#16650 Clarify upgrades post 1.11
  website/content/docs/upgrading/index.mdx
Labels: website, pr/no-changelog, backport/1.11.x

#16365 Vault-5626: add key wrapping guide for transit import
  website/content/docs/secrets/transit/index.mdx
  website/content/docs/secrets/transit/key-wrapping-guide.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#16653 Add Open Source project workflow
  .github/workflows/oss.yml
Labels: pr/no-changelog

#16655 Vault documentation: updated architecture page
  website/content/docs/internals/architecture.mdx
Labels: pr/no-changelog, backport/1.11.x

#16660 Update project auto-triage to use new token
  .github/workflows/oss.yml
Labels: pr/no-changelog

#16659 UI/ fix tooltip submitting form
  changelog/16659.txt
  ui/lib/core/addon/components/info-tooltip.js
  ui/lib/core/addon/templates/components/info-tooltip.hbs
Labels: ui, bug, backport/1.11.x

#16654 UI/Client route acceptance tests - fixed branch
  ui/app/components/oidc/client-form.js
  ui/app/controllers/vault/cluster/access/oidc/clients/client.js
  ui/app/models/oidc/client.js
  ui/app/templates/components/oidc/client-form.hbs
  ui/app/templates/components/oidc/provider-list.hbs
  ui/app/templates/components/radio-card.hbs
  ui/app/templates/vault/cluster/access/oidc.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/details.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
  ui/app/templates/vault/cluster/access/oidc/index.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/radio-button.hbs
  ui/lib/core/addon/templates/components/box-radio.hbs
  ui/mirage/handlers/oidc-config.js
  ui/tests/acceptance/oidc-config/clients-test.js
  ui/tests/helpers/oidc-config.js
  ui/tests/integration/components/oidc/assignment-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
Labels: ui, pr/no-changelog

#16593 VAULT-6818 Docs for entity merge functionality
  website/content/api-docs/secret/identity/entity.mdx
Labels: docs, pr/no-changelog

#16666 Update OSS workflow so not all issues get put in the UI board
  .github/workflows/oss.yml
Labels: pr/no-changelog

#16375 [CI-only] Use pattern matching for release_branches
  .release/ci.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16670 Backport of [CI-only] Use pattern matching for release_branches into release/1.10.x
  .release/ci.hcl
Labels: pr/no-changelog

#16669 Backport of [CI-only] Use pattern matching for release_branches into release/1.9.x
  .release/ci.hcl
Labels: pr/no-changelog

#16671 Backport of [CI-only] Use pattern matching for release_branches into release/1.11.x
  .release/ci.hcl
Labels: pr/no-changelog

#16511 OIDC Assignments Details view.
  ui/app/controllers/vault/cluster/access/oidc/assignments/assignment/details.js
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/details.hbs
  ui/lib/core/addon/components/info-table-item-array.hbs
  ui/lib/core/addon/components/info-table-item-array.js
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/read-more.js
Labels: ui, pr/no-changelog

#15998 UI Support for Okta Number Challenge
  changelog/15998.txt
  ui/app/adapters/cluster.js
  ui/app/components/auth-form.js
  ui/app/components/okta-number-challenge.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/okta-number-challenge.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/tests/integration/components/okta-number-challenge-test.js
  ui/tests/unit/adapters/cluster-test.js
Labels: ui

#16506 Docs: Update Vault CSI Provider SecretProviderClass config options
  website/content/docs/platform/k8s/csi/configurations.mdx
Labels: pr/no-changelog, backport/1.11.x

#16612 UI/OIDC providers create/edit route
  ui/app/components/oidc/provider-form.js
  ui/app/components/regex-validator.hbs
  ui/app/controllers/vault/cluster/access/oidc/providers/provider.js
  ui/app/models/database/connection.js
  ui/app/models/oidc/provider.js
  ui/app/routes/vault/cluster/access/oidc/providers/create.js
  ui/app/routes/vault/cluster/access/oidc/providers/provider.js
  ui/app/templates/components/clients/config.hbs
  ui/app/templates/components/oidc/provider-form.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/create.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider/edit.hbs
  ui/lib/core/addon/components/form-field-label.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/mirage/handlers/oidc-config.js
  ui/tests/integration/components/form-field-label-test.js
  ui/tests/integration/components/oidc/provider-form-test.js
Labels: ui, pr/no-changelog

#16675 unit test: remove postgres dependecy from testing.go
  vault/testing.go
Labels: pr/no-changelog

#16573 docs: update agent template certificate section
  website/content/docs/agent/template.mdx
Labels: docs, agent, pr/no-changelog, backport/1.11.x

#16679 secrets/db: update documentation on password policies
  website/content/docs/secrets/databases/index.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16673 secrets/auth: fix bug with aliased backends
  changelog/16673.txt
  vault/auth.go
  vault/auth_test.go
  vault/mount.go
  vault/mount_test.go
  vault/testing.go
Labels: backport/1.11.x

#16674 Cleanup OIDC Config Mirage handler
  ui/mirage/handlers/oidc-config.js
  ui/tests/acceptance/oidc-config/clients-test.js
  ui/tests/helpers/oidc-config.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/oidc/provider-form-test.js
Labels: ui, pr/no-changelog

#16687 add a note clarifying to leave website event in oss only
  .release/ci.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16686 secret/database: fix bug where too many wal deletes are deferred
  builtin/logical/database/rotation.go
  changelog/16686.txt
Labels: backport/1.9.x, backport/1.10.x, backport/1.11.x

#16697 Fix UI Enterprise test failures on 1.9 specifically
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/enterprise-kmip-test.js
Labels: ui, pr/no-changelog

#16698 Fix UI Enterprise test failures on 1.10 specifically
  ui/tests/acceptance/enterprise-kmip-test.js
Labels: ui, pr/no-changelog

#16703 Fix enterprise test failures for 1.11
  ui/tests/acceptance/enterprise-kmip-test.js
Labels: ui, pr/no-changelog

#16665 Update replication-dr.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
Labels: pr/no-changelog, backport/1.11.x

#16645 Update health.mdx
  website/content/api-docs/system/health.mdx
Labels: pr/no-changelog, backport/1.11.x

#16695 Do not mask RSA verification misuse errors as verification failures
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_test.go
Labels: pr/no-changelog

#16399 Update internal-ui-mounts.mdx
  website/content/api-docs/system/internal-ui-mounts.mdx
Labels: docs, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16707 Scope acceptance tests
  ui/app/components/oidc/scope-form.js
  ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/scope/details.hbs
  ui/tests/acceptance/oidc-config/scopes-test.js
  ui/tests/helpers/oidc-config.js
  ui/tests/integration/components/oidc/scope-form-test.js
Labels: ui, pr/no-changelog

#16632 UI/OIDC Provider read view
  ui/app/adapters/named-path.js
  ui/app/controllers/vault/cluster/access/oidc/providers/provider/details.js
  ui/app/router.js
  ui/app/routes/vault/cluster/access/oidc/providers/provider/clients.js
  ui/app/serializers/oidc/client.js
  ui/app/templates/components/oidc/client-list.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/details.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider/clients.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider/details.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/scope/details.hbs
  ui/tests/acceptance/oidc-config/clients-test.js
  ui/tests/helpers/oidc-config.js
  ui/tests/integration/components/oidc/provider-form-test.js
  ui/tests/unit/adapters/oidc/client-test.js
  ui/tests/unit/adapters/oidc/test-helper.js
Labels: ui, pr/no-changelog

#16662 Backport of UI/ fix tooltip submitting form into release/1.11.x
  changelog/16659.txt
  ui/lib/core/addon/components/info-tooltip.js
  ui/lib/core/addon/templates/components/info-tooltip.hbs
Labels: ui, backport, bug

#16711 vault documentation: doc cleanup effort-batch4
  website/content/docs/internals/integrated-storage.mdx
  website/content/docs/internals/security.mdx
Labels: pr/no-changelog, backport/1.11.x

#16564 Add BYOC-based revocation to PKI secrets engine
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
  changelog/16564.txt
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki, cryptosec

#16721 Ignore EC PARAMETER blocks during issuer import
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_manage_issuers.go
  changelog/16721.txt
Labels: bug, secret/pki, backport/1.11.x

#16684 UI/vault 7613/flaky test glimmerize confirm action
  ui/lib/core/addon/components/confirm-action.hbs
  ui/lib/core/addon/components/confirm-action.js
  ui/lib/kmip/addon/components/header-credentials.hbs
  ui/lib/kmip/addon/components/header-credentials.js
  ui/lib/kmip/addon/routes/role.js
  ui/tests/acceptance/enterprise-kmip-test.js
Labels: ui, pr/no-changelog

#16497 handle ssct errors in PopulateTokenEntry
  vault/request_handling.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16725 metadata for client list view
  ui/app/templates/components/oidc/client-list.hbs
  ui/tests/acceptance/oidc-config/clients-test.js
Labels: ui, pr/no-changelog

#16730 Fix a typo -> 'authorised' should be 'authorized'
  website/content/docs/auth/cert.mdx
Labels: pr/no-changelog, backport/1.11.x

#16606 Removed the extra div around the radio button.
  ui/lib/replication/addon/templates/components/replication-summary.hbs
Labels: ui, bug, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16736 Backport of Removed the extra div around the radio button. into release/1.11.x
  ui/lib/replication/addon/templates/components/replication-summary.hbs
Labels: ui, backport, bug

#16566 Add proof possession revocation for PKI secrets engine
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_revoke.go
  changelog/16566.txt
  sdk/helper/certutil/helpers.go
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: secret/pki, cryptosec

#9288 Update kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: ecosystem, website, pr/no-changelog, backport/1.11.x

#9738 Updated OpenShift version
  website/content/docs/platform/k8s/helm/openshift.mdx
Labels: ecosystem, website, pr/no-changelog, backport/1.11.x

#16739 Fix naming of permitted_dns_domains in webui
  changelog/16739.txt
  ui/app/models/pki-ca-certificate-sign.js
  ui/app/models/pki-ca-certificate.js
Labels: ui, bug, secret/pki, backport/1.11.x

#16056 fix bug with allowed_users_template and add allowed_domains_template for SSH role
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/ssh/path_roles.go
  changelog/16056.txt
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, secret/ssh

#13014 dev docs: clarify internal and external token helpers
  command/config/util.go
  command/token/helper_external.go
  command/util.go
Labels: pr/no-changelog

#16446 vault documentation: general doc cleanup
  website/content/docs/browser-support.mdx
  website/content/docs/use-cases.mdx
  website/content/docs/what-is-vault.mdx
Labels: pr/no-changelog, backport/1.11.x

#16751 Update the Vault Agent config example
  website/content/docs/agent/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#16731 docs/vault-helm: updates for the v0.21.0 release
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/external.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/index.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
  website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
  website/content/partials/helm/version.mdx
Labels: pr/no-changelog, backport/1.11.x

#16473 re-add namespace attribution to current month
  changelog/16447.txt
  vault/activity_log.go
Labels: pr/no-changelog

#16745 Allow Partial Month Counts To Be Returned Without Precomputation [OSS]
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
Labels: pr/no-changelog

#16764 Update consul-template to v0.29.2.
  go.mod
  go.sum
Labels: agent, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16747 Fix the referenced learn link
  website/content/docs/platform/k8s/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#16749 Fix spelling issues
  website/content/api-docs/relatedtools.mdx
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/1.11.x

#16743 Mount paths case-sensitivity
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/secrets/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#16775 Backport Update consul-template v0.29.2 (#16764) to 1.11.x
  go.mod
  go.sum
Labels: pr/no-changelog

#16738 metadata for provider list view
  ui/app/serializers/oidc/provider.js
  ui/app/templates/components/oidc/provider-list.hbs
Labels: ui, pr/no-changelog

#16683 Env Flag Filtering
  command/base.go
  command/base_helpers.go
  command/base_helpers_test.go
  command/main.go
Labels: pr/no-changelog

#16781 update go-plugin to v1.4.5
  go.mod
  go.sum
Labels: pr/no-changelog

#16777 Confirm-action fixes
  ui/lib/core/addon/components/confirm-action.hbs
  ui/lib/core/addon/components/confirm-action.js
  ui/tests/integration/components/confirm-action-test.js
Labels: ui, pr/no-changelog

#16780 Add Multi-Host Connection String info to Postgres secrets API docs
  website/content/api-docs/secret/databases/postgresql.mdx
  website/content/docs/secrets/databases/postgresql.mdx
Labels: pr/no-changelog

#16779 Setting upload url explicitly empty
  builtin/credential/github/backend.go
Labels: pr/no-changelog

#16744 UI/Add client ids to search select
  ui/app/adapters/named-path.js
  ui/app/components/oidc/provider-form.js
  ui/app/routes/vault/cluster/access/oidc/clients/client/providers.js
  ui/app/routes/vault/cluster/access/oidc/providers/provider/clients.js
  ui/app/templates/components/oidc/provider-form.hbs
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/tests/integration/components/oidc/provider-form-test.js
  ui/tests/integration/components/search-select-test.js
  ui/tests/unit/adapters/oidc/test-helper.js
Labels: ui, pr/no-changelog

#16774 Fixing flaky "oidc auth method" tests
  ui/tests/acceptance/oidc-auth-method-test.js
Labels: ui, pr/no-changelog

#16783 vault documentation: updated use cases doc
  website/content/docs/use-cases.mdx
Labels: pr/no-changelog, backport/1.11.x

#16621 Allow marking issuers as revoked
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/storage.go
  changelog/16621.txt
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: secret/pki, cryptosec

#16741 OIDC Assignment Acceptance tests
  ui/app/components/oidc/assignment-form.js
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/details.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs
  ui/tests/acceptance/oidc-config/assignments-test.js
  ui/tests/acceptance/oidc-config/clients-test.js
  ui/tests/acceptance/oidc-config/scopes-test.js
  ui/tests/helpers/oidc-config.js
  ui/tests/integration/components/oidc/assignment-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/unit/adapters/oidc/assignment-test.js
Labels: ui, pr/no-changelog

#16563 Add per-issuer AIA URI information to PKI secrets engine
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_config_urls.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
  changelog/16563.txt
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: secret/pki, cryptosec

#16793 Backport consul-template update
  go.mod
  go.sum
Labels: agent, pr/no-changelog

#16792 Backport consul-template update
  go.mod
  go.sum
Labels: agent, pr/no-changelog

#16776 UI/Key details view
  ui/app/components/oidc/key-form.js
  ui/app/controllers/vault/cluster/access/oidc/keys/key.js
  ui/app/controllers/vault/cluster/access/oidc/keys/key/details.js
  ui/app/models/oidc/key.js
  ui/app/router.js
  ui/app/routes/vault/cluster/access/oidc/keys/key/clients.js
  ui/app/serializers/oidc/client.js
  ui/app/templates/components/oidc/key-form.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key/clients.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key/details.hbs
  ui/tests/integration/components/oidc/key-form-test.js
Labels: ui, pr/no-changelog

#12631 Telemetry typo fix in vault.secret.kv.count
  website/content/docs/internals/telemetry.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#12596 Docs/autopilot typo fix and DR autopilot clarification
  website/content/api-docs/system/storage/raftautopilot.mdx
  website/content/docs/concepts/integrated-storage/autopilot.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16804 Include jwt_claim expiration error message
  website/content/docs/auth/gcp.mdx
Labels: pr/no-changelog, backport/1.11.x

#16803 Clarify keytab gen process
  website/content/docs/auth/kerberos.mdx
Labels: pr/no-changelog, backport/1.11.x

#16756 Revert "Do not mask RSA verification misuse errors as verification failures (#16695)"
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_test.go
Labels: pr/no-changelog

#16808 Update apiVersion of the ClusterRoleBinding example
  website/content/docs/auth/kubernetes.mdx
Labels: docs, auth/k8s, pr/no-changelog, backport/1.11.x

#16799 Update crypto package to fix GO-2021-0356
  go.mod
  go.sum
Labels: pr/no-changelog

#16813 Migrate existing PKI mounts that only contains a key
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations_test.go
  changelog/16813.txt
Labels: secret/pki, backport/1.11.x

#16796 UI: rollbackAttributes when destroyRecord fails
  ui/app/controllers/vault/cluster/access/oidc/assignments/assignment/details.js
  ui/app/controllers/vault/cluster/access/oidc/clients/client/details.js
  ui/app/controllers/vault/cluster/access/oidc/keys/key/details.js
  ui/app/controllers/vault/cluster/access/oidc/providers/provider/details.js
  ui/app/controllers/vault/cluster/access/oidc/scopes/scope/details.js
Labels: ui, pr/no-changelog

#16723 Add an OCSP responder to Vault's PKI plugin
  builtin/logical/pki/backend.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/ocsp.go
  builtin/logical/pki/ocsp_test.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_test.go
  builtin/logical/pki/test_helpers.go
  builtin/logical/pki/util.go
  changelog/16723.txt
  http/logical.go
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki

#16817 Update Userpass API Docs
  website/content/api-docs/auth/userpass.mdx
Labels: docs, auth/userpass, pr/no-changelog, backport/1.11.x

#12517 Use HCL syntax for code snippet
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, website, pr/no-changelog, backport/1.11.x

#16824 Update phrasing in internals/architecture
  website/content/docs/internals/architecture.mdx
Labels: pr/no-changelog, backport/1.11.x

#16830 Fix LIST issuers endpoint
  builtin/logical/pki/backend.go
  changelog/16830.txt
Labels: bug, secret/pki, cryptosec, backport/1.11.x

#16821 UI: Forward to `redirect_to` param to when auth'd
  changelog/16821.txt
  ui/app/lib/route-paths.js
  ui/app/mixins/cluster-route.js
  ui/app/router.js
  ui/app/routes/vault/cluster/redirect.js
  ui/app/templates/vault/cluster/redirect.hbs
  ui/tests/unit/mixins/cluster-route-test.js
  ui/tests/unit/routes/vault/cluster/redirect-test.js
Labels: ui

#16677 Add VAULT_ASSUMED_ROLE_ARN parameter to VLE docs
  website/content/docs/platform/aws/lambda-extension.mdx
Labels: pr/no-changelog

#16835 Finish refactor to remove global crlLifetime
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/storage.go
Labels: bug, secret/pki, pr/no-changelog

#16811 OSS portion of wrapper-v2
  command/agent.go
  command/agent/cache/cacheboltdb/bolt.go
  command/agent/cache/cacheboltdb/bolt_test.go
  command/agent/cache/keymanager/manager.go
  command/agent/cache/keymanager/passthrough.go
  command/agent/cache/keymanager/passthrough_test.go
  command/agent/cache/lease_cache_test.go
  command/operator_diagnose.go
  command/server.go
  command/server/server_seal_transit_acc_test.go
  go.mod
  go.sum
  helper/testhelpers/seal/sealhelper.go
  http/sys_init_test.go
  internalshared/configutil/encrypt_decrypt.go
  internalshared/configutil/encrypt_decrypt_test.go
  internalshared/configutil/kms.go
  physical/raft/raft.go
  vault/core.go
  vault/external_tests/raft/raft_test.go
  vault/external_tests/sealmigration/testshared.go
  vault/ha.go
  vault/identity_store_oidc.go
  vault/init.go
  vault/init_test.go
  vault/logical_system.go
  vault/logical_system_raft.go
  vault/raft.go
  vault/rekey.go
  vault/rekey_test.go
  vault/seal.go
  vault/seal/envelope.go
  vault/seal/seal.go
  vault/seal/seal_testing.go
  vault/seal_access.go
  vault/seal_autoseal.go
  vault/seal_autoseal_test.go
  vault/seal_testing_util.go
  vault/sealunwrapper.go
  vault/sealunwrapper_test.go
Labels: pr/no-changelog

#16838 identity/entity-alias: fix bug where wrong metadata was updated
  vault/identity_store.go
  vault/identity_store_test.go
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16760 [QTI-308] Add Enos intregration tests
  .github/workflows/build.yml
  .github/workflows/enos-fmt.yml
  .github/workflows/enos-run.yml
  .gitignore
  enos/Makefile
  enos/README.md
  enos/enos-modules.hcl
  enos/enos-providers.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-terraform.hcl
  enos/enos-variables.hcl
  enos/enos.vars.hcl
  enos/modules/autopilot_upgrade_storageconfig/main.tf
  enos/modules/az_finder/main.tf
  enos/modules/backend_raft/main.tf
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/build_local/templates/build.sh
  enos/modules/get_local_version_from_make/main.tf
  enos/modules/get_local_version_from_make/scripts/version.sh
  enos/modules/read_license/main.tf
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_upgrade/templates/get-follower-public-ips.sh
  enos/modules/vault_upgrade/templates/get-leader-public-ip.sh
  enos/modules/vault_upgrade/templates/restart-vault.sh
  enos/modules/vault_verify_autopilot/main.tf
  enos/modules/vault_verify_autopilot/templates/smoke-verify-autopilot.sh
  enos/modules/vault_verify_raft_auto_join_voter/main.tf
  enos/modules/vault_verify_raft_auto_join_voter/templates/verify-raft-auto-join-voter.sh
  enos/modules/vault_verify_unsealed/main.tf
  enos/modules/vault_verify_unsealed/templates/verify-vault-node-unsealed.sh
  enos/modules/vault_verify_version/main.tf
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
Labels: backport, pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#16834 command/debug: fix bug where monitor was not honoring configured duration
  changelog/16834.txt
  command/debug.go
Labels: backport/1.9.x, backport/1.10.x, backport/1.11.x

#16857 Add documentation for enabling mutual TLS with the CloudFoundry API
  website/content/docs/auth/cf.mdx
Labels: pr/no-changelog, backport/1.11.x

#16859 Updated Nomad Secret Engine docs with proper terminology
  website/content/api-docs/secret/nomad.mdx
  website/content/docs/secrets/nomad.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x

#16826 Docs: SSH CA Config & Comments. Resolves: #7529
  website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
Labels: docs, secret/ssh, pr/no-changelog

#16848 Handle multiple matching issuers in OCSP requests
  builtin/logical/pki/ocsp.go
  builtin/logical/pki/ocsp_test.go
Labels: pr/no-changelog

#9081 updated usage example
  changelog/9081.txt
  website/content/api-docs/secret/transit.mdx
  website/content/docs/secrets/consul.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#13092 Documentation grammar update for https://www.vaultproject.io/docs/concepts/seal#migration-post-vault-1-5-1
  website/content/docs/concepts/seal.mdx
Labels: pr/no-changelog, backport/1.11.x

#16763 Identify issuer on revocation
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
Labels: secret/pki, pr/no-changelog

#16795 Docs: Client Count Concept clarity.
  website/content/docs/concepts/client-count/index.mdx
Labels: pr/no-changelog, backport/1.11.x
