Repository hashicorp/vault, pull requests merged in 2022-01, with the labels that each got.

#13521 fix: backport squashes into stable-website
  .github/workflows/backport-docs.yml
Labels: pr/no-changelog

#13510 Updating version for 1.7.9
  sdk/version/version_base.go
  vendor/github.com/hashicorp/vault/sdk/version/version_base.go
Labels: pr/no-changelog

#13511 Updating version for 1.8.8
  sdk/version/version_base.go
Labels: pr/no-changelog

#13512 Updating version for 1.9.3
  sdk/version/version_base.go
Labels: pr/no-changelog

#13547 Go get for 1.9.3 SDK
  go.mod
Labels: pr/no-changelog

#13546 Go get for 1.7.9 SDK
  go.mod
  vendor/modules.txt
Labels: pr/no-changelog

#13545 Go get for 1.8.8 SDK
  go.mod
Labels: pr/no-changelog

#13522 Updates codeowners for OIDC coordination with UI
  CODEOWNERS
Labels: pr/no-changelog

#13140 fix(docs-k8s-helm): changed server's podAntiAffinity labelSelector example to match helm default values
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs, pr/no-changelog

#13548 secrets/gcp: update plugin to v0.11.1
  changelog/13548.txt
  go.mod
  go.sum
Labels: backport/1.9.x

#13543 Update docs to reflect new plugin behavior.
  website/content/docs/internals/plugins.mdx
Labels: docs, pr/no-changelog

#13552 Fix status icon color after moving to flight icons
  ui/app/styles/components/status-menu.scss
  ui/app/templates/components/status-menu.hbs
  ui/public/status-indicator.svg
Labels: ui, bug, pr/no-changelog

#13553 Vault documentation: fixed broken links
  website/content/docs/concepts/ha.mdx
Labels: pr/no-changelog, backport/website

#13539 Fix a sentence in architecture.mdx
  website/content/docs/internals/architecture.mdx
Labels: docs, pr/no-changelog, backport/website, backport/1.9.x, backport/1.8.x

#13562 client count doc: corrected name and added link
  website/content/docs/concepts/client-count/index.mdx
Labels: backport/website, backport/1.9.x, backport/1.8.x

#13572 docs: update GitHub auth method docs and security model
  website/content/docs/auth/github.mdx
  website/content/docs/auth/index.mdx
  website/content/docs/internals/security.mdx
Labels: pr/no-changelog, backport/website, backport/1.9.x, backport/1.8.x

#13439 update okta-sdk-golang to v2.9.1
  changelog/13439.txt
  go.mod
  go.sum
Labels: auth/okta

#13567 Updated Vault API documentation: added permissions table
  website/content/api-docs/secret/azure.mdx
Labels: pr/no-changelog, backport/website

#13574 UI/client count 1.10
  ui/app/components/clients/attribution.js
  ui/app/components/clients/dashboard.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/styles/components/bar-chart.scss
  ui/app/styles/core.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/horizontal-bar-chart.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/app/templates/vault/cluster/clients/index.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/components/bar-chart.js
  ui/mirage/config.js
  ui/package.json
  ui/yarn.lock
Labels: pr/no-changelog

#13590 Search Select Input Fix
  changelog/13590.txt
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/lib/core/package.json
  ui/lib/core/stories/search-select.md
  ui/package.json
  ui/yarn.lock
Labels: ui

#13585 UI/fix kmip role form
  changelog/13585.txt
  ui/app/adapters/kmip/role.js
  ui/app/models/kmip/role.js
  ui/app/templates/components/generate-credentials.hbs
  ui/app/templates/components/identity/item-alias/alias-details.hbs
  ui/app/templates/components/identity/item-details.hbs
  ui/app/templates/components/license-info.hbs
  ui/app/templates/components/tool-lookup.hbs
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/info-table-row.js
  ui/lib/core/addon/templates/components/info-table-row.hbs
  ui/lib/replication/addon/templates/mode/secondaries/config-show.hbs
  ui/tests/acceptance/secrets/backend/pki/cert-test.js
  ui/tests/integration/components/info-table-row-test.js
Labels: ui, backport, bug

#13593 docs: fix typo in azure auth debug log mode
  website/content/docs/auth/azure.mdx
Labels: docs-cherrypick, pr/no-changelog

#13571 Add missing word "database" in docs
  README.md
  website/content/docs/what-is-vault.mdx
Labels: docs, pr/no-changelog, backport/website

#13594 Backport 1.9.3: UI/fix kmip role form (#13585)
  changelog/13585.txt
  ui/app/adapters/kmip/role.js
  ui/app/models/kmip/role.js
Labels: ui, backport, bug

#13586 add retry logic to TestKV_Patch_RootToken
  http/handler_test.go
  vault/external_tests/kv/kv_patch_test.go
Labels: secret/kv, pr/no-changelog

#13592 Note that api_addr and cluster_addr can use go-sockaddr templates.
  website/content/docs/configuration/index.mdx
Labels: pr/no-changelog, backport/1.9.x

#13601 UI/fix icon colors
  ui/app/helpers/mountable-auth-methods.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/styles/components/empty-state.scss
  ui/app/styles/components/page-header.scss
  ui/app/styles/components/toolbar.scss
  ui/app/templates/components/alert-popup.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/diff-version-selector.hbs
  ui/app/templates/components/mount-backend-form.hbs
Labels: ui, pr/no-changelog

#13604 UI/Fixes secrets list breadcrumb
  changelog/13604.txt
  ui/app/templates/components/secret-list-header.hbs
Labels: ui, bug, backport/1.9.x, backport/1.8.x

#13614 Clarify the distinction between token and identity policies.
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog, backport/website, backport/1.9.x, backport/1.8.x

#13628 Flaky Acceptance Tests
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/secrets/backend/pki/role-test.js
  ui/tests/acceptance/transit-test.js
  ui/tests/acceptance/unseal-test.js
Labels: ui, pr/no-changelog

#13618 Backport 1.7.x: UI/Fix secrets list breadcrumb nav
  changelog/13604.txt
  ui/app/templates/components/secret-list-header.hbs
Labels: ui, bug

#13613 Client Count Calendar Widget for 1.10
  ui/app/components/calendar-widget.js
  ui/app/components/clients/dashboard.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/core.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/dashboard.hbs
Labels: ui, pr/no-changelog

#13620 Mirage Dev Workflow
  ui/config/environment.js
  ui/mirage/config.js
  ui/mirage/handlers/base.js
  ui/mirage/handlers/index.js
  ui/package.json
Labels: ui, pr/no-changelog

#13191 use GetOkErr in patch handler so type coercion errors result in error response
  sdk/framework/backend.go
Labels: pr/no-changelog

#13632 Template Lint Overrides
  ui/.template-lintrc.js
Labels: ui, pr/no-changelog

#13638 KMSE: Key Model / Adapter / Serializer setup
  ui/app/adapters/keymgmt/key.js
  ui/app/components/keymgmt/key-edit.js
  ui/app/helpers/options-for-backend.js
  ui/app/models/keymgmt/key.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/keymgmt/key.js
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/lib/core/addon/components/info-table-row.hbs
  ui/mirage/handlers/index.js
  ui/mirage/handlers/kms.js
  ui/tests/integration/components/info-table-row-test.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
Labels: ui, pr/no-changelog

#13633 Vault documentation: updated client count FAQ
  website/content/docs/concepts/client-count/faq.mdx
Labels: pr/no-changelog, backport/website

#13598 Backport 1.8.x: UI Fix KMIP Role not saving (#13594)
  changelog/13585.txt
  ui/app/adapters/kmip/role.js
  ui/app/models/kmip/role.js
Labels: ui, bug

#13599 Backport 1.7.9: UI Fix KMIP Role not saving (#13594)
  changelog/13585.txt
  ui/app/adapters/kmip/role.js
  ui/app/models/kmip/role.js
Labels: ui, bug

#13635 UI/Clients single month template
  ui/app/styles/components/stat-text.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/single-month.hbs
  ui/lib/core/addon/components/stat-text.js
  ui/lib/core/addon/helpers/format-number.js
  ui/lib/core/addon/templates/components/bar-chart.hbs
Labels: ui, pr/no-changelog

#13642 UI/Attribution component updates
  ui/app/components/clients/attribution.js
  ui/app/components/clients/dashboard.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/styles/components/modal.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/lib/core/addon/templates/components/download-csv.hbs
  ui/mirage/handlers/activity.js
  ui/mirage/handlers/index.js
Labels: ui, pr/no-changelog

#13640 secrets/keymgmt: Adds documentation for using Azure Private Link
  website/content/docs/secrets/key-management/awskms.mdx
  website/content/docs/secrets/key-management/azurekeyvault.mdx
Labels: pr/no-changelog, backport/website

#13641 auth/azure: Documents config env vars and fixes resource used in examples
  website/content/api-docs/auth/azure.mdx
  website/content/docs/auth/azure.mdx
Labels: pr/no-changelog, backport/website

#13659 docs: update oracle tls examples
  website/content/docs/secrets/databases/oracle.mdx
Labels: pr/no-changelog, backport/website

#13668 Flaky Replication Tests
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/helpers/poll-cluster.js
Labels: ui, pr/no-changelog

#13667 Vault-3991 Code Scanning Alerts Changes
  changelog/13667.txt
  command/base_flags.go
  sdk/helper/certutil/helpers.go
  sdk/logical/translate_response.go
  vault/auth.go
  vault/barrier_aes_gcm.go
  vault/identity_store_oidc.go
  vault/mount.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.7.x

#13595 auth/kubernetes: support for dynamically reloading short-lived tokens
  changelog/13595.txt
  go.mod
  go.sum
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: ecosystem, auth/k8s

#13661 Make auth/token/revoke-accessor idempotent
  changelog/13661.txt
  vault/logical_system.go
  vault/token_store.go
  vault/token_store_test.go
Labels: core/token

#13684 Remove extra commas
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, backport/website, backport/1.9.x, backport/1.8.x, backport/1.7.x

#13692 Update http requests API link to versioned docs
  website/content/docs/upgrading/upgrade-to-1.9.x.mdx
Labels: pr/no-changelog, backport/website

#13637 Client Count - startDate
  ui/app/adapters/clients/new-init-activity.js
  ui/app/components/calendar-widget.js
  ui/app/components/clients/dashboard.js
  ui/app/models/clients/new-init-activity.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/serializers/clients/new-init-activity.js
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/mirage/handlers/activity.js
Labels: ui, pr/no-changelog

#13673 UI/Update activity response with mock data
  ui/mirage/handlers/activity.js
Labels: ui, pr/no-changelog

#13693 Depend explicitly on go-msgpack v1.1.5
  go.mod
  physical/raft/msgpack.go
Labels: pr/no-changelog

#13678 Support go-sockaddr templates in top-level cluster_addr config
  changelog/13678.txt
  command/server.go
  vault/core.go
Labels: backport/1.9.x

#13708 docs/oracle: fix typo in connection_url example
  website/content/docs/secrets/databases/oracle.mdx
Labels: docs, pr/no-changelog, backport/website

#13699 OSS side of the managed key interfaces
  sdk/logical/managed_key.go
  vault/managed_key.go
Labels: pr/no-changelog

#13696 OSS changes for ent pr
  api/client.go
  command/agent.go
  command/agent/auth/cert/cert.go
  command/agent/sink/sink.go
Labels: pr/no-changelog

#13662 docs: add known issues section to 1.9.x upgrade guide
  website/content/docs/upgrading/upgrade-to-1.9.x.mdx
Labels: docs, pr/no-changelog, backport/website

#12438 Docs add algo signer to support openssl as of recent
  website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
Labels: pr/no-changelog, backport/website

#13537 Enhance sys/raw to read and write values that cannot be encoded in json
  changelog/13537.txt
  sdk/helper/compressutil/compress.go
  sdk/helper/compressutil/compress_test.go
  vault/logical_raw.go
  vault/logical_system_test.go
  website/content/api-docs/system/raw.mdx
Labels: enhancement

#13691 Time-based transit key autorotation
  builtin/logical/transit/backend.go
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_config.go
  builtin/logical/transit/path_config_test.go
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_keys_test.go
  changelog/13691.txt
  sdk/helper/keysutil/lock_manager.go
  sdk/helper/keysutil/policy.go
  website/content/api-docs/secret/transit.mdx
Labels: secret/transit, cryptosec

#13683 Accept both -f and --force in the web terminal
  changelog/13683.txt
  ui/app/components/console/ui-panel.js
  ui/app/lib/console-helpers.js
  ui/tests/unit/lib/console-helpers-test.js
Labels: ui

#13660 Add support for client certificates to -output-curl-string
  api/client.go
  api/output_string.go
  changelog/13660.txt
Labels: core/cli

#13728 Add tag to fix DNS bug with mac builds
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.7.x

#13727 Vault3991 Fix lower bound check
  command/base_flags.go
Labels: pr/no-changelog

#13740 Vault documentation: Fixed typo on browser support page
  website/content/docs/browser-support.mdx
Labels: pr/no-changelog, backport/website

#13743 Backport 1.9.x: UI/Fix secrets list breadcrumb nav
  changelog/13604.txt
  ui/app/templates/components/secret-list-header.hbs
Labels: ui, bug

#13744 Backport 1.8.x: UI/Fix secrets list breadcrumb nav
  changelog/13604.txt
  ui/app/templates/components/secret-list-header.hbs
Labels: ui, bug

#13703 Update to raft lib v1.3.3
  changelog/13703.txt
  go.mod
  go.sum
Labels: backport/1.9.x, backport/1.8.x, backport/1.7.x

#13747 Correct doc link for namespaces in API Explorer
  ui/lib/open-api-explorer/addon/templates/components/swagger-ui.hbs
Labels: pr/no-changelog, backport/1.9.x

#13749 Raft/fix raft telemetry metric unit
  changelog/13749.txt
  physical/raft/raft.go
Labels: backport/1.9.x, backport/1.8.x

#13716 oidc: check for nil signing key on rotation
  changelog/13716.txt
  vault/identity_store_oidc.go
  vault/identity_store_oidc_test.go
Labels: backport/1.9.x

#13767 Client count 1.10 reshuffle
  ui/app/controllers/vault/cluster/clients/index.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/vault/cluster/clients/index.hbs
  ui/lib/open-api-explorer/addon/templates/components/swagger-ui.hbs
  ui/mirage/handlers/activity.js
  ui/mirage/handlers/base.js
Labels: ui, pr/no-changelog

#12787 Add LIST support to sys/policies/password
  changelog/12787.txt
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  website/content/api-docs/system/policies-password.mdx
Labels: waiting-for-response, core/policy

#13751 Updated spelling
  website/content/docs/release-notes/1.9.0.mdx
Labels: pr/no-changelog, backport/website

#13748 docs/k8s: Updates for vault-k8s 0.14.2 and vault-helm 0.19.0
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, backport/website

#13531 docs: add vault-plugin-secrets-jenkins to plugin portal page
  website/content/docs/plugin-portal.mdx
Labels: pr/no-changelog, backport/website

#13775 Vault documentation: Re-added missing heading
  website/content/docs/enterprise/license/autoloading.mdx
Labels: pr/no-changelog, backport/website

#12262 Update influxdb client
  changelog/12262.txt
  go.mod
  go.sum
  plugins/database/influxdb/connection_producer.go
  plugins/database/influxdb/influxdb.go
  plugins/database/influxdb/influxdb_test.go
Labels: ecosystem, dependencies, secret/database/influxdb

#13778 Remove Faker
  ui/app/components/file-to-array-buffer.js
  ui/mirage/factories/configuration.js
  ui/mirage/factories/secret-engine.js
  ui/mirage/factories/server.js
  ui/package.json
  ui/tests/.eslintrc.js
Labels: ui, pr/no-changelog

#13776 docs: fix limits docs to reflect listener variable name
  website/content/docs/internals/limits.mdx
Labels: docs, pr/no-changelog, backport/website, backport/1.8.x, backport/1.7.x

#13717 UI/Revert client count work pushed to 1.11, add monthly and activity serializers
  ui/app/adapters/clients/activity.js
  ui/app/adapters/clients/monthly.js
  ui/app/adapters/clients/new-init-activity.js
  ui/app/components/clients/attribution.js
  ui/app/components/clients/dashboard.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/monthly-usage.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/models/clients/activity.js
  ui/app/models/clients/monthly.js
  ui/app/models/clients/new-init-activity.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/serializers/clients/new-init-activity.js
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/mirage/factories/metrics/activity.js
  ui/mirage/handlers/activity.js
Labels: ui, pr/no-changelog

#12791 Return num_uses during authentication
  changelog/12791.txt
  http/logical_test.go
  sdk/logical/translate_response.go
  website/content/api-docs/auth/token.mdx
Labels: docs-cherrypick, pr/no-changelog

#13763 Update CSI provider installation on OpenShift
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
Labels: pr/no-changelog, backport/website

#13768 website: Add Qualified chatbot to consent manager
  website/lib/consent-manager-services/index.ts
  website/pages/_app.js
Labels: website, pr/no-changelog, backport/website

#12790 Add remote_port in the audit logs when it is available
  audit/format.go
  changelog/12790.txt
  http/logical.go
  http/logical_test.go
  sdk/logical/connection.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
Labels: enhancement, waiting-for-response, core/audit

#13793 OSS integration of the PKI plugin with managed key infrastructure
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/managed_key_util.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/util.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
  sdk/logical/managed_key.go
Labels: pr/no-changelog

#13795 Fix a transit deadlock
  builtin/logical/transit/backend.go
Labels: secret/transit, pr/no-changelog, cryptosec

#13229 Add SSH auth plugin to plugin portal
  website/content/docs/plugin-portal.mdx
Labels: ecosystem/plugin

#13808 Updating website for 1.9.3
  website/data/version.js
Labels: pr/no-changelog, backport/website

#13788 UI/Current month view
  ui/app/components/clients/attribution.js
  ui/app/components/clients/current.js
  ui/app/components/clients/dashboard.js
  ui/app/models/clients/activity.js
  ui/app/models/clients/monthly.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/styles/components/stat-text.scss
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/single-month.hbs
  ui/app/templates/components/clients/usage-stats.hbs
Labels: ui, pr/no-changelog

#13797 KMS Providers
  ui/app/adapters/keymgmt/key.js
  ui/app/adapters/keymgmt/provider.js
  ui/app/components/keymgmt/provider-edit.js
  ui/app/components/pagination-controls.js
  ui/app/controllers/vault/cluster/secrets/backend/edit.js
  ui/app/controllers/vault/cluster/secrets/backend/show.js
  ui/app/helpers/options-for-backend.js
  ui/app/helpers/secret-query-params.js
  ui/app/helpers/sub.js
  ui/app/models/keymgmt/key.js
  ui/app/models/keymgmt/provider.js
  ui/app/routes/vault/cluster/secrets/backend/create-root.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/keymgmt/provider.js
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/core/title.scss
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/components/pagination-controls.hbs
  ui/app/templates/components/secret-list/item.hbs
  ui/app/utils/model-validations-helper.js
  ui/mirage/handlers/kms.js
  ui/stories/pagination-controls.md
  ui/tests/integration/components/keymgmt/provider-edit-test.js
  ui/tests/integration/components/pagination-controls-test.js
Labels: ui, pr/no-changelog

#13811 Remove deprecated call to BuildNameToCertificate
  api/plugin_helpers.go
  sdk/helper/certutil/types.go
  sdk/helper/pluginutil/tls.go
  vault/testing.go
Labels: pr/no-changelog

#13813 Clarify that backend authors can specify that all or no values are sealwrapped
  website/content/docs/enterprise/sealwrap.mdx
Labels: docs-cherrypick, pr/no-changelog

#13815 Add notes on the PKI cert generation forwarding regression
  website/content/docs/upgrading/upgrade-to-1.8.x.mdx
  website/content/docs/upgrading/upgrade-to-1.9.x.mdx
  website/content/partials/pki-forwarding-bug.mdx
Labels: pr/no-changelog, backport/website

#13799 Remove fmt strings and replace with inline queries
  changelog/13799.txt
  plugins/database/mssql/mssql.go
  plugins/database/mssql/mssql_test.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.7.x

#13805 docs: add cluster-to-cluster communications to external threat overview
  website/content/docs/internals/security.mdx
Labels: docs, pr/no-changelog, backport/website

#11218 pki: calculate Subject Key Identifier according to RFC 5280
  changelog/11218.txt
  sdk/helper/certutil/helpers.go
Labels: cryptosec

#13825 Add new parameter managed_key_id for PKI CA key generation.
  builtin/logical/pki/fields.go
  builtin/logical/pki/util.go
Labels: pr/no-changelog

#13814 Documentation updates for new keys for PKCS#11 unsealing
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, backport/website, backport/1.9.x, backport/1.8.x

#13819 auth/oidc: Documentation updates for Azure AD applications
  website/content/docs/auth/jwt/index.mdx
  website/content/docs/auth/jwt/oidc_providers.mdx
Labels: pr/no-changelog, backport/website

#12341 Update upgrade-to-1.3.10.mdx
  website/content/docs/upgrading/upgrade-to-1.3.10.mdx
Labels: docs-cherrypick

#13796 website: Add Demandbase tag to consent manager
  website/lib/consent-manager-services/index.ts
Labels: website, pr/no-changelog, backport/website

#13627 add security-scan for CRT
  .gitignore
  .release/ci.hcl
  .release/security-scan.hcl
  Dockerfile
Labels: pr/no-changelog

#13836 Bump timeout for gauge testing to 500 ms from 100 ms.
  helper/metricsutil/gauge_process_test.go
Labels: pr/no-changelog

#13527 Update mssql.mdx with typo error
  website/content/docs/secrets/databases/mssql.mdx
Labels: docs, pr/no-changelog, backport/website

#13736 Support Y10K value in notAfter field when signing non-CA certificates
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  changelog/13736.txt
Labels: enhancement, auth/cert, cryptosec

#13853 Docs/auth kubernetes 1.9.3
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog

#13852 Update k8s auth long-lived token instructions
  website/content/docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, backport/website

#13803 Add make fmt CI check
  .circleci/config.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/fmt.yml
  .circleci/config/workflows/ci.yml
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/managed_key_util.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/util.go
  plugins/database/mssql/mssql.go
  sdk/helper/certutil/types.go
Labels: pr/no-changelog
