Repository hashicorp/vault, pull requests merged in 2022-05, with the labels that each got.

#15214 MFA Push Methods Login Update
  ui/app/components/mfa-form.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/services/auth.js
  ui/app/templates/components/mfa-form.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/mirage/handlers/mfa-login.js
  ui/tests/acceptance/mfa-login-test.js
  ui/tests/integration/components/mfa-form-test.js
Labels: ui

#15256 Address PKI to properly support managed keys
  builtin/logical/pki/backend.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/key_util.go
  builtin/logical/pki/managed_key_util.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_test.go
  sdk/helper/certutil/helpers.go
Labels: secret/pki, rotation

#15169 CSV Export include monthly data
  ui/app/components/clients/attribution.js
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/models/clients/monthly.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/lib/core/addon/utils/client-count-utils.js
  ui/lib/core/addon/utils/date-formatters.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/components/clients/horizontal-bar-chart-test.js
Labels: ui, pr/no-changelog

#15041 When running under systemd, send ready when server completed reloading config #7028
  changelog/15041.txt
  command/server.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15244 MFA Login Enforcement Model
  ui/app/adapters/mfa-login-enforcement.js
  ui/app/models/mfa-login-enforcement.js
  ui/app/serializers/mfa-login-enforcement.js
  ui/tests/unit/serializers/mfa-login-enforcement-test.js
Labels: ui, pr/no-changelog

#15274 clone vault agent client with headers
  command/agent.go
Labels: pr/no-changelog

#15268 Add build_date to CLI and API docs
  website/content/api-docs/system/seal-status.mdx
  website/content/api-docs/system/version-history.mdx
  website/content/docs/commands/status.mdx
  website/content/docs/commands/version-history.mdx
  website/content/docs/commands/version.mdx
Labels: pr/no-changelog

#15255 Add issuer usage restrictions
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations.go
Labels: secret/pki, pr/no-changelog, rotation

#15270 [RelAPI Onboarding] Add release metadata config key
  .release/ci.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#14969 updating legacy MFA doc with link to Login MFA
  website/content/docs/auth/mfa.mdx
Labels: pr/no-changelog

#15288 GOPATH is being set incorrectly in latest CircleCI machine image
  .circleci/config.yml
  .circleci/config/commands/@caches.yml
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15287 Vault documentation: added another install option to the installation doc
  website/content/docs/install.mdx
Labels: pr/no-changelog, backport/1.10.x

#15286 base sys/license/status mock times based on current timestamp
  ui/app/templates/components/license-banners.hbs
  ui/lib/core/addon/components/alert-banner.js
  ui/lib/core/addon/templates/components/alert-banner.hbs
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
Labels: pr/no-changelog

#12763 Skip metric increment during existence check
  changelog/12763.txt
  vault/router.go
Labels: waiting-for-response, core/metric

#15297 update go-plugin to v1.4.4
  go.mod
  go.sum
Labels: pr/no-changelog

#15278 removing prem/pro references as part of removing some build targets
  sdk/plugin/grpc_system_test.go
  vault/diagnose/constants.go
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
Labels: pr/no-changelog

#15294 Add ForgeRock to OIDC Providers
  website/content/docs/auth/jwt/oidc_providers.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15326 fix linting
  ui/mirage/handlers/clients.js
Labels: pr/no-changelog

#15329 Vault documentation: added disable parameter to seal stanza-related doc pages
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/alicloudkms.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/azurekeyvault.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/seal/ocikms.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/configuration/seal/transit.mdx
Labels: pr/no-changelog, backport/1.10.x

#15320 unit test: fix oidc periodicfunc flaky test
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog

#15279 UI/filter monthly graphs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/history.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/monthly-usage.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/utils/client-count-utils.js
  ui/mirage/handlers/clients.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui, pr/no-changelog

#15338 Vaut documentation: Updated documents referencing performance replication
  website/content/api-docs/system/replication/replication-performance.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
Labels: pr/no-changelog, backport/1.10.x

#15340 Link to the Learn guide for PKI with Managed Keys
  website/content/docs/secrets/pki.mdx
Labels: website, backport/1.10.x

#15351 Propagate context within UnwrapWithContext func
  api/logical.go
Labels: pr/no-changelog

#15354 docs: update dep table to include okta auth changes
  website/content/docs/deprecation/index.mdx
Labels: docs, pr/no-changelog

#15350 UI/single historical month
  ui/app/components/clients/history.js
  ui/app/components/clients/running-total.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/mirage/handlers/clients.js
Labels: ui, pr/no-changelog

#15364 UI/ fix firefox not recognizing csv export
  changelog/15364.txt
  ui/app/services/download-csv.js
Labels: ui, bug, backport/1.10.x

#15359 UI/Remove legend beneath line chart
  ui/app/templates/components/clients/running-total.hbs
Labels: ui, pr/no-changelog

#15271 Add Transit BYOK wrapping key endpoint
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_wrapping_key.go
  builtin/logical/transit/path_wrapping_key_test.go
Labels: secret/transit, pr/no-changelog

#15285 Compare issuer certificates using cert, signature algo and signature fields
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/test_helpers.go
Labels: pr/no-changelog, rotation

#15319 Add parameter validation to the new generate key PKI api
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_manage_keys_test.go
Labels: secret/pki, pr/no-changelog, rotation

#15306 Root issuers lack CA Chain + Chain Building Bug Fix
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/chain_util.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
Labels: secret/pki, pr/no-changelog, rotation

#15322 Use Get lookup within PKI resolveXXX functions instead of list iterations
  builtin/logical/pki/backend.go
  builtin/logical/pki/storage.go
Labels: secret/pki, pr/no-changelog, rotation

#15336 Return names for leaf_not_after_behavior responses
  builtin/logical/pki/path_fetch_issuers.go
  sdk/helper/certutil/types.go
Labels: secret/pki, pr/no-changelog, rotation

#15325 Rework locking within the PKI crlBuilder
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
Labels: secret/pki, pr/no-changelog, rotation

#15362 UI: Fix version-history serializer and update mirage to reflect real API
  ui/app/components/clients/current.js
  ui/app/serializers/clients/version-history.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
Labels: ui, pr/no-changelog, backport/1.10.x

#15315 Benchmark chain building
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/test_helpers.go
Labels: secret/pki, pr/no-changelog, rotation

#15339 docs: fix typo in example custom db plugin
  website/content/docs/secrets/databases/custom.mdx
Labels: pr/no-changelog

#15360 Fix revoking certificates in pre-migration state within PKI
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_migrations_test.go
Labels: secret/pki, pr/no-changelog, rotation

#15371 Add revocation check to chain building
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/crl_util.go
Labels: secret/pki, pr/no-changelog, rotation

#15375 Backport 1.10.x: UI/Fix version-history serializer and update mirage to reflect real API #15362
  ui/app/serializers/clients/version-history.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
Labels: ui, bug

#15385 Remove 1.11-only mount flag syntax
  website/content/docs/secrets/kv/kv-v2.mdx
Labels: pr/no-changelog

#15384 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog

#15361 auth/okta: Add support for Okta number challenge
  builtin/credential/okta/backend.go
  builtin/credential/okta/cli.go
  builtin/credential/okta/path_login.go
  changelog/15361.txt
  website/content/api-docs/auth/okta.mdx
Labels: ecosystem, auth/okta

#15250 not_before_duration added to SSH
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_config_ca_test.go
  builtin/logical/ssh/path_roles.go
  builtin/logical/ssh/path_sign.go
  changelog/15250.txt
  ui/app/models/role-ssh.js
  website/content/api-docs/secret/ssh.mdx
Labels: secret/ssh, cryptosec

#15386 Fix changelog formatting for feature
  changelog/14899.txt
Labels: pr/no-changelog

#15396 UI/remove flaky client count tests
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
Labels: ui, pr/no-changelog

#15380 VAULT-5935 agent: redact renew-self if using auto auth
  changelog/15380.txt
  command/agent/cache/cache_test.go
  command/agent/cache/handler.go
  command/agent/cache/lease_cache.go
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15379 docs: update for vault-k8s 0.16.0
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: pr/no-changelog, backport/1.10.x

#15391 Fix typo in login docs
  website/content/docs/commands/login.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15369 Disabling client side rate limiting in Okta login MFA client
  changelog/15369.txt
  vault/login_mfa.go
Labels: bug, backport/1.10.x

#15401 Fix unknown type parameter during CA generation
  ui/app/adapters/pki-ca-certificate.js
Labels: ui, secret/pki, pr/no-changelog

#15407 UI/remove chart check
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
Labels: ui, pr/no-changelog

#15365 Backport of UI/ fix firefox not recognizing csv export into release/1.10.x
  changelog/15364.txt
  ui/app/services/download-csv.js
Labels: ui, bug

#15404 Update SDK to 1.10.4
  sdk/version/version_base.go
Labels: pr/no-changelog

#15411 Add tests for usage-based restrictions of issuers
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/test_helpers.go
Labels: secret/pki, pr/no-changelog, rotation

#14383 Updated Docs For Specific Call Out
  website/content/api-docs/secret/ssh.mdx
Labels: docs, secret/ssh, pr/no-changelog

#15272 UBI Containerfile - CRT Enablement
  .github/workflows/build.yml
  .release/docker/ubi-docker-entrypoint.sh
  Dockerfile
Labels: release/build, docker, pr/no-changelog

#15413 Restructure PKI Documentation Section
  website/content/docs/secrets/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
  website/content/docs/secrets/pki/quick-start-root-ca.mdx
  website/content/docs/secrets/pki/setup.mdx
  website/data/docs-nav-data.json
Labels: docs, secret/pki, pr/no-changelog

#15412 Import SDK for 1.10.4 version
  go.mod
Labels: pr/no-changelog

#15378 Fix OIDC callback query params
  changelog/15378.txt
  ui/app/routes/vault/cluster/oidc-callback.js
Labels: ui

#15358 docs: updated monitor doc
  website/content/api-docs/system/monitor.mdx
Labels: pr/no-changelog, backport/1.10.x

#15424 Plural typo in the Tokenization API docs for stores
  website/content/api-docs/secret/transform.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15410 MFA Login Enforcement Form
  ui/app/adapters/mfa-login-enforcement.js
  ui/app/components/mfa-login-enforcement-form.js
  ui/app/components/mfa-login-enforcement-header.js
  ui/app/components/mount-accessor-select.js
  ui/app/models/mfa-login-enforcement.js
  ui/app/models/mfa-method.js
  ui/app/styles/components/radio-card.scss
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/mfa-login-enforcement-form.hbs
  ui/app/templates/components/mfa-login-enforcement-header.hbs
  ui/app/templates/components/mount-accessor-select.hbs
  ui/app/templates/components/radio-card.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/tests/integration/components/mfa-login-enforcement-form-test.js
Labels: ui, pr/no-changelog

#15422 MFA Login Enforcement Create and Edit routes
  ui/app/components/mfa-login-enforcement-form.js
  ui/app/router.js
  ui/app/routes/vault/cluster/access/mfa/configure.js
  ui/app/routes/vault/cluster/access/mfa/enforcements/create.js
  ui/app/routes/vault/cluster/access/mfa/enforcements/enforcement.js
  ui/app/routes/vault/cluster/access/mfa/enforcements/enforcement/edit.js
  ui/app/routes/vault/cluster/access/mfa/enforcements/index.js
  ui/app/routes/vault/cluster/access/mfa/index.js
  ui/app/routes/vault/cluster/access/mfa/methods/create.js
  ui/app/routes/vault/cluster/access/mfa/methods/index.js
  ui/app/routes/vault/cluster/access/mfa/methods/method.js
  ui/app/serializers/mfa-login-enforcement.js
  ui/app/templates/components/mfa-login-enforcement-form.hbs
  ui/app/templates/vault/cluster/access.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/create.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/edit.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
  ui/app/templates/vault/cluster/access/mfa/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
  ui/lib/core/addon/components/search-select.js
  ui/mirage/factories/mfa-login-enforcement.js
  ui/mirage/handlers/mfa-config.js
Labels: ui, pr/no-changelog

#15435 Include default information in LIST keys, issuers
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_fetch_keys.go
Labels: secret/pki, pr/no-changelog, rotation

#15439 Set HOME=/home/vault in UBI Dockerfile
  Dockerfile
Labels: release/build, pr/no-changelog

#15441 Use backendUUID instead of mount points for managed keys (OSS)
  builtin/logical/pki/backend.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/key_util.go
  builtin/logical/pki/managed_key_util.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_test.go
  sdk/logical/managed_key.go
Labels: pr/no-changelog

#15414 Transit byok import endpoints
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_import.go
  builtin/logical/transit/path_import_test.go
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_wrapping_key.go
  changelog/15414.txt
  go.mod
  go.sum
  sdk/helper/keysutil/lock_manager.go
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_test.go
Labels: cryptosec

#15443 Fix ubi-docker-entrypoint.sh->docker-entrypoint.sh
  Dockerfile
Labels: release/build, pr/no-changelog

#15442 Update considerations for multiple issuers
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog, rotation

#15437 Fix integer overflows with new parseutil
  api/secret.go
  builtin/logical/ssh/util.go
  command/base_flags.go
  command/server/config.go
  go.mod
  go.sum
Labels: bug, core/api, secret/ssh, command, pr/no-changelog

#15447 Fix a keysutil policy lock
  builtin/logical/transit/path_import.go
  sdk/helper/keysutil/lock_manager.go
Labels: pr/no-changelog, cryptosec

#15357 Add note about concurrency to plugin dev docs
  website/content/docs/plugins/plugin-development.mdx
Labels: pr/no-changelog

#15449 Store migrated issuer, key ID in migration log
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_migrations_test.go
Labels: secret/pki, pr/no-changelog, rotation

#15055 Remove duplicate policies when creating/updating identity groups
  changelog/15055.txt
  vault/identity_store_groups_test.go
  vault/identity_store_util.go
Labels: bug, core/identity, backport/1.10.x

#15446 Vault documentation: updated unseal information
  website/content/docs/commands/operator/init.mdx
  website/content/docs/internals/architecture.mdx
  website/public/img/unseal.png
Labels: pr/no-changelog, backport/1.10.x

#15456 auth/oidc: documents user claim constraint for optional google workspace config
  website/content/docs/auth/jwt/oidc_providers.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15454 auth/oidc: adds documentation for JSON pointer user claim
  website/content/api-docs/auth/jwt.mdx
  website/content/docs/auth/jwt/index.mdx
Labels: docs, pr/no-changelog

#15451 Log less around the current status of the PKI migration
  builtin/logical/pki/backend.go
  builtin/logical/pki/storage_migrations.go
Labels: secret/pki, pr/no-changelog, rotation

#15470 Always return PKI configs for CRLs, URLs
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_config_urls.go
  changelog/15470.txt
Labels: secret/pki

#15445 docs: add note about upndomain for AD secret engine
  website/content/api-docs/secret/ad.mdx
Labels: pr/no-changelog, backport/1.10.x

#15466 Add documentation on rotation primitives
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
  website/content/docs/secrets/pki/quick-start-root-ca.mdx
  website/content/docs/secrets/pki/rotation-primitives.mdx
  website/content/docs/secrets/pki/setup.mdx
  website/data/docs-nav-data.json
Labels: docs, secret/pki, pr/no-changelog

#15376 secrets/database: adds ability to manage alternative credential types and configuration
  builtin/logical/database/credentials.go
  builtin/logical/database/credentials_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_creds_create.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/path_rotate_credentials.go
  builtin/logical/database/rollback.go
  builtin/logical/database/rotation.go
  builtin/logical/database/version_wrapper.go
  builtin/logical/database/version_wrapper_test.go
  changelog/15376.txt
  go.mod
  sdk/database/dbplugin/v5/conversions_test.go
  sdk/database/dbplugin/v5/database.go
  sdk/database/dbplugin/v5/grpc_client.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/database/dbplugin/v5/proto/database.proto
Labels: ecosystem, secret/database

#15462 MFA Login Enforcement Read Views
  ui/app/adapters/mfa-login-enforcement.js
  ui/app/components/mfa-login-enforcement-form.js
  ui/app/controllers/vault/cluster/access/mfa/enforcements/enforcement/index.js
  ui/app/controllers/vault/cluster/access/mfa/enforcements/index.js
  ui/app/models/mfa-login-enforcement.js
  ui/app/routes/vault/cluster/access/mfa/enforcements/enforcement.js
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/mfa-login-enforcement-form.hbs
  ui/app/templates/components/mfa-method-list-item.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
  ui/lib/core/addon/components/linked-block.hbs
  ui/lib/core/addon/components/linked-block.js
  ui/tests/integration/components/mfa-method-list-item-test.js
Labels: ui, pr/no-changelog

#15432 MFA method form
  ui/app/adapters/mfa-method.js
  ui/app/components/mfa/method-form.js
  ui/app/models/mfa-method.js
  ui/app/router.js
  ui/app/routes/vault/cluster/access/mfa/methods/method/edit.js
  ui/app/templates/components/mfa/method-form.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/edit.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
Labels: ui

#15273 Sidebranch: MFA end user setup
  ui/app/adapters/mfa-setup.js
  ui/app/components/auth-info.js
  ui/app/components/mfa-setup-step-one.js
  ui/app/components/mfa-setup-step-two.js
  ui/app/components/splash-page.js
  ui/app/controllers/vault/cluster/mfa-setup.js
  ui/app/router.js
  ui/app/routes/vault/cluster/mfa-setup.js
  ui/app/styles/components/list-item-row.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/auth-info.hbs
  ui/app/templates/components/mfa-setup-step-one.hbs
  ui/app/templates/components/mfa-setup-step-two.hbs
  ui/app/templates/components/splash-page.hbs
  ui/app/templates/vault/cluster/mfa-setup.hbs
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog

#15475 Start documentation for FIPS variants of Vault Enterprise
  website/content/api-docs/secret/pki.mdx
  website/content/api-docs/secret/ssh.mdx
  website/content/api-docs/secret/transit.mdx
  website/content/api-docs/system/tools.mdx
  website/content/docs/enterprise/fips/fips1402.mdx
  website/content/docs/enterprise/fips/index.mdx
  website/content/docs/enterprise/fips/sealwrap.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/secrets/transit.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#15469 possibly forward cached MFA auth response to leader
  changelog/15469.txt
  vault/request_handling.go
  vault/request_handling_util.go
Labels: backport/1.10.x

#15363 Username format login mfa
  vault/external_tests/identity/login_mfa_duo_test.go
  vault/external_tests/identity/login_mfa_okta_test.go
  vault/identity_store.go
  vault/login_mfa.go
  website/content/api-docs/secret/identity/mfa/duo.mdx
  website/content/api-docs/secret/identity/mfa/okta.mdx
  website/content/api-docs/secret/identity/mfa/pingid.mdx
  website/content/docs/auth/login-mfa/faq.mdx
Labels: pr/no-changelog

#15479 MFA Guided Setup Route
  ui/app/controllers/vault/cluster/access/mfa/methods/create.js
  ui/app/styles/core/helpers.scss
  ui/app/templates/components/radio-card.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
Labels: ui, pr/no-changelog

#15480 docs: add note about requiring 3.6+ helm
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/external.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/index.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
  website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
Labels: pr/no-changelog, backport/1.10.x

#15474 UI: Better default transit auto-rotation
  changelog/15474.txt
  ui/app/templates/components/transit-form-create.hbs
  ui/app/templates/components/transit-form-edit.hbs
  ui/lib/core/addon/components/ttl-picker2.js
  ui/tests/acceptance/transit-test.js
  ui/tests/integration/components/ttl-picker2-test.js
Labels: ui

#15450 Update documentation for vault-helm v0.20.0 release
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, backport/1.10.x

#15495 Fix a generic PKI description for key_name and issuer_name fields
  builtin/logical/pki/fields.go
Labels: secret/pki, pr/no-changelog, rotation

#15417 Vault CLI: show detailed information with ListResponseWithInfo
  changelog/15417.txt
  command/base.go
  command/commands.go
  command/format.go
  command/list.go
  command/main.go
  command/operator_unseal_test.go
  command/version_history_test.go
Labels: core/cli

#15485 Enforcement view at MFA method level
  ui/app/adapters/mfa-method.js
  ui/app/controllers/vault/cluster/access/mfa/methods/method/index.js
  ui/app/routes/vault/cluster/access/mfa/methods/method.js
  ui/app/templates/components/mfa/login-enforcement-list-item.hbs
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/edit.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
Labels: ui

#15497 UI/1.11 Changelog for client counts improvements
  changelog/client-counts-1.11.txt
Labels: ui, pr/no-changelog

#15464 UI/vault 6212/multiple issuer pki changes
  changelog/15464.txt
  ui/app/adapters/pki-ca-certificate.js
  ui/app/components/config-pki-ca.js
  ui/app/components/config-pki.js
  ui/app/models/pki-ca-certificate.js
  ui/app/styles/components/popup-menu.scss
  ui/app/templates/components/config-pki-ca.hbs
  ui/tests/integration/components/config-pki-ca-test.js
Labels: ui, pr/no-changelog

#15473 Vault 6122 pki role issuer name validation
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/storage.go
Labels: secret/pki, pr/no-changelog, cryptosec, rotation

#15498 MFA Login Enforcement Validations
  ui/app/components/mfa-login-enforcement-form.js
  ui/app/controllers/vault/cluster/access/mfa/methods/create.js
  ui/app/models/mfa-login-enforcement.js
  ui/app/routes/vault/cluster/access/mfa/methods/create.js
  ui/app/templates/components/mfa-login-enforcement-form.hbs
  ui/app/templates/components/radio-card.hbs
  ui/app/templates/vault/cluster/access/mfa/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
Labels: ui, pr/no-changelog

#15504 Fix minor typos and change terminology slightly in database secrets engines docs
  builtin/logical/cassandra/test-fixtures/cassandra.yaml
  website/content/api-docs/secret/databases/hanadb.mdx
  website/content/api-docs/secret/databases/index.mdx
  website/content/api-docs/secret/databases/mssql.mdx
  website/content/api-docs/secret/databases/mysql-maria.mdx
  website/content/api-docs/secret/databases/oracle.mdx
  website/content/api-docs/secret/databases/postgresql.mdx
  website/content/api-docs/secret/databases/redshift.mdx
  website/content/api-docs/secret/databases/snowflake.mdx
  website/content/docs/secrets/databases/index.mdx
Labels: pr/no-changelog

#15408 UI/cleanup client charts for 1.11
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/lib/core/addon/utils/client-count-utils.js
Labels: ui, pr/no-changelog

#15502 Update FIPS documentation to clarify mlock
  website/content/docs/enterprise/fips/fips1402.mdx
Labels: pr/no-changelog, cryptosec

#15509 Add warning on missing AIA info fields
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_root.go
  changelog/15509.txt
Labels: secret/pki

#15467 Add more CA usage best practices
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog

#15506 Added validations for mfa method model
  ui/app/components/mfa/method-form.js
  ui/app/controllers/vault/cluster/access/mfa/methods/create.js
  ui/app/models/mfa-method.js
  ui/app/templates/components/mfa/method-form.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
Labels: ui

#15511 Rebase #14178 / Add not_before_duration API parameter to Root/Intermediate CA generation
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_root.go
  changelog/14178.txt
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki, pr/no-changelog, cryptosec

#15344 Remove spurious fmt.Printf, including one of a key
  api/auth/azure/azure.go
  builtin/credential/aws/pkcs7/decrypt.go
  builtin/credential/aws/pkcs7/verify_test_dsa.go
  builtin/logical/rabbitmq/path_role_create.go
  command/server/config_test_helpers.go
  helper/dhutil/dhutil.go
  tools/semgrep/ci/fmt-printf.yml
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x

#15499 UI/mfa breadcrumbs and small fixes
  ui/app/routes/vault/cluster/access/mfa/index.js
  ui/app/templates/components/mfa-login-enforcement-header.hbs
  ui/app/templates/vault/cluster/access.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/index.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
  ui/app/templates/vault/cluster/access/mfa/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
Labels: ui, pr/no-changelog

#15522 UI/mfa small bugs
  ui/app/routes/vault/cluster/access/mfa/enforcements/index.js
  ui/app/routes/vault/cluster/access/mfa/methods/index.js
  ui/app/templates/vault/cluster/access/mfa/enforcements/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/index.hbs
Labels: ui, pr/no-changelog

#15528 Set OutputCurlString and OutputPolicy on client whether single or double hyphen in flag
  command/main.go
Labels: pr/no-changelog

#15514 Vault documentation: updated all references from Learn to Tutorial
  website/content/docs/concepts/integrated-storage/autopilot.mdx
  website/content/docs/concepts/password-policies.mdx
  website/content/docs/concepts/policies.mdx
  website/content/docs/concepts/resource-quotas.mdx
  website/content/docs/concepts/username-templating.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/storage/index.mdx
  website/content/docs/configuration/storage/raft.mdx
  website/content/docs/enterprise/lease-count-quotas.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/platform/aws/lambda-extension.mdx
  website/content/docs/platform/k8s/injector/index.mdx
  website/content/docs/secrets/consul.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/mongodb.mdx
  website/content/docs/secrets/kmip.mdx
  website/content/docs/secrets/nomad.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/terraform.mdx
  website/content/docs/secrets/transform/tokenization.mdx
Labels: pr/no-changelog, backport/1.10.x

#15530 Fix typo in documentation
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs

#15520 typo: embeds -> embedded
  website/content/docs/auth/login-mfa/index.mdx
Labels: docs

#14503 typo: adding missing word 'may'
  website/content/docs/platform/k8s/helm/run.mdx
Labels: docs

#15463 Update seal.mdx
  website/content/docs/concepts/seal.mdx
Labels: docs

#15524 Return the signed ca in the ca_chain response field within sign-intermediate api call.
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_root.go
  changelog/15524.txt
Labels: secret/pki, rotation

#15523 UI: keymgmt secret engine
  changelog/15523.txt
  ui/app/adapters/keymgmt/key.js
  ui/app/components/keymgmt/distribute.js
  ui/app/components/keymgmt/key-edit.js
  ui/app/components/keymgmt/provider-edit.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/keymgmt/provider.js
  ui/app/templates/components/input-search.hbs
  ui/app/templates/components/keymgmt/distribute.hbs
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/lib/core/addon/components/confirm-action.js
  ui/lib/core/addon/templates/components/confirm-action.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
  ui/tests/integration/components/keymgmt/distribute-test.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
  ui/tests/integration/components/keymgmt/provider-edit-test.js
Labels: ui

#15535 Clarify KU/EKU parameters on sign-verbatim
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog

#15537 Fix typo in allowed_uri_sans_template doctype
  website/content/api-docs/secret/pki.mdx
Labels: docs, pr/no-changelog

#15513 Remove reference to stored license
  changelog/15513.txt
  ui/app/serializers/license.js
  ui/app/templates/components/license-info.hbs
  ui/mirage/handlers/base.js
  ui/tests/integration/components/license-info-test.js
Labels: ui

#15542 Fix label for value on radio-card
  ui/app/templates/components/radio-card.hbs
Labels: ui, pr/no-changelog

#15541 PKI: Do not error out on unknown issuers/keys on delete api calls.
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_fetch_keys.go
  builtin/logical/pki/path_manage_keys_test.go
Labels: secret/pki, pr/no-changelog, rotation

#15510 Vault 5917 allow patch operations to pki roles issuers
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_roles.go
  changelog/15510.txt
Labels: secret/pki, rotation

#15540 Remove default values from mfa method model
  ui/app/models/mfa-method.js
Labels: ui

#15257 Update oracle.mdx
  website/content/docs/secrets/databases/oracle.mdx
Labels: docs, pr/no-changelog

#15526 Vault documentation: updated key share/unseal images
  website/content/docs/concepts/seal.mdx
  website/content/docs/internals/architecture.mdx
  website/content/docs/internals/rotation.mdx
  website/public/img/vault-auto-unseal.png
  website/public/img/vault-key-rotate.png
  website/public/img/vault-shamir-seal.png
Labels: pr/no-changelog, backport/1.10.x

#15549 UI/mfa small cleanup
  ui/app/adapters/mfa-login-enforcement.js
  ui/app/components/auth-info.js
  ui/app/serializers/mfa-login-enforcement.js
  ui/app/styles/components/radio-card.scss
  ui/app/templates/components/radio-card.hbs
Labels: ui, pr/no-changelog

#15547 MFA Login Enforcements Auth Method Target Bug
  ui/app/components/mfa-login-enforcement-form.js
  ui/tests/integration/components/mfa-login-enforcement-form-test.js
Labels: ui, pr/no-changelog

#15548 remove token type
  ui/app/components/mount-accessor-select.js
  ui/app/templates/components/mfa-login-enforcement-form.hbs
  ui/app/templates/components/mount-accessor-select.hbs
Labels: ui

#15545 Add role patching test case
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_roles_test.go
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki, pr/no-changelog, rotation

#15167 Handle client count timezone
  changelog/15167.txt
  ui/app/adapters/clients/activity.js
Labels: ui

#15521 Add autopilot automated upgrades and redundancy zones
  api/client.go
  api/sys_hastatus.go
  api/sys_raft.go
  command/format.go
  command/operator_members.go
  command/operator_raft_autopilot_get_config.go
  command/operator_raft_autopilot_set_config.go
  physical/raft/fsm.go
  physical/raft/raft.go
  physical/raft/raft_autopilot.go
  physical/raft/raft_test.go
  physical/raft/raft_util.go
  vault/core.go
  vault/external_tests/raft/raft_autopilot_test.go
  vault/external_tests/raft/raft_test.go
  vault/logical_system.go
  vault/logical_system_raft.go
  vault/raft.go
  vault/request_forwarding.go
  vault/request_forwarding_rpc.go
  vault/request_forwarding_service.pb.go
  vault/request_forwarding_service.proto
  vault/testing.go
Labels: pr/no-changelog

#15525 Fix handling of username_as_alias during LDAP authentication
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_login.go
  changelog/15525.txt
  sdk/helper/ldaputil/client.go
Labels: ecosystem, auth/ldap, backport/1.9.x, backport/1.10.x

#15555 Backport FIPS 140-2 Documentation
  website/content/api-docs/secret/pki.mdx
  website/content/api-docs/secret/ssh.mdx
  website/content/api-docs/secret/transit.mdx
  website/content/api-docs/system/tools.mdx
  website/content/docs/enterprise/fips/fips1402.mdx
  website/content/docs/enterprise/fips/index.mdx
  website/content/docs/enterprise/fips/sealwrap.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/secrets/transit.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#15554 Link FIPS binary sources from the FIPS docs
  website/content/docs/enterprise/fips/fips1402.mdx
Labels: docs, pr/no-changelog

#15558 Update autopilot update interval
  vault/external_tests/raft/raft_autopilot_test.go
Labels: pr/no-changelog

#15559 Convert not_before_duration to seconds before returning it
  builtin/logical/ssh/path_roles.go
  changelog/15559.txt
Labels: bug, secret/ssh

#15314 FAQ doc updates for removal of stored licenses in 1.11
  website/content/docs/enterprise/license/faq.mdx
Labels: pr/no-changelog

#15500 Add various missing PKI related changelog entries
  CHANGELOG.md
  changelog/14975.txt
  changelog/15004.txt
  changelog/15100.txt
  changelog/15152.txt
  changelog/15155.txt
  changelog/15179.txt
  changelog/15211.txt
  changelog/15277.txt
Labels: pr/no-changelog

#15562 Add more PKI usage best practices to documentation
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog

#15543 Allow issuer/:issuer_ref/sign-verbatim/:role, add error on missing role
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_issue_sign.go
  changelog/15543.txt
Labels: bug, secret/pki, rotation

#15566 auth/okta: documents API token minimal permissions
  website/content/docs/auth/okta.mdx
  website/content/docs/auth/token.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15563 Vault documentation: reorganized docs by moving recovery key description
  website/content/docs/commands/operator/init.mdx
  website/content/docs/concepts/seal.mdx
  website/content/docs/enterprise/hsm/behavior.mdx
Labels: pr/no-changelog, backport/1.10.x

#15536 api/monitor: Adding log format to monitor command and debug
  api/sys_monitor.go
  changelog/15536.txt
  command/debug.go
  command/monitor.go
  helper/monitor/monitor_test.go
  http/sys_monitor_test.go
  vault/logical_system.go
  vault/logical_system_paths.go
  website/content/api-docs/system/monitor.mdx
  website/content/docs/commands/debug.mdx
  website/content/docs/commands/monitor.mdx
Labels: backport/1.10.x

#15377 Added support for VAULT_PROXY_ADDR + Updated docs
  api/client.go
  api/client_test.go
  changelog/15377.txt
  website/content/docs/commands/index.mdx
Labels: pr/no-changelog, backport/1.10.x

#15565 Glimmerize and add component test for MountAccessorSelect
  ui/app/components/mount-accessor-select.js
  ui/app/templates/components/mount-accessor-select.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/tests/integration/components/mount-accessor-select-test.js
Labels: ui, pr/no-changelog

#15573 Remove unsupported fields for DB roles show page
  changelog/15573.txt
  ui/app/models/database/role.js
Labels: ui

#15590 autopilot_upgrade_version should be parseable
  physical/raft/raft.go
  physical/raft/raft_test.go
Labels: pr/no-changelog
