Repository hashicorp/vault, pull requests merged in 2022-12, with the labels that each got.

#18146 ui: delete pki key functionality
  ui/app/adapters/pki/key.js
  ui/app/models/pki/key.js
  ui/app/services/flash-messages.ts
  ui/app/utils/error-message.js
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/page/pki-key-details.ts
  ui/lib/pki/addon/components/page/pki-role-details.hbs
  ui/lib/pki/addon/components/page/pki-role-details.ts
  ui/lib/pki/addon/components/pki-key-details.ts
  ui/lib/pki/addon/templates/keys/key/details.hbs
  ui/lib/pki/addon/templates/roles/role/details.hbs
  ui/tests/helpers/pki/keys/page-details.js
  ui/tests/helpers/pki/roles/form.js
  ui/tests/helpers/pki/roles/page-details.js
  ui/tests/integration/components/pki/keys/page-details-test.js
  ui/tests/integration/components/pki/pki-key-parameters-test.js
  ui/tests/integration/components/pki/pki-key-usage-test.js
  ui/tests/integration/components/pki/roles/form-test.js
  ui/tests/integration/components/pki/roles/page-details-test.js
  ui/tests/unit/adapters/pki/key-test.js
  ui/types/ember-cli-flash/services/flash-messages.d.ts
Labels: ui, pr/no-changelog

#18173 Fix plugin list API when audit logging enabled
  changelog/18173.txt
  vault/external_plugin_test.go
  vault/logical_system.go
  vault/logical_system_test.go
  vault/testing.go
Labels: bug, core/plugin, ecosystem/plugin, backport/1.12.x

#18184 Address a nil panic when writing an empty POST request to the ocsp handler
  builtin/logical/pki/ocsp.go
  changelog/18184.txt
Labels: bug, secret/pki, backport/1.12.x

#18114 UI: TTL picker cleanup
  changelog/18114.txt
  ui/app/components/configure-aws-secret.js
  ui/app/components/wrap-ttl.hbs
  ui/app/components/wrap-ttl.js
  ui/app/styles/app.scss
  ui/app/styles/components/ttl-picker.scss
  ui/app/styles/core.scss
  ui/app/templates/components/configure-aws-secret.hbs
  ui/app/templates/components/form-field-from-model.hbs
  ui/app/templates/components/pki/config-pki.hbs
  ui/app/templates/components/tool-wrap.hbs
  ui/app/templates/components/transit-form-create.hbs
  ui/app/templates/components/transit-form-edit.hbs
  ui/app/templates/vault/cluster/access/leases/show.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/radio-select-ttl-or-string.hbs
  ui/lib/core/addon/components/toggle.hbs
  ui/lib/core/addon/components/ttl-form.js
  ui/lib/core/addon/components/ttl-picker.hbs
  ui/lib/core/addon/components/ttl-picker.js
  ui/lib/core/addon/components/ttl-picker2.js
  ui/lib/core/addon/templates/components/ttl-form.hbs
  ui/lib/core/addon/templates/components/ttl-picker.hbs
  ui/lib/core/addon/templates/components/ttl-picker2.hbs
  ui/lib/core/app/components/ttl-form.js
  ui/lib/core/app/components/ttl-picker2.js
  ui/lib/replication/addon/templates/mode/secondaries/add.hbs
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/helpers/components/ttl-picker.js
  ui/tests/integration/components/mfa/method-form-test.js
  ui/tests/integration/components/pki/config-pki-test.js
  ui/tests/integration/components/pki/radio-select-ttl-or-string-test.js
  ui/tests/integration/components/ttl-form-test.js
  ui/tests/integration/components/ttl-picker-test.js
  ui/tests/integration/components/ttl-picker2-test.js
  ui/tests/integration/components/wrap-ttl-test.js
Labels: ui

#18190 Do not use possibly nil HttpRequest object in default OCSP error handler
  builtin/logical/pki/ocsp.go
Labels: pr/no-changelog, backport/1.12.x

#18180 Use shared github runners from ent repo
  .github/workflows/security-scan.yml
Labels: pr/no-changelog

#18163 Skip Formatting For NIL Secret
  changelog/18163.txt
  command/kv_patch.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x

#18143 Fix vault cli namespace patch examples
  changelog/18143.txt
  command/namespace_patch.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x

#18125 Log environment variable keys at startup
  changelog/18125.txt
  command/server.go
  command/server_test.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x

#18194 UI: PKI Roles Edit
  ui/app/models/pki/role.js
  ui/app/styles/app.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/engines.scss
  ui/app/styles/pki/pki-not-valid-after-form.scss
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/info-table-row.js
  ui/lib/core/addon/components/radio-select-ttl-or-string.hbs
  ui/lib/core/addon/components/radio-select-ttl-or-string.js
  ui/lib/core/addon/components/ttl-picker.js
  ui/lib/core/addon/decorators/confirm-leave.js
  ui/lib/core/addon/utils/duration-utils.ts
  ui/lib/core/app/components/radio-select-ttl-or-string.js
  ui/lib/core/app/decorators/confirm-leave.js
  ui/lib/pki/addon/components/page/pki-role-details.hbs
  ui/lib/pki/addon/components/pki-not-valid-after-form.hbs
  ui/lib/pki/addon/components/pki-not-valid-after-form.ts
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/components/pki-role-form.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/role/edit.js
  ui/lib/pki/addon/templates/roles/role/edit.hbs
  ui/tests/helpers/pki/pki-not-valid-after-form.js
  ui/tests/helpers/pki/roles/page-details.js
  ui/tests/integration/components/info-table-row-test.js
  ui/tests/integration/components/pki/pki-not-valid-after-form-test.js
  ui/tests/integration/components/pki/radio-select-ttl-or-string-test.js
  ui/tests/integration/components/pki/roles/page-pki-role-details-test.js
Labels: ui, pr/no-changelog

#18218 Add Nutanix to the interoperability matrix
  website/content/docs/interoperability-matrix.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#18189 plugins: Mount missing plugin entries and skip loading
  changelog/18189.txt
  vault/auth.go
  vault/core.go
  vault/external_plugin_test.go
  vault/mount.go
Labels: backport/1.12.x

#18174 [QT-318] Add workflow dispatch trigger for bootstrap workflow, update ssh key name
  .github/workflows/enos-ci-bootstrap.yml
  enos/README.md
  enos/ci/bootstrap/main.tf
  enos/ci/bootstrap/variables.tf
Labels: pr/no-changelog

#18220 Remove semi colon from mysql
  website/content/docs/secrets/databases/mssql.mdx
Labels: docs, website, pr/no-changelog

#18199 Allow templating cluster-local AIA URIs
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_config_cluster.go
  builtin/logical/pki/path_config_urls.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations_test.go
  changelog/18199.txt
  website/content/api-docs/secret/pki.mdx
Labels: enhancement, secret/pki

#18222 Respond with data to all writes in PKI engine
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/integration_test.go
  builtin/logical/pki/ocsp_test.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_resign_crls_test.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/storage_migrations_test.go
  changelog/18222.txt
  command/patch_test.go
Labels: secret/pki

#18195 Backport docs for retry_join_as_non_voter config option
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/configuration/storage/raft.mdx
Labels: docs, core/config, website, pr/no-changelog, backport/1.12.x

#18211 Kubernetes Roles List
  ui/app/adapters/kubernetes/role.js
  ui/app/models/kubernetes/role.js
  ui/lib/core/addon/components/navigate-input.js
  ui/lib/core/addon/templates/components/empty-state.hbs
  ui/lib/kubernetes/addon/components/page/roles.hbs
  ui/lib/kubernetes/addon/components/page/roles.js
  ui/lib/kubernetes/addon/components/tab-page-header.hbs
  ui/lib/kubernetes/addon/controllers/roles/index.js
  ui/lib/kubernetes/addon/routes/roles/index.js
  ui/lib/kubernetes/addon/templates/roles/index.hbs
  ui/tests/integration/components/kubernetes/page/roles-test.js
  ui/tests/integration/components/kubernetes/tab-page-header-test.js
Labels: ui

#18231 Add ManagedMACKey interface to SDK.
  sdk/logical/managed_key.go
Labels: sdk, pr/no-changelog, cryptosec

#18232 VAULT-9863 Kubernetes Overview Page
  ui/app/styles/core/helpers.scss
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/kubernetes/addon/components/page/overview.js
  ui/lib/kubernetes/addon/routes/overview.js
  ui/lib/kubernetes/addon/templates/overview.hbs
  ui/tests/integration/components/kubernetes/page/overview-test.js
Labels: ui

#18229 UI: PKI Role toolbar
  ui/app/adapters/pki/role.js
  ui/app/models/pki/role.js
  ui/app/templates/components/pki/role-pki-edit.hbs
  ui/lib/core/addon/components/secret-list-header-tab.hbs
  ui/lib/pki/addon/components/page/pki-role-details.hbs
  ui/lib/pki/addon/components/page/pki-role-details.ts
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/routes/roles/role/details.js
  ui/lib/pki/addon/routes/roles/role/edit.js
  ui/lib/pki/addon/templates/roles/create.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
  ui/lib/pki/addon/templates/roles/role/details.hbs
  ui/lib/pki/addon/templates/roles/role/edit.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/roles/page-details.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki/keys/page-details-test.js
  ui/tests/integration/components/pki/pki-key-parameters-test.js
  ui/tests/integration/components/pki/roles/page-pki-role-details-test.js
Labels: ui, pr/no-changelog

#18249 Ensure base logging uses IndependentLevels
  helper/logging/logger.go
  helper/logging/logger_test.go
Labels: pr/no-changelog

#18262 Only attempt rotation if files already exist when a Write is requested.
  helper/logging/logfile.go
Labels: pr/no-changelog

#18265 Docs: improve bound_audiences documentation for jwt role
  website/content/api-docs/auth/jwt.mdx
Labels: docs, pr/no-changelog

#18267 Address race in PKI test case
  builtin/logical/pki/backend_test.go
Labels: pr/no-changelog

#18266 Refactor PKI to use shared storage context
  builtin/logical/pki/backend.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/ocsp.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/secret_certs.go
Labels: secret/pki, pr/no-changelog

#17926 Add mount path into the default generated openapi.json spec (UI)
  api/plugin_helpers.go
  sdk/framework/backend.go
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
  sdk/framework/path.go
  sdk/framework/testdata/legacy.json
  sdk/framework/testdata/operations.json
  sdk/framework/testdata/operations_list.json
  sdk/framework/testdata/responses.json
  ui/app/services/path-help.js
  vault/logical_system.go
  vault/logical_system_test.go
Labels: pr/no-changelog

#18274 Update namespace LIST response example to be more accurate
  website/content/api-docs/system/namespaces.mdx
Labels: website, pr/no-changelog, backport/1.12.x

#18269 Add ManagedKeyRandomSource interface to SDK.
  sdk/logical/managed_key.go
Labels: sdk, pr/no-changelog, cryptosec

#18276 Fix Link dependencies
  go.mod
Labels: pr/no-changelog

#18272 Add transit key config to disable upserting
  builtin/logical/transit/backend.go
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_config_keys.go
  builtin/logical/transit/path_config_keys_test.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_keys_config.go
  builtin/logical/transit/path_keys_config_test.go
  changelog/18272.txt
  website/content/api-docs/secret/transit.mdx
Labels: enhancement, secret/transit

#18268 ui: generate pki key
  ui/app/adapters/pki/key.js
  ui/app/models/pki/key.js
  ui/app/models/pki/role.js
  ui/app/serializers/pki/key.js
  ui/app/styles/core/forms.scss
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/page/pki-key-details.ts
  ui/lib/pki/addon/components/pki-key-form.hbs
  ui/lib/pki/addon/components/pki-key-form.js
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/lib/pki/addon/components/pki-key-parameters.js
  ui/lib/pki/addon/routes/keys/create.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/keys/key/details.js
  ui/lib/pki/addon/routes/keys/key/edit.js
  ui/lib/pki/addon/templates/keys/create.hbs
  ui/lib/pki/addon/templates/keys/key/details.hbs
  ui/lib/pki/addon/templates/keys/key/edit.hbs
  ui/tests/helpers/pki/keys/form.js
  ui/tests/integration/components/pki/keys/form-test.js
  ui/tests/integration/components/pki/keys/page-details-test.js
  ui/tests/integration/components/pki/pki-key-parameters-test.js
Labels: ui, pr/no-changelog

#18280 Remove mention of public Vault trial license form
  website/content/docs/enterprise/license/faq.mdx
Labels: docs, website, pr/no-changelog

#18286 Fix broken link
  website/content/docs/release-notes/1.10.0.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18285 copy over link_control and meta to link proto module
  Makefile
  vault/hcp_link/proto/go.mod
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/link_control/link_control.proto
  vault/hcp_link/proto/link_control/link_control_grpc.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/meta/meta.proto
  vault/hcp_link/proto/meta/meta_grpc.pb.go
Labels: pr/no-changelog

#18290 use meta and link_control from link proto
  go.mod
  go.sum
  vault/hcp_link/capabilities/link_control/link_control.go
  vault/hcp_link/capabilities/link_control/link_control.pb.go
  vault/hcp_link/capabilities/link_control/link_control.proto
  vault/hcp_link/capabilities/link_control/link_control_grpc.pb.go
  vault/hcp_link/capabilities/meta/meta.go
  vault/hcp_link/capabilities/meta/meta.pb.go
  vault/hcp_link/capabilities/meta/meta.proto
  vault/hcp_link/capabilities/meta/meta_grpc.pb.go
Labels: pr/no-changelog

#18271 Kubernetes Secrets Engine Create/Edit Views
  ui/app/adapters/kubernetes/role.js
  ui/app/models/kubernetes/role.js
  ui/lib/core/addon/components/json-editor.hbs
  ui/lib/core/addon/components/json-editor.js
  ui/lib/core/addon/components/kv-object-editor.hbs
  ui/lib/core/addon/components/kv-object-editor.js
  ui/lib/core/addon/modifiers/code-mirror.js
  ui/lib/core/app/components/json-editor.js
  ui/lib/core/app/components/kv-object-editor.js
  ui/lib/core/app/modifiers/code-mirror.js
  ui/lib/core/package.json
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
  ui/lib/kubernetes/addon/routes/roles/create.js
  ui/lib/kubernetes/addon/routes/roles/role/edit.js
  ui/lib/kubernetes/addon/templates/roles/create.hbs
  ui/lib/kubernetes/addon/templates/roles/role/edit.hbs
  ui/lib/kubernetes/addon/utils/generated-role-rules.js
  ui/lib/kubernetes/package.json
  ui/mirage/factories/kubernetes-role.js
  ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
  ui/tests/unit/adapters/kubernetes/role-test.js
Labels: ui

#18296 remove deleted link proto paths
  Makefile
Labels: pr/no-changelog

#18227 Server: add and support unix listener (UDS)
  changelog/18227.txt
  command/server/listener.go
  command/server/listener_test.go
  command/server/listener_unix.go
  command/server/listener_unix_test.go
  website/content/docs/configuration/listener/index.mdx
  website/content/docs/configuration/listener/unix.mdx
  website/data/docs-nav-data.json
Labels: enhancement

#18303 Kubernetes Secrets Engine Overview Bug
  ui/lib/kubernetes/addon/routes/overview.js
Labels: ui

#18294 Kubernetes Role Details View
  ui/app/models/kubernetes/role.js
  ui/lib/core/addon/helpers/format-duration.js
  ui/lib/core/app/helpers/format-duration.js
  ui/lib/kubernetes/addon/components/page/role/details.hbs
  ui/lib/kubernetes/addon/components/page/role/details.js
  ui/lib/kubernetes/addon/routes/roles/role/details.js
  ui/lib/kubernetes/addon/templates/roles/role/details.hbs
  ui/mirage/factories/kubernetes-role.js
  ui/mirage/scenarios/default.js
  ui/tests/integration/components/kubernetes/page/role/details-test.js
Labels: ui

#18292 ui: glimmerize download button component
  ui/app/templates/components/toolbar-download-button.hbs
  ui/app/templates/vault/cluster/init.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/lib/core/addon/components/download-button.hbs
  ui/lib/core/addon/components/download-button.js
  ui/lib/core/addon/components/toolbar-download-button.js
  ui/lib/core/app/components/toolbar-download-button.js
  ui/lib/kmip/addon/templates/configuration.hbs
  ui/tests/integration/components/toolbar-download-button-test.js
Labels: ui, pr/no-changelog

#18308 Document adding metadata to entity alias within cert auth
  builtin/credential/cert/path_certs.go
  website/content/api-docs/auth/cert.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18056 [QT-436] Psuedorandom artifact test scenarios
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/build-github-oss-linux-amd64-zip.json
  .github/enos-run-matrices/build-github-oss-linux-arm64-zip.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  .github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-amd64-zip.json
  .github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-arm64-zip.json
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run.yml
  .github/workflows/enos-verify-stable.yml
  .release/ci.hcl
  CODEOWNERS
  Makefile
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_local/scripts/build.sh
  enos/modules/get_local_metadata/scripts/build_date.sh
  enos/modules/get_local_metadata/scripts/version.sh
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
  scripts/build.sh
  scripts/ci-helper.sh
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18313 Secrets List Engine Link
  ui/app/routes/vault/cluster/secrets/backend/list.js
Labels: ui

#18322 test: use the correct actions runner
  .github/workflows/build-vault-oss.yml
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog

#18244 Use a small pool of workers to run postUnsealFuncs in parallel
  changelog/18244.txt
  vault/core.go
Labels: backport/1.11.x, backport/1.12.x

#18310 Return the partial success code override for all batch error types
  builtin/logical/transit/path_encrypt.go
  changelog/18310.txt
  website/content/api-docs/secret/transit.mdx
Labels: backport/1.11.x, backport/1.12.x

#18330 Fix role name in CI bootstrap workflow
  .github/workflows/enos-ci-bootstrap.yml
Labels: pr/no-changelog

#18300 UI: PKI generate cert from role
  ui/app/adapters/pki/certificate/generate.js
  ui/app/adapters/pki/role.js
  ui/app/app.js
  ui/app/components/clients/attribution.js
  ui/app/helpers/parse-pki-cert.js
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/certificate/generate.js
  ui/app/serializers/pki/certificate/generate.js
  ui/app/services/download-csv.js
  ui/app/services/download.ts
  ui/app/services/secret-mount-path.js
  ui/lib/core/addon/components/form-field-groups-loop.hbs
  ui/lib/core/addon/components/form-field-groups-loop.js
  ui/lib/pki/addon/components/pki-role-generate.hbs
  ui/lib/pki/addon/components/pki-role-generate.ts
  ui/lib/pki/addon/controllers/roles/role/generate.js
  ui/lib/pki/addon/engine.js
  ui/lib/pki/addon/routes/error.js
  ui/lib/pki/addon/routes/roles/role/generate.js
  ui/lib/pki/addon/templates/error.hbs
  ui/lib/pki/addon/templates/roles/role/generate.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/pki-role-generate.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/helpers/stubs.js
  ui/tests/integration/components/pki-role-generate-test.js
  ui/tests/unit/adapters/pki/certificate/generate-test.js
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/adapters/pki/role.d.ts
Labels: ui, pr/no-changelog

#18333 Manual Testing: Bug Fixes and Improvements
  ui/lib/kubernetes/addon/components/config-cta.hbs
  ui/lib/kubernetes/addon/components/page/configuration.hbs
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/kubernetes/addon/components/page/overview.js
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
  ui/lib/kubernetes/addon/components/page/roles.hbs
  ui/lib/kubernetes/addon/components/page/roles.js
  ui/lib/kubernetes/addon/routes/index.js
  ui/lib/kubernetes/addon/routes/roles/index.js
  ui/lib/kubernetes/addon/templates/configuration.hbs
  ui/lib/kubernetes/addon/templates/overview.hbs
  ui/lib/kubernetes/addon/templates/roles/index.hbs
  ui/mirage/factories/kubernetes-role.js
  ui/tests/integration/components/kubernetes/page/configuration-test.js
  ui/tests/integration/components/kubernetes/page/overview-test.js
  ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
  ui/tests/integration/components/kubernetes/page/role/details-test.js
  ui/tests/integration/components/kubernetes/page/roles-test.js
Labels: ui

#18336 test: add build artifacts to release testing workflow
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18341 Backport of test: add build artifacts to release testing workflow into release/1.12.x
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog

#18340 Backport of test: add build artifacts to release testing workflow into release/1.11.x
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog

#18339 Backport of test: add build artifacts to release testing workflow into release/1.10.x
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog

#18270 VAULT-9877 Kubernetes Credential Generate/View Pages
  ui/app/adapters/kubernetes/role.js
  ui/lib/kubernetes/addon/components/page/credentials.hbs
  ui/lib/kubernetes/addon/components/page/credentials.js
  ui/lib/kubernetes/addon/routes/roles/role/credentials.js
  ui/lib/kubernetes/addon/templates/roles/role/credentials.hbs
  ui/mirage/handlers/kubernetes.js
  ui/tests/integration/components/kubernetes/page/credentials-test.js
Labels: ui

#18344 docs: add note on aws snapstart incompatibility
  website/content/docs/platform/aws/lambda-extension.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18348 command/audit: Recommend multiple audit devices
  command/audit.go
  website/content/docs/audit/index.mdx
Labels: core/audit, pr/no-changelog, backport/1.12.x

#18358 core: Make shutdownDoneCh atomic
  vault/core.go
Labels: pr/no-changelog, backport/1.12.x

#18360 Kubernetes Roles Acceptance Tests
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/lib/kubernetes/addon/components/page/credentials.hbs
  ui/lib/kubernetes/addon/components/page/roles.hbs
  ui/mirage/handlers/kubernetes.js
  ui/mirage/scenarios/default.js
  ui/mirage/scenarios/kubernetes.js
  ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
Labels: ui

#18366 docs/policies: update denied_parameters description
  website/content/docs/concepts/policies.mdx
Labels: website, backport/1.12.x

#18367 UI: Update database to connection name on role (#18350)
  changelog/18350.txt
  ui/app/models/database/role.js
Labels: ui, backport

#18368 UI: Update database to connection name on role (#18350)
  changelog/18350.txt
  ui/app/models/database/role.js
Labels: ui, backport

#18369 UI: Update database to connection name on role (#18350)
  changelog/18350.txt
  ui/app/models/database/role.js
Labels: ui, backport

#18349 UI: PKI stub configure page
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-configure-form.ts
  ui/lib/pki/addon/routes.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/templates/configuration.hbs
  ui/lib/pki/addon/templates/configuration/create.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/tests/integration/components/pki-configure-form-test.js
Labels: ui, pr/no-changelog

#17879 plugins: Handle mount/enable for shadowed builtins
  changelog/17879.txt
  command/auth_enable_test.go
  command/path_map_upgrade_api_test.go
  command/secrets_enable_test.go
  command/server.go
  sdk/helper/consts/deprecation_status.go
  vault/auth.go
  vault/core.go
  vault/external_plugin_test.go
  vault/logical_system.go
  vault/mount.go
  vault/testing.go
  vault/version_store.go
Labels: backport/1.12.x

#18016 Add a workaround to allow SHA-1 signatures in certs to work for Vault <= 1.11
  internal/go118_sha1_patch.go
  main.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#18347 Correctly handle issuer tidying in auto-tidy config
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  website/content/api-docs/secret/pki.mdx
Labels: bug, secret/pki, pr/no-changelog

#18382 Fix ci-config for go-version bumps
  .circleci/Makefile
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18374 UI: update host to new doc link location (developer.hashicorp.com/)
  changelog/18374.txt
  ui/lib/core/addon/components/doc-link.js
  ui/lib/core/addon/components/learn-link.js
  ui/tests/integration/components/form-field-label-test.js
Labels: ui

#18386 Fix race in fsm.db
  physical/raft/fsm.go
  physical/raft/raft.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18371 Revert "Create test-reusable.yml"
  .github/workflows/test-reusable.yml
Labels: pr/no-changelog

#18306 [Doc] Fix minor inconsistencies with vault Helm chart
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18405 Fix SHA1 patch for Go 1.19.4; patch test
  builtin/credential/aws/pkcs7/sign.go
  internal/go118_sha1_patch.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18338 Capture cryptosec responsibilities in CODEOWNERS
  CODEOWNERS
Labels: pr/no-changelog

#18411 test: pass build artifact name to release testing workflow
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18418 OSS PR for Config Changes PR
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  command/server/test-fixtures/config.hcl
  http/sys_config_state_test.go
  vault/core.go
  vault/external_tests/api/sudo_paths_test.go
  vault/inspectable_test.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/testing.go
Labels: pr/no-changelog

#18417 ui: fix flaky oid auth test
  ui/tests/acceptance/oidc-auth-method-test.js
Labels: ui, pr/no-changelog

#17972 Added default endpoint info. Added note about backwards compabitibility
  website/content/api-docs/system/inspect/index.mdx
  website/content/api-docs/system/inspect/router.mdx
  website/content/docs/configuration/index.mdx
Labels: docs, pr/no-changelog

#18381 UI: download generated pki key
  ui/app/app.js
  ui/app/services/download.ts
  ui/app/templates/vault/cluster/init.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/lib/core/addon/components/download-button.js
  ui/lib/kmip/addon/engine.js
  ui/lib/kmip/addon/templates/configuration.hbs
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/engine.js
  ui/lib/pki/addon/routes/keys/create.js
Labels: ui, pr/no-changelog

#18425 test: normalize job and steps between build and release test workflows
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18432 Remove browserstack dep and tests
  .circleci/config.yml
  .circleci/config/jobs/test-ui-browserstack.yml
  .circleci/config/workflows/ci.yml
  Makefile
  ui/README.md
  ui/package.json
  ui/scripts/start-vault.js
  ui/testem.browserstack.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/yarn.lock
Labels: pr/no-changelog

#18430 UI/remove browserstack 1.10
  .circleci/config.yml
  .circleci/config/jobs/test-ui-browserstack.yml
  .circleci/config/workflows/ci.yml
  Makefile
  ui/README.md
  ui/package.json
  ui/scripts/start-vault.js
  ui/testem.browserstack.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/yarn.lock
Labels: pr/no-changelog

#18422 Use a cleaner worker pattern
  vault/core.go
Labels: pr/no-changelog, backport/1.12.x

#18444 Update the notes about Consul Connect CA issue
  website/content/docs/release-notes/1.11.0.mdx
  website/content/docs/secrets/pki/index.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#18443 UI/fix policy template doclinks
  ui/app/components/modal-form/policy-template.hbs
  ui/app/components/policy-form.hbs
Labels: ui, pr/no-changelog

#18445 Fix the checkout sha for enos-run workflow
  .github/workflows/enos-run.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18335 UI: glimmerize mount backend form
  ui/app/components/mount-backend-form.js
  ui/app/components/mount-backend/type-form.hbs
  ui/app/components/mount-backend/type-form.js
  ui/app/components/wizard/mounts-wizard.js
  ui/app/controllers/vault/cluster/settings/mount-secret-backend.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/secret-engine.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/settings/auth/enable.js
  ui/app/routes/vault/cluster/settings/mount-secret-backend.js
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/vault/cluster/settings/auth/enable.hbs
  ui/app/templates/vault/cluster/settings/mount-secret-backend.hbs
  ui/lib/core/addon/decorators/confirm-leave.js
  ui/lib/core/addon/helpers/options-for-backend.js
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/noop-all-api-requests.js
  ui/tests/helpers/stubs.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
  ui/tests/integration/components/pki-role-generate-test.js
  ui/tests/unit/models/secret-engine-test.js
Labels: ui, pr/no-changelog

#17675 Adding an Enos test for undo logs
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_verify_undo_logs/main.tf
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
Labels: pr/no-changelog, backport/1.12.x

#18412 ui: add capabilities to pki key model
  ui/app/models/pki/key.js
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/page/pki-key-list.hbs
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/keys/key/details.hbs
  ui/tests/helpers/pki/page/pki-key-details.js
  ui/tests/helpers/pki/page/pki-key-list.js
  ui/tests/helpers/pki/page/pki-role-details.js
  ui/tests/helpers/pki/pki-key-form.js
  ui/tests/helpers/pki/pki-role-form.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki/page/pki-key-details-test.js
  ui/tests/integration/components/pki/page/pki-key-list-test.js
  ui/tests/integration/components/pki/page/pki-role-details-test.js
  ui/tests/integration/components/pki/pki-key-form-test.js
  ui/tests/integration/components/pki/pki-key-list-test.js
  ui/tests/integration/components/pki/pki-key-parameters-test.js
  ui/tests/integration/components/pki/pki-key-usage-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog

#18457 UI: Fix mount backend type-form enterprise test
  ui/tests/integration/components/mount-backend/type-form-test.js
Labels: ui, pr/no-changelog

#18459 Fix typo
  website/content/docs/secrets/pki/index.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x

#18406 Add GitHub action to check for a milestone
  .github/configs/milestone-check.json
  .github/workflows/milestone-checker.yml
Labels: pr/no-changelog, pr/no-milestone

#18413 docs: highlight paragraph about default path in kv secrets engines docs.
  website/content/api-docs/secret/kv/kv-v1.mdx
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18469 Fix autopilot scenario race condition
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_verify_autopilot/main.tf
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18482 Add issuer reference info on JSON endpoint
  builtin/logical/pki/ca_test.go
  builtin/logical/pki/path_fetch_issuers.go
  changelog/18482.txt
Labels: enhancement, secret/pki

#18483 update golang/x/net
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18458 ui: refactor text file component
  ui/app/components/file-to-array-buffer.js
  ui/app/components/pgp-file.js
  ui/app/components/policy-form.hbs
  ui/app/components/policy-form.js
  ui/app/components/text-file.js
  ui/app/templates/components/file-to-array-buffer.hbs
  ui/app/templates/components/pgp-file.hbs
  ui/app/templates/components/text-file.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/text-file.hbs
  ui/lib/core/addon/components/text-file.js
  ui/lib/core/addon/templates/components/icon.hbs
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/lib/core/addon/templates/components/shamir-flow.hbs
  ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
  ui/lib/core/app/components/text-file.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/integration/components/policy-form-test.js
  ui/tests/integration/components/text-file-test.js
  ui/tests/pages/components/masked-input.js
Labels: ui, pr/no-changelog

#18486 Backport of update golang/x/net into release/1.11.x
  go.mod
  go.sum
  helper/hostutil/hostinfo.go
  helper/hostutil/hostinfo_util.go
  physical/raft/bolt_linux.go
  vault/diagnose/os_common.go
Labels: pr/no-changelog

#18487 Backport of update golang/x/net into release/1.12.x
  go.mod
  go.sum
Labels: pr/no-changelog

#18485 Backport of update golang/x/net into release/1.10.x
  go.mod
  go.sum
  helper/hostutil/hostinfo.go
  helper/hostutil/hostinfo_util.go
  physical/raft/bolt_linux.go
  vault/diagnose/os_common.go
Labels: pr/no-changelog

#18497 Fix Artifactory search for fips and hsm editions
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18489 VAULT-12127 Refactor breadcrumbs to use breadcrumb component
  ui/lib/kubernetes/addon/components/page/configuration.hbs
  ui/lib/kubernetes/addon/components/page/credentials.hbs
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/kubernetes/addon/components/page/role/details.hbs
  ui/lib/kubernetes/addon/components/page/roles.hbs
  ui/lib/kubernetes/addon/components/tab-page-header.hbs
  ui/lib/kubernetes/addon/routes/configuration.js
  ui/lib/kubernetes/addon/routes/overview.js
  ui/lib/kubernetes/addon/routes/roles/index.js
  ui/lib/kubernetes/addon/routes/roles/role/credentials.js
  ui/lib/kubernetes/addon/routes/roles/role/details.js
  ui/lib/kubernetes/addon/templates/configuration.hbs
  ui/lib/kubernetes/addon/templates/overview.hbs
  ui/lib/kubernetes/addon/templates/roles/index.hbs
  ui/lib/kubernetes/addon/templates/roles/role/credentials.hbs
  ui/lib/kubernetes/addon/templates/roles/role/details.hbs
  ui/tests/acceptance/secrets/backend/kubernetes/credentials-test.js
  ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
  ui/tests/integration/components/kubernetes/page/configuration-test.js
  ui/tests/integration/components/kubernetes/page/credentials-test.js
  ui/tests/integration/components/kubernetes/page/overview-test.js
  ui/tests/integration/components/kubernetes/page/role/details-test.js
  ui/tests/integration/components/kubernetes/page/roles-test.js
  ui/tests/integration/components/kubernetes/tab-page-header-test.js
Labels: ui

#18490 ui: add ability to edit pki key
  ui/app/adapters/pki/key.js
  ui/lib/pki/addon/components/pki-key-form.hbs
  ui/lib/pki/addon/components/pki-key-form.js
  ui/lib/pki/addon/templates/keys/key/edit.hbs
Labels: ui, pr/no-changelog

#18454 ui: pki import key
  ui/app/adapters/pki/key.js
  ui/app/models/pki/key.js
  ui/lib/pki/addon/components/pki-key-form.js
  ui/lib/pki/addon/components/pki-key-import.hbs
  ui/lib/pki/addon/components/pki-key-import.js
  ui/lib/pki/addon/routes/keys/import.js
  ui/lib/pki/addon/templates/keys/import.hbs
Labels: ui, pr/no-changelog

#18512 Add PKI base command
  command/commands.go
  command/pki.go
Labels: enhancement, secret/pki, pr/no-changelog

#18495 UI: PKI Issuer details
  ui/app/adapters/pki/issuer.js
  ui/app/models/pki/issuer.js
  ui/app/serializers/pki/issuer.js
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/issuers/issuer/details.js
  ui/lib/pki/addon/routes/issuers/issuer/index.js
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/issuers/issuer/details.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
Labels: ui, pr/no-changelog

#18526 Turn off undo logs for enos auto-upgrade scenario pre-v1.13
  enos/enos-scenario-autopilot.hcl
Labels: pr/no-changelog, backport/1.12.x

#18527 Add LICENSE back to pkcs7
  .copywrite.hcl
  .gitignore
  builtin/credential/aws/pkcs7/LICENSE
Labels: pr/no-changelog

#18531 Persist metadata post release tests
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18536 Update XKS docs to use AWS CLI
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#18532 auth/oidc: fix permissions for Azure 200+ group workflow
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18540 Save release testing metadata only when tests are run
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18546 MongoDB - Fix write_concern param
  changelog/18546.txt
  plugins/database/mongodb/mongodb.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x
