Repository hashicorp/vault, pull requests merged in 2022-06, with the labels that each got.

#15721 Update terraform secrets to v0.5
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.11.x

#15714 UI/client history binary bug
  ui/lib/core/addon/utils/client-count-utils.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui, bug, pr/no-changelog, backport/1.11.x

#15587 Add Patch KV helper
  api/kv_v2.go
  vault/external_tests/api/kv_helpers_test.go
Labels: pr/no-changelog

#15731 fix off by one error in activity log nil padding for month data
  vault/activity_log.go
  vault/activity_log_test.go
Labels: pr/no-changelog, backport/1.11.x

#15734 Only use additional entropy source when configured within transit and sys random calls
  helper/random/random_api.go
Labels: pr/no-changelog, backport/1.11.x

#15715 Option to show radio button in form field
  ui/app/models/mfa-method.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/ttl-picker2.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/pages/components/form-field.js
Labels: ui, pr/no-changelog

#15569 Vault documentation: vault overview page proposal
  website/content/docs/what-is-vault.mdx
  website/package-lock.json
  website/public/img/how-vault-works.png
  website/public/img/vault-workflow-diagram.png
  website/public/img/vault-workflow-diagram1.png
  website/public/img/vault-workflow-diagram2.png
Labels: pr/no-changelog, backport/1.10.x

#15756 Fixed mfa method acceptance tests
  ui/app/models/mfa-method.js
  ui/lib/core/addon/components/form-field.hbs
  ui/tests/acceptance/mfa-method-test.js
  ui/tests/integration/components/form-field-test.js
Labels: ui, pr/no-changelog

#15757 More PKI docs updates
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.11.x

#15754 PKI: Only set issuers with an associated key as default on import
  builtin/logical/pki/integation_test.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/storage.go
Labels: secret/pki, pr/no-changelog, backport/1.11.x

#15762 Vault documentation: added relevant link to tutorial from audit device page
  website/content/docs/audit/index.mdx
Labels: pr/no-changelog, backport/1.10.x

#15761 Fix copy/paste typo in PKI key generation docs
  website/content/api-docs/secret/pki.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#15765 Vault documentation: update sample code for Azure API
  website/content/api-docs/secret/azure.mdx
Labels: pr/no-changelog, backport/1.10.x

#15770 Add details to CHANGELOG and 1.10 upgrade note regarding new 412 error response resulting from SSCTs.
  CHANGELOG.md
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#15769 Revert UI: replace localStorage with sessionStorage
  changelog/15769.txt
  ui/app/lib/local-storage.js
  ui/app/lib/token-storage.js
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/redirect-to-test.js
Labels: ui, bug, backport/1.10.x

#15744 Glimmerize components using outer-html
  ui/app/components/alert-popup.js
  ui/app/components/auth-jwt.js
  ui/app/components/block-error.js
  ui/app/components/logo-splash.js
  ui/app/components/wizard-section.js
  ui/app/templates/components/alert-popup.hbs
  ui/app/templates/components/wizard-section.hbs
Labels: ui, pr/no-changelog

#15781 Revert UI: replace localStorage with sessionStorage (#15769)
  changelog/15769.txt
  ui/app/lib/local-storage.js
  ui/app/lib/token-storage.js
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/redirect-to-test.js
Labels: ui, backport

#15759 File Audit Mode 0000 bug
  builtin/audit/file/backend.go
  builtin/audit/file/backend_test.go
  changelog/15759.txt
Labels: backport/1.9.x, backport/1.8.x, backport/1.10.x

#15768 iterate through all available logs for precomputation and query gets
  vault/activity_log.go
Labels: pr/no-changelog

#15767 refactor some code in modifyResponseMonths and ensure that the last mo…
  vault/activity_log.go
Labels: pr/no-changelog

#15637 KV helpers for DeleteMetadata, Undelete, Destroy, and Rollback
  api/kv_v2.go
  vault/external_tests/api/kv_helpers_test.go
Labels: pr/no-changelog

#15777 Integration tests for mfa method form
  ui/app/templates/components/mfa/method-form.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/tests/integration/components/mfa/method-form-test.js
Labels: ui, pr/no-changelog

#15785 Backport of iterate through all available logs for precomputation and query gets into release/1.11.x
  vault/activity_log.go
Labels: pr/no-changelog

#15751 Support for CPS URLs in Custom Policy Identifiers.
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_roles_test.go
  changelog/15751.txt
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
Labels: backport/1.11.x

#15704 add missing patch capability to policy docs
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog

#15789 UI: calendar widget fix
  changelog/15789.txt
  ui/app/components/calendar-widget.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/tests/integration/components/calendar-widget-test.js
Labels: ui, bug, backport/1.10.x, backport/1.11.x

#15748 UI/1.11 client count component tests
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/monthly-usage.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/horizontal-bar-chart.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/templates/components/stat-text.hbs
  ui/lib/core/addon/utils/date-formatters.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients/line-chart-test.js
  ui/tests/integration/components/clients/monthly-usage-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/components/clients/vertical-bar-chart-test.js
  ui/tests/unit/utils/chart-helpers-test.js
Labels: ui, pr/no-changelog, backport/1.11.x

#15801 secrets/db: fix structpb conversion for external plugins using alternative cred types
  sdk/database/dbplugin/v5/database.go
  sdk/database/dbplugin/v5/grpc_client.go
Labels: bug, pr/no-changelog, backport/1.11.x

#15786 Glimmer continued
  ui/app/components/database-role-setting-form.js
  ui/app/components/generated-item-list.js
  ui/app/components/home-link.js
  ui/app/components/hover-copy-button.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/components/home-link.hbs
  ui/app/templates/components/hover-copy-button.hbs
  ui/app/templates/vault/cluster/access/method/item/list.hbs
  ui/tests/integration/components/hover-copy-button-test.js
Labels: ui, pr/no-changelog

#13859 Add upgrade and config docs for MSSQL EKM Provider
  website/content/docs/platform/mssql/configuration.mdx
  website/content/docs/platform/mssql/index.mdx
  website/content/docs/platform/mssql/installation.mdx
  website/content/docs/platform/mssql/troubleshooting.mdx
  website/content/docs/platform/mssql/upgrading.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, backport/1.11.x

#15811 Ignore crt builds on docs branches
  .github/workflows/build.yml
Labels: pr/no-changelog

#15814 db/snowflake: updates plugin to v0.5.1
  go.mod
  go.sum
Labels: bug, pr/no-changelog, backport/1.11.x

#15813 Move Mfa components to MFA folder
  ui/app/components/mfa/mfa-form.js
  ui/app/components/mfa/mfa-login-enforcement-form.js
  ui/app/components/mfa/mfa-login-enforcement-header.js
  ui/app/components/mfa/mfa-setup-step-one.js
  ui/app/components/mfa/mfa-setup-step-two.js
  ui/app/templates/components/mfa/mfa-form.hbs
  ui/app/templates/components/mfa/mfa-login-enforcement-form.hbs
  ui/app/templates/components/mfa/mfa-login-enforcement-header.hbs
  ui/app/templates/components/mfa/mfa-setup-step-one.hbs
  ui/app/templates/components/mfa/mfa-setup-step-two.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/create.hbs
  ui/app/templates/vault/cluster/access/mfa/enforcements/enforcement/edit.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/app/templates/vault/cluster/mfa-setup.hbs
  ui/tests/integration/components/mfa-form-test.js
  ui/tests/integration/components/mfa-login-enforcement-form-test.js
  ui/tests/integration/components/mfa-login-enforcement-header-test.js
Labels: pr/no-changelog

#15818 Update Go to 1.17.11
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/executors/@executors.yml
  .github/workflows/build.yml
  Makefile
  README.md
  changelog/15818.txt
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: backport/1.9.x, backport/1.10.x, backport/1.11.x

#15736 Backport of UI/1.11 client acceptance tests into release/1.11.x
  ui/app/components/clients/line-chart.js
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/lib/core/addon/utils/date-formatters.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/acceptance/enterprise-license-banner-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/utils/date-formatters-test.js
Labels: ui

#15819 Document Convergent Tokenization and Token Lookup
  website/content/api-docs/secret/transform.mdx
  website/content/docs/secrets/transform/index.mdx
  website/content/docs/secrets/transform/tokenization.mdx
Labels: pr/no-changelog, backport/1.11.x

#15803 Backport: UI/1.11 client count component tests #15748
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/monthly-usage.js
  ui/app/components/clients/running-total.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/horizontal-bar-chart.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/monthly-usage.hbs
  ui/app/templates/components/clients/running-total.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/templates/components/stat-text.hbs
  ui/lib/core/addon/utils/date-formatters.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients/line-chart-test.js
  ui/tests/integration/components/clients/monthly-usage-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/components/clients/vertical-bar-chart-test.js
  ui/tests/unit/utils/chart-helpers-test.js
Labels: ui

#14069 Update documentation to reduce confusion about default_extensions.
  website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#15833 Fix listing_visibility value documentation
  vault/logical_system.go
  website/content/api-docs/system/auth.mdx
Labels: docs, core/auth, pr/no-changelog

#15711 add codeowners to protect release dirs
  CODEOWNERS
Labels: pr/no-changelog

#15742 Add parsing for NSS-wrapped Ed25519 keys
  builtin/logical/transit/path_import_test.go
  changelog/15742.txt
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/util.go
Labels: secret/transit, cryptosec

#15810 docs: Update CSI Provider command line arguments
  website/content/docs/platform/k8s/csi/configurations.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: docs, website, pr/no-changelog, backport/1.11.x

#15843 Add support notes, Entropy Augmentation notes, RH repo
  website/content/docs/configuration/entropy-augmentation.mdx
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/fips/fips1402.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x

#15824 UI: Fix metadata tab not showing given policy
  changelog/15824.txt
  ui/app/components/secret-edit.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui, bug, backport/1.9.x, backport/1.10.x, backport/1.11.x

#15805 chore: remove duplicate overview item
  website/data/api-docs-nav-data.json
Labels: website, pr/no-changelog

#15850 Vault documentation: updated deprecation table
  website/content/docs/deprecation/index.mdx
Labels: pr/no-changelog, backport/1.10.x

#15836 docs: add pkiCert example on agent template docs
  website/content/docs/agent/template.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#15852 Change tooltip for token_bound_certs and glimmerize string-list component
  changelog/15852.txt
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/string-list.hbs
  ui/lib/core/addon/components/string-list.js
  ui/lib/core/addon/templates/components/string-list.hbs
  ui/lib/core/package.json
  ui/tests/integration/components/string-list-test.js
Labels: ui

#15741 Update AWS auth docs for SHA-1 deprecation
  website/content/api-docs/auth/aws.mdx
  website/content/docs/auth/aws.mdx
  website/content/partials/aws-sha1-deprecation.mdx
Labels: pr/no-changelog, backport/1.11.x

#15849 Backport of UI: Fix metadata tab not showing given policy into release/1.11.x
  changelog/15824.txt
  ui/app/components/secret-edit.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui, backport, bug

#15589 Autopilot enterprise docs
  website/content/api-docs/system/ha-status.mdx
  website/content/api-docs/system/storage/raftautopilot.mdx
  website/content/docs/commands/operator/members.mdx
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/concepts/integrated-storage/autopilot.mdx
  website/content/docs/configuration/storage/raft.mdx
  website/content/docs/enterprise/automated-upgrades.mdx
  website/content/docs/enterprise/redundancy-zones.mdx
  website/data/docs-nav-data.json
  website/public/img/autopilot-automated-upgrade.png
Labels: pr/no-changelog, backport/1.11.x

#15728 Backport/1.11.x: UI/ add additional serializer check
  ui/lib/core/addon/utils/client-count-utils.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui

#15855 Update GCP auth docs for GCE identity token login
  website/content/docs/auth/gcp.mdx
Labels: pr/no-changelog, backport/1.11.x

#15858 Add warning about EA in FIPS mode
  changelog/15858.txt
  command/server.go
Labels: backport/1.10.x, backport/1.11.x, fips

#15755 Add PutMetadata and PatchMetadata KV helpers
  api/kv_v2.go
  vault/external_tests/api/kv_helpers_test.go
Labels: pr/no-changelog

#15876 Use manual_chain for cross-signed intermediates
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.11.x

#15868 Update KMIP documentation to reflect Vault 1.11 changes.
  website/content/docs/secrets/kmip.mdx
Labels: pr/no-changelog, backport/1.11.x

#15880 Make KV structs public so the KV helper methods show in godoc
  api/kv.go
  api/kv_v1.go
  api/kv_v2.go
Labels: pr/no-changelog

#15854 Update Consul secrets features docs, api-docs for 1.11
  website/content/api-docs/secret/consul.mdx
  website/content/docs/deprecation/index.mdx
  website/content/docs/secrets/consul.mdx
Labels: pr/no-changelog, backport/1.11.x

#15881 Backport of Update KMIP documentation to reflect Vault 1.11 changes. into release/1.11.x
  website/content/docs/secrets/kmip.mdx
Labels: docs

#15886 pki: Do not use a static issuer/key name within the migration
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_migrations_test.go
Labels: secret/pki, pr/no-changelog, rotation, backport/1.11.x

#15883 Add missing nil check to FIPS EA verification
  command/server.go
Labels: bug, pr/no-changelog, backport/1.10.x, backport/1.11.x, fips

#15888 Remove fingerprinting for images
  ui/ember-cli-build.js
Labels: ui, bug, pr/no-changelog, backport/1.11.x

#15894 add OSS noop check for valid ent storage
  command/server.go
  command/server_util.go
Labels: pr/no-changelog

#15866 pass context to postgres queries
  changelog/15866.txt
  physical/postgresql/postgresql.go
Labels: ecosystem

#15893 Backport of Remove fingerprinting for images into release/1.11.x
  ui/ember-cli-build.js
Labels: ui, bug

#15885 Kv cas parameter documentation
  website/content/api-docs/secret/kv/kv-v2.mdx
  website/content/docs/commands/kv/put.mdx
  website/content/docs/secrets/kv/kv-v2.mdx
Labels: pr/no-changelog

#15902 Use KV helpers in docs and dev quickstart guide
  website/content/docs/auth/approle.mdx
  website/content/docs/auth/aws.mdx
  website/content/docs/auth/azure.mdx
  website/content/docs/auth/gcp.mdx
  website/content/docs/auth/kubernetes.mdx
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog, backport/1.11.x

#15904 Removed IRC reference in architecture internals doc
  website/content/docs/internals/architecture.mdx
Labels: docs, pr/no-changelog

#15898 Remove deprecated core-js version from production builds
  changelog/15898.txt
  ui/.browserslistrc
  ui/.eslintrc.js
  ui/ember-cli-build.js
  ui/package.json
  ui/yarn.lock
Labels: ui

#15907 Update SDK to 1.8.13
  sdk/version/version_base.go
Labels: pr/no-changelog

#15909 UI: Fix tooltip hover for vertical bar chart
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/templates/components/clients/vertical-bar-chart.hbs
Labels: ui, pr/no-changelog, backport/1.11.x

#15910 Backport of UI: Fix tooltip hover for vertical bar chart into release/1.11.x
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/templates/components/clients/vertical-bar-chart.hbs
Labels: ui, pr/no-changelog

#15913 Update minimum required go version for sdk
  sdk/go.mod
Labels: pr/no-changelog, backport/1.11.x

#15915 Update minimum required go version for api
  api/go.mod
  api/go.sum
  go.mod
Labels: pr/no-changelog, backport/1.11.x

#15917 Use latest api version
  go.mod
Labels: pr/no-changelog, backport/1.11.x

#15901 docs/postgres: replaces lib/pq with pgx
  website/content/docs/configuration/storage/cockroachdb.mdx
  website/content/docs/configuration/storage/postgresql.mdx
  website/content/docs/secrets/databases/postgresql.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#15892 secrets/db: documents credential types and snowflake key pair auth
  website/content/api-docs/secret/databases/index.mdx
  website/content/api-docs/secret/databases/snowflake.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/snowflake.mdx
  website/content/partials/db-secrets-credential-types.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#14399 Fix debug bundle panic on Windows
  changelog/14399.txt
  command/debug.go
Labels: bug, waiting-for-response

#15911 Glimmerize mount-backend-form
  ui/app/components/mount-backend-form.js
  ui/app/templates/components/mount-backend-form.hbs
Labels: ui, pr/no-changelog

#15921 Quick Bug Fix: missing database icon on overview page
  ui/app/routes/vault/cluster/secrets/backend/overview.js
Labels: ui, bug, pr/no-changelog

#15561 SSH secrets engine - Enabled creation of key pairs (CA Mode)
  builtin/logical/ssh/backend.go
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_issue.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/ssh/path_sign.go
  changelog/15561.txt
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, secret/ssh

#15809 Allow reading Nomad CA/Client cert configuration
  builtin/logical/nomad/backend_test.go
  builtin/logical/nomad/path_config_access.go
  changelog/15809.txt
Labels: enhancement, secret/nomad, tls

#15926 Fix location of not_before_duration on ssh docs
  website/content/api-docs/secret/ssh.mdx
Labels: docs, secret/ssh, pr/no-changelog, backport/1.11.x

#15929 ssh: Do not convert errors into logical.ErrorResponse in issue path
  builtin/logical/ssh/path_issue.go
  builtin/logical/ssh/path_sign.go
Labels: secret/ssh, pr/no-changelog

#15906 VAULT-5095 Update docs to reflect that child namespaces do not inherit parent quotas
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/rate-limit-quotas.mdx
  website/content/docs/enterprise/lease-count-quotas.mdx
Labels: pr/no-changelog

#15882 docs for activity log noncontiguous billing period changes
  website/content/api-docs/system/internal-counters.mdx
Labels: pr/no-changelog

#15933 database plugin: Invalidate queue should cancel context first
  builtin/logical/database/backend.go
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x

#15943 docs/oidc: adds missing steps for Google Workspace configuration
  website/content/docs/auth/jwt/oidc_providers.mdx
Labels: docs, pr/no-changelog, backport/1.10.x

#15919 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog

#15920 VAULT-6091 Document Duration Format String
  website/content/api-docs/secret/ad.mdx
  website/content/api-docs/secret/azure.mdx
  website/content/api-docs/secret/consul.mdx
  website/content/api-docs/secret/gcp.mdx
  website/content/api-docs/secret/identity/oidc-provider.mdx
  website/content/api-docs/secret/identity/tokens.mdx
  website/content/api-docs/secret/kv/kv-v2.mdx
  website/content/api-docs/secret/nomad.mdx
  website/content/api-docs/secret/openldap.mdx
  website/content/api-docs/secret/pki.mdx
  website/content/api-docs/secret/ssh.mdx
  website/content/api-docs/secret/terraform.mdx
  website/content/api-docs/secret/transform.mdx
  website/content/api-docs/secret/transit.mdx
  website/content/docs/agent/autoauth/index.mdx
  website/content/docs/agent/template.mdx
  website/content/docs/commands/auth/enable.mdx
  website/content/docs/commands/kv/metadata.mdx
  website/content/docs/commands/secrets/tune.mdx
  website/content/docs/commands/token/create.mdx
  website/content/docs/concepts/duration-format.mdx
  website/content/docs/concepts/oidc-provider.mdx
  website/content/docs/concepts/policies.mdx
  website/content/docs/configuration/telemetry.mdx
  website/content/docs/secrets/ad.mdx
  website/content/docs/secrets/consul.mdx
  website/content/docs/secrets/identity/identity-token.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#15949 Update SDK to 1.10.5
  sdk/version/version_base.go
Labels: pr/no-changelog

#15952 Import SDK 1.9.8
  go.mod
Labels: pr/no-changelog

#15873 Add 1.10 upgrade note for SSCT on Consul.
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#15816 Update containerd/containerd indirect test dep
  go.mod
  go.sum
Labels: bug, pr/no-changelog

#15958 docs: update double use of "note" in client faq
  website/content/docs/concepts/client-count/faq.mdx
Labels: docs, pr/no-changelog

#15685 updates `leasId` to `leaseId`
  changelog/15685.txt
  ui/app/models/aws-credential.js
Labels: ui, bug, backport/1.9.x, backport/1.10.x, backport/1.11.x

#15962 go get sdk v0.5.2
  go.mod
Labels: pr/no-changelog

#15969 TestLifetimeWatcher: Address bad assumption in test assertions
  api/renewer_test.go
Labels: pr/no-changelog, backport/1.11.x

#15963 Move PKI components to PKI Folder
  ui/app/adapters/pki/pki-certificate.js
  ui/app/adapters/pki/pki-role.js
  ui/app/components/generate-credentials.js
  ui/app/components/pki/config-pki-ca.js
  ui/app/components/pki/config-pki.js
  ui/app/components/pki/pki-cert-popup.js
  ui/app/components/pki/pki-cert-show.js
  ui/app/components/pki/role-pki-edit.js
  ui/app/helpers/options-for-backend.js
  ui/app/models/pki-ca-certificate.js
  ui/app/models/pki-certificate-sign.js
  ui/app/models/pki/pki-certificate.js
  ui/app/models/pki/pki-role.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/pki/pki-certificate.js
  ui/app/serializers/pki/pki-role.js
  ui/app/templates/components/pki/config-pki-ca.hbs
  ui/app/templates/components/pki/config-pki.hbs
  ui/app/templates/components/pki/configure-pki-secret.hbs
  ui/app/templates/components/pki/pki-cert-popup.hbs
  ui/app/templates/components/pki/pki-cert-show.hbs
  ui/app/templates/components/pki/role-pki-edit.hbs
  ui/app/templates/components/secret-list/pki-cert-item.hbs
  ui/app/templates/vault/cluster/settings/configure-secret-backend.hbs
  ui/app/templates/vault/cluster/settings/configure-secret-backend/section.hbs
  ui/tests/integration/components/pki/config-pki-ca-test.js
  ui/tests/integration/components/pki/config-pki-test.js
  ui/tests/pages/components/pki/config-pki-ca.js
  ui/tests/pages/components/pki/config-pki.js
  ui/tests/pages/settings/configure-secret-backends/pki/section-cert.js
  ui/tests/pages/settings/configure-secret-backends/pki/section.js
Labels: ui, pr/no-changelog

#15972 Clarify permitted_dns_domains are Name Constraints
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.10.x, backport/1.11.x

#15976 website: fix broken links
  website/content/api-docs/relatedtools.mdx
  website/content/api-docs/secret/transit.mdx
  website/content/docs/auth/azure.mdx
  website/content/docs/auth/jwt/index.mdx
  website/content/docs/concepts/client-count/faq.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/faq/ssct.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/plugins/plugin-portal.mdx
  website/content/docs/release-notes/1.9.0.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/secrets/terraform.mdx
  website/content/docs/what-is-vault.mdx
Labels: website, pr/no-changelog

#15971 KMSE distribute key bug
  ui/app/components/keymgmt/distribute.js
  ui/app/models/keymgmt/provider.js
  ui/app/templates/components/keymgmt/distribute.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/tests/acceptance/enterprise-kmse-test.js
  ui/tests/integration/components/keymgmt/provider-edit-test.js
Labels: ui, pr/no-changelog, backport/1.11.x

#15965 docs/vault-k8s: update the service annotation
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x

#15979 KMSE provider list menu fix
  ui/app/adapters/keymgmt/provider.js
  ui/app/serializers/keymgmt/provider.js
  ui/app/templates/components/secret-list/item.hbs
Labels: ui, bug, pr/no-changelog

#15961 Backport of updates `leasId` to `leaseId` into release/1.11.x
  changelog/15685.txt
  ui/app/models/aws-credential.js
Labels: ui, backport

#15960 Backport of updates `leasId` to `leaseId` into release/1.10.x
  changelog/15685.txt
  ui/app/models/aws-credential.js
Labels: ui, backport

#15959 Backport of updates `leasId` to `leaseId` into release/1.9.x
  changelog/15685.txt
  ui/app/models/aws-credential.js
Labels: ui, backport

#15966 Correct drift between ENT and OSS
  builtin/credential/aws/path_config_rotate_root_test.go
  command/operator_diagnose.go
  helper/identity/sentinel.go
  plugins/database/mssql/mssql.go
  vault/cluster.go
  vault/ha.go
Labels: pr/no-changelog

#15987 Update semgrep to the latest version - 0.97.0
  .circleci/config.yml
  .circleci/config/commands/setup-semgrep.yml
Labels: pr/no-changelog

#15856 Vault documentation: updated deprecation table for vault 1.11 release
  website/content/docs/deprecation/index.mdx
Labels: pr/no-changelog, backport/1.11.x

#15990 auth/gcp: adds note on custom endpoints to configuration section
  website/content/docs/agent/autoauth/methods/gcp.mdx
  website/content/docs/auth/gcp.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#15997 UI/VAULT-3645/Remove browserstack
  .circleci/config.yml
  .circleci/config/jobs/test-ui-browserstack.yml
  .circleci/config/workflows/ci.yml
  Makefile
  ui/README.md
  ui/package.json
  ui/scripts/start-vault.js
  ui/testem.browserstack.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog

#16002 Use new -mount syntax for all KV subcommands in 1.11 docs
  website/content/docs/commands/index.mdx
  website/content/docs/commands/kv/delete.mdx
  website/content/docs/commands/kv/destroy.mdx
  website/content/docs/commands/kv/get.mdx
  website/content/docs/commands/kv/index.mdx
  website/content/docs/commands/kv/metadata.mdx
  website/content/docs/commands/kv/patch.mdx
  website/content/docs/commands/kv/put.mdx
  website/content/docs/commands/kv/rollback.mdx
  website/content/docs/commands/kv/undelete.mdx
  website/content/docs/commands/read.mdx
Labels: pr/no-changelog, backport/1.11.x

#16004 manual backport: Use new -mount syntax for all KV subcommands in 1.11 docs
  website/content/docs/commands/index.mdx
  website/content/docs/commands/kv/delete.mdx
  website/content/docs/commands/kv/destroy.mdx
  website/content/docs/commands/kv/get.mdx
  website/content/docs/commands/kv/index.mdx
  website/content/docs/commands/kv/metadata.mdx
  website/content/docs/commands/kv/patch.mdx
  website/content/docs/commands/kv/put.mdx
  website/content/docs/commands/kv/rollback.mdx
  website/content/docs/commands/kv/undelete.mdx
  website/content/docs/commands/read.mdx
Labels: pr/no-changelog

#15980 PKI cleanup continued: queryParams and moving routes/models/serializers to pki folder
  ui/app/adapters/pki/cert.js
  ui/app/adapters/pki/pki-config.js
  ui/app/components/generate-credentials.js
  ui/app/helpers/options-for-backend.js
  ui/app/models/pki-ca-certificate.js
  ui/app/models/pki-certificate-sign.js
  ui/app/models/pki/cert.js
  ui/app/models/pki/pki-config.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/routes/vault/cluster/settings/configure-secret-backend/section.js
  ui/app/serializers/pki/cert.js
  ui/app/serializers/pki/pki-config.js
  ui/app/templates/components/pki/pki-cert-show.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/tests/acceptance/secrets/backend/pki/cert-test.js
Labels: ui, pr/no-changelog

#16005 Vault documentation: release notes for 1.11.0
  website/content/docs/release-notes/1.11.0.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.11.x

#15999 Refactor PKI tests for speed
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/test_helpers.go
Labels: test, pr/no-changelog

#16012 Document limitations in FIPS 140-2 migrations
  website/content/docs/enterprise/fips/fips1402.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x, fips

#16015 Fix format errors in PKI tests
  builtin/logical/pki/backend_test.go
Labels: pr/no-changelog

#16001 Added nonce field to payload for okta sign in.
  ui/app/adapters/cluster.js
  ui/app/components/auth-form.js
  ui/tests/unit/adapters/cluster-test.js
Labels: ui, pr/no-changelog

#16017 Document additional entropy augmentation usage locations
  website/content/docs/enterprise/entropy-augmentation.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x

#16007 Vault documentation: updated client count faqs for 1.11
  website/content/docs/concepts/client-count/faq.mdx
  website/public/img/vault-usage-metrics-1-11.png
Labels: pr/no-changelog, backport/1.11.x

#16026 docs: Fix sample request on okta verify nonce
  website/content/api-docs/auth/okta.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16028 OIDC Config Routing
  ui/app/router.js
  ui/app/routes/vault/cluster/access/oidc/assignments/assignment.js
  ui/app/routes/vault/cluster/access/oidc/assignments/assignment/edit.js
  ui/app/routes/vault/cluster/access/oidc/assignments/create.js
  ui/app/routes/vault/cluster/access/oidc/assignments/index.js
  ui/app/routes/vault/cluster/access/oidc/clients/client.js
  ui/app/routes/vault/cluster/access/oidc/clients/client/edit.js
  ui/app/routes/vault/cluster/access/oidc/clients/create.js
  ui/app/routes/vault/cluster/access/oidc/clients/index.js
  ui/app/routes/vault/cluster/access/oidc/index.js
  ui/app/routes/vault/cluster/access/oidc/keys/create.js
  ui/app/routes/vault/cluster/access/oidc/keys/index.js
  ui/app/routes/vault/cluster/access/oidc/keys/key.js
  ui/app/routes/vault/cluster/access/oidc/keys/key/edit.js
  ui/app/routes/vault/cluster/access/oidc/providers/create.js
  ui/app/routes/vault/cluster/access/oidc/providers/index.js
  ui/app/routes/vault/cluster/access/oidc/providers/provider.js
  ui/app/routes/vault/cluster/access/oidc/providers/provider/edit.js
  ui/app/routes/vault/cluster/access/oidc/scopes/create.js
  ui/app/routes/vault/cluster/access/oidc/scopes/index.js
  ui/app/routes/vault/cluster/access/oidc/scopes/scope.js
  ui/app/routes/vault/cluster/access/oidc/scopes/scope/edit.js
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/create.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/create.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
  ui/app/templates/vault/cluster/access/oidc/index.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/create.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/index.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/create.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/index.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/create.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/scope.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/scope/edit.hbs
Labels: ui, pr/no-changelog

#16024 Small refactor of mount entry manipulation
  vault/logical_system_quotas.go
  vault/mount.go
Labels: pr/no-changelog

#15993 docs: Add how to rotate SQL Server key
  website/content/docs/platform/mssql/installation.mdx
Labels: pr/no-changelog, backport/1.11.x

#15679 Document `LIST sys/quotas/lease-count`
  website/content/api-docs/system/lease-count-quotas.mdx
Labels: docs

#15944 Cleanup and simplify lock usage in database plugin
  builtin/logical/database/backend.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_rotate_credentials.go
  builtin/logical/database/rotation.go
Labels: pr/no-changelog

#16040 Fix flaky test
  ui/app/helpers/-date-base.js
Labels: ui, pr/no-changelog

#15817 Vault-5619: Transit BYOK Documentation
  website/content/api-docs/secret/transit.mdx
  website/content/docs/secrets/transit.mdx
Labels: pr/no-changelog, backport/1.11.x

#16052 Fix leaf revocation under intermediate CAs
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
Labels: bug, secret/pki, pr/no-changelog, rotation, backport/1.11.x

#16051 change rotation_period to algorithm
  website/content/docs/concepts/oidc-provider.mdx
Labels: docs/learn, pr/no-changelog

#16064 Clarify that the returned chain is used everywhere
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.11.x

#16068 fix docs typo - couple to few
  website/content/docs/agent/index.mdx
Labels: pr/no-changelog, backport/1.10.x

#16047 website: Update old learn links to redirect locations
  website/content/docs/secrets/databases/index.mdx
Labels: website, pr/no-changelog

#16069 UI/vault 6646/landing page
  ui/app/services/permissions.js
  ui/app/templates/vault/cluster/access.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/index.hbs
  ui/public/images/oidc-landing.png
Labels: ui, pr/no-changelog

#16074 Changelog updates for 1.11.0
  CHANGELOG.md
Labels: pr/no-changelog

#16049 Start of implementation of the plumbing for role resolution logic on auth mounts
  builtin/credential/approle/path_login.go
  builtin/credential/approle/path_login_test.go
  sdk/logical/request.go
  sdk/logical/response.go
  vault/logical_system_quotas.go
Labels: pr/no-changelog

#16081 Fix incorrect HSM mechanisms in transit BYOK docs
  website/content/docs/secrets/transit.mdx
Labels: pr/no-changelog, backport/1.11.x

#16083 Update for 1.11.1
  sdk/version/version_base.go
Labels: pr/no-changelog

#16086 Bump SDK version for 1.11.1
  go.mod
Labels: pr/no-changelog

#16032 UI/Glimmerize modal & confirmation modal component
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/keymgmt/key-edit.hbs
  ui/app/templates/components/mfa/method-form.hbs
  ui/lib/core/addon/components/confirmation-modal.hbs
  ui/lib/core/addon/components/confirmation-modal.js
  ui/lib/core/addon/components/info-table-row.js
  ui/lib/core/addon/components/modal.hbs
  ui/lib/core/addon/components/modal.js
  ui/lib/core/addon/templates/components/replication-action-demote.hbs
  ui/lib/core/addon/templates/components/replication-action-disable.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/integration/components/confirmation-modal-test.js
  ui/tests/integration/components/mfa/method-form-test.js
  ui/tests/integration/components/modal-test.js
Labels: ui, pr/no-changelog

#16009 changelog: fix spelling mistake
  CHANGELOG.md
Labels: pr/no-changelog

#16095 dockerfile: use ubi-minimal:8.6
  Dockerfile
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x

#11904 Improving Handling of Unix Domain Socket Addresses
  api/client.go
  api/client_test.go
  changelog/11904.txt
Labels: bug

#16079 Add role resolution operations to cert and aws auth types (VAULT-6612)
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  builtin/credential/aws/path_role.go
  builtin/credential/cert/path_login.go
  builtin/credential/cert/path_login_test.go
Labels: pr/no-changelog

#16099 fix typo in release notes
  website/content/docs/release-notes/1.11.0.mdx
Labels: docs, pr/no-changelog, backport/1.11.x

#16108 Docs: Fix typo for Lambda extension env var config
  website/content/docs/platform/aws/lambda-extension.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x

#16107 Add new KMIP backend operation parameters to API documentation.
  website/content/api-docs/secret/kmip.mdx
Labels: pr/no-changelog, backport/1.11.x
