Repository hashicorp/vault, pull requests merged in 2022-02, with the labels that each got.

#13777 Client Count Calendar widget updates
  ui/app/adapters/clients/activity.js
  ui/app/adapters/clients/monthly.js
  ui/app/components/calendar-widget.js
  ui/app/components/clients/dashboard.js
  ui/app/models/clients/activity.js
  ui/app/models/clients/monthly.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/mirage/handlers/activity.js
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog

#13868 update changelog with recent security entries
  CHANGELOG.md
Labels: pr/no-changelog

#13812 UI/Add CSV export, update history and current tabs
  ui/app/adapters/clients/activity.js
  ui/app/components/clients/attribution.js
  ui/app/components/clients/current.js
  ui/app/components/clients/dashboard.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/models/clients/activity.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/services/download-csv.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/styles/components/doc-link.scss
  ui/app/styles/components/modal.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/core/title.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/horizontal-bar-chart.hbs
  ui/app/templates/components/clients/usage-stats.hbs
  ui/app/templates/vault/cluster/clients/index.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/components/download-csv.js
  ui/lib/core/addon/templates/components/download-csv.hbs
  ui/lib/core/app/components/download-csv.js
  ui/tests/integration/components/clients-history-test.js
Labels: ui, pr/no-changelog

#13872 Fix kv secret access bug
  changelog/13872.txt
  ui/app/routes/vault/cluster/secrets/backend/list.js
Labels: ui, backport

#13880 Backport 1.9.x: Fix kv secret access bug
  changelog/13872.txt
  ui/app/routes/vault/cluster/secrets/backend/list.js
Labels: ui, bug

#13879 UI/Fix activity and monthly serializer
  ui/app/components/clients/attribution.js
  ui/app/components/clients/current.js
  ui/app/components/clients/dashboard.js
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
Labels: ui, pr/no-changelog

#13876 Make backport assistant work with ENT backport tags
  .github/workflows/backport.yml
Labels: pr/no-changelog

#13888 turning go modules to false until jwt cve issue fixed
  .release/security-scan.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.7.x

#13798 Use `improvement` instead of `feature` for API update
  changelog/12793.txt
Labels: pr/no-changelog

#12936 Update index.mdx
  website/content/docs/configuration/index.mdx
Labels: pr/no-changelog, backport/website

#13790 docs/helm: fix duplicate ingress tls section
  website/content/docs/platform/k8s/helm/configuration.mdx
Labels: pr/no-changelog, backport/website

#13139 Add Rekey Example When Auto Unseal is Used
  website/content/docs/commands/operator/rekey.mdx
Labels: pr/no-changelog

#11985 Document the use of inline SSL certificates for PostgreSQL
  website/content/api-docs/secret/databases/postgresql.mdx
Labels: ecosystem, pr/no-changelog

#13596 Backport of Add missing word "database" in docs into stable-website
  README.md
  website/content/docs/what-is-vault.mdx
Labels: backport/website

#13894 Switch from node-forge to PKI.js
  changelog/13894.txt
  ui/app/helpers/parse-pki-cert.js
  ui/package.json
  ui/yarn.lock
Labels: ui, secret/pki

#13529 Fix documentation of "replication_performance_mode" in health API
  website/content/api-docs/system/health.mdx
Labels: docs, pr/no-changelog, backport/website

#13148 Update delete.mdx
  website/content/docs/commands/delete.mdx
Labels: docs, pr/no-changelog

#13559 Backport of Fix a sentence in architecture.mdx into release/1.8.x
  website/content/docs/internals/architecture.mdx
Labels: pr/no-changelog, backport/1.8.x

#13881 Client count namespace filter
  ui/app/components/clients/current.js
  ui/app/components/clients/dashboard.js
  ui/app/styles/components/icon.scss
  ui/app/styles/components/search-select.scss
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/templates/components/search-select-placeholder.hbs
  ui/lib/core/addon/templates/components/search-select.hbs
Labels: ui, pr/no-changelog

#13841 [API] Add LDAP auth method
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/ldap/ldap.go
  api/auth/ldap/ldap_test.go
  changelog/13841.txt
Labels: auth/ldap, devex

#13824 Backport of docs: add cluster-to-cluster communications to external threat overview into release/1.9.x
  website/content/docs/internals/security.mdx
Labels: pr/no-changelog, backport/1.9.x

#13782 [Docs] Adding dotnet example app to docs
  website/content/api-docs/libraries.mdx
Labels: docs, pr/no-changelog, backport/website

#13905 Seal wrap storage entries of the ManagedKeyRegistry.
  http/handler_test.go
  http/sys_mount_test.go
  vault/logical_system.go
  vault/logical_system_test.go
  vault/managed_key_registry.go
  vault/mount.go
  vault/mount_test.go
Labels: pr/no-changelog

#13316 Add iam:GetUser permission to the example.
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog

#13401 typo: Updated terraform dynamodb example
  website/content/docs/configuration/storage/dynamodb.mdx
Labels: docs, pr/no-changelog, backport/website

#13914 Run 'make fmt'.
  api/auth/ldap/ldap.go
  api/auth/ldap/ldap_test.go
Labels: pr/no-changelog

#13912 Backport of typo: Updated terraform dynamodb example into release/1.9.x
  website/content/docs/configuration/storage/dynamodb.mdx
Labels: pr/no-changelog, backport/1.9.x

#13913 UI/Fix parsing CRL in PKI engine
  ui/app/helpers/parse-pki-cert.js
  ui/app/serializers/pki-certificate.js
  ui/tests/acceptance/settings/configure-secret-backends/pki/section-cert-test.js
  ui/tests/pages/components/config-pki-ca.js
Labels: ui, pr/no-changelog

#13920 Turning off binary secret scanning
  .release/security-scan.hcl
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.7.x

#13924 docs/oracle: add wallet permissions example
  website/content/docs/secrets/databases/oracle.mdx
Labels: pr/no-changelog, backport/website

#13871 Feat/OIDC loopback redirect dynamic
  changelog/13871.txt
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_util.go
Labels: ecosystem, bug, identity/oidc

#13908 Transform Advanced Templating
  changelog/13908.txt
  ui/app/components/kv-object-editor.js
  ui/app/components/regex-validator.hbs
  ui/app/components/regex-validator.js
  ui/app/components/transform-advanced-templating.js
  ui/app/models/transform/template.js
  ui/app/serializers/transform/template.js
  ui/app/styles/components/regex-validator.scss
  ui/app/styles/components/transform-edit.scss
  ui/app/styles/core/forms.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/utils/_colors.scss
  ui/app/templates/components/kv-object-editor.hbs
  ui/app/templates/components/transform-advanced-templating.hbs
  ui/app/templates/components/transform-template-edit.hbs
  ui/lib/core/addon/components/autocomplete-input.hbs
  ui/lib/core/addon/components/autocomplete-input.js
  ui/lib/core/addon/components/form-field-label.hbs
  ui/lib/core/addon/components/form-field-label.js
  ui/lib/core/addon/templates/components/form-field.hbs
  ui/lib/core/app/components/autocomplete-input.js
  ui/lib/core/app/components/form-field-label.js
  ui/tests/integration/components/autocomplete-input-test.js
  ui/tests/integration/components/form-field-label-test.js
  ui/tests/integration/components/kv-object-editor-test.js
  ui/tests/integration/components/regex-validator-test.js
  ui/tests/integration/components/transform-advanced-templating-test.js
Labels: ui

#13939 identity/oidc: adds tests for validation of loopback IP redirect URIs
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_provider_util.go
Labels: pr/no-changelog

#13402 Typo: Corrected same typo in 2 locations (on-premise to on-premises)
  website/content/docs/secrets/terraform.mdx
Labels: docs, waiting-for-response, pr/no-changelog, backport/website

#13951 go-mssqldb: update to v0.12.0
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.9.x

#13944 auth/okta: documentation improvements
  website/content/docs/auth/okta.mdx
Labels: pr/no-changelog, backport/website

#13950 UI: Add check for renewal time before triggering renew-self
  changelog/13950.txt
  ui/app/services/auth.js
Labels: ui, bug, backport/1.9.x, backport/1.8.x, backport/1.7.x

#13931 Correct return value explanation in docstring
  api/client.go
Labels: pr/no-changelog

#13907 Client counts version-history endpoint
  ui/app/adapters/clients/version-history.js
  ui/app/components/clients/current.js
  ui/app/components/clients/dashboard.js
  ui/app/models/clients/version-history.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/serializers/clients/version-history.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/mirage/handlers/activity.js
Labels: ui, pr/no-changelog

#13856 Add documentation for Managed Keys
  command/secrets_enable.go
  command/secrets_tune.go
  website/content/api-docs/secret/pki.mdx
  website/content/api-docs/system/managed-keys.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#13597 Backport of Add missing word "database" in docs into release/1.9.x
  README.md
  website/content/docs/what-is-vault.mdx
Labels: pr/no-changelog, backport/1.9.x

#13104 mysql is also supported for transform external storage
  website/content/docs/secrets/transform/index.mdx
Labels: pr/no-changelog, backport/website

#13910 Backport of [Docs] Adding dotnet example app to docs into release/1.9.x
  website/content/api-docs/libraries.mdx
Labels: pr/no-changelog, backport/1.9.x

#13966 Remove old vault binary in GOPATH/bin/ before copying new one back into it
  scripts/build.sh
Labels: pr/no-changelog

#13973 secrets/azure: update to v0.11.3
  changelog/13973.txt
  go.mod
  go.sum
Labels: backport/1.9.x

#13961 Vault documentation: added a warning message to vault ui browser support doc
  website/content/docs/browser-support.mdx
Labels: pr/no-changelog, backport/website

#12658 Use secret_id_bound_cidrs instead of bound_cidr_list in approle docs
  website/content/api-docs/auth/approle.mdx
Labels: core, waiting-for-response, auth/approle, docs-cherrypick, website, pr/no-changelog

#13974 secrets/gcp: update to v0.11.2
  changelog/13974.txt
  go.mod
  go.sum
Labels: backport/1.9.x

#13968 Add clarification around vague "this" references
  website/content/docs/agent/autoauth/index.mdx
  website/content/docs/configuration/listener/tcp.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/secrets/aws.mdx
  website/content/docs/secrets/databases/oracle.mdx
  website/content/docs/secrets/gcp.mdx
Labels: docs, pr/no-changelog, backport/website

#13948 Formatting touch ups on storage/dynamodb.mdx
  website/content/docs/configuration/storage/dynamodb.mdx
Labels: docs, pr/no-changelog, backport/website

#13959 Vault documentation: Updated Licensing FAQ page
  website/content/docs/enterprise/license/faq.mdx
Labels: pr/no-changelog, backport/website

#13985 Backport of secrets/gcp: update to v0.11.2 into release/1.9.x
  changelog/13974.txt
  go.mod
  go.sum
Labels: backport

#13969 Fix Environment Variables in Kubernetes config
  website/content/docs/auth/kubernetes.mdx
Labels: docs, ecosystem, pr/no-changelog

#13438 Update gcp.mdx
  website/content/docs/secrets/gcp.mdx
Labels: pr/no-changelog, backport/website

#13967 Update approle.mdx
  website/content/docs/auth/approle.mdx
Labels: docs, pr/no-changelog, backport/website

#13895 contained_db DeleteUser unit test
  plugins/database/mssql/mssql_test.go
Labels: pr/no-changelog

#13994 Remove extra blank line from consul-scrt-eng-upd
  helper/testhelpers/consul/consulhelper.go
Labels: pr/no-changelog

#13992 Vault documentation: added link to HCP Vault doc site
  website/content/docs/what-is-vault.mdx
  website/data/docs-nav-data.json
Labels: docs-cherrypick, pr/no-changelog

#13993 Vault documentation: cleaned up some steps in the FAQ doc
  website/content/docs/enterprise/license/faq.mdx
Labels: pr/no-changelog, backport/website

#13937 Calendar widget tooltip
  ui/app/components/calendar-widget.js
  ui/app/components/clients/history.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
Labels: ui, pr/no-changelog

#13964 UI/Client counts view if no license
  ui/app/adapters/clients/activity.js
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/components/date-dropdown.js
  ui/app/routes/vault/cluster/clients/history.js
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/templates/vault/cluster.hbs
  ui/app/templates/vault/cluster/clients/history.hbs
  ui/tests/integration/components/clients-current-test.js
Labels: ui, pr/no-changelog

#13947 vault/external_tests/approle: fix dropped test error
  vault/external_tests/approle/wrapped_secretid_test.go
Labels: auth/approle, pr/no-changelog

#13999 Add 'Integrated Storage vs. Consul' comparison
  website/content/docs/concepts/storage.mdx
  website/content/docs/configuration/storage/index.mdx
Labels: pr/no-changelog, backport/website

#14013 identity/oidc: use inherited group membership for client assignments
  changelog/14013.txt
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
Labels: backport/1.9.x

#14020 docs/azure: add note about identities
  website/content/docs/auth/azure.mdx
Labels: pr/no-changelog, backport/website

#14022 Some folder restructuring to help with route loading states
  ui/app/components/clients/history.js
  ui/app/controllers/vault/cluster/clients.js
  ui/app/controllers/vault/cluster/clients/current.js
  ui/app/router.js
  ui/app/routes/vault/cluster/clients.js
  ui/app/routes/vault/cluster/clients/config.js
  ui/app/routes/vault/cluster/clients/current.js
  ui/app/routes/vault/cluster/clients/history.js
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/config.hbs
  ui/app/templates/vault/cluster/clients/current.hbs
  ui/app/templates/vault/cluster/clients/history.hbs
  ui/app/templates/vault/cluster/clients/index.hbs
  ui/mirage/handlers/activity.js
  ui/tests/integration/components/clients-current-test.js
Labels: ui, pr/no-changelog

#13851 Backport 1.8.x: Fix pkcs7 parsing in some cases (#12519)
  builtin/credential/aws/pkcs7/ber.go
  builtin/credential/aws/pkcs7/ber_test.go
  changelog/12519.txt
Labels: backport

#14036 Vault documentation: added new warning to listener stanza parameters
  website/content/docs/configuration/listener/tcp.mdx
Labels: pr/no-changelog, backport/website

#14030 docs/fix-code-block-in-tab
  website/content/api-docs/secret/aws.mdx
Labels: pr/no-changelog, backport/website

#14050 Client count: remove default period and extra controllers
  ui/app/components/clients/config.js
  ui/app/controllers/vault/cluster/clients/config.js
  ui/app/controllers/vault/cluster/clients/current.js
  ui/app/controllers/vault/cluster/clients/history.js
  ui/app/controllers/vault/cluster/clients/index.js
  ui/app/models/clients/config.js
  ui/app/serializers/clients/config.js
  ui/app/templates/components/clients/config.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/vault/cluster/clients/edit.hbs
  ui/tests/integration/components/clients-config-test.js
Labels: ui, pr/no-changelog

#13893 add API docs for KVv2 subkeys endpoint
  changelog/13893.txt
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: secret/kv

#14044 Remove documentation for upcoming /pki/tidy-status endpoint.
  website/content/api-docs/secret/pki.mdx
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog, backport/website

#14062 fix fmt issues introduced by version-history
  command/version_history.go
  vault/logical_system.go
  vault/logical_system_integ_test.go
  vault/version_store.go
  vault/version_store_test.go
Labels: pr/no-changelog

#14065 Some format edits for PR14038
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog

#14064 Tool Tip Styling Issue
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/console/command-input.hbs
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/templates/components/diff-version-selector.hbs
  ui/app/templates/components/hover-copy-button.hbs
  ui/app/templates/components/namespace-picker.hbs
  ui/app/templates/components/raft-storage-overview.hbs
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/app/templates/components/secret-form-show.hbs
  ui/app/templates/components/secret-list/transform-list-item.hbs
  ui/app/templates/components/secret-version-menu.hbs
  ui/app/templates/components/status-menu.hbs
  ui/app/templates/components/transformation-edit.hbs
  ui/app/templates/components/wizard-content.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
  ui/lib/core/addon/components/autocomplete-input.hbs
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/templates/components/box-radio.hbs
  ui/lib/core/addon/templates/components/confirm-action.hbs
  ui/lib/core/addon/templates/components/info-tooltip.hbs
  ui/lib/core/addon/templates/components/linkable-item/content.hbs
  ui/lib/core/addon/templates/components/popup-menu.hbs
  ui/lib/core/addon/templates/components/replication-secondary-card.hbs
  ui/lib/core/addon/templates/components/toolbar-link.hbs
  ui/lib/core/addon/templates/components/ttl-picker2.hbs
  ui/scripts/codemods/dropdown-transform.js
Labels: ui, pr/no-changelog

#14008 Allow generation of other types of SSH CA keys
  builtin/logical/ssh/path_config_ca.go
  builtin/logical/ssh/path_config_ca_test.go
  changelog/14008.txt
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, secret/ssh, cryptosec

#14031 Vault Integration Program Update
  website/content/docs/partnerships.mdx
  website/public/img/HCPV_badge.png
  website/public/img/VaultEnterprise_badge.png
  website/public/img/integration-program-vaulteco.png
Labels: pr/no-changelog, backport/website

#14078 Return integral seconds for transit auto_rotate_interval instead of a time string.
  builtin/logical/transit/path_config_test.go
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_keys_test.go
Labels: pr/no-changelog

#14089 website: update docs-page, fix code tabs syncing
  website/package-lock.json
  website/package.json
Labels: website, pr/no-changelog, backport/website

#14092 Convert install instructions to use tabs
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog

#14093 UI/client count auth filter
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/helpers/format-ttl.js
  ui/app/serializers/clients/config.js
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/mirage/handlers/activity.js
  ui/tests/integration/helpers/format-ttl-test.js
Labels: ui, pr/no-changelog

#14067 api/client: forward and inconsistent header const
  api/client.go
  changelog/14067.txt
Labels: clientapi

#14066 Ui/ Clients error handling
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/components/date-dropdown.js
  ui/app/routes/vault/cluster/clients/history.js
  ui/app/styles/core/buttons.scss
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/templates/vault/cluster/clients/error.hbs
Labels: ui, pr/no-changelog

#14104 oss changes for cross ns remount
  api/sys_mounts.go
  command/secrets_move.go
  command/secrets_move_test.go
  helper/namespace/namespace.go
  http/sys_mount_test.go
  vault/auth.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_quotas.go
  vault/logical_system_test.go
  vault/mount.go
  vault/mount_test.go
  vault/quotas/quotas.go
  vault/quotas/quotas_rate_limit.go
  vault/quotas/quotas_test.go
  vault/quotas/quotas_util.go
Labels: pr/no-changelog

#14101 Fix ed25519 generated SSH key marshalling
  builtin/logical/ssh/path_config_ca.go
  builtin/logical/ssh/path_config_ca_test.go
  go.mod
  go.sum
Labels: bug, secret/ssh, pr/no-changelog, cryptosec

#14108 Update plugin-portal.mdx (#13229)
  website/content/docs/plugin-portal.mdx
Labels: pr/no-changelog, backport/website

#14103 Rename transit's auto_rotate_interval to auto_rotate_period
  builtin/logical/transit/backend.go
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_config.go
  builtin/logical/transit/path_config_test.go
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_keys_test.go
  sdk/helper/keysutil/lock_manager.go
  sdk/helper/keysutil/policy.go
  ui/app/components/transit-edit.js
  ui/app/helpers/format-duration.js
  ui/app/models/transit-key.js
  ui/app/serializers/transit-key.js
  ui/app/templates/components/transit-form-create.hbs
  ui/app/templates/components/transit-form-edit.hbs
  ui/app/templates/components/transit-form-show.hbs
  website/content/api-docs/secret/transit.mdx
Labels: pr/no-changelog

#14107 fix approle login IPBelongsToCIDRBlocksSlice err handling
  builtin/credential/approle/path_login.go
  changelog/14107.txt
Labels: bug, auth/approle

#14038 Vault documentation: created new developer quick start guide
  website/content/docs/get-started/developer-qs.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/website

#14087 Document `vault write` JSON request parameters
  website/content/docs/commands/write.mdx
Labels: docs, pr/no-changelog, backport/website

#14118 UI/format-duration error fix
  ui/app/helpers/format-duration.js
Labels: ui, pr/no-changelog

#14126 update G Suite to Google Workspace in docs
  website/content/docs/auth/gcp.mdx
  website/content/docs/auth/jwt/oidc_providers.mdx
Labels: website, pr/no-changelog

#14112 Update repository links to point to main
  ui/app/components/home-link.js
  ui/app/models/role-ssh.js
  ui/lib/core/stories/alert-banner.md
  ui/lib/core/stories/alert-inline.md
  ui/lib/core/stories/bar-chart.md
  ui/lib/core/stories/box-radio.md
  ui/lib/core/stories/chevron.md
  ui/lib/core/stories/confirm-action.md
  ui/lib/core/stories/confirm.md
  ui/lib/core/stories/doc-link.md
  ui/lib/core/stories/empty-state.md
  ui/lib/core/stories/form-field-groups.md
  ui/lib/core/stories/form-field.md
  ui/lib/core/stories/form-save-buttons.md
  ui/lib/core/stories/icon.md
  ui/lib/core/stories/info-table-row.md
  ui/lib/core/stories/info-table.md
  ui/lib/core/stories/layout-loading.md
  ui/lib/core/stories/linkable-item.md
  ui/lib/core/stories/list-view.md
  ui/lib/core/stories/masked-input.md
  ui/lib/core/stories/message-error.md
  ui/lib/core/stories/message.md
  ui/lib/core/stories/popup-menu.md
  ui/lib/core/stories/search-select.md
  ui/lib/core/stories/select.md
  ui/lib/core/stories/stat-text.md
  ui/lib/core/stories/toggle-button.md
  ui/lib/core/stories/toolbar/toolbar-actions.md
  ui/lib/core/stories/toolbar/toolbar-download-button.md
  ui/lib/core/stories/toolbar/toolbar-filters.md
  ui/lib/core/stories/toolbar/toolbar-link.md
  ui/lib/core/stories/toolbar/toolbar-secret-link.md
  ui/lib/core/stories/toolbar/toolbar.md
  ui/lib/core/stories/ttl-form.md
  ui/lib/core/stories/ttl-picker.md
  ui/lib/core/stories/ttl-picker2.md
  ui/lib/core/stories/vault-logo-spinner.md
  ui/scripts/gen-story-md.js
  ui/stories/alert-popup.md
  ui/stories/auth-config-form/config.md
  ui/stories/auth-config-form/options.md
  ui/stories/auth-form.md
  ui/stories/file-to-array-buffer.md
  ui/stories/selectable-card.md
  ui/stories/toggle.md
  website/content/api-docs/relatedtools.mdx
  website/content/docs/agent/autoauth/index.mdx
  website/content/docs/auth/aws.mdx
  website/content/docs/plugin-portal.mdx
  website/content/docs/secrets/ssh/dynamic-ssh-keys.mdx
Labels: ui, docs, pr/no-changelog, backport/website

#14130 secrets/azure: update plugin to v0.11.4
  changelog/14130.txt
  go.mod
  go.sum
  website/content/api-docs/secret/azure.mdx
Labels: backport/1.9.x

#14105 feature: multiplexing: handle error plugin shutdown
  vault/plugin_catalog.go
Labels: pr/no-changelog

#13991 Allow specifying multiple allowed SSH key lengths
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_roles.go
  builtin/logical/ssh/path_sign.go
  builtin/logical/ssh/util.go
  changelog/13991.txt
  go.mod
  go.sum
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, secret/ssh, cryptosec

#14140 builtin/logical/pki: fix dropped test error
  builtin/logical/pki/backend_test.go
Labels: secret/pki, pr/no-changelog, cryptosec

#14139 Calendar widget test and small styling fix on wide screens
  ui/app/adapters/clients/monthly.js
  ui/app/components/calendar-widget.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/tests/integration/components/calendar-widget-test.js
  ui/tests/pages/components/calendar-widget.js
Labels: ui, pr/no-changelog

#13675 Add telemetry to Vault agent
  api/lifetime_watcher.go
  changelog/13675.txt
  command/agent.go
  command/agent/auth/auth.go
  command/agent/cache/handler.go
  command/agent_test.go
  sdk/helper/consts/agent.go
  website/content/docs/agent/index.mdx
Labels: ecosystem, agent

#14102 Cleanup bool checks
  builtin/logical/mysql/backend_test.go
  builtin/logical/postgresql/secret_creds.go
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/stepwise_test.go
  http/handler.go
  http/sys_mounts_test.go
  plugins/database/influxdb/connection_producer.go
  serviceregistration/consul/consul_service_registration_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/barrier_aes_gcm_test.go
  vault/request_handling.go
Labels: pr/no-changelog

#14098 validate cipher length before decrypting
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: pr/no-changelog

#14154 Backport 1.7.10: TOB-016 fix
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: pr/no-changelog

#14156 Backport 1.8.9: TOB-016 fix
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: pr/no-changelog

#14157 Backport 1.9.4: TOB-016 fix
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: pr/no-changelog

#14141 Vault 4632 auth remount oss
  http/sys_auth_test.go
  vault/auth.go
  vault/auth_test.go
  vault/logical_system.go
  vault/logical_system_test.go
  vault/mount.go
  vault/mount_test.go
Labels: pr/no-changelog

#14079 Add HTTP-level tests for KV subkeys endpoint
  go.mod
  go.sum
  vault/external_tests/kv/kv_subkeys_test.go
Labels: secret/kv, test, pr/no-changelog

#14148 ui/oidc: adds PKCE code_challenge and code_challenge_method parameters
  ui/app/controllers/vault/cluster/oidc-provider.js
Labels: ui, pr/no-changelog

#14027 Remove --privileged recommendation from entrypoint script message
  .release/docker/docker-entrypoint.sh
  scripts/docker/docker-entrypoint.sh
Labels: pr/no-changelog

#14168 add missed test
  vault/logical_system_test.go
Labels: pr/no-changelog

#14143 Allow OpenSSH-style key type identifiers
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_sign.go
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, pr/no-changelog

#13960 Fix link to Kubernetes 1.21 section
  website/content/docs/auth/kubernetes.mdx
Labels: pr/no-changelog, backport/website

#14179 Invalidate the ManagedKeyRegistry cache when Vault config is updated.
  command/server.go
  vault/managed_key_registry.go
Labels: pr/no-changelog

#14181 Fix a simple typo
  website/content/api-docs/system/monitor.mdx
Labels: pr/no-changelog, backport/website

#13883 [VAULT-1011] Update autoauth docs
  website/content/docs/agent/autoauth/index.mdx
Labels: pr/no-changelog

#14166 UI/Client counts changelog 1.10
  changelog/client-counts.txt
  ui/app/components/clients/history-old.js
  ui/app/components/pricing-metrics-dates.js
  ui/app/styles/components/pricing-metrics-dates.scss
  ui/app/styles/core.scss
  ui/app/templates/components/clients/history-old.hbs
  ui/app/templates/components/pricing-metrics-dates.hbs
  ui/lib/core/addon/components/bar-chart.js
  ui/lib/core/addon/templates/components/bar-chart.hbs
  ui/lib/core/app/components/bar-chart.js
  ui/lib/core/stories/bar-chart.md
  ui/lib/core/stories/bar-chart.stories.js
  ui/tests/integration/components/bar-chart-test.js
  ui/tests/integration/components/pricing-metrics-dates-test.js
Labels: ui

#14167 Replace dgrijava/jwt-go with golang-jwt/jwt for login_mfa
  go.mod
  go.sum
  vault/login_mfa.go
Labels: pr/no-changelog

#14201 Prefix mount to path
  ui/app/serializers/clients/activity.js
  ui/app/serializers/clients/monthly.js
  ui/mirage/handlers/clients.js
  ui/mirage/handlers/index.js
Labels: ui, pr/no-changelog

#14203 sdk prerelease version upgrade (dev-1)
  sdk/version/version_base.go
Labels: pr/no-changelog

#14210 update sdk in go mod for vault and api
  go.mod
Labels: pr/no-changelog

#14205 fix(doc): mention that leases can be revoked on the UI
  website/content/docs/concepts/lease.mdx
Labels: docs, pr/no-changelog, backport/website

#14212 docs/vault-k8s: path for agent-inject-token
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: docs, k8s, pr/no-changelog, backport/website

#14180 Add documentation for managed key test sign API
  website/content/api-docs/system/managed-keys.mdx
Labels: docs, pr/no-changelog

#14190 Update github.com/prometheus/client_golang
  changelog/14190.txt
  go.mod
  go.sum
Labels: dependencies

#14224 UI/fix db role ttl display
  changelog/14224.txt
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/utils/database-helpers.js
  ui/tests/integration/components/database-role-setting-form-test.js
Labels: ui, bug, backport/1.9.x, backport/1.8.x, backport/1.7.x

#14024 Fix max measurements gauge test
  helper/metricsutil/gauge_process.go
  helper/metricsutil/gauge_process_test.go
Labels: pr/no-changelog

#14233 UI: Fix incorrect validity modal on transit secrets engine
  changelog/14233.txt
  ui/app/templates/components/transit-key-actions.hbs
Labels: ui, bug, backport/1.9.x

#14235 Fix broken interactions between glob_domains and wildcards
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  changelog/14235.txt
Labels: secret/pki, cryptosec

#14222 Set header content type instead of overwriting all headers
  api/logical.go
  changelog/14222.txt
Labels: bug, core/api

#14239 Remove use of compressionutil from activitylog segments.
  vault/activity_log.go
  vault/activity_log_test.go
Labels: pr/no-changelog

#14243 Mirage MFA Fix
  ui/tests/acceptance/mfa-test.js
Labels: ui, pr/no-changelog

#14238 Add role parameter to restrict issuance of wildcard certificates
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_root.go
  changelog/14238.txt
Labels: enhancement, secret/pki, cryptosec

#14236 Clarify documentation around certificate issuance
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, cryptosec

#14246 Make web_ui complient with Go's native embedding
  http/web_ui/.gitkeep
Labels: ui, pr/no-changelog

#14244 builtin/logical/transit: fix dropped test error
  builtin/logical/transit/path_config_test.go
Labels: secret/transit, test, pr/no-changelog

#14242 Fix broken interactions between glob_domains and wildcards
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  changelog/14235.txt
Labels: secret/pki, cryptosec

#14251 Backport 1.9.x - Add role parameter to restrict issuance of wildcard certificates + Clarify documentation around certificate issuance
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_root.go
  changelog/14238.txt
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, cryptosec

#14252 Backport 1.8.x - Add role parameter to restrict issuance of wildcard certificates + Clarify documentation around certificate issuance
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_util.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_root.go
  changelog/14238.txt
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, cryptosec

#14250 Client Count Styling fixes after design review
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/styles/components/calendar-widget.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/core/title.scss
  ui/app/templates/components/clients/usage-stats.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/lib/core/addon/templates/components/empty-state.hbs
  ui/lib/core/addon/templates/components/stat-text.hbs
Labels: ui, pr/no-changelog

#14227 Backport of UI/fix db role ttl display into release/1.8.x
  ui/app/components/database-role-setting-form.js
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/tests/integration/components/database-role-setting-form-test.js
Labels: ui

#14226 Backport of UI/fix db role ttl display into release/1.9.x
  changelog/14224.txt
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/utils/database-helpers.js
  ui/tests/integration/components/database-role-setting-form-test.js
Labels: ui

#14237 Fix ent diff check 2022/02/23
  .github/workflows/build.yml
  vault/core.go
  vault/request_handling.go
Labels: pr/no-changelog

#14256 plugin/database: update changelog to include db config connection return value change
  changelog/14033.txt
Labels: pr/no-changelog

#14162 UI/client count tests
  ui/README.md
  ui/app/components/clients/attribution.js
  ui/app/components/clients/current.js
  ui/app/components/clients/history.js
  ui/app/components/clients/horizontal-bar-chart.js
  ui/app/components/clients/line-chart.js
  ui/app/components/clients/vertical-bar-chart.js
  ui/app/components/date-dropdown.js
  ui/app/routes/vault/cluster/clients/history.js
  ui/app/styles/core/charts.scss
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/components/clients/line-chart.hbs
  ui/app/templates/components/clients/usage-stats.hbs
  ui/app/templates/components/clients/vertical-bar-chart.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/templates/components/stat-text.hbs
  ui/lib/core/addon/templates/components/toolbar.hbs
  ui/mirage/handlers/activity.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/client-current-test.js
  ui/tests/acceptance/client-history-test.js
  ui/tests/acceptance/oidc-provider-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients-current-test.js
  ui/tests/integration/components/clients-history-test.js
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/components/clients/config-test.js
  ui/tests/integration/components/clients/horizontal-bar-chart-test.js
  ui/tests/integration/components/clients/line-chart-test.js
  ui/tests/integration/components/clients/usage-stats-test.js
  ui/tests/integration/components/clients/vertical-bar-chart-test.js
  ui/tests/integration/components/date-dropdown-test.js
  ui/tests/unit/utils/chart-helpers-test.js
Labels: ui, pr/no-changelog

#14255 Backport 1.9: UI Fix incorrect validity message on transit verify
  changelog/14233.txt
  ui/app/templates/components/transit-key-actions.hbs
Labels: ui, backport

#14240 chore: bump docs-page for code-block fix
  website/package-lock.json
  website/package.json
Labels: website, pr/no-changelog, backport/website

#14228 Backport of UI/fix db role ttl display into release/1.7.x
  ui/app/components/database-role-setting-form.js
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/tests/integration/components/database-role-setting-form-test.js
Labels: ui

#14264 sdk changes for 1.10.0 release branch
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog

#14223 Quit agent endpoint with config
  changelog/14223.txt
  command/agent.go
  command/agent_test.go
  command/server/config_test_helpers.go
  internalshared/configutil/listener.go
  sdk/helper/consts/agent.go
  website/content/docs/agent/index.mdx
Labels: enhancement, agent

#14270 Replace docs references to PUT with POST
  website/content/api-docs/index.mdx
  website/content/api-docs/secret/aws.mdx
  website/content/api-docs/secret/cubbyhole.mdx
  website/content/api-docs/secret/key-management/awskms.mdx
  website/content/api-docs/secret/key-management/azurekeyvault.mdx
  website/content/api-docs/secret/key-management/gcpkms.mdx
  website/content/api-docs/secret/key-management/index.mdx
  website/content/api-docs/secret/kv/kv-v1.mdx
  website/content/api-docs/system/audit.mdx
  website/content/api-docs/system/config-auditing.mdx
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/config-cors.mdx
  website/content/api-docs/system/config-reload.mdx
  website/content/api-docs/system/config-ui.mdx
  website/content/api-docs/system/generate-recovery-token.mdx
  website/content/api-docs/system/generate-root.mdx
  website/content/api-docs/system/init.mdx
  website/content/api-docs/system/leases.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/plugins-catalog.mdx
  website/content/api-docs/system/plugins-reload-backend.mdx
  website/content/api-docs/system/policies-password.mdx
  website/content/api-docs/system/policies.mdx
  website/content/api-docs/system/policy.mdx
  website/content/api-docs/system/raw.mdx
  website/content/api-docs/system/rekey-recovery-key.mdx
  website/content/api-docs/system/rekey.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/rotate.mdx
  website/content/api-docs/system/seal.mdx
  website/content/api-docs/system/step-down.mdx
  website/content/api-docs/system/unseal.mdx
  website/content/docs/auth/jwt/oidc_providers.mdx
  website/content/docs/auth/oci.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/release-notes/1.8.0.mdx
  website/content/docs/secrets/ad.mdx
  website/content/docs/secrets/aws.mdx
  website/content/docs/secrets/consul.mdx
  website/content/intro/getting-started/policies.mdx
Labels: pr/no-changelog, backport/website

#14277 Fix missing quote in docs
  website/content/api-docs/secret/key-management/awskms.mdx
Labels: pr/no-changelog, backport/website
