Repository hashicorp/vault, pull requests merged in 2022-11, with the labels that each got.

#17679 Fix kv -mount flag error when mount and secret path are the same
  changelog/17679.txt
  command/kv_delete.go
  command/kv_destroy.go
  command/kv_get.go
  command/kv_metadata_delete.go
  command/kv_metadata_get.go
  command/kv_metadata_patch.go
  command/kv_metadata_put.go
  command/kv_patch.go
  command/kv_put.go
  command/kv_rollback.go
  command/kv_test.go
Labels: core/cli, secret/kv, backport/1.11.x, backport/1.12.x

#17762 Reduce number of places where go version is set
  .circleci/config.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/commands/setup-go.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/build-go-dev.yml
  .circleci/config/jobs/fmt.yml
  .circleci/config/jobs/pre-flight-checks.yml
  .circleci/config/jobs/test-go-nightly.yml
  .github/workflows/goversion-checker.yml
  .go-version
  Makefile
  README.md
  scripts/docker/Dockerfile
  scripts/docker/Dockerfile.ui
Labels: pr/no-changelog

#17773 changelog++
  CHANGELOG.md
Labels: pr/no-changelog

#17774 Return revocation info within existing certs/<serial> api
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_tidy_test.go
  changelog/17774.txt
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki

#17778 Use hashicorp mirror for container pulls
  builtin/credential/radius/backend_test.go
  builtin/logical/pki/zlint_test.go
  builtin/logical/rabbitmq/backend_test.go
  builtin/logical/ssh/backend_test.go
  command/server/server_seal_transit_acc_test.go
  helper/testhelpers/cassandra/cassandrahelper.go
  helper/testhelpers/consul/consulhelper.go
  helper/testhelpers/fakegcsserver/fake-gcs-server.go
  helper/testhelpers/ldap/ldaphelper.go
  helper/testhelpers/minio/miniohelper.go
  helper/testhelpers/mongodb/mongodbhelper.go
  helper/testhelpers/mysql/mysqlhelper.go
  helper/testhelpers/postgresql/postgresqlhelper.go
  physical/aerospike/aerospike_test.go
  physical/cockroachdb/cockroachdb_test.go
  physical/couchdb/couchdb_test.go
  physical/dynamodb/dynamodb_test.go
Labels: pr/no-changelog

#17780 UI: fix navbar active links
  ui/app/styles/components/popup-menu.scss
  ui/app/templates/vault/cluster.hbs
Labels: ui, pr/no-changelog

#17769 Raft Snapshot Download Bug
  changelog/17769.txt
  ui/app/components/raft-storage-overview.js
  ui/lib/service-worker-authenticated-download/service-worker-registration/index.js
  ui/tests/integration/components/raft-storage-overview-test.js
Labels: ui, bug, backport/1.11.x, backport/1.12.x

#17767 Update seal.mdx, use consistent terminology
  website/content/docs/concepts/seal.mdx
Labels: docs, core/seal, pr/no-changelog, backport/1.12.x

#17760 Docs: Update sample plugin info request
  website/content/api-docs/system/plugins-catalog.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#17787 Backport of Raft Snapshot Download Bug into release/1.12.x
  changelog/17769.txt
  ui/app/components/raft-storage-overview.js
  ui/lib/service-worker-authenticated-download/service-worker-registration/index.js
  ui/tests/integration/components/raft-storage-overview-test.js
Labels: ui, bug

#17783 Docs: Add known issue for 1.12.1 builtin plugin version upgrades
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#17786 Backport of Raft Snapshot Download Bug into release/1.11.x
  changelog/17769.txt
  ui/app/components/raft-storage-overview.js
  ui/lib/service-worker-authenticated-download/service-worker-registration/index.js
  ui/tests/integration/components/raft-storage-overview-test.js
Labels: ui, bug

#17793 Update interoperability-matrix
  website/content/docs/interoperability-matrix.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x

#17770 docs: in transit secret engine docs, specify order with batch_input param
  website/content/api-docs/secret/transit.mdx
Labels: pr/no-changelog, backport/1.12.x

#17798 Fix .go-version path in Makefile
  Makefile
Labels: pr/no-changelog

#17772 PKI - Fix order of chain building writes
  builtin/logical/pki/chain_util.go
  builtin/logical/pki/storage_migrations.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/storage_test.go
  changelog/17772.txt
  website/content/docs/secrets/pki/considerations.mdx
Labels: bug, secret/pki, backport/1.11.x, backport/1.12.x

#17804 Bump up loginMFA testhelper period and skew
  helper/testhelpers/testhelpers.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17801 core: fix start up policy loading race condition on perf standbys
  changelog/17801.txt
  vault/policy_store.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x

#17779 Add new API to PKI to list revoked certificates
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/storage.go
  changelog/17779.txt
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki

#17811 Backport of Bump up period and skew to prevent timeouts into release/1.11.x
  helper/testhelpers/testhelpers.go
Labels: pr/no-changelog

#17812 Backport of Bump up period and skew to prevent timeouts int release/1.12.x
  helper/testhelpers/testhelpers.go
Labels: pr/no-changelog

#17818 docs/vault-k8s: update env example
  website/content/docs/platform/k8s/injector/examples.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17831 1.13 preview
  CHANGELOG.md
Labels: pr/no-changelog

#17848 updated raft-autopilot to v0.2.0
  changelog/17848.txt
  go.mod
  go.sum
Labels: dependencies

#17842 Ember Security Vulnerability Patch
  ui/package.json
  ui/yarn.lock
Labels: ui, backport, pr/no-changelog

#17844 Backport of Ember Security Vulnerability Patch into release/1.12.x
  ui/package.json
  ui/yarn.lock
Labels: ui

#17846 Backport of Ember Security Vulnerability Patch into release/1.10.x
  ui/package.json
  ui/yarn.lock
Labels: ui

#17843 Fix changelog for vault-8305
  changelog/17338.txt
Labels: pr/no-changelog

#17824 Optional automatic default issuer selection
  builtin/logical/pki/config_util.go
  builtin/logical/pki/integation_test.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/storage_test.go
  changelog/17824.txt
  website/content/api-docs/secret/pki.mdx
Labels: bug, secret/pki, backport/1.11.x, backport/1.12.x

#17863 UI: update link-to-external
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/core/addon/templates/components/replication-header.hbs
  ui/lib/kmip/addon/templates/components/kmip-breadcrumb.hbs
Labels: ui, pr/no-changelog

#17860 Move from %v->%w for errs for PKI
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/config_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
Labels: secret/pki, pr/no-changelog

#17861 clarify that certain policy examples are for KVv1
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17876 Fix a typo around custom-metadata in kv put docs
  website/content/docs/commands/kv/metadata.mdx
Labels: docs, secret/kv, pr/no-changelog

#17823 Add automatic tidy of expired issuers
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  builtin/logical/pki/storage.go
  changelog/17823.txt
  website/content/api-docs/secret/pki.mdx
Labels: enhancement, secret/pki

#17882 Update interoperability-matrix.mdx
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog

#17862 clarify that init recovery options are only available for auto unseal
  website/content/api-docs/system/init.mdx
  website/content/docs/commands/operator/init.mdx
Labels: pr/no-changelog, backport/1.12.x

#17875 UI: Remove prepended pki- to new engine files
  ui/app/adapters/pki/certificate.js
  ui/app/adapters/pki/issuer.js
  ui/app/adapters/pki/key.js
  ui/app/adapters/pki/pki-certificate-engine.js
  ui/app/adapters/pki/role.js
  ui/app/models/pki/about-pki-naming.md
  ui/app/models/pki/certificate.js
  ui/app/models/pki/issuer.js
  ui/app/models/pki/key.js
  ui/app/models/pki/role.js
  ui/app/serializers/pki/certificate.js
  ui/app/serializers/pki/issuer.js
  ui/app/serializers/pki/key.js
  ui/app/serializers/pki/pki-certificate-engine.js
  ui/app/serializers/pki/pki-role-engine.js
  ui/app/serializers/pki/role.js
  ui/lib/pki/addon/components/key-parameters.hbs
  ui/lib/pki/addon/components/key-parameters.js
  ui/lib/pki/addon/components/key-usage.hbs
  ui/lib/pki/addon/components/key-usage.js
  ui/lib/pki/addon/components/role-form.hbs
  ui/lib/pki/addon/components/role-form.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/templates/roles/create.hbs
  ui/tests/integration/components/pki/key-parameters-test.js
  ui/tests/integration/components/pki/key-usage-test.js
  ui/tests/integration/components/pki/radio-select-ttl-or-string-test.js
  ui/tests/integration/components/pki/role-form-test.js
Labels: ui, pr/no-changelog

#17883 add noop ent supported storage check
  command/server.go
  command/server_util.go
Labels: pr/no-changelog, backport/1.12.x

#10299 Expose ssh algorithm_signer in web interface (#10114)
  builtin/logical/ssh/path_roles.go
  changelog/10299.txt
  ui/app/models/role-ssh.js
Labels: ui, secret/ssh

#17881 Ember Engine for Kubernetes Secrets Engine
  ui/app/router.js
  ui/lib/kubernetes/addon/engine.js
  ui/lib/kubernetes/addon/routes.js
  ui/lib/kubernetes/addon/templates/application.hbs
  ui/lib/kubernetes/config/environment.js
  ui/lib/kubernetes/index.js
  ui/lib/kubernetes/package.json
  ui/package.json
Labels: ui, pr/no-changelog

#17890 Revert "Add mount path into the default generated openapi.json spec"
  api/plugin_helpers.go
  changelog/17839.txt
  sdk/framework/backend.go
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
  sdk/framework/path.go
  sdk/framework/testdata/legacy.json
  sdk/framework/testdata/operations.json
  sdk/framework/testdata/operations_list.json
  sdk/framework/testdata/responses.json
  vault/logical_system.go
  vault/logical_system_test.go
  website/content/api-docs/system/internal-specs-openapi.mdx
Labels: pr/no-changelog

#17814 Add DataStax Astra DB to Partner DBs
  website/content/docs/plugins/plugin-portal.mdx
Labels: docs, website, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17841 VAULT-8732: Add `log-file` to Vault Agent
  .gitignore
  changelog/17841.txt
  command/agent.go
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-embedded-type.hcl
  command/agent/config/test-fixtures/config.hcl
  command/agent_test.go
  command/commands.go
  helper/logging/logfile.go
  helper/logging/logfile_test.go
  helper/logging/logger.go
  helper/logging/logger_test.go
  website/content/docs/agent/index.mdx
  website/content/docs/agent/winsvc.mdx
  website/content/docs/commands/index.mdx
Labels: agent

#17903 Update Azure 'key_type' description
  website/content/api-docs/system/managed-keys.mdx
Labels: docs, pr/no-changelog

#17866 UI: Update <a> tags to LinkTo's
  changelog/17866.txt
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/license-banners.hbs
  ui/app/templates/components/link-status.hbs
  ui/app/templates/components/namespace-link.hbs
  ui/app/templates/components/pki/config-pki-ca.hbs
  ui/app/templates/components/raft-storage-overview.hbs
  ui/app/templates/components/transform-advanced-templating.hbs
  ui/app/templates/vault.hbs
  ui/app/templates/vault/cluster/unseal.hbs
  ui/lib/core/addon/components/doc-link.js
  ui/lib/core/addon/components/external-link.hbs
  ui/lib/core/addon/components/external-link.js
  ui/lib/core/addon/components/learn-link.js
  ui/lib/core/addon/templates/components/replication-mode-summary.hbs
  ui/lib/core/addon/templates/components/replication-secondary-card.hbs
  ui/lib/core/addon/templates/components/upgrade-page.hbs
  ui/lib/core/app/components/external-link.js
Labels: ui

#17753 Added documentation for Introspection API
  website/content/api-docs/system/inspect/index.mdx
  website/content/api-docs/system/inspect/router.mdx
  website/data/api-docs-nav-data.json
Labels: docs, pr/no-changelog

#17816 plugins: Filter builtins by RunningVersion
  changelog/17816.txt
  vault/external_plugin_test.go
  vault/mount.go
Labels: backport/1.12.x

#17766 [QT-358] Unify CRT and local builder workflows
  .github/workflows/build-docs.yml
  .github/workflows/build-ensure-success.yml
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/enos-fmt.yml
  .github/workflows/enos-run.yml
  .github/workflows/enos-verify-stable.yml
  Makefile
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_local/main.tf
  enos/modules/build_local/scripts/build.sh
  enos/modules/build_local/templates/build.sh
  enos/modules/get_local_metadata/scripts/build_date.sh
  enos/modules/get_local_metadata/scripts/version.sh
  scripts/build.sh
  scripts/build_date.sh
  scripts/crt-builder.sh
  scripts/version.sh
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17930 Handle removed default issuers
  builtin/logical/pki/config_util.go
Labels: bug, secret/pki, pr/no-changelog, backport/1.12.x

#17895 Kubernetes route plumbing
  ui/app/app.js
  ui/lib/kubernetes/addon/engine.js
  ui/lib/kubernetes/addon/routes.js
  ui/lib/kubernetes/addon/routes/configuration/edit.js
  ui/lib/kubernetes/addon/routes/configuration/index.js
  ui/lib/kubernetes/addon/routes/configure.js
  ui/lib/kubernetes/addon/routes/overview.js
  ui/lib/kubernetes/addon/routes/roles/create.js
  ui/lib/kubernetes/addon/routes/roles/index.js
  ui/lib/kubernetes/addon/routes/roles/role/credentials.js
  ui/lib/kubernetes/addon/routes/roles/role/details.js
  ui/lib/kubernetes/addon/routes/roles/role/edit.js
  ui/lib/kubernetes/addon/routes/roles/role/index.js
  ui/lib/kubernetes/addon/templates/application.hbs
  ui/lib/kubernetes/addon/templates/configuration/edit.hbs
  ui/lib/kubernetes/addon/templates/configuration/index.hbs
  ui/lib/kubernetes/addon/templates/configure.hbs
  ui/lib/kubernetes/addon/templates/overview.hbs
  ui/lib/kubernetes/addon/templates/roles/create.hbs
  ui/lib/kubernetes/addon/templates/roles/index.hbs
  ui/lib/kubernetes/addon/templates/roles/role/credentials.hbs
  ui/lib/kubernetes/addon/templates/roles/role/details.hbs
  ui/lib/kubernetes/addon/templates/roles/role/edit.hbs
Labels: ui, pr/no-changelog

#17933 Update api-doc about PKI automatic tidying of issuers and the default issuer
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog

#17928 Move pki docker tests to pkiext
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/integation_test.go
  builtin/logical/pki/ocsp_test.go
  builtin/logical/pki/path_manage_keys_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/path_tidy_test.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/storage_test.go
  builtin/logical/pki/test_helpers.go
  builtin/logical/pkiext/README.md
  builtin/logical/pkiext/zlint_test.go
  command/secrets_enable_test.go
Labels: bug, secret/pki, pr/no-changelog

#17916 Docs clarifications around PKI considerations
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.12.x

#17927 UI: Add Typescript for PKI engine
  changelog/17927.txt
  ui/app/config/environment.d.ts
  ui/app/models/pki/role.js
  ui/lib/core/addon/components/checkbox-grid.hbs
  ui/lib/core/addon/components/checkbox-grid.ts
  ui/lib/core/app/components/checkbox-grid.js
  ui/lib/core/package.json
  ui/lib/pki/addon/components/key-usage.hbs
  ui/lib/pki/addon/components/key-usage.js
  ui/lib/pki/addon/components/key-usage.ts
  ui/lib/pki/package.json
  ui/package.json
  ui/tests/helpers/pki-engine.js
  ui/tests/integration/components/checkbox-grid-test.js
  ui/tests/integration/components/pki/key-usage-test.js
  ui/tsconfig.json
  ui/types/ember-data/types/registries/model.d.ts
  ui/types/forms.ts
  ui/types/global.d.ts
  ui/types/vault/index.d.ts
  ui/yarn.lock
Labels: ui

#17327 Fix link to architecture in AWS platform page
  website/content/docs/platform/aws/index.mdx
Labels: docs, pr/no-changelog

#17917 enos: use amd64 for consul backend
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17765 Vault-8306 User Lockout RPCs oss changes
  vault/core.go
  vault/mount.go
  vault/request_handling.go
  vault/request_handling_util.go
Labels: pr/no-changelog

#17957 Clarify more documentation on audit logging.
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.12.x

#17750 PKI Health Check Command
  api/logical.go
  changelog/17750.txt
  command/commands.go
  command/healthcheck/common.go
  command/healthcheck/pki.go
  command/healthcheck/pki_ca_validity_period.go
  command/healthcheck/pki_crl_validity_period.go
  command/healthcheck/util.go
  command/pki_health_check.go
  command/pki_health_check_test.go
Labels: enhancement, secret/pki, command

#17958 Fix docs by adding self-closing BRs
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, bug, secret/pki, pr/no-changelog

#17959 Add missing anchor for set-crl-configuration
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.12.x

#17825 Docker Deprecation Update
  website/content/docs/deprecation/index.mdx
Labels: pr/no-changelog

#17952 dockerfile: ubi-minimal:8.6 => 8.7
  Dockerfile
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17968 removing setup-go in build.yml as it is unnecessary
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17653 Migrate package_manager smoke test to Enos scenario
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/vault-verify-replication/main.tf
  enos/modules/vault-verify-replication/templates/smoke-verify-replication.sh
  enos/modules/vault-verify-replication/variables.tf
  enos/modules/vault-verify-ui/main.tf
  enos/modules/vault-verify-ui/templates/smoke-verify-ui.sh
  enos/modules/vault-verify-ui/variables.tf
  enos/modules/vault-verify-write-data/main.tf
  enos/modules/vault-verify-write-data/templates/smoke-enable-secrets-kv.sh
  enos/modules/vault-verify-write-data/templates/smoke-write-test-data.sh
  enos/modules/vault-verify-write-data/variables.tf
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
  enos/modules/vault_artifactory_artifact/variables.tf
  enos/modules/vault_upgrade/main.tf
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17865 Add hardware_backed_root, root_issued_leaves health checks
  command/healthcheck/pki.go
  command/healthcheck/pki_hardware_backed_root.go
  command/healthcheck/pki_root_issued_leaves.go
  command/pki_health_check.go
Labels: enhancement, secret/pki, pr/no-changelog

#17950 UI: fixes link from to show page from entity policies list
  changelog/17950.txt
  ui/app/templates/components/identity/item-policies.hbs
Labels: ui, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17986 cherry pick original commit
  changelog/17950.txt
  ui/app/templates/components/identity/item-policies.hbs
Labels: ui, bug

#17981 Backport of UI: fixes link from to show page from entity policies list into release/1.11.x
  changelog/17950.txt
  ui/app/templates/components/identity/item-policies.hbs
Labels: ui, bug

#17982 Backport of UI: fixes link from to show page from entity policies list into release/1.12.x
  changelog/17950.txt
  ui/app/templates/components/identity/item-policies.hbs
Labels: ui, bug

#17914 Deduplicate policies prior to generating ACL on request
  changelog/17914.txt
  vault/request_handling.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x

#17989 Fix path typo in Generate Intermediate CSR PKI docs
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.11.x, backport/1.12.x

#17996 fixing a typo in command login
  command/login.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#17983 Remove unfinished "vault server -diagnose" flag
  command/commands.go
  command/operator_diagnose.go
  command/server.go
Labels: pr/no-changelog

#17984 Fix semgrep false-positive due to co-dependent returns
  command/healthcheck/pki_ca_validity_period.go
  command/healthcheck/pki_crl_validity_period.go
  command/healthcheck/pki_hardware_backed_root.go
  command/healthcheck/pki_root_issued_leaves.go
Labels: bug, pr/no-changelog

#18007 Docs: Enterprise TOTP updates
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/mfa/mfa-totp.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18010 Kubernetes Models, Adapters and Serializers
  ui/app/adapters/kubernetes/config.js
  ui/app/adapters/kubernetes/role.js
  ui/app/decorators/model-form-fields.js
  ui/app/models/kubernetes/config.js
  ui/app/models/kubernetes/role.js
  ui/app/serializers/kubernetes/config.js
  ui/app/serializers/kubernetes/role.js
  ui/tests/unit/adapters/kubernetes/config-test.js
  ui/tests/unit/adapters/kubernetes/role-test.js
  ui/tests/unit/decorators/model-form-fields-test.js
Labels: ui

#17943 Kubernetes Mirage Setup
  ui/mirage/factories/kubernetes-config.js
  ui/mirage/factories/kubernetes-role.js
  ui/mirage/handlers/index.js
  ui/mirage/handlers/kubernetes.js
Labels: ui

#17915 [QT-309] Ensure environment variables are populated before proceeding
  builtin/credential/okta/backend_test.go
  command/agent/alicloud_end_to_end_test.go
  command/agent/aws_end_to_end_test.go
  helper/testhelpers/testhelpers.go
  plugins/database/redshift/redshift_test.go
Labels: pr/no-changelog

#17949 [QT-309] Resolve AWS config before testing ACC
  builtin/logical/aws/backend_test.go
  go.mod
Labels: pr/no-changelog

#18018 certutil.ParseHexFormatted fails parsing 80 hex and above
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
Labels: bug, pr/no-changelog

#17877 Add role-based health checks to PKI Health Check
  command/healthcheck/pki.go
  command/healthcheck/pki_role_allows_glob_wildcards.go
  command/healthcheck/pki_role_allows_localhost.go
  command/healthcheck/pki_role_no_store_false.go
  command/pki_health_check.go
  command/pki_health_check_test.go
Labels: enhancement, secret/pki, pr/no-changelog

#17712 Add docs for vault-k8s JSON patch
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: pr/no-changelog, backport/1.12.x

#18019 VAULT-7707 OSS portion of changes
  vault/quotas/quotas.go
Labels: pr/no-changelog

#17813 Add new PKI api to combine and sign different CRLs from the same issuer
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_resign_crls.go
  builtin/logical/pki/path_resign_crls_test.go
  builtin/logical/pki/test_helpers.go
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki

#18023 add draft 1.13.x upgrade guide
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#18020 docs/vault-k8s: updates for v1.1.0
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/index.mdx
Labels: pr/no-changelog, backport/1.12.x

#17988 PSP-256 - Add security-scanner tool
  .github/workflows/security-scan.yml
  scan.hcl
  tools/semgrep/ci/no-nil-check.yml
  tools/semgrep/ci/return-nil.yml
Labels: pr/no-changelog

#17997 UI: Pki engine (redesign) routing changes
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/lib/pki/addon/components/pki-key-parameters.js
  ui/lib/pki/addon/components/pki-key-usage.hbs
  ui/lib/pki/addon/components/pki-key-usage.ts
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/components/pki-role-form.js
  ui/lib/pki/addon/routes.js
  ui/lib/pki/addon/routes/certificates/certificate/details.js
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/configuration.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/routes/configuration/create/generate-csr.js
  ui/lib/pki/addon/routes/configuration/create/generate-root.js
  ui/lib/pki/addon/routes/configuration/create/import-ca.js
  ui/lib/pki/addon/routes/configuration/create/index.js
  ui/lib/pki/addon/routes/configuration/details.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/issuers/generate-intermediate.js
  ui/lib/pki/addon/routes/issuers/generate-root.js
  ui/lib/pki/addon/routes/issuers/import.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js
  ui/lib/pki/addon/routes/issuers/issuer/details.js
  ui/lib/pki/addon/routes/issuers/issuer/edit.js
  ui/lib/pki/addon/routes/issuers/issuer/sign.js
  ui/lib/pki/addon/routes/keys/create.js
  ui/lib/pki/addon/routes/keys/generate.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/keys/key/details.js
  ui/lib/pki/addon/routes/keys/key/edit.js
  ui/lib/pki/addon/routes/roles/role/details.js
  ui/lib/pki/addon/routes/roles/role/edit.js
  ui/lib/pki/addon/routes/roles/role/generate.js
  ui/lib/pki/addon/routes/roles/role/sign.js
  ui/lib/pki/addon/templates/certificates/certificate/details.hbs
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/lib/pki/addon/templates/configuration.hbs
  ui/lib/pki/addon/templates/configuration/create.hbs
  ui/lib/pki/addon/templates/configuration/create/generate-csr.hbs
  ui/lib/pki/addon/templates/configuration/create/generate-root.hbs
  ui/lib/pki/addon/templates/configuration/create/import-ca.hbs
  ui/lib/pki/addon/templates/configuration/create/index.hbs
  ui/lib/pki/addon/templates/configuration/details.hbs
  ui/lib/pki/addon/templates/issuers/generate-intermediate.hbs
  ui/lib/pki/addon/templates/issuers/generate-root.hbs
  ui/lib/pki/addon/templates/issuers/import.hbs
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/issuers/issuer/cross-sign.hbs
  ui/lib/pki/addon/templates/issuers/issuer/details.hbs
  ui/lib/pki/addon/templates/issuers/issuer/edit.hbs
  ui/lib/pki/addon/templates/issuers/issuer/sign.hbs
  ui/lib/pki/addon/templates/keys/create.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/lib/pki/addon/templates/roles/create.hbs
  ui/lib/pki/addon/templates/roles/role/generate.hbs
  ui/lib/pki/addon/templates/roles/role/sign.hbs
  ui/tests/integration/components/pki/pki-key-parameters-test.js
  ui/tests/integration/components/pki/pki-key-usage-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog

#17799 Docs: Clarify plugin versioning known issue
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#17976 Backport of Migrate package_manager smoke test to Enos scenario into release/1.10.x
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/vault-verify-replication/main.tf
  enos/modules/vault-verify-replication/templates/smoke-verify-replication.sh
  enos/modules/vault-verify-replication/variables.tf
  enos/modules/vault-verify-ui/main.tf
  enos/modules/vault-verify-ui/templates/smoke-verify-ui.sh
  enos/modules/vault-verify-ui/variables.tf
  enos/modules/vault-verify-write-data/main.tf
  enos/modules/vault-verify-write-data/templates/smoke-enable-secrets-kv.sh
  enos/modules/vault-verify-write-data/templates/smoke-write-test-data.sh
  enos/modules/vault-verify-write-data/variables.tf
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
  enos/modules/vault_artifactory_artifact/variables.tf
  enos/modules/vault_upgrade/main.tf
Labels: pr/no-changelog

#17977 Backport of Migrate package_manager smoke test to Enos scenario into release/1.11.x
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/vault-verify-replication/main.tf
  enos/modules/vault-verify-replication/templates/smoke-verify-replication.sh
  enos/modules/vault-verify-replication/variables.tf
  enos/modules/vault-verify-ui/main.tf
  enos/modules/vault-verify-ui/templates/smoke-verify-ui.sh
  enos/modules/vault-verify-ui/variables.tf
  enos/modules/vault-verify-write-data/main.tf
  enos/modules/vault-verify-write-data/templates/smoke-enable-secrets-kv.sh
  enos/modules/vault-verify-write-data/templates/smoke-write-test-data.sh
  enos/modules/vault-verify-write-data/variables.tf
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
  enos/modules/vault_artifactory_artifact/variables.tf
  enos/modules/vault_upgrade/main.tf
Labels: pr/no-changelog

#17978 Backport of Migrate package_manager smoke test to Enos scenario into release/1.12.x
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/artifactory-oss.json
  .github/enos-run-matrices/crt-ent.json
  .github/enos-run-matrices/crt-oss.json
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_crt/main.tf
  enos/modules/build_local/main.tf
  enos/modules/vault-verify-replication/main.tf
  enos/modules/vault-verify-replication/templates/smoke-verify-replication.sh
  enos/modules/vault-verify-replication/variables.tf
  enos/modules/vault-verify-ui/main.tf
  enos/modules/vault-verify-ui/templates/smoke-verify-ui.sh
  enos/modules/vault-verify-ui/variables.tf
  enos/modules/vault-verify-write-data/main.tf
  enos/modules/vault-verify-write-data/templates/smoke-enable-secrets-kv.sh
  enos/modules/vault-verify-write-data/templates/smoke-write-test-data.sh
  enos/modules/vault-verify-write-data/variables.tf
  enos/modules/vault_artifactory_artifact/locals.tf
  enos/modules/vault_artifactory_artifact/main.tf
  enos/modules/vault_artifactory_artifact/variables.tf
  enos/modules/vault_upgrade/main.tf
Labels: pr/no-changelog

#18037 Backport 1.10: VAULT-7707 OSS portion of changes (#18019)
  vault/quotas/quotas.go
Labels: pr/no-changelog

#18036 Backport 1.11: VAULT-7707 OSS portion of changes (#18019)
  vault/quotas/quotas.go
Labels: pr/no-changelog

#17901 Add auto-tidy, last-tidy, and leaf cert health checks
  command/healthcheck/pki.go
  command/healthcheck/pki_enable_auto_tidy.go
  command/healthcheck/pki_tidy_last_run.go
  command/healthcheck/pki_too_many_certs.go
  command/pki_health_check.go
Labels: enhancement, secret/pki, pr/no-changelog

#18015 docs: detail policies parameter for auth methods using tokenutil
  website/content/docs/concepts/policies.mdx
  website/content/partials/tokenfields.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18043 Add list to cert auth's CRLs
  builtin/credential/cert/backend.go
  builtin/credential/cert/backend_test.go
  builtin/credential/cert/path_crls.go
  changelog/18043.txt
  website/content/api-docs/auth/cert.mdx
Labels: enhancement, auth/cert

#18030 storage/raft: Add retry_join_as_non_voter config option
  changelog/18030.txt
  physical/raft/raft.go
  physical/raft/raft_test.go
  vault/raft.go
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/configuration/storage/raft.mdx
Labels: docs, storage/raft, website, backport/1.12.x

#18017 Rename PKI health check helpers
  command/healthcheck/pki.go
  command/healthcheck/pki_ca_validity_period.go
  command/healthcheck/pki_crl_validity_period.go
  command/healthcheck/pki_hardware_backed_root.go
  command/healthcheck/pki_role_allows_glob_wildcards.go
  command/healthcheck/pki_role_allows_localhost.go
  command/healthcheck/pki_role_no_store_false.go
  command/healthcheck/pki_root_issued_leaves.go
  command/healthcheck/pki_too_many_certs.go
Labels: secret/pki, pr/no-changelog

#18049 Update MFA docs
  website/content/docs/auth/login-mfa/index.mdx
Labels: pr/no-changelog, backport/1.12.x

#18045 UI: Create .gitignore file on postBuild
  ui/lib/keep-gitkeep/index.js
  ui/lib/keep-gitkeep/package.json
  ui/package.json
Labels: ui, pr/no-changelog, devex

#17998 [QT-353] Use a different approach to branch restrictions
  .github/workflows/build-docs.yml
  .github/workflows/build-ensure-success.yml
  .github/workflows/build.yml
Labels: pr/no-changelog

#18057 [QT-353] Use a different approach to branch restrictions (#17998)
  .github/workflows/build-docs.yml
  .github/workflows/build-ensure-success.yml
  .github/workflows/build.yml
Labels: pr/no-changelog

#17749 UI: Implement new policy SS + modal designs
  changelog/17749.txt
  ui/app/components/modal-form/FYI.md
  ui/app/components/modal-form/oidc-assignment-template.hbs
  ui/app/components/modal-form/oidc-assignment-template.js
  ui/app/components/modal-form/policy-template.hbs
  ui/app/components/modal-form/policy-template.js
  ui/app/components/oidc/assignment-form.js
  ui/app/components/oidc/client-form.js
  ui/app/components/policy-form.hbs
  ui/app/components/policy-form.js
  ui/app/components/ui-wizard.js
  ui/app/controllers/vault/cluster/policies/create.js
  ui/app/controllers/vault/cluster/policy/edit.js
  ui/app/mixins/policy-edit-controller.js
  ui/app/models/identity/entity.js
  ui/app/models/identity/group.js
  ui/app/routes/vault/cluster/policy/edit.js
  ui/app/routes/vault/cluster/policy/show.js
  ui/app/styles/components/modal.scss
  ui/app/templates/components/identity/edit-form.hbs
  ui/app/templates/components/oidc/assignment-form.hbs
  ui/app/templates/components/oidc/client-form.hbs
  ui/app/templates/components/ui-wizard.hbs
  ui/app/templates/components/wizard/policies-delete.hbs
  ui/app/templates/components/wizard/policies-details.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/assignment/edit.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/create.hbs
  ui/app/templates/vault/cluster/policies/create.hbs
  ui/app/templates/vault/cluster/policy/edit.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/components/search-select-with-modal.js
  ui/lib/core/addon/components/search-select.hbs
  ui/lib/core/addon/templates/components/select.hbs
  ui/tests/acceptance/oidc-config/clients-assignments-test.js
  ui/tests/acceptance/policies-acl-old-test.js
  ui/tests/integration/components/oidc/assignment-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/policy-form-test.js
  ui/tests/integration/components/search-select-with-modal-test.js
Labels: ui

#18059 [QT-353] Use a different approach to branch restrictions (#17998)
  .github/workflows/build-docs.yml
  .github/workflows/build-ensure-success.yml
  .github/workflows/build.yml
Labels: pr/no-changelog

#18058 [QT-353] Use a different approach to branch restrictions (#17998)
  .github/workflows/build-docs.yml
  .github/workflows/build-ensure-success.yml
  .github/workflows/build.yml
Labels: pr/no-changelog

#18063 mention Consul Dataplane compat in 1.13.x upgrade notes
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/partials/consul-dataplane-upgrade-note.mdx
Labels: pr/no-changelog

#17985 UI: PKI Read Role Details
  ui/.eslintignore
  ui/app/adapters/pki/role.js
  ui/app/models/pki/role.js
  ui/lib/pki/addon/components/pki-role-details-page.hbs
  ui/lib/pki/addon/components/pki-role-details-page.ts
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/routes/roles/role/details.js
  ui/lib/pki/addon/templates/roles/role/details.hbs
  ui/lib/pki/package.json
  ui/tests/helpers/pki/page-role-details.js
  ui/tests/integration/components/pki/page-role-detail-test.js
  ui/tsconfig.json
Labels: ui, pr/no-changelog

#18070 Remove ENOS autopilot tests from 1.10.x branch
  .github/enos-run-matrices/artifactory-ent.json
  .github/enos-run-matrices/crt-ent.json
Labels: pr/no-changelog

#18069 UI: refactor pki role form to reuse PkiKeyParameters component
  ui/app/models/pki/role.js
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/lib/pki/addon/components/pki-key-parameters.js
  ui/lib/pki/addon/components/pki-key-usage.hbs
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/tests/integration/components/pki/pki-key-parameters-test.js
  ui/tests/integration/components/pki/pki-key-usage-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog

#18066 mention Consul Dataplane compat in 1.12.x upgrade notes
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
Labels: pr/no-changelog, backport/1.12.x

#18041 Add Consul Dataplane compatibility info to docs
  website/content/api-docs/secret/consul.mdx
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/secrets/consul.mdx
  website/content/partials/consul-dataplane-compat.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18077 website: restrict node engines to <= 16.x
  website/package.json
Labels: pr/no-changelog, backport/1.12.x

#17902 Add mount tuning health checks
  command/healthcheck/pki_allow_if_modified_since.go
  command/healthcheck/pki_audit_visibility.go
  command/healthcheck/shared.go
  command/pki_health_check.go
Labels: enhancement, secret/pki, pr/no-changelog

#18078 add missing consul dataplane partial
  website/content/partials/consul-dataplane-upgrade-note.mdx
Labels: pr/no-changelog

#18040 New PKI API to generate and sign a CRL based on input data
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_resign_crls.go
  builtin/logical/pki/path_resign_crls_test.go
  changelog/18040.txt
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki

#18083 add Consul Dataplane compatibility block
  website/content/api-docs/secret/consul.mdx
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/secrets/consul.mdx
  website/content/partials/consul-dataplane-compat.mdx
Labels: pr/no-changelog

#18082 add Consul Dataplane compatibility block
  website/content/api-docs/secret/consul.mdx
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/secrets/consul.mdx
  website/content/partials/consul-dataplane-compat.mdx
Labels: pr/no-changelog

#18090 update semgrep excludes in security scan
  .github/workflows/security-scan.yml
  scan.hcl
Labels: pr/no-changelog

#17932 Use generate endpoint instead of admin-generate during MFA setup
  changelog/17932.txt
  ui/app/adapters/mfa-setup.js
  ui/app/components/mfa/mfa-setup-step-one.js
  ui/app/templates/vault/cluster/mfa-setup.hbs
  ui/tests/acceptance/mfa-setup-test.js
Labels: auth/mfa

#18096 Various health check improvements + tests
  command/healthcheck/healthcheck.go
  command/healthcheck/pki.go
  command/healthcheck/pki_allow_if_modified_since.go
  command/healthcheck/pki_audit_visibility.go
  command/healthcheck/pki_enable_auto_tidy.go
  command/healthcheck/pki_role_allows_glob_wildcards.go
  command/healthcheck/pki_role_allows_localhost.go
  command/healthcheck/pki_role_no_store_false.go
  command/healthcheck/pki_root_issued_leaves.go
  command/healthcheck/pki_tidy_last_run.go
  command/pki_health_check_test.go
Labels: bug, secret/pki, command, pr/no-changelog

#17630 Create CSR in Transit, sign with PKI
  builtin/logical/transit/backend_test.go
Labels: secret/transit, pr/no-changelog

#18051 Remove pinned builtin plugin versions from storage
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_config_connection_test.go
  builtin/logical/database/path_rotate_credentials.go
  builtin/logical/database/version_wrapper.go
  changelog/18051.txt
  helper/versions/version.go
  helper/versions/version_test.go
  vault/auth.go
  vault/logical_system.go
  vault/logical_system_test.go
  vault/mount.go
  vault/mount_test.go
  vault/plugin_catalog.go
  vault/plugin_catalog_test.go
  vault/testing.go
Labels: core/plugin, ecosystem/plugin, backport/1.12.x

#18087 UI: Pki key read view
  ui/app/adapters/pki/key.js
  ui/app/models/pki/key.js
  ui/app/serializers/pki/key.js
  ui/lib/pki/addon/components/pki-key-details.hbs
  ui/lib/pki/addon/components/pki-key-details.ts
  ui/lib/pki/addon/controllers/issuers/index.js
  ui/lib/pki/addon/controllers/keys/index.js
  ui/lib/pki/addon/routes.js
  ui/lib/pki/addon/routes/keys/key.js
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/keys/key/details.hbs
Labels: ui, pr/no-changelog

#17320 Add pki nginx/wget/curl/Go integration tests
  builtin/logical/pki/integration_test.go
  builtin/logical/pkiext/nginx_test.go
  builtin/logical/pkiext/test_helpers.go
  builtin/logical/pkiext/zlint_test.go
  helper/testhelpers/docker/testhelpers.go
Labels: secret/pki, test, pr/no-changelog

#18107 Sideport Error Message Util
  ui/app/utils/error-message.js
Labels: ui, pr/no-changelog

#18115 Sideport RadioCard v2
  ui/app/styles/components/radio-card.scss
  ui/app/templates/components/oidc/client-form.hbs
  ui/app/templates/components/oidc/key-form.hbs
  ui/app/templates/components/oidc/provider-form.hbs
  ui/lib/core/addon/components/radio-card.hbs
  ui/lib/core/app/components/radio-card.js
  ui/tests/acceptance/oidc-config/clients-assignments-test.js
  ui/tests/acceptance/oidc-config/clients-keys-test.js
  ui/tests/acceptance/oidc-config/providers-scopes-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/oidc/key-form-test.js
  ui/tests/integration/components/oidc/provider-form-test.js
Labels: ui, pr/no-changelog

#18103 Sideport Model Form Fields Decorator
  ui/app/decorators/model-form-fields.js
  ui/tests/unit/decorators/model-form-fields-test.js
Labels: ui, pr/no-changelog

#17447 Add crl integraiton to tests
  builtin/logical/pkiext/nginx_test.go
  builtin/logical/pkiext/test_helpers.go
Labels: secret/pki, test, pr/no-changelog

#17979 VAULT-9427: Add read support to `sys/loggers` endpoints
  changelog/17979.txt
  helper/logging/logger.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  website/content/api-docs/system/loggers.mdx
Labels: backport/1.11.x, backport/1.12.x

#18130 Clarify that cluster_id differs between PR Primary/Secondary clusters
  website/content/api-docs/system/replication/replication-performance.mdx
Labels: docs, core/replication, pr/no-changelog

#17836 Make the error and http code clearer when supplying wrong unseal key
  changelog/17836.txt
  http/sys_seal_test.go
  vault/core.go
  vault/seal.go
Labels: core/seal

#18131 Docs: vault-helm 0.23.0 updates
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x

#18031 VAULT-9900: Log rotation for 'agent' and 'server' commands
  changelog/18031.txt
  command/agent.go
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent_test.go
  command/commands.go
  command/log_flags.go
  command/log_flags_test.go
  command/server.go
  helper/logging/logfile.go
  helper/logging/logfile_test.go
  helper/logging/logger.go
  helper/logging/logger_test.go
  internalshared/configutil/config.go
  internalshared/configutil/merge.go
  website/content/docs/agent/index.mdx
  website/content/docs/commands/index.mdx
  website/content/docs/commands/server.mdx
  website/content/docs/configuration/index.mdx
Labels: docs, agent, core/log, core/client, backport/1.11.x, backport/1.12.x

#18112 UI: Use typescript linter and parser
  ui/.eslintrc.js
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog

#17835 ui: mfa: use proper request id generation
  changelog/17835.txt
  ui/mirage/handlers/mfa-login.js
Labels: ui, auth/mfa

#18134 Update nomad.mdx
  website/content/docs/secrets/nomad.mdx
Labels: pr/no-changelog

#18113 UI: pki engine breadcrumbs
  ui/lib/core/addon/components/page/breadcrumbs.hbs
  ui/lib/core/addon/components/page/breadcrumbs.js
  ui/lib/core/app/components/page/breadcrumbs.js
  ui/lib/pki/addon/components/pki-key-details.hbs
  ui/lib/pki/addon/components/pki-key-details.ts
  ui/lib/pki/addon/components/pki-role-details-page.hbs
  ui/lib/pki/addon/components/pki-role-details-page.ts
  ui/lib/pki/addon/controllers/certificates/index.js
  ui/tests/helpers/pki/page-role-details.js
  ui/tests/integration/components/page/breadcrumbs-test.js
Labels: ui, pr/no-changelog

#18140 VAULT-11786 OSS changes for potential deadlock issue
  vault/expiration.go
Labels: pr/no-changelog

#18141 Disable nginx integration test in pki test suites
  builtin/logical/pkiext/nginx_test.go
Labels: pr/no-changelog

#18038 Create global quotas of each type in every NewTestCluster.
  command/agent_test.go
  command/server.go
  helper/locking/deadlock.go
  helper/locking/lock.go
  http/forwarded_for_test.go
  http/handler.go
  http/testing.go
  vault/core.go
  vault/expiration.go
  vault/external_tests/quotas/quotas_test.go
  vault/quotas/quotas.go
  vault/testing.go
Labels: pr/no-changelog

#17907 [QT-318] Add Vault CI bootstrap scenarios
  .github/workflows/enos-bootstrap-ci.yml
  .gitignore
  enos/README.md
  enos/ci/bootstrap/main.tf
  enos/ci/bootstrap/outputs.tf
  enos/ci/bootstrap/variables.tf
  enos/ci/service-user-iam/main.tf
  enos/ci/service-user-iam/outputs.tf
  enos/ci/service-user-iam/variables.tf
Labels: pr/no-changelog

#18121 Add stack trace to audit logging panic recovery
  changelog/18121.txt
  vault/audit_broker.go
  vault/request_forwarding_rpc.go
Labels: core/audit, core/log, backport/1.12.x

#18169 Update SDK to 1.10.10
  sdk/version/version_base.go
Labels: pr/no-changelog

#18171 Updated changelogs from 'feature' to 'improvement'
  changelog/17841.txt
  changelog/18031.txt
Labels: docs, pr/no-changelog

#18172 Update SDK version to 1.11.7
  sdk/version/version_base.go
Labels: pr/no-changelog

#18175 Update go.mod to use latest 1.11.7 SDK release
  go.mod
Labels: pr/no-changelog

#18149 Add doc for AWS XKS Proxy with PKCS#11 Provider
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, backport/1.12.x

#18147 Kubernetes Configuration View
  ui/app/app.js
  ui/app/styles/core/helpers.scss
  ui/lib/kubernetes/addon/components/config-cta.hbs
  ui/lib/kubernetes/addon/components/page/configuration.hbs
  ui/lib/kubernetes/addon/components/tab-page-header.hbs
  ui/lib/kubernetes/addon/engine.js
  ui/lib/kubernetes/addon/routes.js
  ui/lib/kubernetes/addon/routes/configuration.js
  ui/lib/kubernetes/addon/routes/configuration/edit.js
  ui/lib/kubernetes/addon/routes/configuration/index.js
  ui/lib/kubernetes/addon/templates/configuration.hbs
  ui/lib/kubernetes/addon/templates/configuration/edit.hbs
  ui/lib/kubernetes/addon/templates/configuration/index.hbs
  ui/mirage/factories/kubernetes-config.js
  ui/mirage/factories/kubernetes-role.js
  ui/mirage/scenarios/default.js
  ui/tests/integration/components/kubernetes/config-cta-test.js
  ui/tests/integration/components/kubernetes/page/configuration-test.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
  ui/tests/integration/components/kubernetes/tab-page-header-test.js
Labels: ui
