Repository hashicorp/vault, pull requests merged in 2023-06, with the labels that each got.

#20895 Backport of agent: Don't print errors on exit 0 in supervisor mode into release/1.14.x
  command/agent.go
Labels: pr/no-changelog

#20911 New helper methods for generating readable loggable strings
  sdk/helper/testhelpers/output.go
  sdk/helper/testhelpers/output_test.go
Labels: pr/no-changelog, pr/no-milestone

#20916 UI: Scroll to top after PKI form save
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.ts
  ui/lib/pki/addon/components/pki-import-pem-bundle.ts
  ui/lib/pki/addon/components/pki-sign-intermediate-form.ts
Labels: ui, pr/no-changelog, backport/1.14.x

#20928 Backport of Remove transform from the transit key import cli help text into release/1.14.x
  command/transit.go
  command/transit_import_key.go
  command/transit_import_key_version.go
Labels: pr/no-changelog

#20924 Add more parallelism to raft tests.
  vault/external_tests/raft/raft_autopilot_test.go
  vault/external_tests/raft/raft_test.go
Labels: pr/no-changelog, pr/no-milestone

#20926 Escape the ACME eab key in the certbot command line within integration tests
  builtin/logical/pkiext/pkiext_binary/acme_test.go
Labels: pr/no-changelog, backport/1.14.x

#20929 Backport of UI: Scroll to top after PKI form save into release/1.14.x
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.ts
  ui/lib/pki/addon/components/pki-import-pem-bundle.ts
  ui/lib/pki/addon/components/pki-sign-intermediate-form.ts
Labels: ui, backport, pr/no-changelog

#20932 Backport of agent: Don't restart process unless environment variables changed into release/1.14.x
  command/agent/exec/exec.go
Labels: pr/no-changelog

#20914 Fix order, authorization, challenge status when failing to validate a challenge
  builtin/logical/pki/acme_challenge_engine.go
  builtin/logical/pki/acme_errors.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
Labels: secret/pki, pr/no-changelog, backport/1.14.x

#20931 Backport of Escape the ACME eab key in the certbot command line within integration tests into release/1.14.x
  builtin/logical/pkiext/pkiext_binary/acme_test.go
Labels: pr/no-changelog

#20921 Backport 1.13.x: UI: fixes pki role editing changing to default key parameter values
  changelog/20907.txt
  ui/app/models/pki/role.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/helpers/loose-equal.js
  ui/lib/core/app/helpers/loose-equal.js
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/integration/helpers/loose-equal-test.js
Labels: ui, backport, bug

#20920 Backport of UI: fixes pki role editing changing to default key parameter values into release/1.14.x
  changelog/20907.txt
  ui/app/models/pki/role.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/helpers/loose-equal.js
  ui/lib/core/app/helpers/loose-equal.js
  ui/lib/pki/addon/components/pki-key-parameters.hbs
  ui/lib/pki/addon/components/pki-key-parameters.ts
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/integration/helpers/loose-equal-test.js
  ui/types/vault/models/pki/role.d.ts
Labels: ui, backport

#20918 agent: Allow for a 'cache' stanza in environment template configuration
  command/agent.go
  command/agent/config/config.go
  command/agent/config/test-fixtures/config-env-templates-complex.hcl
Labels: pr/no-changelog, backport/1.14.x

#20941 LDAP Secrets Engine Header Component
  ui/app/models/secret-engine.js
  ui/lib/ldap/addon/components/tab-page-header.hbs
  ui/tests/integration/components/ldap/tab-page-header-test.js
Labels: ui, pr/no-changelog

#20935 Change from default_role to default_directory_policy
  builtin/logical/pki/acme_wrappers.go
  builtin/logical/pki/path_config_acme.go
  website/content/api-docs/secret/pki.mdx
Labels: pr/no-changelog, backport/1.14.x

#20942 UI: pki only render unable to parse banner on issuer details page
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.ts
  ui/lib/pki/addon/components/parsed-certificate-info-rows.hbs
  ui/lib/pki/addon/components/parsed-certificate-info-rows.ts
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
Labels: ui, pr/no-changelog, backport/1.14.x

#20940 agent: Prevent multiple restarts of child process in supervisor mode
  command/agent/exec/exec.go
  command/agent/exec/exec_test.go
Labels: pr/no-changelog, backport/1.14.x

#20949 Backport of agent: Prevent multiple restarts of child process in supervisor mode into release/1.14.x
  command/agent/exec/exec.go
  command/agent/exec/exec_test.go
Labels: pr/no-changelog

#20948 Backport of UI: pki only render unable to parse banner on issuer details page into release/1.14.x
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.ts
  ui/lib/pki/addon/components/parsed-certificate-info-rows.hbs
  ui/lib/pki/addon/components/parsed-certificate-info-rows.ts
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
Labels: ui, backport, pr/no-changelog

#20939 Backport of agent: Allow for a 'cache' stanza in environment template configuration into release/1.14.x
  command/agent.go
  command/agent/config/config.go
  command/agent/config/test-fixtures/config-env-templates-complex.hcl
Labels: pr/no-changelog

#20944 UI: add pki/config/acme, fix pki/configcluster save bug
  ui/app/adapters/pki/config/acme.js
  ui/app/models/pki/config/acme.js
  ui/app/models/pki/config/cluster.js
  ui/app/models/pki/config/urls.js
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.ts
  ui/lib/pki/addon/routes/application.js
  ui/lib/pki/addon/routes/configuration.js
  ui/lib/pki/addon/routes/configuration/edit.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/templates/configuration/edit.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/page/pki-configuration-edit.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
  website/content/api-docs/secret/pki.mdx
Labels: ui, backport/1.14.x

#20951 Backport of UI: add pki/config/acme, fix pki/configcluster save bug into release/1.14.x
  ui/app/adapters/pki/config/acme.js
  ui/app/models/pki/config/acme.js
  ui/app/models/pki/config/cluster.js
  ui/app/models/pki/config/urls.js
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.ts
  ui/lib/pki/addon/routes/application.js
  ui/lib/pki/addon/routes/configuration.js
  ui/lib/pki/addon/routes/configuration/edit.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/templates/configuration/edit.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/page/pki-configuration-edit.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
  website/content/api-docs/secret/pki.mdx
Labels: ui, pr/no-changelog

#20930 Deflake TestActivityLog_MultipleFragmentsAndSegments
  vault/activity_log.go
  vault/activity_log_test.go
  vault/logical_system_test.go
  vault/testing.go
Labels: pr/no-changelog, pr/no-milestone

#20950 agent: Fix bug with early exits during restarts in supervisor mode
  command/agent/exec/exec.go
Labels: pr/no-changelog, backport/1.14.x

#20954 Backport of agent: Fix bug with early exits during restarts in supervisor mode into release/1.14.x
  command/agent/exec/exec.go
Labels: pr/no-changelog

#20898 Automatic license utilization reporting
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x

#20952 Clarify vault helm upgrade instructions in HA mode
  website/content/docs/platform/k8s/helm/run.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x

#20872 Introduce a wrapper for NewTestCluster that only supports single node
  command/agent_test.go
  command/proxy_test.go
  helper/testhelpers/minimal/minimal.go
  vault/expiration_integ_test.go
  vault/external_tests/approle/wrapped_secretid_test.go
  vault/external_tests/expiration/expiration_test.go
  vault/external_tests/identity/aliases_test.go
  vault/external_tests/identity/entities_test.go
  vault/external_tests/identity/group_aliases_test.go
  vault/external_tests/identity/groups_test.go
  vault/external_tests/identity/identity_test.go
  vault/external_tests/identity/login_mfa_duo_test.go
  vault/external_tests/identity/login_mfa_okta_test.go
  vault/external_tests/kv/kv_patch_test.go
  vault/external_tests/kv/kv_subkeys_test.go
  vault/external_tests/kv/kvv2_upgrade_test.go
  vault/external_tests/mfa/login_mfa_test.go
  vault/external_tests/policy/acl_templating_test.go
  vault/external_tests/policy/policy_test.go
  vault/external_tests/router/router_ext_test.go
  vault/external_tests/token/batch_token_test.go
  vault/external_tests/token/token_test.go
  vault/logical_system_integ_test.go
Labels: pr/no-changelog, pr/no-milestone

#20959 Stop overwriting the test results from the different families (normal, -race, -fips)
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#20552 [QT-426] Add support for enabling the file audit device for enos scenarios
  command/test-backend/main.go
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/build_local/main.tf
  enos/modules/get_local_metadata/main.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
  enos/modules/vault_cluster/variables.tf
  enos/modules/vault_get_cluster_ips/main.tf
  enos/modules/vault_setup_perf_primary/main.tf
  enos/modules/vault_unseal_nodes/main.tf
  enos/modules/vault_verify_performance_replication/main.tf
  enos/modules/vault_verify_read_data/main.tf
  enos/modules/vault_verify_write_data/main.tf
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#20960 Attempt to resolve flaky test TestAcmeBasicWorkflow test
  builtin/logical/pki/acme_billing_test.go
  builtin/logical/pki/path_acme_test.go
Labels: secret/pki, pr/no-changelog, pr/no-milestone

#20964 Duplicate groups creation bug
  changelog/20964.txt
  vault/identity_store_groups.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x, backport/1.14.x

#20967 agent: Better help text for agent generate-config
  command/agent_generate_config.go
Labels: pr/no-changelog, backport/1.14.x

#20973 Backport of agent: Better help text for agent generate-config into release/1.14.x
  command/agent_generate_config.go
Labels: pr/no-changelog

#20974 [QT-426] Ensure file audit device is only enabled if the leader is initialized
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#20975 Backport of [QT-426] Ensure file audit device is only enabled if the leader is initialized into release/1.11.x
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
Labels: pr/no-changelog, pr/no-milestone

#20976 Backport of [QT-426] Ensure file audit device is only enabled if the leader is initialized into release/1.12.x
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
Labels: pr/no-changelog, pr/no-milestone

#20977 Backport of [QT-426] Ensure file audit device is only enabled if the leader is initialized into release/1.13.x
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
Labels: pr/no-changelog, pr/no-milestone

#20945 Generate ACME EAB tokens that do not start with '-'
  builtin/logical/pki/path_acme_eab.go
  builtin/logical/pki/path_acme_test.go
  website/content/api-docs/secret/pki.mdx
Labels: secret/pki, pr/no-changelog, pr/no-milestone

#20985 Backport of audit file changes to release/1.14.x
  command/test-backend/main.go
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/build_local/main.tf
  enos/modules/get_local_metadata/main.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
  enos/modules/vault_cluster/variables.tf
  enos/modules/vault_get_cluster_ips/main.tf
  enos/modules/vault_setup_perf_primary/main.tf
  enos/modules/vault_unseal_nodes/main.tf
  enos/modules/vault_verify_performance_replication/main.tf
  enos/modules/vault_verify_read_data/main.tf
  enos/modules/vault_verify_write_data/main.tf
Labels: pr/no-changelog, pr/no-milestone

#20990 VAULT-14847 Skip cetain tests on ARM
  builtin/credential/radius/backend_test.go
  builtin/logical/nomad/backend_test.go
  helper/testhelpers/cassandra/cassandrahelper.go
  helper/testhelpers/ldap/ldaphelper.go
  helper/testhelpers/mssql/mssqlhelper.go
  helper/testhelpers/mysql/mysqlhelper.go
  physical/aerospike/aerospike_test.go
  physical/cockroachdb/cockroachdb_test.go
  physical/couchdb/couchdb_test.go
  physical/dynamodb/dynamodb_test.go
  plugins/database/influxdb/influxdb_test.go
Labels: pr/no-changelog, pr/no-milestone

#20991 Add more tests around issuers, roles, and directories
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/test_helpers.go
Labels: secret/pki, pr/no-changelog

#20933 Code Cleanup Around Audit Backends
  changelog/20933.txt
  vault/audit.go
  vault/audit_broker.go
  vault/audit_test.go
Labels: pr/no-milestone

#21001 Backport of openapi: Fix generated types for duration strings into release/1.12.x
  changelog/20841.txt
  sdk/framework/openapi.go
Labels: pr/no-milestone

#21002 Backport of openapi: Fix generated types for duration strings into release/1.13.x
  changelog/20841.txt
  sdk/framework/openapi.go
Labels: pr/no-milestone

#20997 [QT-426] Always create the file audit directory
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21004 Backport of [QT-426] Always create the file audit directory into release/1.11.x
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, pr/no-milestone

#21005 Backport of [QT-426] Always create the file audit directory into release/1.12.x
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, pr/no-milestone

#21007 Backport of [QT-426] Always create the file audit directory into release/1.14.x
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, pr/no-milestone

#21006 Backport of [QT-426] Always create the file audit directory into release/1.13.x
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, pr/no-milestone

#20981 Limit ACME issued certificates to a max of 90 days
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
  changelog/20981.txt
Labels: secret/pki, pr/no-milestone

#20996 Add CN-only and DNS-only tests to ACME test suite
  builtin/logical/pki/path_acme_test.go
Labels: pr/no-changelog, pr/no-milestone

#20989 Add Config Validity Test to ACME
  builtin/logical/pki/path_config_acme_test.go
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x

#21003 UI: remove remaining references to linkable-item
  ui/app/styles/components/linkable-item.scss
  ui/app/styles/components/linked-block.scss
  ui/app/styles/components/read-more.scss
  ui/app/styles/core.scss
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/info-table-item-array.hbs
  ui/lib/core/addon/templates/components/read-more.hbs
  ui/lib/core/app/components/linkable-item/content.js
  ui/lib/core/app/components/linkable-item/menu.js
Labels: ui, pr/no-changelog

#21019 Initial KV ember engine setup
  ui/app/app.js
  ui/app/router.js
  ui/lib/kv/addon/engine.js
  ui/lib/kv/addon/routes.js
  ui/lib/kv/config/environment.js
  ui/lib/kv/index.js
  ui/lib/kv/package.json
  ui/package.json
Labels: pr/no-changelog

#21016 [docs] Remove beta tag and update example code
  website/content/docs/platform/k8s/index.mdx
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/telemetry.mdx
  website/content/partials/vso-beta-note.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#21020 Add certbot renewal tests to ACME test suite.
  builtin/logical/pkiext/pkiext_binary/acme_test.go
Labels: secret/pki, pr/no-changelog, pr/no-milestone

#21025 Fix autopilot scenario failures
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21030 Backport of Fix autopilot scenario failures into release/1.12.x
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
Labels: pr/no-changelog, pr/no-milestone

#21031 Backport of Fix autopilot scenario failures into release/1.13.x
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
Labels: pr/no-changelog, pr/no-milestone

#21032 Backport of Fix autopilot scenario failures into release/1.14.x
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
Labels: pr/no-changelog, pr/no-milestone

#21029 Backport of Fix autopilot scenario failures into release/1.11.x
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/scripts/create_audit_log_dir.sh
Labels: pr/no-changelog, pr/no-milestone

#21034 Upgrade hashicorp/cap to fix OIDC provider test on 32bit
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone

#21033 Fix autopilot scenario validation error
  enos/enos-scenario-autopilot.hcl
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21024 Fix race in DNS test server configs
  builtin/logical/pki/dnstest/server.go
Labels: secret/pki, pr/no-changelog

#21043 Add route template and js files
  ui/lib/kv/addon/routes.js
  ui/lib/kv/addon/routes/configuration.js
  ui/lib/kv/addon/routes/secrets/create.js
  ui/lib/kv/addon/routes/secrets/index.js
  ui/lib/kv/addon/routes/secrets/secret/details.js
  ui/lib/kv/addon/routes/secrets/secret/diff.js
  ui/lib/kv/addon/routes/secrets/secret/edit.js
  ui/lib/kv/addon/routes/secrets/secret/metadata/details.js
  ui/lib/kv/addon/routes/secrets/secret/metadata/edit.js
  ui/lib/kv/addon/routes/secrets/secret/versions.js
  ui/lib/kv/addon/templates/configuration.hbs
  ui/lib/kv/addon/templates/secrets/create.hbs
  ui/lib/kv/addon/templates/secrets/index.hbs
  ui/lib/kv/addon/templates/secrets/secret/details.hbs
  ui/lib/kv/addon/templates/secrets/secret/diff.hbs
  ui/lib/kv/addon/templates/secrets/secret/edit.hbs
  ui/lib/kv/addon/templates/secrets/secret/metadata/details.hbs
  ui/lib/kv/addon/templates/secrets/secret/metadata/edit.hbs
  ui/lib/kv/addon/templates/secrets/secret/versions.hbs
Labels: ui, pr/no-changelog

#20999 License banner - check for new license on localStorage.
  ui/app/components/license-banners.js
  ui/app/lib/local-storage.js
  ui/app/templates/vault/cluster.hbs
  ui/tests/integration/components/license-banners-test.js
  ui/tests/unit/lib/local-storage-test.js
Labels: pr/no-changelog, backport/1.13.x, backport/1.14.x

#21047 Document how replicated data is handled by type.
  website/content/docs/enterprise/replication.mdx
Labels: pr/no-changelog, pr/no-milestone

#20913 extend vault secrets operator secret CRD examples
  website/content/docs/platform/k8s/vso/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#21044 Refactor encryption funcs for the StoredBarrierKeysPath (root key) OSS
  vault/seal.go
  vault/seal_autoseal.go
  vault/seal_util.go
  vault/sealunwrapper.go
Labels: pr/no-changelog

#21051 UI: VAULT-16941 Initial dashboard route set up
  ui/app/router.js
  ui/app/routes/vault/cluster/dashboard.js
  ui/app/templates/vault/cluster/dashboard.hbs
  ui/tests/unit/routes/vault/cluster/dashboard-test.js
Labels: ui, pr/no-changelog

#21054 Backport of Attempt to resolve flaky test TestAcmeBasicWorkflow test into release/1.14.x
  builtin/logical/pki/acme_billing_test.go
  builtin/logical/pki/path_acme_test.go
Labels: pr/no-changelog

#21061 Rename Sidebar Nav Replication Links
  ui/app/components/sidebar/nav/cluster.hbs
  ui/tests/acceptance/enterprise-sidebar-nav-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
Labels: ui, pr/no-changelog, backport/1.14.x

#21052 [Docs] Update api-ref, helm docs, and vso version for v0.1.0-rc.1
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21067 Backport of [Docs] Update api-ref, helm docs, and vso version for v0.1.0-rc.1 into release/1.14.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone

#21066 Backport of [Docs] Update api-ref, helm docs, and vso version for v0.1.0-rc.1 into release/1.13.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone

#21028 Adds an ACME validation failure test for certbot.
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  helper/testhelpers/testhelpers.go
Labels: secret/pki, pr/no-changelog, pr/no-milestone

#21082 [docs] Additional docs updates for VSO GA
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#21083 secret/pki: add known issue for slow startup times
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21090 Fix release note for Secrets as Environment Variables
  changelog/20530.txt
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x

#21091 Backport of Fix release note for Secrets as Environment Variables into release/1.14.x
  changelog/20530.txt
Labels: pr/no-changelog, pr/no-milestone

#21062 Backport of UI: pki remove ui-only params from issuer serializer into release/1.14.x
  ui/app/serializers/pki/issuer.js
Labels: ui, backport

#21093 Fix link in known issue
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21094 Backport of Fix link in known issue into release/1.13.x
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: pr/no-changelog, pr/no-milestone

#21095 Backport of Fix link in known issue into release/1.14.x
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: pr/no-changelog, pr/no-milestone

#21108 [QT-509] enos: pin to enos-provider < 0.4.0
  .gitignore
  enos/enos-modules.hcl
  enos/enos-terraform.hcl
  enos/k8s/enos-modules-k8s.hcl
  enos/k8s/enos-scenario-k8s.hcl
  enos/k8s/enos-terraform-k8s.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/variables.tf
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21119 OSS changes for fixing bug in update-primary
  helper/testhelpers/teststorage/teststorage.go
  sdk/physical/latency.go
  vault/testing.go
  website/content/api-docs/system/replication/replication-dr.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x, backport/1.14.x

#21129 [QT-527][QT-509] enos: use latest version of enos-provider
  enos/enos-modules.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-terraform.hcl
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/variables.tf
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21143 test: handle occasional lower capacity in zone d
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/vault_cluster/templates/install-packages.sh
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21125 OSS changes for fixing bug in update-primary (#21119)
  helper/testhelpers/teststorage/teststorage.go
  sdk/physical/latency.go
  vault/testing.go
  website/content/api-docs/system/replication/replication-dr.mdx
Labels: pr/no-changelog

#21144 [docs] add telemetry docs for VSO
  website/content/docs/platform/k8s/vso/telemetry.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#21127 OSS changes for fixing bug in update-primary (#21119)
  helper/testhelpers/teststorage/teststorage.go
  sdk/physical/latency.go
  vault/testing.go
Labels: pr/no-changelog

#21117 [docs] VSO documentation updates for GA
  website/content/docs/platform/k8s/index.mdx
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/telemetry.mdx
  website/content/partials/vso-beta-note.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21126 OSS changes for fixing bug in update-primary (#21119)
  helper/testhelpers/teststorage/teststorage.go
  sdk/physical/latency.go
  vault/testing.go
Labels: pr/no-changelog

#21056 [docs] Agent Process Supervisor Mode
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
  website/content/docs/agent-and-proxy/agent/template.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, backport/1.14.x

#21154 Backport of docs: vault agent generate-config into release/1.14.x
  website/content/docs/agent-and-proxy/agent/generate-config/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#21063 Update docs for new 1.14 ACME health checks
  website/content/docs/commands/pki/health-check.mdx
Labels: docs, pr/no-changelog, backport/1.14.x

#21162 Backport of Update docs for new 1.14 ACME health checks into release/1.14.x
  website/content/docs/commands/pki/health-check.mdx
Labels: docs, pr/no-changelog

#21155 Refactor seal wrapping of recovery keys.
  vault/seal_autoseal.go
  vault/seal_util.go
Labels: pr/no-changelog

#21169 Clarify that no_store=true certs can still be revoked
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21172 Backport of [docs] Agent Process Supervisor Mode into release/1.14.x
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
  website/content/docs/agent-and-proxy/agent/template.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#21050 Add the payload parameter description
  website/content/docs/enterprise/license/utilization-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x

#21099 VAULT-15835 Add GHA that checks for nil, nil returns on functions that return an error
  .github/scripts/generate-test-package-lists.sh
  .github/workflows/nil-nil-function-checker.yml
  .gitignore
  Makefile
  tools/gonilnilfunctions/main.go
  tools/gonilnilfunctions/pkg/analyzer/analyzer.go
  tools/gonilnilfunctions/pkg/analyzer/analyzer_test.go
  tools/gonilnilfunctions/pkg/analyzer/testdata/funcs.go
Labels: pr/no-changelog, pr/no-milestone

#21171 [docs] Add note about agent sidecar injector
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
Labels: docs, pr/no-changelog, backport/1.14.x

#21149 Allow CSRs with basic constraint extension with IsCA=false
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
Labels: secret/pki, pr/no-changelog, backport/1.14.x

#21161 docs/pki: add remove_roots_from_chain option to /pki/issue
  website/content/api-docs/secret/pki.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21177 Backport of Verify FailureToTolerance prior to sealing in ACME test SubtestACMEStepDownNode into release/1.14.x
  builtin/logical/pkiext/pkiext_binary/acme_test.go
Labels: pr/no-changelog

#21110 Fix: non-login requests shouldn't care about login roles for lease quotas. Also fix a potential deadlock
  changelog/21110.txt
  vault/core.go
  vault/logical_system.go
  vault/request_handling.go
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x

#21141 Document known issues surrounding update-primary on PR secondaries.
  website/content/docs/release-notes/1.13.0.mdx
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/partials/update-primary-known-issue.mdx
Labels: pr/no-changelog, pr/no-milestone

#21092 Backport of Telemetry Metrics Configuration. (#18186) into release/1.12.x
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  builtin/logical/pki/storage.go
  changelog/18186.txt
Labels: secret/pki

#21197 CI: make tests-completed fail when setup-go-cache fails
  .github/workflows/ci.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21203 Backport of CI: make tests-completed fail when setup-go-cache fails into release/1.12.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#21204 Backport of CI: make tests-completed fail when setup-go-cache fails into release/1.13.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#21202 Backport of CI: make tests-completed fail when setup-go-cache fails into release/1.11.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#21205 Backport of CI: make tests-completed fail when setup-go-cache fails into release/1.14.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#21201 Backport of Clients config updates for census reporting into release/1.13.x
  changelog/20125.txt
  ui/app/components/clients/config.js
  ui/app/decorators/model-validations.js
  ui/app/models/clients/config.js
  ui/app/templates/components/clients/config.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/config.hbs
  ui/tests/integration/components/clients/config-test.js
Labels: ui

#21195 docs/vso: updating pki secret destination doc string
  website/content/docs/platform/k8s/vso/api-reference.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21011 Onboard Vault to the prepare workflow.
  .release/ci.hcl
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21219 Backport of Onboard Vault to the prepare workflow. into release/1.14.x
  .release/ci.hcl
Labels: pr/no-changelog, pr/no-milestone

#21217 Backport of Onboard Vault to the prepare workflow. into release/1.12.x
  .release/ci.hcl
Labels: pr/no-changelog, pr/no-milestone

#21216 Backport of Onboard Vault to the prepare workflow. into release/1.11.x
  .release/ci.hcl
Labels: pr/no-changelog, pr/no-milestone

#21208 Backport of Clients config updates for census reporting into release/1.11.x
  changelog/20125.txt
  ui/app/components/clients/config.js
  ui/app/decorators/model-validations.js
  ui/app/models/clients/config.js
  ui/app/templates/components/clients/config.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/config.hbs
  ui/tests/integration/components/clients/config-test.js
Labels: ui

#21206 Backport of Clients config updates for census reporting into release/1.12.x
  changelog/20125.txt
  ui/app/components/clients/config.js
  ui/app/decorators/model-validations.js
  ui/app/models/clients/config.js
  ui/app/templates/components/clients/config.hbs
  ui/app/templates/components/clients/current.hbs
  ui/app/templates/components/clients/history.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/config.hbs
  ui/tests/integration/components/clients/config-test.js
Labels: ui

#21190 Correctly validate ACME PoP against public key
  builtin/logical/pki/path_acme_revoke.go
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_revoke.go
Labels: bug, secret/pki, pr/no-changelog, backport/1.14.x

#21209 Allow issuance of root certs no AIA when templating is enabled
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  changelog/21209.txt
Labels: bug, secret/pki, backport/1.14.x

#21213 test: run enos scenarios with trace log level
  enos/enos-modules.hcl
  enos/enos-variables.hcl
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21059 LDAP Config Route
  ui/app/models/ldap/config.js
  ui/app/services/secret-mount-path.ts
  ui/lib/core/addon/decorators/fetch-secrets-engine-config.ts
  ui/lib/kubernetes/addon/routes/configuration.js
  ui/lib/kubernetes/addon/routes/configure.js
  ui/lib/kubernetes/addon/routes/overview.js
  ui/lib/kubernetes/addon/routes/roles/create.js
  ui/lib/kubernetes/addon/routes/roles/index.js
  ui/lib/kubernetes/addon/routes/roles/role/credentials.js
  ui/lib/kubernetes/addon/routes/roles/role/details.js
  ui/lib/kubernetes/addon/routes/roles/role/edit.js
  ui/lib/ldap/addon/routes/configure.ts
  ui/lib/ldap/package.json
  ui/tests/unit/decorators/fetch-secrets-engine-config-test.js
  ui/tsconfig.json
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/app-types.ts
  ui/types/vault/models/ldap/config.d.ts
Labels: ui, pr/no-changelog

#21223 Add paths for seal config to cache exceptions.
  changelog/21223.txt
  sdk/physical/cache.go
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x

#21163 UI: HDS adoption replace AlertBanner part 1
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/generate-credentials-database.hbs
  ui/app/templates/components/generate-credentials.hbs
  ui/app/templates/components/license-banners.hbs
  ui/app/templates/components/oidc-callback-splash.hbs
  ui/app/templates/components/raft-join.hbs
  ui/app/templates/components/raft-storage-restore.hbs
  ui/app/templates/components/role-aws-edit.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/lib/core/addon/components/alert-banner.hbs
  ui/tests/acceptance/client-dashboard-test.js
  ui/tests/acceptance/enterprise-license-banner-test.js
  ui/tests/acceptance/pki/pki-action-forms-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/license-banners-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/oidc/key-form-test.js
  ui/tests/integration/components/oidc/provider-form-test.js
  ui/tests/integration/components/oidc/scope-form-test.js
  ui/tests/integration/components/pki/page/pki-issuer-rotate-root-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
Labels: ui, pr/no-changelog

#21237 Backport of agent: Fix bug with 'cache' stanza validation into release/1.13.x
  changelog/20934.txt
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template-with-cache.hcl
Labels: pr/no-milestone

#21027 ui: update multi-endpoint error handling for pki config
  ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.ts
  ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
Labels: ui, pr/no-changelog, backport/1.14.x

#21241 Rename PKI check-config Decorator
  ui/lib/pki/addon/decorators/check-issuers.js
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/routes/tidy.js
Labels: ui, pr/no-changelog

#21249 Fix a panic I observed in a sealed node running CollectMetrics
  changelog/21249.txt
  physical/raft/raft.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x, backport/1.14.x

#21101 Bump protoc-gen-go to v1.29.1
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/activity/generation/generate_data.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog

#21245 VAULT-16905: Add upgrade description about non entity tokens
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/upgrading/upgrade-to-1.9.x.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x, backport/1.14.x

#21259 Bump HDS to 2.7.0
  ui/app/styles/components/page-header-old.scss
  ui/app/styles/core.scss
  ui/package.json
  ui/yarn.lock
Labels: ui, dependencies, pr/no-changelog

#21261 Allow mounted paths to be tracked via path hook
  vault/mount.go
  vault/mount_util.go
Labels: pr/no-changelog, pr/no-milestone

#21260 Call runFilteredPathsEvaluation from within mountInternal/enableCredentialInternal
  changelog/21260.txt
  helper/testhelpers/teststorage/teststorage.go
  vault/auth.go
  vault/core.go
  vault/mount.go
  vault/mount_util.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x, backport/1.14.x

#21242 Backport of ui: update multi-endpoint error handling for pki config into release/1.14.x
  ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.ts
  ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
Labels: ui

#21225 ACME Considerations Guide
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.14.x

#21281 Rework the test package tester to avoid grep pitfalls.
  .github/scripts/generate-test-package-lists.sh
  .github/scripts/test-generate-test-package-lists.sh
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x

#21291 Fix backport: ocsp test should be in PKI, not in sdk
  builtin/logical/pki/integration_test.go
  sdk/helper/ocsp/ocsp_test.go
Labels: bug, secret/pki, sdk, pr/no-changelog

#21277 Adds automated ACME tests using Caddy.
  builtin/logical/pki/acme_challenges.go
  builtin/logical/pki/acme_challenges_test.go
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  builtin/logical/pkiext/pkiext_binary/pki_cluster.go
  builtin/logical/pkiext/pkiext_binary/pki_mount.go
  builtin/logical/pkiext/pkiext_binary/testdata/caddy_http.json
  builtin/logical/pkiext/pkiext_binary/testdata/caddy_http_eab.json
  builtin/logical/pkiext/pkiext_binary/testdata/caddy_tls_alpn.json
Labels: bug, secret/pki, pr/no-changelog, backport/1.14.x

#21118 1.14.0 Known Issues text update
  website/content/partials/ui-pki-control-groups-known-issue.mdx
  website/content/partials/update-primary-known-issue.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x

#21275 Supporting PR for Enterprise ACME PR cluster tests
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_ocsp_test.go
  builtin/logical/pki/test_helpers.go
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x

#21293 Backport of Adds automated ACME tests using Caddy. into release/1.14.x
  builtin/logical/pki/acme_challenges.go
  builtin/logical/pki/acme_challenges_test.go
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  builtin/logical/pkiext/pkiext_binary/pki_cluster.go
  builtin/logical/pkiext/pkiext_binary/pki_mount.go
  builtin/logical/pkiext/pkiext_binary/testdata/caddy_http.json
  builtin/logical/pkiext/pkiext_binary/testdata/caddy_http_eab.json
  builtin/logical/pkiext/pkiext_binary/testdata/caddy_tls_alpn.json
Labels: secret/pki, pr/no-changelog

#21295 Backport of Supporting PR for Enterprise ACME PR cluster tests into release/1.14.x
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_ocsp_test.go
  builtin/logical/pki/test_helpers.go
Labels: pr/no-changelog

#21262 Fix some broken links/clarify some things in the Vault Proxy docs
  website/content/docs/agent-and-proxy/agent/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/commands/agent.mdx
  website/content/docs/commands/proxy.mdx
  website/content/docs/get-started/developer-qs.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone

#21307 Backport of Fix some broken links/clarify some things in the Vault Proxy docs into release/1.14.x
  website/content/docs/agent-and-proxy/agent/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/commands/agent.mdx
  website/content/docs/commands/proxy.mdx
  website/content/docs/get-started/developer-qs.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone

#21308 Setup Go before calling the test package test script
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone
