Repository hashicorp/vault, pull requests merged in 2023-10, with the labels that each got.

#23444 [Docs] Fix a typo
  website/content/docs/release-notes/1.15.0.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#23442 Backport of Prevent split-brain active node writes when using Consul into release/1.15.x
  changelog/23013.txt
  helper/testhelpers/consul/cluster_storage.go
  helper/testhelpers/consul/consulhelper.go
  helper/testhelpers/teststorage/consul/consul.go
  physical/consul/consul.go
  physical/consul/consul_test.go
  sdk/helper/testcluster/docker/environment.go
  sdk/helper/testcluster/types.go
  sdk/helper/testcluster/util.go
  sdk/physical/physical.go
  sdk/physical/testing.go
  vault/external_tests/consul_fencing_binary/consul_fencing_test.go
  vault/ha.go
Labels: hashicorp-contributed-pr

#23445 Backport of [Docs] Fix a typo into release/1.15.x
  website/content/docs/release-notes/1.15.0.mdx
Labels: hashicorp-contributed-pr

#23443 Backport of Prevent split-brain active node writes when using Consul into release/1.14.x
  changelog/23013.txt
  helper/testhelpers/consul/cluster_storage.go
  helper/testhelpers/consul/consulhelper.go
  helper/testhelpers/teststorage/consul/consul.go
  physical/consul/consul.go
  physical/consul/consul_test.go
  sdk/helper/testcluster/docker/environment.go
  sdk/helper/testcluster/types.go
  sdk/helper/testcluster/util.go
  sdk/physical/physical.go
  sdk/physical/testing.go
  vault/external_tests/consul_fencing_binary/consul_fencing_test.go
  vault/ha.go
Labels: hashicorp-contributed-pr

#23415 UI: Part 3 - hds adoption replace <Modal>
  ui/app/styles/components/masked-input.scss
  ui/app/styles/core/buttons.scss
  ui/app/templates/components/link-status.hbs
  ui/app/templates/vault/cluster/init.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/lib/core/addon/components/download-button.hbs
  ui/lib/core/addon/components/download-button.js
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/masked-input.hbs
  ui/lib/kmip/addon/templates/configuration.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/page/pki-key-list.hbs
  ui/tests/integration/components/download-button-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23227 Backport of Added chroot namespace to listener config printing into release/1.15.x
  command/server.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23446 Bug fix for double slash in LIST endpoint
  changelog/23446.txt
  ui/app/services/path-help.js
Labels: hashicorp-contributed-pr, backport/1.15.x

#23450 Backport of Bug fix for double slash in LIST endpoint into release/1.15.x
  changelog/23446.txt
  ui/app/services/path-help.js
Labels: hashicorp-contributed-pr

#23448 UI: Part 3.5 - hds adoption replace <Modal>
  ui/app/styles/core/buttons.scss
  ui/lib/core/addon/templates/components/replication-action-promote.hbs
  ui/lib/core/addon/templates/components/replication-action-recover.hbs
  ui/lib/core/addon/templates/components/replication-action-reindex.hbs
  ui/lib/core/addon/templates/components/replication-action-update-primary.hbs
  ui/lib/replication/addon/controllers/application.js
  ui/lib/replication/addon/templates/mode/secondaries/add.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23453 [VAULT-20630] CI: Fix the CI workflow issue where we check out base ref instead of the ref that triggered the workflow run
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, ci, hashicorp-contributed-pr, backport/1.15.x

#23455 Backport of [VAULT-20630] CI: Fix the CI workflow issue where we check out base ref instead of the ref that triggered the workflow run into release/1.15.x
  .github/workflows/ci.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23424 update changelog with links to published advisories
  CHANGELOG.md
Labels: pr/no-changelog, hashicorp-contributed-pr

#23454 Backport of [VAULT-20630] CI: Fix the CI workflow issue where we check out base ref instead of the ref that triggered the workflow run into release/1.13.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23456 Backport of [VAULT-20630] CI: Fix the CI workflow issue where we check out base ref instead of the ref that triggered the workflow run into release/1.14.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23458 [VAULT-20630] CI: Use 'ref' (not 'base_ref') as a default git reference to check out code in the test-go GHA workflow
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, ci, hashicorp-contributed-pr, backport/1.15.x

#23452 UI: [VAULT-20626] Hide replication if user doesnt have permissions
  ui/app/templates/components/dashboard/overview.hbs
  ui/tests/acceptance/dashboard-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#23461 docs: link to the VSO+HVS quick-start tutorial
  website/content/docs/platform/k8s/vso/sources/hvs.mdx
Labels: pr/no-changelog, pr/no-milestone

#23460 Backport of [VAULT-20630] CI: Use 'ref' (not 'base_ref') as a default git reference to check out code in the test-go GHA workflow into release/1.15.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#23459 Backport of [VAULT-20630] CI: Use 'ref' (not 'base_ref') as a default git reference to check out code in the test-go GHA workflow into release/1.13.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23469 Backport of [VAULT-20630] CI: Use 'ref' (not 'base_ref') as a default git reference to check out code in the test-go GHA workflow into release/1.14.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23451 UI: Part 4 - hds adoption replace <Modal>
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/element-styling.scss
  ui/lib/core/addon/helpers/message-types.js
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/lib/kv/addon/components/kv-delete-modal.hbs
  ui/lib/kv/addon/components/kv-delete-modal.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.hbs
  ui/lib/ldap/addon/components/page/configure.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/page/pki-tidy-status.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23470 Allow AWS secret engine to send empty policy document
  changelog/23470.txt
  ui/app/models/role-aws.js
  ui/lib/core/addon/helpers/jsonify.js
Labels: ui, bug, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23473 [QT-602] Don't fail if scenarios cannot completely destroy infra
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-scenario-replication.hcl
  enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23477 Backport of [QT-602] Don't fail if scenarios cannot completely destroy infra into release/1.13.x
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-scenario-replication.hcl
  enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23478 Backport of [QT-602] Don't fail if scenarios cannot completely destroy infra into release/1.14.x
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-scenario-replication.hcl
  enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23479 Backport of [QT-602] Don't fail if scenarios cannot completely destroy infra into release/1.15.x
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-scenario-replication.hcl
  enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23476 Backport of [QT-602] Don't fail if scenarios cannot completely destroy infra into release/1.12.x
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-scenario-replication.hcl
  enos/modules/vault_get_cluster_ips/scripts/get-follower-private-ips.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23471 UI: Part 5 - hds adoption replace <Modal>
  ui/lib/core/addon/components/confirmation-modal.hbs
  ui/lib/core/addon/components/confirmation-modal.js
  ui/lib/core/addon/templates/components/replication-action-demote.hbs
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23482 test: don't run proxy scenario before 1.14.x
  enos/enos-samples-ce-release.hcl
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, hashicorp-contributed-pr

#23480 Revert "auth/aws: fix panic in IAM-based login when client config doesn't exist (#23366)"
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  changelog/23366.txt
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/aws-auth-panics.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23483 backport test: don't run proxy scenario before 1.14.x (#23482) into release/1.12.x
  enos/enos-samples-ce-release.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23462 Backport of UI: [VAULT-20626] Hide replication if user doesnt have permissions into release/1.15.x
  ui/app/templates/components/dashboard/overview.hbs
  ui/tests/acceptance/dashboard-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23464 Backport of UI: [VAULT-19693] Only make vault configuration call when in root namespace into release/1.15.x
  ui/app/routes/vault/cluster/dashboard.js
Labels: hashicorp-contributed-pr

#23331 Fix Copy token button when sidebar navigation is in a collapsed state due to a small window size
  changelog/23331.txt
  ui/app/components/sidebar/user-menu.hbs
Labels: ui, bug, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23240 MongoDB database secret engine - rotate-root - Only default to admin if DB blank
  changelog/23240.txt
  plugins/database/mongodb/mongodb.go
  plugins/database/mongodb/mongodb_test.go
Labels: backport, backport/1.11.x, backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23493 Backport of Revert "auth/aws: fix panic in IAM-based login when client config doesn't exist (#23366)" into release/1.15.x
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  changelog/23366.txt
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/aws-auth-panics.mdx
Labels: hashicorp-contributed-pr

#23490 Backport of MongoDB database secret engine - rotate-root - Only default to admin if DB blank into release/1.13.x
  changelog/23240.txt
  plugins/database/mongodb/mongodb.go
  plugins/database/mongodb/mongodb_test.go
Labels: hashicorp-contributed-pr

#23492 Backport of MongoDB database secret engine - rotate-root - Only default to admin if DB blank into release/1.15.x
  changelog/23240.txt
  plugins/database/mongodb/mongodb.go
  plugins/database/mongodb/mongodb_test.go
Labels: hashicorp-contributed-pr

#23494 Set VAULT_TEST_LOG_DIR, logs from NewTestLogger will be written there
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23467 add HCP Vault tab for venafi + minor format update
  website/content/docs/secrets/venafi.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#23449 UI: sanitize managed namespace input
  ui/app/controllers/vault/cluster/auth.js
  ui/app/services/console.js
  ui/app/services/path-help.js
  ui/app/templates/vault/cluster/auth.hbs
  ui/lib/core/addon/utils/sanitize-path.js
  ui/lib/core/app/utils/sanitize-path.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/managed-namespace-test.js
  ui/tests/unit/services/console-test.js
  ui/tests/unit/utils/sanitize-path-test.js
Labels: ui, bug, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#23506 Backport of core/link: fix bug where lock was unlocked before getting ha state into release/1.15.x
  vault/core.go
Labels: hashicorp-contributed-pr

#23505 Backport of core/link: fix bug where lock was unlocked before getting ha state into release/1.14.x
  vault/core.go
Labels: hashicorp-contributed-pr

#23504 Backport of core/link: fix bug where lock was unlocked before getting ha state into release/1.13.x
  vault/core.go
Labels: hashicorp-contributed-pr

#23497 Backport of Allow AWS secret engine to send empty policy document into release/1.15.x
  changelog/23470.txt
  ui/app/models/role-aws.js
  ui/lib/core/addon/helpers/jsonify.js
Labels: backport, hashicorp-contributed-pr

#23508 [QT-623] Pin to terraform 1.5.x
  .github/workflows/enos-lint.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23466 Backport of docs: link to the VSO+HVS quick-start tutorial into release/1.15.x
  website/content/docs/platform/k8s/vso/sources/hvs.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#23518 Backport of [QT-623] Pin to terraform 1.5.x into release/1.12.x
  .github/workflows/enos-lint.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23519 Backport of [QT-623] Pin to terraform 1.5.x into release/1.13.x
  .github/workflows/enos-lint.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23520 Backport of [QT-623] Pin to terraform 1.5.x into release/1.14.x
  .github/workflows/enos-lint.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23521 Backport of [QT-623] Pin to terraform 1.5.x into release/1.15.x
  .github/workflows/enos-lint.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: hashicorp-contributed-pr

#23507 Backport of UI: sanitize managed namespace input into release/1.15.x
  ui/app/controllers/vault/cluster/auth.js
  ui/app/services/console.js
  ui/app/services/path-help.js
  ui/app/templates/vault/cluster/auth.hbs
  ui/lib/core/addon/utils/sanitize-path.js
  ui/lib/core/app/utils/sanitize-path.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/managed-namespace-test.js
  ui/tests/unit/services/console-test.js
  ui/tests/unit/utils/sanitize-path-test.js
Labels: ui, backport, hashicorp-contributed-pr

#23515 [DOCS] Confirm restricted endpoint alerts (1.14 docs)
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23502 Config: Listener parsing clean-up
  command/server/config_test_helpers.go
  internalshared/configutil/config.go
  internalshared/configutil/listener.go
  internalshared/configutil/listener_test.go
Labels: core/config, pr/no-changelog, hashicorp-contributed-pr

#23516 Policies Error Route
  changelog/23516.txt
  ui/app/templates/vault/cluster/policies/error.hbs
Labels: ui, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23524 Backport of Policies Error Route into release/1.14.x
  changelog/23516.txt
  ui/app/templates/vault/cluster/policies/error.hbs
Labels: ui, hashicorp-contributed-pr

#23525 Backport of Policies Error Route into release/1.15.x
  changelog/23516.txt
  ui/app/templates/vault/cluster/policies/error.hbs
Labels: ui, hashicorp-contributed-pr

#23513 [DOCS] Confirm restricted endpoint alerts (1.15 docs)
  website/content/api-docs/system/internal-counters.mdx
  website/content/api-docs/system/managed-keys.mdx
  website/content/api-docs/system/mfa/index.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23484 UI: Part 6 - hds adoption replace <Modal>
  ui/app/components/date-dropdown.js
  ui/app/components/modal-form/policy-template.hbs
  ui/app/components/policy-form.hbs
  ui/app/styles/components/modal-component.scss
  ui/app/styles/components/toolbar.scss
  ui/app/styles/core/element-styling.scss
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/templates/components/oidc/assignment-form.hbs
  ui/lib/core/addon/components/choose-pgp-key-form.hbs
  ui/lib/core/addon/components/code-snippet.hbs
  ui/lib/core/addon/components/policy-example.hbs
  ui/lib/core/addon/components/policy-example.js
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/components/search-select.hbs
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/components/shamir/dr-token-flow.hbs
  ui/lib/core/addon/components/shamir/form.hbs
  ui/lib/core/addon/templates/components/replication-action-generate-token.hbs
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/tests/integration/components/date-dropdown-test.js
  ui/tests/integration/components/download-button-test.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23526 bump go-eventlogger to v0.2.5
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23512 Document how to upgrade a Helm managed VSO
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#23529 Backport of Document how to upgrade a Helm managed VSO into release/1.15.x
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23393 Slight rephrase for the association API endpoints
  website/content/api-docs/system/secrets-sync.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#23530 Backport of Slight rephrase for the association API endpoints into release/1.15.x
  website/content/api-docs/system/secrets-sync.mdx
Labels: hashicorp-contributed-pr

#23531 [DOCS] Manual fix of restricted endpoint alerts (1.15.x)
  website/content/api-docs/system/audit-hash.mdx
  website/content/api-docs/system/auth.mdx
  website/content/api-docs/system/capabilities-self.mdx
  website/content/api-docs/system/capabilities.mdx
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/control-group.mdx
  website/content/api-docs/system/ha-status.mdx
  website/content/api-docs/system/internal-specs-openapi.mdx
  website/content/api-docs/system/internal-ui-feature.mdx
  website/content/api-docs/system/internal-ui-mounts.mdx
  website/content/api-docs/system/internal-ui-resultant-acl.mdx
  website/content/api-docs/system/leader.mdx
  website/content/api-docs/system/leases.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/monitor.mdx
  website/content/api-docs/system/mounts.mdx
  website/content/api-docs/system/plugins-catalog.mdx
  website/content/api-docs/system/plugins-reload-backend.mdx
  website/content/api-docs/system/policies-password.mdx
  website/content/api-docs/system/policies.mdx
  website/content/api-docs/system/policy.mdx
  website/content/api-docs/system/remount.mdx
  website/content/api-docs/system/seal-status.mdx
  website/content/api-docs/system/tools.mdx
  website/content/api-docs/system/user-lockout.mdx
  website/content/api-docs/system/version-history.mdx
  website/content/api-docs/system/wrapping-lookup.mdx
  website/content/api-docs/system/wrapping-rewrap.mdx
  website/content/api-docs/system/wrapping-unwrap.mdx
  website/content/api-docs/system/wrapping-wrap.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23532 [DOCS] Manual fix of restricted endpoint alerts (1.14.x)
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23533 [DOCS] Manual fix of restricted endpoint alerts (main)
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23500 events: Ignore send context
  changelog/23500.txt
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23537 Backport of events: Ignore send context into release/1.15.x
  changelog/23500.txt
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: hashicorp-contributed-pr

#23536 Backport of events: Ignore send context into release/1.13.x
  changelog/23500.txt
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: hashicorp-contributed-pr

#23538 Backport of events: Ignore send context into release/1.14.x
  changelog/23500.txt
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: hashicorp-contributed-pr

#23545 Start process of replacing init-style ent hooks with stubmaker
  command/command_stubs_oss.go
  command/commands.go
  command/server.go
  command/server/config.go
  command/server/server_stubs_oss.go
  command/server_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23552 Add known issue notice for AWS auth panic
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/aws-auth-panics.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#23550 Remove old hooks and start calling new ones.
  command/commands.go
  command/server.go
  command/server/config.go
  command/server_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23522 UI: Final hds adoption replace <Modal> cleanup PR
  ui/app/components/sidebar/frame.hbs
  ui/app/styles/components/modal-component.scss
  ui/app/styles/components/shamir-modal-flow.scss
  ui/app/styles/core.scss
  ui/app/templates/components/date-dropdown.hbs
  ui/lib/core/addon/components/choose-pgp-key-form.hbs
  ui/lib/core/addon/components/confirmation-modal.hbs
  ui/lib/core/addon/components/confirmation-modal.js
  ui/lib/core/addon/components/modal.hbs
  ui/lib/core/addon/components/modal.js
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/components/shamir/dr-token-flow.hbs
  ui/lib/core/addon/templates/components/replication-action-demote.hbs
  ui/lib/core/addon/templates/components/replication-action-disable.hbs
  ui/lib/core/addon/templates/components/replication-action-promote.hbs
  ui/lib/core/addon/templates/components/replication-action-recover.hbs
  ui/lib/core/addon/templates/components/replication-action-reindex.hbs
  ui/lib/core/addon/templates/components/replication-action-update-primary.hbs
  ui/lib/core/app/components/modal.js
  ui/lib/core/package.json
  ui/lib/kv/addon/components/kv-delete-modal.hbs
  ui/lib/replication/addon/templates/mode/secondaries/add.hbs
  ui/package.json
  ui/tests/acceptance/client-dashboard-test.js
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/pki/pki-tidy-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/helpers/clients.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/pki/page/pki-tidy.js
  ui/tests/helpers/pki/pki-delete-all-issuers.js
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/index.html
  ui/tests/integration/components/clients/monthly-usage-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/components/confirmation-modal-test.js
  ui/tests/integration/components/date-dropdown-test.js
  ui/tests/integration/components/download-button-test.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
  ui/tests/integration/components/ldap/accounts-checked-out-test.js
  ui/tests/integration/components/ldap/page/configure-test.js
  ui/tests/integration/components/ldap/page/library/details/accounts-test.js
  ui/tests/integration/components/masked-input-test.js
  ui/tests/integration/components/mfa/method-form-test.js
  ui/tests/integration/components/modal-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/oidc/scope-form-test.js
  ui/tests/integration/components/pki/page/pki-tidy-status-test.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
  ui/tests/integration/components/policy-form-test.js
  ui/tests/integration/components/replication-action-generate-token-test.js
  ui/tests/integration/components/replication-actions-test.js
  ui/tests/integration/components/replication-header-test.js
  ui/tests/integration/components/search-select-with-modal-test.js
  ui/tests/integration/components/sidebar/nav/tools-test.js
  ui/tests/integration/components/transit-key-actions-test.js
  ui/tests/integration/components/upgrade-page-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23554 Backport of commit 'baa4dbe8e285e1e3244ae5ce2be89d67c1b5cea9'
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/aws-auth-panics.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23553 Be a bit more explicit about the need for two seals.
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#23534 VAULT-19863: Per-listener redaction settings
  changelog/23534.txt
  command/server.go
  command/server/config_test_helpers.go
  http/handler.go
  http/handler_test.go
  http/options.go
  http/options_test.go
  http/sys_health.go
  http/sys_leader.go
  http/sys_seal.go
  internalshared/configutil/listener.go
  internalshared/configutil/listener_test.go
  vault/testing.go
Labels: hashicorp-contributed-pr

#23558 Fix for failing enterprise test
  helper/testhelpers/teststorage/teststorage.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#23177 VAULT-19233 Second part of caching static secrets work
  command/agentproxyshared/cache/cache_test.go
  command/agentproxyshared/cache/cacheboltdb/bolt.go
  command/agentproxyshared/cache/cachememdb/cache_memdb.go
  command/agentproxyshared/cache/cachememdb/cache_memdb_test.go
  command/agentproxyshared/cache/cachememdb/index.go
  command/agentproxyshared/cache/cachememdb/index_test.go
  command/agentproxyshared/cache/lease_cache.go
  command/agentproxyshared/cache/lease_cache_test.go
  command/agentproxyshared/cache/testing.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23557 Define a bunch of stubs that will replace existing init hooks.
  helper/builtinplugins/registry.go
  helper/builtinplugins/registry_stubs_oss.go
  http/util.go
  http/util_stubs_oss.go
  vault/core.go
  vault/core_stubs_oss.go
  vault/init.go
  vault/request_handling.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23555 auth/aws: fix panic in IAM-based login when client config doesn't exi…
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  changelog/23555.txt
Labels: hashicorp-contributed-pr, backport/1.15.x

#23559 Backport of auth/aws: fix panic in IAM-based login when client config doesn't exi… into release/1.15.x
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  changelog/23555.txt
Labels: hashicorp-contributed-pr

#23140 Implement user lockout log
  changelog/23140.txt
  command/server.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  internalshared/configutil/config.go
  internalshared/configutil/merge.go
  vault/core.go
  vault/logical_system_user_lockout.go
  vault/request_handling.go
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23562 UI: Fix failing dashboard tests
  ui/tests/integration/components/dashboard/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#23511 Fix copy button in collapsed sidebar nav in CopyButton component
  ui/app/components/sidebar/user-menu.hbs
Labels: ui, pr/no-changelog, backport/1.14.x, hashicorp-contributed-pr

#23509 Backport 1.14.1x: Allow AWS secret engine to send empty policy document (#23470)
  changelog/23470.txt
  ui/app/helpers/jsonify.js
  ui/app/models/role-aws.js
Labels: ui, backport, hashicorp-contributed-pr

#23564 Fix copy button in collapsed sidebar nav in CopyButton component
  changelog/23331.txt
  ui/app/components/sidebar/user-menu.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23022 Correct the post-unseal meaning of the seal status type
  api/sys_seal.go
  changelog/23022.txt
  command/format.go
  command/format_test.go
  vault/logical_system.go
Labels: hashicorp-contributed-pr

#23423 adding testonly CI test job (#22439)
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#23422 adding testonly CI test job (#22439)
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#23568 documentation for redaction configuration on listeners
  website/content/docs/configuration/listener/index.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#23556 Backport of Be a bit more explicit about the need for two seals. into release/1.15.x
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23548 Remove asterixes in header
  website/content/api-docs/system/config-state.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, backport/1.15.x

#23542 Fix path for Delete metadata and all versions
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, backport/1.15.x

#23543 Fix Read config header level
  website/content/api-docs/auth/jwt.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, backport/1.15.x

#23575 Backport of Remove asterixes in header into release/1.15.x
  website/content/api-docs/system/config-state.mdx
Labels: hashicorp-contributed-pr

#23576 Backport of Fix path for Delete metadata and all versions into release/1.14.x
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23577 Backport of Fix path for Delete metadata and all versions into release/1.15.x
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23574 Backport of Remove asterixes in header into release/1.14.x
  website/content/api-docs/system/config-state.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23570 Add changelog for Copy Button fix
  changelog/23331.txt
Labels: ui, backport, hashicorp-contributed-pr

#23589 Fix failing transform modal test
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/helpers/pki/page/pki-tidy.js
  ui/tests/helpers/pki/pki-delete-all-issuers.js
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/integration/components/confirmation-modal-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/search-select-with-modal-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23593 add HCP Vault tab for venafi + minor format update (#23467)
  website/content/docs/secrets/venafi.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23535 Update Telemetry Docs
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/docs/internals/telemetry/metrics/availability.mdx
  website/content/partials/telemetry-metrics/vault/replication/fsm/last_remote_wal.mdx
  website/content/partials/telemetry-metrics/vault/replication/fsm/last_upstream_remote_wal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23567 Backport 1.15.x: Fix failing dashboard tests
  ui/tests/integration/components/dashboard/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23594 Docs: update VSO docs for 0.3.2
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.15.x

#23597 Backport of Docs: update VSO docs for 0.3.2 into release/1.15.x
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23588 Backport of Implement user lockout log into release/1.15.x
  changelog/23140.txt
  command/server.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  internalshared/configutil/config.go
  internalshared/configutil/merge.go
  vault/core.go
  vault/logical_system_user_lockout.go
  vault/request_handling.go
Labels: hashicorp-contributed-pr, vault-update

#23600 CI: Pre-emptively delete logs dir after cache restore in test-collect-reports
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#23565 Fix OktaNumberChallenge
  changelog/23565.txt
  ui/app/components/auth-form.js
Labels: ui, hashicorp-contributed-pr, backport/1.15.x

#23605 Backport of exclude changelog in verifying doc/ui into release/1.13.x
  .github/scripts/verify_changes.sh
Labels: hashicorp-contributed-pr

#23606 Backport of exclude changelog in verifying doc/ui into release/1.14.x
  .github/scripts/verify_changes.sh
Labels: hashicorp-contributed-pr

#23604 Backport of Fix OktaNumberChallenge into release/1.15.x
  changelog/23565.txt
  ui/app/components/auth-form.js
Labels: ui, backport, hashicorp-contributed-pr

#23582 Audit: capture emitted errors from nodes
  vault/audit_broker.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#23609 Backport of Audit: eventlogger sink node reopen on SIGHUP into release/1.15.x
  builtin/audit/file/backend.go
  changelog/23598.txt
Labels: hashicorp-contributed-pr

#23610 Backport of Audit: capture emitted errors from nodes into release/1.15.x
  vault/audit_broker.go
Labels: hashicorp-contributed-pr

#23592 Listeners: Redaction only for TCP
  command/server.go
  command/server/config_test_helpers.go
  command/server/listener.go
  internalshared/configutil/config.go
  internalshared/configutil/listener.go
  internalshared/configutil/listener_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#23611 Fix panic when unlocking unlocked user
  vault/logical_system_user_lockout.go
Labels: hashicorp-contributed-pr

#23612 Backport of Fix panic when unlocking unlocked user into release/1.13.x
  vault/logical_system_user_lockout.go
Labels: hashicorp-contributed-pr

#23613 Backport of Fix panic when unlocking unlocked user into release/1.15.x
  vault/logical_system_user_lockout.go
Labels: hashicorp-contributed-pr

#23362 CE changes for https://github.com/hashicorp/vault-enterprise/pull/4780
  vault/core_util.go
  vault/raft.go
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23608 Docs: known issue - audit file reload on SIGHUP
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/1_15-audit-file-sighup-does-not-trigger-reload.mdx
Labels: docs, core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#23614 Backport of CE changes for https://github.com/hashicorp/vault-enterprise/pull/4780 into release/1.13.x
  vault/core_util.go
  vault/raft.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#23618 Backport of Docs: known issue - audit file reload on SIGHUP into release/1.15.x
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/1_15-audit-file-sighup-does-not-trigger-reload.mdx
Labels: hashicorp-contributed-pr

#23616 Backport of CE changes for https://github.com/hashicorp/vault-enterprise/pull/4780 into release/1.15.x
  vault/core_util.go
  vault/raft.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#23579 Backport of Fix Read config header level into release/1.15.x
  website/content/api-docs/auth/jwt.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23578 Backport of Fix Read config header level into release/1.14.x
  website/content/api-docs/auth/jwt.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23615 Backport of CE changes for https://github.com/hashicorp/vault-enterprise/pull/4780 into release/1.14.x
  vault/core_util.go
  vault/raft.go
Labels: pr/no-changelog, hashicorp-contributed-pr, vault-update

#23572 Docs listener config - tweak
  website/content/docs/configuration/listener/index.mdx
  website/content/docs/configuration/listener/tcp.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#23617 Backport of UI: Add version 1 if KV engine has no version data into release/1.15.x
  changelog/23585.txt
  ui/app/serializers/secret-engine.js
  ui/tests/unit/serializers/secret-engine-test.js
Labels: hashicorp-contributed-pr, vault-update

#23619 Update enterprise vs hcp alerts
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/config-group-policy-application.mdx
  website/content/api-docs/system/control-group.mdx
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/replication/index.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
  website/content/api-docs/system/sealwrap-rewrap.mdx
  website/content/api-docs/system/storage/raftautosnapshots.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/content/docs/enterprise/license/index.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/mfa/mfa-duo.mdx
  website/content/docs/enterprise/mfa/mfa-okta.mdx
  website/content/docs/enterprise/mfa/mfa-pingid.mdx
  website/content/docs/enterprise/mfa/mfa-totp.mdx
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/content/docs/enterprise/redundancy-zones.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/enterprise/sentinel/examples.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/enterprise/sentinel/properties.mdx
  website/content/partials/alerts/enterprise-and-hcp-plus.mdx
  website/content/partials/alerts/enterprise-and-hcp-use.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23626 [DOCS] Manually backport of Update enterprise vs hcp alerts (#23619) - 1.14
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/config-group-policy-application.mdx
  website/content/api-docs/system/control-group.mdx
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/replication/index.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
  website/content/api-docs/system/sealwrap-rewrap.mdx
  website/content/api-docs/system/storage/raftautosnapshots.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/content/docs/enterprise/license/index.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/mfa/mfa-duo.mdx
  website/content/docs/enterprise/mfa/mfa-okta.mdx
  website/content/docs/enterprise/mfa/mfa-pingid.mdx
  website/content/docs/enterprise/mfa/mfa-totp.mdx
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/content/docs/enterprise/redundancy-zones.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/enterprise/sentinel/examples.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/enterprise/sentinel/properties.mdx
  website/content/partials/alerts/enterprise-and-hcp-plus.mdx
  website/content/partials/alerts/enterprise-and-hcp-use.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23627 [DOCS] Manually backport of Update enterprise vs hcp alerts (#23619) - 1..15
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/config-group-policy-application.mdx
  website/content/api-docs/system/control-group.mdx
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/replication/index.mdx
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
  website/content/api-docs/system/sealwrap-rewrap.mdx
  website/content/api-docs/system/storage/raftautosnapshots.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/content/docs/enterprise/license/index.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/mfa/mfa-duo.mdx
  website/content/docs/enterprise/mfa/mfa-okta.mdx
  website/content/docs/enterprise/mfa/mfa-pingid.mdx
  website/content/docs/enterprise/mfa/mfa-totp.mdx
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/content/docs/enterprise/redundancy-zones.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/enterprise/sentinel/examples.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/enterprise/sentinel/properties.mdx
  website/content/partials/alerts/enterprise-and-hcp-plus.mdx
  website/content/partials/alerts/enterprise-and-hcp-use.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23277 UI: [VAULT-19783] Set up root token warning modal
  changelog/23277.txt
  ui/app/components/dashboard/vault-version-title.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/services/auth.js
  ui/app/services/namespace.js
  ui/app/templates/components/dashboard/vault-version-title.hbs
  ui/app/templates/components/namespace-link.hbs
  ui/app/templates/components/namespace-picker.hbs
  ui/app/templates/vault/cluster.hbs
Labels: ui, hashicorp-contributed-pr

#23628 UI: prep for running button codemod
  ui/app/components/modal-form/policy-template.hbs
  ui/app/components/modal-form/policy-template.js
  ui/app/components/policy-form.hbs
  ui/app/components/tool-actions-form.js
  ui/app/components/tool-unwrap.js
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/tabs-component.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/helper-classes/colors.scss
  ui/app/templates/components/console/command-input.hbs
  ui/app/templates/components/console/ui-panel.hbs
  ui/app/templates/components/secret-list/ssh-role-item.hbs
  ui/app/templates/components/tool-actions-form.hbs
  ui/app/templates/components/tool-unwrap.hbs
  ui/app/templates/vault/cluster/policies/create.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/tests/integration/components/search-select-with-modal-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#23551 Add method and path for Read the client count configuration
  website/content/api-docs/system/internal-counters.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, backport/1.15.x

#23631 Backport of Add method and path for Read the client count configuration into release/1.14.x
  website/content/api-docs/system/internal-counters.mdx
Labels: hashicorp-contributed-pr

#23632 Backport of Add method and path for Read the client count configuration into release/1.15.x
  website/content/api-docs/system/internal-counters.mdx
Labels: hashicorp-contributed-pr

#23630 Backport of Implement user lockout log into release/1.14.x
  changelog/23140.txt
  command/server.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  internalshared/configutil/config.go
  internalshared/configutil/merge.go
  vault/core.go
  vault/logical_system_user_lockout.go
  vault/request_handling.go
Labels: hashicorp-contributed-pr

#23595 Add known issues for collapsed navbar
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/ui-collapsed-navbar.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23580 Upgrade to HDS 2.13.0
  changelog/23580.txt
  ui/package.json
  ui/yarn.lock
Labels: ui, hashicorp-contributed-pr

#23636 command/server: fix bug with sigusr2 where pprof files were not closed
  changelog/23636.txt
  command/server.go
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23634 Teach stubmaker how to work with methods, not just funcs.
  http/util_stubs_oss.go
  tools/stubmaker/main.go
  vault/core.go
  vault/core_stubs_oss.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23637 Backport of command/server: fix bug with sigusr2 where pprof files were not closed into release/1.12.x
  changelog/23636.txt
  command/server.go
Labels: hashicorp-contributed-pr

#23639 Backport of command/server: fix bug with sigusr2 where pprof files were not closed into release/1.14.x
  changelog/23636.txt
  command/server.go
Labels: hashicorp-contributed-pr

#23641 [DOCS] Fix anchor ID and add link to admin namespace guide
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#23642 Backport of [DOCS] Fix anchor ID and add link to admin namespace guide into release/1.14.x
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23643 Backport of [DOCS] Fix anchor ID and add link to admin namespace guide into release/1.15.x
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23647 remove unused param from entEnableFourClusterDev
  command/command_stubs_oss.go
  command/server.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23633 Button Conversion Part 1
  ui/app/styles/core/buttons.scss
  ui/lib/kmip/addon/templates/components/edit-form-kmip-role.hbs
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/lib/kubernetes/addon/components/page/credentials.hbs
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
  ui/lib/kubernetes/addon/components/page/roles.hbs
  ui/lib/kv/addon/components/kv-version-dropdown.hbs
  ui/lib/kv/addon/components/page/list.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.hbs
  ui/lib/kv/addon/components/page/secrets/create.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.hbs
  ui/lib/ldap/addon/components/page/configure.hbs
  ui/lib/ldap/addon/components/page/libraries.hbs
  ui/lib/ldap/addon/components/page/library/check-out.hbs
  ui/lib/ldap/addon/components/page/library/create-and-edit.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/ldap/addon/components/page/overview.hbs
  ui/lib/ldap/addon/components/page/role/create-and-edit.hbs
  ui/lib/ldap/addon/components/page/role/credentials.hbs
  ui/lib/ldap/addon/components/page/roles.hbs
  ui/scripts/codemods/hds/button.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr
