Repository hashicorp/vault, pull requests merged in 2023-12, with the labels that each got.

#24299 UI: HDS adoption update <AlertInline> component to use Hds::Alert
  changelog/24299.txt
  ui/app/components/auth-saml.hbs
  ui/app/styles/components/doc-link.scss
  ui/app/templates/components/auth-form-options.hbs
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-jwt.hbs
  ui/app/templates/components/clients/attribution.hbs
  ui/app/templates/components/date-dropdown.hbs
  ui/app/templates/components/keymgmt/distribute.hbs
  ui/app/templates/components/mfa/mfa-form.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/oidc/assignment-form.hbs
  ui/app/templates/components/oidc/client-form.hbs
  ui/app/templates/components/oidc/key-form.hbs
  ui/app/templates/components/oidc/provider-form.hbs
  ui/app/templates/components/oidc/scope-form.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/lib/core/addon/components/alert-inline.hbs
  ui/lib/core/addon/components/alert-inline.js
  ui/lib/core/addon/components/kv-object-editor.hbs
  ui/lib/core/addon/components/string-list.hbs
  ui/lib/core/addon/components/text-file.hbs
  ui/lib/core/addon/templates/components/edit-form.hbs
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.hbs
  ui/lib/kv/addon/components/page/secrets/create.hbs
  ui/lib/ldap/addon/components/page/configure.hbs
  ui/lib/ldap/addon/components/page/library/create-and-edit.hbs
  ui/lib/ldap/addon/components/page/role/create-and-edit.hbs
  ui/lib/pki/addon/components/page/pki-configuration-edit.hbs
  ui/lib/pki/addon/components/page/pki-issuer-edit.hbs
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-key-form.hbs
  ui/lib/pki/addon/components/pki-key-import.hbs
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/components/pki-role-generate.hbs
  ui/lib/pki/addon/components/pki-sign-intermediate-form.hbs
  ui/lib/pki/addon/components/pki-tidy-form.hbs
  ui/tests/integration/components/alert-inline-test.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
  ui/tests/integration/components/ldap/page/configure-test.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
Labels: ui, hashicorp-contributed-pr

#24320 Split out reloadSealsEnt stub
  vault/core_stubs_oss.go
  vault/reload_seal_stubs_oss.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24297 fix `-log-file` so that it uses the correct name and only adds timestamps on rotation
  changelog/24297.txt
  command/agent.go
  command/proxy.go
  command/server.go
  helper/logging/logfile.go
  helper/logging/logger.go
  helper/logging/logger_test.go
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/commands/server.mdx
Labels: docs, bug, core, core/log, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24323 Backport of fix `-log-file` so that it uses the correct name and only adds timestamps on rotation into release/1.15.x
  changelog/24297.txt
  command/agent.go
  command/proxy.go
  command/server.go
  helper/logging/logfile.go
  helper/logging/logger.go
  helper/logging/logger_test.go
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/commands/server.mdx
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24327 Backport of Consistently use OperationHandler for entity paths into release/1.15.x
  vault/identity_store_entities.go
Labels: hashicorp-contributed-pr

#24325 Always forward entity merge requests from perfStandby
  changelog/24325.txt
  vault/identity_store_entities.go
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24330 Backport of Always forward entity merge requests from perfStandby into release/1.15.x
  changelog/24325.txt
  vault/identity_store_entities.go
Labels: hashicorp-contributed-pr

#24331 Backport of Always forward entity merge requests from perfStandby into release/1.14.x
  changelog/24325.txt
  vault/identity_store_entities.go
Labels: hashicorp-contributed-pr

#24187 UI: Add list to adapter query param
  ui/app/adapters/config-ui/message.js
Labels: ui, hashicorp-contributed-pr

#24326 Backport of Consistently use OperationHandler for entity paths into release/1.13.x
  vault/identity_store_entities.go
Labels: hashicorp-contributed-pr

#24334 Backport of Always forward entity merge requests from perfStandby into release/1.13.x
  changelog/24325.txt
  vault/identity_store_entities.go
Labels: hashicorp-contributed-pr

#24329 changelog++
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24237 Remove release-engineering as codeowners
  CODEOWNERS
Labels: hashicorp-contributed-pr

#24346 Update LICENSE for 1.15.3
  LICENSE
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24283 UI: Update replication nav
  changelog/24283.txt
  ui/app/app.js
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/models/cluster.js
  ui/app/styles/components/action-block.scss
  ui/lib/core/addon/components/replication-summary-card.hbs
  ui/lib/core/addon/components/replication-summary-card.js
  ui/lib/core/addon/templates/components/replication-actions.hbs
  ui/lib/core/addon/templates/components/replication-header.hbs
  ui/lib/core/addon/templates/components/replication-mode-summary.hbs
  ui/lib/core/addon/templates/components/replication-summary-card.hbs
  ui/lib/replication/addon/engine.js
  ui/lib/replication/addon/templates/application.hbs
  ui/lib/replication/addon/templates/components/replication-summary.hbs
  ui/tests/acceptance/enterprise-replication-modes-test.js
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/enterprise-replication-unsupported-test.js
  ui/tests/acceptance/enterprise-sidebar-nav-test.js
  ui/tests/helpers/replication.js
  ui/tests/integration/components/replication-summary-card-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
Labels: ui, hashicorp-contributed-pr

#24264 Update LICENSE
  LICENSE
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24343 Use our heartbeat echo RPCs to estimate clock skew, expose it in status APIs
  api/replication_status.go
  api/sys_hastatus.go
  api/sys_health.go
  changelog/24343.txt
  http/sys_health.go
  scripts/protocversioncheck.sh
  sdk/helper/testcluster/util.go
  vault/cluster/simulations.go
  vault/core.go
  vault/external_tests/standby/standby_test.go
  vault/ha.go
  vault/logical_system.go
  vault/request_forwarding_rpc.go
  vault/request_forwarding_service.pb.go
  vault/request_forwarding_service.proto
Labels: hashicorp-contributed-pr

#24336 Only use the short persistKeyring timeout for encryption count tracking
  changelog/24336.txt
  vault/barrier_aes_gcm.go
Labels: hashicorp-contributed-pr, backport/1.15.x

#24308 Backport 1.15.x: For showing JSON editor for complex secret in KV details view
  changelog/24290.txt
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/components/page/secrets/create.hbs
  ui/tests/integration/components/kv/kv-data-fields-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
Labels: ui, hashicorp-contributed-pr

#24351 Make it possible to skip the seal re-wrap in progress check
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24262 UI: handle reduced disclosure endpoints
  ui/app/adapters/cluster.js
  ui/app/components/app-footer.hbs
  ui/app/components/app-footer.js
  ui/app/components/dashboard/vault-version-title.js
  ui/app/components/logo-edition.hbs
  ui/app/controllers/vault.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/controllers/vault/cluster/settings/seal.js
  ui/app/controllers/vault/cluster/unseal.js
  ui/app/routes/vault.js
  ui/app/routes/vault/cluster.js
  ui/app/routes/vault/cluster/license.js
  ui/app/routes/vault/cluster/logout.js
  ui/app/routes/vault/cluster/policies/index.js
  ui/app/services/control-group.js
  ui/app/services/version.js
  ui/app/styles/components/env-banner.scss
  ui/app/templates/components/dashboard/vault-version-title.hbs
  ui/app/templates/vault.hbs
  ui/lib/core/addon/helpers/is-version.js
  ui/lib/core/app/helpers/is-version.js
  ui/mirage/handlers/base.js
  ui/tests/acceptance/enterprise-license-banner-test.js
  ui/tests/acceptance/enterprise-reduced-disclosure-test.js
  ui/tests/acceptance/enterprise-sidebar-nav-test.js
  ui/tests/integration/components/app-footer-test.js
  ui/tests/integration/components/dashboard/overview-test.js
  ui/tests/integration/components/license-banners-test.js
  ui/tests/integration/components/link-status-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
  ui/tests/integration/components/pki/page/pki-configuration-details-test.js
  ui/tests/integration/components/pki/page/pki-configuration-edit-test.js
  ui/tests/integration/components/pki/pki-tidy-form-test.js
  ui/tests/integration/components/sidebar/frame-test.js
  ui/tests/pages/auth.js
  ui/tests/unit/adapters/kv/data-test.js
  ui/tests/unit/services/control-group-test.js
  ui/tests/unit/services/version-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24354 Buffer body read up to MaxRequestSize
  helper/forwarding/util.go
  http/handler.go
  http/handler_test.go
  http/util.go
  sdk/logical/request.go
  sdk/logical/request_test.go
  vault/core.go
  vault/logical_system_raft.go
  vault/request_handling.go
Labels: pr/no-changelog, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24279 Update Azure Secrets docs
  website/content/api-docs/secret/azure.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#24348 Cherry pick license updates from main
  LICENSE
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24355 Add Chroot Namespace to UI Resultant Response
  http/handler.go
  http/logical.go
  http/logical_test.go
  http/sys_seal.go
  sdk/logical/request.go
  vault/logical_system.go
  vault/logical_system_integ_test.go
  vault/logical_system_paths.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24362 Backport of Only use the short persistKeyring timeout for encryption count tracking into release/1.13.x
  changelog/24336.txt
  vault/barrier_aes_gcm.go
Labels: hashicorp-contributed-pr

#24363 Backport of Only use the short persistKeyring timeout for encryption count tracking into release/1.14.x
  changelog/24336.txt
  vault/barrier_aes_gcm.go
Labels: hashicorp-contributed-pr

#24356 Update VSO docs for v0.4.1
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24370 Backport of Update VSO docs for v0.4.1 into release/1.15.x
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24365 Buffer body read up to MaxRequestSize (#24354)
  helper/forwarding/util.go
  http/handler.go
  http/handler_test.go
  http/util.go
  sdk/logical/request.go
  vault/core.go
  vault/logical_system_raft.go
  vault/request_handling.go
Labels: hashicorp-contributed-pr

#24357 Adjust `TestSudoPaths` to use minimal cluster
  vault/external_tests/api/sudo_paths_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24375 UI: fix ent tests
  ui/tests/acceptance/enterprise-reduced-disclosure-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24364 Document and augment tests that PKI accepts 8192 bit RSA keys
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_manage_keys_test.go
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24379 UI: handle reduced disclosure on replication endpoints
  ui/app/adapters/cluster.js
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/models/cluster.js
  ui/app/routes/vault/cluster/dashboard.js
  ui/app/templates/components/dashboard/overview.hbs
  ui/lib/replication/addon/routes/application.js
  ui/mirage/handlers/reduced-disclosure.js
  ui/tests/acceptance/enterprise-reduced-disclosure-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24340 Sync Overview
  ui/app/adapters/sync/association.js
  ui/app/adapters/sync/destination.js
  ui/app/app.js
  ui/app/serializers/sync/association.js
  ui/app/serializers/sync/destination.js
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/sync/addon/components/secrets/landing-cta.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/engine.js
  ui/lib/sync/addon/routes/secrets/overview.ts
  ui/lib/sync/addon/templates/secrets/overview.hbs
  ui/mirage/handlers/sync.js
  ui/mirage/scenarios/sync.js
  ui/public/images/sync-landing-2.png
  ui/tests/helpers/general-selectors.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
  ui/tests/unit/adapters/sync/associations-test.js
  ui/tests/unit/adapters/sync/destinations-test.js
  ui/tests/unit/serializers/sync/associations-test.js
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/adapters/sync/association.d.ts
  ui/types/vault/adapters/sync/destination.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24366 UI: HDS Adoption upgrade to design-system-components: 3.3.0 and ember-flight-icons: 4.0.4
  ui/app/components/sidebar/user-menu.hbs
  ui/app/styles/helper-classes/layout.scss
  ui/lib/core/addon/components/certificate-card.hbs
  ui/lib/core/addon/components/code-snippet.hbs
  ui/lib/core/addon/components/copy-secret-dropdown.hbs
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/json-editor.hbs
  ui/lib/core/addon/components/masked-input.hbs
  ui/lib/kv/addon/components/page/secret/paths.hbs
  ui/package.json
  ui/tests/acceptance/pki/pki-cross-sign-test.js
  ui/tests/integration/components/certificate-card-test.js
  ui/tests/integration/components/copy-secret-dropdown-test.js
  ui/tests/integration/components/info-table-row-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-paths-test.js
  ui/tests/integration/components/oidc/scope-form-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/sidebar/user-menu-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24384 Backport of Document and augment tests that PKI accepts 8192 bit RSA keys into release/1.15.x
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_manage_keys_test.go
  website/content/api-docs/secret/pki.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24383 Add_Chroot_Namespace_In_Response
  http/handler.go
  http/logical.go
  http/logical_test.go
  http/sys_seal.go
  sdk/logical/request.go
  vault/logical_system.go
  vault/logical_system_integ_test.go
  vault/logical_system_paths.go
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#24395 update testing.go: `initCores`
  helper/testhelpers/corehelpers/corehelpers.go
  vault/testing.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24388 Remove is-version Helper
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/sync/addon/components/secrets/landing-cta.hbs
  ui/lib/sync/addon/components/secrets/landing-cta.ts
  ui/lib/sync/addon/components/sync-header.hbs
  ui/lib/sync/addon/components/sync-header.ts
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/landing-cta-test.js
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
  ui/tests/integration/components/sync/sync-header-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24397 Common Selectors for Sync Tests
  ui/tests/helpers/general-selectors.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
  ui/tests/integration/components/sync/sync-header-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24332 identity/oidc: lazily generate default key
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_test.go
Labels: pr/no-changelog, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24396 Clarify Vault versions, some upgrade guidance
  website/content/docs/install.mdx
  website/content/docs/upgrading/index.mdx
  website/content/partials/versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24410 UI: Update breadcrumb selectors for enterprise tests
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/enterprise-transform-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24398 Fix recovery mode check for seal migration configuration
  command/server.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24408 Backport of identity/oidc: lazily generate default key into release/1.14.x
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_test.go
Labels: hashicorp-contributed-pr

#24409 Backport of identity/oidc: lazily generate default key into release/1.15.x
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_test.go
Labels: hashicorp-contributed-pr

#24373 Add PATCH to CORS allowed request methods
  changelog/24373.txt
  http/cors.go
  http/handler_test.go
Labels: hashicorp-contributed-pr

#24416 Backport of updated setup/teardown audit code and ordering within broker registration into release/1.15.x
  vault/audit.go
  vault/audit_broker.go
  vault/mount_test.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24414 docs: adds saml to client count entity assignment table
  website/content/partials/authn-names.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24417 Backport of docs: adds saml to client count entity assignment table into release/1.15.x
  website/content/partials/authn-names.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24415 PKI: Refactor storage of certificates into a common method
  builtin/logical/pki/backend.go
  builtin/logical/pki/issuing/issue_common.go
  builtin/logical/pki/parsing/certificate.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/pki_backend/common.go
  builtin/logical/pki/util.go
Labels: secret/pki, pr/no-changelog, hashicorp-contributed-pr

#24420 Add stub for stopping partial wrap monitoring to CE
  vault/core.go
  vault/seal_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24418 Fix two potential channel hangs in access.tryDecrypt
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24421 Backport of Add stub for stopping partial wrap monitoring to CE into release/1.15.x
  vault/core.go
  vault/seal_stubs_oss.go
Labels: hashicorp-contributed-pr

#24422 Backport of Fix two potential channel hangs in access.tryDecrypt into release/1.15.x
  vault/seal/seal.go
Labels: hashicorp-contributed-pr

#24404 Add directory paths to KV capabilities checks
  changelog/24404.txt
  ui/app/models/kv/metadata.js
  ui/lib/kv/addon/components/page/list.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/policy-generator/kv.js
Labels: ui, bug, hashicorp-contributed-pr, backport/1.15.x

#24381 quotas: Move storage updates into quotas package
  vault/core.go
  vault/logical_system_quotas.go
  vault/quotas/quotas.go
  vault/quotas/quotas_rate_limit_test.go
  vault/quotas/quotas_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24428 use a stop chan to prevent sends on the closed result channel
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24372 Make leaderCheckInterval configurable.
  vault/core.go
  vault/external_tests/raft/raft_autopilot_test.go
  vault/ha.go
  vault/testing.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24430 Make sure stopCh is closed first
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24432 Backport stopCh for tryDecrypt to 1.15.x
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24427 UI: Create enable input component
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/lib/core/addon/components/enable-input.hbs
  ui/lib/core/addon/components/enable-input.ts
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/text-file.hbs
  ui/lib/core/app/components/enable-input.js
  ui/tests/integration/components/enable-input-test.js
  ui/tests/integration/components/form-field-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24425 Update docs for VSO v0.4.2
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24434 Backport of Update docs for VSO v0.4.2 into release/1.15.x
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24436 move stopPartialSealRewrapping out
  vault/external_tests/raft/raft_autopilot_test.go
  vault/seal_rewwrap_stubs_oss.go
  vault/seal_stubs_oss.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24442 Bump go-eventlogger to v0.2.8
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog, hashicorp-contributed-pr

#24444 Backport of docs: adds domain to OIDC Google Workspace integration into release/1.15.x
  website/content/docs/auth/jwt/oidc-providers/google.mdx
Labels: hashicorp-contributed-pr

#24448 Remove ui_copywrite Pre-commit Hook
  .hooks/pre-commit
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24446 Backport for 1.15.x: add full path to KV v2 capabilities check
  changelog/24404.txt
  ui/app/models/kv/metadata.js
  ui/lib/kv/addon/components/page/list.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/policy-generator/kv.js
Labels: ui, hashicorp-contributed-pr

#24349 [QT-627] enos: add `pkcs11` seal testing with softhsm
  enos/enos-globals.hcl
  enos/enos-modules.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_local/main.tf
  enos/modules/install_packages/main.tf
  enos/modules/install_packages/scripts/install-packages.sh
  enos/modules/seal_awskms/main.tf
  enos/modules/seal_key_shamir/main.tf
  enos/modules/seal_pkcs11/main.tf
  enos/modules/seal_shamir/main.tf
  enos/modules/softhsm_create_vault_keys/main.tf
  enos/modules/softhsm_create_vault_keys/scripts/create-keys.sh
  enos/modules/softhsm_create_vault_keys/scripts/get-keys.sh
  enos/modules/softhsm_distribute_vault_keys/main.tf
  enos/modules/softhsm_distribute_vault_keys/scripts/distribute-token.sh
  enos/modules/softhsm_init/main.tf
  enos/modules/softhsm_init/scripts/init-softhsm.sh
  enos/modules/softhsm_install/main.tf
  enos/modules/softhsm_install/scripts/find-shared-object.sh
  enos/modules/start_vault/main.tf
  enos/modules/start_vault/variables.tf
  enos/modules/target_ec2_instances/variables.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/scripts/create-audit-log-dir.sh
  enos/modules/vault_cluster/scripts/enable-audit-devices.sh
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
  enos/modules/vault_cluster/scripts/install-packages.sh
  enos/modules/vault_cluster/scripts/start-audit-socket-listener.sh
  enos/modules/vault_cluster/scripts/vault-write-license.sh
  enos/modules/vault_cluster/variables.tf
  enos/modules/vault_verify_raft_auto_join_voter/scripts/verify-raft-auto-join-voter.sh
  enos/modules/vault_wait_for_leader/main.tf
  enos/modules/vault_wait_for_seal_rewrap/main.tf
  enos/modules/vault_wait_for_seal_rewrap/scripts/wait-for-seal-rewrap.sh
  enos/modules/verify_seal_type/main.tf
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24452 Add changelog for 1.15.4, 1.14.8, 1.13.12
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24443 Update recovery mode guard to account for migrating away from Shamir
  command/server.go
  vault/core.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24449 Backport of Handle show and edit views for old KV urls into release/1.15.x
  changelog/24339.txt
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/tests/acceptance/not-found-test.js
  ui/tests/acceptance/redirect-to-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
Labels: ui, hashicorp-contributed-pr

#24455 Backport of [QT-627] enos: add `pkcs11` seal testing with softhsm into release/1.15.x
  enos/enos-globals.hcl
  enos/enos-modules.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_local/main.tf
  enos/modules/install_packages/main.tf
  enos/modules/install_packages/scripts/install-packages.sh
  enos/modules/seal_awskms/main.tf
  enos/modules/seal_key_shamir/main.tf
  enos/modules/seal_pkcs11/main.tf
  enos/modules/seal_shamir/main.tf
  enos/modules/softhsm_create_vault_keys/main.tf
  enos/modules/softhsm_create_vault_keys/scripts/create-keys.sh
  enos/modules/softhsm_create_vault_keys/scripts/get-keys.sh
  enos/modules/softhsm_distribute_vault_keys/main.tf
  enos/modules/softhsm_distribute_vault_keys/scripts/distribute-token.sh
  enos/modules/softhsm_init/main.tf
  enos/modules/softhsm_init/scripts/init-softhsm.sh
  enos/modules/softhsm_install/main.tf
  enos/modules/softhsm_install/scripts/find-shared-object.sh
  enos/modules/start_vault/main.tf
  enos/modules/start_vault/variables.tf
  enos/modules/target_ec2_instances/variables.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/scripts/create-audit-log-dir.sh
  enos/modules/vault_cluster/scripts/enable-audit-devices.sh
  enos/modules/vault_cluster/scripts/enable_audit_logging.sh
  enos/modules/vault_cluster/scripts/install-packages.sh
  enos/modules/vault_cluster/scripts/start-audit-socket-listener.sh
  enos/modules/vault_cluster/scripts/vault-write-license.sh
  enos/modules/vault_cluster/variables.tf
  enos/modules/vault_verify_raft_auto_join_voter/scripts/verify-raft-auto-join-voter.sh
  enos/modules/vault_wait_for_leader/main.tf
  enos/modules/vault_wait_for_seal_rewrap/main.tf
  enos/modules/vault_wait_for_seal_rewrap/scripts/wait-for-seal-rewrap.sh
  enos/modules/verify_seal_type/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24454 Backport of [QT-627] enos: add `pkcs11` seal testing with softhsm into release/1.14.x
  enos/enos-globals.hcl
  enos/enos-modules.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_local/main.tf
  enos/modules/install_packages/main.tf
  enos/modules/install_packages/scripts/install-packages.sh
  enos/modules/seal_awskms/main.tf
  enos/modules/seal_pkcs11/main.tf
  enos/modules/seal_shamir/main.tf
  enos/modules/softhsm_create_vault_keys/main.tf
  enos/modules/softhsm_create_vault_keys/scripts/create-keys.sh
  enos/modules/softhsm_create_vault_keys/scripts/get-keys.sh
  enos/modules/softhsm_distribute_vault_keys/main.tf
  enos/modules/softhsm_distribute_vault_keys/scripts/distribute-token.sh
  enos/modules/softhsm_init/main.tf
  enos/modules/softhsm_init/scripts/init-softhsm.sh
  enos/modules/softhsm_install/main.tf
  enos/modules/softhsm_install/scripts/find-shared-object.sh
  enos/modules/start_vault/main.tf
  enos/modules/start_vault/variables.tf
  enos/modules/target_ec2_instances/variables.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/scripts/create-audit-log-dir.sh
  enos/modules/vault_cluster/scripts/enable-audit-devices.sh
  enos/modules/vault_cluster/scripts/start-audit-socket-listener.sh
  enos/modules/vault_cluster/variables.tf
  enos/modules/vault_verify_raft_auto_join_voter/scripts/verify-raft-auto-join-voter.sh
  enos/modules/vault_wait_for_leader/main.tf
  enos/modules/vault_wait_for_seal_rewrap/main.tf
  enos/modules/vault_wait_for_seal_rewrap/scripts/wait-for-seal-rewrap.sh
  enos/modules/verify_seal_type/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24456 Bumped product version to 1.15.5.
  version/VERSION
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24453 Backport of [QT-627] enos: add `pkcs11` seal testing with softhsm into release/1.13.x
  enos/enos-globals.hcl
  enos/enos-modules.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/build_local/main.tf
  enos/modules/install_packages/main.tf
  enos/modules/install_packages/scripts/install-packages.sh
  enos/modules/seal_awskms/main.tf
  enos/modules/seal_pkcs11/main.tf
  enos/modules/seal_shamir/main.tf
  enos/modules/softhsm_create_vault_keys/main.tf
  enos/modules/softhsm_create_vault_keys/scripts/create-keys.sh
  enos/modules/softhsm_create_vault_keys/scripts/get-keys.sh
  enos/modules/softhsm_distribute_vault_keys/main.tf
  enos/modules/softhsm_distribute_vault_keys/scripts/distribute-token.sh
  enos/modules/softhsm_init/main.tf
  enos/modules/softhsm_init/scripts/init-softhsm.sh
  enos/modules/softhsm_install/main.tf
  enos/modules/softhsm_install/scripts/find-shared-object.sh
  enos/modules/start_vault/main.tf
  enos/modules/start_vault/variables.tf
  enos/modules/target_ec2_instances/variables.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/scripts/create-audit-log-dir.sh
  enos/modules/vault_cluster/scripts/enable-audit-devices.sh
  enos/modules/vault_cluster/scripts/start-audit-socket-listener.sh
  enos/modules/vault_cluster/variables.tf
  enos/modules/vault_verify_raft_auto_join_voter/scripts/verify-raft-auto-join-voter.sh
  enos/modules/vault_wait_for_leader/main.tf
  enos/modules/vault_wait_for_seal_rewrap/main.tf
  enos/modules/vault_wait_for_seal_rewrap/scripts/wait-for-seal-rewrap.sh
  enos/modules/verify_seal_type/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24115 docs: fixes (#24094)
  website/content/docs/auth/ldap.mdx
  website/content/docs/commands/secrets/enable.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, backport/1.15.x

#24458 Backport of docs: fixes (#24094) into release/1.13.x
  website/content/docs/auth/ldap.mdx
  website/content/docs/commands/secrets/enable.mdx
Labels: hashicorp-contributed-pr

#24459 Backport of docs: fixes (#24094) into release/1.14.x
  website/content/docs/auth/ldap.mdx
  website/content/docs/commands/secrets/enable.mdx
Labels: hashicorp-contributed-pr

#24460 Backport of docs: fixes (#24094) into release/1.15.x
  website/content/docs/auth/ldap.mdx
  website/content/docs/commands/secrets/enable.mdx
Labels: hashicorp-contributed-pr

#24437 docs: clarified the MS SQL EKM provider's authentication behavior, and the implications for AppRole configuration
  website/content/docs/platform/mssql/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24464 Backport of docs: clarified the MS SQL EKM provider's authentication behavior, and the implications for AppRole configuration into release/1.15.x
  website/content/docs/platform/mssql/installation.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24445 Docs updates about redirection and metrics
  website/content/docs/configuration/telemetry.mdx
  website/content/docs/enterprise/performance-standby.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24451 Make testCluster_Forwarding more tolerant of timing issues
  vault/cluster_test.go
  vault/testing.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24263 VAULT-21607: Provide Management Endpoints for Vault UI Custom Messages
  sdk/logical/error.go
  sdk/logical/response_util.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_custom_messages.go
  vault/logical_system_custom_messages_test.go
  vault/logical_system_paths.go
  vault/ui_custom_messages/entry.go
  vault/ui_custom_messages/entry_test.go
  vault/ui_custom_messages/filter.go
  vault/ui_custom_messages/filter_test.go
  vault/ui_custom_messages/manager.go
  vault/ui_custom_messages/manager_test.go
  vault/ui_custom_messages/message.go
  vault/ui_custom_messages/message_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24473 Fix channel close race panic in tryDecrypt by using a waitgroup
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24470 Backport of release log gate if disable-gated-logs flag is set into release/1.15.x
  changelog/24280.txt
  command/agent.go
  command/commands.go
  command/log_flags.go
  command/proxy.go
  command/server.go
Labels: hashicorp-contributed-pr

#24474 Backport of Fix channel close race panic in tryDecrypt by using a waitgroup into release/1.15.x
  vault/seal/seal.go
Labels: hashicorp-contributed-pr

#24450 Sync Destination List Refresh Bug
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24475 release log gate if disable-gated-logs flag is set (#24280)
  changelog/24280.txt
  command/agent.go
  command/commands.go
  command/log_flags.go
  command/server.go
Labels: hashicorp-contributed-pr

#24462 enos: always test from the same branch as the revision
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24483 Fix templating mention in Proxy docs
  website/content/docs/agent-and-proxy/proxy/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24484 Fix race in the tryDecrypt waitgroup
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24485 Backport of enos: don't include consul_version in autopilot into release/1.13.x
  enos/enos-scenario-autopilot.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24487 Backport of enos: don't include consul_version in autopilot into release/1.15.x
  enos/enos-scenario-autopilot.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24486 Backport of enos: don't include consul_version in autopilot into release/1.14.x
  enos/enos-scenario-autopilot.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24488 Backport of Fix race in the tryDecrypt waitgroup into release/1.15.x
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24447 KV Suggestion Input
  ui/lib/core/addon/components/filter-input.hbs
  ui/lib/core/addon/components/filter-input.ts
  ui/lib/core/addon/components/kv-suggestion-input.hbs
  ui/lib/core/addon/components/kv-suggestion-input.ts
  ui/lib/core/app/components/kv-suggestion-input.js
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/tests/helpers/general-selectors.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/filter-input-test.js
  ui/tests/integration/components/kv-suggestion-input-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24490 Fix flaky restore test (TestLeaseCacheRestore_expired)
  command/agentproxyshared/cache/lease_cache_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24413 Secrets Sync UI: Editing a destination
  ui/app/adapters/application.js
  ui/app/adapters/sync/destination.js
  ui/app/models/sync/destination.js
  ui/app/models/sync/destinations/aws-sm.js
  ui/app/models/sync/destinations/azure-kv.js
  ui/app/models/sync/destinations/gcp-sm.js
  ui/app/models/sync/destinations/gh.js
  ui/app/models/sync/destinations/vercel-project.js
  ui/app/serializers/sync/destination.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/helpers/sync-destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/templates/secrets/destinations/destination/edit.hbs
  ui/mirage/factories/sync-destination.js
  ui/mirage/handlers/sync.js
  ui/tests/helpers/general-selectors.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/secrets-test.js
  ui/tests/unit/adapters/sync/destinations-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24312 Vault-21960: Add docker tests for reloading seal configuration on SIGHUP
  vault/external_tests/seal_binary/seal_docker_util.go
  vault/external_tests/seal_binary/seal_sighup_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24491 Sync Success Banner
  ui/lib/core/addon/components/kv-suggestion-input.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24481 UI: a11y sidebranch - DOM
  ui/app/components/tool-actions-form.js
  ui/app/styles/components/doc-link.scss
  ui/app/styles/components/empty-state-component.scss
  ui/app/styles/core/link.scss
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/dashboard/secrets-engines-card.hbs
  ui/app/templates/components/link-status.hbs
  ui/app/templates/components/oidc/client-form.hbs
  ui/app/templates/components/oidc/key-form.hbs
  ui/app/templates/components/oidc/provider-form.hbs
  ui/app/templates/components/secret-edit.hbs
  ui/app/templates/error.hbs
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/app/templates/vault/cluster/access/oidc.hbs
  ui/lib/core/addon/components/empty-state.hbs
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/core/addon/components/radio-card.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/core/addon/templates/components/replication-secondary-card.hbs
  ui/lib/kubernetes/addon/components/tab-page-header.hbs
  ui/lib/kv/addon/components/page/configuration.hbs
  ui/lib/kv/addon/components/page/list.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/lib/kv/addon/components/page/secret/paths.hbs
  ui/lib/kv/addon/templates/error.hbs
  ui/lib/ldap/addon/components/page/library/details.hbs
  ui/lib/ldap/addon/components/tab-page-header.hbs
  ui/lib/pki/addon/components/pki-page-header.hbs
  ui/tests/helpers/kubernetes/overview.js
  ui/tests/helpers/pki/overview.js
  ui/tests/integration/components/overview-card-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24345 VAULT-21157: Reduce Technical Debt
  vault/core.go
  vault/core_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24494 use Sync secrets everywhere (remove new)
  ui/lib/sync/addon/components/secrets/destination-header.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/tests/integration/components/sync/secrets/destination-header-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/details-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/secrets-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24496 Sync Destinations List Filter Bug
  ui/app/serializers/sync/destination.js
  ui/lib/sync/addon/components/secrets/page/destinations.ts
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/general-selectors.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24497 UI Secrets sync: Add purge query param to delete endpoint
  ui/app/adapters/sync/destination.js
  ui/tests/unit/adapters/sync/destinations-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24493 Audit related foibles
  builtin/audit/file/backend.go
  builtin/audit/socket/backend.go
  builtin/audit/syslog/backend.go
  helper/builtinplugins/builtinplugins_test.go
  helper/testhelpers/corehelpers/corehelpers.go
  vault/testing.go
Labels: core/audit, test, pr/no-changelog, hashicorp-contributed-pr

#24472 New database plugin API to reload by plugin name
  builtin/logical/database/backend.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  changelog/24472.txt
  website/content/api-docs/secret/databases/index.mdx
Labels: hashicorp-contributed-pr

#24501 Update ACME entity assignment examples
  website/content/docs/concepts/client-count/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24506 Backport of Update ACME entity assignment examples into release/1.14.x
  website/content/docs/concepts/client-count/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24507 Backport of Update ACME entity assignment examples into release/1.15.x
  website/content/docs/concepts/client-count/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24508 Quote example domains within ACME entity docs
  website/content/docs/concepts/client-count/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24510 Backport of Quote example domains within ACME entity docs into release/1.15.x
  website/content/docs/concepts/client-count/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24509 Backport of Quote example domains within ACME entity docs into release/1.14.x
  website/content/docs/concepts/client-count/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24503 Refactor creating docker image to be more reusable
  vault/external_tests/seal_binary/seal_docker_util.go
  vault/external_tests/seal_binary/seal_sighup_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24505 Attempt to move control of registration for nodes and pipelines to the audit broker
  audit/types.go
  builtin/audit/file/backend.go
  builtin/audit/socket/backend.go
  builtin/audit/syslog/backend.go
  helper/testhelpers/corehelpers/corehelpers.go
  internal/observability/event/pipeliner.go
  vault/audit.go
  vault/audit_broker.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24435 docs: fix typo in api-docs/auth/aws.mdx
  website/content/api-docs/auth/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, backport/1.15.x

#24374 Update azurekv.mdx change line 37 stores to destinations
  website/content/docs/sync/azurekv.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24083 Added `vault operator raft snapshot inspect` usage
  website/content/docs/commands/operator/raft.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.15.x

#24101 Adding note about `node-id` being generated when unset
  website/content/docs/configuration/storage/raft.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.15.x

#23939 Document Vault Default Password Policy
  website/content/docs/concepts/password-policies.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, password policy

#23527 Update aws.mdx
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24513 UI: better calculation for advanced secret in KV v2
  changelog/24513.txt
  ui/lib/core/addon/utils/advanced-secret.js
  ui/lib/core/app/utils/advanced-secret.js
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/edit.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/unit/utils/advanced-secret-test.js
Labels: ui, bug, hashicorp-contributed-pr, backport/1.15.x

#24525 Backport of UI: better calculation for advanced secret in KV v2 into release/1.15.x
  changelog/24513.txt
  ui/lib/core/addon/utils/advanced-secret.js
  ui/lib/core/app/utils/advanced-secret.js
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/edit.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/unit/utils/advanced-secret-test.js
Labels: ui, backport, hashicorp-contributed-pr

#24095 Backport of Document secrets sync LIST request modifications into release/1.15.x
  website/content/api-docs/system/secrets-sync.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23985 Automated snapshots info and perf replication.mdx
  website/content/docs/enterprise/replication.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24524 Backport of Update aws.mdx into release/1.15.x
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24520 Backport of Document Vault Default Password Policy into release/1.14.x
  website/content/docs/concepts/password-policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24522 Backport of Update aws.mdx into release/1.13.x
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24521 Backport of Document Vault Default Password Policy into release/1.15.x
  website/content/docs/concepts/password-policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24527 Backport of Automated snapshots info and perf replication.mdx into release/1.15.x
  website/content/docs/enterprise/replication.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24518 Backport of Adding note about `node-id` being generated when unset into release/1.15.x
  website/content/docs/configuration/storage/raft.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24517 Backport of Added `vault operator raft snapshot inspect` usage into release/1.15.x
  website/content/docs/commands/operator/raft.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24516 Backport of Update azurekv.mdx change line 37 stores to destinations into release/1.15.x
  website/content/docs/sync/azurekv.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24338 Update ldap.mdx
  website/content/api-docs/auth/ldap.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24492 UI: Show correct nav items when in chroot namespace
  changelog/24492.txt
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/cluster.js
  ui/app/services/permissions.js
  ui/lib/core/addon/utils/sanitize-path.js
  ui/mirage/handlers/chroot-namespace.js
  ui/tests/acceptance/chroot-namespace-test.js
  ui/tests/unit/services/permissions-test.js
  ui/tests/unit/utils/sanitize-path-test.js
Labels: ui, hashicorp-contributed-pr, backport/1.15.x

#24536 Backport UI: show correct nav items when logged into chrooted namespace
  changelog/24492.txt
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/cluster.js
  ui/app/services/permissions.js
  ui/lib/core/addon/utils/sanitize-path.js
  ui/mirage/handlers/chroot-namespace.js
  ui/tests/acceptance/chroot-namespace-test.js
  ui/tests/pages/auth.js
  ui/tests/unit/services/permissions-test.js
  ui/tests/unit/utils/sanitize-path-test.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#23982 docs/vault-secrets-operator: aws vaultauth
  website/content/docs/platform/k8s/vso/sources/vault/auth/aws.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/gcp.mdx
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24546 Backport of docs/vault-secrets-operator: aws vaultauth into release/1.15.x
  website/content/docs/platform/k8s/vso/sources/vault/auth/aws.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/gcp.mdx
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#24542 UI: Update radio form field to have group styles and label/subtext
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/tests/integration/components/form-field-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24529 Consistently refer to Key Value secrets engine as KV
  changelog/24529.txt
  command/kv_patch.go
  command/kv_rollback.go
  command/server.go
  ui/app/models/auth-method.js
  ui/app/models/secret-engine.js
  ui/app/templates/components/wizard/kv-engine.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/kv/addon/components/kv-page-header.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/integration/components/kv/kv-page-header-test.js
  ui/tests/integration/components/secret-list-header-test.js
  website/content/api-docs/index.mdx
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/rate-limit-quotas.mdx
  website/content/docs/commands/kv/delete.mdx
  website/content/docs/commands/kv/destroy.mdx
  website/content/docs/commands/kv/enable-versioning.mdx
  website/content/docs/commands/kv/get.mdx
  website/content/docs/commands/kv/index.mdx
  website/content/docs/commands/kv/list.mdx
  website/content/docs/commands/kv/metadata.mdx
  website/content/docs/commands/kv/patch.mdx
  website/content/docs/commands/kv/put.mdx
  website/content/docs/commands/kv/rollback.mdx
  website/content/docs/commands/kv/undelete.mdx
  website/content/docs/commands/read.mdx
  website/content/docs/concepts/lease.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/internals/high-availability.mdx
  website/content/docs/interoperability-matrix.mdx
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/release-notes/1.11.0.mdx
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/secrets/kv/index.mdx
  website/content/docs/secrets/kv/kv-v1.mdx
  website/content/docs/secrets/kv/kv-v2.mdx
  website/content/docs/upgrading/upgrade-to-1.5.0.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: ui, docs, hashicorp-contributed-pr

#24530 UI: Obscure values for nested KV v2 secret
  changelog/24530.txt
  ui/lib/core/addon/components/json-editor.hbs
  ui/lib/core/addon/components/json-editor.js
  ui/lib/core/addon/utils/advanced-secret.js
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/integration/components/json-editor-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
  ui/tests/unit/utils/advanced-secret-test.js
Labels: ui, hashicorp-contributed-pr

#24407 UI: [VAULT-21532] Create message
  ui/app/adapters/config-ui/message.js
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/models/config-ui/message.js
  ui/app/serializers/config-ui/message.js
  ui/lib/config-ui/addon/components/messages/message-expiration-date-form.hbs
  ui/lib/config-ui/addon/components/messages/message-expiration-date-form.js
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.js
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/config-ui/addon/components/messages/page/list.js
  ui/lib/config-ui/addon/components/messages/tab-page-header.hbs
  ui/lib/config-ui/addon/controllers/messages/create.js
  ui/lib/config-ui/addon/routes/messages/create.js
  ui/lib/config-ui/addon/routes/messages/index.js
  ui/lib/config-ui/addon/templates/messages/create.hbs
  ui/lib/core/addon/utils/date-formatters.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-message-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24545 move/reimplement schedule code to shared location
  sdk/framework/schedule.go
Labels: hashicorp-contributed-pr

#24540 Remove old audit behavior from test code
  audit/entry_formatter.go
  audit/event.go
  audit/event_test.go
  audit/sink_wrapper.go
  audit/types.go
  helper/testhelpers/corehelpers/corehelpers.go
  http/logical_test.go
  http/sys_generate_root_test.go
  vault/audit_test.go
  vault/core_test.go
  vault/external_tests/identity/login_mfa_totp_test.go
Labels: core/audit, test, pr/no-changelog, hashicorp-contributed-pr

#24549 Don't touch ActiveTime in preSeal/postUnseal
  changelog/24549.txt
  vault/core.go
  vault/ha.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#24554 Add audit filtering feature
  audit/entry_filter.go
  audit/entry_formatter.go
  audit/nodes.go
  audit/nodes_test.go
  audit/sink_wrapper.go
  audit/types.go
  builtin/audit/file/backend.go
  builtin/audit/file/backend_test.go
  builtin/audit/socket/backend.go
  builtin/audit/socket/backend_test.go
  builtin/audit/syslog/backend.go
  builtin/audit/syslog/backend_test.go
  helper/testhelpers/corehelpers/corehelpers.go
  http/logical_test.go
  internal/observability/event/options.go
  internal/observability/event/options_test.go
  internal/observability/event/pipeline_reader.go
  internal/observability/event/sink_socket.go
  internal/observability/event/sink_socket_test.go
  internal/observability/event/sink_stdout.go
  internal/observability/event/sink_syslog.go
  internal/observability/event/sink_syslog_test.go
  vault/audit.go
  vault/audit_broker.go
  vault/audit_broker_test.go
  vault/external_tests/identity/login_mfa_totp_test.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
