Repository hashicorp/vault, pull requests merged in 2023-01, with the labels that each got.

#18519 secrets/gcp: add documentation for impersonated accounts feature
  website/content/api-docs/secret/gcp.mdx
  website/content/docs/secrets/gcp.mdx
Labels: pr/no-changelog

#18576 Remove unreachable code
  vault/policy_store.go
  vault/request_handling.go
Labels: pr/no-changelog

#18586 UI: fix ui date-related tests
  ui/tests/acceptance/client-history-test.js
  ui/tests/integration/components/date-dropdown-test.js
Labels: ui, pr/no-changelog

#18588 Kubernetes Environment Check
  ui/app/adapters/kubernetes/config.js
  ui/mirage/handlers/kubernetes.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
Labels: ui

#18558 Remove `generic_mount_paths` field
  vault/logical_system_paths.go
Labels: pr/no-changelog

#18496 UI/pki key workflow tests
  ui/app/models/pki/key.js
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/page/pki-key-details.ts
  ui/lib/pki/addon/components/pki-key-form.js
  ui/lib/pki/addon/components/pki-key-import.js
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/page/pki-key-list.js
  ui/tests/helpers/pki/page/pki-keys.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/helpers/policy-generator/pki.js
  ui/tests/integration/components/pki/page/pki-key-details-test.js
  ui/tests/integration/components/pki/page/pki-key-list-test.js
  ui/tests/integration/components/pki/pki-key-form-test.js
  ui/tests/integration/components/pki/pki-key-list-test.js
Labels: ui, pr/no-changelog

#18581 Update integrated-storage.mdx
  website/content/docs/internals/integrated-storage.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18504 UI: PKI config via import
  ui/app/adapters/pki/config/import.js
  ui/app/models/pki/config/import.js
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/pki-config/import.hbs
  ui/lib/pki/addon/components/pki-config/import.ts
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-role-generate.ts
  ui/lib/pki/addon/routes/overview.js
  ui/tests/integration/components/pki-config/import-test.js
  ui/tests/unit/adapters/pki/config/import-test.js
  ui/types/ember-data/types/registries/model.d.ts
  ui/types/vault/app-types.ts
  ui/types/vault/models/pki/certificate/generate.d.ts
  ui/types/vault/models/pki/config/import.d.ts
Labels: ui, pr/no-changelog

#18563 ui: add input as event for text form field
  ui/lib/core/addon/components/form-field.hbs
Labels: ui, pr/no-changelog

#18593 docs: clarify parameter constraints limitations when using globs
  website/content/docs/concepts/policies.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18561 Correct sample payload at Generate Secret
  website/content/api-docs/secret/gcp.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone

#18575 Fix typo in mount.go
  vault/mount.go
Labels: pr/no-changelog

#18553 Fix duplicate definition of path `sys/internal/specs/openapi`
  vault/logical_system_paths.go
Labels: pr/no-changelog

#18605 docs: db plugin add link to lease docs
  website/content/docs/secrets/databases/index.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18203 VAULT-11827: Add new Link node level fields
  vault/hcp_link/proto/node_status/status.pb.go
  vault/hcp_link/proto/node_status/status.proto
Labels: pr/no-changelog

#18592 Loading Substate Handling Issue
  ui/app/routes/vault/cluster.js
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
Labels: ui

#18597 docs: Update PKCS#11 provider docs for XKS and RNG
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18607 VAULT-12489 OSS Changes
  vault/core.go
  vault/logical_system.go
  vault/request_handling.go
Labels: pr/no-changelog

#18572 Fix error in changelog template
  CHANGELOG.md
  changelog/changelog.tmpl
Labels: pr/no-changelog, pr/no-milestone

#18619 change quorum warning to a singular string
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/meta/meta.proto
Labels: pr/no-changelog

#18623 UI: extend overview route from issuers index
  ui/lib/pki/addon/components/pki-key-import.js
  ui/lib/pki/addon/routes/issuers/import.js
  ui/lib/pki/addon/routes/issuers/index.js
Labels: ui, pr/no-changelog

#18616 VAULT-12491 Add docs for group policy config
  website/content/api-docs/system/config-group-policy-application.mdx
  website/content/docs/enterprise/namespaces.mdx
  website/data/api-docs-nav-data.json
Labels: pr/no-changelog

#18634 UI: pki import issuer
  ui/app/adapters/pki/issuer.js
  ui/app/helpers/parse-pki-cert.js
  ui/app/models/pki/certificate/base.js
  ui/lib/pki/addon/components/pki-ca-certificate-import.hbs
  ui/lib/pki/addon/components/pki-ca-certificate-import.ts
  ui/lib/pki/addon/routes/issuers/import.js
  ui/lib/pki/addon/templates/issuers/import.hbs
  ui/package.json
  ui/tests/integration/components/pki/pki-issuer-import-test.js
  ui/types/generate-declaration.md
  ui/types/vault/models/pki/certificate/base.d.ts
  ui/yarn.lock
Labels: ui, pr/no-changelog

#18642 Backport of Fix error in changelog template into release/1.11.x
  changelog/changelog.tmpl
Labels: pr/no-changelog, pr/no-milestone

#18643 Backport of Fix error in changelog template into release/1.10.x
  changelog/changelog.tmpl
Labels: pr/no-changelog, pr/no-milestone

#18644 Backport of Fix error in changelog template into release/1.12.x
  changelog/changelog.tmpl
Labels: pr/no-changelog, pr/no-milestone

#18514 Add vault pki command website documentation
  website/content/docs/commands/pki/index.mdx
  website/data/docs-nav-data.json
Labels: docs, secret/pki, pr/no-changelog

#18466 Correctly distinguish empty issuer names in PKI
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/util.go
  changelog/18466.txt
Labels: bug, secret/pki, backport/1.11.x, backport/1.12.x

#18617 Revert "Add mount path into the default generated openapi.json spec (#17926)"
  api/plugin_helpers.go
  sdk/framework/backend.go
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
  sdk/framework/path.go
  sdk/framework/testdata/legacy.json
  sdk/framework/testdata/operations.json
  sdk/framework/testdata/operations_list.json
  sdk/framework/testdata/responses.json
  ui/app/services/path-help.js
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
Labels: ui, pr/no-changelog

#18641 UI: Remove LearnLink, use DocLink!
  ui/app/styles/components/replication-doc-link.scss
  ui/app/styles/components/replication-summary.scss
  ui/app/styles/core.scss
  ui/app/templates/components/clients/usage-stats.hbs
  ui/app/templates/components/generate-credentials-database.hbs
  ui/app/templates/components/identity/item-metadata.hbs
  ui/app/templates/components/license-banners.hbs
  ui/app/templates/components/transform-advanced-templating.hbs
  ui/app/templates/components/wizard/replication-setup.hbs
  ui/app/templates/vault/cluster/access/identity/aliases/index.hbs
  ui/app/templates/vault/cluster/access/identity/index.hbs
  ui/app/templates/vault/cluster/access/mfa/index.hbs
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/app/templates/vault/cluster/access/oidc.hbs
  ui/app/templates/vault/cluster/policies/index.hbs
  ui/app/templates/vault/cluster/replication-dr-promote/details.hbs
  ui/app/templates/vault/cluster/replication-dr-promote/index.hbs
  ui/app/templates/vault/cluster/unseal.hbs
  ui/lib/core/addon/components/doc-link.js
  ui/lib/core/addon/components/external-link.js
  ui/lib/core/addon/components/learn-link.js
  ui/lib/core/addon/components/replication-doc-link.js
  ui/lib/core/addon/templates/components/replication-dashboard.hbs
  ui/lib/core/addon/templates/components/replication-doc-link.hbs
  ui/lib/core/addon/templates/components/replication-secondary-card.hbs
  ui/lib/core/app/components/learn-link.js
  ui/lib/core/app/components/replication-doc-link.js
  ui/tests/integration/components/clients/usage-stats-test.js
Labels: ui, pr/no-changelog

#18638 VAULT-9883: Agent Reloadable Config
  changelog/18638.txt
  command/agent.go
  command/agent/cache/listener.go
  command/agent/test-fixtures/reload/reload_bar.key
  command/agent/test-fixtures/reload/reload_bar.pem
  command/agent/test-fixtures/reload/reload_ca.pem
  command/agent/test-fixtures/reload/reload_foo.key
  command/agent/test-fixtures/reload/reload_foo.pem
  command/agent_test.go
  command/commands.go
  website/content/docs/agent/index.mdx
Labels: enhancement, core, agent, core/config, command

#18650 Backport of UI: fix ui date-related tests into release/1.12.x
  ui/tests/acceptance/client-history-test.js
  ui/tests/integration/components/date-dropdown-test.js
Labels: backport

#18652 docs: note that env vars must be set on the vault process and can be checked in 1.13
  website/content/docs/commands/index.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18639 UI: PKI config refactor
  ui/app/adapters/pki/config.js
  ui/app/adapters/pki/config/import.js
  ui/app/models/pki/config.js
  ui/app/models/pki/config/import.js
  ui/app/serializers/pki/config.js
  ui/lib/pki/addon/components/pki-ca-certificate-import.ts
  ui/lib/pki/addon/components/pki-config/import.hbs
  ui/lib/pki/addon/components/pki-config/import.ts
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-configure-form.ts
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/templates/configuration/create.hbs
  ui/lib/pki/addon/templates/issuers/import.hbs
  ui/tests/integration/components/pki-config/import-test.js
  ui/tests/integration/components/pki-configure-form-test.js
  ui/tests/integration/components/pki/pki-issuer-import-test.js
  ui/tests/unit/adapters/pki/config-test.js
  ui/tests/unit/adapters/pki/config/import-test.js
  ui/tests/unit/serializers/pki/config-test.js
  ui/types/vault/models/pki/config.d.ts
  ui/types/vault/models/pki/config/import.d.ts
Labels: ui, pr/no-changelog

#18613 Add documentation for KMIP features implemented in 1.13
  website/content/docs/secrets/kmip-profiles.mdx
  website/content/docs/secrets/kmip.mdx
Labels: pr/no-changelog

#18645 Allow tidy to backup legacy CA bundles
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/storage_migrations_test.go
  changelog/18645.txt
  website/content/api-docs/secret/pki.mdx
Labels: enhancement, secret/pki

#18637 Fix AppRole / path_role response schema
  builtin/credential/approle/path_role.go
Labels: pr/no-changelog

#18669 docs/plugin: adds note on leases and tokens during upgrades
  website/content/docs/upgrading/plugins.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18666 VAULT-12264: Fix log rotation params which require an integer
  command/agent.go
  command/agent_test.go
  command/base_flags.go
  command/log_flags.go
  command/log_flags_test.go
  command/server.go
  helper/logging/logger.go
  internalshared/configutil/config.go
  internalshared/configutil/merge.go
Labels: bug, core/log, pr/no-changelog

#18659 Add automated CI account cleanup & monitoring
  .github/workflows/test-ci-cleanup.yml
  enos/ci/aws-nuke.yml
  enos/ci/service-user-iam/main.tf
Labels: pr/no-changelog, pr/no-milestone

#18676 docs/oidc: change user type recommendation for Google workspace integration
  website/content/docs/auth/jwt/oidc-providers/google.mdx
Labels: docs, pr/no-changelog, backport/1.12.x

#18674 VAULT-12548: Fix data races in Link status reporting
  go.mod
  go.sum
  vault/hcp_link/link.go
Labels: pr/no-changelog

#18651 ui: unload auth method when navigating away from form
  changelog/18651.txt
  ui/app/components/mount-backend-form.js
Labels: ui, backport/1.12.x

#18671 ui: create object list input component
  ui/app/styles/core/forms.scss
  ui/lib/core/addon/components/object-list-input.hbs
  ui/lib/core/addon/components/object-list-input.js
  ui/lib/core/app/components/object-list-input.js
  ui/tests/integration/components/object-list-input-test.js
Labels: ui, pr/no-changelog

#18687 PKI Issuer Edit
  ui/app/adapters/pki/issuer.js
  ui/app/models/pki/issuer.js
  ui/app/serializers/pki/issuer.js
  ui/lib/pki/addon/components/page/pki-issuer-edit.hbs
  ui/lib/pki/addon/components/page/pki-issuer-edit.ts
  ui/lib/pki/addon/routes/index.js
  ui/lib/pki/addon/routes/issuers/issuer/edit.js
  ui/lib/pki/addon/templates/issuers/issuer/edit.hbs
  ui/package.json
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
  ui/types/vault/app-types.ts
  ui/types/vault/models/pki/issuer.d.ts
Labels: ui, pr/no-changelog

#18691 Backport: ui: unload auth method when navigating away from form #18651
  changelog/18651.txt
  ui/app/components/mount-backend-form.js
Labels: ui

#18685 Refactor the PKI revocation handler to prep for unified revocation
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/secret_certs.go
Labels: secret/pki, pr/no-changelog

#17748 [QT-19] Enable Enos replication scenario
  enos/README.md
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/generate_secondary_token/main.tf
  enos/modules/shutdown_node/main.tf
  enos/modules/vault-verify-write-data/main.tf
  enos/modules/vault-verify-write-data/variables.tf
  enos/modules/vault_get_cluster_ips/main.tf
  enos/modules/vault_get_cluster_ips/scripts/get-leader-private-ip.sh
  enos/modules/vault_setup_perf_primary/main.tf
  enos/modules/vault_setup_perf_primary/scripts/configure-vault-pr-primary.sh
  enos/modules/vault_setup_perf_secondary/main.tf
  enos/modules/vault_unseal_nodes/main.tf
  enos/modules/vault_unseal_nodes/scripts/unseal-node.sh
  enos/modules/vault_unseal_nodes/scripts/wait-until-sealed.sh
  enos/modules/vault_verify_performance_replication/main.tf
  enos/modules/vault_verify_performance_replication/scripts/verify-performance-replication.sh
  enos/modules/vault_verify_read_data/main.tf
  enos/modules/vault_verify_read_data/scripts/verify-data.sh
  enos/modules/vault_verify_replication/main.tf
  enos/modules/vault_verify_replication/templates/smoke-verify-replication.sh
  enos/modules/vault_verify_replication/variables.tf
  enos/modules/vault_verify_ui/main.tf
  enos/modules/vault_verify_ui/templates/smoke-verify-ui.sh
  enos/modules/vault_verify_ui/variables.tf
  enos/modules/vault_verify_undo_logs/main.tf
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
  enos/modules/vault_verify_unsealed/main.tf
  enos/modules/vault_verify_unsealed/templates/verify-vault-node-unsealed.sh
  enos/modules/vault_verify_write_data/main.tf
  enos/modules/vault_verify_write_data/scripts/smoke-enable-secrets-kv.sh
  enos/modules/vault_verify_write_data/scripts/smoke-write-test-data.sh
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18694 [Docs] Add VAULT_LOG_LEVEL to the environment var list
  website/content/docs/commands/index.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18715 Revert "auth/kubernetes: upgrade to v0.14.1"
  changelog/18711.txt
  go.mod
  go.sum
Labels: pr/no-changelog

#18726 Revert "Add new clients into the monthly breakdown"
  changelog/18629.txt
  vault/activity_log.go
Labels: pr/no-changelog

#18682 Add experiment system + events experiment
  changelog/18682.txt
  command/commands.go
  command/server.go
  command/server/config.go
  command/server/config_test.go
  command/server/config_test_helpers.go
  helper/experiments/experiments.go
  http/sys_config_state_test.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  website/content/api-docs/system/experiments.mdx
  website/content/docs/commands/server.mdx
  website/content/docs/configuration/index.mdx
  website/data/api-docs-nav-data.json
Labels: docs, core/cli, core/api, core/config, website

#18703 Added JWT Token Validation
  website/content/docs/auth/jwt/index.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18717 ui: small pki issuer details cleanup
  ui/app/models/pki/issuer.js
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
Labels: ui, pr/no-changelog

#18557 Fix a very old comment to include query-string parameters
  sdk/framework/path.go
Labels: docs, pr/no-changelog

#18713 docs: updates inline alert authoring info
  website/README.md
  website/package-lock.json
  website/package.json
Labels: docs, website, pr/no-changelog, pr/no-milestone

#18602 [QT-309] Ensure creds are available for OCI and S3
  physical/oci/oci_ha_test.go
  physical/oci/oci_test.go
  physical/s3/s3_test.go
Labels: pr/no-changelog

#18702 ui: VAULT-8673 Add empty states to certificates and roles
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/workflow.js
Labels: ui, pr/no-changelog

#18599 ui: VAULT-6511 PKI Overview Page
  ui/app/styles/components/selectable-card-container.scss
  ui/lib/core/addon/components/input-search.hbs
  ui/lib/core/addon/components/input-search.js
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/core/app/components/input-search.js
  ui/lib/core/app/components/overview-card.js
  ui/lib/pki/addon/components/page/pki-overview.hbs
  ui/lib/pki/addon/components/page/pki-overview.ts
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/templates/overview.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/helpers/pki/overview.js
  ui/tests/helpers/pki/pki-run-commands.js
  ui/tests/integration/components/overview-card-test.js
  ui/tests/integration/components/pki/page/pki-overview-test.js
Labels: ui, pr/no-changelog

#18640 Add basic event bus broker stub
  go.mod
  go.sum
  sdk/logical/events.go
  vault/core.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: pr/no-changelog

#18692 Enable undo logs by default
  go.mod
  go.sum
  physical/consul/consul.go
  physical/consul/consul_test.go
  physical/raft/chunking_test.go
  physical/raft/raft.go
  physical/raft/raft_test.go
  physical/raft/snapshot_test.go
  physical/raft/testing.go
  vault/raft.go
Labels: pr/no-changelog

#18741 Fix arch for backend storage in Enos replication scenario
  enos/enos-scenario-replication.hcl
Labels: pr/no-changelog

#18478 user-lockout documentation changes
  website/content/api-docs/system/auth.mdx
  website/content/api-docs/system/user-lockout.mdx
  website/content/docs/commands/auth/tune.mdx
  website/content/docs/concepts/user-lockout.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/user-lockout.mdx
  website/content/docs/internals/telemetry.mdx
  website/content/partials/user-lockout.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: pr/no-changelog

#18709 [docs] Fixing invalid link
  website/content/docs/agent/caching/index.mdx
Labels: docs, website, pr/no-changelog, backport/1.12.x, pr/no-milestone

#18743 API Explorer Query Params
  changelog/18743.txt
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
Labels: ui, bug, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18737 PKI Certificate Details
  ui/app/adapters/pki/certificate.js
  ui/app/adapters/pki/certificate/base.js
  ui/app/models/pki/certificate/base.js
  ui/app/serializers/pki/certificate/base.js
  ui/app/serializers/pki/certificate/generate.js
  ui/app/serializers/pki/certificate/sign.js
  ui/lib/pki/addon/components/page/pki-certificate-details.hbs
  ui/lib/pki/addon/components/page/pki-certificate-details.ts
  ui/lib/pki/addon/components/page/pki-overview.hbs
  ui/lib/pki/addon/components/pki-role-generate.hbs
  ui/lib/pki/addon/components/pki-role-generate.ts
  ui/lib/pki/addon/routes/certificates/certificate/details.js
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/templates/certificates/certificate/details.hbs
  ui/tests/integration/components/pki/page/pki-certificate-details-test.js
  ui/tests/integration/components/pki/page/pki-overview-test.js
  ui/tests/unit/adapters/pki/certificate/base-test.js
  ui/tests/unit/adapters/pki/certificate/generate-test.js
  ui/tests/unit/adapters/pki/certificate/sign-test.js
Labels: ui, pr/no-changelog

#18753 Backport of API Explorer Query Params into release/1.12.x
  changelog/18743.txt
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
Labels: ui

#18755 Backport of API Explorer Query Params into release/1.11.x
  changelog/18743.txt
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
Labels: ui

#18756 Backport of API Explorer Query Params into release/1.10.x
  changelog/18743.txt
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
Labels: ui

#18744 ui: VAULT-12670 Update pki list view labels for list items
  ui/lib/pki/addon/components/page/pki-key-list.hbs
  ui/tests/helpers/pki/page/pki-keys.js
  ui/tests/integration/components/pki/page/pki-key-list-test.js
Labels: ui, pr/no-changelog

#18758 Add enterprise resources to CI cleanup
  enos/ci/aws-nuke.yml
Labels: pr/no-changelog, pr/no-milestone

#18754 Refactor CRL Building for unified CRLs
  builtin/logical/pki/backend.go
  builtin/logical/pki/config_util.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/storage.go
Labels: secret/pki, pr/no-changelog

#18398 [QT-441] Switch over to using new vault_ci AWS account for enos CI workflows
  .github/workflows/build.yml
  .github/workflows/enos-run.yml
  .github/workflows/test-ci-bootstrap.yml
  enos/ci/service-user-iam/main.tf
Labels: pr/no-changelog, pr/no-milestone

#18757 Rename reusable enos-run workflow file
  .github/workflows/build.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/README.md
  enos/modules/vault_verify_write_data/scripts/smoke-enable-secrets-kv.sh
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18765 Update api & vault to use sdk v0.7.0
  api/go.mod
  go.mod
Labels: pr/no-changelog

#18771 enos: default undo-logs to cluster behavior
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-variables.hcl
  enos/modules/shutdown_multiple_nodes/main.tf
  enos/modules/vault_raft_remove_peer/main.tf
  enos/modules/vault_raft_remove_peer/templates/raft-remove-peer.sh
  enos/modules/vault_verify_undo_logs/main.tf
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
Labels: pr/no-changelog, backport/1.12.x

#18778 Add missing space in PKI error
  builtin/logical/pki/ca_util.go
Labels: bug, pr/no-changelog

#18773 Update vault and api/auth submodules to use api/v1.8.3
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  go.mod
Labels: pr/no-changelog

#18693 Use schema for events in event broker
  sdk/logical/event.pb.go
  sdk/logical/event.proto
  sdk/logical/events.go
  vault/core.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: pr/no-changelog

#18672 Add workflow for running Docker-only acc tests
  .github/workflows/test-acc-dockeronly-nightly.yml
  .github/workflows/test-run-go-tests-for-path.yml
Labels: pr/no-changelog

#18761 UI: VAULT-12357 VAULT-12356 Add PKI Beta tag and Modal
  ui/app/app.js
  ui/app/styles/core/tags.scss
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/core/addon/components/secret-list-header.js
  ui/lib/pki/addon/engine.js
  ui/tests/integration/components/secret-list-header-test.js
Labels: ui, pr/no-changelog

#18735 Add path based primary write forwarding (PBPWF) - OSS
  sdk/logical/logical.go
  sdk/logical/storage.go
  sdk/logical/system_view.go
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_system.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/backend_grpc.pb.go
  vault/core.go
  vault/dynamic_system_view.go
  vault/forwarded_writer_oss.go
  vault/mount.go
  vault/mount_util.go
  vault/mount_util_shared.go
Labels: core, secret/pki, core/storage, pr/no-changelog

#18782 UI: VAULT-12820 Fix styling for pki beta badge
  ui/app/styles/core/tags.scss
  ui/lib/core/addon/components/secret-list-header.hbs
Labels: ui, pr/no-changelog

#18784 Add cross-cluster revocation queues for PKI
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
  vault/testing.go
Labels: enhancement, secret/pki, pr/no-changelog

#18774 Fix link meta panics
  vault/core.go
  vault/hcp_link/capabilities/link_control/link_control.go
  vault/hcp_link/capabilities/meta/meta.go
  vault/hcp_link/capabilities/node_status/node_status.go
  vault/hcp_link/link.go
Labels: pr/no-changelog

#18786 Add support for revoke by serial number to update the unified CRL
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/secret_certs.go
  builtin/logical/pki/storage_unified.go
Labels: enhancement, secret/pki, pr/no-changelog

#18788 Add unified storage support to OCSP handler
  builtin/logical/pki/backend.go
  builtin/logical/pki/ocsp.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
Labels: enhancement, secret/pki, pr/no-changelog

#18789 More cross cluster queue tweaks
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_tidy.go
Labels: enhancement, bug, secret/pki, pr/no-changelog

#18785 Write delta WAL entries for unified CRLs
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_crl.go
Labels: secret/pki, pr/no-changelog

#18790 Replace the docs codeowner
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone

#18794 Update x/crypto + x/net
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: bug, pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#18792 Add unified crl building
  builtin/logical/pki/backend.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
Labels: enhancement, secret/pki, pr/no-changelog

#18795 Event system alpha experiment
  changelog/18682.txt
  helper/experiments/experiments.go
  vault/core.go
  vault/logical_system_test.go
  website/content/api-docs/system/experiments.mdx
Labels: pr/no-changelog

#18781 UI: PKI URLs section on generate-root form
  ui/app/adapters/pki/urls.js
  ui/app/models/pki/action.js
  ui/app/models/pki/urls.js
  ui/app/serializers/pki/action.js
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-generate-root.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/templates/configuration/create.hbs
  ui/lib/pki/addon/templates/issuers/generate-root.hbs
  ui/lib/pki/addon/utils/action-params.js
  ui/lib/pki/app/utils/action-params.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/secrets/backend/pki/cert-test.js
  ui/tests/helpers/pki/pki-configure-form.js
  ui/tests/helpers/pki/pki-generate-root.js
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/helpers/pki/values.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki-configure-form-test.js
  ui/tests/integration/components/pki-generate-root-test.js
  ui/tests/integration/components/pki/pki-issuer-import-test.js
  ui/tests/integration/components/text-file-test.js
  ui/tests/unit/adapters/pki/action-test.js
  ui/tests/unit/adapters/pki/certificate/sign-test.js
  ui/tests/unit/adapters/pki/urls-test.js
  ui/tests/unit/serializers/pki/action-test.js
Labels: ui, pr/no-changelog

#18799 secrets/mysql: Add `tls_server_name` and `tls_skip_verify` parameters
  changelog/18799.txt
  plugins/database/mysql/connection_producer.go
  website/content/api-docs/secret/databases/mysql-maria.mdx
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x

#18800 Add the description front matter
  website/content/docs/index.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18801 Deny setting cross-cluster revocation features on local mounts
  builtin/logical/pki/path_config_crl.go
Labels: secret/pki, pr/no-changelog

#18791 UI: VAULT-12355 return to old pki from configuration
  ui/app/app.js
  ui/lib/pki/addon/engine.js
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/workflow.js
Labels: ui, pr/no-changelog

#18760 ui: add params to pki parser
  ui/app/adapters/pki-ca-certificate.js
  ui/app/helpers/parse-pki-cert.js
  ui/app/models/pki/certificate.js
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/issuer.js
  ui/app/models/pki/role.js
  ui/app/serializers/pki/cert.js
  ui/app/serializers/pki/certificate/base.js
  ui/app/serializers/pki/issuer.js
  ui/app/styles/components/form-section.scss
  ui/app/utils/parse-pki-cert-oids.js
  ui/app/utils/parse-pki-cert.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/string-list.hbs
  ui/lib/core/addon/components/string-list.js
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/pki-key-usage.hbs
  ui/package.json
  ui/tests/helpers/pki/values.js
  ui/tests/integration/components/pki/page/pki-certificate-details-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/integration/utils/parse-pki-cert-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog

#18815 Parallel migration
  changelog/18815.txt
  command/operator_migrate.go
  command/operator_migrate_test.go
  website/content/docs/commands/operator/migrate.mdx
Labels: core, core/cli, core/migration

#18819 Ensure unified_crl requires auto_rebuild
  builtin/logical/pki/path_config_crl.go
Labels: secret/pki, pr/no-changelog

#18821 UI: Fix details view on role (old PKI)
  ui/app/templates/components/pki/role-pki-edit.hbs
Labels: ui, pr/no-changelog

#18689 Allow Token Create Requests To Be Replicated
  Makefile
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  http/handler.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/translation.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/request_handling.go
  vault/request_handling_util.go
  vault/token_store.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog

#18807 Pki Generate Intermediate CSR
  ui/app/models/pki/action.js
  ui/app/serializers/pki/action.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-configure-form.ts
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-generate-root.js
  ui/lib/pki/addon/components/pki-generate-toggle-groups.hbs
  ui/lib/pki/addon/components/pki-generate-toggle-groups.ts
  ui/lib/pki/addon/routes/issuers/generate-intermediate.js
  ui/lib/pki/addon/templates/issuers/generate-intermediate.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-generate-toggle-groups-test.js
  ui/tsconfig.json
  ui/types/vault/app-types.ts
  ui/types/vault/models/capabilities.d.ts
  ui/types/vault/models/pki/action.d.ts
  ui/types/vault/utils/field-to-attrs.d.ts
Labels: ui, pr/no-changelog

#18808 UI: Bugfix: VAULT-9343 fix key management key view bug
  changelog/18808.txt
  ui/app/helpers/secret-query-params.js
Labels: ui, bug, backport/1.11.x, backport/1.12.x

#18829 Backport of UI: fix ui date-related tests into release/1.11.x
  ui/tests/acceptance/client-history-test.js
  ui/tests/integration/components/date-dropdown-test.js
Labels: backport

#18831 backport: fix indentation of cas field in KV API docs
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog

#18811 Provide IP Address in Duo Request
  changelog/18811.txt
  vault/login_mfa.go
Labels: auth/mfa

#18830 backport: fix indentation of cas field in KV API docs
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog

#18835 UI: VAULT-12892 temporarily remove configuration toolbar
  ui/lib/pki/addon/templates/configuration/index.hbs
Labels: ui, pr/no-changelog

#18817 Parallel migration (#18815)
  changelog/18817.txt
  command/operator_migrate.go
  command/operator_migrate_test.go
  website/content/docs/commands/operator/migrate.mdx
Labels: docs, enhancement, core, core/cli, core/migration

#18783 VAULT-12564 Docs for token file auth method
  website/content/docs/agent/autoauth/methods/approle.mdx
  website/content/docs/agent/autoauth/methods/token_file.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#18839 Document setting manual_chain after cross-signing
  website/content/docs/secrets/pki/rotation-primitives.mdx
Labels: docs, secret/pki, pr/no-changelog

#18695 UI: pki cross-sign issuers
  ui/app/adapters/pki/action.js
  ui/app/adapters/pki/issuer.js
  ui/app/app.js
  ui/app/models/pki/action.js
  ui/app/models/pki/certificate/base.js
  ui/app/serializers/pki/action.js
  ui/app/serializers/pki/issuer.js
  ui/app/styles/core/helpers.scss
  ui/lib/core/addon/components/object-list-input.hbs
  ui/lib/core/addon/components/object-list-input.js
  ui/lib/core/addon/helpers/img-path.js
  ui/lib/core/addon/templates/components/info-tooltip.hbs
  ui/lib/core/app/helpers/img-path.js
  ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
  ui/lib/pki/addon/components/pki-issuer-cross-sign.js
  ui/lib/pki/addon/engine.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js
  ui/lib/pki/addon/templates/issuers/issuer/cross-sign.hbs
  ui/public/images/pki-cross-sign.png
  ui/tests/integration/components/object-list-input-test.js
  ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
Labels: ui, pr/no-changelog

#18841 Don't execute the seal recovery tests on ENT.
  vault/external_tests/sealmigration/seal_migration_oss_test.go
  vault/external_tests/sealmigration/seal_migration_test.go
Labels: pr/no-changelog

#18845 UI: VAULT-12949 use overview card component for kubernetes overview
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/pki/addon/components/page/pki-overview.hbs
  ui/lib/pki/addon/components/page/pki-overview.ts
  ui/tests/acceptance/secrets/backend/kubernetes/overview-test.js
  ui/tests/helpers/kubernetes/overview.js
  ui/tests/integration/components/kubernetes/page/overview-test.js
Labels: ui, pr/no-changelog

#18847 UI: pki cross-sign component tests
  ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
  ui/lib/pki/addon/components/pki-issuer-cross-sign.js
  ui/tests/helpers/pki/values.js
  ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
Labels: ui, pr/no-changelog

#18848 Store the unified crl in a path that is not cluster local
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/storage.go
Labels: secret/pki, pr/no-changelog

#18855 Add note about mixed FIPS cluster deployments
  website/content/docs/enterprise/fips/fips1402.mdx
Labels: docs, pr/no-changelog

#18854 Clarify key bits for ssh
  builtin/logical/ssh/path_config_ca.go
  website/content/api-docs/secret/ssh.mdx
Labels: docs, bug, pr/no-changelog

#18856 Shadow globally defined var to avoid race
  command/format_test.go
  command/login_test.go
Labels: bug, pr/no-changelog

#18860 Add tidy of cross-cluster revoked storage
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_tidy.go
Labels: enhancement, secret/pki, pr/no-changelog

#18861 UI: VAULT-12950 Add breadcrumbs to create + edit roles and configure for Kubernetes
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
  ui/lib/kubernetes/addon/routes/configure.js
  ui/lib/kubernetes/addon/routes/roles/create.js
  ui/lib/kubernetes/addon/routes/roles/role/edit.js
  ui/lib/kubernetes/addon/templates/configure.hbs
  ui/lib/kubernetes/addon/templates/roles/create.hbs
  ui/lib/kubernetes/addon/templates/roles/role/edit.hbs
  ui/tests/integration/components/kubernetes/page/configure-test.js
  ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
Labels: ui, pr/no-changelog

#18862 Return a detailed list response for unified-revoked API endpoint
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/storage_unified.go
Labels: secret/pki, pr/no-changelog

#18867 UI: VAULT-12985 Update pki modal copy
  ui/lib/core/addon/components/secret-list-header.hbs
Labels: ui, pr/no-changelog

#18463 Vault 11796 vault cli list intermediates
  changelog/18463.txt
  command/commands.go
  command/pki_list_children_command.go
  command/pki_list_children_test.go
  command/pki_verify_sign_command.go
  command/pki_verify_sign_test.go
Labels: enhancement, secret/pki

#18866 Unified revocation migration code
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/periodic.go
  builtin/logical/pki/storage.go
  builtin/logical/pki/util.go
Labels: secret/pki, pr/no-changelog

#18873 Allow unification of revocations on other clusters
  builtin/logical/pki/backend.go
  builtin/logical/pki/crl_util.go
Labels: enhancement, secret/pki, pr/no-changelog

#18877 Small cleanup on pki commands for consistency
  command/commands.go
  command/healthcheck/pki_crl_validity_period.go
  command/pki_list_intermediate_command.go
  command/pki_list_intermediate_test.go
  command/pki_verify_sign_command.go
Labels: core/cli, secret/pki, pr/no-changelog

#18876 Add timeout functionality to inmem
  vault/cluster/inmem_layer.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18881 Add t.Helper() to various PKI test helper methods
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/chain_test.go
  builtin/logical/pki/ocsp_test.go
  builtin/logical/pki/path_resign_crls_test.go
  builtin/logical/pki/storage_migrations_test.go
  builtin/logical/pki/test_helpers.go
Labels: secret/pki, pr/no-changelog

#18885 Move cert auth backend setup into initialize
  builtin/credential/cert/backend.go
  builtin/credential/cert/backend_test.go
  changelog/18885.txt
Labels: enhancement, auth/cert

#18842 UI: PKI Sign Intermediate
  changelog/18842.txt
  ui/app/adapters/pki/action.js
  ui/app/adapters/pki/sign-intermediate.js
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/issuer.js
  ui/app/models/pki/sign-intermediate.js
  ui/app/serializers/pki/role.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/pki-generate-toggle-groups.ts
  ui/lib/pki/addon/components/pki-sign-intermediate-form.hbs
  ui/lib/pki/addon/components/pki-sign-intermediate-form.ts
  ui/lib/pki/addon/routes/issuers/issuer/details.js
  ui/lib/pki/addon/routes/issuers/issuer/sign.js
  ui/lib/pki/addon/templates/issuers/issuer/details.hbs
  ui/lib/pki/addon/templates/issuers/issuer/sign.hbs
  ui/tests/integration/components/pki-sign-intermediate-form-test.js
  ui/tests/integration/components/pki/pki-generate-toggle-groups-test.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/unit/adapters/pki/sign-intermediate-test.js
  ui/types/vault/models/pki/issuer.d.ts
Labels: ui

#18886 ui: add empty state for certificate index view
  ui/lib/pki/addon/templates/certificates/index.hbs
Labels: ui, pr/no-changelog

#18467 Vault 11798 vault cli issue intermediate
  changelog/18467.txt
  command/commands.go
  command/pki_issue_intermediate.go
  command/pki_issue_intermediate_test.go
  command/pki_list_intermediate_test.go
  command/pki_verify_sign_test.go
  vault/cluster/inmem_layer.go
Labels: core/cli, cryptosec

#18888 ui: mount pki engine in router
  ui/app/router.js
Labels: ui, pr/no-changelog

#18889 Switch ed25519 keytype to ec keytype to make the fips build happy.
  command/pki_issue_intermediate_test.go
  command/pki_verify_sign_test.go
Labels: core/cli, pr/no-changelog

#18894 core: make fmt on inmem_layer
  vault/cluster/inmem_layer.go
Labels: pr/no-changelog, pr/no-milestone

#18897 Replace the Plugin Portal link to point Vault Integrations
  website/content/docs/partnerships.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/docs/plugins/plugin-development.mdx
Labels: pr/no-changelog, pr/no-milestone

#18902 Add some managed key build tags to support incoming enterprise feature work.
  builtin/logical/transit/managed_key_util.go
  sdk/helper/keysutil/managed_key_util.go
Labels: pr/no-changelog

#16537 Update docs for Azure Secrets Engine new feature
  website/content/api-docs/secret/azure.mdx
Labels: docs, ecosystem, secret/azure, pr/no-changelog

#18903 Address pki::TestAutoRebuild flakiness
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/test_helpers.go
  sdk/helper/certutil/helpers.go
Labels: pr/no-changelog

#18905 UI: Fix date-dropdown test
  ui/tests/integration/components/date-dropdown-test.js
Labels: ui, bug, pr/no-changelog

#18900 [QT-470] Normalize and simplify container build workflows
  .github/workflows/build.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18904 Fix command.RunCustom(...) correctly
  command/commands.go
  command/main.go
  command/pki_health_check_test.go
Labels: bug, core/cli, pr/no-changelog

#18914 TestClusterCore's TLSConfig becomes a method and does a Clone
  builtin/credential/cert/backend_test.go
  helper/testhelpers/testhelpers.go
  http/forwarding_bench_test.go
  http/forwarding_test.go
  vault/external_tests/api/feature_flag_ext_test.go
  vault/external_tests/pprof/pprof_test.go
  vault/external_tests/raft/raft_autopilot_test.go
  vault/external_tests/raft/raft_test.go
  vault/external_tests/sealmigration/testshared.go
  vault/testing.go
Labels: pr/no-changelog

#18898 Updates for Plugin Portal deprecation in favor of new Integrations section
  website/content/docs/partnerships.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/docs/plugins/plugin-development.mdx
  website/content/docs/plugins/plugin-portal.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18893 Update integrated-storage.mdx
  website/content/docs/internals/integrated-storage.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18874 Remove dynamic keys from SSH Secrets Engine
  builtin/logical/ssh/backend.go
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/communicator.go
  builtin/logical/ssh/linux_install_script.go
  builtin/logical/ssh/path_creds_create.go
  builtin/logical/ssh/path_fetch.go
  builtin/logical/ssh/path_keys.go
  builtin/logical/ssh/path_roles.go
  builtin/logical/ssh/secret_dynamic_key.go
  builtin/logical/ssh/util.go
  changelog/18874.txt
  website/content/api-docs/secret/ssh.mdx
  website/content/docs/secrets/ssh/dynamic-ssh-keys.mdx
  website/content/docs/secrets/ssh/index.mdx
  website/data/docs-nav-data.json
Labels: enhancement, secret/ssh

#18923 prevent panic on mfa enforcement delete after a namespace is deleted
  changelog/18923.txt
  vault/login_mfa.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x
