Repository hashicorp/vault, pull requests merged in 2023-08, with the labels that each got.

#22142 LDAP Role Credentials
  ui/app/adapters/ldap/role.js
  ui/app/models/ldap/role.js
  ui/lib/ldap/addon/components/page/role/credentials.hbs
  ui/lib/ldap/addon/components/page/role/credentials.ts
  ui/lib/ldap/addon/components/page/role/details.hbs
  ui/lib/ldap/addon/components/page/role/details.ts
  ui/lib/ldap/addon/components/page/roles.hbs
  ui/lib/ldap/addon/components/page/roles.ts
  ui/lib/ldap/addon/routes/roles/role/credentials.ts
  ui/lib/ldap/addon/templates/roles/role/credentials.hbs
  ui/mirage/factories/ldap-credential.js
  ui/tests/integration/components/ldap/page/role/credentials-test.js
  ui/tests/integration/components/ldap/page/roles-test.js
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/adapters/ldap/role.d.ts
  ui/types/vault/models/ldap/role.d.ts
Labels: ui, pr/no-changelog

#22154 Backport of Docs/add imagepullsecrets example vso into release/1.13.x
  website/content/docs/platform/k8s/vso/examples.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22159 Add protobuf linter config necessary for vault-enterprise.
  buf.yaml
Labels: pr/no-changelog, hashicorp-contributed-pr

#22127 Add version specific redirects for agent/proxy pages
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22166 Backport of CI: fix conditional statements for notification and test report collection jobs into release/1.13.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22167 Backport of CI: fix conditional statements for notification and test report collection jobs into release/1.12.x
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22141 Split Changelog into Smaller Files
  CHANGELOG-pre-v1.10.md
  CHANGELOG-v0.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22126 bug(20562): allowed_domains are compared case-sensitive if they use g…
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/cert_util_test.go
  changelog/22126.txt
Labels: bug, secret/pki

#22176 Bump google.golang.go/protobuf dependency to v1.31.0
  go.mod
  go.sum
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/activity/generation/generate_data.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22170 Bump go mod versions to match those in ent
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22169 Bump go mod versions to match those in ent
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22168 Bump go mod versions to match those in ent
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22172 Bump go mod versions to match those in ent
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22109 Docs: Fix typo in list-intermediates nav entry
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x

#22180 Backport of Docs: Fix typo in list-intermediates nav entry into release/1.14.x
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22178 Fix incorrect kv delete page description
  website/content/docs/commands/kv/delete.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22179 Backport of Docs: Fix typo in list-intermediates nav entry into release/1.13.x
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22181 Backport of Fix incorrect kv delete page description into release/1.14.x
  website/content/docs/commands/kv/delete.mdx
Labels: hashicorp-contributed-pr

#22182 Fix some duplication of partials, and add fix versions for update-primary data loss issue
  website/content/docs/release-notes/1.13.0.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/partials/known-issues/update-primary-data-loss.mdx
  website/content/partials/update-primary-addrs-panic.mdx
  website/content/partials/update-primary-known-issue.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22192 Remove stray slash on redirect path
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22194 Backport of Remove stray slash on redirect path into release/1.14.x
  website/redirects.js
Labels: hashicorp-contributed-pr

#22195 Use Hashicorp docker proxy for CI docker images
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  helper/testhelpers/consul/consulhelper.go
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22198 Backport of Use Hashicorp docker proxy for CI docker images into release/1.14.x
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  helper/testhelpers/consul/consulhelper.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22197 Backport of Use Hashicorp docker proxy for CI docker images into release/1.13.x
  helper/testhelpers/consul/consulhelper.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22199 fixes
  ui/lib/kv/addon/components/kv-list-filter.hbs
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22200 LDAP Library Details
  ui/lib/ldap/addon/components/page/library/details.hbs
  ui/lib/ldap/addon/components/page/library/details.ts
  ui/lib/ldap/addon/routes/libraries/library/details.ts
  ui/lib/ldap/addon/routes/libraries/library/details/index.ts
  ui/lib/ldap/addon/templates/libraries/library/details.hbs
  ui/tests/integration/components/ldap/page/library/details-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22201 LDAP Library Details Configuration
  ui/app/models/ldap/library.js
  ui/app/serializers/ldap/library.js
  ui/lib/core/addon/modifiers/code-mirror.js
  ui/lib/ldap/addon/components/page/library/details/configuration.hbs
  ui/lib/ldap/addon/templates/libraries/library/details/configuration.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
  ui/tests/integration/components/ldap/page/library/details/configuration-test.js
  ui/tests/unit/serializers/ldap/library-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22163 ui: create new version of kv secret
  ui/app/adapters/kv/data.js
  ui/app/models/kv/data.js
  ui/app/serializers/kv/data.js
  ui/lib/kv/addon/components/kv-secret-form.hbs
  ui/lib/kv/addon/components/kv-secret-form.js
  ui/lib/kv/addon/components/page/list.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/routes.js
  ui/lib/kv/addon/routes/secret/details.js
  ui/lib/kv/addon/routes/secret/details/edit.js
  ui/lib/kv/addon/routes/secret/details/index.js
  ui/lib/kv/addon/templates/secret/details/edit.hbs
  ui/lib/kv/addon/templates/secret/details/index.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-create-new-version-test.js
  ui/tests/helpers/kv/kv-general-selectors.js
  ui/tests/helpers/kv/kv-page-selectors.js
  ui/tests/integration/components/kv/kv-secret-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22196 Backport of Use Hashicorp docker proxy for CI docker images into release/1.12.x
  helper/testhelpers/consul/consulhelper.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22207 Backport of Add timeouts to ACME test contexts into release/1.14.x
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_config_acme_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22209 Moving metadata component to a secret/metadata directory to match routing.
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.js
  ui/lib/kv/addon/templates/secret/metadata/edit.hbs
  ui/lib/kv/addon/templates/secret/metadata/index.hbs
  ui/tests/integration/components/kv/page/kv-page-metadata-details-test.js
  ui/tests/integration/components/kv/page/kv-page-metadata-edit-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22208 UI: KV-V2 setup workflow acceptance tests
  ui/lib/kv/addon/components/kv-secret-form.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/kv/breadcrumbs-test.js
  ui/tests/acceptance/secrets/backend/kv/diff-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-create-new-version-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-engine-permissions-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-version-history-diff-test.js
  ui/tests/helpers/commands.js
  ui/tests/helpers/kv/kv-general-selectors.js
  ui/tests/helpers/kv/kv-page-selectors.js
  ui/tests/helpers/kv/kv-run-commands.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/policy-generator/kv.js
  ui/tests/integration/components/kv/kv-secret-form-test.js
  ui/tests/integration/components/kv/page/kv-page-metadata-details-test.js
  ui/tests/integration/components/kv/page/kv-page-metadata-edit-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22175 KV Version History tab
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/styles/helper-classes/layout.scss
  ui/lib/kv/addon/components/page/secret/metadata/version-diff.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/lib/kv/addon/components/page/secret/version-history.hbs
  ui/lib/kv/addon/routes/secret/metadata/versions.js
  ui/lib/kv/addon/templates/secret/metadata/diff.hbs
  ui/lib/kv/addon/templates/secret/metadata/versions.hbs
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/package.json
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/integration/components/kv/page/kv-page-metadata-edit-test.js
  ui/tests/integration/components/kv/page/kv-page-version-history-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22215 Bump go-eventlogger to v0.2.2
  go.mod
  go.sum
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#22213 UI/rename kv form component
  ui/app/models/kv/data.js
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/lib/kv/addon/components/kv-secret-form.hbs
  ui/lib/kv/addon/components/kv-secret-form.js
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/components/page/secret/edit.js
  ui/lib/kv/addon/components/page/secrets/create.hbs
  ui/lib/kv/addon/components/page/secrets/create.js
  ui/lib/kv/addon/routes/create.js
  ui/lib/kv/addon/routes/secret/details/edit.js
  ui/lib/kv/addon/routes/secret/edit.js
  ui/lib/kv/addon/templates/secret/details/edit.hbs
  ui/lib/kv/addon/templates/secret/edit.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
  ui/tests/integration/components/kv/kv-data-fields-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-edit-test.js
  ui/tests/integration/components/kv/page/kv-page-secrets-create-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22177 Pass consul license in Enos scenarios that have `backend` in the matrix
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/backend_raft/main.tf
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22218 ui: add validator to check if string ends in slash
  ui/app/utils/validators.js
  ui/tests/unit/utils/validators-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22217 Disaster Recovery Secondary nodes cannot handle API requests
  sdk/helper/certutil/cieps.go
Labels: secret/pki, pr/no-changelog, hashicorp-contributed-pr

#22210 clarify docs in ldap/auth for userfilter
  website/content/api-docs/auth/ldap.mdx
  website/content/docs/auth/ldap.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#22223 Send leaf_not_after_behavior as string not an integer - OSS
  sdk/helper/certutil/cieps.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#21453 Docs for Application Default Credentials, links to non-dwdoa setup
  website/content/docs/auth/jwt/oidc-providers/google.mdx
Labels: docs, auth/jwt-oidc

#22225 Add an anchor link to policy override section
  website/content/docs/enterprise/sentinel/index.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22226 Backport of Add an anchor link to policy override section into release/1.14.x
  website/content/docs/enterprise/sentinel/index.mdx
Labels: hashicorp-contributed-pr

#22230 Refactor logic on applying leaf_not_after_behavior
  builtin/logical/pki/cert_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22232 Audit: small tidy up
  audit/options_test.go
  internal/observability/event/event_type.go
  internal/observability/event/options_test.go
  internal/observability/event/sink_file.go
  internal/observability/event/sink_noop.go
  internal/observability/event/sink_socket.go
  internal/observability/event/sink_stdout.go
  internal/observability/event/sink_syslog.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#22219 Backport of Pass consul license in Enos scenarios that have `backend` in the matrix into release/1.12.x
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/backend_raft/main.tf
  enos/modules/vault_cluster/main.tf
Labels: hashicorp-contributed-pr

#22221 Backport of Pass consul license in Enos scenarios that have `backend` in the matrix into release/1.14.x
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/backend_raft/main.tf
  enos/modules/vault_cluster/main.tf
Labels: hashicorp-contributed-pr

#22235 Ignore errors from rollback manager invocations
  changelog/22235.txt
  vault/external_tests/router/router_ext_test.go
  vault/mount.go
  vault/router_testing.go
Labels: core, backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22239 docs/db: fix outdated static role information
  website/content/api-docs/secret/databases/index.mdx
Labels: docs, pr/no-changelog, backport/1.14.x, hashicorp-contributed-pr

#21929 UI: [VAULT-17035 VAULT-17038 VAULT-17039] Dashboard Quick Actions card
  ui/app/components/dashboard/quick-actions-card.js
  ui/app/templates/components/dashboard/quick-actions-card.hbs
  ui/app/templates/vault/cluster/dashboard.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/integration/components/dashboard/quick-actions-card-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22240 Backport of docs/db: fix outdated static role information into release/1.14.x
  website/content/api-docs/secret/databases/index.mdx
Labels: hashicorp-contributed-pr

#22191 UI: Add missing allowed_user_ids to role form in PKI
  changelog/22191.txt
  ui/app/models/pki/certificate/generate.js
  ui/app/models/pki/role.js
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22038 Automatically track subloggers in allLoggers
  changelog/22038.txt
  command/server.go
  helper/logging/logger.go
  helper/testhelpers/corehelpers/corehelpers.go
  vault/activity_log.go
  vault/audit.go
  vault/auth.go
  vault/cluster.go
  vault/core.go
  vault/core_util.go
  vault/expiration.go
  vault/identity_store.go
  vault/logical_system_test.go
  vault/mount.go
  vault/policy_store.go
  vault/raft.go
  vault/rollback.go
  vault/seal_autoseal.go
  vault/testing.go
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22243 ui: remove `on input` event from `<input>` in `<FormField>` component
  ui/lib/core/addon/components/form-field.hbs
Labels: ui, hashicorp-contributed-pr

#22234 Audit Logging Using go-eventlogger Under Experiment Flag
  audit/entry_formatter.go
  audit/entry_formatter_test.go
  audit/event.go
  audit/event_test.go
  audit/types.go
  internal/observability/event/event_type.go
  vault/audit_broker.go
  vault/core.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22242 Backport of UI: Add missing allowed_user_ids to role form in PKI into release/1.14.x
  changelog/22191.txt
  ui/app/models/pki/certificate/generate.js
  ui/app/models/pki/role.js
Labels: ui, hashicorp-contributed-pr

#22249 Address LDAP issues
  changelog/22249.txt
  sdk/helper/ldaputil/client.go
  sdk/helper/ldaputil/client_test.go
Labels: hashicorp-contributed-pr

#22251 Backport of Address LDAP issues into release/1.14.x
  changelog/22249.txt
  sdk/helper/ldaputil/client.go
  sdk/helper/ldaputil/client_test.go
Labels: hashicorp-contributed-pr

#22252 Backport of Address LDAP issues into release/1.13.x
  changelog/22249.txt
  sdk/helper/ldaputil/client.go
  sdk/helper/ldaputil/client_test.go
Labels: hashicorp-contributed-pr

#22253 secrets/db: improves error logs for static role rotation
  builtin/logical/database/rotation.go
  changelog/22253.txt
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22255 Backport of secrets/db: improves error logs for static role rotation into release/1.13.x
  builtin/logical/database/rotation.go
  changelog/22253.txt
Labels: hashicorp-contributed-pr

#22256 Backport of secrets/db: improves error logs for static role rotation into release/1.14.x
  builtin/logical/database/rotation.go
  changelog/22253.txt
Labels: hashicorp-contributed-pr

#22098 Add API docs on CIEPS issuance
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, hashicorp-contributed-pr

#22259 Docs CIEPS Configuration
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog, hashicorp-contributed-pr

#22261 Backport of Address LDAP issues into release/1.12.x
  changelog/22249.txt
  sdk/helper/ldaputil/client.go
  sdk/helper/ldaputil/client_test.go
Labels: hashicorp-contributed-pr

#16623 chore(api-docs): remove vc since it's unmaintained
  website/content/api-docs/libraries.mdx
Labels: docs, pr/no-changelog

#22245 UI: KV engine - workflow nav test
  ui/app/templates/components/secret-create-or-update.hbs
  ui/lib/core/addon/components/page/breadcrumbs.hbs
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/routes/secret/metadata/edit.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/helpers/kv/kv-run-commands.js
  ui/tests/helpers/kv/kv-selectors.js
Labels: hashicorp-contributed-pr

#22263 VAULT-18157: Audit events: Log Test Message
  audit/nodes.go
  audit/nodes_test.go
  builtin/audit/file/backend.go
  builtin/audit/socket/backend.go
  builtin/audit/syslog/backend.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#22254 UI: create kv secret metadata
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/kv/metadata.js
  ui/lib/kv/addon/components/kv-metadata-fields.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.hbs
  ui/lib/kv/addon/components/page/secrets/create.hbs
  ui/lib/kv/addon/components/page/secrets/create.js
  ui/lib/kv/addon/routes/create.js
  ui/lib/kv/addon/templates/create.hbs
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/integration/components/kv/page/kv-page-metadata-edit-test.js
  ui/tests/integration/components/kv/page/kv-page-secrets-create-test.js
  ui/tests/unit/adapters/kv/metadata-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22266 VAULT-18934: Record individual metrics for each Auditing Event Pipeline
  audit/event.go
  audit/sink_wrapper.go
  audit/types.go
  builtin/audit/file/backend.go
  builtin/audit/socket/backend.go
  builtin/audit/syslog/backend.go
  vault/audit.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#22269 Refactor sign-intermediate API response
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_sign_issuers.go
  sdk/helper/certutil/cieps.go
Labels: secret/pki, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22264 VAULT-14644 Add support for Azure WIF auth to auto-auth (for Agent and Proxy)
  changelog/22264.txt
  command/agentproxyshared/auth/azure/azure.go
  go.mod
  go.sum
  website/content/docs/agent-and-proxy/autoauth/methods/azure.mdx
Labels: hashicorp-contributed-pr

#22274 Backport of VAULT-14644 Add support for Azure WIF auth to auto-auth (for Agent and Proxy) into release/1.14.x
  changelog/22264.txt
  command/agentproxyshared/auth/azure/azure.go
  go.mod
  go.sum
  website/content/docs/agent-and-proxy/autoauth/methods/azure.mdx
Labels: hashicorp-contributed-pr

#22270 UI: disable create popup menu link from deleted version
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22277 Update hashicorp/vault-plugin-auth-azure to v0.16.0
  changelog/22277.txt
  go.mod
  go.sum
Labels: dependencies, backport/1.14.x, hashicorp-contributed-pr

#17815 Docs: Add ADP requirement callout to PKCS#11 doc
  website/content/docs/enterprise/pkcs11-provider/index.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, backport/1.13.x, backport/1.14.x

#22278 Backport of Update hashicorp/vault-plugin-auth-azure to v0.16.0 into release/1.14.x
  changelog/22277.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22283 Backport of Docs: Add ADP requirement callout to PKCS#11 doc into release/1.14.x
  website/content/docs/enterprise/pkcs11-provider/index.mdx
Labels: hashicorp-contributed-pr

#22272 Docs: Changelog for MSSQL EKM Provider v0.2.2
  website/content/docs/platform/mssql/changelog.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22285 Backport of Docs: Changelog for MSSQL EKM Provider v0.2.2 into release/1.14.x
  website/content/docs/platform/mssql/changelog.mdx
Labels: hashicorp-contributed-pr

#18520 Major overhaul of `vault operator generate-root` CLI help
  command/operator_generate_root.go
  command/server.go
  vault/generate_root.go
  vault/generate_root_recovery.go
  website/content/docs/commands/operator/generate-root.mdx
Labels: core, core/cli, pr/no-changelog

#22287 LDAP Library Account Details
  ui/app/adapters/ldap/library.js
  ui/app/app.js
  ui/app/models/ldap/library.js
  ui/app/styles/helper-classes/colors.scss
  ui/app/styles/helper-classes/general.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/lib/ldap/addon/components/accounts-checked-out.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.ts
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.ts
  ui/lib/ldap/addon/engine.js
  ui/lib/ldap/addon/routes/libraries/library/details/accounts.ts
  ui/lib/ldap/addon/templates/libraries/library/details/accounts.hbs
  ui/tests/integration/components/ldap/accounts-checked-out-test.js
  ui/tests/integration/components/ldap/page/library/details/accounts-test.js
  ui/tests/unit/adapters/ldap/library-test.js
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/adapters/ldap/library.d.ts
  ui/types/vault/models/ldap/library.d.ts
  ui/types/vault/services/auth.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22160 Display CertificateCard instead of MaskedInput for certificates in PKI
  changelog/22160.txt
  ui/app/models/pki/action.js
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/issuer.js
  ui/lib/core/addon/components/certificate-card.hbs
  ui/lib/core/addon/components/certificate-card.js
  ui/lib/kubernetes/addon/components/page/configuration.hbs
  ui/lib/pki/addon/components/page/pki-certificate-details.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-info-table-rows.hbs
  ui/lib/pki/addon/components/pki-sign-intermediate-form.hbs
  ui/tests/acceptance/pki/pki-action-forms-test.js
  ui/tests/helpers/pki.js
  ui/tests/helpers/pki/pki-generate-root.js
  ui/tests/helpers/pki/pki-issuer-details.js
  ui/tests/helpers/pki/values.js
  ui/tests/integration/components/certificate-card-test.js
  ui/tests/integration/components/kubernetes/page/configuration-test.js
  ui/tests/integration/components/pki/page/pki-certificate-details-test.js
  ui/tests/integration/components/pki/page/pki-issuer-rotate-root-test.js
  ui/tests/integration/components/pki/page/pki-key-details-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
  ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
Labels: ui, hashicorp-contributed-pr

#20774 VAULT-15396: Client count testing library
  buf.yaml
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/clientcountutil/generation/generate_data.proto
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#21132 VAULT-17145, VAULT-17146: Write intent logs and event type in testing
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/clientcountutil/generation/generate_data.proto
  vault/activity_log.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22293 Share the same mssql container across all four subtests.
  plugins/database/mssql/mssql_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#11901 Add IBM 3rd Party Tools and Fix PR link
  website/content/api-docs/relatedtools.mdx
Labels: docs, website, pr/no-changelog

#22296 documenting missing option
  website/content/docs/audit/socket.mdx
Labels: docs, core/audit, pr/no-changelog, backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22299 Backport of documenting missing option into release/1.13.x
  website/content/docs/audit/socket.mdx
Labels: hashicorp-contributed-pr

#22300 Backport of documenting missing option into release/1.14.x
  website/content/docs/audit/socket.mdx
Labels: hashicorp-contributed-pr

#22301 Fix activity log generator license
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/clientcountutil/generation/generate_data.proto
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22289 LDAP Library Check-out
  ui/app/models/ldap/library.js
  ui/app/styles/core/buttons.scss
  ui/app/styles/helper-classes/general.scss
  ui/lib/ldap/addon/components/accounts-checked-out.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.ts
  ui/lib/ldap/addon/components/page/library/check-out.hbs
  ui/lib/ldap/addon/routes/libraries/library/check-out.ts
  ui/lib/ldap/addon/templates/libraries/library/check-out.hbs
  ui/tests/integration/components/ldap/page/library/check-out-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22284 UI: kv v2 nav test fixes pt 1
  ui/app/adapters/kv/data.js
  ui/app/models/kv/data.js
  ui/app/serializers/kv/data.js
  ui/lib/kv/addon/components/kv-version-dropdown.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/routes/secret.js
  ui/lib/kv/addon/routes/secret/details.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/helpers/kv/kv-run-commands.js
  ui/tests/helpers/policy-generator/kv.js
  ui/tests/unit/adapters/kv/data-test.js
Labels: hashicorp-contributed-pr

#22302 Improve docs around enable_rate_limit_response_headers
  website/content/api-docs/system/quotas-config.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22305 Adjust the omitempty json flags within CIEPSResponse
  sdk/helper/certutil/cieps.go
Labels: secret/pki, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22306 handle mutual exclusion of rotation fields
  builtin/logical/database/path_roles.go
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22307 UI: add deletion_time to details
  ui/app/models/kv/data.js
  ui/lib/kv/addon/components/kv-tooltip-timestamp.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-create-new-version-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22303 adv ttl mgmt: add rotation_window field
  builtin/logical/database/backend.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rotation.go
Labels: hashicorp-contributed-pr

#22320 suggestion for log test message fix
  audit/entry_formatter.go
  audit/nodes.go
  audit/nodes_test.go
  audit/types.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#22308 Use non-persistent Salter for logging test message
  audit/entry_formatter.go
  audit/nodes.go
  audit/nodes_test.go
  audit/types.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22304 Chroot Listener
  changelog/22304.txt
  command/server/config_test_helpers.go
  command/server/test-fixtures/config3.hcl
  go.sum
  http/handler.go
  http/handler_stubs_oss.go
  http/util.go
  internalshared/configutil/listener.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/testcluster/docker/environment.go
  sdk/helper/testcluster/types.go
Labels: backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22322 Bump consul-template 0.32.0 -> 0.33.0
  changelog/22322.txt
  command/agent_test.go
  go.mod
  go.sum
Labels: agent, dependencies, backport/1.14.x, hashicorp-contributed-pr

#22310 UI: fix/simplify linting config
  ui/.template-lintrc.js
  ui/app/templates/components/backend-configure.hbs
  ui/tests/integration/components/policy-example-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#21495 Update step-down.mdx
  changelog/21495.txt
  website/content/docs/commands/operator/step-down.mdx
Labels: docs, core, core/ha, pr/no-changelog, pr/no-milestone

#21450 Update ServiceNow Vault documentation
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, ServiceNow, hashicorp-contributed-pr

#22330 secrets/ldap: upgrade to v0.11.1 for bug fix
  changelog/22330.txt
  go.mod
  go.sum
Labels: backport/1.14.x, hashicorp-contributed-pr

#22331 secrets/ldap: upgrade to v0.10.2 for bug fix
  changelog/22331.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22332 secrets/ldap: upgrade to v0.9.2 for bug fix
  changelog/22332.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22338 Backport into 1.14.x: Bump consul-template 0.32.0 -> 0.33.0 (#22322)
  changelog/22322.txt
  command/agent_test.go
  go.mod
  go.sum
Labels: backport, agent, dependencies, pr/no-changelog, hashicorp-contributed-pr

#22325 LDAP Overview Cards
  ui/app/adapters/ldap/library.js
  ui/app/styles/components/overview-card.scss
  ui/app/styles/helper-classes/colors.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.ts
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/ldap/addon/components/page/overview.hbs
  ui/lib/ldap/addon/components/page/overview.ts
  ui/lib/ldap/addon/routes/overview.ts
  ui/lib/ldap/addon/templates/overview.hbs
  ui/tests/integration/components/ldap/accounts-checked-out-test.js
  ui/tests/integration/components/ldap/page/configuration-test.js
  ui/tests/integration/components/ldap/page/configure-test.js
  ui/tests/integration/components/ldap/page/libraries-test.js
  ui/tests/integration/components/ldap/page/library/details/accounts-test.js
  ui/tests/integration/components/ldap/page/overview-test.js
  ui/tests/integration/components/ldap/page/roles-test.js
  ui/types/vault/adapters/ldap/library.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22345 Backport of [DOCS] Content update for issue #20021 into release/1.14.x
  website/content/docs/auth/aws.mdx
Labels: hashicorp-contributed-pr

#22343 Convert OSS language to "community"
  website/content/api-docs/relatedtools.mdx
  website/content/api-docs/secret/identity/mfa/index.mdx
  website/content/api-docs/secret/pki.mdx
  website/content/api-docs/system/internal-counters.mdx
  website/content/api-docs/system/mfa/index.mdx
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/concepts/integrated-storage/index.mdx
  website/content/docs/concepts/mount-migration.mdx
  website/content/docs/concepts/storage.mdx
  website/content/docs/deprecation/faq.mdx
  website/content/docs/deprecation/index.mdx
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/faq/ssct.mdx
  website/content/docs/platform/aws/index.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/release-notes/1.10.0.mdx
  website/content/docs/release-notes/1.11.0.mdx
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/upgrading/index.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.8.x.mdx
  website/content/partials/builds-without-ui.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22347 [DOCS] Manual backport for OSS language updates
  website/content/api-docs/relatedtools.mdx
  website/content/api-docs/secret/identity/mfa/index.mdx
  website/content/api-docs/secret/pki.mdx
  website/content/api-docs/system/internal-counters.mdx
  website/content/api-docs/system/mfa/index.mdx
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/concepts/integrated-storage/index.mdx
  website/content/docs/concepts/mount-migration.mdx
  website/content/docs/concepts/storage.mdx
  website/content/docs/deprecation/faq.mdx
  website/content/docs/deprecation/index.mdx
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/faq/ssct.mdx
  website/content/docs/platform/aws/index.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/release-notes/1.10.0.mdx
  website/content/docs/release-notes/1.11.0.mdx
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/upgrading/index.mdx
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.8.x.mdx
  website/content/partials/builds-without-ui.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#18298 Add description for VaultSharp client library
  website/content/api-docs/libraries.mdx
Labels: docs

#22348 Move version diff to dropdown and remove from tab
  ui/lib/kv/addon/components/kv-version-dropdown.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-diff.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-engine-permissions-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22349 ui: client count card refactor
  ui/app/components/dashboard/client-count-card.js
Labels: hashicorp-contributed-pr

#10961 Add support for signed GET requests for aws authentication
  builtin/credential/aws/backend.go
  builtin/credential/aws/path_config_client.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  changelog/10961.txt
  website/content/api-docs/auth/aws.mdx
Labels: ecosystem, auth/aws

#22323 UI: [VAULT-17041] Client count card
  ui/app/components/dashboard/client-count-card.js
  ui/app/routes/vault/cluster/dashboard.js
  ui/app/styles/helper-classes/spacing.scss
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/components/clients/no-data.hbs
  ui/app/templates/components/dashboard/client-count-card.hbs
  ui/app/templates/vault/cluster/dashboard.hbs
  ui/tests/integration/components/dashboard/client-count-card-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22341 adv ttl mgmt: Ensure initialization sets appropriate rotation schedule
  builtin/logical/database/path_roles.go
  builtin/logical/database/rotation.go
Labels: hashicorp-contributed-pr

#22353 audit: remove extra metric
  vault/audit_broker.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#22358 Add clarification about TLS configuration options needed to enable TL…
  website/content/docs/auth/cert.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#16460 docs: add notice regarding GitHub SSO enabled orgnization
  website/content/docs/auth/github.mdx
Labels: docs, auth/github, pr/no-changelog

#22361 Backport of Add clarification about TLS configuration options needed to enable TL… into release/1.14.x
  website/content/docs/auth/cert.mdx
Labels: hashicorp-contributed-pr

#22351 Skip security-scan and test comment notifications on community PRs
  .github/workflows/ci.yml
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22365 Backport of add autoloaded license path to the cache exempt list into release/1.13.x
  changelog/22363.txt
  sdk/physical/cache.go
Labels: hashicorp-contributed-pr

#22366 Backport of add autoloaded license path to the cache exempt list into release/1.14.x
  changelog/22363.txt
  sdk/physical/cache.go
Labels: hashicorp-contributed-pr

#22370 Backport of Don't rely on post-unseal funcs being run in any particular order. into release/1.14.x
  changelog/21470.txt
  changelog/22362.txt
  vault/auth.go
  vault/mount.go
Labels: hashicorp-contributed-pr

#22368 Backport of Don't rely on post-unseal funcs being run in any particular order. into release/1.12.x
  changelog/21470.txt
  changelog/22362.txt
  vault/auth.go
  vault/mount.go
Labels: hashicorp-contributed-pr

#22369 Backport of Don't rely on post-unseal funcs being run in any particular order. into release/1.13.x
  changelog/21470.txt
  changelog/22362.txt
  vault/auth.go
  vault/mount.go
Labels: hashicorp-contributed-pr

#22319 Update linux package license to BUSL-1.1
  .github/workflows/build-vault-oss.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#18305 Update JWT docs to not recommend `-path` for `vault write`
  website/content/docs/auth/jwt/index.mdx
Labels: docs, pr/no-changelog

#22236 Backport of Ignore errors from rollback manager invocations into release/1.12.x
  changelog/22235.txt
  vault/external_tests/router/router_ext_test.go
  vault/mount.go
  vault/router_testing.go
Labels: hashicorp-contributed-pr

#22238 Backport of Ignore errors from rollback manager invocations into release/1.14.x
  changelog/22235.txt
  vault/external_tests/router/router_ext_test.go
  vault/mount.go
  vault/router_testing.go
Labels: hashicorp-contributed-pr

#22340 KV delete modal
  ui/app/adapters/kv/data.js
  ui/app/adapters/kv/metadata.js
  ui/app/models/kv/metadata.js
  ui/app/styles/components/modal-component.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/helper-classes/layout.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/utils/kv-path.ts
  ui/lib/kv/addon/components/kv-delete-modal.hbs
  ui/lib/kv/addon/components/kv-delete-modal.js
  ui/lib/kv/addon/components/page/list.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.js
  ui/lib/kv/addon/components/page/secret/metadata/version-diff.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-diff.js
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/integration/components/kv/page/kv-page-version-history-test.js
  ui/tests/unit/adapters/kv/data-test.js
  ui/tests/unit/adapters/kv/metadata-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22328 UI: Copy/wrap kv secret
  ui/app/adapters/kv/data.js
  ui/app/components/secret-edit-toolbar.js
  ui/app/templates/components/secret-edit-toolbar.hbs
  ui/lib/core/addon/components/copy-secret-dropdown.hbs
  ui/lib/core/app/components/copy-secret-dropdown.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/tests/acceptance/secrets/backend/cubbyhole/secret-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/helpers/secret-edit-toolbar.js
  ui/tests/integration/components/copy-secret-dropdown-test.js
Labels: ui, hashicorp-contributed-pr

#12666 make etcd param MaxCallSendMsgSize configurable
  changelog/12666.txt
  physical/etcd/etcd3.go
  website/content/docs/configuration/storage/etcd.mdx
Labels: waiting-for-response, storage/etcd, pr/no-changelog

#22352 add unit tests to handle mutual exclusion
  builtin/logical/database/path_roles_test.go
Labels: hashicorp-contributed-pr

#22374 Prevent a deadlock in expiration
  changelog/22374.txt
  vault/expiration.go
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#21961 Backport of fix: Broken docs links for Auto-Auth page into release/1.14.x
  website/content/docs/agent-and-proxy/agent/apiproxy.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#20980 updated the clarification note for performance_multiplier
  website/content/docs/configuration/storage/raft.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, hashicorp-contributed-pr

#22026 Clarify license reporting timing and other details
  website/content/docs/enterprise/license/utilization-reporting.mdx
Labels: docs, backport/1.11.x, backport/1.12.x, backport/1.13.x, hashicorp-contributed-pr

#21927 Docs: Add metrics for mount table monitoring
  website/content/docs/internals/limits.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22386 Backport of Docs: Add metrics for mount table monitoring into release/1.14.x
  website/content/docs/internals/limits.mdx
Labels: hashicorp-contributed-pr

#22377 Backport of Prevent a deadlock in expiration into release/1.12.x
  changelog/22374.txt
  vault/expiration.go
Labels: hashicorp-contributed-pr

#22382 Backport of updated the clarification note for performance_multiplier into release/1.13.x
  website/content/docs/configuration/storage/raft.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22378 Backport of Prevent a deadlock in expiration into release/1.13.x
  changelog/22374.txt
  vault/expiration.go
Labels: hashicorp-contributed-pr

#22376 adv ttl mgmt: add tests for init queue
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rotation_test.go
Labels: hashicorp-contributed-pr

#22379 Backport of Prevent a deadlock in expiration into release/1.14.x
  changelog/22374.txt
  vault/expiration.go
Labels: hashicorp-contributed-pr

#13945 Backport of Typo: Corrected same typo in 2 locations (on-premise to on-premises) into stable-website
  website/content/docs/agent/index.mdx
  website/content/docs/auth/approle.mdx
  website/content/docs/auth/aws.mdx
  website/content/docs/configuration/listener/tcp.mdx
  website/content/docs/internals/security.mdx
  website/next.config.js
Labels: hashicorp-contributed-pr

#22387 ui: add deleted and updated time to kv secret
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr
