Repository hashicorp/vault, pull requests merged in 2023-03, with the labels that each got.

#19312 UI: VAULT-13782 VAULT-13794 pki ui improvements for phase two
  ui/app/models/pki/certificate/generate.js
  ui/app/styles/app.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/engines.scss
  ui/app/styles/pki/pki-not-valid-after-form.scss
  ui/lib/core/addon/helpers/options-for-backend.js
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.js
  ui/lib/pki/addon/components/pki-not-valid-after-form.hbs
  ui/lib/pki/addon/components/pki-role-generate.hbs
  ui/lib/pki/addon/utils/action-params.js
  ui/tests/integration/components/pki/pki-generate-root-test.js
  ui/tests/integration/components/pki/pki-generate-toggle-groups-test.js
Labels: ui, pr/no-changelog

#19377 Document RSA operations
  website/content/docs/secrets/transit/index.mdx
Labels: docs, secret/transit, pr/no-changelog, backport/1.13.x

#19361 Vault Status Command Differs Depending on Format
  website/content/docs/commands/status.mdx
Labels: pr/no-changelog

#19419 UI: Use specific date in clients activity test
  ui/tests/unit/adapters/clients-activity-test.js
Labels: ui, pr/no-changelog, backport/1.13.x

#19424 Updated Changelog for 1.13 and point releases
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone

#19423 Backport of UI: Use specific date in clients activity test into release/1.13.x
  ui/tests/unit/adapters/clients-activity-test.js
Labels: ui, pr/no-changelog

#19442 Backport of Configure Ember Data ID Generation into release/1.13.x
  changelog/19428.txt
  ui/app/initializers/ember-data-identifiers.js
Labels: ui, bug

#19425 UI: refactor to use pki/action model for importing a pem bundle
  ui/app/adapters/pki/issuer.js
  ui/app/models/pki/action.js
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-import-pem-bundle.hbs
  ui/lib/pki/addon/components/pki-import-pem-bundle.ts
  ui/lib/pki/addon/components/pki-issuer-cross-sign.js
  ui/lib/pki/addon/routes/issuers/import.js
  ui/lib/pki/addon/templates/issuers/import.hbs
  ui/tests/acceptance/pki-engine-route-cleanupt-test.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/pki-configure-form.js
  ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
  ui/tests/unit/adapters/pki/action-test.js
Labels: ui, pr/no-changelog

#19346 docs: updated key size in transit documentation
  website/content/api-docs/secret/transit.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19435 update entity-alias doc fix
  website/content/api-docs/secret/identity/entity-alias.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19450 Docs - update ldap page to add clarity around sAMAccountName
  website/content/docs/secrets/ldap.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19456 Add more context on the Release Notes landing page
  website/content/docs/release-notes/index.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19433 VAULT-13729 activity log test godocs
  vault/activity_log_test.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog

#19429 Pass encodeBase64 param to transit-key-actions
  changelog/19429.txt
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/tests/integration/components/transit-key-actions-test.js
Labels: ui, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19461 [docs] Link to the Nomad tutorial for Vault as OIDC provider
  website/content/docs/secrets/identity/oidc-provider.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19462 Add OpenAPI-based (Beta)
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone

#19469 ldaputil: adds comment on available text/template functions
  sdk/helper/ldaputil/client.go
Labels: pr/no-changelog, pr/no-milestone

#19467 Delete test-link-rewrites.yml
  .github/workflows/test-link-rewrites.yml
Labels: pr/no-changelog, pr/no-milestone

#19402 Change headings to h2 for entity-alias page to maintain style consistency
  website/content/api-docs/secret/identity/entity-alias.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19019 UI/vault 12818/oracle banner sll
  changelog/19019.txt
  ui/app/templates/components/database-connection.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
Labels: ui

#19448 UI: fix delete for SSH engine config
  changelog/19448.txt
  ui/app/components/configure-ssh-secret.js
  ui/app/controllers/vault/cluster/settings/configure-secret-backend.js
  ui/app/templates/components/configure-ssh-secret.hbs
  ui/app/templates/vault/cluster/settings/configure-secret-backend.hbs
  ui/tests/acceptance/settings/configure-secret-backends/configure-ssh-secret-test.js
Labels: ui, bug, backport/1.13.x

#19484 Backport of UI: fix delete for SSH engine config into release/1.13.x
  changelog/19448.txt
  ui/app/components/configure-ssh-secret.js
  ui/app/controllers/vault/cluster/settings/configure-secret-backend.js
  ui/app/templates/components/configure-ssh-secret.hbs
  ui/app/templates/vault/cluster/settings/configure-secret-backend.hbs
  ui/tests/acceptance/settings/configure-secret-backends/configure-ssh-secret-test.js
Labels: ui, bug

#18729 bug: correct handling of the zero int64 value
  changelog/18729.txt
  sdk/framework/backend.go
Labels: bug

#19474 Fix failing TestHCPLinkConnected Test
  .github/workflows/ci.yml
  Makefile
  command/server/hcp_link_config_test.go
  vault/external_tests/hcp_link/hcp_link_test.go
Labels: pr/no-changelog, pr/no-milestone

#19497 Remove the note about Vault not supporting number challenge
  website/content/docs/auth/login-mfa/faq.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19496 Add note to gcp secrets docs to explan service account key encoding
  website/content/docs/secrets/gcp.mdx
Labels: pr/no-changelog, backport/1.13.x

#19504 Backport of Add note to gcp secrets docs to explan service account key encoding into release/1.13.x
  website/content/docs/secrets/gcp.mdx
Labels: pr/no-changelog, pr/no-milestone

#19505 Un-hiding link to 1.13 upgrade guide
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19493 sdk: Fix fmt + add FieldType test
  sdk/framework/backend.go
  sdk/framework/backend_test.go
  sdk/framework/field_type.go
Labels: test, pr/no-changelog, pr/no-milestone

#19508 [Backport] Remove the note about not supporting number challenge
  website/content/docs/auth/login-mfa/faq.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#19507 [Backport] Remove the note about not supporting number challenge
  website/content/docs/auth/login-mfa/faq.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#19519 Add support for importing RSA-PSS keys into Transit
  builtin/logical/transit/path_import_test.go
  changelog/19519.txt
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/util.go
Labels: enhancement, secret/transit

#19495 Make shamir functions constant time
  shamir/shamir.go
  shamir/tables.go
  shamir/tables_test.go
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19533 Explain use of math/rand in LifetimeWatcher
  api/lifetime_watcher.go
Labels: sdk, pr/no-changelog

#19468 Fix a possible data race with rollback manager and plugin reload
  changelog/19468.txt
  vault/external_tests/plugin/external_plugin_test.go
  vault/external_tests/plugin/plugin_test.go
  vault/router.go
Labels: backport/1.12.x, backport/1.13.x

#19530 Ignore special HTTP fields in response validation tests
  builtin/logical/pki/path_fetch.go
  sdk/helper/testhelpers/schema/response_validation.go
  sdk/helper/testhelpers/schema/response_validation_test.go
Labels: pr/no-changelog

#18612 PKI Responses Part 4
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_ocsp_test.go
  builtin/logical/pki/path_resign_crls.go
  builtin/logical/pki/path_resign_crls_test.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_sign_issuers.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
Labels: pr/no-changelog

#19517 Glimmer Navigate Input component
  ui/app/templates/vault/cluster/policies/index.hbs
  ui/lib/core/addon/components/navigate-input.hbs
  ui/lib/core/addon/components/navigate-input.js
  ui/lib/core/addon/templates/components/navigate-input.hbs
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/tests/acceptance/aws-test.js
  ui/tests/acceptance/leases-test.js
  ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
  ui/tests/acceptance/ssh-test.js
  ui/tests/integration/components/auth-form-test.js
  ui/tests/pages/secrets/backend/kmip/credentials.js
Labels: ui, pr/no-changelog

#19548 Update auto-auth docs to remove tilde for home
  website/content/docs/agent/autoauth/methods/token_file.mdx
Labels: agent, pr/no-changelog, pr/no-milestone

#19542 Add the Tokenization/Rotation persistence issue as a Known Issue
  website/content/docs/upgrading/upgrade-to-1.10.x.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/partials/tokenization-rotation-persistence.mdx
Labels: pr/no-changelog

#19545 database/elasticsearch: upgrades plugin to v0.13.1
  changelog/19545.txt
  go.mod
  go.sum
Labels: backport/1.13.x

#19560 ci: pin terraform until planning bug is resolved
  .github/workflows/enos-fmt.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19531 Add upgrade docs for Removed builtins in 1.13
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19574 Backport of Add upgrade docs for Removed builtins in 1.13 into release/1.13.x
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: pr/no-changelog, pr/no-milestone

#19583 Comment Out HCP_SCADA_ADDRESS Environment Variable
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#19446 Sidebar Navigation Components
  ui/app/components/sidebar/frame.hbs
  ui/app/components/sidebar/frame.js
  ui/app/components/sidebar/nav/access.hbs
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/cluster.js
  ui/app/components/sidebar/nav/policies.hbs
  ui/app/components/sidebar/nav/tools.hbs
  ui/app/components/sidebar/user-menu.hbs
  ui/app/components/sidebar/user-menu.js
  ui/app/styles/app.scss
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/sidebar.scss
  ui/app/templates/application.hbs
  ui/app/templates/components/namespace-picker.hbs
  ui/app/templates/vault.hbs
  ui/ember-cli-build.js
  ui/package.json
  ui/tests/acceptance/cluster-test.js
  ui/tests/acceptance/mfa-setup-test.js
  ui/tests/helpers/components/sidebar-nav.js
  ui/tests/integration/components/sidebar/frame-test.js
  ui/tests/integration/components/sidebar/nav/access-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/components/sidebar/nav/policies-test.js
  ui/tests/integration/components/sidebar/nav/tools-test.js
  ui/tests/integration/components/sidebar/user-menu-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog

#19584 [QT-523] Remove copyright/license header from raft config used in theDocker/K8S integration test
  .copywrite.hcl
  enos/modules/k8s_deploy_vault/raft-config.hcl
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19586 VAULT-14204 Update parameter policy documentation
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog

#19371 update link policy fetch URL
  vault/hcp_link/capabilities/api_capability/token_manager.go
Labels: pr/no-changelog, backport/1.13.x

#19569 UI: Glimmerize - Colocate template and remove component file
  ui/lib/core/addon/components/form-error.hbs
  ui/lib/core/addon/components/form-error.js
  ui/lib/core/addon/components/layout-loading.hbs
  ui/lib/core/addon/components/layout-loading.js
  ui/lib/core/addon/components/menu-loader.hbs
  ui/lib/core/addon/components/menu-loader.js
  ui/lib/core/addon/components/popup-menu.hbs
  ui/lib/core/addon/components/popup-menu.js
  ui/lib/core/addon/components/search-select-placeholder.hbs
  ui/lib/core/addon/components/search-select-placeholder.js
  ui/lib/core/addon/components/toolbar-actions.hbs
  ui/lib/core/addon/components/toolbar-actions.js
  ui/lib/core/addon/components/toolbar-filters.hbs
  ui/lib/core/addon/components/toolbar-filters.js
  ui/lib/core/addon/components/toolbar.hbs
  ui/lib/core/addon/components/toolbar.js
  ui/lib/core/addon/components/vault-logo-spinner.hbs
  ui/lib/core/addon/components/vault-logo-spinner.js
  ui/lib/core/addon/templates/components/menu-loader.hbs
  ui/lib/core/addon/templates/components/popup-menu.hbs
Labels: ui, pr/no-changelog

#19572 UI: Glimmerize InfoTable, PageHeader, UpgradePage, NamespaceReminder, PageHeaderLevel Left,Right,Top
  ui/lib/core/addon/components/info-table.hbs
  ui/lib/core/addon/components/info-table.js
  ui/lib/core/addon/components/namespace-reminder.hbs
  ui/lib/core/addon/components/namespace-reminder.js
  ui/lib/core/addon/components/page-header-level-left.js
  ui/lib/core/addon/components/page-header-level-right.js
  ui/lib/core/addon/components/page-header-level.hbs
  ui/lib/core/addon/components/page-header-top.js
  ui/lib/core/addon/components/page-header.hbs
  ui/lib/core/addon/components/page-header.js
  ui/lib/core/addon/components/upgrade-page.hbs
  ui/lib/core/addon/components/upgrade-page.js
  ui/lib/core/addon/templates/components/page-header.hbs
  ui/lib/core/app/components/page-header-level-left.js
  ui/lib/core/app/components/page-header-level-right.js
  ui/lib/core/app/components/page-header-level.js
  ui/lib/core/app/components/page-header-top.js
Labels: ui, pr/no-changelog

#19607 Update KV-V2 docs to explicitly call out the secret mount path as a parameter
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, pr/no-milestone

#19570 UI: Glimmerize Chevron, EmptyState, FieldGroupShow, InfoTooltip, Icon
  ui/lib/core/addon/components/chevron.hbs
  ui/lib/core/addon/components/chevron.js
  ui/lib/core/addon/components/empty-state.hbs
  ui/lib/core/addon/components/empty-state.js
  ui/lib/core/addon/components/field-group-show.hbs
  ui/lib/core/addon/components/field-group-show.js
  ui/lib/core/addon/components/icon.hbs
  ui/lib/core/addon/components/icon.js
  ui/lib/core/addon/components/info-tooltip.hbs
  ui/lib/core/addon/components/info-tooltip.js
  ui/lib/core/addon/templates/components/icon.hbs
  ui/lib/core/addon/templates/components/info-tooltip.hbs
  ui/tests/integration/components/chevron-test.js
Labels: ui, pr/no-changelog

#19598 Backport of [QT-523] Remove copyright/license header from raft config used in theDocker/K8S integration test into release/1.13.x
  .copywrite.hcl
Labels: pr/no-changelog, pr/no-milestone

#19523 Add known issue about OCSP GET redirection responses
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/partials/ocsp-redirect.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19613 Backport of Add known issue about OCSP GET redirection responses into release/1.13.x
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/partials/ocsp-redirect.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#19612 Backport of Add known issue about OCSP GET redirection responses into release/1.12.x
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/partials/ocsp-redirect.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#19593 Suppress event broker not started log warning
  changelog/19593.txt
  sdk/plugin/grpc_events.go
  vault/auth.go
  vault/mount.go
Labels: backport/1.13.x

#19580 VAULT-8337 OSS changes
  vault/request_handling.go
  vault/token_store.go
Labels: pr/no-changelog, pr/no-milestone

#19625 Add no-op CensusAgent
  changelog/19625.txt
  vault/activity_log.go
  vault/activity_log_util.go
  vault/census.go
  vault/core.go
  vault/testing.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x

#19624 Forward PKI revocation requests received by standby nodes to active node
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_revoke.go
  changelog/19624.txt
Labels: bug, secret/pki, backport/1.13.x

#19447 Replace and remove old nav components with new ones
  ui/app/components/cluster-info.js
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/splash-page.js
  ui/app/controllers/application.js
  ui/app/controllers/vault.js
  ui/app/controllers/vault/cluster.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/services/auth.js
  ui/app/styles/components/sidebar.scss
  ui/app/styles/core/layout.scss
  ui/app/templates/application.hbs
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/components/splash-page.hbs
  ui/app/templates/vault.hbs
  ui/app/templates/vault/cluster.hbs
  ui/app/templates/vault/cluster/access.hbs
  ui/app/templates/vault/cluster/policies.hbs
  ui/app/templates/vault/cluster/policy.hbs
  ui/app/templates/vault/cluster/tools/tool.hbs
  ui/app/templates/vault/cluster/unseal.hbs
  ui/app/templates/vault/error.hbs
  ui/lib/core/addon/templates/components/replication-header.hbs
  ui/lib/replication/addon/routes/application.js
Labels: ui, pr/no-changelog

#19631 More wrapped errors - PKI, SSH, Transit
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/storage.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/transit/path_keys.go
Labels: bug, pr/no-changelog

#19632 Add known issue text for PKI revocation
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.13.x

#19640 secrets/ldap: upgrades plugin to v0.10.1
  changelog/19640.txt
  go.mod
  go.sum
Labels: backport/1.13.x

#19573 docs / update 'vault plugin deregister' command doc
  website/content/docs/commands/plugin/deregister.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19378 Add `-mount` flag to kv list command
  changelog/19378.txt
  command/kv_list.go
  command/kv_test.go
  website/content/docs/commands/kv/list.mdx
Labels: pr/no-milestone

#19636 Backport of openapi: Fix logic for labeling unauthenticated/sudo paths into release/1.13.x
  changelog/19600.txt
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
Labels: pr/no-milestone

#19647 Fix for PKI.TestStandby_Operations test to work in ENT
  builtin/logical/pki/backend_test.go
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19648 Backport of Fix for PKI.TestStandby_Operations test to work in ENT into release/1.13.x
  builtin/logical/pki/backend_test.go
Labels: pr/no-changelog, pr/no-milestone

#19646 Manually cherry-pick docs PR 19573
  website/content/docs/commands/plugin/deregister.mdx
Labels: pr/no-changelog, pr/no-milestone

#19650 activitylog: Fix pq.Get trace logger output
  vault/activity/query.go
Labels: pr/no-changelog, pr/no-milestone

#19601 docs / Update 1.13.0 Known Issues
  website/content/docs/release-notes/1.13.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19541 UI/update auth form to fetchRoles after a namespace is inputted, prior to OIDC auth
  changelog/19541.txt
  ui/app/components/auth-jwt.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/pages/auth.js
Labels: ui, bug, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19611 use Platform from host info for node status OS
  vault/hcp_link/capabilities/node_status/node_status.go
Labels: pr/no-changelog, backport/1.13.x

#19561 Add a GHA job running Go tests with race detection enabled to the CI …
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
  Makefile
Labels: pr/no-changelog, pr/no-milestone

#19587 Step one: remove bulma
  ui/app/styles/components/box-label.scss
  ui/app/styles/components/confirm.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/core.scss
  ui/app/styles/core/element-styling.css
  ui/app/styles/core/forms.scss
  ui/app/styles/core/helpers.scss
  ui/app/styles/utils/_bulma_checkboxes.css
  ui/app/styles/utils/_bulma_switch.css
  ui/app/styles/utils/_bulma_variables.scss
  ui/lib/css/index.js
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog

#19637 Backport of openapi: Fix logic for labeling unauthenticated/sudo paths into release/1.12.x
  changelog/19600.txt
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
Labels: pr/no-milestone

#19634 Backport of openapi: Fix logic for labeling unauthenticated/sudo paths into release/1.11.x
  changelog/19600.txt
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
Labels: pr/no-milestone

#19667 Updated connection_url to be pgx library relevant
  website/content/api-docs/secret/databases/postgresql.mdx
Labels: website, secret/database/postgresql, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19662 Migrating CircleCI Jobs to GHA Workflow
  .github/actionlint.yaml
  .github/workflows/actionlint.yml
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/godoc-test-checker.yml
  .github/workflows/oss.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#19671 UI: fix enterprise test failures
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/enterprise-oidc-namespace-test.js
Labels: ui, pr/no-changelog

#19681 Nav component cleanup
  ui/app/components/auth-info.js
  ui/app/components/cluster-info.js
  ui/app/components/menu-sidebar.js
  ui/app/components/nav-header.js
  ui/app/components/nav-header/home.js
  ui/app/components/nav-header/items.js
  ui/app/components/nav-header/main.js
  ui/app/components/sidebar/frame.hbs
  ui/app/components/status-menu.js
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/components/sidebar.scss
  ui/app/styles/components/splash-page.scss
  ui/app/styles/components/status-menu.scss
  ui/app/styles/core.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/templates/components/auth-info.hbs
  ui/app/templates/components/calendar-widget.hbs
  ui/app/templates/components/cluster-info.hbs
  ui/app/templates/components/link-status.hbs
  ui/app/templates/components/menu-sidebar.hbs
  ui/app/templates/components/nav-header.hbs
  ui/app/templates/components/status-menu.hbs
  ui/app/templates/vault/not-found.hbs
  ui/lib/core/addon/templates/components/replication-mode-summary.hbs
  ui/lib/replication/addon/templates/index.hbs
  ui/lib/replication/addon/templates/mode.hbs
  ui/tests/acceptance/access/methods-test.js
  ui/tests/acceptance/auth-test.js
  ui/tests/acceptance/client-dashboard-test.js
  ui/tests/acceptance/cluster-test.js
  ui/tests/acceptance/enterprise-replication-test.js
  ui/tests/acceptance/mfa-login-enforcement-test.js
  ui/tests/acceptance/mfa-method-test.js
  ui/tests/acceptance/mfa-setup-test.js
  ui/tests/acceptance/not-found-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/tools-test.js
  ui/tests/helpers/clients.js
  ui/tests/helpers/components/sidebar-nav.js
  ui/tests/integration/components/link-status-test.js
  ui/tests/integration/components/nav-header-test.js
  ui/tests/integration/components/sidebar/frame-test.js
  ui/tests/integration/components/sidebar/nav/tools-test.js
  ui/tests/pages/access/methods.js
  ui/tests/pages/components/nav-header.js
  ui/tests/pages/settings/mount-secret-backend.js
Labels: ui, pr/no-changelog

#19664 Step two: add back and organize relevant Bulma classes
  ui/app/styles/core.scss
  ui/app/styles/core/bulma-classes.css
  ui/app/styles/core/helpers.scss
  ui/app/styles/helper-classes/colors.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/styles/helper-classes/helpers.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_color_variables.scss
  ui/app/styles/utils/_size_variables.scss
  ui/app/styles/utils/_spacing.scss
Labels: ui, pr/no-changelog

#19677 UI: VAULT-6519 PKI configuration read
  ui/app/adapters/pki/crl.js
  ui/app/models/mount-config.js
  ui/app/models/pki/crl.js
  ui/app/styles/core/helpers.scss
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/page/pki-configuration-details.js
  ui/tests/integration/components/pki/page/pki-configuration-details-test.js
Labels: ui, pr/no-changelog

#19683 Step three: add Bulma classes to relevant component styles
  ui/app/styles/components/modal.scss
  ui/app/styles/components/replication-header.scss
  ui/app/styles/components/tabs.scss
  ui/app/styles/components/ui-wizard.scss
  ui/app/styles/core.scss
  ui/app/styles/core/breadcrumb.scss
  ui/lib/core/addon/templates/components/replication-header.hbs
Labels: ui, pr/no-changelog

#19685 [Docs] Fix the title parsing error - userpass
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19661 Backport 1.13.x: UI/update auth form to fetchRoles after a namespace is inputted, prior to OIDC auth #19541
  changelog/19541.txt
  ui/app/components/auth-jwt.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/enterprise-oidc-namespace-test.js
  ui/tests/pages/auth.js
Labels: ui, backport, bug

#19694 Backport 1.11.x: AD FS namespace OIDC bug fix #19460
  changelog/19460.txt
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/tests/unit/routes/vault/cluster/oidc-callback-test.js
Labels: ui, backport, bug

#19701 Make sure that we specify Backoff in conjunction with MinConnectTimeout
  vault/request_forwarding.go
Labels: pr/no-changelog

#19696 Backport 1.13.x: AD FS namespace OIDC bug fix #19460
  changelog/19460.txt
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/tests/unit/routes/vault/cluster/oidc-callback-test.js
Labels: ui, backport, bug

#19700 VAULT-8337 Revert "VAULT-8337 OSS changes"
  vault/request_handling.go
  vault/token_store.go
Labels: pr/no-changelog

#19704 Add tests for PKI endpoint authentication via OpenAPI
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_fetch_issuers.go
Labels: secret/pki, pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19691 Step three cont. Bulma classes to component files
  ui/app/styles/components/box-label.scss
  ui/app/styles/components/icon.scss
  ui/app/styles/components/modal.scss
  ui/app/styles/core.scss
  ui/app/styles/core/box.scss
  ui/app/styles/core/bulma-classes.css
  ui/app/styles/core/buttons.scss
Labels: ui, pr/no-changelog

#19703 Secret Metadata Breadcrumb Bug
  changelog/19703.txt
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/tests/acceptance/secrets/backend/kv/breadcrumbs-test.js
Labels: ui, bug, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19365 auth/aws: pass cancelable context with AWS calls
  builtin/credential/aws/backend.go
  builtin/credential/aws/client.go
  builtin/credential/aws/path_config_rotate_root.go
  builtin/credential/aws/path_config_rotate_root_test.go
  builtin/credential/aws/path_login.go
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/iam_policies.go
  builtin/logical/aws/iam_policies_test.go
  builtin/logical/aws/path_config_rotate_root.go
  builtin/logical/aws/path_user.go
  builtin/logical/aws/secret_access_keys.go
  changelog/19365.txt
Labels: enhancement, secret/aws, auth/aws

#19714 Backport of Secret Metadata Breadcrumb Bug into release/1.11.x
  changelog/19703.txt
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/tests/acceptance/secrets/backend/kv/breadcrumbs-test.js
Labels: ui, bug

#19716 Backport of Secret Metadata Breadcrumb Bug into release/1.13.x
  changelog/19703.txt
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/tests/acceptance/secrets/backend/kv/breadcrumbs-test.js
Labels: ui, bug

#19730 Backport of ci: unpin terraform in CI into release/1.12.x
  .github/workflows/enos-fmt.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#18896 Add OpenAPI Go and C#
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19690 Update username template description for AWS
  website/content/api-docs/secret/aws.mdx
Labels: secret/aws, website, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19721 Address regression introduced by #15493 for non-raft storage backends.
  changelog/19721.txt
  vault/ha.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x

#19741 Console Panel Updates
  ui/app/components/sidebar/frame.hbs
  ui/app/components/sidebar/frame.js
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/sidebar.scss
  ui/app/templates/components/console/log-command.hbs
  ui/app/templates/components/console/ui-panel.hbs
  ui/tests/acceptance/console-test.js
Labels: ui, pr/no-changelog

#19742 Migrate the FIPS testing job to GitHub Actions
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#19719 Step four: address core directory files
  ui/app/styles/components/icon.scss
  ui/app/styles/core.scss
  ui/app/styles/core/box.scss
  ui/app/styles/core/bulma-classes.css
  ui/app/styles/core/element-styling.scss
  ui/app/styles/core/generic.scss
  ui/app/styles/core/hero.scss
  ui/app/styles/core/level.scss
  ui/app/styles/core/link.scss
  ui/app/styles/core/menu.scss
  ui/app/styles/helper-classes/other.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_size_variables.scss
Labels: ui, pr/no-changelog

#19747 Marcboudreau/vault 13760/add test UI to completed
  .github/workflows/ci.yml
  .hooks/pre-commit
Labels: pr/no-changelog, pr/no-milestone

#19751 Remove CircleCI Configuration
  .circleci/.gitattributes
  .circleci/.gitignore
  .circleci/Makefile
  .circleci/README.md
  .circleci/config.yml
  .circleci/config/@config.yml
  .circleci/config/commands/@caches.yml
  .circleci/config/commands/configure-git.yml
  .circleci/config/commands/exit-if-branch-does-not-need-test-ui.yml
  .circleci/config/commands/exit-if-ui-or-docs-branch.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/commands/setup-go.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/build-go-dev.yml
  .circleci/config/jobs/fmt.yml
  .circleci/config/jobs/install-ui-dependencies.yml
  .circleci/config/jobs/pre-flight-checks.yml
  .circleci/config/jobs/semgrep.yml
  .circleci/config/jobs/test-go-nightly.yml
  .circleci/config/jobs/test-go-race-remote-docker.yml
  .circleci/config/jobs/test-go-race.yml
  .circleci/config/jobs/test-go-remote-docker.yml
  .circleci/config/jobs/test-go.yml
  .circleci/config/jobs/test-ui.yml
  .circleci/config/workflows/ci.yml
  .github/workflows/goversion-checker.yml
  .hooks/pre-commit
  Makefile
Labels: pr/no-changelog, pr/no-milestone

#19738 add warning for vault lambda extension cache ttl
  website/content/docs/platform/aws/lambda-extension.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19768 docs: Fix duration format link in kv-v2 docs page
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: docs, pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19754 UI/step four core files 2
  ui/app/styles/components/modal.scss
  ui/app/styles/core.scss
  ui/app/styles/core/bulma-classes.css
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/element-styling.scss
  ui/app/styles/core/forms.scss
  ui/app/styles/core/select.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/styles/utils/_size_variables.scss
  ui/app/templates/components/secret-create-or-update.hbs
  ui/lib/core/addon/templates/components/shamir-flow.hbs
  ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
Labels: ui, pr/no-changelog

#19774 Backport of docs: Fix duration format link in kv-v2 docs page into release/1.13.x
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, pr/no-milestone

#19773 Backport of docs: Fix duration format link in kv-v2 docs page into release/1.12.x
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, pr/no-milestone

#19771 Backport of docs: Fix duration format link in kv-v2 docs page into release/1.10.x
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, pr/no-milestone

#19750 UI: secret-engine model octanified
  ui/app/decorators/model-expanded-attributes.js
  ui/app/models/secret-engine.js
  ui/app/routes/vault/cluster/secrets/backend/create-root.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/unit/decorators/model-expanded-attributes-test.js
  ui/tests/unit/models/secret-engine-test.js
Labels: ui, pr/no-changelog

#19777 openapi: Remove 'ad' from gen_openapi.sh
  helper/builtinplugins/registry_test.go
  scripts/gen_openapi.sh
Labels: pr/no-changelog

#19727 UI: Test business logic for oidc callback params
  ui/app/routes/vault/cluster/oidc-callback.js
  ui/tests/unit/routes/vault/cluster/oidc-callback-test.js
Labels: ui, pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19666 Github Action to check deprecations in PR
  .github/workflows/drepecated-functions-checker.yml
  Makefile
  go.mod
  go.sum
  scripts/deprecations-checker.sh
  tools/tools.go
Labels: pr/no-changelog, pr/no-milestone

#19698 VAULT-8337 OSS changes part 2
  vault/request_handling.go
Labels: pr/no-changelog

#19779 Cleaning up the last of the core files (welp there's still more)
  ui/app/styles/components/box-label.scss
  ui/app/styles/components/toolbar.scss
  ui/app/styles/core.scss
  ui/app/styles/core/bulma-classes.css
  ui/app/styles/core/columns.scss
  ui/app/styles/core/level.scss
  ui/app/styles/core/link.scss
  ui/app/styles/core/menu.scss
  ui/app/styles/core/message.scss
  ui/app/styles/core/notification.scss
  ui/app/styles/core/progress.scss
  ui/app/styles/helper-classes/colors.scss
Labels: ui, pr/no-changelog

#19359 mark internal/counters/requests as deprecated
  vault/logical_system_paths.go
Labels: pr/no-changelog

#19795 UI: Remove out of date blueprint
  ui/blueprints/component/files/__root__/__path__/__name__.js
  ui/blueprints/component/files/__root__/__templatepath__/__templatename__.hbs
  ui/blueprints/component/index.js
Labels: ui, pr/no-changelog, devex

#19801 Backport of Update Vault PKCS#11 Provider documentation for v0.2.0. into release/1.13.x
  website/content/docs/enterprise/pkcs11-provider/index.mdx
Labels: docs

#19797 Tighten JWS algorithm lists
  .github/scripts/generate-test-package-lists.sh
  builtin/logical/pki/acme/jws.go
Labels: secret/pki, pr/no-changelog

#19805 fix github ref
  .github/workflows/ci.yml
Labels: pr/no-changelog

#19808 add docs for VLE VAULT_RUN_MODE
  website/content/docs/platform/aws/lambda-extension.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19748 Add mechanism to disable automatic rollbacks
  vault/rollback.go
  vault/testing.go
Labels: test, pr/no-changelog

#19803 PKI: Initial ACME directory API support
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_acme_directory.go
  builtin/logical/pki/path_acme_directory_test.go
Labels: secret/pki, pr/no-changelog

#19822 Initial ACME new-nonce API
  builtin/logical/pki/acme/state.go
  builtin/logical/pki/acme/state_test.go
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_acme_nonce.go
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/test_helpers.go
Labels: secret/pki, pr/no-changelog

#19824 Backport of Change wording for AssumeRole permissions into release/1.13.x
  website/content/docs/secrets/aws.mdx
Labels: pr/no-changelog, pr/no-milestone

#19819 changelog: Drop entry for no-op
  changelog/19625.txt
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19820 Add ACME new account creation handlers
  builtin/logical/pki/acme/errors.go
  builtin/logical/pki/acme/jws.go
  builtin/logical/pki/acme/state.go
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_acme_directory.go
  builtin/logical/pki/path_acme_new_account.go
  builtin/logical/pki/path_acme_nonce.go
Labels: enhancement, secret/pki, pr/no-changelog

#19827 Add vault-secrets-operator beta docs.
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/index.mdx
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/telemetry.mdx
  website/content/partials/vso-beta-note.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog

#19821 Docs: API: Update token_period description
  website/content/partials/tokenstorefields.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19835 docs/vault-secrets-operator: update for beta install
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19834 changelog: updates for 1.13.1, 1.12.5, 1.11.9
  CHANGELOG.md
Labels: pr/no-changelog

#19836 backport of commit 25934124a046199f7434f9c61e1454bcbef08cdf
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/index.mdx
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/telemetry.mdx
  website/content/partials/vso-beta-note.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone

#19838 Backport of docs/vault-secrets-operator: update for beta install into release/1.13.x
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#19841 Remove acme from CI test_packages
  .github/scripts/generate-test-package-lists.sh
Labels: pr/no-changelog

#19669 Add PKI-CLI to docs
  website/content/docs/commands/pki/index.mdx
  website/content/docs/commands/pki/issue.mdx
  website/content/docs/commands/pki/list-intermediates.mdx
  website/content/docs/commands/pki/reissue.mdx
  website/content/docs/commands/pki/verify-sign.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, backport/1.13.x

#19843 Update Vault version to 1.13.2
  version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#19845 Bump SDK version to 1.11.10
  sdk/version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#19847 Bump vault version to 1.12.6
  go.mod
Labels: pr/no-changelog, pr/no-milestone

#19848 Bump Vault version to 1.11.10
  go.mod
Labels: pr/no-changelog, pr/no-milestone

#19846 plugin/secrets/alicloud: upgrade dependencies
  changelog/19846.txt
  go.mod
  go.sum
Labels: pr/no-milestone

#19770 Backport changes related to CI migration to GitHub Actions to 1.12.x
  .circleci/.gitattributes
  .circleci/.gitignore
  .circleci/Makefile
  .circleci/README.md
  .circleci/config.yml
  .circleci/config/@config.yml
  .circleci/config/commands/@caches.yml
  .circleci/config/commands/configure-git.yml
  .circleci/config/commands/exit-if-branch-does-not-need-test-ui.yml
  .circleci/config/commands/exit-if-ui-or-docs-branch.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/commands/setup-go.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/build-go-dev.yml
  .circleci/config/jobs/fmt.yml
  .circleci/config/jobs/install-ui-dependencies.yml
  .circleci/config/jobs/pre-flight-checks.yml
  .circleci/config/jobs/semgrep.yml
  .circleci/config/jobs/test-go-nightly.yml
  .circleci/config/jobs/test-go-race-remote-docker.yml
  .circleci/config/jobs/test-go-race.yml
  .circleci/config/jobs/test-go-remote-docker.yml
  .circleci/config/jobs/test-go.yml
  .circleci/config/jobs/test-ui.yml
  .circleci/config/workflows/ci.yml
  .github/actionlint.yaml
  .github/scripts/generate-test-package-lists.sh
  .github/scripts/test-generate-test-package-lists.sh
  .github/workflows/actionlint.yml
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/goversion-checker.yml
  .github/workflows/oss.yml
  .github/workflows/setup-go-cache.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .hooks/pre-commit
  Makefile
  go.mod
  go.sum
  physical/mssql/mssql.go
  serviceregistration/kubernetes/testing/testserver.go
  tools/tools.go
Labels: pr/no-changelog, pr/no-milestone

#19850 Add available types to API documentation for enable audit
  website/content/api-docs/system/audit.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19807 Add a new category of runners to the CI workflow; use new, dedicated …
  .github/workflows/ci.yml
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19775 Backport changes related to CI migration to GitHub Actions to 1.11.x
  .circleci/.gitattributes
  .circleci/.gitignore
  .circleci/Makefile
  .circleci/README.md
  .circleci/config.yml
  .circleci/config/@config.yml
  .circleci/config/commands/@caches.yml
  .circleci/config/commands/configure-git.yml
  .circleci/config/commands/exit-if-branch-does-not-need-test-ui.yml
  .circleci/config/commands/exit-if-ui-or-docs-branch.yml
  .circleci/config/commands/go_test.yml
  .circleci/config/commands/setup-go.yml
  .circleci/config/commands/setup-semgrep.yml
  .circleci/config/executors/@executors.yml
  .circleci/config/jobs/build-go-dev.yml
  .circleci/config/jobs/fmt.yml
  .circleci/config/jobs/install-ui-dependencies.yml
  .circleci/config/jobs/pre-flight-checks.yml
  .circleci/config/jobs/semgrep.yml
  .circleci/config/jobs/test-go-nightly.yml
  .circleci/config/jobs/test-go-race-remote-docker.yml
  .circleci/config/jobs/test-go-race.yml
  .circleci/config/jobs/test-go-remote-docker.yml
  .circleci/config/jobs/test-go.yml
  .circleci/config/jobs/test-ui.yml
  .circleci/config/workflows/ci.yml
  .github/actionlint.yaml
  .github/scripts/generate-test-package-lists.sh
  .github/scripts/test-generate-test-package-lists.sh
  .github/workflows/actionlint.yml
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/goversion-checker.yml
  .github/workflows/setup-go-cache.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .hooks/pre-commit
  Makefile
  go.mod
  go.sum
  physical/mssql/mssql.go
  serviceregistration/kubernetes/testing/testserver.go
  tools/tools.go
Labels: pr/no-changelog, pr/no-milestone

#19857 Add larger runners for CI
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#19830 Removing excess div wrapped on page-header-level
  ui/lib/core/addon/components/page-header-level.hbs
Labels: ui, bug, pr/no-changelog
