Repository hashicorp/vault, pull requests merged in 2023-09, with the labels that each got.

#22635 [VAULT-15398] Client count tests
  sdk/helper/clientcountutil/clientcountutil.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22725 seal_wrapper: make fmt fix
  vault/seal/seal_wrapper.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22651 Add config value that gives users options to skip calculating role for each lease
  changelog/22651.txt
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  http/util.go
  vault/core.go
  vault/request_handling.go
  vault/testing.go
  website/content/docs/configuration/index.mdx
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#22702 Backport of Add worker pool for LDAP group lookup into release/1.12.x
  changelog/22659.txt
  sdk/helper/ldaputil/client.go
Labels: hashicorp-contributed-pr

#22727 Fix activity log test for enterprise
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22729 Backport of Add config value that gives users options to skip calculating role for each lease into release/1.13.x
  changelog/22651.txt
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  http/util.go
  vault/core.go
  vault/request_handling.go
  vault/testing.go
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#22730 Backport of Add config value that gives users options to skip calculating role for each lease into release/1.14.x
  changelog/22651.txt
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  http/util.go
  vault/core.go
  vault/request_handling.go
  vault/testing.go
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#22670 KV - no list permissions error catch
  ui/lib/core/addon/components/input-search.hbs
  ui/lib/kv/addon/components/page/list.hbs
  ui/lib/kv/addon/components/page/list.js
  ui/lib/kv/addon/routes/list-directory.js
  ui/lib/kv/addon/templates/list-directory.hbs
  ui/lib/kv/addon/templates/list.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/integration/components/kv/page/kv-page-list-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22716 Update hashicorp/vault-plugin-secrets-kv to v0.16.1
  changelog/22716.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#22734 Update hashicorp/vault-plugin-secrets-openldap to v0.11.2
  changelog/22734.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#22709 fix: upgrade vault-plugin-auth-kubernetes to v0.17.0
  changelog/22709.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22710 [DOCS] Add WAF links for metric best practice guide
  website/content/docs/internals/telemetry/enable-telemetry.mdx
  website/content/docs/internals/telemetry/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22247 Backport of Automatically track subloggers in allLoggers into release/1.14.x
  changelog/22038.txt
  command/server.go
  helper/logging/logger.go
  helper/testhelpers/corehelpers/corehelpers.go
  vault/activity_log.go
  vault/audit.go
  vault/auth.go
  vault/cluster.go
  vault/core.go
  vault/core_util.go
  vault/expiration.go
  vault/identity_store.go
  vault/logical_system_test.go
  vault/mount.go
  vault/policy_store.go
  vault/raft.go
  vault/rollback.go
  vault/seal_autoseal.go
  vault/testing.go
Labels: hashicorp-contributed-pr

#22246 Backport of Automatically track subloggers in allLoggers into release/1.13.x
  changelog/22038.txt
  command/server.go
  helper/logging/logger.go
  helper/testhelpers/corehelpers/corehelpers.go
  vault/activity_log.go
  vault/audit.go
  vault/auth.go
  vault/cluster.go
  vault/core.go
  vault/core_util.go
  vault/expiration.go
  vault/identity_store.go
  vault/logical_system_test.go
  vault/mount.go
  vault/policy_store.go
  vault/raft.go
  vault/rollback.go
  vault/seal_autoseal.go
  vault/testing.go
Labels: hashicorp-contributed-pr

#22739 add copyright header
  vault/plugin_runtime_catalog.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22712 Support running plugins in isolated containers
  api/sys_plugins.go
  changelog/22712.txt
  command/plugin_info.go
  command/plugin_register.go
  command/plugin_register_test.go
  go.mod
  go.sum
  helper/testhelpers/pluginhelpers/pluginhelpers.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/runner.go
  vault/external_plugin_container_test.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  vault/plugin_catalog.go
  vault/testdata/Dockerfile
  vault/testing.go
Labels: hashicorp-contributed-pr

#22736 Backport of [DOCS] Add WAF links for metric best practice guide into release/1.14.x
  website/content/docs/internals/telemetry/enable-telemetry.mdx
  website/content/docs/internals/telemetry/index.mdx
Labels: hashicorp-contributed-pr

#22738 Remove version and version-root
  ui/app/router.js
  ui/app/routes/vault/cluster/secrets/backend/versions-root.js
  ui/app/routes/vault/cluster/secrets/backend/versions.js
  ui/app/styles/helper-classes/general.scss
  ui/app/templates/components/secret-list/item.hbs
  ui/app/templates/vault/cluster/secrets/backend/versions.hbs
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22740 Protect SealWrapper health fields
  command/server.go
  helper/testhelpers/seal/sealhelper.go
  vault/core.go
  vault/logical_system.go
  vault/rekey.go
  vault/seal/seal.go
  vault/seal/seal_testing.go
  vault/seal/seal_wrapper.go
  vault/seal_autoseal.go
  vault/seal_autoseal_test.go
  vault/seal_config.go
  vault/seal_testing_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22677 Add more docs for update-primary
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr

#22743 Backport of Add more docs for update-primary into release/1.14.x
  website/content/api-docs/system/replication/replication-dr.mdx
  website/content/api-docs/system/replication/replication-performance.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#22745 Revert "Pin security scan's semgrep version to 1.37.0 (#22731)"
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#22746 Update hashicorp/vault-plugin-secrets-gcp to v0.17.0
  changelog/22746.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#22748 Update hashicorp/vault-plugin-secrets-mongodbatlas to v0.10.1
  changelog/22748.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#22567 [VAULT-17827] Rollback manager worker pool
  changelog/22567.txt
  go.mod
  vault/core.go
  vault/rollback.go
  vault/rollback_test.go
  vault/testing.go
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/docs/internals/telemetry/metrics/core-system.mdx
  website/content/partials/telemetry-metrics/vault/rollback/inflight.mdx
  website/content/partials/telemetry-metrics/vault/rollback/queued.mdx
  website/content/partials/telemetry-metrics/vault/rollback/waiting.mdx
Labels: hashicorp-contributed-pr, content-lgtm

#22754 Fix flaky rollback test
  vault/rollback_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22755 Improve transit import command error handling
  command/transit_import_key.go
Labels: bug, pr/no-changelog, pr/no-milestone

#22753 Fix transit panic with invalid PEM
  changelog/22753.txt
  sdk/helper/keysutil/policy.go
Labels: bug, secret/transit, backport/1.14.x, hashicorp-contributed-pr

#22758 Update hashicorp/vault-plugin-auth-cf to v0.15.1
  changelog/22758.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#22756 Backport of Fix transit panic with invalid PEM into release/1.14.x
  changelog/22753.txt
  sdk/helper/keysutil/policy.go
Labels: hashicorp-contributed-pr

#22733 UI: [VAULT-18126] adding style to prevent namespace to overflow on sidebar
  changelog/_22733.txt
  ui/app/styles/components/namespace-picker.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/templates/components/namespace-picker.hbs
Labels: ui, pr/no-changelog, backport/1.14.x, hashicorp-contributed-pr

#22757 Update hashicorp/vault-plugin-secrets-gcpkms to v0.15.1
  changelog/22757.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#22741 Validate seal generation info only if beta flag is enabled
  command/server.go
  command/server_sealgenerationinfo_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22771 Use new sdk and api versions
  go.mod
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22772 update vault auth submodules to api/v1.10.0
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22760 Update go-kms-wrapping to get Azure HTTP/2 workaround (1.12.x)
  changelog/22760.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22768 Update go-kms-wrapping to get Azure HTTP/2 workaround (1.14.x)
  changelog/22760.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22769 Update go-kms-wrapping to get Azure HTTP/2 workaround (1.13.x)
  changelog/22760.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22777 Backport 1.15.x: Manual to rename delete metadata
  ui/lib/kv/addon/components/kv-delete-modal.js
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#22762 [VAULT-19341] convert secrets engines, learn more to ts and fix date bug
  ui/app/components/dashboard/learn-more-card.ts
  ui/app/components/dashboard/secrets-engines-card.ts
  ui/app/templates/components/dashboard/client-count-card.hbs
  ui/app/templates/components/dashboard/replication-card.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22776 UI: [VAULT-19478] Fix info table row value overflow
  ui/app/styles/helper-classes/general.scss
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/info-table-row.js
  ui/lib/kv/addon/components/page/secret/paths.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22782 bump version to rc1
  version/version_base.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22783 bump version to 1.16 beta1
  version/version_base.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22781 Backport 1.15.x: Truncate long paths in info-table-row for kv
  ui/app/styles/helper-classes/general.scss
  ui/lib/core/addon/components/info-table-row.hbs
  ui/lib/core/addon/components/info-table-row.js
  ui/lib/kv/addon/components/page/secret/paths.hbs
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#22780 Backport 1.15.x: Secrets engine + learn more card to ts and updated at bug on dashboard
  ui/app/components/dashboard/learn-more-card.ts
  ui/app/components/dashboard/secrets-engines-card.ts
  ui/app/templates/components/dashboard/client-count-card.hbs
  ui/app/templates/components/dashboard/replication-card.hbs
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#22705 events: Continuously verify policies
  http/events.go
  http/events_test.go
  http/http_test.go
  vault/acl.go
  vault/capabilities.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22785 Backport of events: Continuously verify policies into release/1.15.x
  http/events.go
  http/events_test.go
  http/http_test.go
  vault/acl.go
  vault/capabilities.go
Labels: hashicorp-contributed-pr

#22788 Backport of Add administrative namespace docs into release/1.14.x
  website/content/api-docs/system/audit-hash.mdx
  website/content/api-docs/system/auth.mdx
  website/content/api-docs/system/capabilities-self.mdx
  website/content/api-docs/system/capabilities.mdx
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/control-group.mdx
  website/content/api-docs/system/ha-status.mdx
  website/content/api-docs/system/internal-counters.mdx
  website/content/api-docs/system/internal-specs-openapi.mdx
  website/content/api-docs/system/internal-ui-feature.mdx
  website/content/api-docs/system/internal-ui-mounts.mdx
  website/content/api-docs/system/internal-ui-resultant-acl.mdx
  website/content/api-docs/system/leader.mdx
  website/content/api-docs/system/leases.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/managed-keys.mdx
  website/content/api-docs/system/mfa/index.mdx
  website/content/api-docs/system/monitor.mdx
  website/content/api-docs/system/mounts.mdx
  website/content/api-docs/system/plugins-catalog.mdx
  website/content/api-docs/system/plugins-reload-backend.mdx
  website/content/api-docs/system/policies-password.mdx
  website/content/api-docs/system/policies.mdx
  website/content/api-docs/system/policy.mdx
  website/content/api-docs/system/remount.mdx
  website/content/api-docs/system/seal-status.mdx
  website/content/api-docs/system/tools.mdx
  website/content/api-docs/system/user-lockout.mdx
  website/content/api-docs/system/version-history.mdx
  website/content/api-docs/system/wrapping-lookup.mdx
  website/content/api-docs/system/wrapping-rewrap.mdx
  website/content/api-docs/system/wrapping-unwrap.mdx
  website/content/api-docs/system/wrapping-wrap.mdx
  website/content/docs/enterprise/namespaces.mdx
  website/content/partials/alerts/restricted-admin.mdx
  website/content/partials/alerts/restricted-root.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#22790 Bumped kv plugin
  changelog/22790.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22791 Skip unhealthy seal wrappers when performing encryption or decryption.
  vault/seal/seal.go
  vault/seal/seal_wrapper.go
  vault/seal_autoseal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22795 Update hashicorp/vault-plugin-auth-azure to v0.16.1
  changelog/22795.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22796 Backport of Skip unhealthy seal wrappers when performing encryption or decryption. into release/1.15.x
  vault/seal/seal.go
  vault/seal/seal_wrapper.go
  vault/seal_autoseal.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22797 Update hashicorp/vault-plugin-auth-kerberos to v0.10.1
  changelog/22797.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22799 Update hashicorp/vault-plugin-secrets-azure to v0.16.2
  changelog/22799.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22805 Update hashicorp/vault-plugin-auth-oci to v0.14.2
  changelog/22805.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22813 manual backport 1.14.x
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .release/ci.hcl
  Makefile
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-ui.hcl
  enos/modules/build_local/main.tf
  enos/modules/build_local/scripts/build.sh
  enos/modules/get_local_metadata/main.tf
  enos/modules/get_local_metadata/scripts/version.sh
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
  scripts/ci-helper.sh
  version/VERSION
  version/version_base.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#22811 Manual backport 1.13.x
  .github/workflows/build-vault-oss.yml
  .github/workflows/build.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .release/ci.hcl
  Makefile
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-ui.hcl
  enos/modules/build_local/main.tf
  enos/modules/build_local/scripts/build.sh
  enos/modules/get_local_metadata/main.tf
  enos/modules/get_local_metadata/scripts/version.sh
  enos/modules/vault_verify_version/templates/verify-cluster-version.sh
  scripts/ci-helper.sh
  version/VERSION
  version/version_base.go
Labels: pr/no-milestone

#22804 Backport of Update hashicorp/vault-plugin-auth-kerberos to v0.10.1 into release/1.15.x
  changelog/22797.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr, backport/1.15.x

#22614 UI: HDS adoption replace <CopyButton> part 3
  ui/app/styles/core/buttons.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/templates/components/transit-key-action/datakey.hbs
  ui/app/templates/components/transit-key-action/decrypt.hbs
  ui/app/templates/components/transit-key-action/encrypt.hbs
  ui/app/templates/components/transit-key-action/export.hbs
  ui/app/templates/components/transit-key-action/hmac.hbs
  ui/app/templates/components/transit-key-action/rewrap.hbs
  ui/app/templates/components/transit-key-action/sign.hbs
  ui/tests/integration/components/transit-key-actions-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22824 Update hashicorp/vault-plugin-secrets-azure to v0.16.3
  changelog/22824.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22823 Update hashicorp/vault-plugin-secrets-kubernetes to v0.6.0
  changelog/22823.txt
  go.mod
  go.sum
  vault/seal/seal.go
  website/content/partials/db-secrets-credential-types.mdx
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22821 UI: Show error if tool action is not recognized
  ui/app/routes/vault/cluster/tools/tool.js
  ui/app/templates/vault/cluster/tools/error.hbs
Labels: ui, pr/no-changelog, backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#22822 Update hashicorp/vault-plugin-auth-oci to v0.14.2 (#22805)
  changelog/22805.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22831 Backport of UI: Show error if tool action is not recognized into release/1.15.x
  ui/app/routes/vault/cluster/tools/tool.js
  ui/app/templates/vault/cluster/tools/error.hbs
Labels: ui, backport, hashicorp-contributed-pr

#22445 Add support for IAM Auth for Google CloudSQL DBs
  changelog/22445.txt
  go.mod
  go.sum
  plugins/database/mysql/connection_producer.go
  plugins/database/mysql/mysql_test.go
  plugins/database/postgresql/postgresql_test.go
  sdk/database/dbplugin/v5/testing/test_helpers.go
  sdk/database/helper/connutil/cloudsql.go
  sdk/database/helper/connutil/sql.go
  sdk/go.mod
  sdk/go.sum
Labels: hashicorp-contributed-pr, backport/1.15.x

#22825 Backport of Update hashicorp/vault-plugin-secrets-azure to v0.16.3 into release/1.15.x
  changelog/22824.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22834 Backport of Add support for IAM Auth for Google CloudSQL DBs into release/1.15.x
  changelog/22445.txt
  go.mod
  go.sum
  plugins/database/mysql/connection_producer.go
  plugins/database/mysql/mysql_test.go
  plugins/database/postgresql/postgresql_test.go
  sdk/database/dbplugin/v5/testing/test_helpers.go
  sdk/database/helper/connutil/cloudsql.go
  sdk/database/helper/connutil/sql.go
  sdk/go.mod
  sdk/go.sum
Labels: hashicorp-contributed-pr

#22832 Form Field Tooltip Alignment
  changelog/22832.txt
  ui/app/styles/core/label.scss
Labels: ui, hashicorp-contributed-pr, backport/1.15.x

#22837 Backport of Form Field Tooltip Alignment into release/1.15.x
  changelog/22832.txt
  ui/app/styles/core/label.scss
Labels: ui, hashicorp-contributed-pr

#22827 Backport of Update hashicorp/vault-plugin-secrets-kubernetes to v0.6.0 into release/1.15.x
  changelog/22823.txt
  go.mod
  go.sum
  vault/seal/seal.go
  website/content/partials/db-secrets-credential-types.mdx
Labels: hashicorp-contributed-pr

#22833 Update go-kms-wrapping dependencies for community
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22744 Vault 18538 reference runtime on plugin register
  api/sys_plugins.go
  api/sys_plugins_test.go
  command/plugin_info.go
  command/plugin_register.go
  command/plugin_register_test.go
  sdk/helper/pluginutil/runner.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  vault/plugin_catalog.go
Labels: pr/no-changelog, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#22752 [VAULT-15398] Activity log data generation fixes
  vault/activity_log.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22792 Add administrative namespace docs (#22581)
  website/content/api-docs/system/audit-hash.mdx
  website/content/api-docs/system/auth.mdx
  website/content/api-docs/system/capabilities-self.mdx
  website/content/api-docs/system/capabilities.mdx
  website/content/api-docs/system/config-control-group.mdx
  website/content/api-docs/system/control-group.mdx
  website/content/api-docs/system/ha-status.mdx
  website/content/api-docs/system/internal-counters.mdx
  website/content/api-docs/system/internal-specs-openapi.mdx
  website/content/api-docs/system/internal-ui-feature.mdx
  website/content/api-docs/system/internal-ui-mounts.mdx
  website/content/api-docs/system/internal-ui-resultant-acl.mdx
  website/content/api-docs/system/leader.mdx
  website/content/api-docs/system/leases.mdx
  website/content/api-docs/system/license.mdx
  website/content/api-docs/system/managed-keys.mdx
  website/content/api-docs/system/mfa/index.mdx
  website/content/api-docs/system/monitor.mdx
  website/content/api-docs/system/mounts.mdx
  website/content/api-docs/system/plugins-catalog.mdx
  website/content/api-docs/system/plugins-reload-backend.mdx
  website/content/api-docs/system/policies-password.mdx
  website/content/api-docs/system/policies.mdx
  website/content/api-docs/system/policy.mdx
  website/content/api-docs/system/remount.mdx
  website/content/api-docs/system/seal-status.mdx
  website/content/api-docs/system/tools.mdx
  website/content/api-docs/system/user-lockout.mdx
  website/content/api-docs/system/version-history.mdx
  website/content/api-docs/system/wrapping-lookup.mdx
  website/content/api-docs/system/wrapping-rewrap.mdx
  website/content/api-docs/system/wrapping-unwrap.mdx
  website/content/api-docs/system/wrapping-wrap.mdx
  website/content/docs/enterprise/namespaces.mdx
  website/content/partials/alerts/restricted-admin.mdx
  website/content/partials/alerts/restricted-root.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#22844 LDAP Libraries and Roles Delete Bug
  ui/lib/ldap/addon/components/page/libraries.ts
  ui/lib/ldap/addon/components/page/roles.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22848 Backport of LDAP Libraries and Roles Delete Bug into release/1.15.x
  ui/lib/ldap/addon/components/page/libraries.ts
  ui/lib/ldap/addon/components/page/roles.ts
Labels: ui, hashicorp-contributed-pr

#22843 Backport of Update go-kms-wrapping dependencies for community into release/1.15.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22849 LDAP Disable Name Edit
  ui/app/models/ldap/library.js
  ui/app/models/ldap/role.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
  ui/tests/integration/components/ldap/page/role/create-and-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22851 Backport of LDAP Disable Name Edit into release/1.15.x
  ui/app/models/ldap/library.js
  ui/app/models/ldap/role.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
  ui/tests/integration/components/ldap/page/role/create-and-edit-test.js
Labels: ui, hashicorp-contributed-pr

#22853 LDAP Library Check-in Bug
  ui/lib/ldap/addon/components/accounts-checked-out.ts
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/ldap/addon/components/page/overview.hbs
  ui/tests/integration/components/ldap/accounts-checked-out-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22808 events: remove flaky test
  http/events_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#22854 Update hashicorp/vault-plugin-database-couchbase to v0.9.3
  changelog/22854.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22860 Backport of events: remove flaky test into release/1.15.x
  http/events_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#22815 events: Enable by default, disable flag
  changelog/22815.txt
  command/server.go
  command/server/config.go
  helper/experiments/experiments.go
  http/events_test.go
  http/logical.go
  vault/auth.go
  vault/core.go
  vault/events_test.go
  vault/mount.go
Labels: hashicorp-contributed-pr, backport/1.15.x

#22861 Backport of Update hashicorp/vault-plugin-database-couchbase to v0.9.3 into release/1.15.x
  changelog/22854.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22858 Backport of LDAP Library Check-in Bug into release/1.15.x
  ui/lib/ldap/addon/components/accounts-checked-out.ts
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/ldap/addon/components/page/overview.hbs
  ui/tests/integration/components/ldap/accounts-checked-out-test.js
Labels: ui, hashicorp-contributed-pr

#22856 Update hashicorp/vault-plugin-secrets-ad to v0.16.1
  changelog/22856.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22818 [VAULT-1324] Fix the CLI failing to return wrapping information for KV PUT and PATCH operations when format is set to 'table'
  changelog/22818.txt
  command/kv_patch.go
  command/kv_put.go
Labels: core/cli, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#22867 Backport of [VAULT-1324] Fix the CLI failing to return wrapping information for KV PUT and PATCH operations when format is set to 'table' into release/1.13.x
  changelog/22818.txt
  command/kv_patch.go
  command/kv_put.go
Labels: hashicorp-contributed-pr

#22869 Backport of [VAULT-1324] Fix the CLI failing to return wrapping information for KV PUT and PATCH operations when format is set to 'table' into release/1.15.x
  changelog/22818.txt
  command/kv_patch.go
  command/kv_put.go
Labels: hashicorp-contributed-pr

#22862 Backport of events: Enable by default, disable flag into release/1.15.x
  changelog/22815.txt
  command/server.go
  command/server/config.go
  helper/experiments/experiments.go
  http/events_test.go
  http/logical.go
  vault/auth.go
  vault/core.go
  vault/events_test.go
  vault/mount.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#22868 Backport of [VAULT-1324] Fix the CLI failing to return wrapping information for KV PUT and PATCH operations when format is set to 'table' into release/1.14.x
  changelog/22818.txt
  command/kv_patch.go
  command/kv_put.go
Labels: hashicorp-contributed-pr

#22835 events: WebSocket subscriptions support go-bexpr expressions
  changelog/22835.txt
  command/events.go
  go.mod
  go.sum
  http/events.go
  http/events_test.go
  sdk/logical/events.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/events_test.go
Labels: hashicorp-contributed-pr, backport/1.15.x

#22846 Backport of Vault 18538 reference runtime on plugin register into release/1.15.x
  api/sys_plugins.go
  api/sys_plugins_test.go
  command/plugin_info.go
  command/plugin_register.go
  command/plugin_register_test.go
  sdk/helper/pluginutil/runner.go
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  vault/plugin_catalog.go
Labels: hashicorp-contributed-pr

#22870 LDAP Role Credentials Error Handling
  ui/lib/ldap/addon/components/page/role/credentials.hbs
  ui/lib/ldap/addon/components/page/role/credentials.ts
  ui/lib/ldap/addon/routes/roles/role/credentials.ts
  ui/lib/ldap/addon/templates/roles/role/credentials.hbs
  ui/tests/integration/components/ldap/page/role/credentials-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22866 add oci_image and runtime to VersionedPlugin
  api/sys_plugins.go
  command/plugin_list.go
  sdk/helper/pluginutil/runner.go
  vault/logical_system.go
  vault/plugin_catalog.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22874 Backport of [VAULT-1324] Fix the CLI failing to return wrapping information for KV PUT and PATCH operations when format is set to 'table' into release/1.12.x
  changelog/22818.txt
  command/kv_patch.go
  command/kv_put.go
Labels: hashicorp-contributed-pr

#22842 Fix KV bug on deletion_time
  ui/app/models/kv/data.js
  ui/app/models/kv/metadata.js
  ui/lib/kv/addon/components/kv-version-dropdown.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/lib/kv/addon/utils/kv-deleted.js
  ui/lib/kv/app/utils/kv-deleted.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/integration/components/kv/page/kv-page-version-history-test.js
  ui/tests/unit/adapters/kv/metadata-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22876 Fix auto-squash events experiments
  http/events_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22877 Backport of Fix KV bug on deletion_time into release/1.15.x
  ui/app/models/kv/data.js
  ui/app/models/kv/metadata.js
  ui/lib/kv/addon/components/kv-version-dropdown.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/lib/kv/addon/utils/kv-deleted.js
  ui/lib/kv/app/utils/kv-deleted.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/integration/components/kv/page/kv-page-version-history-test.js
  ui/tests/unit/adapters/kv/metadata-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#22875 Backport of add oci_image and runtime to VersionedPlugin into release/1.15.x
  api/sys_plugins.go
  command/plugin_list.go
  sdk/helper/pluginutil/runner.go
  vault/logical_system.go
  vault/plugin_catalog.go
Labels: hashicorp-contributed-pr

#22863 docs: db schedule-based static role rotations
  website/content/api-docs/secret/databases/index.mdx
  website/content/docs/secrets/databases/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22878 Backport of docs: db schedule-based static role rotations into release/1.15.x
  website/content/api-docs/secret/databases/index.mdx
  website/content/docs/secrets/databases/index.mdx
Labels: hashicorp-contributed-pr

#22850 Make runsc the default plugin container runtime
  .github/workflows/test-go.yml
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/consts/plugin_runtime_types.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  sdk/helper/pluginutil/runner.go
  vault/external_plugin_container_test.go
  vault/external_plugin_test.go
  vault/logical_system.go
  vault/plugin_catalog.go
  vault/plugin_catalog_test.go
Labels: core/plugin, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22871 Update hashicorp/vault-plugin-database-couchbase to v0.9.4
  changelog/22871.txt
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22872 Backport of events: WebSocket subscriptions support go-bexpr expressions into release/1.15.x
  changelog/22835.txt
  command/events.go
  go.mod
  go.sum
  http/events.go
  http/events_test.go
  sdk/logical/events.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/events_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#22873 Backport of LDAP Role Credentials Error Handling into release/1.15.x
  ui/lib/ldap/addon/components/page/role/credentials.hbs
  ui/lib/ldap/addon/components/page/role/credentials.ts
  ui/lib/ldap/addon/routes/roles/role/credentials.ts
  ui/lib/ldap/addon/templates/roles/role/credentials.hbs
  ui/tests/integration/components/ldap/page/role/credentials-test.js
Labels: ui, hashicorp-contributed-pr

#22879 Update hashicorp/vault-plugin-auth-kubernetes to v0.17.1
  changelog/22879.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22881 Disable gVisor in tests (for now)
  .github/workflows/test-go.yml
  vault/external_plugin_container_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#22883 Backport of Update hashicorp/vault-plugin-auth-kubernetes to v0.17.1 into release/1.15.x
  changelog/22879.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22886 Backport of Make runsc the default plugin container runtime into release/1.15.x
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/consts/plugin_runtime_types.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  sdk/helper/pluginutil/runner.go
  vault/external_plugin_container_test.go
  vault/external_plugin_test.go
  vault/logical_system.go
  vault/plugin_catalog.go
  vault/plugin_catalog_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#22852 Reject supplied nonces for non-convergent encryption operations
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_rewrap.go
  changelog/22852.txt
  sdk/helper/keysutil/policy.go
Labels: backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#22892 Add timeout for http events tests
  http/events_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#22896 Add sys/monitor and sys/audit-hash to root only namespace list
  website/content/docs/enterprise/namespaces.mdx
Labels: hashicorp-contributed-pr

#22899 Backport of Reject supplied nonces for non-convergent encryption operations into release/1.15.x
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_rewrap.go
  changelog/22852.txt
  sdk/helper/keysutil/policy.go
Labels: hashicorp-contributed-pr

#22882 LDAP Overview Responsive Layout
  ui/lib/ldap/addon/components/page/overview.hbs
Labels: ui, pr/no-changelog, backport/1.15.x

#22902 Reject supplied nonces for non-convergent encryption operations (#22852)
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_rewrap.go
  changelog/22852.txt
  sdk/helper/keysutil/policy.go
Labels: hashicorp-contributed-pr

#22900 Backport of Reject supplied nonces for non-convergent encryption operations into release/1.14.x
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_rewrap.go
  changelog/22852.txt
  sdk/helper/keysutil/policy.go
Labels: hashicorp-contributed-pr

#22901 Reject supplied nonces for non-convergent encryption operations (#22852)
  builtin/logical/transit/backend_test.go
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_encrypt_test.go
  builtin/logical/transit/path_rewrap.go
  changelog/22852.txt
  sdk/helper/keysutil/policy.go
Labels: hashicorp-contributed-pr

#22820 UI: Namespace validation update
  ui/app/models/namespace.js
  ui/lib/core/addon/components/edit-form.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-save-buttons.hbs
  ui/lib/core/addon/components/form-save-buttons.js
  ui/lib/core/addon/templates/components/edit-form.hbs
Labels: ui, pr/no-changelog, backport/1.12.x, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#22903 Backport of LDAP Overview Responsive Layout into release/1.15.x
  ui/lib/ldap/addon/components/page/overview.hbs
Labels: ui, hashicorp-contributed-pr

#22640 ui: adds a new auth form option
  changelog/_22640.txt
  ui/app/adapters/auth-method.js
  ui/app/adapters/role-saml.js
  ui/app/components/auth-form.js
  ui/app/components/auth-saml.js
  ui/app/components/mount-backend/type-form.js
  ui/app/helpers/mountable-auth-methods.js
  ui/app/helpers/supported-auth-backends.js
  ui/app/models/role-saml.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-saml.hbs
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22905 Typo in seal config doc for pkcs#11
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#22908 Backport of Typo in seal config doc for pkcs#11 into release/1.12.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, hashicorp-contributed-pr

#22909 Backport of Typo in seal config doc for pkcs#11 into release/1.13.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, hashicorp-contributed-pr

#22910 Backport of Typo in seal config doc for pkcs#11 into release/1.14.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, hashicorp-contributed-pr

#22911 Backport of Typo in seal config doc for pkcs#11 into release/1.15.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, hashicorp-contributed-pr

#22906 Backport of ui: adds a new auth form option into release/1.15.x
  changelog/_22640.txt
  ui/app/adapters/auth-method.js
  ui/app/adapters/role-saml.js
  ui/app/components/auth-form.js
  ui/app/components/auth-saml.js
  ui/app/components/mount-backend/type-form.js
  ui/app/helpers/mountable-auth-methods.js
  ui/app/helpers/supported-auth-backends.js
  ui/app/models/role-saml.js
  ui/app/services/auth.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-saml.hbs
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
Labels: hashicorp-contributed-pr

#22828 Backport of UI: Show error if tool action is not recognized into release/1.12.x
  ui/app/routes/vault/cluster/tools/tool.js
  ui/app/templates/vault/cluster/tools/error.hbs
Labels: ui, backport, hashicorp-contributed-pr

#22829 Backport of UI: Show error if tool action is not recognized into release/1.13.x
  ui/app/routes/vault/cluster/tools/tool.js
  ui/app/templates/vault/cluster/tools/error.hbs
Labels: ui, backport, hashicorp-contributed-pr

#22830 Backport of UI: Show error if tool action is not recognized into release/1.14.x
  ui/app/routes/vault/cluster/tools/tool.js
  ui/app/templates/vault/cluster/tools/error.hbs
Labels: ui, backport, hashicorp-contributed-pr

#22907 Update hashicorp/vault-plugin-secrets-terraform to v0.7.3
  changelog/22907.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.15.x

#22749 UI: HDS adoption replace <CopyButton> part 4
  ui/app/components/sidebar/user-menu.hbs
  ui/app/styles/core/buttons.scss
  ui/app/templates/components/configure-ssh-secret.hbs
  ui/app/templates/components/generate-credentials.hbs
  ui/app/templates/components/hover-copy-button.hbs
  ui/app/templates/components/tool-hash.hbs
  ui/app/templates/components/tool-random.hbs
  ui/app/templates/components/tool-rewrap.hbs
  ui/app/templates/components/tool-unwrap.hbs
  ui/app/templates/components/tool-wrap.hbs
  ui/app/templates/components/transform-show-transformation.hbs
  ui/app/templates/components/transit-form-show.hbs
  ui/app/templates/vault/cluster/secrets/backend/sign.hbs
  ui/lib/core/addon/components/code-snippet.hbs
  ui/lib/core/addon/components/copy-secret-dropdown.hbs
  ui/lib/kmip/addon/templates/credentials/show.hbs
  ui/lib/kv/addon/components/page/secret/paths.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/replication/addon/templates/mode/secondaries/add.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#22894 Backport of Add timeout for http events tests into release/1.15.x
  http/events_test.go
Labels: hashicorp-contributed-pr

#22915 Backport of Update hashicorp/vault-plugin-secrets-terraform to v0.7.3 into release/1.15.x
  changelog/22907.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22819 add CLI commands for plugin runtime VAULT-18181
  api/sys_plugins_runtimes.go
  command/commands.go
  command/plugin_register_test.go
  command/plugin_runtime.go
  command/plugin_runtime_deregister.go
  command/plugin_runtime_deregister_test.go
  command/plugin_runtime_info.go
  command/plugin_runtime_info_test.go
  command/plugin_runtime_list.go
  command/plugin_runtime_list_test.go
  command/plugin_runtime_register.go
  command/plugin_runtime_register_test.go
  command/util.go
  vault/logical_system.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22779 Add unit tests for seal backend health check
  vault/logical_system.go
  vault/logical_system_test.go
  vault/seal_autoseal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22914 Avoid Vault hang when no communication established with plugin
  changelog/22914.txt
  helper/testhelpers/pluginhelpers/pluginhelpers.go
  sdk/plugin/grpc_backend_client.go
  vault/plugin_catalog.go
Labels: bug, core/plugin, hashicorp-contributed-pr, backport/1.15.x

#22919 Backport of add CLI commands for plugin runtime VAULT-18181 into release/1.15.x
  api/sys_plugins_runtimes.go
  command/commands.go
  command/plugin_register_test.go
  command/plugin_runtime.go
  command/plugin_runtime_deregister.go
  command/plugin_runtime_deregister_test.go
  command/plugin_runtime_info.go
  command/plugin_runtime_info_test.go
  command/plugin_runtime_list.go
  command/plugin_runtime_list_test.go
  command/plugin_runtime_register.go
  command/plugin_runtime_register_test.go
  command/util.go
  vault/logical_system.go
Labels: hashicorp-contributed-pr

#22857 docs/k8s-auth: non-JWT tokens are now allowed for token_reviewer_jwt
  website/content/api-docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22921 Backport of Add unit tests for seal backend health check into release/1.15.x
  vault/logical_system.go
  vault/logical_system_test.go
  vault/seal_autoseal.go
Labels: hashicorp-contributed-pr

#22924 Backport of docs/k8s-auth: non-JWT tokens are now allowed for token_reviewer_jwt into release/1.15.x
  website/content/api-docs/auth/kubernetes.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#22920 Backport of events: Avoid data race by checking for root token into release/1.15.x
  http/events.go
Labels: hashicorp-contributed-pr

#22922 Backport of Avoid Vault hang when no communication established with plugin into release/1.15.x
  changelog/22914.txt
  helper/testhelpers/pluginhelpers/pluginhelpers.go
  sdk/plugin/grpc_backend_client.go
  vault/plugin_catalog.go
Labels: hashicorp-contributed-pr

#22917 Code Snippet Updates
  ui/app/styles/components/code-snippet.scss
  ui/app/styles/core.scss
  ui/lib/core/addon/components/code-snippet.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/tests/integration/components/ldap/page/library/details/accounts-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22880 Backport of Update hashicorp/vault-plugin-database-couchbase to v0.9.4 into release/1.15.x
  changelog/22871.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22923 Backport of plugins: adding vault and plugin metadata labels to plugin containers into release/1.15.x
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  sdk/helper/pluginutil/runner.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#22913 Safer check in http/events validateSubscribeAccessLoop
  http/events.go
  http/events_test.go
  vault/request_handling.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#22865 Backport of Update hashicorp/vault-plugin-secrets-ad to v0.16.1 into release/1.15.x
  changelog/22856.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#22887 UI: Small styling fix when viewing KMIP credentials
  ui/lib/kmip/addon/templates/credentials/show.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x
