Repository hashicorp/vault, pull requests merged in 2023-02, with the labels that each got.

#18928 Vault test cluster helper refactorings, mostly audit related
  builtin/logical/ssh/backend_test.go
  command/auth_tune_test.go
  command/plugin_deregister_test.go
  command/plugin_info_test.go
  command/plugin_register_test.go
  command/plugin_reload_test.go
  command/secrets_tune_test.go
  helper/testhelpers/corehelpers/corehelpers.go
  helper/testhelpers/logical/testing.go
  http/logical_test.go
  http/sys_auth_test.go
  http/sys_generate_root_test.go
  http/sys_metrics_test.go
  http/sys_mount_test.go
  vault/audit_test.go
  vault/auth_test.go
  vault/cluster_test.go
  vault/core_test.go
  vault/external_plugin_test.go
  vault/external_tests/identity/login_mfa_totp_test.go
  vault/external_tests/metrics/core_metrics_int_test.go
  vault/external_tests/raft/raft_test.go
  vault/logical_system_integ_test.go
  vault/logical_system_test.go
  vault/mount_test.go
  vault/testing.go
Labels: pr/no-changelog

#18933 Refactor an ENT test helper back to OSS to wait for updated CRLs within PKI tests
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/test_helpers.go
Labels: pr/no-changelog

#18871 check for nil references
  vault/login_mfa.go
Labels: pr/no-changelog

#18939 Allow cleanup ssh dynamic keys host keys
  builtin/logical/ssh/backend.go
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_cleanup_dynamic_host_keys.go
  changelog/18939.txt
  website/content/api-docs/secret/ssh.mdx
Labels: enhancement, secret/ssh

#18833 docs for named login MFA
  website/content/api-docs/secret/identity/mfa/duo.mdx
  website/content/api-docs/secret/identity/mfa/okta.mdx
  website/content/api-docs/secret/identity/mfa/pingid.mdx
  website/content/api-docs/secret/identity/mfa/totp.mdx
  website/content/api-docs/system/mfa/validate.mdx
  website/content/docs/auth/login-mfa/index.mdx
Labels: pr/no-changelog, pr/no-milestone

#18938 Apply URL encoding/unencoding to OCSP Get requests
  builtin/logical/pki/path_ocsp.go
  builtin/logical/pki/path_ocsp_test.go
  changelog/18938.txt
Labels: bug, secret/pki, backport/1.12.x

#18937 secrets/azure: changes permission recommendation to be minimally permissive
  website/content/api-docs/secret/azure.mdx
  website/content/docs/secrets/azure.mdx
Labels: docs, secret/azure, pr/no-changelog, backport/1.12.x, pr/no-milestone

#18944 add ClusterName to meta GetClusterStatusResponse
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/meta/meta.proto
Labels: pr/no-changelog

#18945 Fix race accessing b.crls within cert auth
  builtin/credential/cert/backend.go
  builtin/credential/cert/path_crls.go
  builtin/credential/cert/path_crls_test.go
  builtin/credential/cert/path_login.go
  changelog/18945.txt
Labels: bug, auth/cert, backport/1.12.x

#18950 Add ClusteName to GetClusterStatus response
  go.mod
  go.sum
  vault/hcp_link/capabilities/meta/meta.go
  vault/hcp_link/internal/wrapped_hcpLink.go
Labels: pr/no-changelog

#18954 UI: VAULT-13044 pki cleanup attributes
  ui/app/models/pki/action.js
  ui/app/models/pki/issuer.js
  ui/app/models/pki/role.js
  ui/app/models/pki/urls.js
  ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
Labels: ui, pr/no-changelog

#18955 openapi: Ensure mount_path parameters are marked as required
  vault/logical_system.go
Labels: pr/no-changelog

#18965 Fix docLinks in models
  ui/app/models/database/connection.js
  ui/app/models/oidc/provider.js
  ui/app/models/pki/role.js
Labels: ui, pr/no-changelog

#18964 VAULT-7254 beta pki modal bugfix
  ui/lib/core/addon/components/secret-list-header.js
Labels: ui, pr/no-changelog

#18518 [QT-304] Add enos ui scenario
  .github/workflows/test-enos-scenario-ui.yml
  enos/README.md
  enos/enos-modules.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-variables.hcl
  enos/modules/vault_test_ui/main.tf
  enos/modules/vault_test_ui/outputs.tf
  enos/modules/vault_test_ui/scripts/test_ui.sh
  enos/modules/vault_test_ui/variables.tf
  ui/scripts/enos-test-ember.js
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#18967 Revert has-bottom-margin-m on form-field
  ui/lib/core/addon/components/form-field.hbs
Labels: ui, pr/no-changelog

#18984 Use UTC for leaf exceeding CA's notAfter
  builtin/logical/pki/cert_util.go
  changelog/18984.txt
Labels: bug, secret/pki

#18978 make fmt
  vault/cluster/inmem_layer.go
Labels: pr/no-changelog

#18983 docs: Change default value for ha_enabled to false
  website/content/docs/configuration/storage/mysql.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18980 OpenAPI attributes not populating on pki/role model
  ui/lib/pki/addon/routes/application.js
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/routes/roles/role/details.js
  ui/lib/pki/addon/routes/roles/role/edit.js
Labels: ui, pr/no-changelog

#18956 docs allow_forwarding_via_token syntax update
  website/content/docs/faq/ssct.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone

#18990 UI: VAULT-13136 Update textfile to use native ember Textarea
  ui/lib/core/addon/components/text-file.hbs
Labels: ui, pr/no-changelog

#18979 Add docs on cross cluster tidy operations
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog

#18953 Add support for missing attributes in PKI UI
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/issuer.js
  ui/app/utils/parse-pki-cert-oids.js
  ui/app/utils/parse-pki-cert.js
  ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
  ui/lib/pki/addon/components/pki-issuer-cross-sign.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/values.js
  ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
  ui/tests/integration/utils/parse-pki-cert-test.js
Labels: ui, secret/pki, pr/no-changelog

#18989 Use the unified CRL on local CRL paths if UnifiedCRLOnExistingPaths is set
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_ocsp.go
  builtin/logical/pki/test_helpers.go
Labels: secret/pki, pr/no-changelog

#18986 Add notes on cross cluster CRLs
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog

#18987 Add docs on cross-cluster listing endpoints
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog

#18968 UI: add issuerRef getter in case issuer is nameless
  ui/app/adapters/pki/action.js
  ui/app/models/pki/issuer.js
  ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
  ui/lib/pki/addon/components/pki-issuer-cross-sign.js
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/issuers/issuer/cross-sign.hbs
  ui/tests/unit/serializers/pki/action-test.js
  ui/types/vault/models/pki/issuer.d.ts
Labels: ui, pr/no-changelog

#18988 docs: Remove XKS proxy TLS setup note
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#18834 Add events sending routed from plugins
  sdk/framework/backend.go
  sdk/logical/event.proto
  sdk/logical/logical.go
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_events.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/backend_grpc.pb.go
  vault/auth.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/events_test.go
  vault/mount.go
  vault/testing.go
Labels: pr/no-changelog

#18970 Document Cross-Cluster CRLs/OCSP for Vault Enterprise
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog

#18997 Backport of docs: Remove XKS proxy TLS setup note into release/1.12.x
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
Labels: pr/no-milestone

#18952 test/plugin: refactor compilePlugin for reuse
  helper/testhelpers/pluginhelpers/pluginhelpers.go
  vault/external_plugin_test.go
  vault/testing.go
Labels: pr/no-changelog, pr/no-milestone

#18998 PKI cleanup hardcoded mount path value
  ui/lib/pki/addon/components/page/pki-role-details.ts
  ui/lib/pki/addon/components/pki-role-form.js
  ui/lib/pki/addon/routes/certificates/certificate/details.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/routes/error.js
  ui/lib/pki/addon/routes/issuers/generate-root.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/issuers/issuer/index.js
  ui/lib/pki/addon/routes/issuers/issuer/sign.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/role/details.js
  ui/lib/pki/addon/routes/roles/role/edit.js
  ui/lib/pki/addon/routes/roles/role/generate.js
  ui/lib/pki/addon/routes/roles/role/sign.js
Labels: ui, pr/no-changelog

#18999 fix: upgrade vault-plugin-database-couchbase to v0.9.0
  go.mod
  go.sum
Labels: pr/no-changelog

#18994 Transit Managed Keys Documentation
  website/content/api-docs/secret/transit.mdx
  website/content/api-docs/system/managed-keys.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: docs, pr/no-changelog

#18818 VAULT-8436 remove <-time.After statements in for loops
  api/lifetime_watcher.go
  builtin/credential/okta/backend.go
  builtin/credential/okta/cli.go
  command/agent/sink/sink.go
  command/server.go
  physical/zookeeper/zookeeper.go
  tools/semgrep/ci/loop-time-after.yml
  vault/ha.go
  vault/login_mfa.go
  vault/raft.go
Labels: pr/no-changelog

#19004 VAULT-13192 only validate form on submit instead of onChange
  ui/lib/pki/addon/components/pki-generate-root.hbs
Labels: ui, pr/no-changelog

#18681 update annotation docs for agent telemetry stanza
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone

#19003 [QT-304] Ensure Chrome is only installed for vault-enterprise UI Test workflows
  .github/workflows/test-enos-scenario-ui.yml
  enos/enos-scenario-ui.hcl
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#19011 Add a stronger warning about the usage of recovery keys
  vault/gentle_storage.go
  website/content/api-docs/system/init.mdx
  website/content/docs/concepts/seal.mdx
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x

#19010 docs/vault-k8s: 1.2.0 release updates
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/index.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#19016 Remove accidental addition of a hackweek file
  vault/gentle_storage.go
Labels: pr/no-changelog

#19012 fix: upgrade vault-plugin-secrets-mongodbatlas to v0.9.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19006 Backport of update annotation docs for agent telemetry stanza into release/1.12.x
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: website, pr/no-changelog, pr/no-milestone

#19024 Add a note that multi-cluster ENT setups can avoid this risk
  website/content/docs/concepts/seal.mdx
Labels: pr/no-changelog

#19026 docs: update learn links to point to developer locations
  website/content/docs/agent/autoauth/methods/aws.mdx
  website/content/docs/agent/autoauth/methods/kubernetes.mdx
  website/content/docs/agent/caching/index.mdx
  website/content/docs/auth/approle.mdx
  website/content/docs/auth/kerberos.mdx
  website/content/docs/concepts/dev-server.mdx
  website/content/docs/concepts/integrated-storage/index.mdx
  website/content/docs/concepts/password-policies.mdx
  website/content/docs/concepts/policies.mdx
  website/content/docs/concepts/resource-quotas.mdx
  website/content/docs/configuration/entropy-augmentation.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/azurekeyvault.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/configuration/seal/transit.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/lease-count-quotas.mdx
  website/content/docs/enterprise/namespaces.mdx
  website/content/docs/enterprise/replication.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/install.mdx
  website/content/docs/platform/aws/run.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/examples/external.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/index.mdx
  website/content/docs/plugins/plugin-development.mdx
  website/content/docs/secrets/ad.mdx
  website/content/docs/secrets/azure.mdx
  website/content/docs/secrets/cubbyhole.mdx
  website/content/docs/secrets/databases/mysql-maria.mdx
  website/content/docs/secrets/kmip.mdx
  website/content/docs/secrets/kv/kv-v1.mdx
  website/content/docs/secrets/kv/kv-v2.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
  website/content/docs/secrets/pki/quick-start-root-ca.mdx
  website/content/docs/secrets/pki/rotation-primitives.mdx
  website/content/docs/secrets/pki/setup.mdx
  website/content/docs/secrets/ssh/one-time-ssh-passwords.mdx
  website/content/docs/secrets/transform/index.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: docs, pr/no-changelog, backport/1.12.x, pr/no-milestone

#18971 VAULT-13169 Require go docs for all new test functions
  .github/workflows/godoc-test-checker.yml
  .gitignore
  Makefile
  go.mod
  go.sum
  tools/godoctests/main.go
  tools/godoctests/pkg/analyzer/analyzer.go
  tools/godoctests/pkg/analyzer/analyzer_test.go
  tools/godoctests/pkg/analyzer/testdata/funcs.go
  tools/tools.go
Labels: pr/no-changelog, pr/no-milestone

#18541 Small typo in Internals > Integrated Storage Doc
  website/content/docs/internals/integrated-storage.mdx
Labels: docs, pr/no-changelog

#18985 fix: upgrade vault-plugin-database-snowflake to v0.7.0
  go.mod
  go.sum
Labels: pr/no-changelog

#18993 Add updateRecord to role adapter
  ui/app/adapters/pki/role.js
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/unit/adapters/pki/role-test.js
Labels: ui, pr/no-changelog

#19031 Document pki cross cluster behavior
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, secret/pki, pr/no-changelog

#19038 Remove duplicate adapter methods
  ui/app/adapters/pki/role.js
  ui/types/vault/adapters/pki/role.d.ts
Labels: ui, pr/no-changelog

#19034 Upversion sdk for 1.10.11
  sdk/version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#19033 Add suggested root rotation procedure
  website/content/docs/secrets/pki/rotation-primitives.mdx
Labels: docs, secret/pki, pr/no-changelog, backport/1.12.x

#19027 Update vault.core.locked_users telemetry documentation
  website/content/docs/configuration/user-lockout.mdx
  website/content/docs/internals/telemetry.mdx
Labels: pr/no-changelog

#19042 Update SDK version base for 1.12.4
  sdk/version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#19041 Update sdk version base for release/1.11.x
  sdk/version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#19022 UI: add error-handling and validation to pki cross-signing
  ui/lib/core/addon/components/object-list-input.hbs
  ui/lib/core/addon/components/object-list-input.js
  ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
  ui/lib/pki/addon/components/pki-issuer-cross-sign.js
Labels: ui, pr/no-changelog

#19046 Fix documentation on CRL fixed version
  website/content/docs/secrets/pki/considerations.mdx
Labels: docs, bug, secret/pki, pr/no-changelog

#19045 SDK Go mod update for 1.11.x
  go.mod
Labels: pr/no-changelog, pr/no-milestone

#19047 SDK Go mod update for 1.12.x
  go.mod
Labels: pr/no-changelog, pr/no-milestone

#19049 upgrade vault-plugin-auth-gcp to v0.15.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19036 Wrapped token login bug
  changelog/19036.txt
  ui/app/mixins/cluster-route.js
  ui/tests/acceptance/wrapped-token-test.js
Labels: ui, bug, backport/1.10.x, backport/1.11.x, backport/1.12.x

#19050 upgrade vault-plugin-database-elasticsearch to v0.13.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19051 Backport of Wrapped token login bug into release/1.10.x
  changelog/19036.txt
  ui/app/mixins/cluster-route.js
  ui/tests/acceptance/wrapped-token-test.js
Labels: ui, backport

#19053 Backport of Wrapped token login bug into release/1.12.x
  changelog/19036.txt
  ui/app/mixins/cluster-route.js
  ui/tests/acceptance/wrapped-token-test.js
Labels: ui, bug

#19060 fix: upgrade vault-plugin-auth-kerberos to v0.9.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19062 Changelog entry fix
  changelog/17893.txt
Labels: pr/no-changelog

#19059 Update terraform secrets plugin version
  go.mod
  go.sum
Labels: pr/no-changelog

#11620 improve cleanup docs
  website/content/docs/internals/integrated-storage.mdx
Labels: docs, pr/no-changelog

#19066 Document OCSP GET known issue
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#19037 Revert URL encoding OCSP GET fix #18938
  builtin/logical/pki/path_ocsp.go
  builtin/logical/pki/path_ocsp_test.go
Labels: bug, secret/pki, backport/1.12.x

#19035 UI: VAULT-13128 Add inline error to generate cert form
  ui/app/models/pki/certificate/generate.js
  ui/lib/pki/addon/components/pki-role-generate.hbs
  ui/lib/pki/addon/components/pki-role-generate.ts
  ui/tests/helpers/pki/pki-role-generate.js
  ui/tests/integration/components/pki-role-generate-test.js
  ui/types/vault/models/pki/certificate/generate.d.ts
Labels: ui, pr/no-changelog

#19058 UI: PKI Clean up dirty model on leave
  ui/app/models/pki/issuer.js
  ui/lib/core/addon/decorators/confirm-leave.js
  ui/lib/pki/addon/components/page/pki-key-details.ts
  ui/lib/pki/addon/components/page/pki-role-details.ts
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-configure-form.ts
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-key-form.hbs
  ui/lib/pki/addon/components/pki-key-form.js
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/components/pki-role-form.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/routes/issuers/generate-intermediate.js
  ui/lib/pki/addon/routes/issuers/generate-root.js
  ui/lib/pki/addon/routes/issuers/issuer/edit.js
  ui/lib/pki/addon/routes/issuers/issuer/sign.js
  ui/lib/pki/addon/routes/keys/key/details.js
  ui/lib/pki/addon/routes/keys/key/edit.js
  ui/lib/pki/addon/routes/roles/role/generate.js
  ui/lib/pki/addon/routes/roles/role/sign.js
  ui/lib/pki/addon/templates/configuration/create.hbs
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/tests/acceptance/pki-engine-route-cleanup-test.js-test.js
  ui/tests/helpers/pki/workflow.js
  ui/tests/integration/components/pki-configure-form-test.js
  ui/tests/integration/components/pki/pki-key-form-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog

#19054 UI: VAULT-13135 Add copyable issuer id row to issuer details
  ui/app/models/pki/issuer.js
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
Labels: ui, pr/no-changelog

#19072 Backend mount success message copy fix
  ui/app/components/mount-backend-form.js
  ui/tests/integration/components/mount-backend-form-test.js
Labels: ui, pr/no-changelog

#19071 UI: Fix OIDC login in fullscreen
  changelog/19071.txt
  ui/app/components/auth-jwt.js
  ui/tests/unit/components/auth-jwt-test.js
Labels: ui, bug, backport/1.10.x, backport/1.11.x, backport/1.12.x

#19078 UI: clarify beta configuration info banner
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/templates/configuration/index.hbs
Labels: ui, pr/no-changelog

#19083 Add Vault log level support
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/k8s/enos-scenario-k8s.hcl
  enos/k8s/enos-variables-k8s.hcl
  enos/modules/k8s_deploy_vault/main.tf
  enos/modules/k8s_deploy_vault/variables.tf
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#19088 fix: upgrade vault-plugin-auth-oci to v0.13.0
  go.mod
  go.sum
Labels: pr/no-changelog

#18780 Azure Auth - rotate-root documentation
  website/content/api-docs/auth/azure.mdx
  website/content/docs/auth/azure.mdx
Labels: pr/no-changelog

#19085 [QT-481] Move env var declaration to called workflow
  .github/workflows/test-acc-dockeronly-nightly.yml
  .github/workflows/test-run-acc-tests-for-path.yml
Labels: pr/no-changelog, pr/no-milestone

#19097 Kubernetes config form validation
  ui/app/models/kubernetes/config.js
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/lib/kubernetes/addon/components/page/configure.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
Labels: ui, pr/no-changelog

#19104 Stop using title capitalization for vault pki synoposis
  command/pki_health_check.go
  command/pki_issue_intermediate.go
  command/pki_list_intermediate_command.go
  command/pki_verify_sign_command.go
Labels: secret/pki, pr/no-changelog

#19102 update diagnose command to no longer require docker dependency
  command/operator_diagnose.go
Labels: dependencies, core/diagnose, pr/no-changelog

#19095 UI: VAULT-13419 Remove flash message for form errors and use MessageError instead
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.hbs
  ui/lib/kubernetes/addon/components/page/role/create-and-edit.js
  ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
Labels: ui, bug, pr/no-changelog

#19081 Backport of UI: Fix OIDC login in fullscreen into release/1.12.x
  changelog/19071.txt
  ui/app/components/auth-jwt.js
  ui/tests/unit/components/auth-jwt-test.js
Labels: ui, backport

#19080 Backport of UI: Fix OIDC login in fullscreen into release/1.11.x
  changelog/19071.txt
  ui/app/components/auth-jwt.js
  ui/tests/unit/components/auth-jwt-test.js
Labels: ui, backport

#17894 Add default to allowed values for algorithm_signer
  builtin/logical/ssh/path_roles.go
  changelog/17894.txt
  ui/app/models/role-ssh.js
Labels: enhancement

#19101 Update specific wrappers to v2.0.7
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog

#19105 Glimmerize alert-banner
  ui/app/templates/components/license-banners.hbs
  ui/app/templates/components/raft-join.hbs
  ui/lib/core/addon/components/alert-banner.hbs
  ui/lib/core/addon/components/alert-banner.js
  ui/lib/core/addon/helpers/message-types.js
  ui/lib/core/addon/templates/components/alert-banner.hbs
  ui/lib/core/addon/templates/components/replication-dashboard.hbs
  ui/lib/pki/addon/components/pki-issuer-cross-sign.hbs
  ui/tests/integration/components/alert-inline-test.js
Labels: ui, pr/no-changelog

#19108 upgrade vault-plugin-secrets-openldap to v0.10.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19107 fix: upgrade vault-plugin-auth-centrify to v0.14.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19110 Quick Fix
  ui/lib/core/addon/helpers/message-types.js
Labels: ui, pr/no-changelog

#18966 Make experiments API authenticated
  vault/logical_system.go
  vault/policy_store.go
  vault/policy_store_test.go
Labels: pr/no-changelog

#19057 events: Add websockets and command
  command/commands.go
  command/events.go
  command/events_test.go
  go.mod
  go.sum
  http/events.go
  http/events_test.go
  http/handler.go
  sdk/logical/event.pb.go
  sdk/logical/event.proto
  sdk/logical/response.go
  vault/core.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/events_test.go
Labels: pr/no-changelog

#19112 upgrade vault-plugin-database-redis to v0.2.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19113 Kubernetes host form field description change
  ui/app/models/kubernetes/config.js
Labels: ui, pr/no-changelog

#19094 fix: upgrade vault-plugin-auth-kubernetes to v0.15.0
  changelog/19094.txt
  go.mod
  go.sum
Labels: pr/no-changelog

#19084 fix: upgrade vault-plugin-secrets-kubernetes to v0.3.0
  changelog/19084.txt
  go.mod
  go.sum
Labels: pr/no-changelog

#19086 replace existing zookeeper import with an actively maintained one
  go.mod
  go.sum
  physical/zookeeper/zookeeper.go
  physical/zookeeper/zookeeper_test.go
Labels: pr/no-changelog

#19118 upgrade vault-plugin-secrets-alicloud to v0.14.0
  go.mod
  go.sum
Labels: pr/no-changelog

#19128 upgrade vault-plugin-secrets-alicloud to v0.14.1
  go.mod
  go.sum
Labels: pr/no-changelog

#19123 Kubernetes config validation update
  ui/app/models/kubernetes/config.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
Labels: ui, pr/no-changelog

#19114 UI: display CSR after generation
  ui/app/models/pki/action.js
  ui/lib/pki/addon/components/page/pki-key-details.hbs
  ui/lib/pki/addon/components/pki-configure-form.hbs
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-sign-intermediate-form.hbs
  ui/lib/pki/addon/templates/issuers/generate-intermediate.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/pki-configure-form.js
  ui/tests/integration/components/pki/pki-configure-form-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-generate-root-test.js
  ui/tests/integration/components/pki/pki-role-generate-test.js
  ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
Labels: ui, pr/no-changelog

#19121 UI/vault 13506/pki attr cleanup
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/certificate/generate.js
  ui/app/serializers/pki/role.js
  ui/lib/pki/addon/components/page/pki-role-details.hbs
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.js
  ui/lib/pki/addon/components/pki-key-usage.ts
  ui/lib/pki/addon/components/pki-role-generate.hbs
  ui/tests/integration/components/pki/page/pki-role-details-test.js
Labels: ui, pr/no-changelog

#19130 Convert events metadata type to google.protobuf.Struct
  sdk/logical/event.pb.go
  sdk/logical/event.proto
Labels: pr/no-changelog, backport/1.13.x

#19134 events: Allow subscribing to events in namespaces
  http/events.go
  http/handler.go
  http/logical.go
Labels: pr/no-changelog, backport/1.13.x

#19135 UI: Fix cancel button on role transform form
  changelog/19135.txt
  ui/app/templates/components/transform-role-edit.hbs
Labels: ui, bug, backport/1.10.x, backport/1.11.x, backport/1.12.x

#19138 events: Check token and ACLs on request
  http/events.go
  http/events_test.go
  http/logical.go
  vault/request_handling.go
Labels: pr/no-changelog, backport/1.13.x

#19122 Update PKI Secret Engine doc for auto-tidy
  website/content/api-docs/secret/pki.mdx
Labels: docs, secret/pki, pr/no-changelog

#19142 Backport of UI: Fix cancel button on role transform form into release/1.11.x
  changelog/19135.txt
  ui/app/templates/components/transform-role-edit.hbs
Labels: ui, backport, bug

#18186 Telemetry Metrics Configuration.
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  builtin/logical/pki/storage.go
  changelog/18186.txt
Labels: backport/1.12.x

#19139 UI: sets operationNone for a kmip role if no checkboxes are selected
  changelog/19139.txt
  ui/app/models/kmip/role.js
  ui/lib/kmip/addon/components/edit-form-kmip-role.js
  ui/tests/integration/components/edit-form-kmip-role-test.js
Labels: ui, bug, backport/1.10.x, backport/1.11.x, backport/1.12.x

#19145 Bump kv plugin v0.14.0->v0.14.2
  changelog/19145.txt
  go.mod
  go.sum
Labels: secret/kv, ecosystem/plugin, backport/1.13.x

#19153 upgrade vault-plugin-database-mongodbatlas to v0.9.0
  go.mod
  go.sum
Labels: pr/no-changelog, backport/1.13.x

#19140 Update test dependencies
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog, backport/1.13.x

#19146 Backport of UI: Fix cancel button on role transform form into release/1.10.x
  changelog/19135.txt
  ui/app/templates/components/transform-role-edit.hbs
Labels: ui, backport, bug

#19163 Update version to 1.14.0 and version prerelease to beta1
  version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#19164 Update version prerelease to rc1
  version/version_base.go
Labels: pr/no-changelog, pr/no-milestone

#18840 Update namespace.FromContext comment
  helper/namespace/namespace.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19119 docs/vault-helm: fix multi-line block copy
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
Labels: pr/no-changelog, backport/1.9.x, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#19171 Reduce memory usage within PKI testing in CI
  builtin/logical/pki/path_tidy_test.go
Labels: pr/no-changelog, pr/no-milestone

#19165 Trap errors related to vault pki list-intermediate issuer reading
  command/healthcheck/pki.go
  command/healthcheck/pki_allow_if_modified_since.go
  command/healthcheck/pki_audit_visibility.go
  command/healthcheck/shared.go
  command/pki_issue_intermediate.go
  command/pki_list_intermediate.go
  command/pki_reissue_intermediate.go
  command/pki_verify_sign.go
Labels: pr/no-changelog, backport/1.13.x

#17919 LifeTimeWatcher SleepDuration calculation testing
  api/lifetime_watcher.go
  api/renewer_test.go
  changelog/17919.txt
Labels: agent

#19070 Add cryptosec as codeowners to relevant docs
  CODEOWNERS
Labels: pr/no-changelog

#19116 Disabling License Banners
  changelog/19116.txt
  ui/app/components/license-banners.js
  ui/app/lib/local-storage.js
  ui/app/templates/components/license-banners.hbs
  ui/tests/integration/components/license-banners-test.js
  ui/tests/unit/lib/local-storage-test.js
Labels: ui

#19132 Fetch replication status in its own resource
  enos/modules/vault_verify_performance_replication/main.tf
  enos/modules/vault_verify_performance_replication/scripts/get-replication-status.sh
  enos/modules/vault_verify_performance_replication/scripts/verify-performance-replication.sh
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone

#19109 docs/plugins: update upgrading plugins
  website/content/docs/upgrading/plugins.mdx
Labels: pr/no-changelog, backport/1.12.x

#19184 Kubernetes config payload fix
  ui/app/adapters/kubernetes/role.js
  ui/app/serializers/kubernetes/config.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
Labels: ui, pr/no-changelog, backport/1.13.x

#18996 Update raftautosnapshots.mdx
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#19075 docs: remove content/docs/plugins/plugin-portal
  website/content/docs/plugins/plugin-portal.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone

#19196 Add PKI unified-revocation feture changelog
  changelog/19196.txt
Labels: backport/1.13.x

#19188 Refactor approle response validation tests
  builtin/credential/approle/path_login_test.go
  builtin/credential/approle/path_role_test.go
  builtin/credential/approle/path_tidy_user_id_test.go
Labels: pr/no-changelog

#19200 secrets/gcp: use feature format for changelog entry of impersonated accounts
  changelog/19018.txt
Labels: pr/no-changelog, backport/1.13.x

#19199 Allow listing health checks without mount path
  command/pki_health_check.go
Labels: bug, pr/no-changelog, backport/1.13.x

#19185 events: Remove subscriptions on timeout and cancel
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: pr/no-changelog, backport/1.13.x

#19043 Validate response schema for integration tests
  changelog/19043.txt
  sdk/helper/testhelpers/schema/response_validation.go
  vault/core.go
  vault/request_handling.go
  vault/testing.go
Labels: devex

#19201 fix TestBackendAcc_LoginWithCallerIdentity
  builtin/credential/aws/backend_test.go
Labels: pr/no-changelog

#18479 PKI Response Structures Part 2
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_manage_keys_test.go
Labels: pr/no-changelog

#19208 Remove incorrect information about being able to set environment vari…
  website/content/docs/agent/index.mdx
Labels: docs, pr/no-changelog, backport/1.13.x

#19212 Backport of Remove incorrect information about being able to set environment vari… into release/1.13.x
  website/content/docs/agent/index.mdx
Labels: docs

#19213 Use MaxInt vs. MaxInt64 to prevent overflow on 32bit architectures
  api/renewer_test.go
Labels: pr/no-changelog, backport/1.13.x

#19216 UI/add allowed response headers secret mount
  changelog/19216.txt
  ui/app/models/mount-config.js
  ui/app/models/secret-engine.js
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/lib/core/addon/helpers/options-for-backend.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/unit/models/secret-engine-test.js
Labels: ui, backport/1.13.x

#19219 Update go-kms-wrapping and it's gcpc wrapper to pick up google-cloud-go migration
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog

#19205 Support event subscriptions with glob wildcards
  http/events.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/events_test.go
Labels: pr/no-changelog

#19190 Show generate creds for static-roles when you have read permissions
  changelog/19190.txt
  ui/app/templates/components/database-role-edit.hbs
Labels: ui, bug, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19226 Adds test coverage for PR 19190
  ui/tests/integration/components/database-role-edit-test.js
Labels: ui, pr/no-changelog

#19221 Update changelog 1.13.0-rc1
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone
