Repository hashicorp/vault, pull requests merged in 2023-04, with the labels that each got.

#19912 Backport of Add DataDog test visibility to the test-go job into release/1.11.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#19910 Backport of Add DataDog test visibility to the test-go job into release/1.12.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#19911 Backport of Add DataDog test visibility to the test-go job into release/1.13.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#19868 Extend expiration of diagnose test-fixture ecdsa certificate
  vault/diagnose/test-fixtures/ecdsa.crt
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19938 Backport of Extend expiration of diagnose test-fixture ecdsa certificate into release/1.11.x
  vault/diagnose/test-fixtures/ecdsa.crt
Labels: pr/no-changelog, pr/no-milestone

#19930 Core files continued
  ui/app/styles/components/list-pagination.scss
  ui/app/styles/core.scss
  ui/app/styles/core/bulma-classes.css
  ui/app/styles/core/checkbox-and-radio.scss
  ui/app/styles/core/container.scss
  ui/app/styles/core/control.scss
  ui/app/styles/core/field.scss
  ui/app/styles/core/label.scss
  ui/app/styles/core/lists.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/helper-classes/layout.scss
  ui/app/styles/helper-classes/other.scss
  ui/app/templates/vault/cluster/access/mfa/index.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/app/templates/vault/cluster/access/oidc.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/lib/core/addon/components/list-pagination.js
  ui/lib/pki/addon/components/pki-key-usage.hbs
Labels: ui, pr/no-changelog

#19939 Backport of Extend expiration of diagnose test-fixture ecdsa certificate into release/1.12.x
  vault/diagnose/test-fixtures/ecdsa.crt
Labels: pr/no-changelog, pr/no-milestone

#19940 Backport of Extend expiration of diagnose test-fixture ecdsa certificate into release/1.13.x
  vault/diagnose/test-fixtures/ecdsa.crt
Labels: pr/no-changelog, pr/no-milestone

#19941 Update TestDebugCommand_NoConnection to work when run in an environment with working Vault
  command/debug_test.go
Labels: pr/no-changelog, pr/no-milestone

#19472 VAULT-14048: raft-autopilot appears to refuse to remove a node which has left and wouldn't impact stability
  changelog/19472.txt
  go.mod
  go.sum
  helper/testhelpers/testhelpers_oss.go
  physical/raft/raft_autopilot.go
  vault/external_tests/raft/raft_autopilot_test.go
  vault/raft.go
Labels: bug, core

#19792 Add dependabot Configuration
  .github/dependabot.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19937 Backport Clear Client Address
  command/debug_test.go
Labels: pr/no-changelog, pr/no-milestone

#19604 Update api dr/secondary/disable documentation
  website/content/api-docs/system/replication/replication-dr.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19963 Re-add custom flash service so engines can extend cluster's template
  ui/app/app.js
  ui/app/services/flash-messages.ts
  ui/lib/kmip/package.json
  ui/lib/kubernetes/addon/engine.js
  ui/lib/kubernetes/package.json
  ui/lib/open-api-explorer/package.json
  ui/lib/pki/addon/components/page/pki-certificate-details.ts
  ui/lib/pki/addon/components/page/pki-configure-create.ts
  ui/lib/pki/addon/components/page/pki-issuer-edit.ts
  ui/lib/pki/addon/components/page/pki-key-details.ts
  ui/lib/pki/addon/components/page/pki-role-details.ts
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.ts
  ui/lib/pki/addon/components/pki-import-pem-bundle.ts
  ui/lib/pki/addon/components/pki-role-generate.ts
  ui/lib/pki/addon/components/pki-sign-intermediate-form.ts
  ui/lib/pki/package.json
  ui/lib/replication/package.json
Labels: ui, pr/no-changelog

#19948 Ensure tests-completed job fails if required jobs before it do
  .github/workflows/ci.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19953 Add acme account storage
  builtin/logical/pki/acme_jws.go
  builtin/logical/pki/acme_state.go
  builtin/logical/pki/path_acme_directory.go
  builtin/logical/pki/path_acme_new_account.go
  builtin/logical/pki/path_acme_nonce.go
Labels: enhancement, secret/pki, pr/no-changelog

#19840 UI: VAULT-13341 add toggle and select to pki role-form
  ui/lib/core/addon/components/search-select-placeholder.hbs
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/lib/pki/addon/components/pki-role-form.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/role/edit.js
  ui/lib/pki/addon/templates/roles/create.hbs
  ui/lib/pki/addon/templates/roles/role/edit.hbs
  ui/tests/acceptance/pki/pki-engine-route-cleanup-test.js
  ui/tests/helpers/pki/pki-role-form.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog

#19951 Consolidating our size variables with Bulma's
  ui/app/styles/components/action-block.scss
  ui/app/styles/components/calendar-widget.scss
  ui/app/styles/components/confirm.scss
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/info-table-row.scss
  ui/app/styles/components/list-item-row.scss
  ui/app/styles/components/list-pagination.scss
  ui/app/styles/components/page-header.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/components/sidebar.scss
  ui/app/styles/components/ui-wizard.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/core/field.scss
  ui/app/styles/core/file.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/label.scss
  ui/app/styles/core/layout.scss
  ui/app/styles/core/level.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/progress.scss
  ui/app/styles/core/select.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/core/toggle.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/styles/helper-classes/layout.scss
  ui/app/styles/helper-classes/other.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/styles/utils/_size_variables.scss
  ui/app/templates/components/selectable-card.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/core/addon/templates/components/shamir-modal-flow.hbs
  ui/lib/pki/addon/components/page/pki-role-details.hbs
Labels: ui, pr/no-changelog

#19901 Address Critical Vulnerabilities from Dependencies
  .github/workflows/ci.yml
  changelog/19901.txt
  scripts/cross/Dockerfile
  scripts/docker/Dockerfile.ui
  ui/.github/workflows/ci.yml
  ui/package.json
  ui/yarn.lock
Labels: ui

#19913 Model Validation Warnings
  changelog/19913.txt
  ui/app/components/mount-backend-form.js
  ui/app/decorators/model-validations.js
  ui/app/models/auth-method.js
  ui/app/models/secret-engine.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/unit/decorators/model-validations-test.js
Labels: ui

#19926 docs/vault-k8s: example using pkiCert and writeToFile
  website/content/docs/platform/k8s/injector/examples.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#19933 VAULT-14733: Refactor processClientRecord in activity log
  vault/activity_log.go
  vault/activity_log_test.go
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19976 Moved 'WaitForNodesExcludingSelectedStandbys' to shared testhelpers file
  .github/workflows/build-vault-oss.yml
  helper/testhelpers/testhelpers.go
  helper/testhelpers/testhelpers_oss.go
  ui/.nvmrc
Labels: pr/no-changelog, pr/no-milestone

#19971 ui: fix empty tooltip rendering when no creation time
  ui/app/templates/components/secret-form-show.hbs
  ui/tests/acceptance/secrets/backend/cubbyhole/secret-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
Labels: ui, pr/no-changelog

#19978 Node Version CI Update
  .github/workflows/build-vault-oss.yml
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
  ui/.nvmrc
  ui/package.json
Labels: pr/no-changelog

#19928 OCI auth doc clean up
  website/content/docs/auth/oci.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19983 Fix OpenAPI-related tests
  sdk/framework/testdata/legacy.json
  sdk/framework/testdata/operations.json
  sdk/framework/testdata/responses.json
Labels: pr/no-changelog, pr/no-milestone

#19985 Updated the example config with api_addr parameter
  website/content/docs/configuration/index.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19986 Fix an issue tripping the actionlint linter in test-run-enos-scenario-matrix.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#19988 Backport of Fix an issue tripping the actionlint linter in test-run-enos-scenario-matrix.yml into release/1.12.x
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#19989 Backport of Fix an issue tripping the actionlint linter in test-run-enos-scenario-matrix.yml into release/1.13.x
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#19979 Add workflow_dispatch Trigger to ci.yml Workflow
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#19987 Backport of Fix an issue tripping the actionlint linter in test-run-enos-scenario-matrix.yml into release/1.11.x
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#19982 Ui: adds test for model passed to rotate-root route
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.ts
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/helpers/pki/pki-configure-create.js
  ui/tests/helpers/pki/values.js
Labels: ui, pr/no-changelog

#19981 Update create.mdx
  website/content/docs/commands/token/create.mdx
Labels: pr/no-changelog, backport/1.12.x, pr/no-milestone

#19799 UI: Namespace area fixes
  changelog/19799.txt
  ui/app/adapters/namespace.js
  ui/app/components/namespace-link.js
  ui/app/models/namespace.js
  ui/app/serializers/namespace.js
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
Labels: ui, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19980 Add extra ssct gen counter debug logs
  vault/token_store_util_common.go
Labels: pr/no-changelog, backport/1.10.x, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19977 [QT-488] Get artifact summary info along with product metadata
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#19756 UI: VAULT-9408 Delete all issuers toolbar action + modal
  ui/app/adapters/pki/issuer.js
  ui/app/models/pki/issuer.js
  ui/app/styles/core/helpers.scss
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/lib/pki/addon/components/page/pki-configuration-details.ts
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
  ui/tests/acceptance/pki/configuration-test.js
  ui/tests/helpers/pki/pki-configure-create.js
  ui/tests/helpers/pki/pki-delete-all-issuers.js
  ui/tests/helpers/pki/pki-generate-root.js
  ui/tests/helpers/pki/workflow.js
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/adapters/pki/issuer.d.ts
Labels: ui, pr/no-changelog

#20000 Update Create Role heading to Create/Update Role
  website/content/api-docs/secret/ssh.mdx
Labels: backport/1.13.x

#19363 openapi: Add display attributes for approle
  builtin/credential/approle/backend.go
  builtin/credential/approle/path_login.go
  builtin/credential/approle/path_role.go
  builtin/credential/approle/path_tidy_user_id.go
Labels: pr/no-changelog

#19422 openapi: Add display attributes for PKI plugin
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_config_ca.go
  builtin/logical/pki/path_config_cluster.go
  builtin/logical/pki/path_config_crl.go
  builtin/logical/pki/path_config_urls.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_fetch_keys.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_manage_keys.go
  builtin/logical/pki/path_ocsp.go
  builtin/logical/pki/path_resign_crls.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_sign_issuers.go
  builtin/logical/pki/path_tidy.go
Labels: pr/no-changelog

#19399 openapi: Add display attributes for token/
  vault/token_store.go
Labels: pr/no-changelog

#19970 Finish size var clean up
  ui/app/styles/components/masked-input.scss
  ui/app/styles/components/sidebar.scss
  ui/app/styles/core.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/element-styling.scss
  ui/app/styles/core/label.scss
  ui/app/styles/core/message.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/styles/utils/_font_family_variables.scss
  ui/app/styles/utils/_size_variables.scss
Labels: ui, pr/no-changelog

#20027 Remove HomeLink Component
  ui/app/adapters/secret-engine.js
  ui/app/components/home-link.js
  ui/app/templates/components/home-link.hbs
  ui/app/templates/components/not-found.hbs
  ui/app/templates/vault/cluster/access/loading.hbs
  ui/app/templates/vault/cluster/secrets/backend/error.hbs
Labels: ui, pr/no-changelog

#20030 Backport of Fix issues tripping the actionlint linter again into release/1.12.x
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#20029 Backport of Fix issues tripping the actionlint linter again into release/1.13.x
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#20028 Backport of Fix issues tripping the actionlint linter again into release/1.11.x
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone

#20022 UI: Namespace area fixes (#19799)
  changelog/19799.txt
  ui/app/adapters/namespace.js
  ui/app/components/namespace-link.js
  ui/app/serializers/namespace.js
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
Labels: ui, backport

#20031 Update Color Vars (remove bulma color vars and overrides)
  ui/app/styles/components/auth-buttons.scss
  ui/app/styles/components/auth-form.scss
  ui/app/styles/components/box-label.scss
  ui/app/styles/components/calendar-widget.scss
  ui/app/styles/components/codemirror.scss
  ui/app/styles/components/confirm.scss
  ui/app/styles/components/control-group.scss
  ui/app/styles/components/doc-link.scss
  ui/app/styles/components/env-banner.scss
  ui/app/styles/components/list-pagination.scss
  ui/app/styles/components/modal.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/components/search-select.scss
  ui/app/styles/components/selectable-card.scss
  ui/app/styles/components/shamir-progress.scss
  ui/app/styles/components/tabs.scss
  ui/app/styles/components/ui-wizard.scss
  ui/app/styles/core.scss
  ui/app/styles/core/box.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/core/field.scss
  ui/app/styles/core/file.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/label.scss
  ui/app/styles/core/lists.scss
  ui/app/styles/core/menu.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/progress.scss
  ui/app/styles/helper-classes/colors.scss
  ui/app/styles/utils/_box-shadow_variables.scss
  ui/app/styles/utils/_bulma_variables.scss
  ui/app/styles/utils/_color_variables.scss
  ui/app/styles/utils/_font_variables.scss
  ui/app/styles/utils/mixins.scss
  ui/app/templates/components/mfa/mfa-setup-step-two.hbs
  ui/app/templates/components/secret-delete-menu.hbs
  ui/lib/kubernetes/addon/components/page/configure.hbs
  ui/tests/integration/components/kubernetes/page/configure-test.js
Labels: ui, pr/no-changelog

#20033 Sidebar Animation Glitch Fixes
  ui/app/components/sidebar/nav/access.hbs
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/policies.hbs
  ui/app/routes/vault/cluster.js
  ui/app/routes/vault/cluster/clients.js
  ui/app/templates/vault/cluster.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/loading.hbs
  ui/tests/integration/components/sidebar/nav/access-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/components/sidebar/nav/policies-test.js
Labels: ui, pr/no-changelog

#20032 API docs: update Transit restore payload example
  website/content/api-docs/secret/transit.mdx
Labels: docs, backport/1.12.x, backport/1.13.x

#20023 UI: Namespace area fixes (#19799)
  changelog/19799.txt
  ui/app/adapters/namespace.js
  ui/app/components/namespace-link.js
  ui/app/serializers/namespace.js
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
Labels: ui, backport

#20035 Small fixes post var and core file work
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/columns.scss
  ui/app/styles/core/control.scss
  ui/app/styles/core/field.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/label.scss
  ui/app/styles/core/layout.scss
  ui/app/styles/core/menu.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/select.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
Labels: ui, pr/no-changelog

#19932 update index.mdx with correct installation doc ref
  website/content/docs/platform/k8s/vso/index.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#20020 Replace defaultVaultAuthMethod with defaultAuthMethod in Snippet
  website/content/docs/platform/k8s/vso/helm.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19383 openapi: Add display attributes for cert auth
  builtin/credential/cert/backend.go
  builtin/credential/cert/path_certs.go
  builtin/credential/cert/path_config.go
  builtin/credential/cert/path_crls.go
  builtin/credential/cert/path_login.go
Labels: pr/no-changelog

#19392 openapi: Add display attributes for Radius auth
  builtin/credential/radius/backend.go
  builtin/credential/radius/path_config.go
  builtin/credential/radius/path_login.go
  builtin/credential/radius/path_users.go
Labels: pr/no-changelog

#19389 openapi: Add display attributes for LDAP auth
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/path_config.go
  builtin/credential/ldap/path_groups.go
  builtin/credential/ldap/path_login.go
  builtin/credential/ldap/path_users.go
Labels: pr/no-changelog

#19415 openapi: Add display attributes for Nomad plugin
  builtin/logical/nomad/backend.go
  builtin/logical/nomad/path_config_access.go
  builtin/logical/nomad/path_config_lease.go
  builtin/logical/nomad/path_creds_create.go
  builtin/logical/nomad/path_roles.go
Labels: pr/no-changelog

#20024 UI: Namespace area fixes (#19799)
  changelog/19799.txt
  ui/app/adapters/namespace.js
  ui/app/components/namespace-link.js
  ui/app/serializers/namespace.js
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
Labels: ui, backport

#19384 openapi: Add display attributes for GitHub auth
  builtin/credential/github/backend.go
  builtin/credential/github/path_config.go
  builtin/credential/github/path_login.go
Labels: pr/no-changelog

#20011 add upgrade documentation around STS lease_duration issue
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x

#20047 Backport of add upgrade documentation around STS lease_duration issue into release/1.13.x
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#20050 Use vault/sdk v0.9.0
  go.mod
Labels: pr/no-changelog, pr/no-milestone

#20049 Update docs for Helm 0.24.0 release
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19791 UI: Mount PKI options + allowed_managed_keys
  changelog/19791.txt
  ui/app/components/mount-backend-form.js
  ui/app/decorators/model-expanded-attributes.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/mount-config.js
  ui/app/models/secret-engine.js
  ui/app/templates/vault/cluster/secrets/backend/configuration.hbs
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/pages/secrets/backend/configuration.js
  ui/tests/unit/models/secret-engine-test.js
Labels: ui

#20052 Backport of Update docs for Helm 0.24.0 release into release/1.13.x
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-milestone

#20041 Only log stopping rollback manager once
  vault/rollback.go
Labels: bug, test, pr/no-changelog, backport/1.13.x

#19544 openapi: Add display attributes for TOTP plugin
  builtin/logical/totp/backend.go
  builtin/logical/totp/path_code.go
  builtin/logical/totp/path_keys.go
Labels: pr/no-changelog

#20065 Remove bulma switch
  ui/app/styles/core.scss
  ui/app/styles/core/switch.scss
  ui/app/styles/utils/_bulma_switch.css
Labels: ui, pr/no-changelog

#19543 openapi: Add display attributes for SSH plugin
  builtin/logical/ssh/backend.go
  builtin/logical/ssh/path_cleanup_dynamic_host_keys.go
  builtin/logical/ssh/path_config_ca.go
  builtin/logical/ssh/path_config_zeroaddress.go
  builtin/logical/ssh/path_creds_create.go
  builtin/logical/ssh/path_fetch.go
  builtin/logical/ssh/path_issue.go
  builtin/logical/ssh/path_lookup.go
  builtin/logical/ssh/path_roles.go
  builtin/logical/ssh/path_sign.go
  builtin/logical/ssh/path_verify.go
Labels: pr/no-changelog

#19540 openapi: Add display attributes for RabbitMQ plugin
  builtin/logical/rabbitmq/backend.go
  builtin/logical/rabbitmq/path_config_connection.go
  builtin/logical/rabbitmq/path_config_lease.go
  builtin/logical/rabbitmq/path_role_create.go
  builtin/logical/rabbitmq/path_roles.go
Labels: pr/no-changelog

#19575 openapi: Add display attributes for transit plugin
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_backup.go
  builtin/logical/transit/path_cache_config.go
  builtin/logical/transit/path_config_keys.go
  builtin/logical/transit/path_datakey.go
  builtin/logical/transit/path_decrypt.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_export.go
  builtin/logical/transit/path_hash.go
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_import.go
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_keys_config.go
  builtin/logical/transit/path_random.go
  builtin/logical/transit/path_restore.go
  builtin/logical/transit/path_rewrap.go
  builtin/logical/transit/path_rotate.go
  builtin/logical/transit/path_sign_verify.go
  builtin/logical/transit/path_trim.go
  builtin/logical/transit/path_wrapping_key.go
Labels: pr/no-changelog

#19414 openapi: Add display attributes for database plugin
  builtin/logical/database/backend.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_creds_create.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_rotate_credentials.go
Labels: pr/no-changelog

#20061 [Backport] Update create.mdx (#19981)
  website/content/docs/commands/token/create.mdx
Labels: docs

#20068 Updated the example config with api_addr parameter (#19985)
  website/content/docs/configuration/index.mdx
Labels: docs

#20070 UI: Fix remaining DocLink paths
  changelog/20070.txt
  ui/app/templates/components/keymgmt/distribute.hbs
  ui/app/templates/components/mfa/mfa-login-enforcement-header.hbs
  ui/app/templates/components/oidc/scope-form.hbs
  ui/app/templates/components/pki/config-pki-ca.hbs
  ui/app/templates/components/secret-form-show.hbs
  ui/app/templates/vault.hbs
  ui/app/templates/vault/cluster/access/method/section.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/app/templates/vault/cluster/access/oidc/assignments/index.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs
  ui/app/templates/vault/cluster/secrets/backend/edit-metadata.hbs
  ui/lib/core/addon/components/doc-link.js
  ui/lib/open-api-explorer/addon/templates/components/swagger-ui.hbs
  ui/lib/replication/addon/templates/mode/secondaries/index.hbs
Labels: ui, backport/1.13.x

#20057 Log, don't err, on unified delta WAL write failure
  builtin/logical/pki/crl_util.go
  changelog/20057.txt
Labels: bug, secret/pki, backport/1.13.x

#19973 secrets/openldap: add creds/ endpoint to API docs
  website/content/api-docs/secret/ldap.mdx
Labels: docs, pr/no-changelog

#20048 Support namespaces in test helpers
  helper/testhelpers/testhelpers.go
Labels: test, pr/no-changelog, backport/1.13.x

#20059 Make config load consistent with config write
  builtin/logical/pki/storage.go
Labels: bug, secret/pki, pr/no-changelog

#20076 Fix list formatting
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#20069 Use absolute path for debug datadir
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#20080 Remove dead licensing code and extra core setup
  vault/testing.go
  vault/testing_util.go
Labels: pr/no-changelog, pr/no-milestone

#20064 UI: fix browser console formatting
  changelog/20064.txt
  ui/.template-lintrc.js
  ui/app/templates/components/console/log-command.hbs
  ui/app/templates/components/console/log-help.hbs
  ui/app/templates/components/console/log-list.hbs
  ui/tests/integration/components/console/log-command-test.js
Labels: ui, bug

#20058 Fix building unified delta WAL, unified delta CRLs
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/periodic.go
  changelog/20058.txt
Labels: bug, secret/pki, backport/1.13.x

#20094 UI/add prettier ignore for ui console file
  ui/.template-lintrc.js
  ui/app/templates/components/console/log-help.hbs
Labels: ui

#20100 Fix RFC3339 comment typo
  sdk/framework/field_type.go
Labels: pr/no-changelog

#20056 [Docs] Update the KV v2 API docs
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#19990 UI: Show parsed certificate data in PKI
  ui/app/models/pki/action.js
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/issuer.js
  ui/app/models/pki/key.js
  ui/app/serializers/pki/action.js
  ui/app/serializers/pki/certificate/base.js
  ui/app/serializers/pki/issuer.js
  ui/app/utils/parse-pki-cert-oids.js
  ui/lib/core/addon/templates/components/masked-input.hbs
  ui/lib/pki/addon/components/page/pki-certificate-details.hbs
  ui/lib/pki/addon/components/page/pki-issuer-details.hbs
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.hbs
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.ts
  ui/lib/pki/addon/components/parsed-certificate-info-rows.hbs
  ui/lib/pki/addon/components/parsed-certificate-info-rows.js
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-csr.ts
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-generate-root.ts
  ui/lib/pki/addon/components/pki-generate-toggle-groups.hbs
  ui/lib/pki/addon/components/pki-generate-toggle-groups.ts
  ui/lib/pki/addon/components/pki-import-pem-bundle.hbs
  ui/lib/pki/addon/components/pki-import-pem-bundle.ts
  ui/lib/pki/addon/components/pki-sign-intermediate-form.hbs
  ui/lib/pki/addon/components/pki-sign-intermediate-form.ts
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/integration/components/pki/page/pki-certificate-details-test.js
  ui/tests/integration/components/pki/page/pki-issuer-rotate-root-test.js
  ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
  ui/tests/unit/adapters/pki/action-test.js
  ui/types/vault/app-types.ts
  ui/types/vault/models/pki/issuer.d.ts
  ui/types/vault/utils/parse-pki-cert.d.ts
Labels: ui, pr/no-changelog

#20110 Use a UUID for ACME kid instead of a key fingerprint
  builtin/logical/pki/acme_jws.go
  builtin/logical/pki/acme_state.go
  builtin/logical/pki/path_acme_new_account.go
Labels: secret/pki, pr/no-changelog

#20107 [Backport] Fix list formatting (#20076)
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: docs

#20108 [Backport] Fix list formatting (#20076)
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: docs

#20019 VAULT-14734: activity log write endpoint
  Makefile
  changelog/20019.txt
  vault/activity/generation/generate_data.pb.go
  vault/activity/generation/generate_data.proto
  vault/logical_system_activity.go
  vault/logical_system_activity_write.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x

#20066 Bulma removal: starting the clean up process
  ui/app/components/modal-form/policy-template.hbs
  ui/app/styles/components/icon.scss
  ui/app/styles/components/modal.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/components/tabs.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/checkbox-and-radio.scss
  ui/app/styles/core/file.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/message.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/switch.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/templates/components/file-to-array-buffer.hbs
  ui/lib/core/addon/components/modal.hbs
  ui/lib/core/addon/components/text-file.hbs
Labels: ui, pr/no-changelog

#20113 Add ACME authorizations & challenges
  builtin/logical/pki/acme_authorizations.go
  builtin/logical/pki/acme_jws.go
  builtin/logical/pki/acme_state.go
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_acme_authorizations.go
  builtin/logical/pki/path_acme_challenges.go
Labels: enhancement, secret/pki, pr/no-changelog

#20098 Backport 1.12.x: UI/fix browser console formatting
  changelog/20064.txt
  ui/app/templates/components/console/log-command.hbs
  ui/app/templates/components/console/log-help.hbs
  ui/app/templates/components/console/log-list.hbs
  ui/tests/integration/components/console/log-command-test.js
Labels: ui, backport

#20097 Backport 1.11.x: UI/fix browser console formatting
  changelog/20064.txt
  ui/app/templates/components/console/log-command.hbs
  ui/app/templates/components/console/log-help.hbs
  ui/app/templates/components/console/log-list.hbs
  ui/tests/integration/components/console/log-command-test.js
Labels: ui, backport

#20118 Backport of Require activity log retention months at least the minimum into release/1.13.x
  changelog/20078.txt
  vault/logical_system_activity.go
Labels: pr/no-changelog, pr/no-milestone

#20099 Update docs to include specifics and caveats around Transit Managed Keys support.
  website/content/api-docs/secret/transit.mdx
  website/content/api-docs/system/managed-keys.mdx
  website/content/docs/enterprise/managed-keys.mdx
Labels: docs, pr/no-changelog, backport/1.13.x

#20009 Simplify tracking of external plugins
  builtin/plugin/backend.go
  sdk/logical/logical.go
  sdk/plugin/plugin.go
  sdk/plugin/plugin_v5.go
  vault/auth.go
  vault/mount.go
  vault/plugin_reload.go
Labels: pr/no-changelog

#20102 [Backport] Update the HTTP verb for consistency (#20056)
  website/content/api-docs/secret/kv/kv-v2.mdx
Labels: docs

#20088 Backport of UI: fix browser console formatting into release/1.13.x
  changelog/20064.txt
  ui/app/templates/components/console/log-command.hbs
  ui/app/templates/components/console/log-help.hbs
  ui/app/templates/components/console/log-list.hbs
  ui/tests/integration/components/console/log-command-test.js
Labels: ui, backport, bug

#19758 openapi: Add display attributes for identity/oidc
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
Labels: pr/no-changelog

#19760 openapi: Add display attributes for identity/entity
  vault/identity_store_aliases.go
  vault/identity_store_entities.go
Labels: pr/no-changelog

#19762 openapi: Add display attributes for identity/group
  vault/identity_store_group_aliases.go
  vault/identity_store_groups.go
Labels: pr/no-changelog

#19763 openapi: Add display attributes for identity/ (remaining)
  vault/identity_lookup.go
  vault/identity_store_upgrade.go
Labels: pr/no-changelog

#20114 Potentially Malicious Link
  changelog/20114.txt
  website/content/docs/enterprise/namespaces.mdx
Labels: docs, pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#20075 Backport of secrets/openldap: add creds/ endpoint to API docs into release/1.13.x
  website/content/api-docs/secret/ldap.mdx
Labels: docs

#20126 Delete unnecessary changelog from #20114
  changelog/20114.txt
Labels: pr/no-changelog

#20129 Add additional clarity around autopilot upgrade versions
  website/content/docs/enterprise/automated-upgrades.mdx
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#20115 chore: remove check-legacy-links-format workflow
  .github/workflows/check-legacy-links-format.yml
Labels: pr/no-changelog, pr/no-milestone

#20142 Revert "Backport of VAULT-13191: OSS changes into release/1.13.x"
  changelog/19891.txt
  command/server/config_test_helpers.go
  command/server/config_test_helpers_util.go
  vault/activity_log.go
  vault/core.go
  vault/logical_system_activity.go
  vault/testing.go
Labels: pr/no-changelog

#20145 Revert "Backport of Add no-op CensusAgent into release/1.13.x"
  vault/activity_log.go
  vault/activity_log_util.go
  vault/census.go
  vault/core.go
  vault/testing.go
Labels: pr/no-changelog

#19391 openapi: Add display attributes for Okta auth
  builtin/credential/okta/backend.go
  builtin/credential/okta/path_config.go
  builtin/credential/okta/path_groups.go
  builtin/credential/okta/path_login.go
  builtin/credential/okta/path_users.go
Labels: pr/no-changelog

#19411 openapi: Add display attributes for userpass
  builtin/credential/userpass/backend.go
  builtin/credential/userpass/path_login.go
  builtin/credential/userpass/path_user_password.go
  builtin/credential/userpass/path_user_policies.go
  builtin/credential/userpass/path_users.go
Labels: pr/no-changelog

#19707 openapi: Add display attributes for /sys (p2)
  vault/logical_raw.go
  vault/logical_system_activity.go
  vault/logical_system_helpers.go
  vault/logical_system_pprof.go
  vault/logical_system_quotas.go
  vault/login_mfa.go
Labels: pr/no-changelog

#20144 sdk/ldaputil: add connection_timeout configurable
  builtin/credential/ldap/backend_test.go
  changelog/20144.txt
  sdk/helper/ldaputil/client.go
  sdk/helper/ldaputil/config.go
  sdk/helper/ldaputil/config_test.go
  website/content/api-docs/auth/ldap.mdx
  website/content/api-docs/secret/ad.mdx
  website/content/api-docs/secret/ldap.mdx
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x

#20149 Stop running UI tests on every PR into a release branch in CI
  .github/workflows/ci.yml
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#18064 Add documentation for cert auth OCSP checking
  website/content/api-docs/auth/cert.mdx
  website/content/docs/auth/cert.mdx
Labels: docs, auth/cert, pr/no-changelog, backport/1.13.x

#20154 Add missing cert auth ocsp read data
  builtin/credential/cert/backend_test.go
  builtin/credential/cert/path_certs.go
  builtin/credential/cert/path_login_test.go
  changelog/20154.txt
Labels: bug, auth/cert, backport/1.13.x

#20037 [QT-525] enos: use spot instances for Vault targets
  .github/enos-run-matrices/build-github-oss-linux-amd64-zip.json
  .github/enos-run-matrices/build-github-oss-linux-arm64-zip.json
  .github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-amd64-zip.json
  .github/enos-run-matrices/enos_release_testing_oss-artifactory-oss-linux-arm64-zip.json
  .gitignore
  enos/ci/service-user-iam/main.tf
  enos/ci/service-user-iam/service-quotas.tf
  enos/enos-modules.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/target_ec2_instances/main.tf
  enos/modules/target_ec2_instances/outputs.tf
  enos/modules/target_ec2_instances/variables.tf
  enos/modules/target_ec2_spot_fleet/main.tf
  enos/modules/target_ec2_spot_fleet/outputs.tf
  enos/modules/target_ec2_spot_fleet/variables.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_cluster/outputs.tf
  enos/modules/vault_cluster/templates/install-packages.sh
  enos/modules/vault_cluster/templates/vault-write-license.sh
  enos/modules/vault_cluster/variables.tf
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x

#20034 Revert changes to STS leases but keep the ttl field
  builtin/logical/aws/secret_access_keys.go
  changelog/20034.txt
Labels: bug, secret/aws, backport/1.13.x

#20153 Backport of Stop running UI tests on every PR into a release branch in CI into release/1.13.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone

#20125 Clients config updates for census reporting
  changelog/20125.txt
  ui/app/components/clients/config.js
  ui/app/decorators/model-validations.js
  ui/app/models/clients/config.js
  ui/app/templates/components/clients/config.hbs
  ui/app/templates/components/clients/dashboard.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/config.hbs
  ui/tests/integration/components/clients/config-test.js
Labels: ui

#20162 openapi: Better comments for OperationPrefix/Verb/Suffix
  sdk/framework/path.go
Labels: pr/no-changelog

#20044 add max_entry_size to sanitized config output
  changelog/20044.txt
  command/server/config.go
  http/sys_config_state_test.go
Labels: backport/1.11.x, backport/1.12.x, backport/1.13.x

#20127 Implement ACME order API
  builtin/logical/pki/acme_authorizations.go
  builtin/logical/pki/acme_state.go
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_acme_authorizations.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
Labels: secret/pki, pr/no-changelog

#20164 UI: VAULT-15385 VAULT-15386 VAULT-15487 Hide create role button, show mount configuration when pki not configured, update overview page so it's responsive
  ui/app/styles/components/selectable-card-container.scss
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
  ui/tests/acceptance/pki/pki-configuration-test.js
  ui/tests/helpers/pki/pki-configure-create.js
  ui/tests/integration/components/pki/page/pki-configuration-details-test.js
Labels: ui, pr/no-changelog

#20178 Backport of Revert changes to STS leases but keep the ttl field into release/1.13.x
  builtin/logical/aws/secret_access_keys.go
  changelog/20034.txt
Labels: secret/aws

#20174 Move all ACME wrappers into a dedicated go file
  builtin/logical/pki/acme_authorizations.go
  builtin/logical/pki/acme_errors.go
  builtin/logical/pki/acme_jws.go
  builtin/logical/pki/acme_state.go
  builtin/logical/pki/acme_state_test.go
  builtin/logical/pki/acme_wrappers.go
  builtin/logical/pki/path_acme_authorizations.go
  builtin/logical/pki/path_acme_challenges.go
  builtin/logical/pki/path_acme_directory.go
  builtin/logical/pki/path_acme_new_account.go
  builtin/logical/pki/path_acme_nonce.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
Labels: secret/pki, pr/no-changelog

#20180 Add a helper function to build PKI ACME API patterns
  builtin/logical/pki/acme_wrappers.go
  builtin/logical/pki/backend.go
  builtin/logical/pki/path_acme_authorizations.go
  builtin/logical/pki/path_acme_challenges.go
  builtin/logical/pki/path_acme_directory.go
  builtin/logical/pki/path_acme_new_account.go
  builtin/logical/pki/path_acme_nonce.go
  builtin/logical/pki/path_acme_order.go
Labels: secret/pki, pr/no-changelog

#20119 Bulma clean up cont.
  ui/app/styles/app.scss
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/modal.scss
  ui/app/styles/components/sidebar.scss
  ui/app/styles/components/toolbar.scss
  ui/app/styles/components/ui-wizard.scss
  ui/app/styles/components/vlt-table.scss
  ui/app/styles/core.scss
  ui/app/styles/core/columns.scss
  ui/app/styles/core/containers.scss
  ui/app/styles/core/field.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/layout.scss
  ui/app/styles/core/link.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/select.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/core/title.scss
  ui/app/styles/helper-classes/colors.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/styles/helper-classes/layout.scss
  ui/app/styles/helper-classes/other.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_size_variables.scss
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/lib/core/addon/components/modal.hbs
  ui/lib/core/addon/templates/components/shamir-flow.hbs
  ui/lib/kubernetes/addon/components/page/configuration.hbs
  ui/lib/kubernetes/addon/components/page/configure.hbs
Labels: ui, pr/no-changelog

#20183 Move console panel to bottom
  ui/app/components/sidebar/frame.hbs
  ui/app/styles/components/console-ui-panel.scss
  ui/app/templates/components/console/log-command.hbs
  ui/app/templates/components/console/ui-panel.hbs
Labels: ui, pr/no-changelog

#20181 Add fix for Go x/crypto/ocsp failure case
  changelog/20181.txt
  sdk/helper/ocsp/client.go
  sdk/helper/ocsp/ocsp_test.go
Labels: bug, auth/cert, backport/1.13.x

#20179 UI: PKI routes extend base Route
  ui/lib/pki/addon/routes/application.js
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/issuers/generate-intermediate.js
  ui/lib/pki/addon/routes/issuers/import.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/issuers/issuer.js
  ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js
  ui/lib/pki/addon/routes/issuers/issuer/details.js
  ui/lib/pki/addon/routes/issuers/issuer/edit.js
  ui/lib/pki/addon/routes/issuers/issuer/rotate-root.js
  ui/lib/pki/addon/routes/issuers/issuer/sign.js
  ui/lib/pki/addon/routes/keys/create.js
  ui/lib/pki/addon/routes/keys/import.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/keys/key.js
  ui/lib/pki/addon/routes/keys/key/details.js
  ui/lib/pki/addon/routes/keys/key/edit.js
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/routes/roles/role/generate.js
  ui/lib/pki/addon/routes/roles/role/sign.js
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/lib/pki/addon/templates/issuers/index.hbs
  ui/lib/pki/addon/templates/keys/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
Labels: ui, pr/no-changelog

#20121 Update userpass.mdx
  website/content/docs/auth/userpass.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#20205 Add tests for fetching ACME authorizations and challenges
  builtin/logical/pki/acme_authorizations.go
  builtin/logical/pki/acme_wrappers.go
  builtin/logical/pki/path_acme_authorizations.go
  builtin/logical/pki/path_acme_challenges.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
Labels: secret/pki, pr/no-changelog

#20141 Add ACME HTTP-01 Challenge
  builtin/logical/pki/acme_challenges.go
  builtin/logical/pki/acme_challenges_test.go
  builtin/logical/pki/acme_state.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
Labels: enhancement, secret/pki, pr/no-changelog

#20200 sdk/ldap: update interface to use DialURL
  sdk/helper/ldaputil/client.go
  sdk/helper/ldaputil/ldap.go
Labels: pr/no-changelog, backport/1.11.x, backport/1.12.x, backport/1.13.x

#19862 build: try creating the go bin directory
  changelog/19862.txt
  scripts/build.sh
Labels: pr/no-milestone

#20196 Cleanup 🧹
  ui/app/styles/components/action-block.scss
  ui/app/styles/components/auth-buttons.scss
  ui/app/styles/components/b64-toggle.scss
  ui/app/styles/components/box-radio.scss
  ui/app/styles/components/calendar-widget.scss
  ui/app/styles/components/confirm.scss
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/env-banner.scss
  ui/app/styles/components/form-section.scss
  ui/app/styles/components/hover-copy-button.scss
  ui/app/styles/components/icon.scss
  ui/app/styles/components/info-table-row.scss
  ui/app/styles/components/info-table.scss
  ui/app/styles/components/kmip-role-edit.scss
  ui/app/styles/components/license-banners.scss
  ui/app/styles/components/list-pagination.scss
  ui/app/styles/components/masked-input.scss
  ui/app/styles/components/namespace-picker.scss
  ui/app/styles/components/page-header.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/components/read-more.scss
  ui/app/styles/core.scss
  ui/app/styles/core/box.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/charts.scss
  ui/app/styles/core/checkbox-and-radio.scss
  ui/app/styles/core/columns.scss
  ui/app/styles/core/control.scss
  ui/app/styles/core/field.scss
  ui/app/styles/core/file.scss
  ui/app/styles/core/footer.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/label.scss
  ui/app/styles/core/level.scss
  ui/app/styles/core/menu.scss
  ui/app/styles/core/message.scss
  ui/app/styles/core/navbar.scss
  ui/app/styles/core/progress.scss
  ui/app/styles/core/select.scss
  ui/app/styles/core/switch.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/core/title.scss
  ui/app/styles/core/toggle.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/styles/utils/_box-shadow_variables.scss
  ui/app/templates/components/secret-edit-metadata.hbs
  ui/app/templates/vault/cluster/secrets/backend/metadata.hbs
  ui/lib/kmip/addon/templates/components/edit-form-kmip-role.hbs
  ui/lib/pki/addon/components/pki-import-pem-bundle.hbs
  ui/lib/pki/addon/templates/issuers/issuer/cross-sign.hbs
Labels: ui

#20220 Minor follow-ups to #16865
  builtin/logical/pki/storage.go
  changelog/20220.txt
  website/content/api-docs/secret/pki.mdx
Labels: bug, secret/pki, backport/1.12.x, backport/1.13.x

#19566 Add changelog for constant-time shamir change
  changelog/19495.txt
Labels: backport/1.10.x, backport/1.11.x, backport/1.12.x, backport/1.13.x

#20218 Remove out of scope changes
  ui/app/styles/components/auth-buttons.scss
  ui/app/styles/components/auth-form.scss
  ui/app/styles/components/b64-toggle.scss
  ui/app/styles/components/box-radio.scss
  ui/app/styles/components/confirm.scss
  ui/app/styles/components/console-ui-panel.scss
  ui/app/styles/components/hover-copy-button.scss
  ui/app/styles/components/icon.scss
  ui/app/styles/components/license-banners.scss
  ui/app/styles/components/list-pagination.scss
  ui/app/styles/components/masked-input.scss
  ui/app/styles/components/namespace-picker.scss
  ui/app/styles/components/page-header.scss
  ui/app/styles/components/popup-menu.scss
  ui/app/styles/components/tabs.scss
  ui/app/styles/components/vlt-table.scss
  ui/app/styles/core/breadcrumb.scss
  ui/app/styles/core/buttons.scss
  ui/app/styles/core/file.scss
  ui/app/styles/core/footer.scss
  ui/app/styles/core/inputs.scss
  ui/app/styles/core/level.scss
  ui/app/styles/core/progress.scss
  ui/app/styles/core/toggle.scss
  ui/app/styles/utils/_font_variables.scss
  ui/app/styles/utils/_size_variables.scss
  ui/tests/integration/components/kubernetes/page/configure-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog

#20232 docs/debug: add example policy for debug command
  website/content/docs/commands/debug.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, backport/1.13.x

#20233 Backport of docs/debug: add example policy for debug command into release/1.13.x
  website/content/docs/commands/debug.mdx
Labels: pr/no-changelog, pr/no-milestone

#20195 Add discuss links to changelog entries for previous releases
  CHANGELOG.md
Labels: pr/no-changelog

#20209 Run UI tests on PRs with "ui" label
  .github/workflows/ci.yml
  .github/workflows/milestone-checker.yml
Labels: ui, pr/no-changelog
