Repository hashicorp/vault, pull requests merged in 2024-07, with the labels that each got.

#27631 Force rotate root to the active node
  changelog/27631.txt
  vault/logical_system_paths.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27647 Backport of Allow stubmaker to work outside of a git repository into release/1.17.x
  tools/stubmaker/main.go
Labels: hashicorp-contributed-pr

#27648 Update index.mdx with proper capitalization
  website/content/docs/enterprise/index.mdx
Labels: hashicorp-contributed-pr

#27652 Update vault-plugin-secrets-azure to v0.19.2
  changelog/27652.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.17.x

#27654 Backport Azure Secrets v0.19.2 upgrade into `release/1.17.x`
  changelog/27652.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#27636 VAULT-28522: Update actions/checkout to 4.1.7
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27659 Backport of VAULT-28522: Update actions/checkout to 4.1.7 into release/1.17.x
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27617 add retry logic in ldap.PrepareTestContainer
  helper/testhelpers/ldap/ldaphelper.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27620 AWS secrets: add support for STS session tags
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/path_roles.go
  builtin/logical/aws/path_roles_test.go
  builtin/logical/aws/path_user.go
  builtin/logical/aws/secret_access_keys.go
  changelog/27620.txt
  website/content/api-docs/secret/aws.mdx
Labels: hashicorp-contributed-pr

#27633 Make mountsLock and authLock in Core configurable
  changelog/27633.txt
  vault/core.go
  vault/core_test.go
  vault/logical_system.go
Labels: hashicorp-contributed-pr

#27656 Add auto-roll billing start date changes CE changes
  changelog/27656.txt
  helper/timeutil/timeutil.go
  helper/timeutil/timeutil_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#27628 docs: known issue for listener using `proxy_protocol _behavior`
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/config_listener_proxy_protocol_behavior_issue.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27663 db/mssql: increase context timeout in test
  plugins/database/mssql/mssql.go
  plugins/database/mssql/mssql_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27665 Backport of docs: known issue for listener using `proxy_protocol _behavior` into release/1.17.x
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/config_listener_proxy_protocol_behavior_issue.mdx
Labels: backport, docs, pr/no-milestone, hashicorp-contributed-pr

#27669 Backport of known issue with autopilot upgrades into release/1.17.x
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/autopilot-upgrade-upgrade-version.mdx
Labels: backport, docs, pr/no-milestone, hashicorp-contributed-pr

#27660 VAULT-28255: Fix namespaced redirects
  changelog/27660.txt
  http/handler.go
  http/help.go
  http/logical.go
  http/sys_rekey.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27667 Update to Go 1.22.5
  .go-version
  changelog/_go-ver-1180.txt
Labels: hashicorp-contributed-pr

#27658 [Docs] Update the KV secrets engine overview page
  website/content/docs/secrets/kv/index.mdx
  website/content/docs/secrets/kv/kv-v1.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27672 Backport of [Docs] Update the KV secrets engine overview page into release/1.17.x
  website/content/docs/secrets/kv/index.mdx
  website/content/docs/secrets/kv/kv-v1.mdx
Labels: hashicorp-contributed-pr

#27657 UI: resolves braces < 3.0.3 dep vulnerability and ws < 8.17.1
  ui/package.json
  ui/tests/integration/components/transit-key-actions-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27671 Backport of VAULT-28255: Fix namespaced redirects into release/1.17.x
  changelog/27660.txt
  http/handler.go
  http/help.go
  http/logical.go
  http/sys_rekey.go
Labels: hashicorp-contributed-pr

#27664 Add CE plumbing for CensusManager reload
  command/server.go
  command/server_util.go
  vault/census_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#27650 chore: fix deprecated ioutil nopcloser
  api/request.go
  api/response.go
  command/agentproxyshared/cache/handler.go
  http/handler.go
  http/handler_test.go
  physical/oci/oci.go
  physical/oci/oci_ha.go
  physical/raft/snapshot.go
  physical/raft/snapshot_test.go
  vault/login_mfa.go
Labels: pr/no-changelog

#27680 Update azure docs to include new param
  website/content/api-docs/secret/azure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27682 Update link to perf rep tutorial
  website/content/docs/enterprise/replication/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27683 Backport of Update link to perf rep tutorial into release/1.17.x
  website/content/docs/enterprise/replication/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27681 Handle missing serial number more gracefully
  builtin/logical/pki/path_fetch.go
  changelog/27681.txt
Labels: hashicorp-contributed-pr

#27676 Backport 1.17.x: resolves braces < 3.0.3 dep vulnerability and ws < 8.17.1
  ui/package.json
  ui/tests/integration/components/transit-key-actions-test.js
  ui/yarn.lock
Labels: backport, hashicorp-contributed-pr

#27578 Removal of go-testing-interface (CE changes)
  changelog/27578.txt
  command/command_stubs_oss.go
  command/command_test.go
  command/server.go
  helper/testhelpers/corehelpers/corehelpers.go
  helper/testhelpers/minimal/minimal.go
  helper/testhelpers/pluginhelpers/pluginhelpers.go
  helper/testhelpers/seal/sealhelper.go
  helper/testhelpers/testhelpers.go
  helper/testhelpers/testhelpers_oss.go
  helper/testhelpers/teststorage/consul/consul.go
  helper/testhelpers/teststorage/teststorage.go
  helper/testhelpers/teststorage/teststorage_reusable.go
  http/forwarding_bench_test.go
  http/plugin_test.go
  sdk/helper/testcluster/exec.go
  sdk/helper/testhelpers/output.go
  sdk/logical/testing.go
  vault/expiration_test.go
  vault/external_tests/api/api_integration_test.go
  vault/external_tests/pprof/pprof.go
  vault/external_tests/pprof/pprof_binary/pprof_test.go
  vault/external_tests/pprof/pprof_test.go
  vault/external_tests/raft/raft_test.go
  vault/plugincatalog/testing.go
  vault/seal_testing.go
  vault/seal_testing_util.go
  vault/testing.go
  vault/testing_util.go
  vault/token_store_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#27695 [VAULT-28664] Enable the --rerun-fails option in gotestsum for enterprise to reduce the impact of flaky tests on the CI
  .github/workflows/test-go.yml
Labels: test, pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#27697 Fix CE drift
  helper/benchhelpers/benchhelpers.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27560 Update tcp-tls.mdx
  website/content/docs/configuration/listener/tcp/tcp-tls.mdx
Labels: docs, hashicorp-contributed-pr, backport/1.17.x

#27699 Backport of Update tcp-tls.mdx into release/1.17.x
  website/content/docs/configuration/listener/tcp/tcp-tls.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone

#27511 Update mongodbatlas.mdx
  website/content/docs/secrets/databases/mongodbatlas.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.17.x

#27700 Backport of Update mongodbatlas.mdx into release/1.17.x
  website/content/docs/secrets/databases/mongodbatlas.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27701 Backport of VAULT-28317 Update vault-hcp-lib to fix resource case bug into release/1.17.x
  changelog/27694.txt
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27662 Backport of AWS secrets: add support for STS session tags into release/1.17.x
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/path_roles.go
  builtin/logical/aws/path_roles_test.go
  builtin/logical/aws/path_user.go
  builtin/logical/aws/secret_access_keys.go
  changelog/27620.txt
  website/content/api-docs/secret/aws.mdx
Labels: hashicorp-contributed-pr

#27674 actions: don't use linux runs-on label
  .github/workflows/enos-release-testing-oss.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27711 Fix space in release notes
  website/content/docs/release-notes/1.16.1.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27714 Document the Transit AES CMAC known issue
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/transit-input-on-cmac-response.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27715 Backport of Document the Transit AES CMAC known issue into release/1.17.x
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/transit-input-on-cmac-response.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27708 Backport of [VAULT-28664] Enable the --rerun-fails option in gotestsum for enterprise to reduce the impact of flaky tests on the CI into release/1.17.x
  .github/workflows/test-go.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27712 Backport of Fix space in release notes into release/1.17.x
  website/content/docs/release-notes/1.16.1.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27713 Remove link
  website/content/docs/internals/telemetry/key-metrics.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27716 Backport of Remove link into release/1.17.x
  website/content/docs/internals/telemetry/key-metrics.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27684 refactor external plugin tests
  vault/external_tests/plugin/external_plugin_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27698 Docs: fix telemetry docs for Audit
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27718 Backport of Docs: fix telemetry docs for Audit into release/1.17.x
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Labels: backport, docs, hashicorp-contributed-pr

#27719 Backport: Docs: fix telemetry docs for Audit into 1.15.x
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27720 Backport: Docs: fix telemetry docs for Audit into 1.16.x
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27721 remove erroneous mention of {DEVICE} specific telemetry for Vault aud…
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/device/log_response_failure.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27696 Return the proper serial number in OCSP verification errors
  builtin/logical/pki/integration_test.go
  changelog/27696.txt
  sdk/helper/ocsp/client.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27722 Backport of Return the proper serial number in OCSP verification errors into release/1.17.x
  builtin/logical/pki/integration_test.go
  changelog/27696.txt
  sdk/helper/ocsp/client.go
Labels: backport, auth/cert

#27661 Backport of add retry logic in ldap.PrepareTestContainer into release/1.17.x
  helper/testhelpers/ldap/ldaphelper.go
Labels: hashicorp-contributed-pr

#27547 Handle Query Updates
  changelog/27547.txt
  vault/activity_log.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr

#27726 raft/autopilot: fix panic during autopilot shutdown
  changelog/27726.txt
  physical/raft/raft_autopilot.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27724 Update vault-plugin-auth-cf to v0.18.0
  changelog/27724.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#27727 Backport of raft/autopilot: fix panic during autopilot shutdown into release/1.17.x
  changelog/27726.txt
  physical/raft/raft_autopilot.go
Labels: hashicorp-contributed-pr

#27725 UI: Add more auth test coverage
  ui/tests/acceptance/auth-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27729 Backport of Update vault-plugin-auth-cf to v0.18.0 into release/1.17.x
  changelog/27724.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#27728 UI: Fix namespace picker in small screens
  changelog/27728.txt
  ui/app/styles/components/namespace-picker.scss
  ui/app/templates/components/namespace-picker.hbs
Labels: ui, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27731 Backport of UI: Fix namespace picker in small screens into release/1.17.x
  changelog/27728.txt
  ui/app/styles/components/namespace-picker.scss
  ui/app/templates/components/namespace-picker.hbs
Labels: ui, backport, hashicorp-contributed-pr

#27730 VAULT-28656 CE changes for Proxy bug
  changelog/27730.txt
  command/agentproxyshared/cache/lease_cache.go
  command/agentproxyshared/cache/static_secret_cache_updater.go
  command/agentproxyshared/cache/static_secret_cache_updater_test.go
Labels: hashicorp-contributed-pr

#27741 Fix lowercase steps in utilization docs
  website/content/docs/enterprise/license/utilization-reporting.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27569 KVv2 json cursor jumps on "enter"
  changelog/27569.txt
  ui/lib/core/addon/modifiers/code-mirror.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/json-editor-test.js
Labels: ui, hashicorp-contributed-pr, regression, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27740 Backport of VAULT-28656 CE changes for Proxy bug into release/1.17.x
  changelog/27730.txt
  command/agentproxyshared/cache/lease_cache.go
  command/agentproxyshared/cache/static_secret_cache_updater.go
  command/agentproxyshared/cache/static_secret_cache_updater_test.go
Labels: hashicorp-contributed-pr

#27746 Backport of Docs: add UI support to databases capabilities docs into release/1.17.x
  website/content/docs/secrets/databases/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27744 Docs: Add "administrative_namespace_path" as an available parameter in Vault config
  website/content/docs/configuration/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27748 Backport of Docs: Add "administrative_namespace_path" as an available parameter in Vault config into release/1.17.x
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#27742 UI: Fix ACME Account Safety Buffer not able to be turned off
  changelog/27742.txt
  ui/app/models/pki/tidy.js
  ui/tests/acceptance/pki/pki-tidy-test.js
  ui/tests/integration/components/pki/pki-tidy-form-test.js
Labels: ui, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27753 Update CHANGELOG.md for 1.17.2 1.16.6 and 1.15.12
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27751 Backport of UI: Fix ACME Account Safety Buffer not able to be turned off into release/1.17.x
  changelog/27742.txt
  ui/app/models/pki/tidy.js
  ui/tests/acceptance/pki/pki-tidy-test.js
  ui/tests/integration/components/pki/pki-tidy-form-test.js
Labels: ui, hashicorp-contributed-pr

#27745 Backport of UI: fix KVv2 cursor jumps on enter into release/1.17.x
  changelog/27569.txt
  ui/lib/core/addon/modifiers/code-mirror.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/json-editor-test.js
Labels: ui, backport, hashicorp-contributed-pr

#27759 PKI: Refactor common role path policy code into common area
  builtin/logical/pki/acme_wrappers.go
  builtin/logical/pki/acme_wrappers_test.go
  builtin/logical/pki/issuing/context.go
  builtin/logical/pki/issuing/issue_common.go
  builtin/logical/pki/issuing/issuers.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/pki_backend/common.go
  builtin/logical/pki/pki_backend/rolepathpolicy_enumer.go
  builtin/logical/pki/pki_backend/storage_context.go
  builtin/logical/pki/storage.go
Labels: secret/pki, pr/no-changelog, hashicorp-contributed-pr

#27757 Add custom tags section to sync overview, denote normalized values
  website/content/docs/sync/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.17.x

#27761 Backport of Add custom tags section to sync overview, denote normalized values into release/1.17.x
  website/content/docs/sync/index.mdx
Labels: hashicorp-contributed-pr

#27762 Backport of Add custom tags section to sync overview, denote normalized values into release/1.16.x
  website/content/docs/sync/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#27760 UI: Reuse CC Mirage data if dates are same
  ui/mirage/handlers/clients.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27754 add a retry-command script
  .github/actions/install-external-tools/action.yml
  .github/scripts/retry-command.sh
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#27771 Update go.mod and sdk/go.mod to Go 1.22
  go.mod
  sdk/go.mod
Labels: dependencies, pr/no-changelog, hashicorp-contributed-pr

#27767 Docs: PGP & gpg version requirements with ECDH & Vault 1.13.x or higher
  website/content/docs/concepts/pgp-gpg-keybase.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27646 Docs: autosnapshots notes around AWS EKS & S3 configuration requirments
  website/content/api-docs/system/storage/raftautosnapshots.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27777 Backport of Docs: PGP & gpg version requirements with ECDH & Vault 1.13.x or higher into release/1.17.x
  website/content/docs/concepts/pgp-gpg-keybase.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27778 Backport of Docs: autosnapshots notes around AWS EKS & S3 configuration requirments into release/1.17.x
  website/content/api-docs/system/storage/raftautosnapshots.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27764 UI: Move useOpenApi and getHelpUrl methods to util
  ui/app/models/auth-config.js
  ui/app/models/auth-config/azure.js
  ui/app/models/auth-config/gcp.js
  ui/app/models/auth-config/github.js
  ui/app/models/auth-config/jwt.js
  ui/app/models/auth-config/kubernetes.js
  ui/app/models/auth-config/ldap.js
  ui/app/models/auth-config/okta.js
  ui/app/models/auth-config/radius.js
  ui/app/models/kmip/config.js
  ui/app/models/kmip/role.js
  ui/app/models/pki/certificate/base.js
  ui/app/models/pki/certificate/generate.js
  ui/app/models/pki/certificate/sign.js
  ui/app/models/pki/config/acme.js
  ui/app/models/pki/config/cluster.js
  ui/app/models/pki/config/urls.js
  ui/app/models/pki/issuer.js
  ui/app/models/pki/role.js
  ui/app/models/pki/sign-intermediate.js
  ui/app/models/pki/tidy.js
  ui/app/models/role-ssh.js
  ui/app/services/path-help.js
  ui/app/utils/openapi-helpers.ts
  ui/tests/acceptance/open-api-path-help-test.js
  ui/tests/unit/utils/openapi-helpers-test.js
  ui/types/vault/models/pki/certificate/base.d.ts
  ui/types/vault/models/pki/config/urls.d.ts
  ui/types/vault/models/pki/issuer.d.ts
  ui/types/vault/models/pki/role.d.ts
  ui/types/vault/models/pki/tidy.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27781 [VAULT-28666] Retry staticcheck download on failure in GitHub Actions (GHA)
  .github/actions/set-up-staticcheck/action.yml
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#27710 UI: Refactor auth controller so it does less
  ui/app/components/auth/login-form.hbs
  ui/app/components/auth/login-form.js
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/services/auth.js
  ui/app/templates/components/mfa/mfa-form.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/tests/acceptance/access/namespaces/index-test.js
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/integration/components/auth/page-test.js
  ui/tests/pages/access/namespaces/index.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27783 Backport of add a retry-command script into release/1.17.x
  .github/actions/install-external-tools/action.yml
  .github/scripts/retry-command.sh
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27784 Backport of [VAULT-28666] Retry staticcheck download on failure in GitHub Actions (GHA) into release/1.17.x
  .github/actions/set-up-staticcheck/action.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27786 [VAULT-28666] Retry tool download from GitHub releases on failure in GitHub Actions (GHA)
  .github/actions/set-up-buf/action.yml
  .github/actions/set-up-gofumpt/action.yml
  .github/actions/set-up-gosimports/action.yml
  .github/actions/set-up-gotestsum/action.yml
  .github/actions/set-up-misspell/action.yml
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#27789 Backport of [VAULT-28666] Retry tool download from GitHub releases on failure in GitHub Actions (GHA) into release/1.17.x
  .github/actions/set-up-buf/action.yml
  .github/actions/set-up-gofumpt/action.yml
  .github/actions/set-up-gosimports/action.yml
  .github/actions/set-up-gotestsum/action.yml
  .github/actions/set-up-misspell/action.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27723 remove redundant call to set token in tests
  vault/external_tests/plugin/external_plugin_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27752 WIF AWS: Add identity_token_key to model and render
  ui/app/components/mount-backend-form.hbs
  ui/app/components/mount-backend-form.ts
  ui/app/models/mount-config.js
  ui/app/models/secret-engine.js
  ui/lib/core/addon/components/form-field-groups.hbs
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/components/search-select-with-modal.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/unit/adapters/secret-engine-test.js
  ui/tests/unit/models/secret-engine-test.js
Labels: ui, hashicorp-contributed-pr

#27793 Update docs around dead_server_last_contact_threshold
  website/content/api-docs/system/storage/raftautopilot.mdx
  website/content/docs/concepts/integrated-storage/autopilot.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27785 UI: update overview card action handling
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/kv/addon/components/page/list.hbs
  ui/lib/ldap/addon/components/accounts-checked-out.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/lib/ldap/addon/components/page/overview.hbs
  ui/lib/pki/addon/components/page/pki-overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/tests/integration/components/overview-card-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27800 docs: add missing rotation_statements to mssql api docs
  website/content/api-docs/secret/databases/mssql.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27801 Backport of docs: add missing rotation_statements to mssql api docs into release/1.17.x
  website/content/api-docs/secret/databases/mssql.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27796 UI: Update date-picker UX in Client Counts
  changelog/27796.txt
  ui/app/components/calendar-widget.js
  ui/app/components/clients/date-range.hbs
  ui/app/components/clients/date-range.ts
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/date-dropdown.js
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/app/styles/components/clients-date-range.scss
  ui/app/styles/core.scss
  ui/app/templates/components/date-dropdown.hbs
  ui/tests/acceptance/clients/counts-test.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/helpers/clients/client-count-helpers.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/integration/components/calendar-widget-test.js
  ui/tests/integration/components/clients/date-range-test.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/date-dropdown-test.js
Labels: ui, hashicorp-contributed-pr

#27802 docs: add missing rotation_statements to oracle docs
  website/content/api-docs/secret/databases/oracle.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27803 Backport of docs: add missing rotation_statements to oracle docs into release/1.17.x
  website/content/api-docs/secret/databases/oracle.mdx
Labels: hashicorp-contributed-pr

#27806 audit: name `audit` logger used by audit broker for `standardUnsealStrategy`'s `unseal` method
  vault/core.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27807 Backport of audit: name `audit` logger used by audit broker for `standardUnsealStrategy`'s `unseal` method into release/1.17.x
  vault/core.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27809 Audit: log 'warnings' from eventlogger even if audit is deemed a success
  audit/broker.go
  changelog/27809.txt
Labels: core/audit, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27813 Backport of Audit: log 'warnings' from eventlogger even if audit is deemed a success into release/1.17.x
  audit/broker.go
  changelog/27809.txt
Labels: backport, hashicorp-contributed-pr

#27811 db: refactor postgres test helpers
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rollback_test.go
  builtin/logical/database/rotation_test.go
  helper/testhelpers/postgresql/postgresqlhelper.go
  physical/postgresql/postgresql_test.go
  plugins/database/postgresql/postgresql_test.go
  vault/external_tests/plugin/external_plugin_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27792 Docs: Add a Priority matching policy example using Namespaces
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27817 Backport of Docs: Add a Priority matching policy example using Namespaces into release/1.17.x
  website/content/docs/concepts/policies.mdx
Labels: hashicorp-contributed-pr

#27808 Title case all static breadcrumbs
  ui/app/components/transit-edit.js
  ui/app/controllers/vault/cluster/access/leases/list.js
  ui/app/controllers/vault/cluster/access/leases/show.js
  ui/app/routes/vault/cluster/secrets/backend/actions.js
  ui/lib/kubernetes/addon/routes/configuration.js
  ui/lib/kubernetes/addon/routes/configure.js
  ui/lib/kubernetes/addon/routes/roles/create.js
  ui/lib/kubernetes/addon/routes/roles/index.js
  ui/lib/kubernetes/addon/routes/roles/role/credentials.js
  ui/lib/kubernetes/addon/routes/roles/role/details.js
  ui/lib/kubernetes/addon/routes/roles/role/edit.js
  ui/lib/kv/addon/routes/configuration.js
  ui/lib/kv/addon/routes/create.js
  ui/lib/kv/addon/routes/secret/details/edit.js
  ui/lib/kv/addon/routes/secret/metadata/diff.js
  ui/lib/kv/addon/routes/secret/metadata/edit.js
  ui/lib/kv/addon/routes/secret/metadata/index.js
  ui/lib/kv/addon/routes/secret/metadata/versions.js
  ui/lib/kv/addon/routes/secret/paths.js
  ui/lib/ldap/addon/routes/configuration.ts
  ui/lib/ldap/addon/routes/libraries/create.ts
  ui/lib/ldap/addon/routes/libraries/index.ts
  ui/lib/ldap/addon/routes/roles/create.ts
  ui/lib/ldap/addon/routes/roles/index.ts
  ui/lib/pki/addon/routes/certificates/certificate/details.js
  ui/lib/pki/addon/routes/configuration/create.js
  ui/lib/pki/addon/routes/configuration/edit.js
  ui/lib/pki/addon/routes/issuers/generate-intermediate.js
  ui/lib/pki/addon/routes/issuers/generate-root.js
  ui/lib/pki/addon/routes/issuers/import.js
  ui/lib/pki/addon/routes/issuers/index.js
  ui/lib/pki/addon/routes/issuers/issuer.js
  ui/lib/pki/addon/routes/issuers/issuer/cross-sign.js
  ui/lib/pki/addon/routes/issuers/issuer/details.js
  ui/lib/pki/addon/routes/issuers/issuer/edit.js
  ui/lib/pki/addon/routes/issuers/issuer/rotate-root.js
  ui/lib/pki/addon/routes/issuers/issuer/sign.js
  ui/lib/pki/addon/routes/keys/create.js
  ui/lib/pki/addon/routes/keys/import.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/integration/components/kv/page/kv-page-metadata-edit-test.js
  ui/tests/integration/components/kv/page/kv-page-version-diff-test.js
  ui/tests/integration/components/kv/page/kv-page-version-history-test.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
  ui/tests/integration/components/ldap/page/role/create-and-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27758 Fixing typo "auth_auth" should be "auto_auth"
  website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.17.x

#27818 Backport of Fixing typo "auth_auth" should be "auto_auth" into release/1.17.x
  website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx
Labels: hashicorp-contributed-pr

#27812 [Docs] Add a warning about namespace info for HVD
  website/content/api-docs/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27819 Backport of [Docs] Add a warning about namespace info for HVD into release/1.17.x
  website/content/api-docs/index.mdx
Labels: hashicorp-contributed-pr

#27766 Docs update for vault helm v0.28.1 release
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27820 Backport of Docs update for vault helm v0.28.1 release into release/1.17.x
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: hashicorp-contributed-pr

#27790 VAULT-28329: Fix `months` activity log counts when querying for a namespace
  changelog/27790.txt
  vault/activity_log.go
Labels: hashicorp-contributed-pr

#27668 docs/vso: instant updates
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/instant-updates.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27763 Update VSO docs for auto CRD upgrade behaviour
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27797 VSO: update docs for VaultAuthGlobals
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/content/partials/vso/common-links.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27828 Backport of Bump google.golang.org/grpc from 1.64.0 to 1.64.1 into release/1.17.x
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27827 CE no-op CensusManager
  vault/census.go
  vault/census_manager.go
  vault/census_stubs_oss.go
  vault/core.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#27810 VAULT-27384 Fix faulty assignments and unchecked errors
  builtin/logical/database/secret_creds.go
  command/agentproxyshared/auth/auth.go
  command/pki_reissue_intermediate.go
  helper/testhelpers/pluginhelpers/pluginhelpers.go
  vault/eventbus/bus.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27835 Bump VSO versions to 0.8.0
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27834 Backport of VSO: update docs for VaultAuthGlobals into release/1.17.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/content/partials/vso/common-links.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27826 Backport of Update VSO docs for auto CRD upgrade behaviour into release/1.17.x
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27825 Backport of docs/vso: instant updates into release/1.17.x
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/instant-updates.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27843 UI: upgrade HDS to 4.6.0
  ui/package.json
  ui/yarn.lock
Labels: ui, backport, dependencies, pr/no-changelog, hashicorp-contributed-pr

#27844 UI Backport 1.17.x: Upgrade HDS to 4.6.0
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27842 [VAULT-28666] Remove the errexit option from the retry script and add increasing wait on failure (up to 5 seconds and 5 retries)
  .github/scripts/retry-command.sh
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr, backport/1.17.x

#27639 Backport of Docs: VAULT_DISABLE_REDIRECTS added further clarity into release/1.17.x
  website/content/docs/commands/index.mdx
Labels: hashicorp-contributed-pr

#27848 UI: Move OIDC key header out of form component
  ui/app/templates/components/oidc/key-form.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/create.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key/edit.hbs
  ui/tests/integration/components/oidc/key-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27845 Backport of [VAULT-28666] Remove the errexit option from the retry script and add increasing wait on failure (up to 5 seconds and 5 retries) into release/1.17.x
  .github/scripts/retry-command.sh
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27852 [VAULT-28666] Enable the --clobber flag on GitHub CLI release downloads in CI to avoid errors when retrying
  .github/actions/set-up-buf/action.yml
  .github/actions/set-up-gofumpt/action.yml
  .github/actions/set-up-gosimports/action.yml
  .github/actions/set-up-gotestsum/action.yml
  .github/actions/set-up-misspell/action.yml
  .github/actions/set-up-staticcheck/action.yml
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr, backport/1.17.x

#27853 Backport of [VAULT-28666] Enable the --clobber flag on GitHub CLI release downloads in CI to avoid errors when retrying into release/1.17.x
  .github/actions/set-up-buf/action.yml
  .github/actions/set-up-gofumpt/action.yml
  .github/actions/set-up-gosimports/action.yml
  .github/actions/set-up-gotestsum/action.yml
  .github/actions/set-up-misspell/action.yml
  .github/actions/set-up-staticcheck/action.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27847 VAULT-27563 CE changes
  vault/activity_log.go
  vault/census_manager.go
  vault/core.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27846 Add non-root access with filtering support to activity export API
  api/sudo_paths.go
  changelog/27846.txt
  vault/activity/test_fixtures/aug.csv
  vault/activity/test_fixtures/aug.json
  vault/activity/test_fixtures/aug_oct.csv
  vault/activity/test_fixtures/aug_oct.json
  vault/activity/test_fixtures/aug_sep.csv
  vault/activity/test_fixtures/aug_sep.json
  vault/activity/test_fixtures/full_history.csv
  vault/activity/test_fixtures/full_history.json
  vault/activity_log.go
  vault/activity_log_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system.go
  vault/logical_system_activity.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: hashicorp-contributed-pr

#27851 [Docs] Minor editorial fixes - "token capabilities"
  website/content/docs/commands/token/capabilities.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27857 Backport of [Docs] Minor editorial fixes - "token capabilities" into release/1.17.x
  website/content/docs/commands/token/capabilities.mdx
Labels: hashicorp-contributed-pr

#27860 Audit: Use the `core` logger for audit enable errors (not the system backend)
  vault/logical_system.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27859 Audit: optional logger for sinks will log on errors when context is done
  audit/backend_file.go
  audit/backend_socket.go
  audit/backend_syslog.go
  changelog/27859.txt
  internal/observability/event/options.go
  internal/observability/event/options_test.go
  internal/observability/event/sink_file.go
  internal/observability/event/sink_socket.go
  internal/observability/event/sink_syslog.go
  vault/audit.go
Labels: core/audit, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27861 Audit: Remove multi-errors and update expected error msg in tests
  audit/broker.go
  vault/audit_test.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27779 Send warning and do not return error on group update if cluster is a PR secondary and RPC client is nil
  vault/identity_store_util.go
  vault/testing.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27863 Backport of Audit: Use the `core` logger for audit enable errors (not the system backend) into release/1.17.x
  vault/logical_system.go
Labels: backport, hashicorp-contributed-pr

#27864 Backport of Audit: optional logger for sinks will log on errors when context is done into release/1.17.x
  audit/backend_file.go
  audit/backend_socket.go
  audit/backend_syslog.go
  changelog/27859.txt
  internal/observability/event/options.go
  internal/observability/event/options_test.go
  internal/observability/event/sink_file.go
  internal/observability/event/sink_socket.go
  internal/observability/event/sink_syslog.go
  vault/audit.go
Labels: backport, hashicorp-contributed-pr

#27865 Backport of Audit: Remove multi-errors and update expected error msg in tests into release/1.17.x
  audit/broker.go
  vault/audit_test.go
Labels: hashicorp-contributed-pr

#27866 Backport of Send warning and do not return error on group update if cluster is a PR secondary and RPC client is nil into release/1.17.x
  vault/identity_store_util.go
  vault/testing.go
Labels: hashicorp-contributed-pr

#27776 VAULT-28029: Cleanup for activity log
  vault/activity_log.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#27856 WIF AWS: add create functionality to SearchSelectWithModal for identity_token_key (take 2)
  ui/app/components/modal-form/oidc-key-template.hbs
  ui/app/components/modal-form/oidc-key-template.js
  ui/app/components/mount-backend-form.hbs
  ui/app/components/mount-backend-form.ts
  ui/app/components/oidc/key-form.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/serializers/secret-engine.js
  ui/app/templates/components/oidc/key-form.hbs
  ui/lib/core/addon/components/input-search.hbs
  ui/lib/core/addon/components/search-select-with-modal.hbs
  ui/lib/core/addon/components/search-select-with-modal.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/secrets/policy-generator.ts
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/search-select-with-modal-test.js
  ui/tests/unit/adapters/secret-engine-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#27849 Remove distinct_entities and non_entity_tokens from ResponseCounts and update docs
  vault/activity_log.go
  website/content/api-docs/system/internal-counters.mdx
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27750 VAULT-28677: Fix dangling entity-aliases in MemDB after invalidation
  changelog/27750.txt
  vault/identity_store.go
  vault/identity_store_test.go
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/dangling-entity-aliases-in-memory.mdx
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.17.x

#27870 Backport of VAULT-28677: Fix dangling entity-aliases in MemDB after invalidation into release/1.17.x
  changelog/27750.txt
  vault/identity_store.go
  vault/identity_store_test.go
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/dangling-entity-aliases-in-memory.mdx
Labels: hashicorp-contributed-pr
