Repository hashicorp/vault, pull requests merged in 2024-02, with the labels that each got.

#25130 Support adding new stubs to existing stub files
  tools/stubmaker/main.go
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#25126 Request Limiter Reload tests
  .github/workflows/test-go.yml
  command/command_testonly/server_testonly_test.go
  command/server_test.go
  command/server_util.go
  http/handler.go
  limits/limiter.go
  limits/registry.go
  sdk/logical/request.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_limits.go
  vault/logical_system_limits_testonly.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24958 Base Binary Cert and CSR Parse functions.
  builtin/logical/pki/cert_util_test.go
  command/pki_reissue_intermediate.go
  sdk/helper/certutil/helpers.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25160 Notify For Data Race Failures
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone

#25162 Fix typo in count.mdx
  website/content/partials/telemetry-metrics/vault/identity/entity/alias/count.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.15.x

#25172 Backport of Fix typo in count.mdx into release/1.15.x
  website/content/partials/telemetry-metrics/vault/identity/entity/alias/count.mdx
Labels: hashicorp-contributed-pr

#25175 Initialize license in command_testonly for enterprise
  command/command_testonly/server_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25152 Bug fix: Update KV data when you change the version of a nested secret
  changelog/25152.txt
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
Labels: ui, bug, secret/kv, hashicorp-contributed-pr, backport/1.15.x

#19318 docs(kubernetes-auth): add API documentation for kubernetes auth namespace selectors
  website/content/api-docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog

#24941 add new config option use_annotations_as_alias_metadata for k8s auth on api docs
  website/content/api-docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25171 Seal HA Improvements, CE side
  changelog/25171.txt
  vault/logical_system.go
  vault/seal/seal.go
Labels: hashicorp-contributed-pr

#25180 Fix a race in ToggleableWrapper (test struct)
  vault/seal/seal_testing.go
Labels: pr/no-changelog, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#25179 UI: hardcode selectChoose for Page::Counts
  ui/tests/integration/components/clients/page/counts-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#25181 Backport of Fix a race in ToggleableWrapper (test struct) into release/1.13.x
  vault/seal/seal_testing.go
Labels: hashicorp-contributed-pr

#25182 Backport of Fix a race in ToggleableWrapper (test struct) into release/1.14.x
  vault/seal/seal_testing.go
Labels: hashicorp-contributed-pr

#25183 Backport of Fix a race in ToggleableWrapper (test struct) into release/1.15.x
  vault/seal/seal_testing.go
Labels: hashicorp-contributed-pr

#25187 Update vault-plugin-secrets-ad to v0.17.0
  changelog/25187.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25154 Manual license reporting backport 1.13
  command/commands.go
  command/operator_utilization.go
  helper/timeutil/timeutil.go
  helper/timeutil/timeutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/census.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_activity.go
  vault/testing.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#25139 Revert "Revert manual license reporting changes from 1.14.x"
  command/commands.go
  command/operator_utilization.go
  helper/timeutil/timeutil.go
  helper/timeutil/timeutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/census.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_activity.go
  vault/testing.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25128 Make plugin-specific env take precedence over sys env
  changelog/25128.txt
  sdk/helper/pluginutil/env.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_test.go
  sdk/plugin/mock/backend.go
  sdk/plugin/mock/path_env.go
  vault/external_tests/plugin/plugin_test.go
  vault/plugincatalog/plugin_catalog.go
  vault/plugincatalog/plugin_catalog_test.go
Labels: hashicorp-contributed-pr

#25168 Docs: Tranform secrets encode parameter: `expiration` added.
  website/content/api-docs/secret/transform.mdx
Labels: docs, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#25136 Manual license reporting backport 1.15
  command/commands.go
  command/operator_utilization.go
  helper/timeutil/timeutil.go
  helper/timeutil/timeutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/census.go
  vault/core.go
  vault/logical_system.go
  vault/logical_system_activity.go
  vault/testing.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#25194 Backport of Docs: Tranform secrets encode parameter: `expiration` added. into release/1.15.x
  website/content/api-docs/secret/transform.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25193 Backport of Docs: Tranform secrets encode parameter: `expiration` added. into release/1.14.x
  website/content/api-docs/secret/transform.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25192 Backport of Docs: Tranform secrets encode parameter: `expiration` added. into release/1.13.x
  website/content/api-docs/secret/transform.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25186 Secrets Sync Demo Feedback
  ui/lib/sync/addon/components/secrets/destination-header.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/destination-header-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: ui, pr/no-changelog

#25177 Backport 1.15.6: Manual of update KV data on version dropdown change for nested secrets
  changelog/25152.txt
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
Labels: ui, backport, hashicorp-contributed-pr

#25197 [QT-669] Automatically synchronize git hooks on make invocation
  Makefile
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25199 [QT-669] Automatically synchronize git hooks on make invocation
  .hooks/pre-commit
  Makefile
  scripts/go-helper.sh
  scripts/gofmtcheck.sh
  scripts/goversioncheck.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25201 [QT-669] Automatically synchronize git hooks on make invocation
  .hooks/pre-commit
  Makefile
  scripts/go-helper.sh
  scripts/goversioncheck.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25198 [QT-669] Automatically synchronize git hooks on make invocation
  Makefile
  builtin/credential/aws/client.go
  builtin/credential/aws/path_config_client_test.go
  builtin/credential/aws/path_role_test.go
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/secret_access_keys.go
  builtin/plugin/v5/backend.go
  command/agentproxyshared/auth/oci/oci.go
  command/kv_metadata_put_test.go
  helper/pgpkeys/encrypt_decrypt.go
  physical/dynamodb/dynamodb.go
  physical/foundationdb/foundationdb.go
  physical/raft/raft_test.go
  physical/zookeeper/zookeeper_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/docker/testhelpers.go
  vault/external_tests/kv/kv_patch_test.go
  vault/identity_store_aliases_test.go
  vault/request_handling.go
  vault/version_store.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25204 Update vault-plugin-secrets-kubernetes to v0.7.0
  changelog/25204.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25205 Add experiment flag for import
  helper/experiments/experiments.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25196 Update vault-plugin-auth-cf to v0.16.0
  changelog/25196.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25189 Update vault-plugin-secrets-azure to v0.17.0
  changelog/25189.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25207 Update vault-plugin-auth-kubernetes to v0.18.0
  changelog/25207.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25208 Sync Acceptance Tests
  ui/lib/sync/addon/components/secrets/page/destinations/select-type.hbs
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/acceptance/sync/secrets/overview-test.js
  ui/tests/helpers/general-selectors.js
  ui/tests/helpers/sync/sync-selectors.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25209 UI: Make empty state links consistent
  changelog/25209.txt
  ui/app/components/clients/no-data.hbs
  ui/app/templates/components/dashboard/quick-actions-card.hbs
  ui/app/templates/components/dashboard/replication-card.hbs
  ui/app/templates/components/dashboard/secrets-engines-card.hbs
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/generate-credentials-database.hbs
  ui/app/templates/components/identity/item-metadata.hbs
  ui/app/templates/components/keymgmt/provider-edit.hbs
  ui/app/templates/vault/cluster/access/identity/aliases/index.hbs
  ui/app/templates/vault/cluster/access/identity/index.hbs
  ui/app/templates/vault/cluster/access/leases/error.hbs
  ui/app/templates/vault/cluster/access/oidc/clients/client/providers.hbs
  ui/app/templates/vault/cluster/access/oidc/keys/key/clients.hbs
  ui/app/templates/vault/cluster/access/oidc/providers/provider/clients.hbs
  ui/app/templates/vault/cluster/access/oidc/scopes/index.hbs
  ui/app/templates/vault/cluster/access/reset-password-error.hbs
  ui/app/templates/vault/cluster/policies/index.hbs
  ui/app/templates/vault/cluster/replication-dr-promote/details.hbs
  ui/app/templates/vault/cluster/replication-dr-promote/index.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/app/templates/vault/cluster/unseal.hbs
  ui/lib/core/addon/components/upgrade-page.hbs
  ui/lib/kmip/addon/templates/configuration.hbs
  ui/lib/kubernetes/addon/components/config-cta.hbs
  ui/lib/kubernetes/addon/components/page/roles.hbs
  ui/lib/kv/addon/components/page/list.hbs
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/details.hbs
  ui/lib/kv/addon/components/page/secret/metadata/edit.hbs
  ui/lib/ldap/addon/components/config-cta.hbs
  ui/lib/ldap/addon/components/page/libraries.hbs
  ui/lib/ldap/addon/components/page/roles.hbs
  ui/lib/pki/addon/components/page/pki-issuer-list.hbs
  ui/lib/pki/addon/components/page/pki-key-list.hbs
  ui/lib/pki/addon/templates/certificates/index.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/lib/pki/addon/templates/overview.hbs
  ui/lib/pki/addon/templates/roles/index.hbs
  ui/lib/pki/addon/templates/tidy/index.hbs
  ui/lib/replication/addon/templates/mode/secondaries/index.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/tests/acceptance/oidc-config/providers-scopes-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/database/workflow-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/helpers/oidc-config.js
  ui/tests/integration/components/kubernetes/page/roles-test.js
  ui/tests/integration/components/ldap/page/libraries-test.js
  ui/tests/integration/components/ldap/page/roles-test.js
Labels: ui, hashicorp-contributed-pr

#25215 Docs: audit log: `client_id`
  website/content/docs/concepts/client-count/index.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#25216 Avoid map iteration induced flakiness in seal wrapper key searching
  vault/seal/seal.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25217 Update vault-plugin-auth-alicloud to v0.17.0
  changelog/25217.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25169 UI: Fix bugs in custom messages
  ui/app/templates/vault/cluster.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.js
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/config-ui/addon/components/messages/preview-image.hbs
  ui/lib/core/addon/helpers/new-line-split.js
  ui/lib/core/app/helpers/new-line-split.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-message-test.js
  ui/tests/integration/components/config-ui/messages/page/list-test.js
  ui/tests/integration/helpers/new-line-split-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24718 database: Emit event notifications
  builtin/logical/database/backend.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_creds_create.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_rotate_credentials.go
  builtin/logical/database/rotation.go
  builtin/logical/database/rotation_test.go
  changelog/24718.txt
  sdk/logical/events_mock.go
  website/content/docs/concepts/events.mdx
Labels: hashicorp-contributed-pr

#25218 UI: k8s auth openapi update
  ui/app/models/auth-config/kubernetes.js
  ui/tests/helpers/openapi/auth-model-attributes.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25173 Update vault-plugin-secrets-gcp to v0.18.0
  changelog/25173.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25227 Backport of Only warn if failing to persist encryption counts due to timeout into release/1.15.x
  vault/core.go
Labels: hashicorp-contributed-pr

#25220 VAULT-20086 Handle potential panic
  vault/expiration.go
  vault/token_store.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25222 Sync Destination Edit Bug
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/helpers/general-selectors.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25081 UI: Custom messages acceptance tests
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/tests/acceptance/config-ui/messages/messages-test.js
  ui/tests/helpers/config-ui/message-selectors.js
  ui/tests/helpers/general-selectors.js
  ui/tests/integration/components/config-ui/messages/page/list-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25226 Replace PKI test suites custom runCommands with vault tools runCmd
  ui/tests/acceptance/pki/pki-action-forms-test.js
  ui/tests/acceptance/pki/pki-configuration-test.js
  ui/tests/acceptance/pki/pki-cross-sign-test.js
  ui/tests/acceptance/pki/pki-engine-route-cleanup-test.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/acceptance/pki/pki-tidy-test.js
  ui/tests/helpers/pki/pki-run-commands.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25231 Update vault-plugin-secrets-gcpkms to v0.16.0
  changelog/25231.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25233 Update vault-plugin-auth-gcp to v0.16.2
  changelog/25233.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25234 rotation POC: detect schedule updates
  builtin/credential/ldap/path_config.go
  vault/rotation.go
Labels: hashicorp-contributed-pr

#25225 Backport of Only warn if failing to persist encryption counts due to timeout into release/1.14.x
  vault/core.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25235 UI: KV version 2 advanced secret updates
  changelog/25235.txt
  ui/lib/core/addon/components/json-editor.hbs
  ui/lib/core/addon/components/json-editor.js
  ui/lib/core/addon/components/kv-object-editor.hbs
  ui/lib/core/addon/components/kv-object-editor.js
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/addon/components/page/secret/details.js
  ui/lib/kv/addon/components/page/secret/edit.hbs
  ui/lib/kv/addon/components/page/secret/edit.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/integration/components/json-editor-test.js
  ui/tests/integration/components/kv-object-editor-test.js
  ui/tests/integration/components/kv/kv-data-fields-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-edit-test.js
Labels: ui, hashicorp-contributed-pr, backport/1.15.x

#24965 Inject rotation jobs in RotationManager over plugin SystemView
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/path_config.go
  builtin/logical/aws/path_config_root.go
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/logical/response.go
  sdk/logical/root_credential.go
  sdk/logical/schedule.go
  sdk/logical/system_view.go
  sdk/plugin/grpc_system.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/backend_grpc.pb.go
  vault/core.go
  vault/dynamic_system_view.go
  vault/request_handling.go
  vault/request_handling_util.go
  vault/rotation.go
  vault/router.go
Labels: hashicorp-contributed-pr

#25236 Test stability cont.
  ui/app/adapters/ldap/role.js
  ui/tests/acceptance/oidc-provider-test.js
  ui/tests/integration/components/page/userpass-reset-password-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24892 [QT-637] Streamline our build pipeline
  .github/actions/build-vault/action.yml
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/actions/containerize/action.yml
  .github/actions/metadata/action.yml
  .github/actions/set-up-buf/action.yml
  .github/actions/set-up-go/action.yml
  .github/actions/set-up-gofumpt/action.yml
  .github/actions/set-up-gotestsum/action.yml
  .github/actions/set-up-misspell/action.yml
  .github/actions/set-up-staticcheck/action.yml
  .github/scripts/changed-files.sh
  .github/scripts/gh-comment.sh
  .github/scripts/report-build-status.sh
  .github/scripts/report-ci-status.sh
  .github/scripts/report_failed_builds.sh
  .github/scripts/verify_changes.sh
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build-vault-ce.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/oss.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .github/workflows/verify_changes.yml
  enos/k8s/enos-terraform-k8s.hcl
  enos/modules/k8s_vault_verify_ui/main.tf
  scripts/ci-helper.sh
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#25147 events: Add filter watch function
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/eventbus/filter.go
  vault/eventbus/filter_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25244 ci: always trigger slack notification for any failure
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25245 Update vault-plugin-auth-oci to v0.15.1
  changelog/25245.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25219 identity: adds generation of plugin identity tokens
  changelog/25219.txt
  vault/dynamic_system_view.go
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_provider.go
  vault/identity_store_oidc_provider_test.go
  vault/identity_store_oidc_test.go
  vault/identity_store_structs.go
  vault/logical_system.go
  vault/mount.go
Labels: hashicorp-contributed-pr

#25247 UI: Update advanced-secret tests and logic
  ui/lib/core/addon/utils/advanced-secret.js
  ui/tests/unit/utils/advanced-secret-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#25251 Update vault-plugin-secrets-openldap to v0.12.0
  changelog/25251.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25253 Update vault-plugin-secrets-mongodbatlas to v0.11.0
  changelog/25253.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25257 Update vault-plugin-secrets-alicloud to v0.16.0
  changelog/25257.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25258 Update vault-plugin-auth-azure to v0.17.0
  changelog/25258.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25223 Fix typo in namespace API unlock
  website/content/docs/concepts/namespace-api-lock.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#25261 Backport of Fix typo in namespace API unlock into release/1.15.x
  website/content/docs/concepts/namespace-api-lock.mdx
Labels: hashicorp-contributed-pr

#25259 Backport of Fix typo in namespace API unlock into release/1.13.x
  website/content/docs/concepts/namespace-api-lock.mdx
Labels: hashicorp-contributed-pr

#25262 ci: fix changed file detection
  .github/scripts/changed-files.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25229 UI: Part three bug bash custom messages
  ui/app/models/config-ui/message.js
  ui/app/serializers/config-ui/message.js
  ui/lib/config-ui/addon/components/messages/message-expiration-date-form.hbs
  ui/lib/config-ui/addon/components/messages/message-expiration-date-form.js
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/config-ui/addon/controllers/messages/create.js
  ui/lib/config-ui/addon/routes/messages/index.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/tests/acceptance/config-ui/messages/messages-test.js
  ui/tests/helpers/config-ui/message-selectors.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-message-test.js
  ui/tests/integration/components/form-field-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25256 UI: Update resultant-acl banner
  changelog/25256.txt
  ui/app/adapters/permissions.js
  ui/app/components/resultant-acl-banner.hbs
  ui/app/components/resultant-acl-banner.js
  ui/app/controllers/vault/cluster.js
  ui/app/services/permissions.js
  ui/app/templates/vault/cluster.hbs
  ui/tests/integration/components/resultant-acl-banner-test.js
  ui/tests/unit/adapters/permissions-test.js
Labels: ui, hashicorp-contributed-pr, backport/1.15.x

#25267 Backport of UI: Update resultant-acl banner into release/1.15.x
  changelog/25256.txt
  ui/app/adapters/permissions.js
  ui/app/components/resultant-acl-banner.hbs
  ui/app/components/resultant-acl-banner.js
  ui/app/controllers/vault/cluster.js
  ui/app/services/permissions.js
  ui/app/templates/vault/cluster.hbs
  ui/tests/integration/components/resultant-acl-banner-test.js
  ui/tests/unit/adapters/permissions-test.js
Labels: ui, backport, hashicorp-contributed-pr

#25264 Update vault-plugin-database-mongodbatlas to v0.11.0
  changelog/25264.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25269 UI: Fix copy button not working for non-string masked values
  changelog/25269.txt
  ui/lib/core/addon/components/masked-input.hbs
  ui/lib/core/addon/components/masked-input.js
  ui/tests/integration/components/masked-input-test.js
Labels: ui, bug, hashicorp-contributed-pr

#25265 identity: skip oidc default key generation on read-only storage error for local mounts
  vault/logical_system.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25275 Update vault-plugin-database-couchbase to v0.10.0
  changelog/25275.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25277 Update vault-plugin-secrets-kv to v0.17.0
  changelog/25277.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25271 bump tags on VLE docs, include ap-south-2
  website/content/docs/platform/aws/lambda-extension.mdx
Labels: docs, pr/no-changelog

#25276 Test Fixes
  ui/lib/core/addon/components/masked-input.js
  ui/tests/integration/components/masked-input-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25273 Sync Destination Delete Bug
  ui/lib/sync/addon/components/secrets/destination-header.ts
  ui/tests/integration/components/sync/secrets/destination-header-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25268 ci: fix status result determination
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25288 Update vault-plugin-secrets-terraform to v0.7.5
  changelog/25288.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25289 Update vault-plugin-database-redis to v0.2.3
  changelog/25289.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#25287 Use new SDK and API versions for 1.16.0
  go.mod
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25283 UI: Updates sync delete test
  ui/tests/acceptance/sync/secrets/destination-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25290 Update Vault auth submodule API versions for 1.16
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25291 Document max_parallel for PKCS#11 seals
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#25293 Backport of Document max_parallel for PKCS#11 seals into release/1.14.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#25294 Backport of Document max_parallel for PKCS#11 seals into release/1.15.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#25298 Remove Enterprise Label from Sync Acceptance Test Module Names
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/acceptance/sync/secrets/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25296 Update vault-plugin-database-redis-elasticache to v0.3.0
  changelog/25296.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.16.x

#25297 Update 1.16 version base on release branch
  version/VERSION
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25281 VSO supports Vault cross namespace auth and fetch
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25301 Backport of Update vault-plugin-database-redis-elasticache to v0.3.0 into release/1.16.x
  changelog/25296.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25305 Update couchbase database plugin to v0.10.1
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25307 Backport of build: fix scheduled workflow logic into release/1.16.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25308 Backport of Update couchbase database plugin to v0.10.1 into release/1.16.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25303 Backport of VSO supports Vault cross namespace auth and fetch into release/1.15.x
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25306 update opentelemetry dependencies
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25243 Fix test to be less flacky
  builtin/logical/pki/cert_util_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25302 Backport of VSO supports Vault cross namespace auth and fetch into release/1.16.x
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25310 Backport of update opentelemetry dependencies into release/1.16.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25311 Backport of Fix test to be less flacky into release/1.16.x
  builtin/logical/pki/cert_util_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25317 test-go: only install datadog-ci if necessary
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25304 Forward EST .well-known requests on performance replicas
  http/handler.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25316 Seal HA documentation updates
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25320 Backport of Seal HA documentation updates into release/1.16.x
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#25319 Backport of Forward EST .well-known requests on performance replicas into release/1.16.x
  http/handler.go
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#25322 ci: always upload data race logs
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25326 Update vault-plugin-auth-jwt to v0.20.0
  changelog/25326.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.16.x

#25323 Backport of ci: always upload data race logs into release/1.16.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25327 Backport of Update vault-plugin-auth-jwt to v0.20.0 into release/1.16.x
  changelog/25326.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25270 Add some helpers to the sdk for working with namespaces.
  changelog/25270.txt
  sdk/helper/testhelpers/namespaces/namespaces.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#25329 Minor improvements to test cluster libraries
  changelog/25329.txt
  helper/testhelpers/testhelpers.go
  helper/testhelpers/teststorage/teststorage.go
  sdk/helper/testcluster/replication.go
  sdk/helper/testcluster/util.go
  vault/testing.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#25191 Router: fix missing lock on routeEntry when accessing backend field
  changelog/25191.txt
  vault/router.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#25331 UI: Fix openAPI test for JWT
  ui/app/models/auth-config/jwt.js
  ui/tests/helpers/openapi/auth-model-attributes.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25333 Backport of UI: Fix openAPI test for JWT into release/1.16.x
  ui/app/models/auth-config/jwt.js
  ui/tests/helpers/openapi/auth-model-attributes.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25335 UI: Redirect after logging in from token expiry
  changelog/25335.txt
  ui/app/components/token-expire-warning.hbs
  ui/app/components/token-expire-warning.js
Labels: ui, bug, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25340 Backport of UI: Redirect after logging in from token expiry into release/1.16.x
  changelog/25335.txt
  ui/app/components/token-expire-warning.hbs
  ui/app/components/token-expire-warning.js
Labels: ui, backport, hashicorp-contributed-pr

#25336 Transit: Release locks using defer statements
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_decrypt.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_rewrap.go
  builtin/logical/transit/path_sign_verify.go
  changelog/25336.txt
Labels: bug, secret/transit, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25339 Backport of UI: Redirect after logging in from token expiry into release/1.15.x
  changelog/25335.txt
  ui/app/components/token-expire-warning.hbs
  ui/app/components/token-expire-warning.js
Labels: ui, backport, hashicorp-contributed-pr

#25345 Backport UI: Redirect after logging in from token expiry (#25335)
  changelog/25335.txt
  ui/app/components/token-expire-warning.js
  ui/app/templates/components/token-expire-warning.hbs
Labels: ui, backport, hashicorp-contributed-pr

#25342 Backport of Transit: Release locks using defer statements into release/1.14.x
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_decrypt.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_rewrap.go
  builtin/logical/transit/path_sign_verify.go
  changelog/25336.txt
Labels: backport, hashicorp-contributed-pr

#25343 Backport of Transit: Release locks using defer statements into release/1.15.x
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_decrypt.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_rewrap.go
  builtin/logical/transit/path_sign_verify.go
  changelog/25336.txt
Labels: backport, hashicorp-contributed-pr

#25344 Backport of Transit: Release locks using defer statements into release/1.16.x
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_decrypt.go
  builtin/logical/transit/path_encrypt.go
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_rewrap.go
  builtin/logical/transit/path_sign_verify.go
  changelog/25336.txt
Labels: backport, hashicorp-contributed-pr

#25334 Hide Sync Destination Actions When Purging
  ui/app/models/sync/destination.js
  ui/lib/sync/addon/routes/secrets/destinations/destination.ts
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/integration/components/sync/secrets/destination-header-test.js
  ui/types/vault/models/sync/destination.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25348 Backport of Hide Sync Destination Actions When Purging into release/1.16.x
  ui/app/models/sync/destination.js
  ui/lib/sync/addon/routes/secrets/destinations/destination.ts
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/integration/components/sync/secrets/destination-header-test.js
  ui/types/vault/models/sync/destination.d.ts
Labels: ui, hashicorp-contributed-pr

#25347 remove regular expression comparison in a GHA script
  .github/scripts/changed-files.sh
Labels: backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25313 UI: Add acceptance tests
  ui/lib/config-ui/addon/components/messages/page/create-and-edit.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit.js
  ui/lib/config-ui/addon/templates/messages/create.hbs
  ui/lib/config-ui/addon/templates/messages/message/edit.hbs
  ui/tests/acceptance/config-ui/messages/messages-test.js
  ui/tests/acceptance/config-ui/messages/messages-unauth-auth-test.js
  ui/tests/acceptance/custom-messages-auth-test.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25353 Backport of UI: Add acceptance tests into release/1.16.x
  ui/lib/config-ui/addon/components/messages/page/create-and-edit.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit.js
  ui/lib/config-ui/addon/templates/messages/create.hbs
  ui/lib/config-ui/addon/templates/messages/message/edit.hbs
  ui/tests/acceptance/config-ui/messages/messages-test.js
  ui/tests/acceptance/config-ui/messages/messages-unauth-auth-test.js
  ui/tests/acceptance/custom-messages-auth-test.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-test.js
Labels: hashicorp-contributed-pr

#25349 UI: Reauth banner at top of page
  ui/app/components/app-footer.hbs
  ui/app/styles/helper-classes/layout.scss
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25352 Backport of remove regular expression comparison in a GHA script into release/1.16.x
  .github/scripts/changed-files.sh
Labels: hashicorp-contributed-pr

#25355 Backport of UI: Reauth banner at top of page into release/1.16.x
  ui/app/components/app-footer.hbs
  ui/app/styles/helper-classes/layout.scss
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25356 ci: fix notification, step summary, and comment
  .github/scripts/report-ci-status.sh
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25362 Backport of ci: fix notification, step summary, and comment into release/1.16.x
  .github/scripts/report-ci-status.sh
  .github/workflows/build.yml
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25363 A couple build focused dependency bumps
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25368 Rollback couchbase/gocb/v2 to v2.6.5 for 386 compat
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, build/all, backport/1.16.x

#25370 ci: namespace data race logs
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25371 Backport of ci: namespace data race logs into release/1.16.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25369 Backport of Rollback couchbase/gocb/v2 to v2.6.5 for 386 compat into release/1.16.x
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25372 build: use the version with metadata in our metadata file
  .github/actions/metadata/action.yml
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25373 Backport of build: use the version with metadata in our metadata file into release/1.16.x
  .github/actions/metadata/action.yml
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25376 build: allow building all artifacts with empty pull requests
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25377 Backport of build: allow building all artifacts with empty pull requests into release/1.16.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25382 Fix raft tests so they don't capture the parent's t
  physical/raft/raft_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24990 fix plugin register cli error on unfound oci images
  changelog/24990.txt
  vault/logical_system.go
  vault/logical_system_test.go
  vault/plugincatalog/plugin_catalog.go
  vault/plugincatalog/plugin_catalog_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25387 VAULT-528 Fix Vault Agent being unable to render secrets with delete_version_after set.
  changelog/25387.txt
  command/agent_test.go
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25295 UI: glimmerize services
  ui/app/services/namespace.js
  ui/app/services/permissions.js
  ui/tests/unit/adapters/capabilities-test.js
  ui/tests/unit/adapters/permissions-test.js
  ui/types/vault/services/auth.d.ts
  ui/types/vault/services/namespace.d.ts
  ui/types/vault/services/permissions.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr
