Repository hashicorp/vault, pull requests merged in 2024-01, with the labels that each got.

#24645 UI: [VAULT-21435] Message details
  ui/app/serializers/config-ui/message.js
  ui/lib/config-ui/addon/components/messages/page/details.hbs
  ui/lib/config-ui/addon/components/messages/page/details.js
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/config-ui/addon/routes/messages/message/details.js
  ui/lib/config-ui/addon/templates/messages/message/details.hbs
  ui/tests/integration/components/config-ui/messages/page/details-test.js
  ui/tests/integration/components/config-ui/messages/page/list-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24632 Add KVv2 known issue to release notes
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/kv2-url-change.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24655 Backport of Add KVv2 known issue to release notes into release/1.15.x
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/kv2-url-change.mdx
Labels: hashicorp-contributed-pr

#24368 [DO NOT MERGE UNTIL EOY] update year in LICENSE and copywrite files
  .copywrite.hcl
  LICENSE
  api/.copywrite.hcl
  scripts/copywrite-exceptions.sh
  sdk/.copywrite.hcl
  sdk/logical/audit_test.go
  sdk/logical/request_test.go
  shamir/.copywrite.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24642 docs(web repl): add initial docs about the UI REPL
  ui/app/templates/components/console/log-help.hbs
  ui/app/templates/components/console/ui-panel.hbs
  ui/app/templates/components/wizard/secrets-list.hbs
  ui/tests/integration/components/secret-edit-test.js
  website/content/docs/commands/web.mdx
  website/content/docs/configuration/ui.mdx
  website/data/docs-nav-data.json
Labels: ui, docs, pr/no-changelog, hashicorp-contributed-pr

#24659 make fmt
  api/secret_test.go
  sdk/helper/testcluster/consts.go
  sdk/helper/testcluster/replication.go
  sdk/helper/testhelpers/output.go
  sdk/helper/testhelpers/output_test.go
  sdk/logical/events_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24658 Move pkcs7 fork into a shared location
  .copywrite.hcl
  builtin/credential/aws/path_login.go
  helper/pkcs7/LICENSE
  helper/pkcs7/README.md
  helper/pkcs7/ber.go
  helper/pkcs7/ber_test.go
  helper/pkcs7/decrypt.go
  helper/pkcs7/decrypt_test.go
  helper/pkcs7/encrypt.go
  helper/pkcs7/encrypt_test.go
  helper/pkcs7/pkcs7.go
  helper/pkcs7/pkcs7_test.go
  helper/pkcs7/sign.go
  helper/pkcs7/sign_test.go
  helper/pkcs7/verify.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24663 Sync Destination Transition Bug
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
  ui/tests/acceptance/sync/secrets/destination-test.js
Labels: ui, bug, pr/no-changelog, hashicorp-contributed-pr

#24661 UI: Delete empty file thats causing ui linting errors
  ui/app/templates/components/backend-configure.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24664 UI: Delete empty file thats causing ui linter errors
  ui/app/templates/components/backend-configure.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24548 VAULT-22552: Add MaxConnsPerHost field to Agent template_config
  changelog/24548.txt
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template_config.hcl
  command/agent/internal/ctmanager/runner_config.go
  command/agent_generate_config.go
  command/agent_generate_config_test.go
  go.mod
  go.sum
  website/content/docs/agent-and-proxy/agent/generate-config/index.mdx
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
  website/content/docs/agent-and-proxy/agent/template.mdx
Labels: hashicorp-contributed-pr

#24402 VAULT-8790 Ensure time.NewTicker never gets called with a negative value
  builtin/logical/database/rotation.go
  builtin/logical/database/rotation_test.go
  command/agentproxyshared/auth/alicloud/alicloud.go
  command/agentproxyshared/auth/aws/aws.go
  command/agentproxyshared/auth/ldap/ldap.go
  vault/core.go
  vault/request_forwarding.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24653 Update namespace-picker.js
  ui/app/components/namespace-picker.js
Labels: pr/no-changelog

#24667 VAULT-17292 CE portion of changes
  changelog/24667.txt
  command/agent.go
  command/agent/config/config.go
  command/agentproxyshared/auth/auth.go
  command/agentproxyshared/cache/api_proxy.go
  command/proxy.go
  command/proxy/config/config.go
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/autoauth/index.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
Labels: hashicorp-contributed-pr

#24668 Refactor auto-auth backoff to helper package.
  command/agentproxyshared/auth/auth.go
  command/agentproxyshared/auth/auth_test.go
  sdk/helper/backoff/backoff.go
  sdk/helper/backoff/backoff_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24564 add token_reviewer_jwt_set to resp data on config read api doc example
  website/content/api-docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#24644 Secrets Sync UI: Bug fixes part 3
  ui/app/models/sync/destinations/azure-kv.js
  ui/lib/core/addon/helpers/sync-destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/routes/secrets/destinations/index.ts
  ui/mirage/factories/sync-destination.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
  ui/types/vault/app-types.ts
  ui/types/vault/route.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24671 Rename secret sync association to secret syncs in activity log
  vault/activity/query.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24680 Backport of Rename secret sync association to secret syncs in activity log into release/1.15.x
  vault/activity/query.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
Labels: hashicorp-contributed-pr

#24586 [VAULT-22641] Include secret sync associations with hyperloglog estimations
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24681 Backport of [VAULT-22641] Include secret sync associations with hyperloglog estimations into release/1.15.x
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: hashicorp-contributed-pr

#24676 Fix pluralization error in ACME entity assignment doc
  website/content/docs/concepts/client-count/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24684 Backport of Fix pluralization error in ACME entity assignment doc into release/1.14.x
  website/content/docs/concepts/client-count/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24679 UI: remove keyvauluri from credentials section
  ui/app/models/sync/destinations/azure-kv.js
  ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24688 Backport of Fix UI when editing database roles into release/1.14.x
  changelog/24660.txt
  ui/app/adapters/database/role.js
  ui/app/components/database-role-edit.js
Labels: ui, backport, hashicorp-contributed-pr

#24689 Backport of Fix UI when editing database roles into release/1.15.x
  changelog/24660.txt
  ui/app/adapters/database/role.js
  ui/app/components/database-role-edit.js
Labels: ui, backport, hashicorp-contributed-pr

#24626 VAULT-21608: Endpoints to Retrieve Active Pre- and Post- Login Messages
  vault/core.go
  vault/custom_messages_manager.go
  vault/logical_system.go
  vault/logical_system_custom_messages.go
  vault/logical_system_custom_messages_test.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  vault/ui_custom_messages/manager.go
  vault/ui_custom_messages/manager_test.go
  vault/ui_custom_messages/namespace.go
  vault/ui_custom_messages/namespace_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24686 UI: fix PKI issuer capabilities
  changelog/24686.txt
  ui/app/models/pki/issuer.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/acceptance/policies-acl-old-test.js
  ui/tests/helpers/pki/pki-run-commands.js
Labels: ui, bug, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24665 UI: VAULT-21538 unauth endpoint message display
  ui/app/controllers/vault/cluster/auth.js
  ui/app/serializers/config-ui/message.js
  ui/app/services/custom-messages.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs
  ui/mirage/handlers/custom-messages.js
  ui/tests/acceptance/custom-messages-auth-test.js
  ui/tests/helpers/config-ui/message-selectors.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-message-test.js
  ui/tests/integration/components/mfa-login-enforcement-form-test.js
  ui/tests/unit/serializers/config-ui/message-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24693 Secrets Sync UI: Small UX copy improvements
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/kv/package.json
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24599 add docs for configuring jwt validation pubkeys for vso
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24696 Backport of add docs for configuring jwt validation pubkeys for vso into release/1.15.x
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
Labels: hashicorp-contributed-pr

#24242 Documentation for Quotas in Admin Namespace
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/quotas-config.mdx
  website/content/api-docs/system/rate-limit-quotas.mdx
  website/content/partials/api/restricted-endpoints.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24695 Sync Destinations List Name Filter Updates
  ui/app/styles/helper-classes/typography.scss
  ui/lib/core/addon/components/search-select-placeholder.hbs
  ui/lib/sync/addon/components/secrets/page/destinations.hbs
  ui/lib/sync/addon/components/secrets/page/destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
  ui/lib/sync/addon/routes/secrets/destinations/destination/secrets.ts
  ui/lib/sync/addon/routes/secrets/destinations/index.ts
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/general-selectors.js
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24697 UI: Changes jwks_ca_pem param to a 'file' edit type
  changelog/24697.txt
  ui/app/models/auth-config/jwt.js
Labels: ui, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24701 Backport of UI: Changes jwks_ca_pem param to a 'file' edit type into release/1.15.x
  changelog/24697.txt
  ui/app/models/auth-config/jwt.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24700 Backport of UI: Changes jwks_ca_pem param to a 'file' edit type into release/1.14.x
  changelog/24697.txt
  ui/app/models/auth-config/jwt.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24699 Backport of UI: Changes jwks_ca_pem param to a 'file' edit type into release/1.13.x
  changelog/24697.txt
  ui/app/models/auth-config/jwt.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24512 Support reloading database plugins across multiple mounts
  builtin/logical/database/backend_test.go
  builtin/logical/database/versioning_large_test.go
  builtin/plugin/backend_test.go
  changelog/24512.txt
  http/plugin_test.go
  vault/external_tests/plugin/plugin_test.go
  vault/logical_system.go
  vault/mount.go
  vault/plugin_reload.go
Labels: core/plugin, hashicorp-contributed-pr

#24583 [VAULT-22480] Add audit fallback device
  audit/types.go
  builtin/audit/file/backend.go
  builtin/audit/file/backend_test.go
  builtin/audit/socket/backend.go
  builtin/audit/socket/backend_test.go
  builtin/audit/syslog/backend.go
  builtin/audit/syslog/backend_test.go
  helper/testhelpers/corehelpers/corehelpers.go
  vault/audit.go
  vault/audit_broker.go
  vault/audit_broker_test.go
  vault/audit_test.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#24706 Backport UI: fix PKI issuer capabilities (#24686)
  changelog/24686.txt
  ui/app/models/pki/issuer.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/acceptance/policies-acl-old-test.js
  ui/tests/helpers/pki/pki-run-commands.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24669 ui: add ember exam
  ui/package.json
  ui/scripts/start-vault.js
  ui/testem.js
  ui/tests/acceptance/console-test.js
  ui/tests/acceptance/oidc-config/clients-assignments-test.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-create-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-version-history-paths-test.js
  ui/tests/acceptance/unseal-test.js
  ui/tests/helpers/control-groups.js
  ui/tests/integration/components/info-table-row-test.js
  ui/tests/test-helper.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24711 Add -type -f to the -find delete call as part of test collect reports
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23750 Upgrade go-msgpack to v2 2.1.1
  go.mod
  go.sum
  physical/raft/msgpack.go
  physical/raft/raft.go
  vault/cluster/cluster.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24705 Backport UI: fix PKI issuer capabilities
  changelog/24686.txt
  ui/app/models/pki/issuer.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/acceptance/policies-acl-old-test.js
  ui/tests/helpers/pki/pki-run-commands.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#18513 Fixed Oauth redirect not working on Android Chrome
  changelog/18513.txt
  ui/app/routes/vault/cluster/oidc-provider.js
  ui/app/templates/vault/cluster/oidc-provider.hbs
  ui/tests/acceptance/oidc-provider-test.js
Labels: ui, identity/oidc, backport/1.13.x, backport/1.14.x, backport/1.15.x

#24694 UI: Date time local transform
  ui/app/models/config-ui/message.js
  ui/app/serializers/config-ui/message.js
  ui/app/services/custom-messages.js
  ui/app/transforms/date-time-local.js
  ui/tests/unit/transforms/date-time-local-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24712 Prep ember data: relationships
  ui/app/models/control-group.js
  ui/app/models/identity/entity-alias.js
  ui/app/models/identity/entity.js
  ui/app/models/identity/group.js
  ui/app/models/kmip/ca.js
  ui/app/models/kmip/config.js
  ui/app/models/mfa-login-enforcement.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24715 Backport of Fixed Oauth redirect not working on Android Chrome into release/1.15.x
  changelog/18513.txt
  ui/app/routes/vault/cluster/oidc-provider.js
  ui/app/templates/vault/cluster/oidc-provider.hbs
  ui/tests/acceptance/oidc-provider-test.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24714 Backport of Fixed Oauth redirect not working on Android Chrome into release/1.14.x
  changelog/18513.txt
  ui/app/routes/vault/cluster/oidc-provider.js
  ui/app/templates/vault/cluster/oidc-provider.hbs
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/oidc-provider-test.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24235 VAULT-21944: add documentation for thousands of namespaces
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/docs/enterprise/namespaces/namespace-limits.mdx
  website/content/docs/internals/limits.mdx
  website/content/partials/namespace-limits.mdx
  website/content/partials/storage-entry-size.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24683 Documentation: WAF: New lease explosions overview
  website/content/docs/concepts/lease-explosions.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/data/docs-nav-data.json
Labels: docs, docs/learn, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, WAF

#24729 Make the TestRaft_Snapshot_API "rotate" tests use TCP networking again
  vault/external_tests/raft/raft_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24723 Backport of VAULT-21944: add documentation for thousands of namespaces into release/1.15.x
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/docs/enterprise/namespaces/namespace-limits.mdx
  website/content/docs/internals/limits.mdx
  website/content/partials/namespace-limits.mdx
  website/content/partials/storage-entry-size.mdx
  website/data/docs-nav-data.json
Labels: docs, hashicorp-contributed-pr

#24727 Unset VAULT_ADDR before invoking gotestsum
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24106 Sample payload is empty for AWS auth login request in API docs
  website/content/api-docs/auth/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.15.x

#24730 Backport of Sample payload is empty for AWS auth login request in API docs into release/1.15.x
  website/content/api-docs/auth/aws.mdx
Labels: hashicorp-contributed-pr

#23887 Docs update with known issue
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/partials/known-issues/user-lockout-logging.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24713 Backport of Fixed Oauth redirect not working on Android Chrome into release/1.13.x
  changelog/18513.txt
  ui/app/routes/vault/cluster/oidc-provider.js
  ui/app/templates/vault/cluster/oidc-provider.hbs
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/oidc-provider-test.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24709 Prep ember data: ids
  ui/app/adapters/named-path.js
  ui/app/adapters/pki/tidy.js
  ui/app/adapters/secrets-engine-path.js
  ui/app/adapters/sync/destination.js
  ui/tests/integration/components/mfa/method-form-test.js
  ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
  ui/tests/integration/components/pki/pki-import-pem-bundle-test.js
  ui/tests/integration/components/pki/pki-issuer-cross-sign-test.js
  ui/tests/integration/components/pki/pki-key-form-test.js
  ui/tests/integration/components/pki/pki-tidy-form-test.js
  ui/tests/unit/adapters/ldap/role-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24734 Backport UI: fix PKI issuer capabilities (#24686)
  changelog/24686.txt
  ui/app/models/pki/issuer.js
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/helpers/pki/pki-run-commands.js
Labels: ui, backport, bug, hashicorp-contributed-pr

#24743 Backport of Bump the `node` version into release/1.14.x
  website/.nvmrc
  website/package-lock.json
  website/package.json
Labels: hashicorp-contributed-pr

#19649 Update configuration.mdx
  website/content/docs/platform/servicenow/configuration.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x

#24745 Backport of Bump the `node` version into release/1.15.x
  website/.nvmrc
  website/package-lock.json
  website/package.json
Labels: hashicorp-contributed-pr

#24737 Backport lockout logging issue to 1.15
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/partials/known-issues/user-lockout-logging.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24736 Backport lockout logging issue for 1.14
  website/content/docs/release-notes/1.14.0.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/partials/known-issues/user-lockout-logging.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24748 Audit Broker: Log Response should always assign the multierror before returning from it.
  vault/audit_broker.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#24747 Backport of Bump the `node` version into release/1.13.x
  website/.nvmrc
  website/package-lock.json
  website/package.json
Labels: hashicorp-contributed-pr

#24751 Manual Backport of Bump the node version into release/1.12.x
  website/.nvmrc
  website/package-lock.json
  website/package.json
Labels: hashicorp-contributed-pr

#24733 Client Count Routing Updates
  ui/app/app.js
  ui/app/components/clients/page/token.hbs
  ui/app/components/clients/page/token.js
  ui/app/router.js
  ui/app/routes/vault/cluster/clients/base.js
  ui/app/routes/vault/cluster/clients/index.js
  ui/app/routes/vault/cluster/clients/overview.js
  ui/app/routes/vault/cluster/clients/sync.js
  ui/app/routes/vault/cluster/clients/token.js
  ui/app/templates/components/dashboard/client-count-card.hbs
  ui/app/templates/vault/cluster/clients.hbs
  ui/app/templates/vault/cluster/clients/overview.hbs
  ui/app/templates/vault/cluster/clients/sync.hbs
  ui/app/templates/vault/cluster/clients/token.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/engine.js
  ui/tests/acceptance/clients/token-test.js
  ui/tests/helpers/clients.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24749 Prep for ember data: misc
  ui/app/lib/attach-capabilities.js
  ui/app/models/pki/certificate/base.js
  ui/app/routes/vault.js
  ui/app/serializers/database/connection.js
  ui/lib/pki/addon/decorators/check-issuers.js
  ui/lib/pki/addon/routes/certificates/index.js
  ui/lib/pki/addon/routes/configuration/index.js
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/overview.js
  ui/lib/pki/addon/routes/roles/index.js
  ui/lib/pki/addon/routes/tidy.js
  ui/package.json
  ui/tests/acceptance/oidc-provider-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24753 Backport of Add -type -f to the -find delete call as part of test collect reports into release/1.15.x
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#24755 Manual backport for deleting only files
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24720 Docs: Small doc fix for vercel project
  website/content/api-docs/system/secrets-sync.mdx
Labels: docs, hashicorp-contributed-pr, backport/1.15.x

#24756 Flaky Tests from lastLogOutput Error
  ui/tests/pages/components/console/ui-panel.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24719 Secrets Sync UI: Small bug fixes from more QA
  ui/app/models/sync/destination.js
  ui/app/models/sync/destinations/azure-kv.js
  ui/lib/core/addon/components/text-file.hbs
  ui/lib/core/addon/helpers/sync-destinations.ts
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#24765 Fix some GHAs not running on enterprise
  .github/workflows/milestone-checker.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24767 Docs/cherrypick waf 183 vault guard against lease explosion
  website/content/docs/concepts/lease-explosions.mdx
  website/data/docs-nav-data.json
Labels: backport, docs, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#24744 Vault 22857/add rotate aws poc
  builtin/credential/ldap/backend.go
  builtin/logical/aws/backend.go
  builtin/logical/aws/path_config_rotate_root.go
Labels: hashicorp-contributed-pr

#24770 Docs/lease explosions update
  website/content/docs/concepts/lease-explosions.mdx
Labels: backport, docs, pr/no-changelog, backport/1.9.x, backport/1.8.x, backport/1.10.x, backport/1.11.x, backport/1.12.x, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr

#24704 VAULT-22482: New audit metrics
  audit/entry_filter_test.go
  audit/sink_metric_labeler.go
  audit/sink_metric_labeler_test.go
  audit/sink_metric_timer.go
  audit/sink_metric_timer_test.go
  audit/sink_wrapper.go
  builtin/audit/file/backend.go
  builtin/audit/file/backend_test.go
  builtin/audit/socket/backend.go
  builtin/audit/socket/backend_test.go
  builtin/audit/syslog/backend.go
  builtin/audit/syslog/backend_test.go
  internal/observability/event/node_metrics_counter.go
  internal/observability/event/node_metrics_counter_test.go
  vault/audit_broker.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#24778 Backport of Bump google.golang.org/grpc from 1.56.2 to 1.56.3 in /vault/hcp_link/proto into release/1.15.x
  vault/hcp_link/proto/go.mod
  vault/hcp_link/proto/go.sum
Labels: hashicorp-contributed-pr

#24785 Backport of Bump github.com/dvsekhvalnov/jose2go from 1.5.0 to 1.6.0 into release/1.15.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#24787 Backport of Bump github.com/dvsekhvalnov/jose2go from 1.5.0 to 1.6.0 into release/1.14.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#24793 Backport dependabot
  vault/hcp_link/proto/go.mod
  vault/hcp_link/proto/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24794 scripts: support bash 3 in scripts
  scripts/go-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24795 Dependabot backport crypto 0.17 in sdk
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24796 Backport crypto 0.17 upversion to 1.14
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24798 Backport cloudflare/circl update to 1.14
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24800 Dependabot backport of crypto 0.17 update in /api to release/1.15.x
  api/go.mod
  api/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24799 Dependabot backport api crypto update to 0.17 to release/1.14
  api/go.mod
  api/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24789 Backport of Bump github.com/cloudflare/circl from 1.3.3 to 1.3.7 into release/1.15.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#24803 Dependabot update containerd for 1.15
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24802 Dependabot update containerd for 1.14
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24762 actions: upload go test logs as a tarball
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24797 Backport of scripts: support bash 3 in scripts into release/1.15.x
  scripts/go-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24806 Backport of actions: upload go test logs as a tarball into release/1.15.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24805 Backport of actions: upload go test logs as a tarball into release/1.14.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24804 Backport of actions: upload go test logs as a tarball into release/1.13.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24766 UI: Make userpass reset test more robust
  ui/app/services/auth.js
  ui/tests/acceptance/redirect-to-test.js
  ui/tests/acceptance/reset-password-test.js
  ui/tests/acceptance/wrapped-token-test.js
  ui/tests/pages/auth.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24742 UI: multiple banner message on create and edit form
  ui/app/serializers/config-ui/message.js
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.hbs
  ui/lib/config-ui/addon/components/messages/page/create-and-edit-message-form.js
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/config-ui/addon/routes/messages/create.js
  ui/lib/config-ui/addon/routes/messages/index.js
  ui/lib/config-ui/addon/routes/messages/message/edit.js
  ui/lib/config-ui/addon/templates/messages/create.hbs
  ui/lib/config-ui/addon/templates/messages/message/edit.hbs
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-message-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24792 [docs] Update docs for VSO release 0.4.3
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24808 Backport of [docs] Update docs for VSO release 0.4.3 into release/1.15.x
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24757 Backport of Docs: Small doc fix for vercel project into release/1.15.x
  website/content/api-docs/system/secrets-sync.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#24761 Secrets Sync UI: Add purge delete progress and error banner to destination header
  ui/app/models/sync/destination.js
  ui/app/serializers/sync/destination.js
  ui/lib/kv/addon/components/page/secret/details.hbs
  ui/lib/sync/addon/components/secrets/destination-header.hbs
  ui/lib/sync/addon/components/secrets/destination-header.ts
  ui/lib/sync/addon/components/secrets/page/destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
  ui/mirage/factories/sync-destination.js
  ui/mirage/handlers/sync.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/destination-header-test.js
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24764 VAULT-23050: Remove undocumented feature flag to disable audit eventlogger
  audit/types.go
  builtin/audit/file/backend.go
  builtin/audit/file/backend_test.go
  builtin/audit/socket/backend.go
  builtin/audit/socket/backend_test.go
  builtin/audit/syslog/backend.go
  builtin/audit/syslog/backend_test.go
  helper/testhelpers/corehelpers/corehelpers.go
  http/logical_test.go
  vault/audit.go
  vault/audit_broker.go
  vault/audit_broker_test.go
  vault/audit_test.go
  vault/core.go
  vault/core_test.go
  vault/external_tests/identity/login_mfa_totp_test.go
  vault/ha.go
  vault/request_handling.go
  vault/wrapping.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr

#24746 Backport of Update configuration.mdx into release/1.13.x
  website/content/docs/platform/servicenow/configuration.mdx
Labels: hashicorp-contributed-pr

#24807 UI: unseal tests used mocked endpoints
  ui/app/templates/vault/cluster/unseal.hbs
  ui/tests/acceptance/reduced-disclosure-test.js
  ui/tests/acceptance/unseal-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24812 CE Update of vault-action from 2.5 to 2.74
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24814 Backport of CE Update of vault-action from 2.5 to 2.74 into release/1.14.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24815 VAULT-21608: Make Namespace Manager a Field in the Manager Structure
  vault/core.go
  vault/core_util.go
  vault/ui_custom_messages/manager.go
  vault/ui_custom_messages/manager_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24820 Run archive test logs always
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24818 Add WriteRaw to client api and new PKI test helper
  api/logical.go
  builtin/logical/pki/test_helpers.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24821 Backport of Run archive test logs always into release/1.15.x
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#24791 Prep for Ember data: misc #2
  ui/app/utils/error-message.js
  ui/mirage/handlers/base.js
  ui/tests/acceptance/auth-list-test.js
  ui/tests/acceptance/dashboard-test.js
  ui/tests/acceptance/policies-acl-old-test.js
  ui/tests/acceptance/policies/index-test.js
  ui/tests/pages/components/console/ui-panel.js
  ui/tests/pages/policies/create.js
  ui/tests/pages/policies/index.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24822 Backport of Run archive test logs always into release/1.14.x
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#24816 update /sys/leader api docs
  website/content/api-docs/system/leader.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24824 Backport of update /sys/leader api docs into release/1.15.x
  website/content/api-docs/system/leader.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24825 Fix build failures sometimes showing as success when failures happened
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24826 UI: make user reset password test less flakey
  ui/tests/acceptance/reset-password-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#24823 UI: Update flight icons
  changelog/24823.txt
  ui/app/components/mount-backend/type-form.hbs
  ui/app/controllers/vault/cluster/access/mfa/methods/create.js
  ui/app/helpers/mountable-auth-methods.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/auth-method.js
  ui/app/models/mfa-method.js
  ui/app/models/role-jwt.js
  ui/app/models/secret-engine.js
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/app/templates/components/mount-backend-form.hbs
  ui/app/templates/components/wizard/features-selection.hbs
  ui/app/templates/components/wizard/init-login.hbs
  ui/app/templates/components/wizard/init-save-keys.hbs
  ui/app/templates/components/wizard/init-setup.hbs
  ui/app/templates/components/wizard/init-unseal.hbs
  ui/app/templates/components/wizard/mounts-wizard.hbs
  ui/app/templates/components/wizard/policies-create.hbs
  ui/app/templates/components/wizard/policies-delete.hbs
  ui/app/templates/components/wizard/policies-details.hbs
  ui/app/templates/components/wizard/policies-intro.hbs
  ui/app/templates/components/wizard/policies-others.hbs
  ui/app/templates/components/wizard/replication-setup.hbs
  ui/app/templates/components/wizard/tools-info.hbs
  ui/app/templates/components/wizard/tools-lookup.hbs
  ui/app/templates/components/wizard/tools-rewrap.hbs
  ui/app/templates/components/wizard/tools-rewrapped.hbs
  ui/app/templates/components/wizard/tools-unwrap.hbs
  ui/app/templates/components/wizard/tools-unwrapped.hbs
  ui/app/templates/components/wizard/tools-wrap.hbs
  ui/app/templates/components/wizard/tools-wrapped.hbs
  ui/app/templates/components/wizard/tutorial-complete.hbs
  ui/app/templates/components/wizard/tutorial-idle.hbs
  ui/app/templates/components/wizard/tutorial-paused.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/create.hbs
  ui/app/templates/vault/cluster/access/mfa/methods/method/index.hbs
  ui/ember-cli-build.js
  ui/lib/core/addon/components/icon.hbs
  ui/lib/core/addon/components/icon.js
  ui/lib/kmip/addon/components/operation-field-display.js
  ui/lib/kmip/addon/templates/components/header-scope.hbs
  ui/lib/kmip/addon/templates/components/operation-field-display.hbs
  ui/lib/kmip/addon/templates/configure.hbs
  ui/lib/kv/addon/components/kv-page-header.hbs
  ui/lib/pki/addon/components/page/pki-tidy-auto-configure.hbs
  ui/lib/pki/addon/components/page/pki-tidy-manual.hbs
  ui/package.json
  ui/tests/integration/components/confirm-action-test.js
  ui/tests/integration/components/dashboard/secrets-engines-card-test.js
  ui/tests/integration/components/icon-test.js
  ui/tests/integration/components/kubernetes/page/configuration-test.js
  ui/tests/integration/components/kubernetes/page/roles-test.js
  ui/tests/integration/components/kubernetes/tab-page-header-test.js
  ui/tests/integration/components/kv/kv-page-header-test.js
  ui/tests/integration/components/pki/pki-page-header-test.js
  ui/tests/integration/components/replication-secondary-card-test.js
  ui/tests/unit/models/role-jwt-test.js
  ui/tests/unit/models/secret-engine-test.js
  ui/yarn.lock
Labels: ui, hashicorp-contributed-pr

#24763 Update index.mdx
  website/content/docs/configuration/index.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24827 Backport of Update index.mdx into release/1.13.x
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#24828 Backport of Update index.mdx into release/1.14.x
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#24829 Backport of Update index.mdx into release/1.15.x
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#24811 audit: entry_formatter update to ensure no race detection issues
  audit/entry_formatter.go
  audit/entry_formatter_test.go
  sdk/logical/audit.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24835 [DOCS] Fix page heading
  website/content/docs/auth/jwt/oidc-providers/auth0.mdx
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
  website/content/docs/auth/jwt/oidc-providers/forgerock.mdx
  website/content/docs/auth/jwt/oidc-providers/gitlab.mdx
  website/content/docs/auth/jwt/oidc-providers/google.mdx
  website/content/docs/auth/jwt/oidc-providers/ibmisam.mdx
  website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/auth/jwt/oidc-providers/okta.mdx
  website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
  website/content/docs/internals/architecture.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24841 Backport of [DOCS] Fix page heading into release/1.15.x
  website/content/docs/auth/jwt/oidc-providers/auth0.mdx
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
  website/content/docs/auth/jwt/oidc-providers/forgerock.mdx
  website/content/docs/auth/jwt/oidc-providers/gitlab.mdx
  website/content/docs/auth/jwt/oidc-providers/google.mdx
  website/content/docs/auth/jwt/oidc-providers/ibmisam.mdx
  website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/auth/jwt/oidc-providers/okta.mdx
  website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
  website/content/docs/internals/architecture.mdx
Labels: hashicorp-contributed-pr

#24840 Backport of [DOCS] Fix page heading into release/1.14.x
  website/content/docs/auth/jwt/oidc-providers/auth0.mdx
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
  website/content/docs/auth/jwt/oidc-providers/forgerock.mdx
  website/content/docs/auth/jwt/oidc-providers/gitlab.mdx
  website/content/docs/auth/jwt/oidc-providers/google.mdx
  website/content/docs/auth/jwt/oidc-providers/ibmisam.mdx
  website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/auth/jwt/oidc-providers/okta.mdx
  website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
  website/content/docs/internals/architecture.mdx
Labels: hashicorp-contributed-pr

#24843 Copy the Connection reference within LogInput Clone()
  sdk/logical/audit.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24844 Backport of Copy the Connection reference within LogInput Clone() into release/1.15.x
  sdk/logical/audit.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24847 Census manual reporting : Always enable manual reporting CE changes
  vault/activity_log.go
  vault/activity_log_test.go
  vault/census.go
  vault/logical_system_activity.go
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#24710 VAULT-22642: Include secret syncs in activity log responses
  changelog/24710.txt
  vault/activity/query.go
  vault/activity_log.go
  vault/activity_log_util_common.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr, backport/1.15.x

#24855 Backport of VAULT-22642: Include secret syncs in activity log responses into release/1.15.x
  changelog/24710.txt
  vault/activity/query.go
  vault/activity_log.go
  vault/activity_log_util_common.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr

#24856 Make TestOIDC_PeriodicFunc less flaky.
  vault/identity_store_oidc_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24859 Backport of Bump actions/github-script from 6.4.1 to 7.0.1 into release/1.14.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24861 Backport of Bump actions/setup-node from 3.7.0 to 4.0.1 into release/1.15.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24860 Backport of Bump actions/setup-node from 3.7.0 to 4.0.1 into release/1.14.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24858 Backport of Bump actions/github-script from 6.4.1 to 7.0.1 into release/1.13.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24759 [VAULT-22506] External tests for audit filtering
  vault/external_tests/audit/audit_filtering_test.go
Labels: core/audit, test, pr/no-changelog, hashicorp-contributed-pr

#24857 Fix mount counts in activity log
  vault/activity_log.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24863 Backport of Fix mount counts in activity log into release/1.15.x
  vault/activity_log.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr

#24848 Add Validation for message Parameter in Create/Update Custom Message Operation
  vault/logical_system_custom_messages.go
  vault/logical_system_custom_messages_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24728 VAULT-22645: Support secret sync in AddActivityToFragment
  vault/activity_log.go
  vault/activity_log_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x

#24865 Backport of VAULT-22645: Support secret sync in AddActivityToFragment into release/1.15.x
  vault/activity_log.go
  vault/activity_log_test.go
Labels: hashicorp-contributed-pr

#24869 Backport of Bump test-summary/action from 2.1 to 2.2 into release/1.15.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24871 Backport of Bump browser-actions/setup-chrome from 1.2.0 to 1.4.0 into release/1.15.x
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24870 Backport of Bump browser-actions/setup-chrome from 1.2.0 to 1.4.0 into release/1.14.x
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24862 Backport of Bump actions/github-script from 6.4.1 to 7.0.1 into release/1.15.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24880 Fix docs link typos
  website/content/docs/secrets/identity/oidc-provider.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
