Repository hashicorp/vault, pull requests merged in 2024-11, with the labels that each got.

#28821 Transit: Allow ENT only arguments for sign/verify.
  builtin/logical/transit/path_sign_verify.go
  builtin/logical/transit/path_sign_verify_ce.go
  sdk/helper/keysutil/policy.go
  website/content/api-docs/secret/transit.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: ui, secret/transit, pr/no-changelog, hashicorp-contributed-pr

#28827 Backport of VAULT-30877: Repopulate AWS static creds queue in initialize into release/1.18.x
  builtin/logical/aws/backend.go
  builtin/logical/aws/path_static_creds.go
  builtin/logical/aws/path_static_creds_test.go
  builtin/logical/aws/path_static_roles.go
  builtin/logical/aws/rotation.go
  builtin/logical/aws/rotation_test.go
  changelog/28775.txt
  helper/testhelpers/testhelpers.go
  website/content/api-docs/secret/aws.mdx
Labels: hashicorp-contributed-pr

#28826 Add PKI issuer config fields to enable check disablement parameters
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/issuing/issuers.go
  builtin/logical/pki/issuing/issuers_oss.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_fetch_issuers_stubs_oss.go
  builtin/logical/pki/path_manage_issuers.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#28828 Backport of Fix: Add missing iam:TagUser permission into release/1.18.x
  website/content/docs/secrets/aws.mdx
Labels: hashicorp-contributed-pr

#28823 Update ServiceNow info
  website/content/docs/platform/servicenow/configuration.mdx
  website/public/img/service-now/vault-credential-resolver-fqcn.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28830 Backport of Update ServiceNow info into release/1.18.x
  website/content/docs/platform/servicenow/configuration.mdx
  website/public/img/service-now/vault-credential-resolver-fqcn.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28832 Fix bug setting PKI issuer enable_aia_url_templating to be set to false
  builtin/logical/pki/path_fetch_issuers.go
  changelog/28832.txt
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28839 Transit: fix race in the key update api responses
  builtin/logical/transit/path_keys.go
  changelog/28839.txt
Labels: secret/transit, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28840 Backport of Transit: fix race in the key update api responses into release/1.18.x
  builtin/logical/transit/path_keys.go
  changelog/28839.txt
Labels: backport, hashicorp-contributed-pr

#28838 Fail sign/verify apis when Ed25519ph/ctx arguments are provided on CE
  builtin/logical/transit/path_sign_verify.go
  builtin/logical/transit/path_sign_verify_ce.go
  builtin/logical/transit/path_sign_verify_test.go
  sdk/helper/keysutil/policy.go
  website/content/api-docs/secret/transit.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#28845 VAULT-31075 CE changes
  vault/core_metrics.go
  vault/core_metrics_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28848 Update vault-plugin-auth-azure to v0.19.2
  changelog/28848.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.18.x

#28850 Backport of Update vault-plugin-auth-azure to v0.19.2 into release/1.18.x
  changelog/28848.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#28837 VAULT-24466: Quotas and replication docs
  website/content/docs/concepts/resource-quotas.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28852 Backport of VAULT-24466: Quotas and replication docs into release/1.18.x
  website/content/docs/concepts/resource-quotas.mdx
Labels: hashicorp-contributed-pr

#28807 VAULT-31393: Return 500 for some gRPC errors during login on perf standbys
  changelog/28807.txt
  vault/request_handling.go
  vault/request_handling_test.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28854 Backport of VAULT-31393: Return 500 for some gRPC errors during login on perf standbys into release/1.18.x
  changelog/28807.txt
  vault/request_handling.go
  vault/request_handling_test.go
Labels: hashicorp-contributed-pr

#28855 Pull versioned golang images in Zlint testsuite to avoid pulling with latest
  builtin/logical/pkiext/zlint_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28843 [Docs] Add recommended patterns
  website/content/docs/auth/approle/approle-pattern.mdx
  website/content/docs/auth/approle/index.mdx
  website/content/docs/configuration/seal/seal-best-practices.mdx
  website/content/docs/configuration/seal/transit-best-practices.mdx
  website/content/docs/enterprise/namespaces/namespace-structure.mdx
  website/data/docs-nav-data.json
  website/public/img/approle-best-practices.png
  website/public/img/diagram_namespaces-for-org.png
  website/public/img/diagram_namespaces_bp.png
  website/public/img/diagram_namespaces_intro.png
  website/public/img/diagram_namespaces_kv-paths.png
  website/public/img/diagram_namespaces_paths.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28859 Backport of [Docs] Add recommended patterns into release/1.18.x
  website/content/docs/auth/approle/approle-pattern.mdx
  website/content/docs/auth/approle/index.mdx
  website/content/docs/configuration/seal/seal-best-practices.mdx
  website/content/docs/configuration/seal/transit-best-practices.mdx
  website/content/docs/enterprise/namespaces/namespace-structure.mdx
  website/data/docs-nav-data.json
  website/public/img/approle-best-practices.png
  website/public/img/diagram_namespaces-for-org.png
  website/public/img/diagram_namespaces_bp.png
  website/public/img/diagram_namespaces_intro.png
  website/public/img/diagram_namespaces_kv-paths.png
  website/public/img/diagram_namespaces_paths.png
Labels: hashicorp-contributed-pr

#28856 adding local clients to local fragments ce changes
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28860 [Docs] Update the AWS Marketplace link
  website/content/docs/platform/aws/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28861 Backport of [Docs] Update the AWS Marketplace link into release/1.18.x
  website/content/docs/platform/aws/index.mdx
Labels: hashicorp-contributed-pr

#28862 add fragment locks to GetActiveLocalFragment and GetActiveFragment
  vault/activity_log_testing_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28863 Update seal-ha.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
Labels: docs, backport/1.18.x

#28864 Backport of Update seal-ha.mdx into release/1.18.x
  website/content/docs/configuration/seal/seal-ha.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28822 Add identity_token_key to Azure and GCP secret engines
  changelog/28822.txt
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/secret-engine.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/secret-engine/policy-generator.ts
  ui/tests/integration/components/mount-backend-form-test.js
Labels: ui, hashicorp-contributed-pr

#28866 500 for grpc context canceled errors during login
  vault/request_handling.go
  vault/request_handling_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28868 Backport of 500 for grpc context canceled errors during login into release/1.18.x
  vault/request_handling.go
  vault/request_handling_test.go
Labels: hashicorp-contributed-pr

#28808 Solve cntrl+f issue on KVv2 JSON details and edit views
  changelog/28808.txt
  ui/app/templates/components/console/log-json.hbs
  ui/app/templates/components/control-group-success.hbs
  ui/lib/core/addon/components/json-editor.hbs
  ui/lib/core/addon/components/json-editor.js
  ui/lib/core/addon/modifiers/code-mirror.js
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/lib/kv/addon/components/kv-patch/subkeys-reveal.hbs
  ui/lib/kv/addon/components/kv-paths-card.hbs
  ui/lib/ldap/addon/components/page/library/details/accounts.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/json-editor-test.js
  ui/tests/integration/components/kv/kv-data-fields-test.js
  ui/tests/integration/components/kv/kv-patch/editor/form-test.js
  ui/tests/integration/components/kv/kv-patch/json-form-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
  ui/tests/integration/components/ldap/page/library/details/accounts-test.js
Labels: ui, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28849 Manual backport of Update Azure SDK logger variable in docs (#28622)
  website/content/docs/auth/azure.mdx
  website/content/docs/secrets/azure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28851 Docs update for vault-helm v0.29.0 and vault-k8s v1.5.0 releases
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28871 Backport of Docs update for vault-helm v0.29.0 and vault-k8s v1.5.0 releases into release/1.18.x
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28825 [Docs] update reference consul-helm url to consul-k8s
  changelog/28825.txt
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/run.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.18.x

#28872 Backport of [Docs] update reference consul-helm url to consul-k8s into release/1.18.x
  changelog/28825.txt
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/run.mdx
Labels: hashicorp-contributed-pr

#28867 Make identity store loading and alias merging deterministic
  changelog/28867.txt
  vault/identity_store_test.go
  vault/identity_store_util.go
  vault/identiy_store_test_stubs_oss.go
  vault/testing.go
Labels: hashicorp-contributed-pr

#28877 Move helper funcs out of tests to fix build errors
  vault/identity_store_test.go
  vault/identity_store_test_stubs_oss.go
  vault/identity_store_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28847 Add 1.19.x upgrade note around Transit API change for Ed25519ph signatures
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#28858 Product usage reporting docs
  changelog/28858.txt
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/reporting.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/data/docs-nav-data.json
Labels: docs, hashicorp-contributed-pr

#28886 Backport of VAULT-31075 CE changes into release/1.18.x
  vault/core_metrics.go
  vault/core_metrics_test.go
Labels: hashicorp-contributed-pr

#28887 Backport of Add steps from IBM Db2 tutorial into release/1.18.x
  website/content/docs/secrets/databases/db2.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28882 Add quickdev Make target
  Makefile
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28888 Docs: Update rotate encryption key command doc
  website/content/docs/commands/operator/rotate.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28889 Docs: remove link to archived tutorial
  website/content/docs/commands/operator/rekey.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28891 Backport of Docs: Update rotate encryption key command doc into release/1.18.x
  website/content/docs/commands/operator/rotate.mdx
Labels: hashicorp-contributed-pr

#28878 VAULT-32330: fix sanitize path function to account for backslashes
  changelog/28878.txt
  vault/logical_system.go
  vault/logical_system_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28898 Add notes within the documentation about the generate_key flag
  website/content/api-docs/system/managed-keys.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28899 Backport of Add notes within the documentation about the generate_key flag into release/1.18.x
  website/content/api-docs/system/managed-keys.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone

#28901 secrets/ssh: Return the allow_empty_principals field in read api
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_roles.go
  changelog/28901.txt
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28902 Backport of secrets/ssh: Return the allow_empty_principals field in read api into release/1.18.x
  builtin/logical/ssh/backend_test.go
  builtin/logical/ssh/path_roles.go
  changelog/28901.txt
Labels: backport, hashicorp-contributed-pr

#28903 Backport of Product usage reporting docs into release/1.18.x
  changelog/28858.txt
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/reporting.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#28905 Remove deprecated tutorial links
  website/content/docs/concepts/username-templating.mdx
  website/content/docs/secrets/databases/mongodb.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28906 Backport of Remove deprecated tutorial links into release/1.18.x
  website/content/docs/concepts/username-templating.mdx
  website/content/docs/secrets/databases/mongodb.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28908 Clarify backport instructions further in PR template
  .github/pull_request_template.md
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28909 [VAULT-31754] Check removed status in sys/unseal and error out if the node has been removed from the cluster
  http/sys_seal.go
  http/sys_seal_test.go
  vault/core.go
  vault/core_test.go
  vault/testing.go
Labels: core, core/ha, pr/no-changelog, hashicorp-contributed-pr

#28900 Docs: update move commands
  website/content/docs/commands/auth/move.mdx
  website/content/docs/commands/secrets/move.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28918 1.16 Manual Backport: Release notes and docs for product usage data
  changelog/28858.txt
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/reporting.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#28917 1.17 Manual Backport: Release notes and docs for product usage data
  changelog/28858.txt
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/reporting.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#28907 PKI: Add a new leaf_not_after_behavior value to force erroring in all circumstances
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/issuing/issue_common.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_root.go
  changelog/28907.txt
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/types.go
  ui/app/models/pki/issuer.js
  ui/lib/pki/addon/components/page/pki-issuer-edit.hbs
  ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
  website/content/api-docs/secret/pki/index.mdx
Labels: hashicorp-contributed-pr, backport/1.18.x

#28915 Release notes backport for 1.18
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: hashicorp-contributed-pr

#28922 Keep wording consistent on main
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: hashicorp-contributed-pr

#28894 [Docs] Move the tutorial content to the docs
  website/content/docs/secrets/key-management/azurekeyvault.mdx
  website/content/docs/secrets/key-management/azurekeyvault/index.mdx
  website/content/docs/secrets/key-management/azurekeyvault/setup.mdx
  website/content/docs/secrets/key-management/gcpkms/index.mdx
  website/content/docs/secrets/key-management/gcpkms/setup.mdx
  website/content/docs/secrets/key-management/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28924 Backport of [Docs] Move the tutorial content to the docs into release/1.18.x
  website/content/docs/secrets/key-management/azurekeyvault.mdx
  website/content/docs/secrets/key-management/azurekeyvault/index.mdx
  website/content/docs/secrets/key-management/azurekeyvault/setup.mdx
  website/content/docs/secrets/key-management/gcpkms/index.mdx
  website/content/docs/secrets/key-management/gcpkms/setup.mdx
  website/content/docs/secrets/key-management/index.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#28923 Backport of PKI: Add a new leaf_not_after_behavior value to force erroring in all circumstances into release/1.18.x
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/issuing/issue_common.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_root.go
  changelog/28907.txt
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/types.go
  ui/app/models/pki/issuer.js
  ui/lib/pki/addon/components/page/pki-issuer-edit.hbs
  ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
  website/content/api-docs/secret/pki/index.mdx
Labels: backport, hashicorp-contributed-pr

#28920 Update to Go 1.23.3
  .go-version
  changelog/_go-ver-1190.txt
  go.mod
  go.sum
  helper/testhelpers/mssql/mssqlhelper.go
  sdk/go.mod
  vault/core_test.go
Labels: hashicorp-contributed-pr

#28890 update supported k8s versions for VSO
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28744 Smoke Benchmarks for Continuous Benchmarking
  vault/bench/smoke_bench_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28926 Store global clients at separate storage paths
  command/command_testonly/operator_usage_testonly_test.go
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#28928 Fix protoc issue
  builtin/logical/pki/metadata.pb.go
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28919 [DOCS] Refresh kv docs
  website/content/docs/secrets/kv/kv-v2.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/custom-metadata.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/delete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/destroy-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/max-versions.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/undelete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/write-data.mdx
  website/content/docs/secrets/kv/kv-v2/index.mdx
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
  website/content/docs/secrets/kv/kv-v2/setup.mdx
  website/content/docs/secrets/kv/kv-v2/upgrade.mdx
  website/content/partials/gui-page-instructions/select-kv-mount.mdx
  website/content/partials/policies/path-prefixes.mdx
  website/content/partials/policies/policy-permissions.mdx
  website/data/docs-nav-data.json
  website/public/img/gui/kv/custom-metadata.png
  website/public/img/gui/kv/delete-version.png
  website/public/img/gui/kv/destroy-version.png
  website/public/img/gui/kv/edit-metadata.png
  website/public/img/gui/kv/patch-data.png
  website/public/img/gui/kv/random-string.png
  website/public/img/gui/kv/read-data.png
  website/public/img/gui/kv/undelete-data.png
  website/public/img/gui/kv/write-data.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28933 Backport of [DOCS] Refresh kv docs into release/1.18.x
  website/content/docs/secrets/kv/kv-v2.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/custom-metadata.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/delete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/destroy-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/max-versions.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/undelete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/write-data.mdx
  website/content/docs/secrets/kv/kv-v2/index.mdx
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
  website/content/docs/secrets/kv/kv-v2/setup.mdx
  website/content/docs/secrets/kv/kv-v2/upgrade.mdx
  website/content/partials/gui-page-instructions/select-kv-mount.mdx
  website/content/partials/policies/path-prefixes.mdx
  website/content/partials/policies/policy-permissions.mdx
  website/data/docs-nav-data.json
  website/public/img/gui/kv/custom-metadata.png
  website/public/img/gui/kv/delete-version.png
  website/public/img/gui/kv/destroy-version.png
  website/public/img/gui/kv/edit-metadata.png
  website/public/img/gui/kv/patch-data.png
  website/public/img/gui/kv/random-string.png
  website/public/img/gui/kv/read-data.png
  website/public/img/gui/kv/undelete-data.png
  website/public/img/gui/kv/write-data.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28881 VAULT-31594 Add debug level logging to the LDAP auth library
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/path_config_rotate_root.go
  changelog/28881.txt
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28937 Backport of VAULT-31594 Add debug level logging to the LDAP auth library into release/1.18.x
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/path_config_rotate_root.go
  changelog/28881.txt
Labels: pr/no-milestone, hashicorp-contributed-pr

#28940 Change link to HCP HVN docs
  website/content/docs/partnerships.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28941 Backport of Change link to HCP HVN docs into release/1.18.x
  website/content/docs/partnerships.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28910 Docs: Seal wrap updates
  website/content/docs/enterprise/sealwrap.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28740 Add a benchmark GHA to Vault to use the Smoke Benchmark tests
  .github/scripts/install-cob.sh
  .github/workflows/hack-week-benchmark.yml
  vault/bench/smoke_bench_test.go
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#28942 Docs: entropy augmentation updates
  website/content/docs/enterprise/entropy-augmentation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28865 Sets a default codeowner for the repo
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28934 [DOCS] Updates screenshots and add ent alert
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/partials/gui-page-instructions/select-kv-data.mdx
  website/public/img/gui/kv/patch-data.png
  website/public/img/gui/kv/random-string.png
  website/public/img/gui/kv/read-data.png
  website/public/img/gui/kv/undelete-data.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28853 Add note regarding event notification with perf replication
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28938 VAULT-31751, VAULT-31752: `removed_from_cluster` in vault status
  api/sys_seal.go
  changelog/28938.txt
  command/command_test.go
  command/format.go
  command/status_test.go
  vault/logical_system.go
  vault/logical_system_test.go
  website/content/api-docs/system/seal-status.mdx
  website/content/docs/commands/status.mdx
Labels: hashicorp-contributed-pr

#28930 Update typo in AWS Secrets Engine documentation
  website/content/docs/secrets/aws.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone

#28958 Storing local clients to local storage paths ce changes
  command/command_testonly/operator_usage_testonly_test.go
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity_write_testonly.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28955 Backport of CE Changes for Auth Method Usage Metrics into release/1.18.x
  helper/builtinplugins/registry_full.go
  helper/pluginconsts/plugin_consts.go
  vault/core_metrics.go
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28870 UI/vault 32202/ember sec vulnerabilities
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent

#28969 Add locking to mount tests that write to the mount table
  vault/mount_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28961 Add ml-dsa key type and stubs
  builtin/logical/transit/backend.go
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_keys_test.go
  go.mod
  go.sum
  sdk/helper/keysutil/lock_manager.go
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_ce.go
  sdk/helper/keysutil/policy_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#28972 [DOCS] SEO updates for Vault Agent docs
  website/content/docs/agent-and-proxy/agent/apiproxy.mdx
  website/content/docs/agent-and-proxy/agent/caching/index.mdx
  website/content/docs/agent-and-proxy/agent/caching/persistent-caches/index.mdx
  website/content/docs/agent-and-proxy/agent/caching/persistent-caches/kubernetes.mdx
  website/content/docs/agent-and-proxy/agent/generate-config.mdx
  website/content/docs/agent-and-proxy/agent/generate-config/index.mdx
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
  website/content/docs/agent-and-proxy/agent/template.mdx
  website/content/docs/agent-and-proxy/agent/versions.mdx
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28963 remove hashicorp-forge/bbolt and replace with official beta release (…
  .go-version
  changelog/_go-ver-1183.txt
  changelog/_go-ver-1190.txt
  command/agentproxyshared/cache/cacheboltdb/bolt.go
  command/agentproxyshared/cache/cacheboltdb/bolt_test.go
  go.mod
  go.sum
  helper/testhelpers/mssql/mssqlhelper.go
  physical/raft/config.go
  physical/raft/fsm.go
  physical/raft/raft.go
  physical/raft/raft_test.go
  physical/raft/snapshot.go
  sdk/go.mod
  vault/core_test.go
Labels: hashicorp-contributed-pr

#28946 Backport of Docs: entropy augmentation updates into release/1.18.x
  website/content/docs/enterprise/entropy-augmentation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28970 lower case "key-value"
  website/content/docs/secrets/kv/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.18.x

#28956 Backport of Update typo in AWS Secrets Engine documentation into release/1.18.x
  website/content/docs/secrets/aws.mdx
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28982 Backport of [DOCS] Move the tutorial content to the doc into release/1.18.x
  website/content/docs/auth/approle/approle-pattern.mdx
Labels: hashicorp-contributed-pr

#28661 Backport of Tweak the ocsp_ca_certificate param docs to be more clear about what kind of cert it wants into release/1.18.x
  website/content/api-docs/auth/cert.mdx
Labels: hashicorp-contributed-pr

#28960 1.17 Docs for auth product usage metrics
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#28959 1.16 Docs for auth product usage metrics
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#28976 Backport of [DOCS] SEO updates for Vault Agent docs into release/1.18.x
  website/content/docs/agent-and-proxy/agent/apiproxy.mdx
  website/content/docs/agent-and-proxy/agent/caching/index.mdx
  website/content/docs/agent-and-proxy/agent/caching/persistent-caches/index.mdx
  website/content/docs/agent-and-proxy/agent/caching/persistent-caches/kubernetes.mdx
  website/content/docs/agent-and-proxy/agent/generate-config.mdx
  website/content/docs/agent-and-proxy/agent/generate-config/index.mdx
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/agent/process-supervisor.mdx
  website/content/docs/agent-and-proxy/agent/template.mdx
  website/content/docs/agent-and-proxy/agent/versions.mdx
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28952 Backport of [DOCS] Updates screenshots and add ent alert into release/1.18.x
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/partials/gui-page-instructions/select-kv-data.mdx
  website/public/img/gui/kv/patch-data.png
  website/public/img/gui/kv/random-string.png
  website/public/img/gui/kv/read-data.png
  website/public/img/gui/kv/undelete-data.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28974 [DOCS] SEO updates for Vault Proxy
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/caching/persistent-caches/index.mdx
  website/content/docs/agent-and-proxy/proxy/caching/persistent-caches/kubernetes.mdx
  website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/agent-and-proxy/proxy/versions.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28977 [DOCS] SEO updates for auth-auth docs
  website/content/docs/agent-and-proxy/autoauth/index.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/alicloud.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/approle.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/aws.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/azure.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cert.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cf.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/gcp.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/index.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/jwt.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/kerberos.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/kubernetes.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/ldap.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/oci.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/token_file.mdx
  website/content/docs/agent-and-proxy/autoauth/sinks/file.mdx
  website/content/docs/agent-and-proxy/autoauth/sinks/index.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28985 Backport of [DOCS] SEO updates for auth-auth docs into release/1.18.x
  website/content/docs/agent-and-proxy/autoauth/index.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/alicloud.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/approle.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/aws.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/azure.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cert.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cf.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/gcp.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/index.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/jwt.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/kerberos.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/kubernetes.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/ldap.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/oci.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/token_file.mdx
  website/content/docs/agent-and-proxy/autoauth/sinks/file.mdx
  website/content/docs/agent-and-proxy/autoauth/sinks/index.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28984 Backport of [DOCS] SEO updates for Vault Proxy into release/1.18.x
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/caching/persistent-caches/index.mdx
  website/content/docs/agent-and-proxy/proxy/caching/persistent-caches/kubernetes.mdx
  website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
  website/content/docs/agent-and-proxy/proxy/versions.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28988 [MANUAL BACKPORT] Update events page with note
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28884 VAULT-31525 Remove lowercasing of RADIUS auth.
  builtin/credential/radius/backend_test.go
  builtin/credential/radius/path_users.go
  changelog/28884.txt
Labels: pr/no-milestone, hashicorp-contributed-pr

#28973 Backport of Add locking to mount tests that write to the mount table into release/1.18.x
  vault/mount_test.go
Labels: hashicorp-contributed-pr

#28992 New changelog file for 1.10-1.15
  CHANGELOG-v1.10-v1.15.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28932 VAULT-32206: verify audit log and systemd journal secret integrity
  .github/workflows/build.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-descriptions.hcl
  enos/enos-modules.hcl
  enos/enos-qualities.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/build_local/scripts/build.sh
  enos/modules/generate_failover_secondary_token/scripts/generate-failover-secondary-token.sh
  enos/modules/install_packages/scripts/install-packages.sh
  enos/modules/softhsm_create_vault_keys/scripts/create-keys.sh
  enos/modules/softhsm_create_vault_keys/scripts/get-keys.sh
  enos/modules/softhsm_distribute_vault_keys/scripts/distribute-token.sh
  enos/modules/softhsm_init/scripts/init-softhsm.sh
  enos/modules/softhsm_install/scripts/find-shared-object.sh
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
  enos/modules/vault_upgrade/scripts/restart-vault.sh
  enos/modules/vault_verify_autopilot/scripts/smoke-verify-autopilot.sh
  enos/modules/vault_verify_default_lcq/scripts/smoke-verify-default-lcq.sh
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
  enos/modules/verify_log_secrets/main.tf
  enos/modules/verify_log_secrets/scripts/scan_logs_for_secrets.sh
  enos/modules/verify_seal_type/scripts/verify-seal-type.sh
  enos/modules/verify_secrets_engines/modules/create/kv.tf
  enos/modules/verify_secrets_engines/modules/read/kv.tf
  enos/modules/verify_secrets_engines/scripts/kv-verify-value.sh
  enos/modules/verify_secrets_engines/scripts/secrets-enable.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#28995 Docs: add Integrated Storage migration checklist
  website/content/docs/concepts/integrated-storage/migration-checklist.mdx
  website/data/docs-nav-data.json
  website/public/img/diagram-vault-integrated-ra-3_az.png
  website/public/img/diagram-vault-ra-3-az.png
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28998 backport-assistant: bump version to 0.5.3
  .github/workflows/backport-ce.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28962 add vault_addr section to va config info
  website/content/docs/agent-and-proxy/agent/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28999 Backport of Docs: add Integrated Storage migration checklist into release/1.18.x
  website/content/docs/concepts/integrated-storage/migration-checklist.mdx
  website/data/docs-nav-data.json
  website/public/img/diagram-vault-integrated-ra-3_az.png
  website/public/img/diagram-vault-ra-3-az.png
Labels: hashicorp-contributed-pr

#28598 adding logic to handle cloud-init error code 2
  enos/modules/install_packages/scripts/synchronize-repos.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29003 VAULT-32507: Docs for secret engine usage metrics
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29014 Backport of VAULT-32507: Docs for secret engine usage metrics into release/1.18.x
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28983 Add known issue for hsm duplicate
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28927 Backport of update supported k8s versions for VSO into release/1.18.x
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#28893 Backport 1.18.x: UI Solve cntrl+f issue on KVv2 JSON details and edit views (#28808)
  changelog/28808.txt
  ui/app/templates/components/console/log-json.hbs
  ui/app/templates/components/control-group-success.hbs
  ui/lib/core/addon/components/json-editor.hbs
  ui/lib/core/addon/components/json-editor.js
  ui/lib/core/addon/modifiers/code-mirror.js
  ui/lib/kv/addon/components/kv-data-fields.hbs
  ui/lib/kv/addon/components/kv-data-fields.js
  ui/lib/kv/addon/components/kv-patch/subkeys-reveal.hbs
  ui/lib/kv/addon/components/kv-paths-card.hbs
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/json-editor-test.js
  ui/tests/integration/components/kv/kv-data-fields-test.js
  ui/tests/integration/components/kv/kv-patch/editor/form-test.js
  ui/tests/integration/components/kv/kv-patch/json-form-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-details-test.js
Labels: ui, backport, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent

#29004 VAULT-32507: CE Changes
  helper/builtinplugins/registry_full.go
  helper/pluginconsts/plugin_consts.go
  vault/core_metrics.go
Labels: hashicorp-contributed-pr, backport/1.18.x

#28950 update docs for eventing
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28975 docs/vault-helm: updates for v0.29.1 release
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29029 Backport of docs/vault-helm: updates for v0.29.1 release into release/1.18.x
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/partials/helm/install.mdx
  website/content/partials/helm/repo.mdx
Labels: hashicorp-contributed-pr

#29030 Backport of VAULT-31409: trace postUnseal function into release/1.18.x
  changelog/28895.txt
  command/server/config.go
  command/server/config_test_helpers.go
  command/server/test-fixtures/config3.hcl
  helper/trace/debug_trace.go
  helper/trace/debug_trace_test.go
  http/sys_config_state_test.go
  vault/core.go
  vault/external_tests/pprof/pprof_test.go
  website/content/docs/configuration/index.mdx
Labels: hashicorp-contributed-pr

#28121 Okta Dep Update
  builtin/credential/okta/backend.go
  builtin/credential/okta/backend_test.go
  builtin/credential/okta/path_config.go
  changelog/28121.txt
  go.mod
  go.sum
  vault/login_mfa.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29025 Backport of add oss stub for autoloaded getter in core into release/1.18.x
  changelog/29024.txt
  vault/core_stubs_oss.go
Labels: hashicorp-contributed-pr

#29032 Backport of Okta Dep Update into release/1.18.x
  builtin/credential/okta/backend.go
  builtin/credential/okta/backend_test.go
  builtin/credential/okta/path_config.go
  changelog/28121.txt
  go.mod
  go.sum
  vault/login_mfa.go
Labels: hashicorp-contributed-pr

#29026 docs: Fix path to allowedSprigFuncs
  website/content/docs/platform/k8s/vso/secret-transformation.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.18.x

#29034 Backport of docs: Fix path to allowedSprigFuncs into release/1.18.x
  website/content/docs/platform/k8s/vso/secret-transformation.mdx
Labels: hashicorp-contributed-pr

#29041 Revert "Perform validation when issuing or signing certificates. (#28921)
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/issuing/issuing_stubs_oss.go
  builtin/logical/pki/path_issue_sign.go
  changelog/28921.txt
  go.mod
  go.sum
  website/content/docs/secrets/pki/considerations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29042 Revert "Perform validation when issuing or signing certificates. (#28921)
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/issuing/issuing_stubs_oss.go
  builtin/logical/pki/path_issue_sign.go
  changelog/28921.txt
  go.mod
  go.sum
  website/content/docs/secrets/pki/considerations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29043 Backport of update docs for eventing into release/1.18.x
  website/content/docs/concepts/events.mdx
Labels: hashicorp-contributed-pr

#28994 Prep for Azure WIF work
  ui/app/components/secret-engine/configure-aws.ts
  ui/app/helpers/mountable-secret-engines.js
  ui/app/helpers/supported-secret-backends.js
  ui/app/models/aws/root-config.js
  ui/app/models/identity/oidc/config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/lib/core/addon/components/secret-list-header.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-aws-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29045 Enforce PKI issuer constraints
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/path_issue_sign.go
  changelog/29045.txt
  go.mod
  go.sum
  website/content/docs/secrets/pki/considerations.mdx
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29046 Backport of Enforce PKI issuer constraints into release/1.18.x
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/path_issue_sign.go
  changelog/29045.txt
  go.mod
  go.sum
  website/content/docs/secrets/pki/considerations.mdx
Labels: hashicorp-contributed-pr

#29048 Add hook for ENT tweaking of PKI contraints verification options
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/issuing/issuing_stubs_oss.go
  builtin/logical/pki/path_issue_sign.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29028 add `read` subkeys to kv patch docs
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-subkey.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29049 Backport of add `read` subkeys to kv patch docs into release/1.18.x
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-subkey.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29053 Run make fmt
  builtin/credential/okta/path_config.go
  builtin/logical/pki/issuing/cert_verify.go
  tools/pipeline/internal/cmd/generate_enos_dynamic_config.go
  tools/pipeline/internal/cmd/releases_list_versions.go
  tools/pipeline/internal/pkg/generate/enos_dynamic_config.go
  tools/pipeline/internal/pkg/generate/enos_dynamic_config_test.go
  tools/pipeline/internal/pkg/releases/client.go
  tools/pipeline/internal/pkg/releases/client_mock.go
  tools/pipeline/internal/pkg/releases/list_versions.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29023 Update docs adding use_pss to PKI root generation api
  website/content/api-docs/secret/pki/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29056 Backport of Update docs adding use_pss to PKI root generation api into release/1.18.x
  website/content/api-docs/secret/pki/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29057 Seal and cleanup cluster before test teardown for TestRaftHA_Recover_Cluster
  vault/external_tests/raftha/raft_ha_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29044 Add an option to allow cert-auth to return metadata about client cert that fails login
  builtin/credential/cert/backend_test.go
  builtin/credential/cert/path_config.go
  builtin/credential/cert/path_login.go
  builtin/credential/cert/path_login_test.go
  changelog/29044.txt
  sdk/logical/response.go
  sdk/logical/response_test.go
  vault/identity_store_entities.go
  website/content/api-docs/auth/cert.mdx
Labels: auth/cert, hashicorp-contributed-pr

#29050 Fix OSS sealunwrapper adding extra get + put request to all storage get requests
  changelog/29050.txt
  sdk/physical/inmem/inmem_ha.go
  vault/sealunwrapper.go
  vault/sealunwrapper_test.go
Labels: backport/1.18.x

#29059 Backport of Fix OSS sealunwrapper adding extra get + put request to all storage get requests into release/1.18.x
  changelog/29050.txt
  sdk/physical/inmem/inmem_ha.go
  vault/sealunwrapper.go
  vault/sealunwrapper_test.go
Labels: hashicorp-contributed-pr
