Repository hashicorp/vault, pull requests merged in 2024-12, with the labels that each got.

#29066 Remove all references to current fragments, standbyfragments and partialMonthTracker
  builtin/logical/pki/acme_billing_test.go
  command/command_testonly/operator_usage_testonly_test.go
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29069 [DOCS] Clarify maintenance table
  website/content/docs/enterprise/lts.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29075 Backport of [DOCS] Clarify maintenance table into release/1.18.x
  website/content/docs/enterprise/lts.mdx
Labels: hashicorp-contributed-pr

#29052 VAULT-32568: Shutdown node when it's not in the raft config
  physical/raft/raft.go
  physical/raft/raft_test.go
  vault/core.go
  vault/external_tests/raft/raft_test.go
  vault/init.go
  vault/raft.go
  vault/request_forwarding.go
  vault/testing.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#28989 Update DB Static role rotation logic to generate new password if retried password fails
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rotation.go
  changelog/28989.txt
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29076 Migrate Clients From Old Storage Paths to New Paths During Upgrade #7032
  vault/activity_log.go
  vault/activity_log_stubs_oss.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29058 VAULT-32158 docs for secret sync usage metrics
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29079 Backport of VAULT-32158 docs for secret sync usage metrics into release/1.18.x
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29078 Make EDU owner for files under website/
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29070 [DOCS] SEO updates for Auth pages
  website/content/docs/auth/approle/approle-pattern.mdx
  website/content/docs/auth/approle/index.mdx
  website/content/docs/auth/jwt/index.mdx
  website/content/docs/auth/jwt/oidc-providers/adfs.mdx
  website/content/docs/auth/jwt/oidc-providers/auth0.mdx
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
  website/content/docs/auth/jwt/oidc-providers/forgerock.mdx
  website/content/docs/auth/jwt/oidc-providers/gitlab.mdx
  website/content/docs/auth/jwt/oidc-providers/google.mdx
  website/content/docs/auth/jwt/oidc-providers/ibmisam.mdx
  website/content/docs/auth/jwt/oidc-providers/index.mdx
  website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/auth/jwt/oidc-providers/okta.mdx
  website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/auth/login-mfa/index.mdx
  website/content/docs/auth/saml/adfs.mdx
  website/content/docs/auth/saml/index.mdx
  website/content/docs/auth/saml/link-vault-group-to-ad.mdx
  website/content/docs/auth/saml/troubleshoot-adfs/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29077 Backport of Update DB Static role rotation logic to generate new password if retried password fails into release/1.18.x
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rotation.go
  changelog/28989.txt
Labels: hashicorp-contributed-pr

#29086 [BACKPORT] Make EDU owner for files under website/ under release/1.18
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28991 VAULT-31755: Add removed and HA health to the sys/health endpoint
  api/sys_health.go
  changelog/28991.txt
  http/sys_health.go
  http/sys_health_test.go
  vault/cluster/inmem_layer.go
  vault/core.go
  vault/external_tests/raft/raft_test.go
  vault/ha.go
  vault/ha_test.go
  vault/request_forwarding.go
  vault/request_forwarding_rpc.go
  vault/testing.go
Labels: core/ha, hashicorp-contributed-pr

#29091 Fix unlocked mounts read
  changelog/29091.txt
  vault/core.go
  vault/core_metrics.go
  vault/expiration.go
  vault/expiration_test.go
  vault/token_store_test.go
Labels: hashicorp-contributed-pr, backport/1.18.x

#29092 Backport of Fix unlocked mounts read into release/1.18.x
  changelog/29091.txt
  vault/core.go
  vault/core_metrics.go
  vault/expiration.go
  vault/expiration_test.go
  vault/token_store_test.go
Labels: hashicorp-contributed-pr

#29067 Docs: Add updated screenshots to kv subkey docs
  website/content/docs/auth/saml/adfs.mdx
  website/content/docs/auth/saml/link-vault-group-to-ad.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/custom-metadata.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/delete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/destroy-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/max-versions.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-subkey.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/undelete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/write-data.mdx
  website/content/docs/secrets/kv/kv-v2/index.mdx
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
  website/content/docs/secrets/kv/kv-v2/setup.mdx
  website/content/partials/gui-instructions/create-acl-policy.mdx
  website/content/partials/gui-instructions/create-group.mdx
  website/content/partials/gui-instructions/enable-authn-plugin.mdx
  website/content/partials/gui-instructions/enable-secrets-plugin.mdx
  website/content/partials/gui-instructions/plugins/kv/open-overview.mdx
  website/content/partials/gui-page-instructions/select-kv-mount.mdx
  website/public/img/gui/kv/overview-page.png
  website/public/img/gui/kv/patch-reveal-subkeys.png
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29095 Backport of Docs: Add updated screenshots to kv subkey docs into release/1.18.x
  website/content/docs/auth/saml/adfs.mdx
  website/content/docs/auth/saml/link-vault-group-to-ad.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/custom-metadata.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/delete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/destroy-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/max-versions.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/patch-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/read-subkey.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/undelete-data.mdx
  website/content/docs/secrets/kv/kv-v2/cookbook/write-data.mdx
  website/content/docs/secrets/kv/kv-v2/index.mdx
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
  website/content/docs/secrets/kv/kv-v2/setup.mdx
  website/content/partials/gui-instructions/create-acl-policy.mdx
  website/content/partials/gui-instructions/create-group.mdx
  website/content/partials/gui-instructions/enable-authn-plugin.mdx
  website/content/partials/gui-instructions/enable-secrets-plugin.mdx
  website/content/partials/gui-instructions/plugins/kv/open-overview.mdx
  website/content/partials/gui-page-instructions/select-kv-mount.mdx
  website/public/img/gui/kv/overview-page.png
  website/public/img/gui/kv/patch-reveal-subkeys.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29103 VAULT-32159 CE changes for PKI metrics
  vault/core_metrics.go
Labels: hashicorp-contributed-pr, backport/1.18.x

#29080 1.17 Backport: VAULT-32158 docs (#29058)
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29104 Backport of VAULT-32159 CE changes for PKI metrics into release/1.18.x
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29102 VAULT-32159 docs for pki metrics
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29105 VAULT-32159 issuers not certs CE changes
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29081 1.16 Backport: VAULT-32158 docs (#29058)
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/content/docs/release-notes/1.16.1.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29073 VAULT-32598: add docs for azure autosnapshot auth modes
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29051 VAULT-32804: Add STS Fallback parameters to secrets-aws engine
  builtin/logical/aws/client.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/aws/path_config_root_test.go
  changelog/29051.txt
  website/content/api-docs/secret/aws.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29106 Backport of VAULT-32159 docs for pki metrics into release/1.18.x
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29109 Manual 1.16 Backport: VAULT-32159 docs for pki metrics (#29102)
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29107 1.17 Manual backport: VAULT-32159 docs for pki metrics (#29102)
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29020 Use go-secure-stdlib's RSA key generator backed by a DRBG
  builtin/credential/cert/backend_test.go
  builtin/logical/database/credentials.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/ca_test.go
  builtin/logical/pki/ca_util_test.go
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_config_acme_test.go
  builtin/logical/pki/path_tidy_test.go
  builtin/logical/pkiext/pkiext_binary/acme_test.go
  builtin/logical/ssh/path_config_ca.go
  builtin/logical/ssh/util.go
  builtin/logical/transit/path_certificates_test.go
  builtin/logical/transit/path_import_test.go
  changelog/29020.txt
  command/transit_import_key_test.go
  go.mod
  go.sum
  helper/testhelpers/certhelpers/cert_helpers.go
  plugins/database/mongodb/cert_helpers_test.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types_test.go
  sdk/helper/cryptoutil/rsa.go
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_test.go
  vault/identity_store_oidc.go
Labels: hashicorp-contributed-pr

#29108 Backport of VAULT-32159 issuers not certs CE changes into release/1.18.x
  vault/core_metrics.go
Labels: hashicorp-contributed-pr

#29110 Fix missing locking in mount tests
  vault/mount_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29111 Backport of Fix missing locking in mount tests into release/1.18.x
  vault/mount_test.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29100 [DOCS] Update the doc title and description for SEO improvements
  website/content/docs/sync/awssm.mdx
  website/content/docs/sync/azurekv.mdx
  website/content/docs/sync/gcpsm.mdx
  website/content/docs/sync/github.mdx
  website/content/docs/sync/index.mdx
  website/content/docs/sync/vercelproject.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29112 Backport of [DOCS] Update the doc title and description for SEO improvements into release/1.18.x
  website/content/docs/sync/awssm.mdx
  website/content/docs/sync/azurekv.mdx
  website/content/docs/sync/gcpsm.mdx
  website/content/docs/sync/github.mdx
  website/content/docs/sync/index.mdx
  website/content/docs/sync/vercelproject.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#29019 Docs: add production hardening document
  website/content/docs/concepts/production-hardening.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28997 Backport of VAULT-32206: verify audit log and systemd journal secret integrity into release/1.18.x
  .github/workflows/build.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-descriptions.hcl
  enos/enos-modules.hcl
  enos/enos-qualities.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/modules/build_local/scripts/build.sh
  enos/modules/generate_failover_secondary_token/scripts/generate-failover-secondary-token.sh
  enos/modules/install_packages/scripts/install-packages.sh
  enos/modules/softhsm_create_vault_keys/scripts/create-keys.sh
  enos/modules/softhsm_create_vault_keys/scripts/get-keys.sh
  enos/modules/softhsm_distribute_vault_keys/scripts/distribute-token.sh
  enos/modules/softhsm_init/scripts/init-softhsm.sh
  enos/modules/softhsm_install/scripts/find-shared-object.sh
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
  enos/modules/vault_upgrade/scripts/restart-vault.sh
  enos/modules/vault_verify_autopilot/scripts/smoke-verify-autopilot.sh
  enos/modules/vault_verify_default_lcq/scripts/smoke-verify-default-lcq.sh
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
  enos/modules/verify_log_secrets/main.tf
  enos/modules/verify_log_secrets/scripts/scan_logs_for_secrets.sh
  enos/modules/verify_seal_type/scripts/verify-seal-type.sh
  enos/modules/verify_secrets_engines/modules/create/kv.tf
  enos/modules/verify_secrets_engines/modules/read/kv.tf
  enos/modules/verify_secrets_engines/scripts/kv-verify-value.sh
  enos/modules/verify_secrets_engines/scripts/secrets-enable.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29121 Backport of Docs: add production hardening document into release/1.18.x
  website/content/docs/concepts/production-hardening.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#29122 Do not use static certificates for diagnose tests
  command/operator_diagnose_test.go
  command/server/test-fixtures/diagnose_seal_transit_tls_check.hcl
  command/server/test-fixtures/tls_config_ok.hcl
  helper/testhelpers/pki/pkihelper.go
  vault/diagnose/test-fixtures/goodcertwithroot.pem
  vault/diagnose/tls_verification_test.go
Labels: test, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29117 Fix decryption of raft bootstrap challenge in multi-seal scenarios
  changelog/29117.txt
  vault/core.go
  vault/raft.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29127 Backport of Fix decryption of raft bootstrap challenge in multi-seal scenarios into release/1.18.x
  changelog/29117.txt
  vault/core.go
  vault/raft.go
Labels: hashicorp-contributed-pr

#29123 Add hybrid key type for ML-DSA/ECDSA
  builtin/logical/transit/path_keys.go
  builtin/logical/transit/path_keys_test.go
  sdk/helper/keysutil/lock_manager.go
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29128 Fix return certificate expiry time from NearExpiration
  changelog/29128.txt
  vault/diagnose/tls_verification.go
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29129 Backport of Fix return certificate expiry time from NearExpiration into release/1.18.x
  changelog/29128.txt
  vault/diagnose/tls_verification.go
Labels: backport, hashicorp-contributed-pr

#29131 Update vault-plugin-secrets-openldap to v0.14.4
  changelog/29131.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29133 Backport of Update vault-plugin-secrets-openldap to v0.14.4 into release/1.18.x
  changelog/29131.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29114 UI: Decode Oracle database `connection_url`
  changelog/29114.txt
  ui/app/helpers/decode-uri.js
  ui/app/serializers/database/connection.js
  ui/app/templates/components/database-connection.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/unit/serializers/database/connection-test.js
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29139 Backport of UI: Decode Oracle database `connection_url` into release/1.18.x
  changelog/29114.txt
  ui/app/helpers/decode-uri.js
  ui/app/serializers/database/connection.js
  ui/app/templates/components/database-connection.hbs
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/unit/serializers/database/connection-test.js
Labels: ui, backport, hashicorp-contributed-pr

#29140 Improve wording of the raft challenge + seal HA bug changelog
  changelog/29117.txt
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.18.x

#29137 Send Global Data From Secondary to Primary During Upgrade
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29141 Backport of Improve wording of the raft challenge + seal HA bug changelog into release/1.18.x
  changelog/29117.txt
Labels: hashicorp-contributed-pr

#29082 Vault 32676 add vault build date to system view plugin env
  changelog/29082.txt
  sdk/logical/plugin.pb.go
  sdk/logical/plugin.proto
  vault/dynamic_system_view.go
  vault/dynamic_system_view_test.go
  vault/testing_util.go
  vault/testing_util_stubs_oss.go
  version/version.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29071 Add Azure configuration details view
  ui/app/adapters/azure/config.js
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/components/secret-engine/configure-aws.hbs
  ui/app/helpers/mountable-secret-engines.js
  ui/app/helpers/supported-secret-backends.js
  ui/app/models/aws/lease-config.js
  ui/app/models/aws/root-config.js
  ui/app/models/azure/config.js
  ui/app/models/identity/oidc/config.js
  ui/app/models/ssh/ca-config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/serializers/azure/config.js
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/core/addon/components/secret-list-header.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/types/vault/models/azure/config.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29090 VAULT-31758: Store when a node is removed in the raft stable store
  changelog/29090.txt
  physical/raft/raft.go
  vault/external_tests/raft/raft_test.go
  vault/external_tests/raftha/raft_ha_test.go
  vault/raft.go
Labels: hashicorp-contributed-pr

#29143 Backport of Vault 32676 add vault build date to system view plugin env into release/1.18.x
  changelog/29082.txt
  sdk/logical/plugin.pb.go
  sdk/logical/plugin.proto
  vault/dynamic_system_view.go
  vault/dynamic_system_view_test.go
  vault/testing_util.go
  vault/testing_util_stubs_oss.go
  version/version.go
Labels: hashicorp-contributed-pr

#29142 Run benchmark only on PRs to main (and rename the file)
  .github/workflows/benchmark-prevent-performance-degradations.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29151 Update VSO docs for v0.9.1
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29154 Disallow querying of activity APIs during upgrade
  vault/logical_system_activity.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29156 Update changelog to clarify fix applies to any database with template variables in `connection_url`
  changelog/29114.txt
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29158 Backport of Update changelog to clarify fix applies to any database with template variables in `connection_url` into release/1.18.x
  changelog/29114.txt
Labels: hashicorp-contributed-pr

#29130 use const for in relation to vault eventing metadata
  sdk/logical/events.go
  vault/eventbus/bus.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29093 secrets/db: enable skip auto import rotation of static roles
  builtin/logical/database/backend.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_config_connection_ce.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_roles_ce.go
  builtin/logical/database/path_rotate_credentials.go
  builtin/logical/database/rotation.go
  builtin/logical/database/rotation_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29162 remove changelog #29024
  changelog/29024.txt
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29159 vso/docs: restore upgrade instructions
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29167 Backport of vso/docs: restore upgrade instructions into release/1.18.x
  website/content/docs/platform/k8s/vso/installation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29161 update changelog for okta dependency update
  changelog/28121.txt
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29168 Backport of update changelog for okta dependency update into release/1.18.x
  changelog/28121.txt
Labels: pr/no-milestone, hashicorp-contributed-pr

#29017 VAULT-31756: Include removed and HA health in sys/health docs
  website/content/api-docs/system/health.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#29153 bump golang.org/x/crypto to v0.31.0
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29165 Backport of remove changelog #29024 into release/1.18.x
  changelog/29024.txt
Labels: hashicorp-contributed-pr

#29166 [DOCS] Update the page description for SEO improvement #4
  website/content/docs/secrets/ad/index.mdx
  website/content/docs/secrets/ad/migration-guide.mdx
  website/content/docs/secrets/identity/identity-token.mdx
  website/content/docs/secrets/identity/index.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
  website/content/docs/secrets/key-management/awskms.mdx
  website/content/docs/secrets/key-management/azurekeyvault/index.mdx
  website/content/docs/secrets/key-management/azurekeyvault/setup.mdx
  website/content/docs/secrets/key-management/gcpkms/index.mdx
  website/content/docs/secrets/key-management/gcpkms/setup.mdx
  website/content/docs/secrets/key-management/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29170 Backport of [DOCS] Update the page description for SEO improvement #4 into release/1.18.x
  website/content/docs/secrets/ad/index.mdx
  website/content/docs/secrets/ad/migration-guide.mdx
  website/content/docs/secrets/identity/identity-token.mdx
  website/content/docs/secrets/identity/index.mdx
  website/content/docs/secrets/identity/oidc-provider.mdx
  website/content/docs/secrets/key-management/awskms.mdx
  website/content/docs/secrets/key-management/azurekeyvault/index.mdx
  website/content/docs/secrets/key-management/azurekeyvault/setup.mdx
  website/content/docs/secrets/key-management/gcpkms/index.mdx
  website/content/docs/secrets/key-management/gcpkms/setup.mdx
  website/content/docs/secrets/key-management/index.mdx
Labels: hashicorp-contributed-pr

#29174 update changelogs for static role role rotation updates
  changelog/28989.txt
  changelog/29131.txt
Labels: pr/no-changelog, hashicorp-contributed-pr

#29175 Add troubleshooting section to 1.16.x docs for Vault 003 exam
  website/content/docs/troubleshoot/generate-root-token.mdx
  website/content/docs/troubleshoot/lease-issues.mdx
  website/content/docs/troubleshoot/tune-lease-ttl.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29149 Docs: add Tune server performance documentation
  website/content/docs/concepts/tune-server-performance.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29180 Backport of Docs: add Tune server performance documentation into release/1.18.x
  website/content/docs/concepts/tune-server-performance.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29094 mfa login/totp
  website/content/docs/auth/login-mfa/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#28746 Docs/secrets sync ssrf private endpoints
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/1_17_secrets-sync-ssrf-private-endpoints.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, sync/aws, backport/1.18.x

#29186 [DOCS] Manual cherry pick PR 28746 to 1.17.x doc
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/1_17_secrets-sync-ssrf-private-endpoints.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29185 [DOCS] Manual cherry pick PR 28746 to 1.18.x doc
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/1_17_secrets-sync-ssrf-private-endpoints.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29189 Update interoperability-matrix.mdx
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29190 Backport of Update interoperability-matrix.mdx into release/1.18.x
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29184 Backport of mfa login/totp into release/1.18.x
  website/content/docs/auth/login-mfa/index.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29187 identity: Introduce ConflictResolver interface
  vault/identity_store_conflicts.go
  vault/identity_store_structs.go
  vault/identity_store_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29169 Backport of bump golang.org/x/crypto to v0.31.0 into release/1.18.x
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29192 [DOCS] Match the page_title and H1 header
  website/content/docs/secrets/databases/cassandra.mdx
  website/content/docs/secrets/databases/couchbase.mdx
  website/content/docs/secrets/databases/custom.mdx
  website/content/docs/secrets/databases/db2.mdx
  website/content/docs/secrets/databases/hanadb.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/influxdb.mdx
  website/content/docs/secrets/databases/mongodb.mdx
  website/content/docs/secrets/databases/mongodbatlas.mdx
  website/content/docs/secrets/databases/mssql.mdx
  website/content/docs/secrets/databases/mysql-maria.mdx
  website/content/docs/secrets/databases/oracle.mdx
  website/content/docs/secrets/databases/postgresql.mdx
  website/content/docs/secrets/databases/redis.mdx
  website/content/docs/secrets/databases/rediselasticache.mdx
  website/content/docs/secrets/databases/redshift.mdx
  website/content/docs/secrets/databases/snowflake.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29197 Backport of [DOCS] Match the page_title and H1 header into release/1.18.x
  website/content/docs/secrets/databases/cassandra.mdx
  website/content/docs/secrets/databases/couchbase.mdx
  website/content/docs/secrets/databases/custom.mdx
  website/content/docs/secrets/databases/db2.mdx
  website/content/docs/secrets/databases/hanadb.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/influxdb.mdx
  website/content/docs/secrets/databases/mongodb.mdx
  website/content/docs/secrets/databases/mongodbatlas.mdx
  website/content/docs/secrets/databases/mssql.mdx
  website/content/docs/secrets/databases/mysql-maria.mdx
  website/content/docs/secrets/databases/oracle.mdx
  website/content/docs/secrets/databases/postgresql.mdx
  website/content/docs/secrets/databases/redis.mdx
  website/content/docs/secrets/databases/rediselasticache.mdx
  website/content/docs/secrets/databases/redshift.mdx
  website/content/docs/secrets/databases/snowflake.mdx
Labels: hashicorp-contributed-pr

#28739 Backport of Add enrollment protocol sublinks. into release/1.18.x
  website/content/api-docs/secret/pki/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29160 Backport of use const for in relation to vault eventing metadata into release/1.18.x
  sdk/logical/events.go
  vault/eventbus/bus.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#29196 make fmt
  builtin/logical/database/credentials.go
  builtin/logical/pki/ca_util_test.go
  builtin/logical/ssh/util.go
  sdk/helper/certutil/helpers.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29198 Backport of Fix docs - server command - log-file parameter - path value example into release/1.18.x
  website/content/docs/commands/server.mdx
Labels: hashicorp-contributed-pr

#29193 Run Migrations If Migration Worker has not been run #7162
  vault/activity_log.go
  vault/activity_log_util_common.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29144 Update docs to reflect that activity log cannot be disabled on Vault Enterprise
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/faq/client-count/usage.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29205 Backport of Update docs to reflect that activity log cannot be disabled on Vault Enterprise into release/1.18.x
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/upgrading/upgrade-to-1.11.x.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/faq/client-count/usage.mdx
Labels: hashicorp-contributed-pr

#29204 [DOCS] Match the page_title with H1 header
  website/content/docs/platform/mssql/configuration.mdx
  website/content/docs/platform/mssql/installation.mdx
  website/content/docs/platform/mssql/rotation.mdx
  website/content/docs/platform/mssql/troubleshooting.mdx
  website/content/docs/platform/mssql/upgrading.mdx
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/platform/servicenow/index.mdx
  website/content/docs/platform/servicenow/installation.mdx
  website/content/docs/platform/servicenow/troubleshooting.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29207 Backport of [DOCS] Match the page_title with H1 header into release/1.18.x
  website/content/docs/platform/mssql/configuration.mdx
  website/content/docs/platform/mssql/installation.mdx
  website/content/docs/platform/mssql/rotation.mdx
  website/content/docs/platform/mssql/troubleshooting.mdx
  website/content/docs/platform/mssql/upgrading.mdx
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/platform/servicenow/index.mdx
  website/content/docs/platform/servicenow/installation.mdx
  website/content/docs/platform/servicenow/troubleshooting.mdx
Labels: hashicorp-contributed-pr

#29199 [DOCS] Fix style inconsistency
  website/content/docs/platform/aws/index.mdx
  website/content/docs/platform/aws/lambda-extension.mdx
  website/content/docs/platform/aws/run.mdx
  website/content/docs/platform/github-actions.mdx
  website/content/docs/platform/index.mdx
  website/content/docs/platform/k8s/csi/configurations.mdx
  website/content/docs/platform/k8s/csi/examples.mdx
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/external.mdx
  website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/index.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
  website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/helm/terraform.mdx
  website/content/docs/platform/k8s/injector-csi.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/examples.mdx
  website/content/docs/platform/k8s/injector/index.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
  website/content/docs/platform/k8s/vso/secret-transformation.mdx
  website/content/docs/platform/k8s/vso/sources/hvs.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/aws.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/gcp.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx
  website/content/docs/platform/k8s/vso/telemetry.mdx
  website/content/docs/plugins/containerized-plugins/add-a-containerized-plugin.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/docs/plugins/plugin-development.mdx
  website/content/docs/plugins/plugin-management.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29209 Backport of [DOCS] Fix style inconsistency into release/1.18.x
  website/content/docs/platform/aws/index.mdx
  website/content/docs/platform/aws/lambda-extension.mdx
  website/content/docs/platform/aws/run.mdx
  website/content/docs/platform/github-actions.mdx
  website/content/docs/platform/index.mdx
  website/content/docs/platform/k8s/csi/configurations.mdx
  website/content/docs/platform/k8s/csi/examples.mdx
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/csi/installation.mdx
  website/content/docs/platform/k8s/helm/configuration.mdx
  website/content/docs/platform/k8s/helm/enterprise.mdx
  website/content/docs/platform/k8s/helm/examples/development.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-dr-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-perf-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/enterprise-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/external.mdx
  website/content/docs/platform/k8s/helm/examples/ha-tls.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-consul.mdx
  website/content/docs/platform/k8s/helm/examples/ha-with-raft.mdx
  website/content/docs/platform/k8s/helm/examples/index.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls-cert-manager.mdx
  website/content/docs/platform/k8s/helm/examples/injector-tls.mdx
  website/content/docs/platform/k8s/helm/examples/kubernetes-auth.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-audit.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-load-balanced-ui.mdx
  website/content/docs/platform/k8s/helm/examples/standalone-tls.mdx
  website/content/docs/platform/k8s/helm/index.mdx
  website/content/docs/platform/k8s/helm/openshift.mdx
  website/content/docs/platform/k8s/helm/run.mdx
  website/content/docs/platform/k8s/helm/terraform.mdx
  website/content/docs/platform/k8s/injector-csi.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/examples.mdx
  website/content/docs/platform/k8s/injector/index.mdx
  website/content/docs/platform/k8s/injector/installation.mdx
  website/content/docs/platform/k8s/vso/examples.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
  website/content/docs/platform/k8s/vso/secret-transformation.mdx
  website/content/docs/platform/k8s/vso/sources/hvs.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/aws.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/gcp.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx
  website/content/docs/platform/k8s/vso/telemetry.mdx
  website/content/docs/plugins/containerized-plugins/add-a-containerized-plugin.mdx
  website/content/docs/plugins/index.mdx
  website/content/docs/plugins/plugin-architecture.mdx
  website/content/docs/plugins/plugin-development.mdx
  website/content/docs/plugins/plugin-management.mdx
Labels: hashicorp-contributed-pr

#28873 UI: Fix MFA + SSO login workflow
  changelog/28873.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/components/auth-saml.js
  ui/app/components/auth/login-form.js
  ui/app/components/auth/page.js
  ui/app/components/mfa/mfa-form.js
  ui/app/services/auth.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/helpers/auth/mfa-helpers.js
  ui/tests/integration/components/auth-jwt-test.js
Labels: hashicorp-contributed-pr

#29210 Do not error during retry join if the node is removed
  vault/core.go
  vault/raft.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29202 db: fix skip-import-rotation/rootless integration
  builtin/logical/database/backend.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_roles.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29212 Add ui team to oidc and jwt codeowners
  CODEOWNERS
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent

#29211 Backport of UI: Fix MFA + SSO login workflow into release/1.18.x
  changelog/28873.txt
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/components/auth-saml.js
  ui/app/components/auth/login-form.js
  ui/app/components/auth/page.js
  ui/app/components/mfa/mfa-form.js
  ui/app/services/auth.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/helpers/auth/mfa-helpers.js
  ui/tests/integration/components/auth-jwt-test.js
Labels: hashicorp-contributed-pr

#29124 Add EDU as approvers for more granular targets
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29194 modify auth.mdx. change order in first example
  website/content/docs/concepts/auth.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.18.x

#29216 Backport of modify auth.mdx. change order in first example into release/1.18.x
  website/content/docs/concepts/auth.mdx
Labels: hashicorp-contributed-pr

#29200 UI: Update PostgreSQL database params
  changelog/29200.txt
  ui/app/models/database/connection.js
  ui/app/utils/model-helpers/database-helpers.js
  ui/tests/helpers/secret-engine/database-helpers.ts
  ui/tests/unit/models/database-connection-test.js
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29220 Add ops quick start, update nav
  website/content/docs/get-started/operations-qs.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29225 Backport of Add ops quick start, update nav into release/1.18.x
  website/content/docs/get-started/operations-qs.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29227 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29047 Allow Configuration of Azure Secret Engine, including WIF for enterprise users
  changelog/29047.txt
  ui/app/adapters/azure/config.js
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/components/secret-engine/configure-azure.hbs
  ui/app/components/secret-engine/configure-azure.ts
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/azure/config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/secret-engine/configure-azure-test.js
  ui/types/vault/models/azure/config.d.ts
Labels: ui, hashicorp-contributed-pr

#29116 [DOCS] Update the page description for SEO improvement #2
  website/content/docs/secrets/ssh/index.mdx
  website/content/docs/secrets/ssh/one-time-ssh-passwords.mdx
  website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
  website/content/docs/secrets/transform/ff3-tweak-details.mdx
  website/content/docs/secrets/transform/index.mdx
  website/content/docs/secrets/transform/tokenization.mdx
  website/content/docs/secrets/transit/index.mdx
  website/content/docs/secrets/transit/key-wrapping-guide.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29115 [DOCS] Update the title & description for SEO improvement
  website/content/docs/secrets/alicloud.mdx
  website/content/docs/secrets/aws.mdx
  website/content/docs/secrets/azure.mdx
  website/content/docs/secrets/consul.mdx
  website/content/docs/secrets/cubbyhole.mdx
  website/content/docs/secrets/gcp.mdx
  website/content/docs/secrets/gcpkms.mdx
  website/content/docs/secrets/index.mdx
  website/content/docs/secrets/kmip-profiles.mdx
  website/content/docs/secrets/kmip.mdx
  website/content/docs/secrets/kubernetes.mdx
  website/content/docs/secrets/ldap.mdx
  website/content/docs/secrets/mongodbatlas.mdx
  website/content/docs/secrets/nomad.mdx
  website/content/docs/secrets/rabbitmq.mdx
  website/content/docs/secrets/terraform.mdx
  website/content/docs/secrets/totp.mdx
  website/content/docs/secrets/venafi.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29136 [DOCS] Update the PKI secrets engine docs title & description
  website/content/docs/secrets/pki/cieps.mdx
  website/content/docs/secrets/pki/cmpv2.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/secrets/pki/est.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
  website/content/docs/secrets/pki/quick-start-root-ca.mdx
  website/content/docs/secrets/pki/rotation-primitives.mdx
  website/content/docs/secrets/pki/setup.mdx
  website/content/docs/secrets/pki/troubleshooting-acme.mdx
  website/content/partials/x509-sha1-deprecation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29234 [BACKPORT] Add EDU as approvers for more granular targets
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29224 go: don't download pipeline modules when caching build modules
  scripts/go-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29231 Backport 1.18.x UI: Update PostgreSQL database params (#29200)
  changelog/29200.txt
  ui/app/models/database/connection.js
  ui/app/utils/database-helpers.js
  ui/tests/helpers/secret-engine/database-helpers.ts
  ui/tests/unit/models/database-connection-test.js
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent

#29232 Backport of [DOCS] Update the page description for SEO improvement #2 into release/1.18.x
  website/content/docs/secrets/ssh/index.mdx
  website/content/docs/secrets/ssh/one-time-ssh-passwords.mdx
  website/content/docs/secrets/ssh/signed-ssh-certificates.mdx
  website/content/docs/secrets/transform/ff3-tweak-details.mdx
  website/content/docs/secrets/transform/index.mdx
  website/content/docs/secrets/transform/tokenization.mdx
  website/content/docs/secrets/transit/index.mdx
  website/content/docs/secrets/transit/key-wrapping-guide.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29233 Backport of [DOCS] Update the title & description for SEO improvement into release/1.18.x
  website/content/docs/secrets/alicloud.mdx
  website/content/docs/secrets/aws.mdx
  website/content/docs/secrets/azure.mdx
  website/content/docs/secrets/consul.mdx
  website/content/docs/secrets/cubbyhole.mdx
  website/content/docs/secrets/gcp.mdx
  website/content/docs/secrets/gcpkms.mdx
  website/content/docs/secrets/index.mdx
  website/content/docs/secrets/kmip-profiles.mdx
  website/content/docs/secrets/kmip.mdx
  website/content/docs/secrets/kubernetes.mdx
  website/content/docs/secrets/ldap.mdx
  website/content/docs/secrets/mongodbatlas.mdx
  website/content/docs/secrets/nomad.mdx
  website/content/docs/secrets/rabbitmq.mdx
  website/content/docs/secrets/terraform.mdx
  website/content/docs/secrets/totp.mdx
  website/content/docs/secrets/venafi.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29242 [DOCS] SEO updates for config docs
  website/content/docs/configuration/adaptive-overload-protection.mdx
  website/content/docs/configuration/entropy-augmentation.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/kms-library.mdx
  website/content/docs/configuration/listener/index.mdx
  website/content/docs/configuration/listener/tcp/index.mdx
  website/content/docs/configuration/listener/unix.mdx
  website/content/docs/configuration/log-requests-level.mdx
  website/content/docs/configuration/prevent-lease-explosions.mdx
  website/content/docs/configuration/programmatic-management.mdx
  website/content/docs/configuration/replication.mdx
  website/content/docs/configuration/reporting.mdx
  website/content/docs/configuration/seal/alicloudkms.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/azurekeyvault.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/seal/index.mdx
  website/content/docs/configuration/seal/ocikms.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/configuration/seal/seal-best-practices.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
  website/content/docs/configuration/seal/transit-best-practices.mdx
  website/content/docs/configuration/seal/transit.mdx
  website/content/docs/configuration/sentinel.mdx
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/service-registration/index.mdx
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/configuration/storage/aerospike.mdx
  website/content/docs/configuration/storage/alicloudoss.mdx
  website/content/docs/configuration/storage/azure.mdx
  website/content/docs/configuration/storage/cassandra.mdx
  website/content/docs/configuration/storage/cockroachdb.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/configuration/storage/couchdb.mdx
  website/content/docs/configuration/storage/dynamodb.mdx
  website/content/docs/configuration/storage/etcd.mdx
  website/content/docs/configuration/storage/filesystem.mdx
  website/content/docs/configuration/storage/foundationdb.mdx
  website/content/docs/configuration/storage/google-cloud-spanner.mdx
  website/content/docs/configuration/storage/google-cloud-storage.mdx
  website/content/docs/configuration/storage/in-memory.mdx
  website/content/docs/configuration/storage/index.mdx
  website/content/docs/configuration/storage/manta.mdx
  website/content/docs/configuration/storage/mssql.mdx
  website/content/docs/configuration/storage/mysql.mdx
  website/content/docs/configuration/storage/oci-object-storage.mdx
  website/content/docs/configuration/storage/postgresql.mdx
  website/content/docs/configuration/storage/raft.mdx
  website/content/docs/configuration/storage/s3.mdx
  website/content/docs/configuration/storage/swift.mdx
  website/content/docs/configuration/storage/zookeeper.mdx
  website/content/docs/configuration/telemetry.mdx
  website/content/docs/configuration/ui.mdx
  website/content/docs/configuration/user-lockout.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29243 Backport of [DOCS] SEO updates for config docs into release/1.18.x
  website/content/docs/configuration/adaptive-overload-protection.mdx
  website/content/docs/configuration/entropy-augmentation.mdx
  website/content/docs/configuration/index.mdx
  website/content/docs/configuration/kms-library.mdx
  website/content/docs/configuration/listener/index.mdx
  website/content/docs/configuration/listener/tcp/index.mdx
  website/content/docs/configuration/listener/unix.mdx
  website/content/docs/configuration/log-requests-level.mdx
  website/content/docs/configuration/prevent-lease-explosions.mdx
  website/content/docs/configuration/programmatic-management.mdx
  website/content/docs/configuration/replication.mdx
  website/content/docs/configuration/reporting.mdx
  website/content/docs/configuration/seal/alicloudkms.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/azurekeyvault.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/seal/index.mdx
  website/content/docs/configuration/seal/ocikms.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/configuration/seal/seal-best-practices.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
  website/content/docs/configuration/seal/transit-best-practices.mdx
  website/content/docs/configuration/seal/transit.mdx
  website/content/docs/configuration/sentinel.mdx
  website/content/docs/configuration/service-registration/consul.mdx
  website/content/docs/configuration/service-registration/index.mdx
  website/content/docs/configuration/service-registration/kubernetes.mdx
  website/content/docs/configuration/storage/aerospike.mdx
  website/content/docs/configuration/storage/alicloudoss.mdx
  website/content/docs/configuration/storage/azure.mdx
  website/content/docs/configuration/storage/cassandra.mdx
  website/content/docs/configuration/storage/cockroachdb.mdx
  website/content/docs/configuration/storage/consul.mdx
  website/content/docs/configuration/storage/couchdb.mdx
  website/content/docs/configuration/storage/dynamodb.mdx
  website/content/docs/configuration/storage/etcd.mdx
  website/content/docs/configuration/storage/filesystem.mdx
  website/content/docs/configuration/storage/foundationdb.mdx
  website/content/docs/configuration/storage/google-cloud-spanner.mdx
  website/content/docs/configuration/storage/google-cloud-storage.mdx
  website/content/docs/configuration/storage/in-memory.mdx
  website/content/docs/configuration/storage/index.mdx
  website/content/docs/configuration/storage/manta.mdx
  website/content/docs/configuration/storage/mssql.mdx
  website/content/docs/configuration/storage/mysql.mdx
  website/content/docs/configuration/storage/oci-object-storage.mdx
  website/content/docs/configuration/storage/postgresql.mdx
  website/content/docs/configuration/storage/raft.mdx
  website/content/docs/configuration/storage/s3.mdx
  website/content/docs/configuration/storage/swift.mdx
  website/content/docs/configuration/storage/zookeeper.mdx
  website/content/docs/configuration/telemetry.mdx
  website/content/docs/configuration/ui.mdx
  website/content/docs/configuration/user-lockout.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29135 Fix key type for hybrid key creation tests
  builtin/logical/transit/path_keys_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29240 update changelog for GH-28670
  CHANGELOG.md
Labels: pr/no-changelog, hashicorp-contributed-pr

#29226 [VAULT-33146] Update tutorial link for creating a policy
  ui/app/templates/vault/cluster/policies/index.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29206 [VAULT-19467] UI Breadcrumb Title Case
  changelog/29206.txt
  ui/lib/ldap/addon/routes/libraries/library/check-out.ts
  ui/lib/ldap/addon/routes/libraries/library/details.ts
  ui/lib/ldap/addon/routes/libraries/library/edit.ts
  ui/lib/pki/addon/components/page/pki-role-details.ts
  ui/lib/pki/addon/routes/keys/index.js
  ui/lib/pki/addon/routes/keys/key/details.js
  ui/lib/pki/addon/routes/keys/key/edit.js
  ui/lib/pki/addon/routes/roles/create.js
  ui/lib/pki/addon/routes/roles/role/details.js
  ui/lib/pki/addon/routes/roles/role/edit.js
  ui/lib/pki/addon/routes/roles/role/generate.js
  ui/lib/pki/addon/routes/roles/role/sign.js
  ui/lib/pki/addon/routes/tidy/auto/configure.js
  ui/lib/pki/addon/routes/tidy/auto/index.js
  ui/lib/pki/addon/routes/tidy/manual.js
  ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
  ui/tests/integration/components/kubernetes/page/credentials-test.js
  ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
  ui/tests/integration/components/kubernetes/page/role/details-test.js
  ui/tests/integration/components/kv/kv-page-header-test.js
  ui/tests/integration/components/kv/page/kv-page-configuration-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-edit-test.js
  ui/tests/integration/components/kv/page/kv-page-secrets-create-test.js
  ui/tests/integration/components/ldap/page/library/check-out-test.js
  ui/tests/integration/components/ldap/page/library/details-test.js
  ui/tests/integration/components/ldap/page/role/credentials-test.js
  ui/tests/integration/components/ldap/page/role/details-test.js
  ui/tests/integration/components/pki/page/pki-configure-create-test.js
  ui/tests/integration/components/pki/page/pki-tidy-auto-settings-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#28703 Enable seal wrapping for approle secret storage
  builtin/credential/approle/backend.go
  changelog/28703.txt
Labels: hashicorp-contributed-pr

#29249 Revert "Run Migrations If Migration Worker has not been run #7162"
  vault/activity_log.go
  vault/activity_log_util_common.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29250 Revert "Disallow querying of activity APIs during upgrade"
  vault/logical_system_activity.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29251 Revert "Added LocalMount field to Export API"
  changelog/29145.txt
  vault/activity_log.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29245 Support all fields of the name constraints extension when generating CA certificates
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/issuing/sign_cert.go
  changelog/29245.txt
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
  website/content/api-docs/secret/pki/index.mdx
  website/content/docs/commands/pki/health-check.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: hashicorp-contributed-pr

#29252 Revert "Send Global Data From Secondary to Primary During Upgrade"
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29253 Revert "Migrate Clients From Old Storage Paths to New Paths During Upgrade #7032"
  vault/activity_log.go
  vault/activity_log_stubs_oss.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29255 Sort CA chain into root and intermediates on VerifyCertificate.
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  changelog/29255.txt
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29238 Backport of go: don't download pipeline modules when caching build modules into release/1.18.x
  scripts/go-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29257 UI: Fix open API failures for pki name constraint params
  ui/tests/acceptance/open-api-path-help-test.js
  ui/tests/helpers/openapi/expected-secret-attrs.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29254 [VAULT-33207] Update Policy Modal links to use HDS, add ACL Policies "get started" link
  ui/lib/core/addon/components/policy-example.hbs
  ui/tests/integration/components/policy-example-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29264 [VAULT-33207] Update Policy Modal to add isHrefExternal to External Links
  ui/lib/core/addon/components/policy-example.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29267 Revert "Remove all references to current fragments, standbyfragments and partialMonthTracker"
  builtin/logical/pki/acme_billing_test.go
  command/command_testonly/operator_usage_testonly_test.go
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
