Repository hashicorp/vault, pull requests merged in 2024-05, with the labels that each got.

#26692 Client count generation simplification
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26730 Updated comments
  helper/testhelpers/testhelpers.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26731 Improve the Slack CI feed message for when data races are detected in Go tests
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr

#26705 Backport of Fix heading level for Parameters in Identity/Group API doc page into release/1.14.x
  website/content/api-docs/secret/identity/group-alias.mdx
  website/content/api-docs/secret/identity/group.mdx
Labels: hashicorp-contributed-pr

#26711 Fix places where we fail to propagate storage errors
  builtin/logical/pki/cert_util.go
  vault/audit.go
  vault/auth.go
  vault/core.go
  vault/logical_system_helpers.go
  vault/login_mfa.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26622 Document tokenization DELETE
  website/content/api-docs/secret/transform.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#26706 Backport of Fix heading level for Parameters in Identity/Group API doc page into release/1.15.x
  website/content/api-docs/secret/identity/group-alias.mdx
  website/content/api-docs/secret/identity/group.mdx
Labels: hashicorp-contributed-pr

#26736 Revert "Client count generation simplification"
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26735 Fix Vault version for 1.15
  version/VERSION
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26734 Fix Vault version for 1.14
  version/VERSION
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25418 adding private DNS name as EC2 metadata
  builtin/credential/aws/path_config_identity.go
  builtin/credential/aws/path_login.go
  builtin/credential/aws/path_login_test.go
  changelog/25418.txt
Labels: ecosystem, auth/aws

#26738 Backport of Improve the Slack CI feed message for when data races are detected in Go tests into release/1.16.x
  .github/workflows/ci.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26739 Backport of Improve the Slack CI feed message for when data races are detected in Go tests into release/1.15.x
  .github/workflows/ci.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26740 Backport of Improve the Slack CI feed message for when data races are detected in Go tests into release/1.14.x
  .github/workflows/ci.yml
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26741 Update Vault version with no newline on 1.15
  version/VERSION
Labels: pr/no-changelog, hashicorp-contributed-pr

#26743 Update Vault version with no newline on 1.14
  version/VERSION
Labels: pr/no-changelog, hashicorp-contributed-pr

#26702 AOP: Force reject header (enterprise)
  http/handler.go
  http/logical.go
  http/priority/priority.go
  sdk/logical/request.go
  sdk/logical/response_util.go
  vault/request_handling.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26710 Certificate Metadata, CE components
  builtin/logical/pki/backend.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/crl_test.go
  builtin/logical/pki/crl_util.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/issuing/config_revocation.go
  builtin/logical/pki/issuing/issue_common.go
  builtin/logical/pki/metadata.pb.go
  builtin/logical/pki/metadata.proto
  builtin/logical/pki/metadata_oss.go
  builtin/logical/pki/metrics.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_revoke.go
  builtin/logical/pki/path_fetch.go
  builtin/logical/pki/path_issue_sign.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_resign_crls.go
  builtin/logical/pki/path_revoke.go
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/secret_certs.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26700 Add policy creation to AppRole setup
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26165 [DOCS]docs/Update cert.mdx
  website/content/api-docs/auth/cert.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25835 [DOCS]update events.mdx
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#24539 Update metrics.mdx
  website/content/api-docs/system/metrics.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x

#24457 Update vault-ha-upgrade.mdx to not step-down during upgrades
  website/content/docs/upgrading/vault-ha-upgrade.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, content-lgtm, backport/1.15.x

#24152 added documentation for mongodb atlas database secrets engine eventua…
  changelog/24152.txt
  website/content/docs/secrets/databases/mongodbatlas.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, content-lgtm, backport/1.15.x

#24341 Add link for Priority matching in Policies.
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, content-lgtm, backport/1.15.x

#26764 Upgrade consul-template version
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone

#23569 Link to deprecation notice page in upgrade guide
  website/content/docs/upgrading/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, content-lgtm, backport/1.15.x

#23275 Docs - Updated info on seal-rewrap during seal migration
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, content-lgtm, backport/1.15.x

#25119 Fix "auto unseal" case inconsistency
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#26770 Backport of Docs - Updated info on seal-rewrap during seal migration into release/1.15.x
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26767 Backport of Link to deprecation notice page in upgrade guide into release/1.15.x
  website/content/docs/upgrading/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26766 Backport of Add link for Priority matching in Policies. into release/1.15.x
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26756 Backport of [DOCS]update events.mdx into release/1.16.x
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26748 Backport of Add policy creation to AppRole setup into release/1.16.x
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26746 Backport of Add policy creation to AppRole setup into release/1.14.x
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#23274 Docs- Update info on key rotation
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x

#26769 Backport of Docs - Updated info on seal-rewrap during seal migration into release/1.14.x
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26783 Backport of Known issues: Vault Enterprise - Performance Standby nodes audit log all request headers into release/1.16.x
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/1_15-audit-vault-enterprise-perf-standby-logs-all-headers.mdx
Labels: hashicorp-contributed-pr

#26781 Client count generation simplification, take 2
  vault/logical_system_activity_write_testonly.go
  vault/logical_system_activity_write_testonly_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26712 Add stub enterprise logical system backend and init
  vault/logical_system.go
  vault/logical_system_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#24159 Update kmip.mdx
  website/content/docs/secrets/kmip.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26782 Address go format and proto linting issues
  buf.yaml
  builtin/logical/pki/metadata.pb.go
  builtin/logical/pki/metadata.proto
  builtin/logical/pki/metadata_oss.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26786 Backport of Update kmip.mdx into release/1.15.x
  website/content/docs/secrets/kmip.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26729 UI: Update dashboard client count query to use `billing_start_timestamp`
  changelog/26729.txt
  ui/app/components/clients/page/token.hbs
  ui/app/components/clients/page/token.ts
  ui/app/components/dashboard/client-count-card.hbs
  ui/app/components/dashboard/client-count-card.js
  ui/app/components/dashboard/overview.hbs
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/app/routes/vault/cluster/dashboard.js
  ui/app/templates/vault/cluster/dashboard.hbs
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/tests/acceptance/dashboard-test.js
  ui/tests/integration/components/clients/page/token-test.js
  ui/tests/integration/components/dashboard/client-count-card-test.js
  ui/tests/integration/components/dashboard/overview-test.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui, hashicorp-contributed-pr

#26761 Backport of added documentation for mongodb atlas database secrets engine eventua… into release/1.15.x
  changelog/24152.txt
  website/content/docs/secrets/databases/mongodbatlas.mdx
Labels: docs, pr/no-milestone, hashicorp-contributed-pr

#26760 Backport of added documentation for mongodb atlas database secrets engine eventua… into release/1.14.x
  changelog/24152.txt
  website/content/docs/secrets/databases/mongodbatlas.mdx
Labels: docs, pr/no-milestone, hashicorp-contributed-pr

#26790 Namespace banner bug Secrets Sync
  changelog/26790.txt
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/tests/acceptance/sync/secrets/overview-test.js
Labels: ui, hashicorp-contributed-pr, backport/1.16.x

#26789 [QT-711] Pin to latest github actions
  .github/actions/build-vault/action.yml
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/actions/set-up-go/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26758 Backport of Update vault-ha-upgrade.mdx to not step-down during upgrades into release/1.15.x
  website/content/docs/upgrading/vault-ha-upgrade.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26146 Backport of Docs: Policy Syntax page to include UI details. into release/1.16.x
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26142 Backport of changing vault.audit.log_response_failure metric doc into release/1.16.x
  website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26240 Backport of docs: Add Node.JS library reference into release/1.14.x
  website/content/api-docs/libraries.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26757 Backport of Update metrics.mdx into release/1.15.x
  website/content/api-docs/system/metrics.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26747 Backport of Add policy creation to AppRole setup into release/1.15.x
  website/content/docs/platform/servicenow/installation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26791 Backport of Namespace banner bug Secrets Sync into release/1.16.x
  changelog/26790.txt
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/tests/acceptance/sync/secrets/overview-test.js
Labels: ui, backport, hashicorp-contributed-pr

#26795 Backport of [QT-711] Pin to latest github actions into release/1.16.x
  .github/actions/build-vault/action.yml
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/actions/set-up-go/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26794 Backport of [QT-711] Pin to latest github actions into release/1.15.x
  .github/actions/build-vault/action.yml
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/actions/set-up-go/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26803 audit: log request: use `timeout` (5s)
  audit/broker.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26802 Backport of VAULT-24945: audit - add context timeout to audit request into release/1.16.x
  changelog/26616.txt
  vault/audit_broker.go
  vault/audit_broker_test.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26713 [Secrets Sync] enable access to Sync clients page for HVD clusters
  ui/app/components/clients/activity.ts
  ui/app/components/clients/attribution.js
  ui/app/components/clients/counts/error.hbs
  ui/app/components/clients/counts/nav-bar.hbs
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.hbs
  ui/app/components/clients/page/overview.ts
  ui/app/components/clients/page/sync.hbs
  ui/app/components/clients/page/sync.ts
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/app/templates/vault/cluster/clients/counts.hbs
  ui/app/templates/vault/cluster/clients/counts/overview.hbs
  ui/app/templates/vault/cluster/clients/counts/sync.hbs
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/integration/components/clients/counts/nav-bar-test.js
  ui/tests/integration/components/clients/page/sync-test.js
Labels: hashicorp-contributed-pr

#26784 ui deps: specify ember scope explicitly
  ui/lib/core/package.json
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26813 Backport 1.16.x - ui deps: specify ember scope explicitly
  ui/lib/core/package.json
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#26812 Backport 1.15.x - ui deps: specify ember scope explicitly
  ui/lib/core/package.json
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#26744 VAULT-24736 CE changes for static secret capability behaviour toggle
  command/agentproxyshared/cache/static_secret_cache_updater.go
  command/agentproxyshared/cache/static_secret_capability_manager.go
  command/agentproxyshared/cache/static_secret_capability_manager_test.go
  command/proxy.go
  command/proxy/config/config.go
  website/content/docs/agent-and-proxy/proxy/caching/static-secret-caching.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#26818 Adjust sync clients reference URL in overview page
  website/content/docs/sync/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#26825 Backport of Adjust sync clients reference URL in overview page into release/1.16.x
  website/content/docs/sync/index.mdx
Labels: hashicorp-contributed-pr

#26824 [Secrets sync] update sync test selectors
  ui/lib/core/addon/components/empty-state.hbs
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/acceptance/clients/counts/sync-test.js
  ui/tests/acceptance/mfa-login-test.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/clients/line-chart-test.js
Labels: hashicorp-contributed-pr

#26807 install ember-sinon-qunit
  ui/package.json
  ui/tests/acceptance/clients/counts-test.js
  ui/tests/acceptance/clients/counts/acme-test.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/acceptance/clients/counts/sync-test.js
  ui/tests/acceptance/enterprise-license-banner-test.js
  ui/tests/integration/components/calendar-widget-test.js
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/components/clients/line-chart-test.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/components/dashboard/client-count-card-test.js
  ui/tests/integration/components/date-dropdown-test.js
  ui/tests/integration/components/keymgmt/key-edit-test.js
  ui/tests/integration/components/kubernetes/page/credentials-test.js
  ui/tests/integration/components/license-banners-test.js
  ui/tests/test-helper.js
  ui/tests/unit/adapters/clients-activity-test.js
  ui/tests/unit/utils/timestamp-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26820 UI: Fix sync test
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/clients/counts/sync-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#26816 Update tcp.mdx
  website/content/docs/configuration/listener/tcp.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, backport/1.15.x, backport/1.16.x

#26833 Backport UI: Fix sync test (#26820)
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/clients/counts/sync-test.js
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#26836 Backport of Update tcp.mdx into release/1.16.x
  website/content/docs/configuration/listener/tcp.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26839 Backport of Fix docker image in developer quickstart into release/1.16.x
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26837 Backport of Fix docker image in developer quickstart into release/1.14.x
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26838 Backport of Fix docker image in developer quickstart into release/1.15.x
  website/content/docs/get-started/developer-qs.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26843 UI: Add 1.17 changes to upgrade alert
  ui/app/components/clients/attribution.js
  ui/app/components/clients/page/counts.ts
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/mirage/handlers/clients.js
  ui/tests/integration/components/clients/page/counts-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26814 Backport 1.14.x - ui deps: specify ember scope explicitly
  ui/lib/core/package.json
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26840 Add permissions check to show/hide activate button
  ui/app/services/flags.ts
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/acceptance/sync/secrets/overview-test.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26804 Docs: audit - tweak text to clarify auth/secrets tuning
  website/content/docs/audit/index.mdx
Labels: docs, core/audit, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26849 Backport of Docs: audit - tweak text to clarify auth/secrets tuning into release/1.14.x
  website/content/docs/audit/index.mdx
Labels: backport, docs, hashicorp-contributed-pr

#26851 Backport of Docs: audit - tweak text to clarify auth/secrets tuning into release/1.16.x
  website/content/docs/audit/index.mdx
Labels: backport, docs, hashicorp-contributed-pr

#26842 Bump cockroach-go to v2.3.8
  go.mod
  go.sum
  physical/cockroachdb/cockroachdb.go
Labels: dependencies, pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26854 Backport of Bump cockroach-go to v2.3.8 into release/1.16.x
  go.mod
  go.sum
  physical/cockroachdb/cockroachdb.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26853 Backport of Bump cockroach-go to v2.3.8 into release/1.15.x
  go.mod
  go.sum
  physical/cockroachdb/cockroachdb.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26856 linter: regenerate protobuf 1.34.1
  builtin/logical/pki/metadata.pb.go
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26855 linter: regenerate protobuf 1.34.1
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26857 linter: regenerate protobuf 1.34.1
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26858 ui: fix broken helper link for web command
  changelog/26858.txt
  ui/app/templates/components/console/log-help.hbs
Labels: hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26860 Backport of ui: fix broken helper link for web command into release/1.16.x
  changelog/26858.txt
  ui/app/templates/components/console/log-help.hbs
Labels: hashicorp-contributed-pr

#26861 NewTestCluster: default to enabling a 'discard' file audit device when none are configured
  helper/builtinplugins/builtinplugins_test.go
  vault/testing.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26708 UI: upgrade Ember to 5.4
  changelog/26708.txt
  ui/.eslintignore
  ui/.eslintrc.js
  ui/.gitignore
  ui/.prettierignore
  ui/.watchmanconfig
  ui/README.md
  ui/app/components/basic-dropdown/trigger.js
  ui/app/components/dashboard/quick-actions-card.hbs
  ui/app/helpers/-date-base.js
  ui/app/initializers/deprecation-filter.js
  ui/app/templates/application.hbs
  ui/app/templates/components/mfa/mfa-login-enforcement-form.hbs
  ui/config/ember-cli-update.json
  ui/ember-cli-build.js
  ui/lib/core/addon/components/search-select.js
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/lib/core/index.js
  ui/lib/kubernetes/addon/components/page/overview.hbs
  ui/lib/kubernetes/index.js
  ui/lib/kv/index.js
  ui/lib/kv/package.json
  ui/lib/ldap/addon/components/page/overview.hbs
  ui/lib/ldap/index.js
  ui/lib/pki/addon/components/page/pki-issuer-rotate-root.ts
  ui/lib/pki/addon/components/page/pki-overview.hbs
  ui/lib/pki/index.js
  ui/lib/pki/package.json
  ui/lib/replication/index.js
  ui/lib/sync/addon/components/secrets/page/destinations.hbs
  ui/lib/sync/index.js
  ui/package.json
  ui/tests/acceptance/access/identity/_shared-tests.js
  ui/tests/acceptance/dashboard-test.js
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/acceptance/oidc-config/clients-keys-test.js
  ui/tests/acceptance/oidc-config/providers-scopes-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/helpers/index.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/dashboard/quick-actions-card-test.js
  ui/tests/integration/components/get-credentials-card-test.js
  ui/tests/integration/components/kubernetes/page/overview-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
  ui/tests/pages/components/calendar-widget.js
  ui/vendor/string-includes.js
  ui/yarn.lock
Labels: ui, hashicorp-contributed-pr

#26863 Updated consul-template version
  changelog/26863.txt
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#26848 UI: wrap client count card in permission conditional
  changelog/26848.txt
  ui/app/adapters/clients/activity.js
  ui/app/components/dashboard/client-count-card.hbs
  ui/app/components/dashboard/client-count-card.js
  ui/app/components/dashboard/overview.hbs
  ui/app/components/dashboard/replication-card.hbs
  ui/mirage/handlers/clients.js
  ui/tests/integration/components/dashboard/client-count-card-test.js
  ui/tests/integration/components/dashboard/overview-test.js
  ui/tests/unit/adapters/clients-activity-test.js
Labels: ui, hashicorp-contributed-pr

#26869 UI: fix flaky enterprise nav test
  ui/tests/acceptance/enterprise-sidebar-nav-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26866 Backport of NewTestCluster: default to enabling a 'discard' file audit device when none are configured into release/1.15.x
  vault/testing.go
Labels: backport, test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26875 Consistency using HMAC'd vs HMAC'ed in docs
  vault/logical_system.go
  website/content/api-docs/system/config-auditing.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26777 VAULT-26466: audit - include correlation ID headers by default
  audit/headers.go
  audit/headers_test.go
  changelog/26777.txt
Labels: core/audit, do-not-merge, hashicorp-contributed-pr

#26873 bugfix: dashboard overview heading levels
  ui/app/components/dashboard/client-count-card.hbs
  ui/app/components/dashboard/learn-more-card.hbs
  ui/app/components/dashboard/quick-actions-card.hbs
  ui/app/components/dashboard/secrets-engines-card.hbs
Labels: pr/no-changelog, hashicorp-contributed-pr, a11y

#26862 bugfix: landmark elements must have unique accnames
  ui/lib/core/addon/components/toolbar-actions.hbs
  ui/lib/core/addon/components/toolbar-filters.hbs
  ui/lib/core/addon/components/toolbar.hbs
Labels: pr/no-changelog, hashicorp-contributed-pr, a11y

#26870 UI: Only include upgrades with previous versions
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/mirage/handlers/clients.js
  ui/tests/helpers/clients/client-count-helpers.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/open-api-explorer/swagger-ui-test.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26366 VAULT-24582: ACME client count regeneration
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26877 Update vault-plugin-secrets-kv to v0.18.0
  changelog/26877.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#26800 [BACKPORT] Manual cherry-pick of failed release/1.15.x backport PRs
  website/content/docs/concepts/events.mdx
  website/content/docs/concepts/seal.mdx
  website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26799 [BACKPORT] Manual cherry-pick of failed release/1.14.x backport PRs
  website/content/docs/concepts/events.mdx
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26876 Add missing delegated_auth_accessors config field to /sys/mounts/<path> response
  changelog/26876.txt
  command/secrets_enable.go
  command/secrets_enable_test.go
  command/secrets_tune_test.go
  vault/logical_system.go
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/commands/secrets/tune.mdx
Labels: hashicorp-contributed-pr, backport/1.16.x

#26884 Backport of Add missing delegated_auth_accessors config field to /sys/mounts/<path> response into release/1.16.x
  changelog/26876.txt
  command/secrets_enable.go
  command/secrets_enable_test.go
  command/secrets_tune_test.go
  vault/logical_system.go
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/commands/secrets/tune.mdx
Labels: backport, hashicorp-contributed-pr

#26886 Backport of [QT-711] actions: use next generation CRT actions into release/1.14.x
  .github/actions/build-vault/action.yml
  .github/actions/containerize/action.yml
  .github/actions/set-up-go/action.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26887 Backport of [QT-711] actions: use next generation CRT actions into release/1.15.x
  .github/actions/build-vault/action.yml
  .github/actions/containerize/action.yml
  .github/actions/set-up-go/action.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26888 Backport of [QT-711] actions: use next generation CRT actions into release/1.16.x
  .github/actions/build-vault/action.yml
  .github/actions/containerize/action.yml
  .github/actions/set-up-go/action.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26880 UI: Fix CSV header descriptions
  ui/app/components/clients/attribution.js
  ui/tests/integration/components/clients/attribution-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26879 Add NewTestLoggerWithSuffix for tests that need multiple log files
  helper/testhelpers/corehelpers/corehelpers.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#20482 Drop unused dependencies dir
  dependencies/2-25-21/deps-upgrade-output.txt
  dependencies/2-25-21/deps-upgrade.txt
  scripts/deps_upgrade.py
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26896 Upgrade vault-plugin-secrets-azure to 0.17.2 to include a bug fix for azure role creation
  changelog/26896.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr, backport/1.16.x

#26898 UI: remove slash
  ui/lib/kv/addon/components/page/list.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26899 Backport of Upgrade vault-plugin-secrets-azure to 0.17.2 to include a bug fix for azure role creation into release/1.16.x
  changelog/26896.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#26797 PKI: Allow operators to increase the maximum TTL for ACME issued certificates
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_acme_test.go
  builtin/logical/pki/path_config_acme.go
  changelog/26797.txt
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
Labels: secret/pki, hashicorp-contributed-pr

#26881 [docs] document known issue for azure secrets engine failing on role creation
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/1_16_azure-secrets-engine-client-id.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#26844 VAULT-25341 Address issue where having no permissions to renew caused auto-auth to attempt to renew with no backoff
  api/lifetime_watcher.go
  api/renewer_test.go
  changelog/26844.txt
  command/agent_test.go
  command/agentproxyshared/auth/auth.go
Labels: hashicorp-contributed-pr, backport/1.16.x

#26900 Backport of [docs] document known issue for azure secrets engine failing on role creation into release/1.16.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/1_16_azure-secrets-engine-client-id.mdx
Labels: hashicorp-contributed-pr

#26796 PKI: Change sign-intermediate to truncate notAfter by default (behavior change)
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_root.go
  builtin/logical/pki/path_sign_issuers.go
  changelog/26796.txt
  website/content/api-docs/secret/pki.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/data/docs-nav-data.json
Labels: secret/pki, hashicorp-contributed-pr

#26897 Backport of Add NewTestLoggerWithSuffix for tests that need multiple log files into release/1.16.x
  helper/testhelpers/corehelpers/corehelpers.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26903 Backport of Build the HSM binary for running ENT tests that require it. into release/1.16.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, hashicorp-contributed-pr

#26904 UI: Update typescript imports
  ui/app/app.js
  ui/package.json
  ui/types/vault/index.d.ts
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26901 Backport of VAULT-25341 Address issue where having no permissions to renew caused auto-auth to attempt to renew with no backoff into release/1.16.x
  api/lifetime_watcher.go
  api/renewer_test.go
  changelog/26844.txt
  command/agent_test.go
  command/agentproxyshared/auth/auth.go
Labels: hashicorp-contributed-pr

#26864 update changelog for HCSEC-2024-10
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26908 Update hashicorp/set-product-version to version 2
  .github/workflows/build.yml
  .github/workflows/enos-lint.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26778 VAULT-26466: audit - docs for including correlation ID headers by default
  website/content/docs/audit/index.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
Labels: docs, core/audit, pr/no-changelog, hashicorp-contributed-pr

#26911 Backport of Update hashicorp/set-product-version to version 2 into release/1.16.x
  .github/workflows/build.yml
  .github/workflows/enos-lint.yml
Labels: hashicorp-contributed-pr

#26909 Backport of Update hashicorp/set-product-version to version 2 into release/1.14.x
  .github/workflows/build.yml
  .github/workflows/enos-lint.yml
Labels: hashicorp-contributed-pr

#26910 Backport of Update hashicorp/set-product-version to version 2 into release/1.15.x
  .github/workflows/build.yml
  .github/workflows/enos-lint.yml
Labels: hashicorp-contributed-pr

#26889 Update interoperability-matrix.mdx
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#26883 Client Count Docs Change
  website/content/partials/faq/client-count/upgrading.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26913 Backport of Update interoperability-matrix.mdx into release/1.15.x
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26914 Backport of Update interoperability-matrix.mdx into release/1.16.x
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26912 Backport of Update interoperability-matrix.mdx into release/1.14.x
  website/content/docs/interoperability-matrix.mdx
  website/content/partials/alerts/beta.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26906 UI: Add max ttl to acme certificates
  ui/app/models/pki/config/acme.js
  ui/app/models/pki/sign-intermediate.js
  ui/lib/pki/addon/components/page/pki-configuration-details.hbs
  ui/tests/acceptance/open-api-path-help-test.js
  ui/tests/helpers/openapi/expected-secret-attrs.js
  ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#26917 Backport of Bump hashicorp/vault-action from 2.8.0 to 3.0.0 into release/1.16.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#26915 Backport of Bump hashicorp/vault-action from 2.8.0 to 3.0.0 into release/1.14.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#26867 Add cert metadata fields for tidy
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/fields.go
  builtin/logical/pki/metadata_oss.go
  builtin/logical/pki/path_tidy.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26916 Backport of Bump hashicorp/vault-action from 2.8.0 to 3.0.0 into release/1.15.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
Labels: hashicorp-contributed-pr

#26841 Enabling Secrets Sync for HVD
  changelog/26841.txt
  ui/app/components/auth-jwt.js
  ui/app/components/clients/activity.ts
  ui/app/components/clients/attribution.js
  ui/app/components/clients/counts/error.hbs
  ui/app/components/clients/counts/nav-bar.hbs
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.hbs
  ui/app/components/clients/page/overview.ts
  ui/app/components/clients/page/sync.hbs
  ui/app/components/clients/page/sync.ts
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/cluster.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/routes/application.js
  ui/app/routes/vault/cluster.js
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/app/services/flags.ts
  ui/app/services/version.js
  ui/app/templates/vault/cluster/auth.hbs
  ui/app/templates/vault/cluster/clients/counts.hbs
  ui/app/templates/vault/cluster/clients/counts/overview.hbs
  ui/app/templates/vault/cluster/clients/counts/sync.hbs
  ui/lib/core/addon/components/empty-state.hbs
  ui/lib/sync/addon/components/secrets/landing-cta.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/components/sync-header.ts
  ui/lib/sync/addon/routes/secrets/overview.ts
  ui/lib/sync/addon/templates/secrets/overview.hbs
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/acceptance/clients/counts/sync-test.js
  ui/tests/acceptance/managed-namespace-test.js
  ui/tests/acceptance/mfa-login-test.js
  ui/tests/acceptance/sync/secrets/overview-test.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/clients/counts/nav-bar-test.js
  ui/tests/integration/components/clients/line-chart-test.js
  ui/tests/integration/components/clients/page/sync-test.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/components/sync-status-badge-test.js
  ui/tests/integration/components/sync/secrets/landing-cta-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
  ui/tests/integration/components/sync/sync-header-test.js
  ui/tests/unit/services/flags-test.js
Labels: ui, hashicorp-contributed-pr

#26907 AOP: Make config reloadable (enterprise)
  command/server.go
  vault/core_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#26776 Backport of Docs- Update info on key rotation into release/1.15.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26752 Backport of [DOCS]docs/Update cert.mdx into release/1.16.x
  website/content/api-docs/auth/cert.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26750 Backport of [DOCS]docs/Update cert.mdx into release/1.14.x
  website/content/api-docs/auth/cert.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26751 Backport of [DOCS]docs/Update cert.mdx into release/1.15.x
  website/content/api-docs/auth/cert.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26775 Backport of Docs- Update info on key rotation into release/1.14.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26774 Backport of Docs- Update info on key rotation into release/1.13.x
  website/content/docs/configuration/seal/pkcs11.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26314 Backport of Update azurekeyvault.mdx into release/1.13.x
  website/content/docs/secrets/key-management/azurekeyvault.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#26749 Backport of [DOCS]docs/Update cert.mdx into release/1.13.x
  website/content/api-docs/auth/cert.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
