Repository hashicorp/vault, pull requests merged in 2024-08, with the labels that each got.

#27904 [docs] Document known issue with duplicate identity groups
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/duplicate-identity-groups.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27936 Backport of [docs] Document known issue with duplicate identity groups into release/1.17.x
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/duplicate-identity-groups.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#27934 Audit: Test fixes and improvements
  audit/hashstructure_test.go
  http/logical_test.go
  vault/external_tests/kv/kv_patch_test.go
  vault/external_tests/plugin/external_plugin_test.go
Labels: core/audit, test, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27937 Backport of Audit: Test fixes and improvements into release/1.17.x
  audit/hashstructure_test.go
  http/logical_test.go
  vault/external_tests/kv/kv_patch_test.go
  vault/external_tests/plugin/external_plugin_test.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27940 Backport of docs: add note on microsoft's saml auth bound attributes syntax into release/1.17.x
  website/content/docs/auth/saml.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27455 UI: Use Client Count export API
  changelog/27455.txt
  ui/app/adapters/clients/activity.js
  ui/app/components/clients/attribution.hbs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/export-button.hbs
  ui/app/components/clients/export-button.js
  ui/app/components/clients/page/overview.hbs
  ui/app/components/clients/running-total.hbs
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/app/services/download.ts
  ui/app/utils/query-param-string.js
  ui/lib/core/addon/helpers/is-empty-value.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/acceptance/oidc-provider-test.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/components/clients/export-button-test.js
  ui/tests/unit/adapters/clients-activity-test.js
  ui/tests/unit/utils/query-param-string-test.js
Labels: ui, hashicorp-contributed-pr

#27871 db/postgres: add feature flag protected sslinline configuration
  builtin/logical/database/backend_test.go
  helper/testhelpers/postgresql/postgresqlhelper.go
  plugins/database/postgresql/postgresql_test.go
  sdk/database/helper/connutil/postgres.go
  sdk/database/helper/connutil/sql.go
  sdk/helper/pluginutil/env.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#27942 Increase cert auth role cache max size
  builtin/credential/cert/backend.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27943 Backport of Increase cert auth role cache max size into release/1.17.x
  builtin/credential/cert/backend.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#27945 UI: fix export button tests
  ui/tests/integration/components/clients/export-button-test.js
  ui/tests/unit/adapters/clients-activity-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27918 Swap route settings.configure-secret-backend for nested edit and index route under secret.configuration
  changelog/27918.txt
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/controllers/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/controllers/vault/cluster/secrets/backend/configuration/index.js
  ui/app/router.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/templates/vault/cluster/secrets/backend/configuration.hbs
  ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/app/templates/vault/cluster/secrets/backend/error.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/configuration/edit-test.js
  ui/tests/acceptance/secrets/backend/cubbyhole/secret-test.js
  ui/tests/acceptance/secrets/backend/ssh/ssh-configuration-test.js
  ui/tests/acceptance/secrets/backend/ssh/ssh-test.js
Labels: ui, hashicorp-contributed-pr

#27939 VAULT-25883: Fix namespace errors with path filters on sys/internal/ui/mounts
  changelog/27939.txt
  vault/logical_system.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27951 Backport of VAULT-25883: Fix namespace errors with path filters on sys/internal/ui/mounts into release/1.17.x
  changelog/27939.txt
  vault/logical_system.go
Labels: hashicorp-contributed-pr

#27946 Add docs note about Windows paths
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27953 UI: update getOwner import
  ui/app/components/console/ui-panel.js
  ui/app/components/generated-item-list.js
  ui/app/components/raft-storage-overview.js
  ui/app/components/raft-storage-restore.js
  ui/app/services/auth.js
  ui/app/services/console.js
  ui/lib/kmip/addon/controllers/credentials/index.js
  ui/lib/kmip/addon/controllers/scope/roles.js
  ui/lib/kmip/addon/controllers/scopes/index.js
  ui/lib/kubernetes/addon/components/page/roles.js
  ui/lib/kv/addon/components/page/list.js
  ui/lib/ldap/addon/components/page/libraries.ts
  ui/lib/ldap/addon/components/page/roles.ts
  ui/lib/pki/addon/controllers/certificates/index.js
  ui/lib/pki/addon/controllers/issuers/index.js
  ui/lib/pki/addon/controllers/keys/index.js
  ui/lib/pki/addon/controllers/roles/index.js
  ui/lib/sync/addon/components/secrets/page/destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27952 Audit: rewrite audit entry formatting to improve performance
  audit/backend_noop.go
  audit/entry_formatter.go
  audit/entry_formatter_test.go
  audit/event.go
  audit/hashstructure.go
  audit/hashstructure_test.go
  audit/types.go
  changelog/27952.txt
Labels: core/audit, hashicorp-contributed-pr, backport/1.17.x

#27954 Backport of Audit: rewrite audit entry formatting to improve performance into release/1.17.x
  audit/backend_noop.go
  audit/entry_formatter.go
  audit/entry_formatter_test.go
  audit/event.go
  audit/hashstructure.go
  audit/hashstructure_test.go
  audit/types.go
  changelog/27952.txt
Labels: backport, hashicorp-contributed-pr

#27955 Audit: explain 'failure' metrics better
  website/content/partials/telemetry-metrics/vault/audit/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27909 Docs: Approle removed incorrect `token_num_uses` that's incompatible with batch
  website/content/docs/auth/approle.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27956 Backport of Audit: explain 'failure' metrics better into release/1.17.x
  website/content/partials/telemetry-metrics/vault/audit/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Labels: hashicorp-contributed-pr

#27947 [VAULT-2937] Verify the `/sys/version-history` in enos scenarios
  enos/enos-descriptions.hcl
  enos/enos-qualities.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
  enos/modules/vault_upgrade/scripts/restart-vault.sh
  enos/modules/vault_verify_version/main.tf
  enos/modules/vault_verify_version/scripts/verify-cli-version.sh
  enos/modules/vault_verify_version/scripts/verify-cluster-version.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27957 Backport of Docs: Approle removed incorrect `token_num_uses` that's incompatible with batch into release/1.17.x
  website/content/docs/auth/approle.mdx
Labels: hashicorp-contributed-pr

#27960 enos: support ancient systemd in `vault_upgrade`
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27958 Backport of [VAULT-2937] Verify the `/sys/version-history` in enos scenarios into release/1.17.x
  enos/enos-descriptions.hcl
  enos/enos-qualities.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
  enos/modules/vault_upgrade/scripts/restart-vault.sh
  enos/modules/vault_verify_version/main.tf
  enos/modules/vault_verify_version/scripts/verify-cli-version.sh
  enos/modules/vault_verify_version/scripts/verify-cluster-version.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27961 Add new GetSignerFromKeyEntry method for ent usage
  builtin/logical/pki/issuing/keys.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#27965 Backport of Pin PKI test suite to zlint v3.6.2 into release/1.17.x
  builtin/logical/pkiext/zlint_test.go
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#27963 Audit: comment updates and conditional merge
  audit/entry_formatter.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27967 Backport of Audit: comment updates and conditional merge into release/1.17.x
  audit/entry_formatter.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27502 Add link from api-docs to namespace docs
  website/content/api-docs/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27968 Update userpass CLI doc for custom path flag
  website/content/docs/auth/userpass.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27972 Backport of Update userpass CLI doc for custom path flag into release/1.17.x
  website/content/docs/auth/userpass.mdx
Labels: hashicorp-contributed-pr

#27971 docker: use alpine 3 and UBI 8 tags instead of minor version pins
  Dockerfile
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#27974 Backport of docker: use alpine 3 and UBI 8 tags instead of minor version pins into release/1.17.x
  Dockerfile
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27948 Prep for configuration.edit refactor
  ui/app/adapters/aws/lease-config.js
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/components/secret-engine/configuration-details.ts
  ui/app/components/secret-engine/configure-aws.hbs
  ui/app/components/secret-engine/configure-aws.ts
  ui/app/components/secret-engine/configure-ssh.hbs
  ui/app/components/secret-engine/configure-ssh.js
  ui/app/controllers/vault/cluster/secrets/backend/configuration/index.js
  ui/app/models/aws/lease-config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/ssh/ssh-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/secret-engine/configuration-details-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27975 Add regular (e.g. not API) doc for cross namespace
  website/content/docs/enterprise/namespaces/configure-cross-namespace-access.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27980 Backport of Add regular (e.g. not API) doc for cross namespace into release/1.17.x
  website/content/docs/enterprise/namespaces/configure-cross-namespace-access.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27986 Update vault-plugin-auth-jwt to v0.21.1
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr

#27977 Update interoperability-matrix.mdx
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27988 Backport of Update interoperability-matrix.mdx into release/1.17.x
  website/content/docs/interoperability-matrix.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27950 Update hana db pkg
  changelog/27950.txt
  go.mod
  go.sum
  website/content/docs/secrets/databases/hanadb.mdx
Labels: hashicorp-contributed-pr

#27987 Backport of enos: don't expect curl available in docker image into release/1.17.x
  enos/k8s/enos-scenario-k8s.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27969 Clarify audit log failure telemetry docs.
  website/content/partials/telemetry-metrics/vault/audit/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27991 Backport of Clarify audit log failure telemetry docs. into release/1.17.x
  website/content/partials/telemetry-metrics/vault/audit/log_request_failure.mdx
  website/content/partials/telemetry-metrics/vault/audit/log_response_failure.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#27926 Auto-rolling billing start docs PR
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/concepts/billing-start-date.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/auto-roll-billing-start-example.mdx
  website/content/partials/auto-roll-billing-start.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27995 docker: add upgrade notes for curl removal
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27992 Update auth-jwt to 0.21.1
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr

#27999 docs: fix upgrade 1.16.x
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27997 Backport of docker: add upgrade notes for curl removal into release/1.17.x
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
Labels: hashicorp-contributed-pr

#27996 UI: Update OpenAPI for JWT config
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.17.x

#28001 Backport of UI: Update OpenAPI for JWT config into release/1.17.x
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: hashicorp-contributed-pr

#27862 Client Count Docs Updates/Cleanup
  website/content/api-docs/system/internal-counters.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#27993 Docs: Kubernetes Auth Method: Update(kubernetes.mdx): k8s-tokenreview URL
  website/content/docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.17.x

#27548 Update programmatic-management.mdx to clarify Terraform prereqs
  website/content/docs/configuration/programmatic-management.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.17.x

#27978 UI: Replace getNewModel with hydrateModel when model exists
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/routes/vault/cluster/settings/auth/configure/section.js
  ui/app/services/path-help.js
  ui/lib/kmip/addon/routes/configuration.js
  ui/lib/kmip/addon/routes/configure.js
  ui/lib/kmip/addon/routes/role.js
  ui/lib/kmip/addon/routes/role/edit.js
  ui/lib/kmip/addon/routes/scope/roles.js
  ui/lib/kmip/addon/routes/scope/roles/create.js
  ui/lib/pki/addon/routes/application.js
  ui/tests/unit/services/path-help-test.js
  ui/tests/unit/services/path-helper-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27994 Backport of Auto-rolling billing start docs PR into release/1.17.x
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/concepts/billing-start-date.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/auto-roll-billing-start-example.mdx
  website/content/partials/auto-roll-billing-start.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27998 Backport of Auto-rolling billing start docs PR into release/1.16.x
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/concepts/billing-start-date.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/auto-roll-billing-start-example.mdx
  website/content/partials/auto-roll-billing-start.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28017 lint: fix misspel linter install
  .github/actions/set-up-misspell/action.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27970 Backport of Add link from api-docs to namespace docs into release/1.17.x
  website/content/api-docs/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28006 Backport of Docs: Kubernetes Auth Method: Update(kubernetes.mdx): k8s-tokenreview URL into release/1.17.x
  website/content/docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28018 Changelog for 1.17.3, 1.16.7 enterprise, 1.15.13 enterprise
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28007 Backport of Update programmatic-management.mdx to clarify Terraform prereqs into release/1.17.x
  website/content/docs/configuration/programmatic-management.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27693 Fix typo in variables.tf
  enos/modules/vault_cluster/variables.tf
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.17.x

#27675 Update 1_15-auto-upgrade.mdx
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/partials/known-issues/1_15-auto-upgrade.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27157 Update 1_16-default-policy-needs-to-be-updated.mdx
  website/content/partials/known-issues/1_16-default-policy-needs-to-be-updated.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28023 Backport of Update 1_16-default-policy-needs-to-be-updated.mdx into release/1.17.x
  website/content/partials/known-issues/1_16-default-policy-needs-to-be-updated.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27382 Edit alias_name_source explanation
  website/content/api-docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#27027 [DOCS] Correct telemetry metric name
  website/content/docs/internals/telemetry/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28026 Backport of [DOCS] Correct telemetry metric name into release/1.17.x
  website/content/docs/internals/telemetry/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#24093 Fix: typo in Vault CLI Env variables
  website/content/docs/commands/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28027 Backport of Fix: typo in Vault CLI Env variables into release/1.17.x
  website/content/docs/commands/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28025 Backport of Edit alias_name_source explanation into release/1.17.x
  website/content/api-docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28031 SDK: fix docker helper (explicitly add `iptables`)
  sdk/helper/testcluster/docker/environment.go
Labels: sdk, docker, pr/no-changelog, pr/no-milestone, ci, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28032 Backport of SDK: fix docker helper (explicitly add `iptables`) into release/1.17.x
  sdk/helper/testcluster/docker/environment.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28020 Backport of Fix typo in variables.tf into release/1.17.x
  enos/modules/vault_cluster/variables.tf
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28033 UI (to sidebranch) - use namespace header for CC filtering
  ui/app/adapters/clients/activity.js
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/tests/acceptance/clients/counts/acme-test.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/unit/adapters/clients-activity-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28013 [docs] document manual entity merge failures when sent to PR secondary cluster
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28037 UI [to sidebranch]: Update CC mirage filtering
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/clients/counts/acme-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28021 SSH configuration test coverage
  ui/app/components/secret-engine/configure-ssh.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/configuration/edit-test.js
  ui/tests/acceptance/secrets/backend/ssh/configuration-test.js
  ui/tests/acceptance/secrets/backend/ssh/role-test.js
  ui/tests/acceptance/secrets/backend/ssh/roles-test.js
  ui/tests/acceptance/secrets/backend/ssh/ssh-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/secret-engine/configure-ssh-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#28035 Backport of [docs] document manual entity merge failures when sent to PR secondary cluster into release/1.17.x
  website/content/docs/release-notes/1.15.0.mdx
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
Labels: hashicorp-contributed-pr

#28034 Backport of pass nil function when no externalID (this matches old functionality) into release/1.17.x
  builtin/credential/aws/client.go
  changelog/27858.txt
Labels: hashicorp-contributed-pr

#28016 Update vault-plugin-secrets-terraform to v0.9.0
  changelog/28016.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.17.x

#28038 [Docs] Add cross referencing link to AppRole usage best practices
  website/content/docs/auth/approle.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28041 Backport of [Docs] Add cross referencing link to AppRole usage best practices into release/1.17.x
  website/content/docs/auth/approle.mdx
Labels: hashicorp-contributed-pr

#19064 Core: CLI Doc improvements to example read / write.
  changelog/19064.txt
  command/read.go
  command/write.go
Labels: hashicorp-contributed-pr

#28039 Audit: unexport as much as possible in the audit package
  audit/backend_file.go
  audit/backend_file_ce_test.go
  audit/backend_file_test.go
  audit/backend_noop.go
  audit/backend_socket.go
  audit/backend_socket_test.go
  audit/backend_syslog.go
  audit/backend_syslog_test.go
  audit/backend_test.go
  audit/broker.go
  audit/broker_ce.go
  audit/broker_test.go
  audit/entry_filter.go
  audit/entry_filter_test.go
  audit/entry_formatter.go
  audit/entry_formatter_config.go
  audit/entry_formatter_test.go
  audit/errors.go
  audit/event.go
  audit/event_test.go
  audit/hashstructure.go
  audit/hashstructure_test.go
  audit/headers.go
  audit/headers_test.go
  audit/nodes.go
  audit/nodes_test.go
  audit/options.go
  audit/options_test.go
  audit/sink_metric_timer.go
  audit/types.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28024 database/postgres: add inline certificate authentication fields
  builtin/logical/database/backend_test.go
  changelog/28024.txt
  helper/testhelpers/postgresql/postgresqlhelper.go
  plugins/database/mysql/connection_producer.go
  plugins/database/postgresql/postgresql.go
  plugins/database/postgresql/postgresql_test.go
  sdk/database/helper/connutil/cloudsql.go
  sdk/database/helper/connutil/postgres.go
  sdk/database/helper/connutil/sql.go
  sdk/go.mod
Labels: hashicorp-contributed-pr

#28042 Show Current Month When Future Month Start Date is Provided
  changelog/28042.txt
  vault/activity_log.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28022 VAULT-29739: Wait for cluster unseal before checking version history
  enos/enos-scenario-replication.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28012 VAULT-29583: Modernize default distributions in enos scenarios
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-dev-scenario-pr-replication.hcl
  enos/enos-dev-scenario-single-cluster.hcl
  enos/enos-globals.hcl
  enos/enos-samples-ce-build.hcl
  enos/enos-samples-ce-release.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/enos.vars.hcl
  enos/modules/build_artifactory_artifact/locals.tf
  enos/modules/ec2_info/main.tf
  enos/modules/install_packages/main.tf
  enos/modules/softhsm_create_vault_keys/main.tf
  enos/modules/softhsm_distribute_vault_keys/main.tf
  enos/modules/softhsm_init/main.tf
  enos/modules/softhsm_install/main.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
  enos/modules/vault_verify_version/scripts/verify-cluster-version.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28047 [DOCS] Lease troubleshooting docs review
  website/content/api-docs/auth/userpass.mdx
  website/content/docs/commands/write.mdx
  website/content/docs/configuration/create-lease-count-quota.mdx
  website/content/docs/configuration/prevent-lease-explosions.mdx
  website/content/docs/troubleshoot/generate-root-token.mdx
  website/content/docs/troubleshoot/lease-count-quota-exceeded.mdx
  website/content/docs/troubleshoot/lease-explosions.mdx
  website/content/docs/troubleshoot/lease-issues.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28045 Backport of VAULT-29739: Wait for cluster unseal before checking version history into release/1.17.x
  enos/enos-scenario-replication.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28046 Backport of VAULT-29583: Modernize default distributions in enos scenarios into release/1.17.x
  .github/workflows/test-run-enos-scenario-matrix.yml
  enos/enos-dev-scenario-pr-replication.hcl
  enos/enos-dev-scenario-single-cluster.hcl
  enos/enos-globals.hcl
  enos/enos-samples-ce-build.hcl
  enos/enos-samples-ce-release.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-replication.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
  enos/enos-variables.hcl
  enos/enos.vars.hcl
  enos/modules/build_artifactory_artifact/locals.tf
  enos/modules/ec2_info/main.tf
  enos/modules/install_packages/main.tf
  enos/modules/softhsm_create_vault_keys/main.tf
  enos/modules/softhsm_distribute_vault_keys/main.tf
  enos/modules/softhsm_init/main.tf
  enos/modules/softhsm_install/main.tf
  enos/modules/vault_cluster/main.tf
  enos/modules/vault_upgrade/scripts/maybe-remove-old-unit-file.sh
  enos/modules/vault_verify_version/scripts/verify-cluster-version.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28028 [Docs] Create 'Troubleshoot' section
  website/content/api-docs/auth/userpass.mdx
  website/content/docs/commands/write.mdx
  website/content/docs/concepts/lease-count-quota-exceeded.mdx
  website/content/docs/concepts/lease-explosions.mdx
  website/content/docs/configuration/create-lease-count-quota.mdx
  website/content/docs/configuration/prevent-lease-explosions.mdx
  website/content/docs/troubleshoot/generate-root-token.mdx
  website/content/docs/troubleshoot/lease-issues.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28048 Backport of [Docs] Create 'Troubleshoot' section into release/1.17.x
  website/content/api-docs/auth/userpass.mdx
  website/content/docs/commands/write.mdx
  website/content/docs/concepts/lease-count-quota-exceeded.mdx
  website/content/docs/concepts/lease-explosions.mdx
  website/content/docs/configuration/create-lease-count-quota.mdx
  website/content/docs/configuration/prevent-lease-explosions.mdx
  website/content/docs/troubleshoot/generate-root-token.mdx
  website/content/docs/troubleshoot/lease-issues.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: hashicorp-contributed-pr

#28049 enos(replication): wait for both clusters to be healthy before enabling replication
  enos/enos-scenario-replication.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28050 Backport of enos(replication): wait for both clusters to be healthy before enabling replication into release/1.17.x
  enos/enos-scenario-replication.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28052 Backport of Audit: unexport as much as possible in the audit package into release/1.17.x
  audit/backend_file.go
  audit/backend_file_ce_test.go
  audit/backend_file_test.go
  audit/backend_noop.go
  audit/backend_socket.go
  audit/backend_socket_test.go
  audit/backend_syslog.go
  audit/backend_syslog_test.go
  audit/backend_test.go
  audit/broker.go
  audit/broker_ce.go
  audit/broker_test.go
  audit/entry_filter.go
  audit/entry_filter_test.go
  audit/entry_formatter.go
  audit/entry_formatter_config.go
  audit/entry_formatter_test.go
  audit/errors.go
  audit/event.go
  audit/event_test.go
  audit/hashstructure.go
  audit/hashstructure_test.go
  audit/headers.go
  audit/headers_test.go
  audit/nodes.go
  audit/nodes_test.go
  audit/options.go
  audit/options_test.go
  audit/sink_metric_timer.go
  audit/types.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28056 Audit: logging and improvements
  audit/broker.go
  audit/sink_metric_labeler.go
  changelog/28056.txt
  go.mod
  go.sum
  internal/observability/event/sink_file.go
  internal/observability/event/sink_file_test.go
  internal/observability/event/sink_socket.go
Labels: core/audit, do-not-merge, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.17.x

#28057 Backport of Audit: logging and improvements into release/1.17.x
  audit/broker.go
  audit/sink_metric_labeler.go
  changelog/28056.txt
  go.mod
  go.sum
  internal/observability/event/sink_file.go
  internal/observability/event/sink_file_test.go
  internal/observability/event/sink_socket.go
Labels: backport, hashicorp-contributed-pr

#28051 [Docs] Minor edits - paths filter
  website/content/docs/enterprise/replication/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28058 Backport of [Docs] Minor edits - paths filter into release/1.17.x
  website/content/docs/enterprise/replication/index.mdx
Labels: hashicorp-contributed-pr

#28040 Backport of Update vault-plugin-secrets-terraform to v0.9.0 into release/1.17.x
  changelog/28016.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#27923 proxy: ensure response is not nil before sanitizing
  command/agentproxyshared/cache/handler.go
Labels: agent, pr/no-changelog, pr/no-milestone, proxy

#28062 Sort namespaces, mounts, and clients before adding them to HLL
  changelog/28062.txt
  vault/activity_log_util_common.go
Labels: hashicorp-contributed-pr

#28055 Backport of VAULT-24636: Add new methods for MFA Login Enforcement configurations by ID into release/1.17.x
  vault/login_mfa.go
Labels: hashicorp-contributed-pr

#28065 Fix linting issue
  vault/activity_log_util_common.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28066 Backport of remove recommendations into release/1.17.x
  website/content/docs/auth/index.mdx
Labels: hashicorp-contributed-pr

#28064 Add identity info to activity export API
  changelog/28064.txt
  tools/semgrep/ci/no-nil-check.yml
  vault/activity/test_fixtures/aug.csv
  vault/activity/test_fixtures/aug_oct.csv
  vault/activity/test_fixtures/aug_sep.csv
  vault/activity/test_fixtures/aug_sep.json
  vault/activity/test_fixtures/full_history.csv
  vault/activity_log.go
  vault/activity_log_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity.go
Labels: hashicorp-contributed-pr

#28070 postgres: sanitize private_key from READ config endpoint
  builtin/logical/database/backend_test.go
  plugins/database/postgresql/postgresql.go
  plugins/database/postgresql/postgresql_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#28069 AWS test prep for WIF work
  ui/app/components/secret-engine/configure-aws.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/aws/aws-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/secret-engine/configure-aws-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#28068 VAULT-29738 CE changes for client count warning
  changelog/28068.txt
  command/operator_usage.go
  vault/logical_system_activity.go
Labels: hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28072 UI: Move Client Count Export button
  ui/app/components/clients/attribution.hbs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/page-header.hbs
  ui/app/components/clients/page-header.js
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.hbs
  ui/mirage/handlers/clients.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/components/clients/page-header-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28060 UI: Build `kv-patch-editor` form
  ui/app/components/secret-create-or-update.js
  ui/app/models/auth-method.js
  ui/app/models/secret-engine.js
  ui/app/styles/helper-classes/layout.scss
  ui/app/styles/helper-classes/typography.scss
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/utils/validators.js
  ui/lib/config-ui/addon/components/messages/preview-image.hbs
  ui/lib/core/addon/components/kv-object-editor.hbs
  ui/lib/core/addon/components/kv-object-editor.js
  ui/lib/kv/addon/components/kv-patch-editor/alerts.hbs
  ui/lib/kv/addon/components/kv-patch-editor/form.hbs
  ui/lib/kv/addon/components/kv-patch-editor/form.js
  ui/lib/kv/addon/components/kv-patch-editor/row.hbs
  ui/lib/kv/addon/components/page/secret/metadata/version-history.hbs
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/integration/components/kv/kv-patch-editor/alerts-test.js
  ui/tests/integration/components/kv/kv-patch-editor/form-test.js
  ui/tests/integration/components/kv/kv-patch-editor/row-test.js
  ui/tests/unit/utils/validators-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#27206 enos: renable undo logs verification
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_get_cluster_ips/main.tf
  enos/modules/vault_verify_undo_logs/main.tf
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
  enos/modules/vault_verify_version/scripts/verify-cli-version.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28079 Backport of enos: renable undo logs verification into release/1.17.x
  enos/enos-scenario-autopilot.hcl
  enos/modules/vault_get_cluster_ips/main.tf
  enos/modules/vault_verify_undo_logs/main.tf
  enos/modules/vault_verify_undo_logs/scripts/smoke-verify-undo-logs.sh
  enos/modules/vault_verify_version/scripts/verify-cli-version.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28067 VAULT-28638: Cost optimize the Security `scan` workflow
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.15.x+ent, backport/ent/1.16.x+ent, backport/1.17.x

#28080 CE: Added deleted namespace string
  vault/activity_log.go
  vault/activity_log_util_common.go
  website/content/api-docs/system/internal-counters.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#28084 Backport of UI: fix failing policy test into release/1.17.x
  ui/tests/acceptance/oidc-config/clients-keys-test.js
  ui/tests/acceptance/policies/index-test.js
Labels: ui, pr/no-changelog

#28071 bumping versions for grpc and docker/docker
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28081 Backport of VAULT-28638: Cost optimize the Security `scan` workflow into release/1.17.x
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28087 Fix Dockerfile LICENSE.txt path
  Dockerfile
Labels: core, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28088 1.17 Manual backport: Current month inconsistencies
  changelog/27547.txt
  changelog/28042.txt
  changelog/28062.txt
  vault/activity_log.go
  vault/activity_log_util_common.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  website/content/api-docs/system/internal-counters.mdx
Labels: hashicorp-contributed-pr

#28078 UI: Split client count attribution
  ui/app/components/clients/activity.ts
  ui/app/components/clients/attribution.hbs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/date-range.hbs
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/overview.hbs
  ui/app/components/clients/page/overview.ts
  ui/app/styles/components/chart-container.scss
  ui/app/styles/core/charts.scss
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/helpers/clients/client-count-helpers.js
  ui/tests/integration/components/clients/attribution-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28015 docs: add note for ldap auth to upgrade guide
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28092 Backport of docs: add note for ldap auth to upgrade guide into release/1.17.x
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#27924 Add LTS label instructions to PR template
  .github/pull_request_template.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28093 UI: Fix toast message text when deleting a kv v2 secret
  changelog/28093.txt
  ui/lib/kv/addon/components/page/secret/details.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
Labels: ui, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.17.x

#28082 UI: kv v2 patch plumbing: adds patch method to adapter
  ui/app/adapters/kv/data.js
  ui/app/models/kv/data.js
  ui/app/utils/kv-path.ts
  ui/app/utils/query-param-string.js
  ui/tests/unit/adapters/kv/data-test.js
  ui/tests/unit/utils/kv-path-test.js
  ui/tests/unit/utils/query-param-string-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#28094 Backport of UI: Fix toast message text when deleting a kv v2 secret into release/1.17.x
  changelog/28093.txt
  ui/lib/kv/addon/components/page/secret/details.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-delete-test.js
Labels: hashicorp-contributed-pr

#28099 Backport of Bump actions/upload-artifact from 4.3.3 to 4.3.6 into release/1.17.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28100 Backport of Bump actions/setup-go from 5.0.1 to 5.0.2 into release/1.17.x
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28097 Backport of bumping versions for grpc and docker/docker into 1.17.x
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28102 treat all errors as part of the same variadic set of arguments
  audit/broker.go
Labels: core/audit, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.17.x

#28103 Backport of treat all errors as part of the same variadic set of arguments into release/1.17.x
  audit/broker.go
Labels: backport, hashicorp-contributed-pr

#28105 Backport of Fix linting issue into release/1.17.x
  vault/activity_log_util_common.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#28108 updating versions on remaining occurances of upload-artifact
  .github/actions/build-vault/action.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28109 Backport of updating remaining occurances of upload-artifact into release/1.17.x
  .github/actions/build-vault/action.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28107 scan: skip running if the PR head is a fork
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28111 Backport of Updating remaining occurances of setup-go into release/1.17.x
  .github/actions/set-up-go/action.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28110 Updating remaining occurances of setup-go
  .github/actions/set-up-go/action.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28106 UI: Build KV v2 overview page
  ui/app/models/kv/metadata.js
  ui/lib/core/addon/components/json-editor.js
  ui/lib/core/addon/components/overview-card.hbs
  ui/lib/core/addon/helpers/date-format.js
  ui/lib/core/addon/helpers/date-from-now.js
  ui/lib/core/app/helpers/date-from-now.js
  ui/lib/kv/addon/components/kv-paths-card.hbs
  ui/lib/kv/addon/components/kv-paths-card.js
  ui/lib/kv/addon/components/kv-subkeys.hbs
  ui/lib/kv/addon/components/page/secret/overview.hbs
  ui/lib/kv/addon/components/page/secret/overview.js
  ui/lib/kv/addon/components/page/secret/paths.hbs
  ui/lib/pki/addon/components/page/pki-overview.hbs
  ui/tests/acceptance/pki/pki-overview-test.js
  ui/tests/acceptance/sync/secrets/overview-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/kv/kv-run-commands.js
  ui/tests/helpers/pki/pki-selectors.ts
  ui/tests/integration/components/kv/kv-paths-card-test.js
  ui/tests/integration/components/kv/page/kv-page-overview-test.js
  ui/tests/integration/components/kv/page/kv-page-secret-paths-test.js
  ui/tests/integration/components/overview-card-test.js
  ui/tests/integration/components/pki/page/pki-overview-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
  ui/tests/integration/helpers/date-format-test.js
  ui/tests/integration/helpers/date-from-now-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#28113 Backport of Bump actions/download-artifact from 4.1.7 to 4.1.8 into release/1.17.x
  .github/workflows/ci.yml
  .github/workflows/enos-run-k8s.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28112 Add valid IP callout
  website/content/docs/configuration/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.17.x

#28116 Backport of Add valid IP callout into release/1.17.x
  website/content/docs/configuration/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28104 Backport of VAULT-28329: Fix `months` activity log counts when querying for a namespace into release/1.17.x
  changelog/27790.txt
  vault/activity_log.go
Labels: hashicorp-contributed-pr

#28090 Backport of Fix Dockerfile LICENSE.txt path into release/1.17.x
  Dockerfile
Labels: pr/no-milestone, hashicorp-contributed-pr

#28096 UI: Client Count remove client-side namespace filtering
  ui/app/components/clients/activity.ts
  ui/app/components/clients/page/acme.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.ts
  ui/app/components/clients/page/sync.hbs
  ui/app/components/clients/page/token.hbs
  ui/app/components/clients/page/token.ts
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/tests/acceptance/clients/counts/acme-test.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/helpers/clients/client-count-helpers.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/integration/components/clients/page/acme-test.js
  ui/tests/integration/components/clients/page/sync-test.js
  ui/tests/integration/components/clients/page/token-test.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#28122 Refactor SSH Configuration workflow
  ui/app/adapters/secret-engine.js
  ui/app/adapters/ssh/ca-config.js
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/components/secret-engine/configure-ssh.hbs
  ui/app/components/secret-engine/configure-ssh.js
  ui/app/components/secret-engine/configure-ssh.ts
  ui/app/controllers/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/models/secret-engine.js
  ui/app/models/ssh/ca-config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs
  ui/tests/acceptance/secrets/backend/ssh/configuration-test.js
  ui/tests/acceptance/secrets/backend/ssh/roles-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-ssh-test.js
  ui/tests/unit/adapters/secret-engine-test.js
  ui/tests/unit/models/secret-engine-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#28089 Bump vault-gcp-secrets-plugin
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone

#28115 Backport of Bump actions/setup-node from 4.0.2 to 4.0.3 into release/1.17.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
