Repository hashicorp/vault, pull requests merged in 2024-03, with the labels that each got.

#25566 Backport of openapi: Fix response fields for rekey operations into release/1.14.x
  changelog/25509.txt
  vault/logical_system_paths.go
Labels: pr/no-milestone, hashicorp-contributed-pr, vault-update

#21000 Backport of openapi: Fix generated types for duration strings into release/1.14.x
  changelog/20841.txt
  sdk/framework/openapi.go
Labels: pr/no-milestone, hashicorp-contributed-pr, vault-update

#25713 VAULT-17555: Secret sync client metrics
  changelog/25713.txt
  helper/metricsutil/wrapped_metrics.go
  vault/activity_log.go
  vault/activity_log_test.go
Labels: hashicorp-contributed-pr, backport/1.16.x

#25741 Backport of VAULT-17555: Secret sync client metrics into release/1.16.x
  changelog/25713.txt
  helper/metricsutil/wrapped_metrics.go
  vault/activity_log.go
  vault/activity_log_test.go
Labels: hashicorp-contributed-pr

#25742 Update changelog for audit filtering
  changelog/24558.txt
Labels: pr/no-changelog, hashicorp-contributed-pr

#25730 Backport of Add new /sys/well-known interface to get information about registered labels into release/1.16.x
  vault/logical_system.go
  vault/logical_system_paths.go
  vault/logical_system_test.go
  vault/well_known_redirect.go
  website/content/api-docs/system/well-known.mdx
  website/data/api-docs-nav-data.json
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#25748 remove _ from server info
  command/server.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25746 docs: update proxy auto-auth recommendations
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
Labels: docs, hashicorp-contributed-pr, backport/1.16.x

#25750 Backport of remove _ from server info into release/1.16.x
  command/server.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25735 Redact Sensitive Info Only When Token Is Not Present
  http/sys_health.go
  http/sys_leader.go
  http/sys_seal.go
  http/sys_seal_test.go
  sdk/helper/testcluster/docker/environment.go
  sdk/helper/testcluster/types.go
  vault/core.go
  vault/logical_system.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25756 Backport of fix VAULT-24372 into release/1.16.x
  http/handler.go
  http/sys_leader.go
  http/util.go
  sdk/logical/request.go
  vault/logical_system.go
  vault/logical_system_test.go
  vault/request_handling.go
Labels: hashicorp-contributed-pr

#25759 Backport of Add notes around OCSP GET request issue into release/1.16.x
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/ocsp-redirect.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25728 Changelog for 1.14.10 and 1.15.6
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25755 Backport of VAULT-24439: Make sys/config/ui/custom-messages enterprise paths into release/1.16.x
  vault/logical_system.go
  website/content/api-docs/system/config-ui-custom-messages.mdx
  website/content/api-docs/system/internal-ui-authenticated-messages.mdx
  website/content/api-docs/system/internal-ui-unauthenticated-messages.mdx
  website/data/api-docs-nav-data.json
Labels: hashicorp-contributed-pr

#25754 Manual Backport Redact with Valid token
  http/sys_health.go
  http/sys_leader.go
  http/sys_seal.go
  http/sys_seal_test.go
  sdk/helper/testcluster/docker/environment.go
  sdk/helper/testcluster/types.go
  vault/core.go
  vault/logical_system.go
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25694 docs: add templated policies workflow example to kubernetes auth
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25760 Backport of docs: add templated policies workflow example to kubernetes auth into release/1.16.x
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25751 VAULT-24556: add secret syncs to vault operator usage output
  changelog/25751.txt
  command/command_testonly/operator_usage_testonly_test.go
  command/operator_usage.go
Labels: hashicorp-contributed-pr

#25761 Backport of VAULT-24556: add secret syncs to vault operator usage output into release/1.16.x
  changelog/25751.txt
  command/command_testonly/operator_usage_testonly_test.go
  command/operator_usage.go
Labels: hashicorp-contributed-pr

#25758 Backport of Add notes around OCSP GET request issue into release/1.15.x
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/upgrading/upgrade-to-1.12.x.mdx
  website/content/docs/upgrading/upgrade-to-1.13.x.mdx
  website/content/docs/upgrading/upgrade-to-1.14.x.mdx
  website/content/docs/upgrading/upgrade-to-1.15.x.mdx
  website/content/partials/known-issues/ocsp-redirect.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25740 Sync Associations ID Format
  ui/app/adapters/sync/association.js
  ui/app/serializers/sync/association.js
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25765 Backport of Sync Associations ID Format into release/1.16.x
  ui/app/adapters/sync/association.js
  ui/app/serializers/sync/association.js
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
Labels: ui, hashicorp-contributed-pr

#25744 Move default token helper to api
  .gitignore
  api/cliconfig/config.go
  api/cliconfig/config_test.go
  api/cliconfig/testdata/config.hcl
  api/cliconfig/util.go
  api/go.mod
  api/go.sum
  api/tokenhelper/helper.go
  api/tokenhelper/helper_external.go
  api/tokenhelper/helper_external_test.go
  api/tokenhelper/helper_internal.go
  api/tokenhelper/helper_internal_test.go
  api/tokenhelper/testing.go
  changelog/25744.txt
  command/base.go
  command/base_predict.go
  command/config.go
  command/config/util.go
  command/config_test.go
  command/main.go
  command/token/helper_testing.go
  command/token/testing.go
  command/util.go
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#25769 Backport of Remove the available in language, since our docs are versioned now into release/1.15.x
  website/content/api-docs/system/unseal.mdx
Labels: docs, hashicorp-contributed-pr

#25770 Backport of Remove the available in language, since our docs are versioned now into release/1.16.x
  website/content/api-docs/system/unseal.mdx
Labels: docs, hashicorp-contributed-pr

#25768 Backport of Remove the available in language, since our docs are versioned now into release/1.14.x
  website/content/api-docs/system/unseal.mdx
Labels: docs, hashicorp-contributed-pr

#25771 Fix lock issue for Agent and Proxy
  command/agent.go
  command/proxy.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25772 Backport of Fix lock issue for Agent and Proxy into release/1.16.x
  command/agent.go
  command/proxy.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25773 Add semgrep lock rules
  tools/semgrep/ci/lock-not-unlocked-on-return.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25776 Backport of UI: Add missing auth config params into release/1.16.x
  changelog/25646.txt
  ui/app/components/auth-config-form/options.js
  ui/app/models/auth-method.js
  ui/app/models/mount-config.js
  ui/app/templates/components/auth-config-form/options.hbs
  ui/tests/helpers/general-selectors.js
  ui/tests/integration/components/auth-config-form/options-test.js
  ui/tests/pages/components/auth-config-form/options.js
Labels: ui, hashicorp-contributed-pr

#25733 UI: Return upgrade banner to refactored client count UI
  ui/app/components/clients/activity.ts
  ui/app/components/clients/attribution.hbs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/charts/line.ts
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.hbs
  ui/app/templates/vault/cluster/clients/counts.hbs
  ui/lib/core/addon/utils/client-count-utils.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/clients/counts-test.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/clients/page/sync-test.js
  ui/tests/integration/components/clients/page/token-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25779 Backport of UI: Return upgrade banner to refactored client count UI into release/1.16.x
  ui/app/components/clients/activity.ts
  ui/app/components/clients/attribution.hbs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/charts/line.ts
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.hbs
  ui/app/templates/vault/cluster/clients/counts.hbs
  ui/lib/core/addon/utils/client-count-utils.js
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/clients/counts-test.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/helpers/clients.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/clients/page/sync-test.js
  ui/tests/integration/components/clients/page/token-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: hashicorp-contributed-pr

#25782 Add test data file to fix ent-only unit test
  .gitignore
  command/test-fixtures/config.hcl
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25766 UI: Correctly call resultant-acl endpoint when user root is root
  changelog/25766.txt
  ui/app/adapters/permissions.js
  ui/tests/unit/adapters/permissions-test.js
Labels: ui, bug, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25743 Documentation: WAF: add merkle-check documentation
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25714 Backport of Stub for namespace cache warming fix into release/1.15.x
  vault/auth.go
  vault/mount.go
  vault/namespaces.go
Labels: hashicorp-contributed-pr

#25715 Backport of Stub for namespace cache warming fix into release/1.16.x
  vault/auth.go
  vault/mount.go
  vault/namespaces.go
Labels: hashicorp-contributed-pr

#25797 Backport of Documentation: WAF: add merkle-check documentation into release/1.16.x
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#25793 Fix duplication of OpenAPI operation ids in sys/well-known list apis
  vault/logical_system_paths.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25800 Backport of Fix duplication of OpenAPI operation ids in sys/well-known list apis into release/1.16.x
  vault/logical_system_paths.go
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#25802 events: Race condition in filter
  vault/eventbus/filter.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25803 Backport of events: Race condition in filter into release/1.16.x
  vault/eventbus/filter.go
Labels: hashicorp-contributed-pr

#25792 Extra information about how to escape an @ as the first char in kv value
  website/content/docs/commands/index.mdx
Labels: docs, command, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25727 Backport of Add a fuller example of a Seal HA compatible seal stanza into release/1.16.x
  website/content/docs/configuration/seal/seal-ha.mdx
Labels: hashicorp-contributed-pr

#25749 fix "Vault as a service" reference in namespace docs
  website/content/docs/enterprise/namespaces/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25682 docs/vault-secrets-operator: supported openshift versions and OperatorHub options
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25811 Backport of docs/vault-secrets-operator: supported openshift versions and OperatorHub options into release/1.15.x
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: hashicorp-contributed-pr

#25812 Backport of docs/vault-secrets-operator: supported openshift versions and OperatorHub options into release/1.16.x
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: hashicorp-contributed-pr

#25805 Backport of Extra information about how to escape an @ as the first char in kv value into release/1.14.x
  website/content/docs/commands/index.mdx
Labels: backport, hashicorp-contributed-pr

#25806 Backport of Extra information about how to escape an @ as the first char in kv value into release/1.15.x
  website/content/docs/commands/index.mdx
Labels: backport, hashicorp-contributed-pr

#25807 Backport of Extra information about how to escape an @ as the first char in kv value into release/1.16.x
  website/content/docs/commands/index.mdx
Labels: backport, hashicorp-contributed-pr

#25676 [DOCS] Edits to audit filtering overview
  website/content/docs/concepts/filtering/audit.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25813 Backport of [DOCS] Edits to audit filtering overview into release/1.16.x
  website/content/docs/concepts/filtering/audit.mdx
Labels: hashicorp-contributed-pr

#25819 Backport of Do not refresh seal-wrapped values when there are unhealthy seals. into release/1.16.x
  vault/seal/seal.go
  website/content/docs/concepts/seal.mdx
  website/content/docs/configuration/seal/seal-ha.mdx
Labels: hashicorp-contributed-pr

#25821 Backport of Documentation: WAF: add merkle-check documentation into release/1.14.x
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/data/docs-nav-data.json
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25822 Backport of Documentation: WAF: add merkle-check documentation into release/1.13.x
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/data/docs-nav-data.json
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25820 Documentation: Backport of WAF: add merkle-check documentation into release/1.15.x
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/data/docs-nav-data.json
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25818 Backport of Do not refresh seal-wrapped values when there are unhealthy seals. into release/1.15.x
  vault/seal/seal.go
  website/content/docs/concepts/seal.mdx
Labels: hashicorp-contributed-pr

#25824 Backport of VAULT-24450: Make Audit Filtering 'Enterprise Only' in documentation into release/1.16.x
  website/content/docs/concepts/filtering.mdx
  website/content/docs/enterprise/audit/filtering.mdx
  website/content/partials/audit-options-common.mdx
  website/content/partials/telemetry-metrics/vault/audit/fallback_miss.mdx
  website/content/partials/telemetry-metrics/vault/audit/fallback_success.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#25823 [QT-683] only create artifact metadata on changes that build artifacts
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25825 lint: fix proto delta and simports
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/barrier_aes_gcm.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/seal/seal.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25829 Backport of [QT-683] only create artifact metadata on changes that build artifacts into release/1.16.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25827 Backport of [QT-683] only create artifact metadata on changes that build artifacts into release/1.14.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25828 Backport of [QT-683] only create artifact metadata on changes that build artifacts into release/1.15.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25831 lint: fix proto delta and formatting
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/seal/seal.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25830 lint: fix proto delta and formatting
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/seal/seal.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25521 PKI EST docs
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/est.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/partials/pki-est-default-policy.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25836 Backport of PKI EST docs into release/1.16.x
  website/content/api-docs/secret/pki.mdx
  website/content/docs/secrets/pki/est.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/partials/pki-est-default-policy.mdx
  website/data/docs-nav-data.json
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25786 Backport of UI: Correctly call resultant-acl endpoint when user root is root into release/1.16.x
  changelog/25766.txt
  ui/app/adapters/permissions.js
  ui/tests/unit/adapters/permissions-test.js
Labels: ui, backport, hashicorp-contributed-pr

#25775 add link to security advisory for latest releases
  CHANGELOG.md
Labels: pr/no-changelog, hashicorp-contributed-pr

#25785 Backport of UI: Correctly call resultant-acl endpoint when user root is root into release/1.15.x
  changelog/25766.txt
  ui/app/adapters/permissions.js
  ui/tests/unit/adapters/permissions-test.js
Labels: ui, backport, hashicorp-contributed-pr

#25810 Backport of fix "Vault as a service" reference in namespace docs into release/1.16.x
  website/content/docs/enterprise/namespaces/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25808 Backport of fix "Vault as a service" reference in namespace docs into release/1.14.x
  website/content/docs/enterprise/namespaces/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25837 Backport UI: fixes flaky enterprise control group test (#23911)
  ui/tests/acceptance/enterprise-control-groups-test.js
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#25739 Sync Enable Feature Workflow
  ui/lib/sync/addon/components/secrets/landing-cta.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/routes/secrets.ts
  ui/lib/sync/addon/routes/secrets/overview.ts
  ui/lib/sync/addon/templates/secrets/overview.hbs
  ui/mirage/handlers/sync.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/landing-cta-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25706 docs: adds enterprise documentation for plugin wif
  website/content/api-docs/secret/aws.mdx
  website/content/api-docs/secret/identity/tokens.mdx
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25790 docs/vault-k8s injector: update for v1.4.0 release
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25844 Backport of docs/vault-k8s injector: update for v1.4.0 release into release/1.15.x
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: hashicorp-contributed-pr

#25845 Backport of docs/vault-k8s injector: update for v1.4.0 release into release/1.16.x
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: hashicorp-contributed-pr

#25604 Docs: New plugins pinned versions APIs
  website/content/api-docs/system/plugins-pins.mdx
  website/data/api-docs-nav-data.json
Labels: docs, website, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25846 Backport of Docs: New plugins pinned versions APIs into release/1.16.x
  website/content/api-docs/system/plugins-pins.mdx
  website/data/api-docs-nav-data.json
Labels: hashicorp-contributed-pr

#25840 Backport 1.16.x: Sync Enable Feature Workflow (#25739)
  ui/lib/sync/addon/components/secrets/landing-cta.hbs
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/routes/secrets.ts
  ui/lib/sync/addon/routes/secrets/overview.ts
  ui/lib/sync/addon/templates/secrets/overview.hbs
  ui/mirage/handlers/sync.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/sync/secrets/landing-cta-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#25767 UI: Glimmerize path-help and generated-item-adapter
  ui/app/adapters/generated-item-list.js
  ui/app/services/path-help.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25849 Secret sync modal language and link change
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25850 Backport of Secret sync modal language and link change into release/1.16.x
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
Labels: ui, backport, hashicorp-contributed-pr

#25843 Backport of docs: adds enterprise documentation for plugin wif into release/1.16.x
  website/content/api-docs/secret/aws.mdx
  website/content/api-docs/secret/identity/tokens.mdx
  website/content/docs/secrets/aws.mdx
Labels: hashicorp-contributed-pr

#25852 VAULT-23705: Enable secret sync billing
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.16.x

#25324 ci: remove re-runs logic for failed tests on release branches
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25856 Backport of ci: remove re-runs logic for failed tests on release branches into release/1.16.x
  .github/workflows/test-go.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25788 UI: Ember Deprecation - Remove A import from ember/array
  ui/app/components/mfa/mfa-login-enforcement-form.js
  ui/app/components/tool-actions-form.js
  ui/app/transforms/array.js
  ui/lib/core/addon/components/replication-actions.js
  ui/lib/core/addon/components/shamir/flow.js
  ui/lib/replication/addon/components/replication-summary.js
  ui/types/ember-cli-flash/services/flash-messages.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25857 Bump Go to 1.21.8
  .go-version
  changelog/_go-ver-1170.txt
  go.mod
Labels: pr/no-milestone, hashicorp-contributed-pr

#25858 Bump Go to 1.21.8
  .go-version
  changelog/_go-ver-1160.txt
  changelog/_go-ver-11600.txt
  go.mod
Labels: pr/no-milestone, hashicorp-contributed-pr

#25496 Fix local alias processing
  vault/identity_store.go
  vault/identity_store_structs.go
  vault/request_handling.go
  vault/request_handling_util.go
Labels: core/ha, do-not-merge, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25867 UI: Only add user lockout config for supported methods
  changelog/25867.txt
  ui/app/components/auth-config-form/options.js
  ui/app/models/auth-method.js
  ui/app/templates/components/auth-config-form/options.hbs
  ui/tests/integration/components/auth-config-form/options-test.js
Labels: hashicorp-contributed-pr, backport/1.16.x

#25863 Backport of Fix local alias processing into release/1.15.x
  vault/identity_store.go
  vault/identity_store_structs.go
  vault/request_handling.go
  vault/request_handling_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#25764 Vault-22903: add option to disable TLS in test clusters
  sdk/helper/testcluster/docker/environment.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25866 Don't ignore error from reloadSealsEnt
  vault/core.go
  vault/reload_seal_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25870 Add k8s 1.29 to the set of supported versions
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25851 UI: Ember deprecation - reopen class
  ui/app/components/auth-config-form/config.hbs
  ui/app/components/auth-config-form/config.js
  ui/app/components/auth-config-form/options.hbs
  ui/app/components/auth-config-form/options.js
  ui/app/components/section-tabs.hbs
  ui/app/components/section-tabs.js
  ui/app/lib/attach-capabilities.js
  ui/app/templates/components/wizard/mount-info.hbs
  ui/app/templates/vault/cluster/access/method/section.hbs
  ui/app/templates/vault/cluster/settings/auth/configure.hbs
  ui/app/templates/vault/cluster/settings/auth/configure/section.hbs
  ui/tests/unit/lib/attach-capabilities-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25875 Backport of Add k8s 1.29 to the set of supported versions into release/1.15.x
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25876 Backport of Add k8s 1.29 to the set of supported versions into release/1.16.x
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25879 Audit: package refactor
  audit/entry_formatter.go
  audit/entry_formatter_test.go
  audit/event.go
  audit/event_test.go
  audit/types.go
Labels: core/audit, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25880 Backport of VAULT-23089: Doc updates for secret sync billing into release/1.16.x
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/commands/operator/usage.mdx
  website/content/docs/concepts/client-count/counting.mdx
  website/content/docs/concepts/client-count/faq.mdx
  website/content/docs/concepts/client-count/index.mdx
  website/content/docs/sync/index.mdx
  website/content/partials/faq/client-count/definitions.mdx
  website/content/partials/telemetry-metrics/vault/identity/secret_sync/monthly.mdx
  website/content/partials/telemetry-metrics/vault/identity/secret_sync/reporting_period.mdx
Labels: hashicorp-contributed-pr

#25881 Backport of Audit: package refactor into release/1.16.x
  audit/entry_formatter.go
  audit/entry_formatter_test.go
  audit/event.go
  audit/event_test.go
  audit/types.go
Labels: backport, hashicorp-contributed-pr

#25874 UI: Remove leading slash from kv version 2 secret path
  changelog/25874.txt
  ui/app/utils/kv-path.ts
  ui/lib/core/app/utils/sanitize-path.js
  ui/tests/unit/utils/kv-path-test.js
Labels: ui, hashicorp-contributed-pr, backport/1.15.x

#25885 Backport of UI: Remove leading slash from kv version 2 secret path into release/1.16.x
  changelog/25874.txt
  ui/app/utils/kv-path.ts
  ui/lib/core/app/utils/sanitize-path.js
  ui/tests/unit/utils/kv-path-test.js
Labels: hashicorp-contributed-pr

#25884 Backport of UI: Remove leading slash from kv version 2 secret path into release/1.15.x
  changelog/25874.txt
  ui/app/utils/kv-path.ts
  ui/lib/core/app/utils/sanitize-path.js
  ui/tests/unit/utils/kv-path-test.js
Labels: hashicorp-contributed-pr

#25890 Backport of fix changelog formatting for vault snapshot inspector feature into release/1.16.x
  changelog/23457.txt
Labels: pr/no-milestone, hashicorp-contributed-pr

#25862 Support pre-hashed passwords with userpass backend
  builtin/credential/userpass/backend_test.go
  builtin/credential/userpass/path_user_password.go
  builtin/credential/userpass/path_user_password_test.go
  builtin/credential/userpass/path_users.go
  changelog/25862.txt
  website/content/api-docs/auth/userpass.mdx
  website/content/docs/auth/userpass.mdx
Labels: core, auth/userpass, cryptosec, pr/no-milestone, hashicorp-contributed-pr, needs-eng-review, content-lgtm

#25892 upgrade github.com/opencontainers/runc to v1.1.12
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25893 upgrade github.com/opencontainers/runc to v1.1.12
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25895 upgrade github.com/opencontainers/runc to v1.1.12
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr

#25894 Add clarification to quota docs regarding parent ns access
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/rate-limit-quotas.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25898 Backport of Add clarification to quota docs regarding parent ns access into release/1.16.x
  website/content/api-docs/system/lease-count-quotas.mdx
  website/content/api-docs/system/rate-limit-quotas.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25899 Fix typo in rate limit quota API docs
  website/content/api-docs/system/rate-limit-quotas.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.16.x

#25900 Backport of Fix typo in rate limit quota API docs into release/1.16.x
  website/content/api-docs/system/rate-limit-quotas.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25903 make fmt
  builtin/credential/userpass/path_user_password_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25859 UI: Ember deprecation - remove toArray
  ui/app/components/mfa/mfa-login-enforcement-form.js
  ui/app/components/mfa/mfa-login-enforcement-header.js
  ui/app/services/store.js
  ui/app/services/wizard.js
  ui/lib/core/addon/components/search-select-with-modal.js
  ui/lib/core/addon/components/search-select.js
  ui/mirage/handlers/mfa-config.js
  ui/tests/helpers/sync/setup-models.js
  ui/tests/integration/components/mfa-login-enforcement-form-test.js
  ui/tests/integration/components/pki-paginated-list-test.js
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
  ui/tests/unit/unload-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#25861 Updated the GRANT statement to use gv_$session instead of gv$session
  website/content/docs/secrets/databases/oracle.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.15.x, backport/1.16.x

#25477 fix(oidc/azuread): set correct oidc_scopes
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: docs, auth/azure, pr/no-changelog, pr/no-milestone, content-lgtm, backport/1.15.x

#25915 Backport of Update the AD to LDAP migration guide with a note about lazy vs automatic password rotation into release/1.16.x
  website/content/docs/secrets/ad/migration-guide.mdx
Labels: hashicorp-contributed-pr

#25913 Backport of Update the AD to LDAP migration guide with a note about lazy vs automatic password rotation into release/1.14.x
  website/content/docs/secrets/ad/migration-guide.mdx
Labels: hashicorp-contributed-pr

#25916 Backport of fix(oidc/azuread): set correct oidc_scopes into release/1.15.x
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: hashicorp-contributed-pr

#25917 Backport of Update gcpkms.mdx "Added a new role required for keymgmt engine GCP's key Import" into release/1.15.x
  website/content/docs/secrets/key-management/gcpkms.mdx
Labels: hashicorp-contributed-pr

#25914 Backport of Update the AD to LDAP migration guide with a note about lazy vs automatic password rotation into release/1.15.x
  website/content/docs/secrets/ad/migration-guide.mdx
Labels: hashicorp-contributed-pr

#25896 fix azuread doc user_claim must be sub
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.15.x, backport/1.16.x

#25918 Backport of fix azuread doc user_claim must be sub into release/1.15.x
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: hashicorp-contributed-pr

#25919 Backport of fix azuread doc user_claim must be sub into release/1.16.x
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
Labels: hashicorp-contributed-pr

#25891 SSCT: updated docs
  website/content/docs/faq/ssct.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25582 Editorial changes to control-groups.mdx
  website/content/docs/enterprise/control-groups.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, content-lgtm, backport/1.15.x, backport/1.16.x

#25920 Backport of SSCT: updated docs into release/1.14.x
  website/content/docs/faq/ssct.mdx
Labels: hashicorp-contributed-pr

#25921 Backport of SSCT: updated docs into release/1.15.x
  website/content/docs/faq/ssct.mdx
Labels: hashicorp-contributed-pr

#25922 Backport of SSCT: updated docs into release/1.16.x
  website/content/docs/faq/ssct.mdx
Labels: hashicorp-contributed-pr

#25923 Backport of Editorial changes to control-groups.mdx into release/1.15.x
  website/content/docs/enterprise/control-groups.mdx
Labels: hashicorp-contributed-pr

#25926 Backport of Docs: New parameter for the Kubernetes Secrets roles into release/1.15.x
  website/content/api-docs/secret/kubernetes.mdx
Labels: hashicorp-contributed-pr

#25925 Patch 2
  website/content/docs/deprecation/index.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, content-lgtm

#23910 Correcting Sample Request to use token and POST
  website/content/api-docs/system/replication/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.13.x, backport/1.14.x, content-lgtm, backport/1.15.x

#25928 Backport of Correcting Sample Request to use token and POST into release/1.14.x
  website/content/api-docs/system/replication/index.mdx
Labels: hashicorp-contributed-pr

#25929 Backport of Correcting Sample Request to use token and POST into release/1.15.x
  website/content/api-docs/system/replication/index.mdx
Labels: hashicorp-contributed-pr

#25927 Backport of Correcting Sample Request to use token and POST into release/1.13.x
  website/content/api-docs/system/replication/index.mdx
Labels: hashicorp-contributed-pr

#25860 remove repetitive words
  builtin/credential/aws/path_role.go
  internalshared/configutil/userlockout.go
  physical/dynamodb/dynamodb.go
  physical/postgresql/postgresql_test.go
  physical/raft/raft.go
  sdk/framework/path.go
  sdk/logical/error.go
  ui/README.md
  vault/core.go
  vault/token_store.go
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.14.x, backport/1.15.x, backport/1.16.x

#25933 Backport of VAULT-24413: Don't run `Create or update a build status comment on the pull request` on community PRs for CE `vault` repo into release/1.15.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25935 Backport of VAULT-24413: Don't run `Create or update a build status comment on the pull request` on community PRs for CE `vault` repo into release/1.16.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25932 Backport of remove repetitive words into release/1.16.x
  builtin/credential/aws/path_role.go
  internalshared/configutil/userlockout.go
  physical/dynamodb/dynamodb.go
  physical/postgresql/postgresql_test.go
  physical/raft/raft.go
  sdk/framework/path.go
  sdk/logical/error.go
  ui/README.md
  vault/core.go
  vault/token_store.go
Labels: hashicorp-contributed-pr

#25937 Update vault-plugin-auth-jwt to v0.20.1
  changelog/25937.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.16.x

#25906 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#25938 Backport of Update vault-plugin-auth-jwt to v0.20.1 into release/1.16.x
  changelog/25937.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#25939 Update docs for VSO v0.5.2
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.15.x, backport/1.16.x

#25942 Backport of Update docs for VSO v0.5.2 into release/1.16.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#25941 Backport of Update docs for VSO v0.5.2 into release/1.15.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr
