Repository hashicorp/vault, pull requests merged in 2025-06, with the labels that each got.

#30466 core metrics changes
  vault/core_metrics.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30800 UI: Fix direct login link for auth mounts
  ui/app/components/auth-config-form/options.hbs
  ui/app/components/auth-config-form/options.js
  ui/app/components/auth/page.ts
  ui/app/models/auth-method.js
  ui/app/templates/components/auth-method/configuration.hbs
  ui/lib/config-ui/addon/components/login-settings/page/list.hbs
  ui/tests/acceptance/settings/auth/enable-test.js
  ui/tests/integration/components/auth-method/configuration-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30797 Update vault-plugin-database-redis to v0.6.0
  changelog/30797.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30805 UI: Fixes issue where backup tab was selected if they included default type
  ui/app/components/auth/page.ts
  ui/tests/acceptance/config-ui/login-settings-test.js
  ui/tests/integration/components/auth/page-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#30687 upgrade known issue documentation with fix version for roles with skip_import_rotation=true
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30813 enos(auth/ldap): update ldap auth config on random node in cluster
  enos/modules/verify_secrets_engines/modules/create/auth.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30819 Update vault-plugin-secrets-ad to v0.21.0
  changelog/30819.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30814 Backport of upgrade known issue documentation with fix version for roles with skip_import_rotation=true into release/1.18.x
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30812 Backport of upgrade known issue documentation with fix version for roles with skip_import_rotation=true into release/1.19.x
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30716 Backport of Update operations-qs.mdx into release/1.19.x
  website/content/docs/get-started/operations-qs.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30791 [UI] Ember Data Migration - Secrets Engine Resource
  ui/app/components/dashboard/secrets-engines-card.ts
  ui/app/components/dashboard/vault-configuration-details-card.hbs
  ui/app/components/dashboard/vault-configuration-details-card.js
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/components/secret-engine/configuration-details.ts
  ui/app/components/secret-engine/list.ts
  ui/app/controllers/vault/cluster/secrets/backend/configuration/index.js
  ui/app/resources/base-factory.ts
  ui/app/resources/secrets/engine.ts
  ui/app/routes/vault/cluster/dashboard.js
  ui/app/routes/vault/cluster/secrets/backend.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backends.ts
  ui/app/services/api.ts
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/secrets-engine-mount-config.ts
  ui/lib/kubernetes/addon/components/page/configuration.hbs
  ui/lib/kv/addon/routes/configuration.js
  ui/lib/ldap/addon/components/page/configuration.hbs
  ui/lib/pki/addon/templates/configuration/index.hbs
  ui/tests/acceptance/dashboard-test.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/list-test.js
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-ssh-test.js
  ui/tests/integration/components/secrets-engine-mount-config-test.js
  ui/types/vault/secrets/engine.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30795 added loaded snapshot metrics docs
  website/content/docs/license/product-usage-reporting.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30832 Update vault-plugin-secrets-azure to v0.22.0
  changelog/30832.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30835 Update vault-plugin-secrets-gcpkms to v0.21.0
  changelog/30835.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30834 [VAULT-35682] build(cgo): Build CGO binaries in a container
  .build/entrypoint.sh
  .build/go.sh
  .build/system.sh
  .github/actions/build-vault/action.yml
  .github/actions/metadata/action.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  Dockerfile
  tools/pipeline/internal/pkg/changed/checkers.go
  tools/pipeline/internal/pkg/changed/checkers_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30836 Update vault-plugin-database-couchbase to v0.14.0
  changelog/30836.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30807 VAULT-36495 CE changes
  vault/acl.go
  vault/observations/observations_consts.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30718 Add 192 to the list of key sizes supported in the docs.
  website/content/api-docs/secret/transit.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30838 UI: Fix error handling so users are redirected to log in when token expires if using Vault as an OIDC provider
  changelog/30838.txt
  ui/app/routes/vault/cluster/oidc-provider.js
  ui/tests/acceptance/oidc-provider-test.js
Labels: hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30856 Update vault-plugin-database-mongodbatlas to v0.15.0
  changelog/30856.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30855 Update vault-plugin-secrets-kubernetes to v0.11.0
  changelog/30855.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30794 VAULT-36229: Nonce for rekey cancellations
  api/sys_rekey.go
  changelog/30794.txt
  command/operator_rekey.go
  command/operator_rekey_test.go
  http/http_test.go
  http/sys_rekey.go
  http/sys_rekey_test.go
  vault/rekey.go
  vault/rekey_test.go
  vault/seal_config.go
  website/content/api-docs/system/rekey-recovery-key.mdx
  website/content/api-docs/system/rekey.mdx
  website/content/docs/updates/important-changes.mdx
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30863 Use new sdk and api versions for v1.20
  go.mod
Labels: pr/no-changelog, hashicorp-contributed-pr

#30848 UI: Update `namespace` key to `namespace_path`
  ui/lib/config-ui/addon/components/login-settings/page/details.js
  ui/lib/config-ui/addon/components/login-settings/page/list.hbs
  ui/tests/acceptance/auth/login-settings-test.js
  ui/tests/acceptance/config-ui/login-settings-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#30868 Update vault-plugin-database-snowflake to v0.14.1
  changelog/30868.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#30867 backport 1.19.x: Update vault-plugin-database-snowflake to v0.13.2
  changelog/30867.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30869 Backport 1.20.x UI: Update `namespace` key to `namespace_path`
  ui/lib/config-ui/addon/components/login-settings/page/details.js
  ui/lib/config-ui/addon/components/login-settings/page/list.hbs
  ui/tests/acceptance/auth/login-settings-test.js
  ui/tests/acceptance/config-ui/login-settings-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30872 Update vault-plugin-auth-azure to v0.21.0
  changelog/30872.txt
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog, hashicorp-contributed-pr

#30875 Backport of [DOCS] Tweak alert text into release/1.20.x
  website/content/partials/alerts/restricted-admin.mdx
  website/content/partials/alerts/restricted-root.mdx
  website/content/partials/alerts/unrestricted.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30874 [DOCS] Add change tracker and prep docs for 1.20
  website/content/docs/updates/change-tracker.mdx
  website/content/docs/updates/important-changes.mdx
  website/content/docs/updates/release-notes.mdx
  website/content/partials/release-notes/change-summary/1_16.mdx
  website/content/partials/release-notes/change-summary/1_17.mdx
  website/content/partials/release-notes/change-summary/1_18.mdx
  website/content/partials/release-notes/change-summary/1_19.mdx
  website/content/partials/release-notes/change-summary/1_20.mdx
  website/content/partials/release-notes/section-notes/3rd-party.mdx
  website/content/partials/release-notes/section-notes/certs.mdx
  website/content/partials/release-notes/section-notes/compliance.mdx
  website/content/partials/release-notes/section-notes/identity.mdx
  website/content/partials/release-notes/section-notes/ops.mdx
  website/content/partials/release-notes/section-notes/sensitive-data.mdx
  website/content/partials/release-notes/section-notes/static-secrets.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#30878 Backport of [DOCS] Add change tracker and prep docs for 1.20 into release/1.20.x
  website/content/docs/updates/change-tracker.mdx
  website/content/docs/updates/important-changes.mdx
  website/content/docs/updates/release-notes.mdx
  website/content/partials/release-notes/change-summary/1_16.mdx
  website/content/partials/release-notes/change-summary/1_17.mdx
  website/content/partials/release-notes/change-summary/1_18.mdx
  website/content/partials/release-notes/change-summary/1_19.mdx
  website/content/partials/release-notes/change-summary/1_20.mdx
  website/content/partials/release-notes/section-notes/3rd-party.mdx
  website/content/partials/release-notes/section-notes/certs.mdx
  website/content/partials/release-notes/section-notes/compliance.mdx
  website/content/partials/release-notes/section-notes/identity.mdx
  website/content/partials/release-notes/section-notes/ops.mdx
  website/content/partials/release-notes/section-notes/sensitive-data.mdx
  website/content/partials/release-notes/section-notes/static-secrets.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30880 [DOCS] Add missing update info to v1.17 docs
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/enterprise-plugins.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30879 [DOCS] Add missing update info to v1.18 of docs
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
  website/content/partials/known-issues/enterprise-plugins.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30881 [DOCS] Add missing update info to v1.16 docs
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/1_13-reload-census-panic-standby.mdx
  website/content/partials/known-issues/1_17_audit-log-hmac.mdx
  website/content/partials/known-issues/autopilot-upgrade-upgrade-version.mdx
  website/content/partials/known-issues/enterprise-plugins.mdx
  website/content/partials/known-issues/sync-activation-flags-cache-not-updated.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30888 UI: Update Swagger Title Element
  ui/app/styles/utils/swagger.scss
  ui/lib/open-api-explorer/addon/components/swagger-ui.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30753 PKI SCEP documentation updates
  website/content/api-docs/auth/scep.mdx
  website/content/api-docs/secret/pki/index.mdx
  website/content/api-docs/secret/pki/issuance.mdx
  website/content/docs/auth/scep.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/scep.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30886 UI: Use HDS icon instance for accessibility
  ui/app/components/dashboard/secrets-engines-card.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30896 Backport of UI: Move keyboard help text above code editor on ACL policy creation page into release/1.20.x
  ui/app/components/policy-form.hbs
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30892 [DOCS] Remove 1.19 from upgrade guide redirect (v1.19.x)
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30889 [DOCS] Remove 1.19 from the versioned redirect
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#30895 re-enable 1.19.x as ce_active
  .release/versions.hcl
Labels: pr/no-changelog, hashicorp-contributed-pr

#30890 Stub updates for Ent
  changelog/30890.txt
  vault/logical_system.go
  vault/logical_system_stubs_oss.go
  vault/plugincatalog/plugin_catalog_stubs_oss.go
Labels: hashicorp-contributed-pr

#30809 Update vault-plugin-secrets-alicloud to v0.20.0
  changelog/30809.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.20.x

#30876 Update vault-plugin-auth-jwt to v0.24.1
  changelog/30876.txt
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30894 Backport of PKI SCEP documentation updates into release/1.20.x
  website/content/api-docs/auth/scep.mdx
  website/content/api-docs/secret/pki/index.mdx
  website/content/api-docs/secret/pki/issuance.mdx
  website/content/docs/auth/scep.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/scep.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30891 Backport of Add missing protocol path table to CMPv2 API documentation into release/1.20.x
  CODEOWNERS
  website/content/api-docs/secret/pki/issuance.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30901 Backport of Add missing protocol path table to CMPv2 API documentation into release/1.19.x
  CODEOWNERS
  website/content/api-docs/secret/pki/issuance.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone

#30904 UI: Add missing aria-label to entities alias dropdown
  ui/app/templates/components/identity/lookup-input.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30903 [DOCS] Update change tracker and important changes page
  website/content/docs/updates/change-tracker.mdx
  website/content/docs/updates/important-changes.mdx
  website/content/partials/release-notes/change-summary/1_16.mdx
  website/content/partials/release-notes/change-summary/1_17.mdx
  website/content/partials/release-notes/change-summary/1_18.mdx
  website/content/partials/release-notes/change-summary/1_19.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30909 Backport of [DOCS] Update table layout into release/1.20.x
  website/content/docs/updates/important-changes.mdx
  website/content/partials/release-notes/change-summary/1_16.mdx
  website/content/partials/release-notes/change-summary/1_17.mdx
  website/content/partials/release-notes/change-summary/1_18.mdx
  website/content/partials/release-notes/change-summary/1_19.mdx
  website/content/partials/release-notes/change-summary/1_20.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#30907 Backport of UI: Add missing aria-label to entities alias dropdown into release/1.20.x
  ui/app/templates/components/identity/lookup-input.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30910 Update vault-plugin-auth-kubernetes to v0.22.1
  changelog/30910.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.20.x

#30884 Manual backport of VAULT-36229 docs: Nonce for rekey cancellations into release/1.18.x
  website/content/api-docs/system/rekey-recovery-key.mdx
  website/content/api-docs/system/rekey.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30885 Manual backport of VAULT-36229 docs: Nonce for rekey cancellations into release/1.16.x
  website/content/api-docs/system/rekey-recovery-key.mdx
  website/content/api-docs/system/rekey.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30862 Backport of VAULT-36229: Nonce for rekey cancellations into release/1.19.x
  api/sys_rekey.go
  changelog/30794.txt
  command/operator_rekey.go
  command/operator_rekey_test.go
  http/http_test.go
  http/sys_rekey.go
  http/sys_rekey_test.go
  vault/rekey.go
  vault/rekey_test.go
  vault/seal_config.go
  website/content/api-docs/system/rekey-recovery-key.mdx
  website/content/api-docs/system/rekey.mdx
  website/content/docs/updates/important-changes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30913 Update Azure Auth Docs To State Required Parameters
  website/content/api-docs/auth/azure.mdx
  website/content/docs/auth/azure.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30852 Ensure valid field is returned when set to false
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_hmac_test.go
  changelog/30852.txt
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30921 Hashiej/go upgrade to 124 for release 1 20
  .go-version
  changelog/_go-ver-1200.txt
Labels: pr/no-changelog, hashicorp-contributed-pr

#30920 update dependencies for vault-plugin-auth-saml ent upgrade
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30922 Backport of update dependencies for vault-plugin-auth-saml ent upgrade into release/1.20.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30918 Backport of Ensure valid field is returned when set to false into release/1.20.x
  builtin/logical/transit/path_hmac.go
  builtin/logical/transit/path_hmac_test.go
  changelog/30852.txt
Labels: hashicorp-contributed-pr

#30923 UI: Adds custom login settings link to empty state
  ui/lib/config-ui/addon/components/login-settings/page/list.hbs
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30925 VAULT-36565 CE changes
  vault/auth.go
  vault/mount.go
  vault/observations/observations_consts.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30788 UI: Add assertion to `FormField` for @attr.name and @model args
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/tests/integration/components/form-field-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30931 OSS patch: Remove active flag from ui banner metrics
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30789 [VAULT-34486] Create namespace GUI documentation
  website/content/docs/ui/namespaces.mdx
  website/data/docs-nav-data.json
  website/public/img/delete-namespace.png
  website/public/img/namespace-picker.png
  website/public/img/save-namespace.png
  website/public/img/switch-to-namespace.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30942 Update circl dependency to v1.6.1 to remediate GHSA-2x5j-vhc8-9cwm
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30926 Add buildvcs=false to revert to older behavior of not embedding VCS info into Vault binary
  changelog/30926.txt
  scripts/ci-helper.sh
  scripts/windows/build.bat
Labels: hashicorp-contributed-pr, backport/1.20.x, backport/ent/1.19.x+ent

#30956 VAULT-36902: Remove error messages when max_entry_size, max_mount_entry_size and autopilot config are empty
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#30717 [Docs] Adding identity-based rate limit
  website/content/docs/concepts/resource-quotas.mdx
  website/content/docs/configuration/create-lease-count-quota.mdx
  website/content/docs/configuration/create-rate-limit-quota.mdx
  website/content/docs/configuration/identity-based-rate-limit.mdx
  website/data/docs-nav-data.json
  website/public/img/resource-quotas/group-by_dark.png
  website/public/img/resource-quotas/group-by_light.png
  website/public/img/resource-quotas/quota-granularity_dark.png
  website/public/img/resource-quotas/quota-granularity_light.png
  website/public/img/resource-quotas/resource-quotas-use-cases_dark.png
  website/public/img/resource-quotas/resource-quotas-use-cases_light.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#30949 UI: Auth test cleanup to prep for auth service refactor
  ui/app/services/auth.js
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/tests/acceptance/access/methods-test.js
  ui/tests/acceptance/auth/auth-list-test.js
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/jwt-auth-method-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/acceptance/settings/auth/enable-test.js
  ui/tests/acceptance/sidebar-nav-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/helpers/auth/response-stubs.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/oidc-window-stub.js
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/form/auth-form-test-helper.js
  ui/tests/integration/components/auth/form/base-test.js
  ui/tests/integration/components/auth/form/oidc-jwt-test.js
  ui/tests/integration/components/auth/form/okta-test.js
  ui/tests/integration/components/auth/form/saml-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/tests/integration/components/auth/page/listing-visibility-test.js
  ui/tests/integration/components/auth/page/login-settings-test.js
  ui/tests/integration/components/auth/page/method-authentication-test.js
  ui/tests/integration/components/auth/page/mfa-test.js
  ui/tests/integration/components/auth/page/page-test.js
  ui/tests/integration/components/auth/page/setup-test-context.js
Labels: pr/no-changelog

#30965 VAULT-36206: bump `hashicorp/go-discover` to v1.1.0
  command/server/config_test_helpers.go
  command/server/test-fixtures/raft_retry_join_attr.hcl
  command/server/test-fixtures/raft_retry_join_block.hcl
  command/server/test-fixtures/raft_retry_join_mixed.hcl
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, backport/1.20.x, backport/ent/1.19.x+ent

#30966 pipeline(actions): fix hashicorp contributed label job
  .github/workflows/add-hashicorp-contributed-label.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#30961 Refactor Groups/Entities tests
  ui/app/templates/components/identity/edit-form.hbs
  ui/app/templates/components/identity/lookup-input.hbs
  ui/app/templates/components/identity/popup-alias.hbs
  ui/tests/acceptance/access/identity/_shared-alias-tests.js
  ui/tests/acceptance/access/identity/_shared-tests.js
  ui/tests/acceptance/access/identity/entities/aliases/create-test.js
  ui/tests/acceptance/access/identity/entities/create-test.js
  ui/tests/acceptance/access/identity/entities/index-test.js
  ui/tests/acceptance/access/identity/groups/aliases/create-test.js
  ui/tests/acceptance/access/identity/groups/create-test.js
  ui/tests/acceptance/access/identity/shared-identity-test.js
  ui/tests/pages/access/identity/aliases/add.js
  ui/tests/pages/access/identity/aliases/index.js
  ui/tests/pages/access/identity/aliases/show.js
  ui/tests/pages/access/identity/create.js
  ui/tests/pages/access/identity/show.js
  ui/tests/pages/components/identity/edit-form.js
Labels: ui, pr/no-changelog

#30968 Backport of VAULT-36206: bump `hashicorp/go-discover` to v1.1.0 into release/1.20.x
  command/server/config_test_helpers.go
  command/server/test-fixtures/raft_retry_join_attr.hcl
  command/server/test-fixtures/raft_retry_join_block.hcl
  command/server/test-fixtures/raft_retry_join_mixed.hcl
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone

#30936 manual Backport of Stub updates for Ent into release/1.20.x and fix DownloadExtractVerifyPlugin stub
  changelog/30890.txt
  vault/extended_system_view.go
  vault/logical_system.go
  vault/logical_system_stubs_oss.go
Labels: hashicorp-contributed-pr

#30969 Backport 1.20.x: UI: Fix initial rendering of ToggleButton values for nested params
  changelog/30960.txt
  ui/lib/core/addon/components/form-field.js
  ui/tests/integration/components/form-field-test.js
Labels: backport

#30970 Backport of pipeline(actions): fix hashicorp contributed label job into release/1.20.x
  .github/workflows/add-hashicorp-contributed-label.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30861 UI: Update Namespaces Page Link Component Behavior
  ui/app/components/namespace-link.js
  ui/app/controllers/vault/cluster/access/namespaces/index.js
  ui/app/templates/components/namespace-link.hbs
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/tests/acceptance/access/namespaces/index-test.js
  ui/tests/acceptance/enterprise-namespaces-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30977 Backport of Update vault-plugin-secrets-mongodbatlas to v0.15.0 into release/1.20.x
  changelog/30860.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30915 Backport of Update vault-plugin-auth-azure to v0.21.0 into release/1.20.x
  changelog/30872.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30978 Backport of Update vault-plugin-database-snowflake to v0.14.1 into release/1.20.x
  changelog/30868.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30951 [UI] Ember Data Migration - Secrets Engine Forms
  ui/app/components/mount-backend-form.hbs
  ui/app/components/mount-backend-form.ts
  ui/app/components/secret-engine/configure-ssh.hbs
  ui/app/components/secret-engine/configure-ssh.ts
  ui/app/components/secret-engine/configure-wif.hbs
  ui/app/components/secret-engine/configure-wif.ts
  ui/app/forms/form.ts
  ui/app/forms/secrets/aws-config.ts
  ui/app/forms/secrets/azure-config.ts
  ui/app/forms/secrets/engine.ts
  ui/app/forms/secrets/gcp-config.ts
  ui/app/forms/secrets/ssh-config.ts
  ui/app/forms/secrets/wif-config.ts
  ui/app/routes/vault/cluster/secrets/backend/configuration.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/routes/vault/cluster/settings/mount-secret-backend.ts
  ui/app/services/api.ts
  ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs
  ui/app/utils/constants/capabilities.ts
  ui/app/utils/forms/field.ts
  ui/lib/core/addon/components/form-field-groups.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/secrets/backend/ssh/configuration-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/secret-engine/configure-ssh-test.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
  ui/tests/pages/settings/mount-secret-backend.js
  ui/tests/unit/services/api-test.js
  ui/types/vault/secrets/engine.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30957 document known issue with ldap service account check ins
  website/content/docs/updates/important-changes.mdx
  website/content/partials/release-notes/change-summary/1_19.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent, backport/ent/1.19.x+ent

#30606 Require rotation_schedule cron style strings to be defined in UTC (VAULT-35616)
  builtin/logical/database/path_creds_create.go
  builtin/logical/database/rotation_test.go
  builtin/logical/database/schedule/schedule.go
  changelog/30606.txt
  website/content/api-docs/secret/databases/index.mdx
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent

#30987 [UI] Enterprise WIF Test Failure
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30964 Fix broken kv docs link
  website/content/docs/secrets/kv/kv-v2/index.mdx
Labels: pr/no-changelog, pr/no-milestone, backport/1.20.x

#30744 identity: use request context namespace for entity merges
  vault/identity_store_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30995 enos(fips1403): simplify semver constraint to only consider currently mixed versions for upgrade scenario
  enos/enos-scenario-upgrade.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent

#30991 [DOCS] Fix broken link
  website/content/docs/secrets/kv/kv-v2/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30988 Backport of Fix broken kv docs link into release/1.20.x
  website/content/docs/secrets/kv/kv-v2/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#30976 Backport of Docs: Update to Reflect Client Count Changes into release/1.20.x
  ui/app/components/clients/usage-stats.hbs
  ui/tests/integration/components/clients/page/acme-test.js
  ui/tests/integration/components/clients/page/sync-test.js
  ui/tests/integration/components/clients/usage-stats-test.js
  website/README.md
  website/content/docs/commands/operator/usage.mdx
  website/content/docs/concepts/client-count/client-usage.mdx
  website/content/docs/concepts/client-count/counting.mdx
  website/content/docs/internals/recommended-patterns.mdx
  website/content/docs/internals/telemetry/key-metrics.mdx
  website/content/partials/faq/client-count/computing-clients.mdx
  website/content/partials/faq/client-count/tools.mdx
  website/data/docs-nav-data.json
  website/public/img/ui-client-usage-1.png
  website/public/img/ui-client-usage-acme.png
  website/public/img/ui-client-usage-config.png
  website/public/img/ui-client-usage-export.png
  website/public/img/ui-client-usage-filter.png
  website/public/img/ui-client-usage-period-ce.png
  website/public/img/ui-client-usage-period-enterprise.png
  website/public/img/ui-client-usage-table.png
  website/public/img/ui-usage-metrics-1.png
  website/public/img/ui-usage-metrics-acme.png
  website/public/img/ui-usage-metrics-export.png
  website/public/img/ui-usage-metrics-filter.png
  website/public/img/ui-usage-metrics-mounts.png
  website/public/img/ui-usage-metrics-namespace.png
  website/public/img/ui-usage-metrics-period.png
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone

#30998 Backport of Add example policy to AWS secrets engine for AssumeRole that will still be able to rotate itself into release/1.20.x
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30950 UI: Removing mountable-secret-engines.js
  ui/app/components/mount-backend-form.ts
  ui/app/controllers/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/controllers/vault/cluster/settings/mount-secret-backend.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/secret-engine.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/serializers/secret-engine.js
  ui/app/templates/vault/cluster/settings/auth/enable.hbs
  ui/app/utils/all-engines-metadata.ts
  ui/lib/core/addon/components/secret-list-header.js
  ui/tests/acceptance/enterprise-kmip-test.js
  ui/tests/acceptance/enterprise-kmse-test.js
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/acceptance/secret-engine-list-view-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30982 [VAULT-37109] UI: Tackle data test toggle group selectors
  ui/app/components/totp/key-create-toggle-groups.hbs
  ui/app/templates/components/database-connection.hbs
  ui/lib/core/addon/components/form-field-groups-loop.hbs
  ui/lib/core/addon/components/form-field-groups.hbs
  ui/lib/pki/addon/components/pki-generate-toggle-groups.hbs
  ui/lib/pki/addon/components/pki-role-form.hbs
  ui/tests/acceptance/auth/test-helper.js
  ui/tests/acceptance/oidc-config/clients-test.js
  ui/tests/acceptance/pki/pki-action-forms-test.js
  ui/tests/acceptance/pki/pki-configuration-test.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/secrets/backend/ssh/roles-test.js
  ui/tests/acceptance/secrets/backend/totp/key-test.js
  ui/tests/acceptance/settings-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/pki/pki-selectors.ts
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-generate-root-test.js
  ui/tests/integration/components/pki/pki-generate-toggle-groups-test.js
  ui/tests/integration/components/pki/pki-role-form-test.js
  ui/tests/integration/components/pki/pki-role-generate-test.js
  ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
  ui/tests/integration/components/totp/key-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#31000 [DOCS] Manual backport of Add example policy to AWS secrets engine for AssumeRole that will still be able to rotate itself into release/1.19.x
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30944 Add documentation for Snowflake keypair auth support
  website/content/api-docs/secret/databases/snowflake.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/snowflake.mdx
  website/content/docs/updates/important-changes.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent, backport/1.20.x, backport/ent/1.19.x+ent

#31004 Remove vault-plugin-mock
  builtin/plugin/mock_plugin_test.go
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent, backport/1.20.x, backport/ent/1.19.x+ent

#31009 Backport of Remove vault-plugin-mock into release/1.20.x
  builtin/plugin/mock_plugin_test.go
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#31017 Backport of VAULT-36112: Better handling for Retry-After rate limit header. into release/1.20.x
  api/client.go
  api/go.mod
  api/go.sum
  changelog/30887.txt
  go.mod
  go.sum
  vault/external_tests/quotas/quotas_test.go
  vault/quotas/quotas_rate_limit.go
  vault/quotas/quotas_rate_limit_test.go
Labels: hashicorp-contributed-pr

#31025 [DOCS] Fix build error associated with Snowflake warning (v 1.20)
  website/content/api-docs/secret/databases/snowflake.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31029 Backport of Remove links and refs to using HVS into release/1.20.x
  website/content/docs/about-vault/what-is-vault.mdx
  website/content/docs/deploy/kubernetes/vso/index.mdx
  website/content/docs/secrets/kv/index.mdx
  website/content/docs/sync/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31026 [DOCS] Fix build error associated with Snowflake warning (v 1.17)
  website/content/api-docs/secret/databases/snowflake.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31027 [DOCS] Fix build error associated with Snowflake warning (v 1.18)
  website/content/api-docs/secret/databases/snowflake.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31028 [DOCS] Fix build error associated with Snowflake warning (v 1.16)
  website/content/api-docs/secret/databases/snowflake.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31020 Backport of doc: plugin register API's Enterprise Beta download parameter into release/1.20.x
  website/content/api-docs/secret/databases/index.mdx
  website/content/api-docs/system/plugins-catalog.mdx
  website/content/docs/plugins/register.mdx
Labels: hashicorp-contributed-pr

#31001 UI: Surface plugin version & cleanup utils
  changelog/31001.txt
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/tabs.hbs
  ui/app/components/mount-backend-form.hbs
  ui/app/components/mount-backend-form.ts
  ui/app/components/mount-backend/type-form.hbs
  ui/app/components/mount-backend/type-form.js
  ui/app/components/secret-engine/list.hbs
  ui/app/components/secret-engine/list.ts
  ui/app/controllers/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/controllers/vault/cluster/secrets/backend/configuration/index.js
  ui/app/controllers/vault/cluster/settings/mount-secret-backend.js
  ui/app/forms/secrets/engine.ts
  ui/app/helpers/auth-display-name.ts
  ui/app/helpers/engines-display-data.ts
  ui/app/helpers/mountable-auth-methods.js
  ui/app/helpers/mountable-secret-engines.js
  ui/app/helpers/supported-auth-backends.js
  ui/app/models/auth-method.js
  ui/app/models/mfa-login-enforcement.js
  ui/app/models/secret-engine.js
  ui/app/resources/secrets/engine.ts
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/routes/vault/cluster/secrets/backend/configuration/index.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/serializers/secret-engine.js
  ui/app/templates/vault/cluster/settings/auth/configure.hbs
  ui/app/templates/vault/cluster/settings/auth/enable.hbs
  ui/app/templates/vault/cluster/settings/mount-secret-backend.hbs
  ui/app/utils/all-engines-metadata.ts
  ui/lib/core/addon/components/secret-list-header.js
  ui/lib/core/addon/components/secrets-engine-mount-config.ts
  ui/tests/acceptance/auth/auth-list-test.js
  ui/tests/acceptance/enterprise-kmip-test.js
  ui/tests/acceptance/enterprise-kmse-test.js
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/acceptance/secret-engine-list-view-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/integration/components/auth-config-form/options-test.js
  ui/tests/integration/components/mount-backend-form-test.js
  ui/tests/integration/components/mount-backend/type-form-test.js
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
  ui/tests/integration/components/secrets-engine-mount-config-test.js
  ui/tests/unit/models/secret-engine-test.js
  ui/types/vault/models/secret-engine.d.ts
Labels: ui, hashicorp-contributed-pr

#31031 enos(fips1403): simplify semver constraint to only consider currently…
  enos/enos-scenario-upgrade.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30983 [VAULT-35162] Development cluster docs clarifications
  website/content/docs/license/utilization/auto-reporting.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#31033 Backport of [VAULT-35162] Development cluster docs clarifications into release/1.20.x
  website/content/docs/license/utilization/auto-reporting.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#31035 UI: fix tooltip test
  ui/tests/acceptance/secret-engine-list-view-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31036 [DOCS] Fix heading
  website/content/docs/updates/important-changes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#31037 [DOCS] Remove 1.20 note from 1.19 ic page
  website/content/docs/updates/important-changes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31039 Backport of [DOCS] Fix heading into release/1.20.x
  website/content/docs/updates/important-changes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31038 Upgrade Kubernetes Authentication Plugin to 0.22.2
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#30981 [DOCS] LTS upgrade summary
  website/content/docs/upgrade/lts-upgrade.mdx
  website/content/partials/release-notes/change-summary/lts/1_16-to-1_19.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31043 Update Docs to Include Notice that Audience is Required in K8s Roles
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#31040 Backport of Upgrade Kubernetes Authentication Plugin to 0.22.2 into release/1.20.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#31030 Fix premature stop of seal rewrap process due to partial rewrap (CE)
  vault/seal/seal.go
  vault/seal_autoseal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent, backport/1.20.x, backport/ent/1.19.x+ent

#31057 enos(consul): only use versions that are CE and ENT
  enos/enos-globals.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31056 Revert "Perform an immediate check when starting the seal health check.
  vault/seal/seal.go
  vault/seal_autoseal.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#31022 [VAULT-21456] Use interned regexp when initialising backends and validating authz headers in the AWS backend
  builtin/credential/aws/path_login.go
  changelog/31022.txt
  go.mod
  go.sum
  sdk/framework/backend.go
  sdk/go.mod
  sdk/go.sum
  vault/external_tests/interned_regexp/interned_regexp_test.go
Labels: hashicorp-contributed-pr, backport/1.20.x, backport/ent/1.19.x+ent

#31060 Backport of [VAULT-21456] Use interned regexp when initialising backends and validating authz headers in the AWS backend into release/1.20.x
  builtin/credential/aws/path_login.go
  changelog/31022.txt
  go.mod
  go.sum
  sdk/framework/backend.go
  sdk/go.mod
  sdk/go.sum
  vault/external_tests/interned_regexp/interned_regexp_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#31054 VAULT-36562 CE changes
  go.mod
  go.sum
  sdk/logical/observation.pb.go
  sdk/logical/observation.proto
  vault/auth.go
  vault/mount.go
  vault/observations/observations_ce.go
  vault/observations/observations_consts.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30216 Docs/operator import enhancements
  website/content/docs/commands/operator/import.mdx
  website/content/docs/import/awssm.mdx
  website/content/docs/import/azurekv.mdx
  website/content/docs/import/gcpsm.mdx
  website/content/docs/import/index.mdx
  website/content/docs/import/mappings.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#31016 Address flaky tests: namespace and config-ui/messages
  ui/app/components/namespace-picker.hbs
  ui/app/components/namespace-picker.ts
  ui/app/routes/vault/cluster/access/namespaces/index.js
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/core/addon/components/filter-input-explicit.hbs
  ui/tests/acceptance/access/namespaces/index-test.js
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/acceptance/config-ui/messages/messages-test.js
  ui/tests/acceptance/config-ui/messages/messages-unauth-auth-test.js
  ui/tests/acceptance/dashboard-test.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/secrets/backend/kubernetes/roles-test.js
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/config-ui/message-selectors.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/namespace-picker.js
  ui/tests/integration/components/config-ui/messages/page/list-test.js
  ui/tests/integration/components/filter-input-explicit-test.js
  ui/tests/integration/components/namespace-picker-test.js
  ui/tests/integration/components/sidebar/frame-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#31058 Include Breaking Changes for Azure and K8s Auth Plugins
  website/content/docs/updates/important-changes.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#31061 Perform an immediate check when starting the seal health check
  vault/seal_autoseal.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.18.x+ent, backport/1.20.x, backport/ent/1.19.x+ent

#31074 [VAULT-34486] Docs: fix broken images
  website/content/docs/ui/namespaces.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#31034 UI: A11y Fixes for malformed swagger interactives
  ui/app/styles/utils/swagger.scss
  ui/lib/core/addon/utils/keys.js
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
  ui/tests/integration/components/open-api-explorer/swagger-ui-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#31008 [VAULT-34485] UI: Internal namespace documentation updates
  website/content/api-docs/system/internal-ui-namespaces.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31079 UI: A11y fix for disabled swagger interarctive
  ui/lib/open-api-explorer/addon/components/swagger-ui.js
  ui/mirage/factories/open-api-explorer.js
  ui/tests/integration/components/open-api-explorer/swagger-ui-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#31044 Backport of Update Docs to Include Notice that Audience is Required in K8s Roles into release/1.20.x
  website/content/api-docs/auth/kubernetes.mdx
  website/content/docs/auth/kubernetes.mdx
Labels: hashicorp-contributed-pr

#30916 Backport of Update Azure Auth Docs To State Required Parameters into release/1.20.x
  website/content/api-docs/auth/azure.mdx
  website/content/docs/auth/azure.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#30993 [DOCS] IA and style guide suggestions [in progress]
  website/content/docs/concepts/integrated-storage/snapshot-recover.mdx
  website/content/docs/configuration/manage-snapshots.mdx
  website/content/docs/sysadmin/snapshots/automate.mdx
  website/content/docs/sysadmin/snapshots/automation-overview.mdx
  website/content/docs/sysadmin/snapshots/index.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/index.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/replicated-cluster.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/single-cluster.mdx
  website/content/docs/sysadmin/snapshots/restore.mdx
  website/content/docs/sysadmin/snapshots/save.mdx
  website/content/partials/recover/deletedmounts.mdx
  website/content/partials/recover/loadedsnapshots.mdx
  website/content/partials/sysadmin/snapshots/check-status/api.mdx
  website/content/partials/sysadmin/snapshots/check-status/cli.mdx
  website/content/partials/sysadmin/snapshots/disabled-mount-warning.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/api/auto.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/api/manual.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/cli/auto.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/cli/manual.mdx
  website/content/partials/sysadmin/snapshots/restore-requirements/load-snapshots.mdx
  website/content/partials/sysadmin/snapshots/restore-requirements/restore-secrets.mdx
  website/content/partials/sysadmin/snapshots/restore-secret-support.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/recover/api.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/recover/cli.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/verify/api.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/verify/cli.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30940 Docs: Manage snapshots content
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/concepts/integrated-storage/snapshot-recover.mdx
  website/content/docs/sysadmin/snapshots/automate.mdx
  website/content/docs/sysadmin/snapshots/automation-overview.mdx
  website/content/docs/sysadmin/snapshots/index.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/index.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/replicated-cluster.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/single-cluster.mdx
  website/content/docs/sysadmin/snapshots/restore.mdx
  website/content/docs/sysadmin/snapshots/save.mdx
  website/content/docs/upgrade/index.mdx
  website/content/partials/recover/deletedmounts.mdx
  website/content/partials/recover/loadedsnapshots.mdx
  website/content/partials/sysadmin/snapshots/check-status/api.mdx
  website/content/partials/sysadmin/snapshots/check-status/cli.mdx
  website/content/partials/sysadmin/snapshots/disabled-mount-warning.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/api/auto.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/api/manual.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/cli/auto.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/cli/manual.mdx
  website/content/partials/sysadmin/snapshots/restore-requirements/load-snapshots.mdx
  website/content/partials/sysadmin/snapshots/restore-requirements/restore-secrets.mdx
  website/content/partials/sysadmin/snapshots/restore-secret-support.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/recover/api.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/recover/cli.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/verify/api.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/verify/cli.mdx
  website/content/partials/tips/manage-snapshots.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#31093 [DOCS] Fix tip link
  website/content/partials/tips/manage-snapshots.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#31097 ci(code-checks): fix buf lint linter errors for new proto files
  buf.yaml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31091 Backport of Docs: Manage snapshots content into release/1.20.x
  website/content/docs/commands/operator/raft.mdx
  website/content/docs/concepts/integrated-storage/snapshot-recover.mdx
  website/content/docs/sysadmin/snapshots/automate.mdx
  website/content/docs/sysadmin/snapshots/automation-overview.mdx
  website/content/docs/sysadmin/snapshots/index.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/index.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/replicated-cluster.mdx
  website/content/docs/sysadmin/snapshots/recover-a-secret/single-cluster.mdx
  website/content/docs/sysadmin/snapshots/restore.mdx
  website/content/docs/sysadmin/snapshots/save.mdx
  website/content/docs/upgrade/index.mdx
  website/content/partials/recover/deletedmounts.mdx
  website/content/partials/recover/loadedsnapshots.mdx
  website/content/partials/sysadmin/snapshots/check-status/api.mdx
  website/content/partials/sysadmin/snapshots/check-status/cli.mdx
  website/content/partials/sysadmin/snapshots/disabled-mount-warning.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/api/auto.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/api/manual.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/cli/auto.mdx
  website/content/partials/sysadmin/snapshots/load-snapshot/cli/manual.mdx
  website/content/partials/sysadmin/snapshots/restore-requirements/load-snapshots.mdx
  website/content/partials/sysadmin/snapshots/restore-requirements/restore-secrets.mdx
  website/content/partials/sysadmin/snapshots/restore-secret-support.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/recover/api.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/recover/cli.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/verify/api.mdx
  website/content/partials/sysadmin/snapshots/secret-restore/verify/cli.mdx
  website/content/partials/tips/manage-snapshots.mdx
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31084 Backport of [VAULT-34485] UI: Internal namespace documentation updates into release/1.20.x
  website/content/api-docs/system/internal-ui-namespaces.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31072 docs/events: add info about vault_index
  website/content/docs/concepts/events.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.20.x

#31104 VAULT-36611 remove goleak test
  go.mod
  vault/quotas/quotas_rate_limit_test.go
Labels: test, pr/no-changelog, hashicorp-contributed-pr

#31103 Fix small typo in observation type
  vault/observations/observations_consts.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31101 Backport 1.20.x UI: Revert api service use for requests to sys/internal/ui/mounts
  changelog/31094.txt
  ui/app/routes/vault/cluster/auth.js
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/tests/acceptance/auth/auth-login-test.js
  ui/tests/acceptance/auth/login-settings-test.js
  ui/tests/acceptance/secret-engine-list-view-test.js
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/tests/integration/components/auth/tabs-test.js
Labels: backport, hashicorp-contributed-pr

#31106 [MANUAL BACKPORT] Remove pending elements from release notes
  website/content/docs/updates/release-notes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31108 Backport of [DOCS] Add missing date into release/1.20.x
  website/content/docs/updates/release-notes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31109 Backport of [VAULT-37096] pipeline(github): add `github copy pr` command into release/1.20.x
  tools/pipeline/internal/cmd/generate.go
  tools/pipeline/internal/cmd/generate_enos_dynamic_config.go
  tools/pipeline/internal/cmd/github.go
  tools/pipeline/internal/cmd/github_copy.go
  tools/pipeline/internal/cmd/github_copy_pull_request.go
  tools/pipeline/internal/cmd/github_create.go
  tools/pipeline/internal/cmd/github_create_backport.go
  tools/pipeline/internal/cmd/github_list.go
  tools/pipeline/internal/cmd/github_list_changed_files.go
  tools/pipeline/internal/cmd/github_list_runs.go
  tools/pipeline/internal/cmd/releases.go
  tools/pipeline/internal/cmd/releases_list.go
  tools/pipeline/internal/cmd/releases_list_active_versions.go
  tools/pipeline/internal/cmd/releases_list_versions.go
  tools/pipeline/internal/pkg/git/merge.go
  tools/pipeline/internal/pkg/git/opts_test.go
  tools/pipeline/internal/pkg/git/pull.go
  tools/pipeline/internal/pkg/git/rebase.go
  tools/pipeline/internal/pkg/git/remote.go
  tools/pipeline/internal/pkg/git/rm.go
  tools/pipeline/internal/pkg/github/add_assignees.go
  tools/pipeline/internal/pkg/github/copy_pull_request.go
  tools/pipeline/internal/pkg/github/copy_pull_request_test.go
  tools/pipeline/internal/pkg/github/create_backport.go
  tools/pipeline/internal/pkg/github/create_backport_test.go
  tools/pipeline/internal/pkg/github/embeds.go
  tools/pipeline/internal/pkg/github/noop_commit.go
  tools/pipeline/internal/pkg/github/pull_request.go
  tools/pipeline/internal/pkg/github/repo.go
  tools/pipeline/internal/pkg/github/templates.go
  tools/pipeline/internal/pkg/github/templates/backport-pr-message.tmpl
  tools/pipeline/internal/pkg/github/templates/copy-pr-commit-message.tmpl
  tools/pipeline/internal/pkg/github/templates/copy-pr-message.tmpl
  tools/pipeline/internal/pkg/github/templates/workflow-run-text.tmpl
  tools/pipeline/internal/pkg/github/templates_test.go
  tools/pipeline/internal/pkg/github/workflow_run_summary.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31086 [DOCS] Add 1.20 release notes
  website/content/docs/ui/namespaces.mdx
  website/content/docs/updates/release-notes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.20.x

#31110 Backport of [DOCS] Add 1.20 release notes into release/1.20.x
  website/content/docs/ui/namespaces.mdx
  website/content/docs/updates/release-notes.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#31092 Updating changelog
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
