Repository hashicorp/vault, pull requests merged in 2025-04, with the labels that each got.

#30135 fix rootless typo
  sdk/helper/pluginruntimeutil/config.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30141 [Docs] Promote HVS as an alternative solution
  website/content/docs/secrets/kv/index.mdx
  website/content/partials/tips/try-hvs.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29798 Fix tutorial typos
  website/content/docs/enterprise/sentinel/index.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone

#30149 [DOCS] Fix true setting in nav
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30148 ldap: pin test container to latest working version
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_config_rotate_root_test.go
  helper/testhelpers/ldap/ldaphelper.go
  sdk/helper/docker/testhelpers.go
  vault/external_tests/identity/groups_test.go
  vault/external_tests/identity/identity_test.go
  vault/external_tests/policy/policy_test.go
  vault/external_tests/token/token_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30151 Backport of ldap: pin test container to latest working version into release/1.19.x
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_config_rotate_root_test.go
  helper/testhelpers/ldap/ldaphelper.go
  sdk/helper/docker/testhelpers.go
  vault/external_tests/identity/groups_test.go
  vault/external_tests/identity/identity_test.go
  vault/external_tests/policy/policy_test.go
  vault/external_tests/token/token_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30152 [DOCS] Manual backport: Fix true setting in nav into release/1.19.x
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30134 Vault-34677-Removing estimates from counters api- handle end of month and end of current billing cycle CE changes
  vault/activity_log.go
  vault/activity_log_testing_util.go
  vault/activity_log_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30145 [docs] add known issue where static roles get rotated on upgrade
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30136 Support reading mysql backend credentials from environment variables
  changelog/30136.txt
  physical/mysql/mysql.go
  website/content/docs/configuration/storage/mysql.mdx
Labels: enhancement, storage/mysql

#30061 Add ce changes for ssh managed keys
  builtin/logical/ssh/backend.go
  builtin/logical/ssh/managed_key/common.go
  builtin/logical/ssh/managed_key/managed_key_util_ce.go
  builtin/logical/ssh/path_config_ca.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30162 Fix race within pkcs7.asn1Structured.EncodeTo
  helper/pkcs7/ber.go
Labels: data-race, test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30130 UI: Glimmerize AuthJwt
  ui/app/components/auth-jwt.js
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-jwt.hbs
  ui/tests/acceptance/auth-test.js
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/jwt-auth-method-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/helpers/oidc-window-stub.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/unit/components/auth-jwt-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30153 Docs/add docs for dynamic secrets opertor import
  website/content/docs/import/awssm.mdx
  website/content/docs/import/azurekv.mdx
  website/content/docs/import/gcpsm.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30175 Cleanup/vault 35002
  builtin/logical/pki/acme_errors.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30034 Allow Root + Intermediate Key_Usage to be set
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_root.go
  changelog/30034.txt
  sdk/helper/certutil/types.go
  website/content/api-docs/secret/pki/index.mdx
Labels: cryptosec, hashicorp-contributed-pr, backport/1.19.x, backport/ent/1.18.x+ent

#29674 Fix annotations.mdx
  website/content/docs/platform/k8s/injector/annotations.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#30165 update to go 1.23.7
  .go-version
  changelog/_go-ver-1200.txt
Labels: hashicorp-contributed-pr

#30157 Backport of [docs] add known issue where static roles get rotated on upgrade into release/1.19.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30169 Backport of [docs] add known issue where static roles get rotated on upgrade into release/1.18.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30174 Backport of Bugfix/vault 35002 into release/1.19.x
  builtin/logical/pki/acme_errors.go
  builtin/logical/pki/acme_state_test.go
  changelog/30168.txt
Labels: hashicorp-contributed-pr

#30128 Backport of docs: fix enterprise Oracle plugin instant client version into release/1.19.x
  website/content/docs/secrets/databases/oracle.mdx
Labels: hashicorp-contributed-pr

#30185 VAULT-30187: adding aws vault ci permissions to destroy enos aws engine test res
  enos/README.md
  enos/ci/service-user-iam/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30121 ﻿pipeline: make 1.18.x CE branch inactive (docs/website only)
  .github/actions/changed-files/action.yml
  .github/actions/install-external-tools/action.yml
  .github/actions/set-up-pipeline/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/inactive-ce-branch-checks.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/test-acc-dockeronly-nightly.yml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-containers.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .github/workflows/test-run-enos-scenario.yml
  tools/pipeline/go.mod
  tools/pipeline/go.sum
  tools/pipeline/internal/cmd/generate_enos_dynamic_config.go
  tools/pipeline/internal/cmd/github.go
  tools/pipeline/internal/cmd/github_list.go
  tools/pipeline/internal/cmd/github_list_changed_files.go
  tools/pipeline/internal/cmd/github_list_runs.go
  tools/pipeline/internal/cmd/releases_list_versions.go
  tools/pipeline/internal/pkg/changed/checkers.go
  tools/pipeline/internal/pkg/changed/checkers_test.go
  tools/pipeline/internal/pkg/changed/file.go
  tools/pipeline/internal/pkg/generate/enos_dynamic_config.go
  tools/pipeline/internal/pkg/generate/enos_dynamic_config_test.go
  tools/pipeline/internal/pkg/github/list_changed_files.go
  tools/pipeline/internal/pkg/metadata/metadata.go
  tools/pipeline/internal/pkg/releases/client.go
  tools/pipeline/internal/pkg/releases/client_mock.go
  tools/pipeline/internal/pkg/releases/list_versions.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30166 add known issue for log file missing logs #35101
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30172 Backport of [docs] add known issue where static roles get rotated on upgrade into release/1.16.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30171 Backport of [docs] add known issue where static roles get rotated on …
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29933 docs/k8s: update supported k8s versions for 1.16
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29934 docs/k8s: update supported k8s versions for 1.17
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30180 docs/vso: update env options for operatorhub deployments
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30194 Backport of docs/vso: update env options for operatorhub deployments into release/1.19.x
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: hashicorp-contributed-pr

#29653 Directly exec ExternalTokenHelper rather than using a SHELL
  api/tokenhelper/helper_external.go
  api/tokenhelper/helper_external_test.go
  changelog/29653.txt
Labels: bug, core/token

#30161 UI: Rebuilding yarn.lock to use upgraded versions
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30190 [backport 1.18] add known issue for log file missing logs (#30166)
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30191 [backport 1.17] add known issue for log file (#30166)
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30192 1.16/docs/known issue log file
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30189 Backport of add known issue for log file missing logs #35101 into release/1.19.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30074 docs(github): add note about `VAULT_AUTH_GITHUB_TOKEN`
  website/content/docs/auth/github.mdx
Labels: docs

#30186 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30198 changelog: add changelog for 29874
  changelog/29874.txt
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30199 Backport of changelog: add changelog for 29874 into release/1.19.x
  changelog/29874.txt
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30177 bump go to 1.23.7
  .go-version
  changelog/_go-ver-1192.txt
Labels: hashicorp-contributed-pr

#29408 Update migrate.mdx
  website/content/docs/commands/operator/migrate.mdx
Labels: docs

#30193 Making some adjustments to compliance language.
  website/content/api-docs/system/auth.mdx
  website/content/docs/concepts/identity.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/public/img/vault-mount-filter-7.png
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30202 [UI] Update vault-reporting addon
  ui/vault-reporting/declarations/components/vault-reporting/base/title-row.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/base/title-row.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/counter.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/counter.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/dashboard/export.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/dashboard/export.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/global-lease.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/global-lease.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/views/dashboard.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/views/dashboard.d.ts.map
  ui/vault-reporting/declarations/modifiers/css-custom-property.d.ts
  ui/vault-reporting/declarations/modifiers/css-custom-property.d.ts.map
  ui/vault-reporting/dist/_app_/components/vault-reporting/base/title-row.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/cluster-replication.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/counter.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/dashboard/export.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/donut-chart.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/global-lease.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/horizontal-bar-chart.js
  ui/vault-reporting/dist/_app_/components/vault-reporting/views/dashboard.js
  ui/vault-reporting/dist/_app_/modifiers/axis-offset.js
  ui/vault-reporting/dist/_app_/modifiers/css-custom-property.js
  ui/vault-reporting/dist/components/vault-reporting/base/title-row.js
  ui/vault-reporting/dist/components/vault-reporting/base/title-row.js.map
  ui/vault-reporting/dist/components/vault-reporting/counter.js
  ui/vault-reporting/dist/components/vault-reporting/counter.js.map
  ui/vault-reporting/dist/components/vault-reporting/dashboard/export.js
  ui/vault-reporting/dist/components/vault-reporting/dashboard/export.js.map
  ui/vault-reporting/dist/components/vault-reporting/global-lease.js
  ui/vault-reporting/dist/components/vault-reporting/global-lease.js.map
  ui/vault-reporting/dist/components/vault-reporting/views/dashboard.js
  ui/vault-reporting/dist/components/vault-reporting/views/dashboard.js.map
  ui/vault-reporting/dist/modifiers/css-custom-property.js
  ui/vault-reporting/dist/modifiers/css-custom-property.js.map
  ui/vault-reporting/dist/styles/vault-reporting.css
  ui/vault-reporting/dist/template-registry.js
  ui/vault-reporting/dist/types/index.js
  ui/vault-reporting/package.json
  ui/yarn.lock
Labels: pr/no-changelog, hashicorp-contributed-pr

#29214 VAULT-33008: Enos tests for removed raft nodes
  enos/enos-modules.hcl
  enos/enos-qualities.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/modules/choose_follower_host/main.tf
  enos/modules/restart_vault/main.tf
  enos/modules/restart_vault/scripts/restart-vault.sh
  enos/modules/vault_raft_remove_node_and_verify/main.tf
  enos/modules/vault_raft_remove_peer/main.tf
  enos/modules/vault_raft_remove_peer/scripts/raft-remove-peer.sh
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_verify_removed_node/main.tf
  enos/modules/vault_verify_removed_node/scripts/verify_manual_rejoin_fails.sh
  enos/modules/vault_verify_removed_node/scripts/verify_raft_remove_peer.sh
  enos/modules/vault_verify_removed_node/scripts/verify_unseal_fails.sh
  enos/modules/vault_verify_removed_node_shim/main.tf
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30200 Fixing some changelog duplicates
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29797 Fix some typos
  Makefile
  audit/broker.go
  builtin/credential/cert/backend_test.go
Labels: docs

#30203 VAULT-34809 Utilization Report docs
  website/content/api-docs/system/utilization-report.mdx
  website/data/api-docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30178 Backport of Allow Root + Intermediate Key_Usage to be set into release/1.19.x
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_root.go
  changelog/30034.txt
  sdk/helper/certutil/types.go
  website/content/api-docs/secret/pki/index.mdx
Labels: hashicorp-contributed-pr

#30217 [DOCS] Add missing include files
  website/content/partials/known-issues/azure-unseal-regression.mdx
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30218 VAULT-35305: fixing enos pki verification issue
  enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
Labels: pr/no-changelog, pr/no-milestone, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30219 Backport of VAULT-35305: fixing enos pki verification issue into release/1.19.x
  enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30220 [DOCS] Add missing partials to fix build errors
  website/content/partials/known-issues/azure-unseal-regression.mdx
  website/content/partials/known-issues/config_listener_proxy_protocol_behavior_issue.mdx
  website/content/partials/known-issues/dangling-entity-aliases-in-memory.mdx
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
  website/content/partials/known-issues/duplicate-identity-groups.mdx
  website/content/partials/known-issues/manual-entity-merge-does-not-persist.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30223 VAULT-35305: fixing enos pki verification
  enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30224 Backport of VAULT-35305: fixing enos pki verification into release/1.19.x
  enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30229 Backport of Fix panic when rotating transit managed keys produces an error into release/1.19.x
  builtin/logical/transit/path_rotate.go
  changelog/30214.txt
Labels: hashicorp-contributed-pr

#30212 Backport of VAULT-33008: Enos tests for removed raft nodes into release/1.19.x
  enos/enos-modules.hcl
  enos/enos-qualities.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-smoke.hcl
  enos/modules/choose_follower_host/main.tf
  enos/modules/restart_vault/main.tf
  enos/modules/restart_vault/scripts/restart-vault.sh
  enos/modules/vault_raft_remove_node_and_verify/main.tf
  enos/modules/vault_raft_remove_peer/main.tf
  enos/modules/vault_raft_remove_peer/scripts/raft-remove-peer.sh
  enos/modules/vault_upgrade/main.tf
  enos/modules/vault_verify_removed_node/main.tf
  enos/modules/vault_verify_removed_node/scripts/verify_manual_rejoin_fails.sh
  enos/modules/vault_verify_removed_node/scripts/verify_raft_remove_peer.sh
  enos/modules/vault_verify_removed_node/scripts/verify_unseal_fails.sh
  enos/modules/vault_verify_removed_node_shim/main.tf
Labels: hashicorp-contributed-pr

#29358 Introduce hashicorp/go-metrics compatibility to the SDK module
  .golangci.yml
  sdk/README.md
  sdk/database/dbplugin/databasemiddleware.go
  sdk/database/dbplugin/v5/middleware.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/metricregistry/metricregistry.go
  sdk/helper/metricregistry/metricregistry_test.go
  sdk/physical/cache.go
  sdk/physical/inmem/cache_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30234 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30213 VAULT-35290 update setup-node to v4.3.0
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30235 Backport of VAULT-35290 update setup-node to v4.3.0 into release/1.19.x
  .github/workflows/build.yml
  .github/workflows/ci.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-run-enos-scenario.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30038 UI: Fix KVv1 Pagination Bug
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/tests/acceptance/secrets/backend/engines-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30231 Backport 1.19.x: Manual backport of rebuilding yarn.lock file
  ui/package.json
  ui/yarn.lock
Labels: ui, backport, hashicorp-contributed-pr

#30173 Update k8s docs
  website/content/docs/platform/k8s/csi/index.mdx
  website/content/docs/platform/k8s/injector/index.mdx
  website/content/docs/platform/k8s/vso/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30187 VAULT-30187: updating aws-nuke version
  .github/workflows/test-ci-cleanup.yml
  enos/ci/aws-nuke.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30246 go: update Go to 1.23.8 to resolve GO-2025-3563
  .go-version
  changelog/_go-ver-1210.txt
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30248 Backport of go: update Go to 1.23.8 to resolve GO-2025-3563 into release/1.19.x
  .go-version
  changelog/_go-ver-1210.txt
Labels: pr/no-milestone, hashicorp-contributed-pr

#30205 [UI] Add engine and auth method mappings to data fetching function
  ui/app/components/usage/page/index.ts
  ui/tests/integration/components/usage/page/index-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#30176 Backport of Cleanup/vault 35002 into release/1.19.x
  builtin/logical/pki/acme_errors.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30252 Backport of fix rootless typo into release/1.19.x
  sdk/helper/pluginruntimeutil/config.go
Labels: hashicorp-contributed-pr

#30251 [auto] Update reporting addon
  ui/vault-reporting/declarations/components/vault-reporting/counter.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/counter.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/global-lease.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/global-lease.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/horizontal-bar-chart.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/horizontal-bar-chart.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/views/dashboard.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/views/dashboard.d.ts.map
  ui/vault-reporting/dist/components/vault-reporting/cluster-replication.js
  ui/vault-reporting/dist/components/vault-reporting/cluster-replication.js.map
  ui/vault-reporting/dist/components/vault-reporting/counter.js
  ui/vault-reporting/dist/components/vault-reporting/counter.js.map
  ui/vault-reporting/dist/components/vault-reporting/global-lease.js
  ui/vault-reporting/dist/components/vault-reporting/global-lease.js.map
  ui/vault-reporting/dist/components/vault-reporting/horizontal-bar-chart.js
  ui/vault-reporting/dist/components/vault-reporting/horizontal-bar-chart.js.map
  ui/vault-reporting/dist/components/vault-reporting/views/dashboard.js
  ui/vault-reporting/dist/components/vault-reporting/views/dashboard.js.map
  ui/vault-reporting/dist/styles/vault-reporting.css
Labels: pr/no-changelog, hashicorp-contributed-pr

#30242 [VAULT-35073] Add base implementation of the loaded snapshot manager
  vault/core.go
  vault/core_util.go
  vault/raft.go
  vault/raft_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30253 UI: Fix KMIP test in 1.19.x
  ui/tests/acceptance/enterprise-kmip-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30164 VAULT-34674
  changelog/30164.txt
  command/command_testonly/operator_usage_testonly_oss_test.go
  vault/activity_log.go
  vault/activity_log_testonly_oss_test.go
  vault/activity_log_util.go
  vault/external_tests/activity_testonly/acme_regeneration_oss_test.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30222 [UI] Ember Data Migration - Update Capabilities Service
  ui/app/services/capabilities.ts
  ui/docs/models.md
  ui/lib/kv/addon/routes/secret.js
  ui/lib/replication/addon/routes/application.js
  ui/tests/unit/services/capabilities-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30232 [UI] Ember Data Migration - Form Class
  ui/app/components/secret-create-or-update.js
  ui/app/decorators/model-validations.js
  ui/app/forms/README.md
  ui/app/forms/form.ts
  ui/app/models/auth-method.js
  ui/app/models/kv/data.js
  ui/app/models/secret-engine.js
  ui/app/utils/forms/field.ts
  ui/app/utils/forms/validate.ts
  ui/app/utils/forms/validators.js
  ui/lib/core/addon/components/kv-object-editor.js
  ui/lib/kv/addon/components/kv-patch/editor/form.js
  ui/tests/integration/components/kv/kv-patch/editor/form-test.js
  ui/tests/unit/decorators/model-validations-test.js
  ui/tests/unit/forms/form-test.js
  ui/tests/unit/utils/forms/field-test.js
  ui/tests/unit/utils/forms/validate-test.js
  ui/tests/unit/utils/forms/validators-test.js
  ui/types/vault/app-types.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30123 UI: Update TOTP Code Generation + Details Flow
  ui/app/components/generate-credentials-totp.hbs
  ui/app/components/generate-credentials-totp.js
  ui/app/components/secret-list/totp-list-item.hbs
  ui/app/components/totp-edit.js
  ui/app/components/totp/key-details.hbs
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/templates/vault/cluster/secrets/backend/credentials.hbs
  ui/tests/acceptance/secrets/backend/totp/key-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/totp/key-form-test.js
Labels: hashicorp-contributed-pr

#30262 Update README.md
  README.md
Labels: docs, pr/no-changelog, pr/no-milestone

#30226 [UI] Ember Data Migration - Pagination Util
  ui/lib/core/addon/utils/paginate-list.ts
  ui/tests/unit/utils/paginate-list-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30267 docs only: add pipeline targets to Makefile
  Makefile
  tools/tools.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30266 Vault 34678-Removing estimates from counters api: Handle billing start date updates CE
  command/server.go
  vault/activity_log.go
  vault/activity_log_util_common.go
  vault/census.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30269 [UI] Capabilities Service Path Bug
  ui/app/services/capabilities.ts
  ui/tests/unit/services/capabilities-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30049 add azure auth security improvement to upgrade guide 1.17.x
  website/content/docs/auth/azure.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30259 [VAULT-34116] Skip TestRaftHACluster_Removed_ReAdd until we fix its flakiness
  vault/external_tests/raftha/raft_ha_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30271 Backport of [VAULT-34116] Skip TestRaftHACluster_Removed_ReAdd until we fix its flakiness into release/1.19.x
  vault/external_tests/raftha/raft_ha_test.go
Labels: hashicorp-contributed-pr

#29866 release/1.16.x: update codeowners
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30245 Backport of UI: Fix KVv1 Pagination Bug into release/1.19.x
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/tests/acceptance/secrets/backend/engines-test.js
Labels: hashicorp-contributed-pr

#30263 Refactoring for returning SSH CA public key with managed keys
  builtin/logical/ssh/path_config_ca.go
  builtin/logical/ssh/path_config_ca_test.go
  builtin/logical/ssh/path_fetch.go
  builtin/logical/ssh/path_issue_sign.go
  builtin/logical/ssh/path_roles.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30265 Update vault-plugin-secrets-openldap to v0.15.3
  changelog/30265.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr, backport/1.19.x

#30274 Backport of Update CODEOWNERS to require a crypto review for Go updates into release/1.19.x
  CODEOWNERS
Labels: backport, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30276 Backport of Update vault-plugin-secrets-openldap to v0.15.3 into release/1.19.x
  changelog/30265.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30272 Update to Go 1.24.2
  .go-version
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/path_root.go
  changelog/_go-ver-1200.txt
  go.mod
  sdk/go.mod
  sdk/helper/certutil/helpers.go
  sdk/plugin/grpc_system.go
  vault/auth_test.go
  vault/mount_test.go
Labels: go, hashicorp-contributed-pr

#30281 Backport of secrets/openldap: update to v0.15.4 into release/1.19.x
  changelog/30279.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29974 disable_mlock must now be explicitly included in config
  builtin/logical/pkiext/pkiext_binary/pki_cluster.go
  changelog/29974.txt
  command/server.go
  command/server/test-fixtures/diagnose_raft_no_bolt_folder.hcl
  command/server_test.go
  command/test-fixtures/config.hcl
  enos/enos-globals.hcl
  enos/modules/start_vault/main.tf
  enos/modules/start_vault/variables.tf
  enos/modules/vault_cluster/main.tf
  sdk/helper/testcluster/docker/environment.go
  sdk/helper/testcluster/docker/environment_test.go
  sdk/helper/testcluster/docker/replication.go
  sdk/helper/testcluster/types.go
  vault/external_tests/misc/misc_binary/recovery_test.go
  vault/external_tests/misc/recover_from_panic_test.go
  vault/external_tests/misc/recovery_test.go
  vault/external_tests/raft/raft_binary/raft_test.go
  website/content/docs/concepts/production-hardening.mdx
  website/content/docs/configuration/index.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30257 UI: Build `Auth::FormTemplate`
  ui/app/components/auth/fields.hbs
  ui/app/components/auth/fields.ts
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/form/base.hbs
  ui/app/components/auth/form/base.ts
  ui/app/components/auth/form/github.js
  ui/app/components/auth/form/ldap.js
  ui/app/components/auth/form/oidc-jwt.js
  ui/app/components/auth/form/okta.js
  ui/app/components/auth/form/radius.js
  ui/app/components/auth/form/saml.js
  ui/app/components/auth/form/token.js
  ui/app/components/auth/form/userpass.js
  ui/app/components/auth/namespace-input.hbs
  ui/app/components/auth/tabs.hbs
  ui/app/styles/helper-classes/colors.scss
  ui/app/styles/utils/_color_variables.scss
  ui/app/utils/supported-login-methods.ts
  ui/tests/acceptance/auth/auth-list-test.js
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/integration/components/auth/fields-test.js
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/form/base-test.js
  ui/tests/integration/components/auth/form/oidc-jwt-test.js
  ui/tests/integration/components/auth/form/okta-test.js
  ui/tests/integration/components/auth/form/saml-test.js
  ui/tests/integration/components/auth/form/test-helper.js
  ui/types/vault/models/cluster.d.ts
  ui/types/vault/services/auth.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30283 Auth test selector cleanup
  ui/app/components/auth-saml.hbs
  ui/app/components/auth/page.hbs
  ui/app/templates/components/auth-form-options.hbs
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-jwt.hbs
  ui/app/templates/components/control-group-success.hbs
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/enterprise-control-groups-test.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/jwt-auth-method-test.js
  ui/tests/acceptance/managed-namespace-test.js
  ui/tests/acceptance/mfa-login-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/oidc-provider-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/integration/components/auth/login-form-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/tests/integration/components/control-group-success-test.js
  ui/tests/pages/auth.js
  ui/tests/pages/components/auth-form.js
  ui/tests/pages/components/auth-jwt.js
  ui/tests/pages/components/control-group-success.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30243 VAULT-34675
  website/content/api-docs/system/internal-counters.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30290 [DOCS] Clean up the Vault Agent & Vault Proxy docs
  website/content/docs/agent-and-proxy/agent/apiproxy.mdx
  website/content/docs/agent-and-proxy/agent/caching/index.mdx
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
  website/content/docs/agent-and-proxy/autoauth/index.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/azure.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cert.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/token_file.mdx
  website/content/docs/agent-and-proxy/autoauth/sinks/file.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30284 VAULT-34834: pipeline: add better heuristics for changed files
  .github/actions/metadata/action.yml
  .github/actions/set-up-go/action.yml
  .github/actions/set-up-pipeline/action.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  tools/pipeline/internal/pkg/changed/checkers.go
  tools/pipeline/internal/pkg/changed/checkers_test.go
  tools/pipeline/internal/pkg/changed/file.go
  tools/pipeline/internal/pkg/github/list_changed_files.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29566 VAULT-30187: Create Enos AWS Engine tests
  enos/ci/service-user-iam/main.tf
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-dr-replication.hcl
  enos/enos-scenario-pr-replication.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/verify_log_secrets/scripts/scan_logs_for_secrets.sh
  enos/modules/verify_secrets_engines/modules/create/aws.tf
  enos/modules/verify_secrets_engines/modules/create/main.tf
  enos/modules/verify_secrets_engines/modules/read/aws.tf
  enos/modules/verify_secrets_engines/modules/read/main.tf
  enos/modules/verify_secrets_engines/scripts/aws-generate-roles.sh
  enos/modules/verify_secrets_engines/scripts/aws-verify-new-creds.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30300 UI: Assume default auth path if custom path is not provided
  ui/app/components/auth/form/base.hbs
  ui/app/components/auth/form/base.ts
  ui/tests/integration/components/auth/form/base-test.js
  ui/tests/integration/components/auth/form/oidc-jwt-test.js
  ui/tests/integration/components/auth/form/okta-test.js
  ui/tests/integration/components/auth/form/saml-test.js
  ui/tests/integration/components/auth/form/test-helper.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30305 CODEOWNERS: update quality group name and add customer eng to docs
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30286 Rename EntCoreConfig to lowercase to preserve encapsulation
  vault/core.go
  vault/core_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30275 UI: Add password field to static role creation page
  changelog/30275.txt
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-setting-form.hbs
  ui/app/utils/model-helpers/database-helpers.js
  ui/lib/core/addon/components/enable-input.hbs
  ui/lib/core/addon/components/enable-input.ts
  ui/tests/integration/components/database-role-edit-test.js
Labels: ui, hashicorp-contributed-pr

#30306 Backport of CODEOWNERS: update quality group name and add customer eng to docs into release/1.19.x
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30307 CODEOWNERS: update quality group name and add customer eng to docs
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30308 CODEOWNERS: update quality group name and add customer eng to docs co…
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30309 CODEOWNERS: update quality group name and add customer eng to docs co…
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30296 Backport of VAULT-34834: pipeline: add better heuristics for changed files into release/1.19.x
  .github/actions/metadata/action.yml
  .github/actions/set-up-go/action.yml
  .github/actions/set-up-pipeline/action.yml
  .github/workflows/build.yml
  .github/workflows/ci.yml
  tools/pipeline/internal/pkg/changed/checkers.go
  tools/pipeline/internal/pkg/changed/checkers_test.go
  tools/pipeline/internal/pkg/changed/file.go
  tools/pipeline/internal/pkg/github/list_changed_files.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30293 Backport of [DOCS] Clean up the Vault Agent & Vault Proxy docs into release/1.19.x
  website/content/docs/agent-and-proxy/agent/apiproxy.mdx
  website/content/docs/agent-and-proxy/agent/caching/index.mdx
  website/content/docs/agent-and-proxy/agent/index.mdx
  website/content/docs/agent-and-proxy/agent/winsvc.mdx
  website/content/docs/agent-and-proxy/autoauth/index.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/azure.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/cert.mdx
  website/content/docs/agent-and-proxy/autoauth/methods/token_file.mdx
  website/content/docs/agent-and-proxy/autoauth/sinks/file.mdx
  website/content/docs/agent-and-proxy/index.mdx
  website/content/docs/agent-and-proxy/proxy/apiproxy.mdx
  website/content/docs/agent-and-proxy/proxy/caching/index.mdx
  website/content/docs/agent-and-proxy/proxy/index.mdx
Labels: hashicorp-contributed-pr

#30298 Address UI Flaky Tests
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/leases-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/transit-test.js
  ui/tests/integration/components/auth/login-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30311 Backport of VAULT-30187: Create Enos AWS Engine tests into release/1.19.x
  enos/ci/service-user-iam/main.tf
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-dr-replication.hcl
  enos/enos-scenario-pr-replication.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/verify_log_secrets/scripts/scan_logs_for_secrets.sh
  enos/modules/verify_secrets_engines/modules/create/aws.tf
  enos/modules/verify_secrets_engines/modules/create/main.tf
  enos/modules/verify_secrets_engines/modules/read/aws.tf
  enos/modules/verify_secrets_engines/modules/read/main.tf
  enos/modules/verify_secrets_engines/scripts/aws-generate-roles.sh
  enos/modules/verify_secrets_engines/scripts/aws-verify-new-creds.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30324 UI: Fix for failing DB role test
  ui/tests/integration/components/database-role-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30319 Delta CRL enablement, including tests.
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/issuing/aia.go
  builtin/logical/pki/path_config_urls.go
  builtin/logical/pki/path_fetch_issuers.go
  builtin/logical/pki/path_intermediate.go
  builtin/logical/pki/path_manage_issuers.go
  builtin/logical/pki/path_root.go
  changelog/30319.txt
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
Labels: cryptosec, hashicorp-contributed-pr

#30282 docs: fix version of static role rotation issue
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/partials/known-issues/database-static-role-premature-rotations.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30331 Backport of docs: fix version of static role rotation issue into release/1.19.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/partials/known-issues/database-static-role-premature-rotations.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#30321 enos(mlock): sync enos changes from main to 1.19
  enos/README.md
  enos/ci/aws-nuke.yml
  enos/enos-globals.hcl
  enos/modules/start_vault/main.tf
  enos/modules/start_vault/variables.tf
  enos/modules/vault_cluster/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/ent/1.18.x+ent

#30181 Chore/remove ember svg jar
  changelog/30181.txt
  ui/app/controllers/vault/cluster/access/mfa/methods/create.js
  ui/app/models/mfa-method.js
  ui/app/styles/components/init-illustration.scss
  ui/app/styles/core.scss
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/app/templates/vault/cluster/init.hbs
  ui/ember-cli-build.js
  ui/lib/core/addon/components/icon.hbs
  ui/lib/core/addon/components/icon.js
  ui/lib/core/icon-mappings.js
  ui/lib/core/package.json
  ui/package.json
  ui/public/android-sync.svg
  ui/public/console.svg
  ui/public/duo.svg
  ui/public/file-error.svg
  ui/public/file-success.svg
  ui/public/hashicorp.svg
  ui/public/initialize.svg
  ui/public/loop.svg
  ui/public/okta.svg
  ui/public/perf-replication.svg
  ui/public/pingid.svg
  ui/public/replication.svg
  ui/public/reply.svg
  ui/public/stopwatch.svg
  ui/public/tour.svg
  ui/public/vault-logo.svg
  ui/tests/integration/components/icon-test.js
  ui/yarn.lock
Labels: ui, pr/no-milestone, hashicorp-contributed-pr

#30336 test(enos): always build artifacts and test when enos files change
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30337 backport-assistant: use the latest version of the backport-assistant
  .github/workflows/backport-ce.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30338 Backport of test(enos): always build artifacts and test when enos files change into release/1.19.x
  .github/workflows/build.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30339 Docs: include missing known issue partial
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30342 Docs: include missing known issue partial
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30261 [UI] Mount vault-reporting components
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/cluster.js
  ui/app/components/usage/page.hbs
  ui/app/components/usage/page.ts
  ui/app/router.js
  ui/app/services/permissions.js
  ui/app/styles/components/usage-page.scss
  ui/app/styles/core.scss
  ui/app/templates/vault/cluster/usage-reporting.hbs
  ui/ember-cli-build.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/components/usage/page/index-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#30316 UI: Build Okta auth method component
  ui/app/components/auth/form/base.ts
  ui/app/components/auth/form/okta.hbs
  ui/app/components/auth/form/okta.js
  ui/app/components/auth/form/okta.ts
  ui/lib/core/addon/utils/uuid.js
  ui/lib/core/app/utils/uuid.js
  ui/tests/integration/components/auth/form/okta-test.js
  ui/tests/integration/components/auth/form/test-helper.js
  ui/types/vault/services/auth.d.ts
Labels: pr/no-changelog, hashicorp-contributed-pr

#30310 Backport of Rename EntCoreConfig to lowercase to preserve encapsulation into release/1.19.x
  vault/core.go
  vault/core_util.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#30346 🤖 - CI Fix - UI Dependencies step
  ui/package.json
  ui/tests/acceptance/pki/pki-action-forms-test.js
  ui/yarn.lock
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30350 VAULT-35615 security(scanner): suppress CVE-2025-46394
  .release/security-scan.hcl
  scan.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30353 backport-assistant: use the new tag schema
  .github/workflows/backport-ce.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30356 VAULT-35615 security(scanner): suppress CVE-2025-46394 1.19.x (#30350)
  .release/security-scan.hcl
  scan.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30360 Backport of ci: fix logic in apupgrade workflow into release/1.19.x
  .github/workflows/ci.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30364 VAULT-35624: Common snapshot source interface
  vault/logical_system_raft.go
  vault/logical_system_stubs_oss.go
  vault/snapshots/source.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30315 Update known issue documentation with symptoms
  website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30373 add known issue docs for azure auth uniform vmss regression
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30328 [UI] Ember Data Migration: has-capabilities helper
  ui/app/services/capabilities.ts
  ui/lib/core/addon/helpers/has-capability.ts
  ui/lib/core/addon/utils/capabilities.ts
  ui/lib/core/app/helpers/has-capability.js
  ui/tests/unit/helpers/has-capability-test.js
  ui/types/vault/app-types.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30326 [UI] Ember Data Migration: Form Class Proxy
  ui/app/forms/form.ts
  ui/app/utils/forms/field.ts
  ui/tests/unit/forms/form-test.js
  ui/tests/unit/utils/forms/field-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30375 [UI] Pins Embroider Macros Dep to 1.15.0
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30352 Missing OpenAPI Fields For Custom Messages
  vault/logical_system_custom_messages.go
  vault/logical_system_paths.go
Labels: pr/no-changelog, go, hashicorp-contributed-pr

#30374 Backport of add known issue docs for azure auth uniform vmss regression into release/1.19.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30377 manual backport of #30373 to 1.17: add known issue docs for azure auth uniform vmss regression
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30378 manual backport of #30373 to 1.16: add known issue docs for azure auth uniform vmss regression
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/partials/known-issues/azure-auth-fails-uniform-vmss.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30369 Backport of Update known issue documentation with symptoms into release/1.19.x
  website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30332 API-Docs for new Delta_CRL_Distribution_Points field
  website/content/api-docs/secret/pki/index.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30381 Update to Go 1.24.2
  .go-version
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/path_root.go
  changelog/_go-ver-1193.txt
  go.mod
  sdk/go.mod
  sdk/helper/certutil/helpers.go
  sdk/plugin/grpc_system.go
  vault/auth_test.go
  vault/mount_test.go
Labels: hashicorp-contributed-pr

#30382 UI: Cleanup and update selectors in Secret Engine tests
  ui/app/components/dashboard/secrets-engines-card.hbs
  ui/app/routes/vault/cluster/secrets/backends.ts
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/vault/cluster/secrets/backend/list.hbs
  ui/app/templates/vault/cluster/secrets/backend/overview.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/tests/acceptance/enterprise-kmse-test.js
  ui/tests/acceptance/enterprise-transform-test.js
  ui/tests/acceptance/leases-test.js
  ui/tests/acceptance/policies/index-test.js
  ui/tests/acceptance/secrets/backend/aws/aws-test.js
  ui/tests/acceptance/secrets/backend/cubbyhole/secret-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/database/workflow-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/acceptance/secrets/backend/generic/secret-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-edge-cases-test.js
  ui/tests/acceptance/secrets/backend/kv/kv-v2-workflow-navigation-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/secrets/backend/ssh/roles-test.js
  ui/tests/acceptance/secrets/backend/totp/key-test.js
  ui/tests/acceptance/settings/mount-secret-backend-test.js
  ui/tests/acceptance/transit-test.js
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/dashboard/secrets-engines-card-test.js
  ui/tests/pages/secrets/backend/database/connection.js
  ui/tests/pages/secrets/backend/kv/edit-secret.js
  ui/tests/pages/secrets/backend/list.js
  ui/tests/pages/secrets/backend/transform/alphabets.js
  ui/tests/pages/secrets/backend/transform/templates.js
  ui/tests/pages/secrets/backend/transform/transformations.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30347 Add ce changes for managed key signatures
  builtin/logical/ssh/managed_key/common.go
  builtin/logical/ssh/managed_key/managed_key_util_ce.go
  builtin/logical/ssh/path_config_ca.go
  builtin/logical/ssh/path_issue_sign.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30392 Backport of bugfix: vault register should respect tmpdir into release/1.19.x
  changelog/29978.txt
  vault/plugincatalog/plugin_catalog_stubs_oss.go
Labels: hashicorp-contributed-pr

#30371 UI: Builds OIDC-JWT component
  ui/app/components/auth/form/base.ts
  ui/app/components/auth/form/oidc-jwt.hbs
  ui/app/components/auth/form/oidc-jwt.js
  ui/app/components/auth/form/oidc-jwt.ts
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/form/oidc-jwt-test.js
  ui/types/ember-data/types/registries/adapter.d.ts
  ui/types/vault/adapters/auth-method.d.ts
  ui/types/vault/services/auth.d.ts
Labels: pr/no-changelog, hashicorp-contributed-pr

#30389 Revert "Update to Go 1.24.2 (#30381)"
  .go-version
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/path_root.go
  changelog/_go-ver-1193.txt
  go.mod
  sdk/go.mod
  sdk/helper/certutil/helpers.go
  sdk/plugin/grpc_system.go
  vault/auth_test.go
  vault/mount_test.go
Labels: hashicorp-contributed-pr
