Repository hashicorp/vault, pull requests merged in 2025-01, with the labels that each got.

#29176 Prevent barrier term overflow on rotation
  changelog/29176.txt
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29271 Backport of Prevent barrier term overflow on rotation into release/1.18.x
  changelog/29176.txt
  vault/barrier_aes_gcm.go
  vault/barrier_aes_gcm_test.go
Labels: backport, hashicorp-contributed-pr

#29268 Revert "Storing local clients to local storage paths ce changes"
  command/command_testonly/operator_usage_testonly_test.go
  sdk/helper/clientcountutil/clientcountutil.go
  sdk/helper/clientcountutil/clientcountutil_test.go
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
  vault/external_tests/activity_testonly/acme_regeneration_test.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
  vault/logical_system_activity_write_testonly.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29263 Add UI support name constraints
  builtin/logical/pki/fields.go
  changelog/29263.txt
  ui/app/models/pki/sign-intermediate.js
  ui/lib/core/addon/components/form-field.js
  ui/lib/pki/addon/components/pki-generate-toggle-groups.hbs
  ui/lib/pki/addon/components/pki-sign-intermediate-form.ts
  ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
Labels: ui, hashicorp-contributed-pr

#29262 Correcting the changelog
  CHANGELOG.md
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29277 Revert "add fragment locks to GetActiveLocalFragment and GetActiveFragment"
  vault/activity_log_testing_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29274 CE side changes to key policy engine for ML-DSA/Hybrid support
  builtin/logical/pki/cert_util_test.go
  builtin/logical/transit/path_export_ce_test.go
  builtin/logical/transit/path_export_test.go
  builtin/logical/transit/path_import.go
  builtin/logical/transit/path_keys.go
  sdk/helper/keysutil/policy.go
  sdk/helper/keysutil/policy_ce.go
  sdk/helper/keysutil/policy_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29276 fix db test data race for queue tick interval
  builtin/logical/database/rotation_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29278 Revert "adding local clients to local fragments ce changes"
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29280 Simply remove any ent machinery from the export test
  builtin/logical/transit/path_export_ce_test.go
  builtin/logical/transit/path_export_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29281 Revert "Send global client data from secondaries to primary to keep in memory."
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_testing_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29229 protobuf: rebuild protos with protobuf 1.36
  builtin/logical/pki/metadata.pb.go
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29284 Revert "Added Stubs to Stop Breaking Builds in Ent"
  vault/activity_log_stubs_oss.go
  vault/activity_log_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29285 Revert "Creates Skeleton RPC to send global client data to primaries …
  vault/activity/activity_log.pb.go
  vault/activity/activity_log.proto
  vault/activity_log.go
  vault/activity_log_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29222 Docs: add migrate Consul storage document
  website/content/docs/concepts/integrated-storage/migrate-consul-storage.mdx
  website/data/docs-nav-data.json
  website/public/img/vault-ent-replication-2.png
  website/public/img/vault-ent-replication-3.png
  website/public/img/vault-ent-replication.png
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29288 Backport of Docs: add migrate Consul storage document into release/1.18.x
  website/content/docs/concepts/integrated-storage/migrate-consul-storage.mdx
  website/data/docs-nav-data.json
  website/public/img/vault-ent-replication-2.png
  website/public/img/vault-ent-replication-3.png
  website/public/img/vault-ent-replication.png
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29289 Update an expired certificate within the cert-auth test fixtures
  builtin/credential/cert/test-fixtures/keys/cert.pem
  builtin/credential/cert/test-fixtures/keys/rebuild-cert.md
  vault/diagnose/tls_verification_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29282 More CE changes for hybrid wireup
  builtin/logical/transit/backend_ce.go
  builtin/logical/transit/path_export.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29256 Backport of Sort CA chain into root and intermediates on VerifyCertificate. into release/1.18.x
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  changelog/29255.txt
Labels: hashicorp-contributed-pr

#29295 Update vault-plugin-auth-cf to v0.19.1
  changelog/29295.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.18.x

#29294 Revert "Store tokens in local storage paths"
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29296 Backport of Update vault-plugin-auth-cf to v0.19.1 into release/1.18.x
  changelog/29295.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29297 Remove potentially misleading part of automated reporting docs
  website/content/docs/enterprise/license/utilization-reporting.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29290 UI: Remove kv data download button
  changelog/29290.txt
  ui/lib/kv/addon/components/kv-data-fields.hbs
Labels: ui, hashicorp-contributed-pr

#29270 fixes for flakes in raft removed tests
  helper/testhelpers/testhelpers.go
  physical/raft/testing.go
  vault/external_tests/raft/raft_test.go
  vault/external_tests/raftha/raft_ha_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29307 test: fix ce/ent diff
  builtin/logical/database/rotation_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29306 [VAULT-21282] Bump raft-autopilot dependency to v0.3.0
  go.mod
  go.sum
Labels: dependencies, pr/no-changelog

#29293 UI: LDAP Hierarchical Library names
  changelog/29293.txt
  ui/app/adapters/ldap/library.js
  ui/app/adapters/ldap/role.js
  ui/app/models/ldap/library.js
  ui/app/models/ldap/role.js
  ui/lib/ldap/addon/components/page/libraries.hbs
  ui/lib/ldap/addon/components/page/libraries.ts
  ui/lib/ldap/addon/components/page/roles.hbs
  ui/lib/ldap/addon/components/page/roles.ts
  ui/lib/ldap/addon/routes.js
  ui/lib/ldap/addon/routes/libraries/library/check-out.ts
  ui/lib/ldap/addon/routes/libraries/library/details.ts
  ui/lib/ldap/addon/routes/libraries/library/edit.ts
  ui/lib/ldap/addon/routes/libraries/subdirectory.ts
  ui/lib/ldap/addon/routes/roles/role/credentials.ts
  ui/lib/ldap/addon/routes/roles/role/details.ts
  ui/lib/ldap/addon/routes/roles/role/edit.ts
  ui/lib/ldap/addon/routes/roles/subdirectory.ts
  ui/lib/ldap/addon/templates/libraries/subdirectory.hbs
  ui/lib/ldap/addon/utils/ldap-breadcrumbs.ts
  ui/mirage/handlers/ldap.js
  ui/mirage/scenarios/ldap.js
  ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
  ui/tests/helpers/ldap/ldap-selectors.ts
  ui/tests/integration/components/ldap/page/libraries-test.js
  ui/tests/unit/adapters/ldap/role-test.js
  ui/tests/unit/utils/ldap-breadcrumbs-test.js
  ui/types/vault/models/ldap/library.d.ts
  ui/types/vault/models/ldap/role.d.ts
Labels: ui, hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent

#29241 VAULT-32677 - Fix missing client count card in managed clusters
  changelog/29241.txt
  ui/app/components/dashboard/overview.hbs
  ui/app/components/dashboard/overview.ts
  ui/tests/integration/components/dashboard/overview-test.js
Labels: ui, backport, hashicorp-contributed-pr

#29134 Vault 27392 log ldap warning - remove from warning from response
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/backend_test.go
  changelog/29134.txt
Labels: hashicorp-contributed-pr

#29273 Add SDK helpers and Core stubs for plugins to communicate with Enterprise Rotation Manager
  builtin/logical/aws/backend.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/aws/path_config_root_test.go
  changelog/29273.txt
  sdk/framework/backend.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/automatedrotationutil/fields.go
  sdk/logical/request.go
  sdk/logical/system_view.go
  sdk/plugin/grpc_system.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/backend_grpc.pb.go
  sdk/rotation/rotation_job.go
  sdk/rotation/schedule.go
  vault/activity/activity_log.pb.go
  vault/core.go
  vault/core_test.go
  vault/dynamic_system_view.go
  vault/rotation_stubs_oss.go
Labels: hashicorp-contributed-pr

#29311 Update docs for auth-cf
  website/content/api-docs/auth/cf.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29310 backport release/1.18.x: db skip auto import rotation
  builtin/logical/database/backend.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_config_connection_ce.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_roles_ce.go
  builtin/logical/database/path_rotate_credentials.go
  builtin/logical/database/rotation.go
  builtin/logical/database/rotation_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29302 Vault 27421 update cap/ldap dep
  changelog/29302.txt
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
Labels: hashicorp-contributed-pr

#29146 Updated description of the `TLS CA` field
  ui/app/models/database/connection.js
Labels: pr/no-changelog, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29315 update copywrite exceptions to exclude *_ent.go
  scripts/copywrite-exceptions.sh
Labels: pr/no-changelog, pr/no-milestone, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29317 Backport of update copywrite exceptions to exclude *_ent.go into release/1.18.x
  scripts/copywrite-exceptions.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29319 exclude *_ent_test.go from copywrite-exceptions.sh
  scripts/copywrite-exceptions.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29318 protobuf: rebuild protos with protobuf 1.36.2
  builtin/logical/pki/metadata.pb.go
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29316 Backport of Updated description of the `TLS CA` field into release/1.18.x
  ui/app/models/database/connection.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#29320 Backport of exclude *_ent_test.go from copywrite-exceptions.sh into release/1.18.x
  scripts/copywrite-exceptions.sh
Labels: pr/no-milestone, hashicorp-contributed-pr

#29237 Port activation flags with dynamic registration
  changelog/29237.txt
  helper/activationflags/activation_flags.go
  vault/core.go
  vault/core_util.go
  vault/logical_system.go
  vault/logical_system_activation_flags.go
  vault/logical_system_activation_flags_test.go
  vault/logical_system_helpers.go
Labels: hashicorp-contributed-pr

#29301 Add identity cleanup activation flag
  vault/logical_system_activation_flags.go
  vault/logical_system_activation_flags_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29113 plugin register with artifact stubs VAULT-32686
  command/commands.go
  command/plugin_register_stubs_oss.go
  sdk/helper/pluginutil/runner.go
  sdk/helper/pluginutil/runner_stubs_oss.go
  vault/logical_system.go
  vault/logical_system_plugins_stubs_oss.go
  vault/plugincatalog/plugin_catalog.go
  vault/plugincatalog/plugin_catalog_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29300 Add information about an enterprise feature related to validating iss…
  website/content/api-docs/secret/pki/index.mdx
Labels: docs, secret/pki, pr/no-changelog, hashicorp-contributed-pr

#29097 sdk/db: do not hold the lock on Close
  changelog/29097.txt
  sdk/database/dbplugin/v5/grpc_client.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/database/dbplugin/v5/grpc_server_test.go
  sdk/helper/pluginutil/env.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#29303 CE changes for vault-31750
  changelog/29303.txt
  physical/raft/raft.go
  physical/raft/raft_autopilot.go
  sdk/plugin/pb/backend.pb.go
  vault/logical_system_raft.go
Labels: hashicorp-contributed-pr

#29246 Add docs for ML-DSA and hybrid keys
  website/content/api-docs/secret/transit.mdx
  website/content/docs/secrets/transit/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#29333 Backport of sdk/db: do not hold the lock on Close into release/1.18.x
  changelog/29097.txt
  sdk/database/dbplugin/v5/grpc_client.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/database/dbplugin/v5/grpc_server_test.go
  sdk/helper/pluginutil/env.go
Labels: hashicorp-contributed-pr

#29327 Backport of plugin register with artifact stubs VAULT-32686 into release/1.18.x
  command/commands.go
  command/plugin_register_stubs_oss.go
  sdk/helper/pluginutil/runner.go
  sdk/helper/pluginutil/runner_stubs_oss.go
  vault/logical_system.go
  vault/logical_system_plugins_stubs_oss.go
  vault/plugincatalog/plugin_catalog.go
  vault/plugincatalog/plugin_catalog_stubs_oss.go
Labels: hashicorp-contributed-pr

#29334 replace keyring dependency to address zombie dbus-daemons processes
  changelog/29334.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29335 Add build flag for CE-specific activation flag tests
  vault/logical_system_activation_flags_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29337 Backport/release/1.18.x/gosnowflake replace keyring
  changelog/29334.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29152 docs/vault-k8s: updates for v1.6.0 release
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29340 Backport of docs/vault-k8s: updates for v1.6.0 release into release/1.18.x
  website/content/docs/platform/k8s/injector/annotations.mdx
  website/content/docs/platform/k8s/injector/index.mdx
Labels: hashicorp-contributed-pr

#29322 docs/vso: instant updates (#27668)
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
  website/content/docs/platform/k8s/vso/secret-transformation.mdx
  website/content/docs/platform/k8s/vso/sources/hvs.mdx
  website/content/docs/platform/k8s/vso/sources/vault/auth/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/index.mdx
  website/content/docs/platform/k8s/vso/sources/vault/instant-updates.mdx
  website/content/partials/vso/common-links.mdx
  website/data/docs-nav-data.json
Labels: pr/no-milestone, hashicorp-contributed-pr

#29329 Exit raft removed checker if raft isn't initialized
  physical/raft/raft.go
  vault/external_tests/raftha/raft_ha_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29338 String to camelCase helper
  ui/app/helpers/string-array-to-camel.js
  ui/tests/integration/helpers/string-array-to-camel-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29291 move system view interface, grpc server, and client to stubs_oss files
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/grpc_backend_client_stubs_oss.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_backend_server_stubs_oss.go
  vault/dynamic_system_view.go
  vault/extended_system_view.go
  vault/extended_system_view_stubs_oss.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29343 Backport of move system view interface, grpc server, and client to stubs_oss files into release/1.18.x
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/grpc_backend_client_stubs_oss.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_backend_server_stubs_oss.go
  vault/dynamic_system_view.go
  vault/extended_system_view.go
  vault/extended_system_view_stubs_oss.go
Labels: hashicorp-contributed-pr

#29299 Add 'how to run' instructions to each Enos scenario'
  enos/enos-dev-scenario-pr-replication.hcl
  enos/enos-dev-scenario-single-cluster.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-dr-replication.hcl
  enos/enos-scenario-pr-replication.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29345 Prep work for creating one WIF configuration component
  ui/app/models/aws/lease-config.js
  ui/app/models/aws/root-config.js
  ui/app/models/gcp/config.js
  ui/app/models/ssh/ca-config.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-aws-test.js
  ui/tests/integration/components/secret-engine/configure-azure-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29098 docs: DB skip auto import rotation
  website/content/api-docs/secret/databases/index.mdx
  website/content/docs/secrets/databases/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29313 Backport of Update docs for auth-cf into release/1.18.x
  website/content/api-docs/auth/cf.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29356 identity: Resolve conflicts with rename
  changelog/29356.txt
  helper/activationflags/activation_flags.go
  helper/identity/identity.go
  vault/identity_store.go
  vault/identity_store_conflicts.go
  vault/identity_store_conflicts_test.go
  vault/identity_store_entities.go
  vault/identity_store_test.go
  vault/identity_store_util.go
  vault/logical_system_activation_flags.go
  vault/logical_system_activation_flags_test.go
Labels: hashicorp-contributed-pr

#29348 Backport of Add 'how to run' instructions to each Enos scenario' into release/1.18.x
  enos/enos-dev-scenario-pr-replication.hcl
  enos/enos-dev-scenario-single-cluster.hcl
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-dr-replication.hcl
  enos/enos-scenario-pr-replication.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-ui.hcl
  enos/enos-scenario-upgrade.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29361 docs: fixed typo in kv v1 upgrade docs
  website/content/docs/secrets/kv/kv-v2/upgrade.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.18.x

#29363 Backport of docs: fixed typo in kv v1 upgrade docs into release/1.18.x
  website/content/docs/secrets/kv/kv-v2/upgrade.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29138 Fix Static Role Name Consistency in PostgreSQL Configuration
  website/content/docs/secrets/databases/postgresql.mdx
Labels: docs, bug, secret/database/postgresql, pr/no-changelog, pr/no-milestone, backport/1.18.x

#29366 Backport of Fix Static Role Name Consistency in PostgreSQL Configuration into release/1.18.x
  website/content/docs/secrets/databases/postgresql.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29370 Fix misleading comments about namespaces in docs
  website/content/partials/telemetry-metrics/vault/identity/entity/active/monthly.mdx
  website/content/partials/telemetry-metrics/vault/identity/entity/active/partial_month.mdx
  website/content/partials/telemetry-metrics/vault/identity/entity/active/reporting_period.mdx
  website/content/partials/telemetry-metrics/vault/identity/entity/count.mdx
  website/content/partials/telemetry-metrics/vault/identity/entity/creation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29374 Backport of Fix typo: compatability => compatibility into release/1.18.x
  Makefile
  website/content/docs/secrets/key-management/awskms.mdx
  website/content/docs/secrets/key-management/gcpkms/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29001 Backport of adding logic to handle cloud-init error code 2 into release/1.18.x
  enos/modules/install_packages/scripts/synchronize-repos.sh
Labels: pr/no-milestone, hashicorp-contributed-pr

#29376 VLT-32875 Export API panics when mount is deleted #7288
  changelog/29376.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29359 proto: bump protoc-gen-go to 1.36.3
  builtin/logical/pki/metadata.pb.go
  go.mod
  go.sum
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/go.mod
  sdk/go.sum
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29387 Backport of VLT-32875 Export API panics when mount is deleted #7288 into release/1.18.x
  changelog/29376.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/activity_log_util_common.go
  vault/activity_log_util_common_test.go
Labels: hashicorp-contributed-pr

#29386 Websocket lib has moved, see https://coder.com/blog/websocket.
  command/agentproxyshared/cache/static_secret_cache_updater.go
  command/agentproxyshared/cache/static_secret_cache_updater_test.go
  command/events.go
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29195 doc updates to include new fields for SAML sig validation
  website/content/api-docs/auth/saml.mdx
  website/content/docs/auth/saml/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29388 Backport 1.18.x - UI: Fix LDAP Mirage Handler
  ui/lib/ldap/addon/components/page/library/details/accounts.ts
  ui/mirage/handlers/ldap.js
  ui/mirage/models/ldap-account-status.js
  ui/mirage/scenarios/ldap.js
  ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
  ui/tests/acceptance/secrets/backend/ldap/overview-test.js
  ui/tests/acceptance/secrets/backend/ldap/roles-test.js
  ui/tests/integration/components/ldap/page/library/details/accounts-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29344 update docs for eventing (#28950)
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-milestone, hashicorp-contributed-pr

#29346 update docs for eventing (#28950)
  website/content/docs/concepts/events.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29393 ignore system view service ent in buf linter
  buf.yaml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29390 Backport 1.18.x UI: LDAP Hierarchical Library names (#29293)
  changelog/29293.txt
  ui/app/adapters/ldap/library.js
  ui/app/adapters/ldap/role.js
  ui/app/models/ldap/library.js
  ui/app/models/ldap/role.js
  ui/lib/ldap/addon/components/page/libraries.hbs
  ui/lib/ldap/addon/components/page/libraries.ts
  ui/lib/ldap/addon/components/page/roles.hbs
  ui/lib/ldap/addon/components/page/roles.ts
  ui/lib/ldap/addon/routes.js
  ui/lib/ldap/addon/routes/libraries/library/check-out.ts
  ui/lib/ldap/addon/routes/libraries/library/details.ts
  ui/lib/ldap/addon/routes/libraries/library/edit.ts
  ui/lib/ldap/addon/routes/libraries/subdirectory.ts
  ui/lib/ldap/addon/routes/roles/role/credentials.ts
  ui/lib/ldap/addon/routes/roles/role/details.ts
  ui/lib/ldap/addon/routes/roles/role/edit.ts
  ui/lib/ldap/addon/routes/roles/subdirectory.ts
  ui/lib/ldap/addon/templates/libraries/subdirectory.hbs
  ui/lib/ldap/addon/utils/ldap-breadcrumbs.ts
  ui/mirage/handlers/ldap.js
  ui/mirage/scenarios/ldap.js
  ui/tests/acceptance/secrets/backend/ldap/libraries-test.js
  ui/tests/helpers/ldap/ldap-selectors.ts
  ui/tests/integration/components/ldap/page/libraries-test.js
  ui/tests/unit/adapters/ldap/role-test.js
  ui/tests/unit/utils/ldap-breadcrumbs-test.js
  ui/types/vault/models/ldap/library.d.ts
  ui/types/vault/models/ldap/role.d.ts
Labels: hashicorp-contributed-pr, backport/ent/1.17.x+ent

#29394 Backport of ignore system view service ent in buf linter into release/1.18.x
  buf.yaml
Labels: hashicorp-contributed-pr

#29007 VAULT-32188: Enos test for PKI certificates
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-dr-replication.hcl
  enos/enos-scenario-pr-replication.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/verify_secrets_engines/modules/create/main.tf
  enos/modules/verify_secrets_engines/modules/create/pki.tf
  enos/modules/verify_secrets_engines/modules/read/main.tf
  enos/modules/verify_secrets_engines/modules/read/pki.tf
  enos/modules/verify_secrets_engines/scripts/pki-issue-certificates.sh
  enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29395 Update release notes for 1.17.x
  website/content/docs/release-notes/1.17.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29397 [MANUAL BACKPORT] Update 1.17.x release notes
  website/content/docs/release-notes/1.17.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29398 Backport of Update release notes for 1.17.x into release/1.18.x
  website/content/docs/release-notes/1.17.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29400 use elevated github token in plugin-update gha ent step
  .github/workflows/plugin-update.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29404 update go-slug to 0.16.3
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29360 Backport of sdk: updating to docker v27.2.1 into release/1.18.x
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/docker/testhelpers.go
Labels: hashicorp-contributed-pr

#29405 Backport of update go-slug to 0.16.3 into release/1.18.x
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29326 VAULT-31907: Entity loading speedup
  changelog/29326.txt
  vault/identity_store_util.go
Labels: hashicorp-contributed-pr

#29367 One WIF configuration component
  ui/app/components/secret-engine/configure-aws.hbs
  ui/app/components/secret-engine/configure-aws.ts
  ui/app/components/secret-engine/configure-azure.ts
  ui/app/components/secret-engine/configure-wif.hbs
  ui/app/components/secret-engine/configure-wif.ts
  ui/app/controllers/vault/cluster/secrets/backend/configuration/edit.js
  ui/app/models/aws/root-config.js
  ui/app/models/azure/config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/templates/vault/cluster/secrets/backend/configuration/edit.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/secret-engine/configure-aws-test.js
  ui/tests/integration/components/secret-engine/configure-azure-test.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
  ui/types/vault/models/aws/lease-config.d.ts
  ui/types/vault/models/aws/root-config.d.ts
  ui/types/vault/models/azure/config.d.ts
  ui/types/vault/models/secret-engine/additional-config.d.ts
  ui/types/vault/models/secret-engine/mount-config.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29118 Adds an option to enable sAMAccountname logins when upndomain is set
  changelog/29118.txt
  sdk/helper/ldaputil/config.go
  sdk/helper/ldaputil/config_test.go
  website/content/api-docs/auth/ldap.mdx
  website/content/docs/auth/ldap.mdx
Labels: ecosystem, auth/ldap, pr/no-milestone

#29407 db: return success response on static role create/update
  builtin/logical/database/path_roles.go
Labels: backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29321 actions: pin to the latest approved workflows
  .github/actions/build-vault/action.yml
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/actions/create-dynamic-config/action.yml
  .github/actions/run-apupgrade-tests/action.yml
  .github/actions/set-up-go/action.yml
  .github/actions/set-up-pipeline/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/benchmark-prevent-performance-degradations.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-containers.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .github/workflows/test-run-enos-scenario.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29410 OpenAPI LDAP config update: Add enableSamaccountnameLogin param
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#29399 database/mssql: set default root rotation stmt for contained db
  changelog/29399.txt
  plugins/database/mssql/mssql.go
  plugins/database/mssql/mssql_test.go
  website/content/docs/secrets/databases/mssql.mdx
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29414 Backport of database/mssql: set default root rotation stmt for contained db into release/1.18.x
  changelog/29399.txt
  plugins/database/mssql/mssql.go
  plugins/database/mssql/mssql_test.go
  website/content/docs/secrets/databases/mssql.mdx
Labels: hashicorp-contributed-pr

#29411 Backport of actions: pin to the latest approved workflows into release/1.18.x
  .github/actions/build-vault/action.yml
  .github/actions/changed-files/action.yml
  .github/actions/checkout/action.yml
  .github/actions/create-dynamic-config/action.yml
  .github/actions/set-up-go/action.yml
  .github/actions/set-up-pipeline/action.yml
  .github/workflows/actionlint.yml
  .github/workflows/build-artifacts-ce.yml
  .github/workflows/build.yml
  .github/workflows/changelog-checker.yml
  .github/workflows/ci.yml
  .github/workflows/code-checker.yml
  .github/workflows/copywrite.yml
  .github/workflows/enos-lint.yml
  .github/workflows/enos-release-testing-oss.yml
  .github/workflows/oss.yml
  .github/workflows/plugin-update-check.yml
  .github/workflows/plugin-update.yml
  .github/workflows/security-scan.yml
  .github/workflows/stable-website.yaml
  .github/workflows/test-ci-bootstrap.yml
  .github/workflows/test-ci-cleanup.yml
  .github/workflows/test-enos-scenario-ui.yml
  .github/workflows/test-go.yml
  .github/workflows/test-run-acc-tests-for-path.yml
  .github/workflows/test-run-enos-scenario-containers.yml
  .github/workflows/test-run-enos-scenario-matrix.yml
  .github/workflows/test-run-enos-scenario.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29347 add docs for missing accessor flag in token renew command
  website/content/docs/commands/token/renew.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29369 Add `serial_number_source` option to PKI role
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/issuing/issue_common.go
  builtin/logical/pki/issuing/roles.go
  builtin/logical/pki/path_roles.go
  builtin/logical/pki/path_roles_test.go
  changelog/29369.txt
Labels: secret/pki

#29425 1.18 Backport: Update go/x/net and go/x/crypto to latest versions throughout
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29424 Add serialNumberSource to OpenAPI test (not added to form)
  ui/tests/helpers/openapi/expected-secret-attrs.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29429 Fix SDK net and crypto versions on main
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29428 1.18: Fix SDK versions for net and crypto
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29228 VAULT-33008: ipv6: always display RFC-5952 §4 conformant addresses
  changelog/29228.txt
  command/operator_migrate_test.go
  command/server.go
  command/server/config.go
  command/server/config_test.go
  command/server/config_test_helpers.go
  command/server/test-fixtures/config2.hcl
  command/server/test-fixtures/raft_retry_join.hcl
  command/server/test-fixtures/raft_retry_join_attr.hcl
  command/server/test-fixtures/raft_retry_join_block.hcl
  command/server/test-fixtures/raft_retry_join_mixed.hcl
  internalshared/configutil/kms.go
  internalshared/configutil/kms_test.go
  internalshared/configutil/listener.go
  internalshared/configutil/listener_test.go
  internalshared/configutil/normalize.go
  internalshared/configutil/normalize_test.go
  internalshared/configutil/telemetry.go
  internalshared/configutil/telemetry_test.go
  vault/identity_store_util.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#29432 Deleted namespace client counts is now shown when queried from admin namespace CE changes
  changelog/29432.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core.go
  vault/core_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29401 Update Rotation Manager OSS Stubs and SDK methods
  builtin/logical/aws/path_config_root.go
  builtin/logical/aws/path_config_root_test.go
  sdk/helper/automatedrotationutil/fields.go
  sdk/helper/automatedrotationutil/fields_test.go
  sdk/logical/request.go
  sdk/logical/system_view.go
  sdk/plugin/grpc_system.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/rotation/rotation_job.go
  vault/dynamic_system_view.go
  vault/rotation_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29436 Fix missing permitted_dns_domains parameter when signing certificates
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
  website/content/api-docs/secret/pki/index.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#29438 Document new serial_number_source PKI role field
  website/content/api-docs/secret/pki/index.mdx
Labels: docs, secret/pki, pr/no-changelog, hashicorp-contributed-pr

#29342 Move all pki-verification calls from sdk-Verify() to pki-specific
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/path_acme_order.go
  builtin/logical/pki/path_root.go
  changelog/29342.txt
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/certutil/cert_verification.go
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29453 Fix reference to "vault policies" command
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29455 Fix tech preview typo in export API docs
  website/content/api-docs/system/internal-counters.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29456 [DOCS] SEO updates for docs under /enterprise
  website/content/docs/enterprise/audit/exclusion.mdx
  website/content/docs/enterprise/audit/filtering.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
  website/content/docs/enterprise/automated-upgrades.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/fips/fips1402.mdx
  website/content/docs/enterprise/fips/index.mdx
  website/content/docs/enterprise/fips/sealwrap.mdx
  website/content/docs/enterprise/hsm/behavior.mdx
  website/content/docs/enterprise/hsm/index.mdx
  website/content/docs/enterprise/hsm/security.mdx
  website/content/docs/enterprise/index.mdx
  website/content/docs/enterprise/lease-count-quotas.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/enterprise/license/index.mdx
  website/content/docs/enterprise/license/manual-reporting.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/mfa/mfa-duo.mdx
  website/content/docs/enterprise/mfa/mfa-okta.mdx
  website/content/docs/enterprise/mfa/mfa-pingid.mdx
  website/content/docs/enterprise/mfa/mfa-totp.mdx
  website/content/docs/enterprise/namespaces/configure-cross-namespace-access.mdx
  website/content/docs/enterprise/namespaces/create-admin-namespace.mdx
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/docs/enterprise/namespaces/namespace-limits.mdx
  website/content/docs/enterprise/namespaces/namespace-structure.mdx
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/content/docs/enterprise/redundancy-zones.mdx
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/enterprise/sentinel/examples.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/enterprise/sentinel/properties.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29454 Backport of Fix reference to "vault policies" command into release/1.18.x
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29452 [v1.17] Fix reference to "vault policies" command
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29451 [v1.16] Fix reference to "vault policies" command
  website/content/docs/concepts/policies.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29440 update doc
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-milestone, hashicorp-contributed-pr

#29459 Fix log level of when starting a raft node
  physical/raft/raft.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29461 Add testonly endpoints for Identity testing
  vault/identity_store.go
  vault/identity_store_injector.go
  vault/identity_store_injector_testonly.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29430 UI: Fix text overflow for long Secret and Auth names
  changelog/29430.txt
  ui/app/components/dashboard/secrets-engines-card.hbs
  ui/app/styles/components/linked-block.scss
  ui/app/styles/components/search-select.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/search-select.hbs
  ui/tests/acceptance/access/methods-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/integration/components/dashboard/secrets-engines-card-test.js
  ui/tests/integration/components/search-select-test.js
Labels: ui, bug, hashicorp-contributed-pr

#29449 docs: db and ldap secrets engine known issues
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29450 docs: db and ldap secrets engine known issues
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/database-skip-static-role-rotation.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29396 Backport of VAULT-32188: Enos test for PKI certificates into release/1.18.x
  enos/enos-scenario-agent.hcl
  enos/enos-scenario-autopilot.hcl
  enos/enos-scenario-dr-replication.hcl
  enos/enos-scenario-pr-replication.hcl
  enos/enos-scenario-proxy.hcl
  enos/enos-scenario-seal-ha.hcl
  enos/enos-scenario-smoke.hcl
  enos/enos-scenario-upgrade.hcl
  enos/modules/verify_secrets_engines/modules/create/main.tf
  enos/modules/verify_secrets_engines/modules/create/pki.tf
  enos/modules/verify_secrets_engines/modules/read/main.tf
  enos/modules/verify_secrets_engines/modules/read/pki.tf
  enos/modules/verify_secrets_engines/scripts/pki-issue-certificates.sh
  enos/modules/verify_secrets_engines/scripts/pki-verify-certificates.sh
Labels: pr/no-milestone, hashicorp-contributed-pr

#29433 Backport of Deleted namespace client counts is now shown when queried from admin namespace CE changes into release/1.18.x
  changelog/29432.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core.go
  vault/core_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#29457 Extra test for vault-33413
  vault/activity_log_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29462 Backport of Extra test for vault-33413 into release/1.18.x
  vault/activity_log_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#29458 Backport of [DOCS] SEO updates for docs under /enterprise into release/1.18.x
  website/content/docs/enterprise/audit/exclusion.mdx
  website/content/docs/enterprise/audit/filtering.mdx
  website/content/docs/enterprise/automated-integrated-storage-snapshots.mdx
  website/content/docs/enterprise/automated-upgrades.mdx
  website/content/docs/enterprise/consistency.mdx
  website/content/docs/enterprise/control-groups.mdx
  website/content/docs/enterprise/entropy-augmentation.mdx
  website/content/docs/enterprise/fips/fips1402.mdx
  website/content/docs/enterprise/fips/index.mdx
  website/content/docs/enterprise/fips/sealwrap.mdx
  website/content/docs/enterprise/hsm/behavior.mdx
  website/content/docs/enterprise/hsm/index.mdx
  website/content/docs/enterprise/hsm/security.mdx
  website/content/docs/enterprise/index.mdx
  website/content/docs/enterprise/lease-count-quotas.mdx
  website/content/docs/enterprise/license/autoloading.mdx
  website/content/docs/enterprise/license/faq.mdx
  website/content/docs/enterprise/license/index.mdx
  website/content/docs/enterprise/license/manual-reporting.mdx
  website/content/docs/enterprise/license/product-usage-reporting.mdx
  website/content/docs/enterprise/license/utilization-reporting.mdx
  website/content/docs/enterprise/managed-keys.mdx
  website/content/docs/enterprise/mfa/index.mdx
  website/content/docs/enterprise/mfa/mfa-duo.mdx
  website/content/docs/enterprise/mfa/mfa-okta.mdx
  website/content/docs/enterprise/mfa/mfa-pingid.mdx
  website/content/docs/enterprise/mfa/mfa-totp.mdx
  website/content/docs/enterprise/namespaces/configure-cross-namespace-access.mdx
  website/content/docs/enterprise/namespaces/create-admin-namespace.mdx
  website/content/docs/enterprise/namespaces/index.mdx
  website/content/docs/enterprise/namespaces/namespace-limits.mdx
  website/content/docs/enterprise/namespaces/namespace-structure.mdx
  website/content/docs/enterprise/performance-standby.mdx
  website/content/docs/enterprise/pkcs11-provider/aws-xks.mdx
  website/content/docs/enterprise/pkcs11-provider/index.mdx
  website/content/docs/enterprise/pkcs11-provider/oracle-tde.mdx
  website/content/docs/enterprise/redundancy-zones.mdx
  website/content/docs/enterprise/replication/check-merkle-tree-corruption.mdx
  website/content/docs/enterprise/replication/index.mdx
  website/content/docs/enterprise/sealwrap.mdx
  website/content/docs/enterprise/sentinel/examples.mdx
  website/content/docs/enterprise/sentinel/index.mdx
  website/content/docs/enterprise/sentinel/properties.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29439 update doc
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-milestone, hashicorp-contributed-pr

#29406 Add docs for new iteration of ent operator import feature
  website/content/docs/commands/operator/import.mdx
  website/content/docs/import/awssm.mdx
  website/content/docs/import/azurekv.mdx
  website/content/docs/import/gcpsm.mdx
  website/content/docs/import/index.mdx
  website/content/docs/import/mappings.mdx
  website/content/docs/import/vault.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29423 Add GCP secret engine configuration Create/Edit views
  changelog/29423.txt
  ui/app/adapters/gcp/config.js
  ui/app/components/secret-engine/configuration-details.hbs
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/gcp/config.js
  ui/app/routes/vault/cluster/secrets/backend/configuration/edit.ts
  ui/app/templates/vault/cluster/secrets/backend/configuration/index.hbs
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/acceptance/secrets/backend/gcp/gcp-configuration-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/secret-engine/configuration-details-test.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
Labels: ui, hashicorp-contributed-pr

#29468 Backport of Add testonly endpoints for Identity testing into release/1.18.x
  vault/identity_store.go
  vault/identity_store_injector.go
  vault/identity_store_injector_testonly.go
Labels: hashicorp-contributed-pr

#29431 Backport of Prepare code base for Go 1.24 update. into release/1.18.x
  api/secret.go
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/chain_util.go
  builtin/logical/transit/path_hmac_test.go
  command/agentproxyshared/cache/cache_test.go
  command/debug_test.go
  command/operator_diagnose_test.go
  command/server/config_custom_response_headers_test.go
  helper/osutil/fileinfo_test.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/keysutil/lock_manager.go
  sdk/plugin/grpc_system.go
  vault/activity_log_test.go
  vault/core_test.go
  vault/diagnose/output.go
  vault/diagnose/tls_verification.go
  vault/diagnose/tls_verification_test.go
  vault/external_tests/metrics/core_metrics_int_test.go
  vault/login_mfa.go
  vault/token_store_test.go
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#29467 identity: Introduce ActivationFunc for managing feature state
  helper/activationflags/activation_flags.go
  sdk/framework/backend.go
  vault/core.go
  vault/identity_store.go
  vault/identity_store_conflicts.go
  vault/identity_store_structs.go
  vault/identity_store_test.go
  vault/identity_store_util.go
  vault/logical_system.go
  vault/logical_system_activation_flags.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29312 VAULT-21474 Run oidcPeriodicFunc for each namespace id store
  changelog/29312.txt
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_test.go
  website/content/docs/enterprise/namespaces/namespace-limits.mdx
Labels: hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent

#29466 Backport 1.18.x - UI: Fix text overflow for long Secret and Auth names (#29430)
  changelog/29430.txt
  ui/app/components/dashboard/secrets-engines-card.hbs
  ui/app/styles/components/linked-block.scss
  ui/app/styles/components/search-select.scss
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/search-select.hbs
  ui/tests/acceptance/access/methods-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/integration/components/dashboard/secrets-engines-card-test.js
  ui/tests/integration/components/search-select-test.js
Labels: backport, hashicorp-contributed-pr

#29339 Suggested edits for identity doc updates
  website/content/docs/upgrading/deduplication/acl-policy-templates.mdx
  website/content/docs/upgrading/deduplication/different-case.mdx
  website/content/docs/upgrading/deduplication/entity-group.mdx
  website/content/docs/upgrading/deduplication/index.mdx
  website/content/docs/upgrading/deduplication/terraform-refs.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29469 UI: Adds `serial_number_source` to pki role form
  ui/app/models/pki/role.js
  ui/tests/integration/components/pki/pki-role-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29464 added the 1.18.4, 1.17.11, and 1.16.15 changelog entries
  CHANGELOG.md
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29470 CE changes for VAULT-33018
  changelog/29470.txt
  http/handler.go
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
Labels: hashicorp-contributed-pr

#29403 VAULT-33074: add `github` sub-command to `pipeline`
  .gitignore
  tools/pipeline/go.mod
  tools/pipeline/go.sum
  tools/pipeline/internal/cmd/github.go
  tools/pipeline/internal/cmd/github_list_runs.go
  tools/pipeline/internal/cmd/root.go
  tools/pipeline/internal/pkg/generate/enos_dynamic_config_test.go
  tools/pipeline/internal/pkg/github/list_workflow_runs.go
  tools/pipeline/internal/pkg/github/list_workflow_runs_test.go
  tools/pipeline/internal/pkg/github/log_scanner.go
  tools/pipeline/internal/pkg/github/log_scanner_test.go
  tools/pipeline/internal/pkg/github/testfixtures/list_workflow_runs.json
  tools/pipeline/internal/pkg/github/workflow_run_summary.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent
