Repository hashicorp/vault, pull requests merged in 2025-03, with the labels that each got.

#29792 Update Azure wrapper to address VAULT-29717
  changelog/29792.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29800 Backport of Update Azure wrapper to address VAULT-29717 into release/1.19.x
  changelog/29792.txt
  go.mod
  go.sum
Labels: backport, pr/no-milestone, hashicorp-contributed-pr

#29799 Backport of Update Azure wrapper to address VAULT-29717 into release/1.18.x
  go.mod
  go.sum
Labels: backport, pr/no-milestone, hashicorp-contributed-pr

#29683 Backport of database: fix reload to not fail early into release/1.19.x
  builtin/logical/database/path_config_connection.go
  changelog/29519.txt
  vault/external_tests/plugin/external_plugin_test.go
Labels: hashicorp-contributed-pr

#29682 Backport of database: fix reload to not fail early into release/1.18.x
  builtin/logical/database/path_config_connection.go
  changelog/29519.txt
  vault/external_tests/plugin/external_plugin_test.go
Labels: hashicorp-contributed-pr

#29788 Add known issue for Azure credential failure
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/azure-unseal-regression.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29807 Backport of Add known issue for Azure credential failure into release/1.19.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/azure-unseal-regression.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29806 Backport of Add known issue for Azure credential failure into release/1.18.x
  website/content/docs/release-notes/1.16.1.mdx
  website/content/docs/release-notes/1.17.0.mdx
  website/content/docs/release-notes/1.18.0.mdx
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
  website/content/partials/known-issues/azure-unseal-regression.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29754 UI: Glimmerize database/role.js and add model validations
  changelog/29754.txt
  ui/app/components/database-role-edit.js
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/database-role-setting-form.hbs
  ui/tests/integration/components/database-role-edit-test.js
Labels: ui, hashicorp-contributed-pr

#29802 Docs - Fix broken link on "tokens" page
  website/content/docs/concepts/tokens.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29791 Update vault operator usage and telemetry metrics docs
  website/content/docs/commands/operator/usage.mdx
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/docs/internals/telemetry/metrics/authn.mdx
  website/content/partials/telemetry-metrics/vault/identity/nonentity/active/monthly.mdx
  website/content/partials/telemetry-metrics/vault/identity/nonentity/active/reporting_period.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29213 update eventing doc
  website/content/docs/concepts/events.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29782 Add docs for GCP automated root rotation
  website/content/api-docs/auth/gcp.mdx
  website/content/api-docs/secret/gcp.mdx
  website/content/docs/auth/aws.mdx
  website/content/docs/auth/gcp.mdx
  website/content/docs/auth/ldap.mdx
  website/content/docs/secrets/aws.mdx
  website/content/docs/secrets/gcp.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29748 sync/gcp: document CMEK and CloudResourceManager API requirement
  website/content/docs/sync/gcpsm.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29749 sync: document new allowlist fields and disable field for SSRF-strict networking
  website/content/api-docs/system/activation-flags.mdx
  website/content/api-docs/system/secrets-sync.mdx
  website/content/docs/sync/azurekv.mdx
  website/content/docs/sync/index.mdx
  website/content/partials/sync-ssrf-fields.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29821 Fix small typo/anchor link in GCP sync API docs section
  website/content/api-docs/system/secrets-sync.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29818 Backport of sync/gcp: document CMEK and CloudResourceManager API requirement into release/1.19.x
  website/content/docs/sync/gcpsm.mdx
Labels: hashicorp-contributed-pr

#29819 Backport of sync: document new allowlist fields and disable field for SSRF-strict networking into release/1.19.x
  website/content/api-docs/system/activation-flags.mdx
  website/content/api-docs/system/secrets-sync.mdx
  website/content/docs/sync/azurekv.mdx
  website/content/docs/sync/index.mdx
  website/content/partials/sync-ssrf-fields.mdx
Labels: hashicorp-contributed-pr

#29824 Backport of Fix small typo/anchor link in GCP sync API docs section into release/1.19.x
  website/content/api-docs/system/secrets-sync.mdx
Labels: hashicorp-contributed-pr

#29809 Backport of VAULT-191: Validate X-Forwarded-For IP into release/1.19.x
  changelog/29774.txt
  http/forwarded_for_test.go
  http/handler.go
Labels: hashicorp-contributed-pr

#29808 Backport of VAULT-191: Validate X-Forwarded-For IP into release/1.18.x
  changelog/29774.txt
  http/forwarded_for_test.go
  http/handler.go
Labels: hashicorp-contributed-pr

#29823 Update VSO docs for v0.10.0
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29827 Backport of Update VSO docs for v0.10.0 into release/1.19.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29826 Backport of Update VSO docs for v0.10.0 into release/1.18.x
  website/content/docs/platform/k8s/vso/api-reference.mdx
  website/content/docs/platform/k8s/vso/helm.mdx
  website/content/docs/platform/k8s/vso/installation.mdx
  website/content/docs/platform/k8s/vso/openshift.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29828 [Enos] Update descriptions for dev scenarios
  enos/enos-dev-scenario-pr-replication.hcl
  enos/enos-dev-scenario-single-cluster.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29679 Backport of VAULT-33601: fixing enos vault-radar failure into release/1.18.x
  enos/enos-scenario-seal-ha.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29829 Backport of [Enos] Update descriptions for dev scenarios into release/1.18.x
  enos/enos-dev-scenario-pr-replication.hcl
  enos/enos-dev-scenario-single-cluster.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29833 Backport 1.19.x 🥐Transform-edit-base: remove use in transform-template-edit and alphabet-edit (#29803)
  ui/app/components/alphabet-edit.hbs
  ui/app/components/alphabet-edit.js
  ui/app/components/transform-template-edit.hbs
  ui/app/components/transform-template-edit.js
  ui/app/models/transform/alphabet.js
  ui/app/models/transform/template.js
Labels: ui, backport, hashicorp-contributed-pr

#29837 VAULT-34477: Add s390x multilib compiler to build-vault action
  .github/actions/build-vault/action.yml
  scripts/ci-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29835 1.19 Release notes
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29839 Backport of 1.19 Release notes into release/1.19.x
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29838 Backport of VAULT-34477: Add s390x multilib compiler to build-vault action into release/1.19.x
  .github/actions/build-vault/action.yml
  scripts/ci-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29836 identity: fix a racy deduplication test assertion
  vault/identity_store_test.go
  vault/identity_store_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29840 Backport of identity: fix a racy deduplication test assertion into release/1.19.x
  vault/identity_store_test.go
  vault/identity_store_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29834 [Chore] - Remove unneeded string extensions
  changelog/29834.txt
  ui/ember-cli-build.js
  ui/package.json
  ui/vendor/.gitkeep
  ui/vendor/string-includes.js
  ui/yarn.lock
Labels: ui, hashicorp-contributed-pr, backport/1.19.x

#29845 Changelog for 1.19.0, 1.18.6, 1.17.13, and 1.16.17
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29814 Backport of Update vault operator usage and telemetry metrics docs into release/1.19.x
  website/content/docs/commands/operator/usage.mdx
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/docs/internals/telemetry/metrics/authn.mdx
  website/content/partials/telemetry-metrics/vault/identity/nonentity/active/monthly.mdx
  website/content/partials/telemetry-metrics/vault/identity/nonentity/active/reporting_period.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29846 (DOCS) VAULT-31525 Added note for case sensitivity changes in the RADIUS auth plugin
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29848 Backport of Fix anchor text in LDAP release note heading into release/1.19.x
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29850 Docs/cherrypick 29846
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29844 Backport of [Chore] - Remove unneeded string extensions into release/1.19.x
  changelog/29834.txt
  ui/ember-cli-build.js
  ui/package.json
  ui/vendor/.gitkeep
  ui/vendor/string-includes.js
  ui/yarn.lock
Labels: ui, backport, hashicorp-contributed-pr

#29849 VAULT-34126 CE part
  api/sys_utilization_report.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29365 Update add-a-containerized-plugin.mdx
  website/content/docs/plugins/containerized-plugins/add-a-containerized-plugin.mdx
Labels: docs, core/plugin, docker, pr/no-changelog, pr/no-milestone

#29853 Backport of Update add-a-containerized-plugin.mdx into release/1.19.x
  website/content/docs/plugins/containerized-plugins/add-a-containerized-plugin.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29852 Fix bug when writing auto tidy config field tidy_cmpv2_nonce_store
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  changelog/29852.txt
Labels: hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29855 Backport of Fix bug when writing auto tidy config field tidy_cmpv2_nonce_store into release/1.19.x
  builtin/logical/pki/path_tidy.go
  builtin/logical/pki/path_tidy_test.go
  changelog/29852.txt
Labels: hashicorp-contributed-pr

#29854 Backport 1.19.x: bump test-watiers and reinstall yarn lock
  ui/package.json
  ui/yarn.lock
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#29568 Persist automatic entity merges
  helper/storagepacker/storagepacker.go
  helper/storagepacker/storagepacker_test.go
  vault/external_tests/identity/identity_test.go
  vault/identity_store.go
  vault/identity_store_conflicts.go
  vault/identity_store_entities.go
  vault/identity_store_injector_testonly.go
  vault/identity_store_oidc_test.go
  vault/identity_store_test.go
  vault/identity_store_test_stubs_oss.go
  vault/identity_store_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29856 docs: enable aws secrets engine, not gcp
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.18.x, backport/1.19.x

#29859 Backport of docs: enable aws secrets engine, not gcp into release/1.19.x
  website/content/docs/secrets/aws.mdx
Labels: hashicorp-contributed-pr

#29857 Backport of Persist automatic entity merges into release/1.19.x
  helper/storagepacker/storagepacker.go
  helper/storagepacker/storagepacker_test.go
  vault/external_tests/identity/identity_test.go
  vault/identity_store.go
  vault/identity_store_conflicts.go
  vault/identity_store_entities.go
  vault/identity_store_injector_testonly.go
  vault/identity_store_oidc_test.go
  vault/identity_store_test.go
  vault/identity_store_test_stubs_oss.go
  vault/identity_store_util.go
Labels: hashicorp-contributed-pr

#29860 Add missing CL for GH-29792
  CHANGELOG.md
Labels: hashicorp-contributed-pr

#29678 docs: add details on plugin downgrades
  website/content/docs/concepts/events.mdx
  website/content/docs/upgrading/plugins.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29805 UI: Refactor to newer patterns
  ui/app/adapters/totp-key.js
  ui/app/components/generate-credentials-totp.hbs
  ui/app/components/generate-credentials-totp.js
  ui/app/components/secret-list/totp-list-item.hbs
  ui/app/components/secret-list/totp-list-item.js
  ui/app/components/totp-edit.hbs
  ui/app/components/totp-edit.js
  ui/app/components/totp/key-create-toggle-groups.hbs
  ui/app/components/totp/key-create-toggle-groups.js
  ui/app/components/totp/key-create.hbs
  ui/app/components/totp/key-details.hbs
  ui/app/components/totp/key-qr-code.hbs
  ui/app/helpers/mountable-secret-engines.js
  ui/app/models/totp-key.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/totp-key.js
  ui/app/templates/components/totp-edit.hbs
  ui/app/templates/vault/cluster/secrets/backend/credentials.hbs
Labels: ui, hashicorp-contributed-pr

#29874 VAULT-34581: retry_join: handle escapes in `auto_join` config
  command/server/config.go
  command/server/config_test_helpers.go
  command/server/test-fixtures/raft_retry_join_attr.hcl
  command/server/test-fixtures/raft_retry_join_block.hcl
  command/server/test-fixtures/raft_retry_join_mixed.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29876 Backport of VAULT-34581: retry_join: handle escapes in `auto_join` config into release/1.19.x
  command/server/config.go
  command/server/config_test_helpers.go
  command/server/test-fixtures/raft_retry_join_attr.hcl
  command/server/test-fixtures/raft_retry_join_block.hcl
  command/server/test-fixtures/raft_retry_join_mixed.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29865 Backport of docs: add details on plugin downgrades into release/1.19.x
  website/content/docs/concepts/events.mdx
  website/content/docs/upgrading/plugins.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29868 Update 1.19 release notes
  website/content/docs/deprecation/index.mdx
  website/content/docs/release-notes/1.19.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29878 Backport of Update 1.19 release notes into release/1.19.x
  website/content/docs/deprecation/index.mdx
  website/content/docs/release-notes/1.19.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29879 [DOCS] Add missing links
  website/content/docs/release-notes/1.19.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29882 Backport of [DOCS] Fix release notes spacing into release/1.19.x
  website/content/docs/release-notes/1.19.0.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29815 Backport of update eventing doc into release/1.18.x
  website/content/docs/concepts/events.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29816 Backport of update eventing doc into release/1.19.x
  website/content/docs/concepts/events.mdx
Labels: hashicorp-contributed-pr

#29649 Updating docs to include new assume role fields
  website/content/api-docs/secret/aws.mdx
  website/content/docs/secrets/aws.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29888 Backport of Updating docs to include new assume role fields into release/1.19.x
  website/content/api-docs/secret/aws.mdx
  website/content/docs/secrets/aws.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29894 Fix reported typos
  website/content/api-docs/system/mounts.mdx
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29895 Backport of Fix reported typos into release/1.18.x
  website/content/api-docs/system/mounts.mdx
  website/content/docs/commands/secrets/enable.mdx
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29889 VAULT-34593 CE changes
  vault/core_metrics.go
  vault/mount.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29897 Backport of VAULT-34593 CE changes into release/1.19.x
  vault/core_metrics.go
  vault/mount.go
Labels: hashicorp-contributed-pr

#29546 feat(api-client): add cert auth method
  api/auth/cert/cert.go
  api/auth/cert/cert_test.go
  api/auth/cert/go.mod
  api/auth/cert/go.sum
  changelog/29546.txt
Labels: enhancement

#29902 [VAULT-34473] Update vault-hcp-lib dependency
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29418 Add web engineering to the CODEOWNERS file for website tooling, but not content.
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29906 Backport of Add web engineering to the CODEOWNERS file for website tooling, but not content. into release/1.18.x
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29904 Backport of [VAULT-34473] Update vault-hcp-lib dependency into release/1.19.x
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#29820 UI: Add Skip password rotation field on DB connection creation
  changelog/29820.txt
  ui/app/components/database-role-edit.js
  ui/app/components/database-role-setting-form.js
  ui/app/models/database/connection.js
  ui/app/models/database/role.js
  ui/app/templates/components/database-role-edit.hbs
  ui/app/templates/components/database-role-setting-form.hbs
  ui/app/utils/model-helpers/database-helpers.js
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/database/workflow-test.js
  ui/tests/integration/components/database-role-edit-test.js
  ui/tests/integration/components/database-role-setting-form-test.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/pages/components/form-field.js
  ui/tests/unit/serializers/database/connection-test.js
Labels: ui, hashicorp-contributed-pr

#29905 Update vault-hcp-lib dependency
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#29842 Add LIST endpoint to AWS Secrets static roles
  builtin/logical/aws/backend.go
  builtin/logical/aws/path_static_roles.go
  builtin/logical/aws/path_static_roles_test.go
  changelog/29842.txt
  website/content/api-docs/secret/aws.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#29911 SECVULN-18432: Default to Encrypted Root Volumes
  enos/modules/target_ec2_instances/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29912 Backport of SECVULN-18432: Default to Encrypted Root Volumes into release/1.19.x
  enos/modules/target_ec2_instances/main.tf
Labels: pr/no-milestone, hashicorp-contributed-pr

#29917 Ensure logger writes to log_file by preventing overwrite of InterceptLogger's output
  changelog/29917.txt
  command/server.go
Labels: hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29919 Backport of Ensure logger writes to log_file by preventing overwrite of InterceptLogger's output into release/1.19.x
  changelog/29917.txt
  command/server.go
Labels: hashicorp-contributed-pr

#29918 Backport of Ensure logger writes to log_file by preventing overwrite of InterceptLogger's output into release/1.18.x
  changelog/29917.txt
  command/server.go
Labels: hashicorp-contributed-pr

#29923 [DOCS] Make AD secrets plugin EOL
  website/content/api-docs/secret/ad.mdx
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/secrets/ad/index.mdx
  website/content/docs/secrets/ad/migration-guide.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/ad-secrets-deprecation.mdx
  website/content/partials/deprecation/active-directory-secrets-engine.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29924 Backport of [DOCS] Make AD secrets plugin EOL into release/1.19.x
  website/content/api-docs/secret/ad.mdx
  website/content/docs/platform/servicenow/configuration.mdx
  website/content/docs/release-notes/1.19.0.mdx
  website/content/docs/secrets/ad/index.mdx
  website/content/docs/secrets/ad/migration-guide.mdx
  website/content/docs/upgrading/upgrade-to-1.19.x.mdx
  website/content/partials/ad-secrets-deprecation.mdx
  website/content/partials/deprecation/active-directory-secrets-engine.mdx
  website/data/api-docs-nav-data.json
  website/data/docs-nav-data.json
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29926 Backport 1.19: Update golang.org/x/net to v0.37.0 for GO-2025-3503
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  tools/pipeline/go.mod
  tools/pipeline/go.sum
  vault/hcp_link/proto/go.mod
  vault/hcp_link/proto/go.sum
Labels: backport, dependencies, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29922 check for case sensitivity at delete for user and group paths, modify…
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_groups.go
  builtin/credential/ldap/path_users.go
  changelog/29922.txt
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29929 Backport of check for case sensitivity at delete for user and group paths, modify… into release/1.19.x
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_groups.go
  builtin/credential/ldap/path_users.go
  changelog/29922.txt
Labels: backport, pr/no-milestone, hashicorp-contributed-pr

#29927 [UI] Resolve ember-cli-typescript to 5.3.0
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29930 [VAULT-34699] UI: Remove `FormError` component (not used)
  changelog/34699.txt
  ui/lib/core/addon/components/form-error.hbs
  ui/lib/core/app/components/form-error.js
  ui/tests/integration/components/form-error-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29931 Rework certificate authentication client api
  CODEOWNERS
  api/auth/cert/cert.go
  api/auth/cert/cert_test.go
  api/auth/cert/go.mod
  api/auth/cert/go.sum
Labels: pr/no-changelog, clientapi, hashicorp-contributed-pr

#29909 Fix double-rename bug and locking issues
  vault/identity_store_injector_testonly.go
  vault/identity_store_test.go
  vault/identity_store_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29937 Bump @babel/core to 7.26.10 in devDependency AND dependency
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29942 Backport 1.19.x: Manual backport of bump babel/core
  ui/package.json
  ui/yarn.lock
Labels: ui, backport, hashicorp-contributed-pr

#29953 backport VAULT-34555 fix seal_ha failure to release/1.19.x
  enos/enos-scenario-seal-ha.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29920 VAULT-34541 CE changes
  api/sys_utilization_report.go
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29944 [VAULT-34728] UI: prepare `FormField` template logic for migration to HDS components
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#29958 [VAULT-34792] UI: refactor `FormField` template code to move `checkboxList` under the newly added HDS block
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#29945 [UI] Local Testing Workaround
  ui/package.json
  ui/scripts/start-vault.js
  ui/testem.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29961 set GOPRIVATE in plugin-update gha ent step
  .github/workflows/plugin-update.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29946 [VAULT-34704] UI: update `FilterInput` component to use `Hds::Form::TextInput`
  ui/lib/core/addon/components/filter-input.hbs
  ui/lib/core/addon/components/filter-input.ts
  ui/lib/core/addon/components/kv-suggestion-input.hbs
  ui/lib/ldap/addon/components/page/libraries.hbs
  ui/lib/ldap/addon/components/page/roles.hbs
  ui/lib/sync/addon/components/secrets/page/destinations.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
  ui/tests/integration/components/filter-input-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#29964 [enos] SECVULN-18910: Enforce IMDSv2 on AWS instances
  enos/modules/target_ec2_instances/main.tf
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29966 Backport of [enos] SECVULN-18910: Enforce IMDSv2 on AWS instances into release/1.19.x
  enos/modules/target_ec2_instances/main.tf
Labels: pr/no-milestone, hashicorp-contributed-pr

#29970 Update vault-plugin-secrets-gcp to v0.21.2
  changelog/29970.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29972 Backport of Update vault-plugin-secrets-gcp to v0.21.2 into release/1.19.x
  changelog/29970.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29978 bugfix: vault register should respect tmpdir
  changelog/29978.txt
  vault/plugincatalog/plugin_catalog_stubs_oss.go
Labels: hashicorp-contributed-pr

#29979 enos(install_packages): handle cloud-init exit code 2 and subshells
  enos/modules/install_packages/scripts/synchronize-repos.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29981 Backport of enos(install_packages): handle cloud-init exit code 2 and subshells into release/1.19.x
  enos/modules/install_packages/scripts/synchronize-repos.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29965 [UI] API Service
  ui/app/config/environment.d.ts
  ui/app/lib/local-storage.ts
  ui/app/lib/memory-storage.ts
  ui/app/services/api.ts
  ui/tests/unit/services/api-test.js
  ui/types/vault/api.d.ts
  ui/types/vault/services/auth.d.ts
  ui/types/vault/services/control-group.d.ts
  ui/types/vault/services/namespace.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29984 [UI] Lint Ignore API Client
  ui/.eslintignore
  ui/.prettierignore
  ui/tsconfig.json
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29960 [VAULT-34742] UI: move the generic `select` block in `FormField` under the HDS block
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#29976 [VAULT-29278] Update hashicorp/raft library from v1.7.1 to v1.7.3 to add logging on leader node when opening and sending a raft snapshot to a follower
  changelog/29976.txt
  go.mod
  go.sum
Labels: storage/raft, dependencies, hashicorp-contributed-pr

#29975 Backport of Document the identity census metrics into release/1.19.x
  website/content/docs/enterprise/license/product-usage-reporting.mdx
Labels: hashicorp-contributed-pr

#29962 [VAULT-34729] UI: move the `password` block in `FormField` under the HDS block
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#29983 WIP: Route for vault usage dashboard
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/router.js
  ui/app/templates/vault/cluster/vault-usage.hbs
Labels: hashicorp-contributed-pr

#30004 go: resolve GHSA-mh63-6h87-95cp by bumping github.com/golang-jwt/jwt/v*
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#29994 [UI] Ember Data Migration - Tools Wrap Component
  ui/app/components/tools/wrap.ts
  ui/app/utils/api-error-message.ts
  ui/app/utils/error-message.js
  ui/package.json
  ui/tests/integration/components/tools/wrap-test.js
  ui/tests/unit/utils/api-error-message-test.js
  ui/types/vault/api.d.ts
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30005 Backport of go: resolve GHSA-mh63-6h87-95cp by bumping github.com/golang-jwt/jwt/v* into release/1.19.x
  go.mod
  go.sum
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30006 [UI] Ember Data Migration - Tools Rewrap Component
  ui/app/components/tools/rewrap.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30009 Bump go-git version
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr

#30000 UI: Updates the namespace service to explicitly check for the HVD managed admin namespace
  ui/app/components/dashboard/overview.ts
  ui/app/services/namespace.js
  ui/tests/integration/components/dashboard/overview-test.js
  ui/types/vault/services/namespace.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29993 Add known issue for sts region/sts endpoint mismatch bug
  website/content/partials/known-issues/aws-fallback-sts.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30013 enos(cloud-init): fix synchronize-repos
  enos/modules/install_packages/scripts/synchronize-repos.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30015 Backport of enos(cloud-init): fix synchronize-repos into release/1.19.x
  enos/modules/install_packages/scripts/synchronize-repos.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30003 usage (CE): Fix data race on IdentityStore metric
  vault/identity_store.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30016 Backport of usage (CE): Fix data race on IdentityStore metric into release/1.19.x
  vault/identity_store.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29921 docs: Update Seal/Unseal concept topic
  website/content/docs/concepts/seal.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30020 Backport of docs: Update Seal/Unseal concept topic into release/1.19.x
  website/content/docs/concepts/seal.mdx
Labels: hashicorp-contributed-pr

#30017 Pin CI tool versions 1.19.x (#29665)
  .github/actions/install-external-tools/action.yml
  .github/actions/set-up-buf/action.yml
  .github/actions/set-up-gofumpt/action.yml
  .github/actions/set-up-gosimports/action.yml
  .github/actions/set-up-gotestsum/action.yml
  .github/actions/set-up-misspell/action.yml
  .github/actions/set-up-shfmt/action.yml
  .github/actions/set-up-sqlc/action.yml
  .github/actions/set-up-staticcheck/action.yml
  sdk/go.mod
  sdk/go.sum
  tools/tools.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30011 Backport of UI: Updates the namespace service to explicitly check for the HVD managed admin namespace into release/1.19.x
  ui/app/components/dashboard/overview.ts
  ui/app/services/namespace.js
  ui/tests/integration/components/dashboard/overview-test.js
  ui/types/vault/services/namespace.d.ts
Labels: backport, hashicorp-contributed-pr

#30001 UI: Separate flag and version service concerns
  ui/app/components/clients/page/counts.hbs
  ui/app/components/sidebar/nav/cluster.hbs
  ui/app/components/sidebar/nav/cluster.js
  ui/app/services/flags.ts
  ui/app/services/version.js
  ui/lib/sync/addon/components/secrets/page/overview.hbs
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/components/secrets/sync-activation-modal.ts
  ui/lib/sync/addon/routes/secrets/overview.ts
  ui/lib/sync/addon/templates/secrets/overview.hbs
  ui/tests/acceptance/sync/secrets/overview-test.js
  ui/tests/helpers/components/sidebar-nav.js
  ui/tests/integration/components/sidebar/nav/cluster-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
  ui/tests/integration/components/sync/secrets/sync-activation-modal-test.js
  ui/tests/unit/services/flags-test.js
  ui/tests/unit/services/version-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29982 secrets/aws: disable environment and shared credential providers when using WIF
  builtin/logical/aws/client.go
  changelog/29982.txt
Labels: hashicorp-contributed-pr

#30023 Backport of secrets/aws: disable environment and shared credential providers when using WIF into release/1.19.x
  builtin/logical/aws/client.go
  changelog/29982.txt
Labels: hashicorp-contributed-pr

#30012 Backport: Bump go-git version
  go.mod
  go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr

#30021 Backport of Add known issue for sts region/sts endpoint mismatch bug into release/1.19.x
  website/content/partials/known-issues/aws-fallback-sts.mdx
Labels: pr/no-milestone, hashicorp-contributed-pr

#30014 [UI] Ember Data Migration - Tools Lookup Component
  ui/app/components/tools/lookup.hbs
  ui/app/components/tools/lookup.js
  ui/app/components/tools/lookup.ts
  ui/tests/integration/components/tools/lookup-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30019 [UI] Ember Data Migration - Tools Random Component
  ui/app/components/tools/random.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30022 [UI] Ember Data Migration - Tools Unwrap Component
  ui/api-client/dist/esm/runtime.d.ts
  ui/api-client/dist/esm/runtime.js
  ui/api-client/dist/runtime.d.ts
  ui/api-client/dist/runtime.js
  ui/api-client/src/runtime.ts
  ui/app/components/tools/unwrap.ts
  ui/app/services/api.ts
  ui/tests/unit/services/api-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30024 [DOCS] Update the callout note for accuracy
  website/content/docs/sync/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30027 Backport of [DOCS] Update the callout note for accuracy into release/1.19.x
  website/content/docs/sync/index.mdx
Labels: hashicorp-contributed-pr

#29935 docs/k8s: update supported k8s versions for 1.18
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29932 docs/k8s: update supported k8s versions
  website/content/partials/kubernetes-supported-versions.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30028 Backport of docs/k8s: update supported k8s versions into release/1.19.x
  website/content/partials/kubernetes-supported-versions.mdx
Labels: hashicorp-contributed-pr

#29969 add docs for Azure auth resource_group_name, vm_name, vmss_name security improvement
  website/content/docs/auth/azure.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30036 Backport of add docs for Azure auth resource_group_name, vm_name, vmss_name security improvement into release/1.19.x
  website/content/docs/auth/azure.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30030 [UI] Ember Data Migration - Remove Tools Adapter
  ui/app/adapters/tools.js
  ui/app/components/auth-form.js
  ui/app/components/control-group-success.js
  ui/tests/integration/components/auth/page-test.js
  ui/tests/integration/components/control-group-success-test.js
  ui/tests/unit/adapters/tools-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30037 Update vault-plugin-secrets-azure to v0.21.2
  changelog/30037.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#30002 raftha: Fix flake in removed peer re-add test
  vault/external_tests/raftha/raft_ha_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30045 Backport of raftha: Fix flake in removed peer re-add test into release/1.19.x
  vault/external_tests/raftha/raft_ha_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30046 UI: Remove slash from check for admin namespace path
  ui/app/services/namespace.js
  ui/tests/integration/components/dashboard/overview-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30047 Backport of UI: Remove slash from check for admin namespace path into release/1.19.x
  ui/app/services/namespace.js
  ui/tests/integration/components/dashboard/overview-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr
