Repository hashicorp/vault, pull requests merged in 2025-05, with the labels that each got.

#30471 Replace summary in important changes section
  website/content/docs/updates/important-changes.mdx
  website/content/docs/updates/release-notes.mdx
  website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
  website/content/partials/known-issues/database-static-role-premature-rotations.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30473 [backport 1.19.x]: update versions, and replace summary in important changes section
  website/content/docs/updates/important-changes.mdx
  website/content/docs/updates/release-notes.mdx
  website/content/partials/known-issues/1_19-failures-after-external-group-changes-standby.mdx
  website/content/partials/known-issues/database-static-role-premature-rotations.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: hashicorp-contributed-pr

#30474 [backport 1.18.x]: update versions, and replace summary in important changes section
  website/content/partials/known-issues/database-static-role-premature-rotations.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30476 [backport 1.16.x]: update versions, and replace summary in important changes section
  website/content/partials/known-issues/database-static-role-premature-rotations.mdx
  website/content/partials/known-issues/log_file_flush_issue.mdx
  website/content/partials/known-issues/static-role-premature-rotations.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30456 Update CHANGELOG.md
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30349 UI: Update Enterprise Client Count Datepicker
  changelog/30349.txt
  ui/app/components/clients/date-range.hbs
  ui/app/components/clients/date-range.ts
  ui/app/components/clients/page-header.hbs
  ui/app/components/clients/page-header.js
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/styles/helper-classes/flexbox-and-grid.scss
  ui/tests/acceptance/clients/counts-test.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/helpers/clients/client-count-selectors.ts
  ui/tests/integration/components/clients/date-range-test.js
  ui/tests/integration/components/clients/page/counts-test.js
Labels: ui, hashicorp-contributed-pr, backport/1.19.x, backport/ent/1.18.x+ent

#30465 UI: Move `wrapped_token` login functionality to route
  ui/app/components/auth-form.js
  ui/app/components/auth/login-form.hbs
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/app/components/mfa/mfa-form.js
  ui/app/controllers/vault.js
  ui/app/controllers/vault/cluster.js
  ui/app/controllers/vault/cluster/auth.js
  ui/app/routes/vault/cluster/auth.js
  ui/app/templates/components/mfa/mfa-form.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/mfa-login-test.js
  ui/tests/acceptance/wrapped-token-test.js
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth/form/oidc-jwt-test.js
  ui/tests/integration/components/auth/login-form-test.js
  ui/tests/integration/components/mfa-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30329 Prevent early-exit of plugin reload
  changelog/30329.txt
  vault/plugin_reload.go
  vault/plugin_reload_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#30482 changelog: sync changelog with main (1.17)
  CHANGELOG-v1.10-v1.15.md
  CHANGELOG.md
Labels: pr/no-milestone, hashicorp-contributed-pr

#30481 changelog: sync changelog with main (1.18)
  CHANGELOG-v1.10-v1.15.md
  CHANGELOG.md
Labels: pr/no-milestone, hashicorp-contributed-pr

#30483 changelog: sync changelog with main (1.16)
  CHANGELOG-v1.10-v1.15.md
  CHANGELOG.md
Labels: pr/no-milestone, hashicorp-contributed-pr

#30484 Backport of [UI] Local Testing Workaround into release/1.19.x
  ui/package.json
  ui/scripts/start-vault.js
  ui/testem.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30485 [DOCS] Add missing redirect
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30459 UI: Adding List view component for custom login settings
  ui/app/app.js
  ui/app/components/sidebar/nav/cluster.hbs
  ui/lib/config-ui/addon/components/login-settings/page/list.hbs
  ui/lib/config-ui/addon/components/login-settings/page/list.js
  ui/lib/config-ui/addon/engine.js
  ui/lib/config-ui/addon/routes/login-settings/index.js
  ui/lib/config-ui/addon/templates/login-settings/index.hbs
  ui/tests/integration/components/sidebar/nav/cluster-test.js
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30462 Backport 1.19.x: pin dependencies and resolutions, remove ^ for ~ for devDependencies
  ui/package.json
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/yarn.lock
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#30468 [VAULT-35780] address TODOs
  ui/app/components/namespace-picker.hbs
  ui/app/components/namespace-picker.ts
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/helpers/commands.js
  ui/tests/helpers/namespace-picker.js
  ui/tests/integration/components/namespace-picker-test.js
Labels: hashicorp-contributed-pr

#30487 Backport of [DOCS] Add missing redirect into release/1.19.x
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30294 VAULT-35498: fix typo in secrets sync docs
  website/content/docs/sync/index.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30489 UI: Add MFA support for SSO methods
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/form/base.ts
  ui/app/components/auth/form/oidc-jwt.ts
  ui/app/components/auth/form/okta.ts
  ui/app/components/auth/form/saml.ts
  ui/app/components/auth/login-form.js
  ui/app/components/auth/page.js
  ui/app/services/auth.js
  ui/tests/acceptance/wrapped-token-test.js
  ui/tests/integration/components/auth/form/saml-test.js
  ui/tests/integration/components/auth/login-form-test.js
  ui/types/vault/adapters/auth-method.d.ts
  ui/types/vault/api.d.ts
  ui/types/vault/auth/methods.d.ts
  ui/types/vault/auth/mfa.d.ts
  ui/types/vault/services/auth.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30492 Move CSP error to page component
  ui/app/components/auth-form.js
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/app/templates/components/auth-form.hbs
  ui/tests/integration/components/auth/login-form-test.js
  ui/tests/integration/components/auth/page-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30501 UI: fix doc links for postgres plugin type
  ui/app/models/database/connection.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30504 UI: Update remaining copyright headers
  ui/app/components/auth/fields.hbs
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/form/base.hbs
  ui/app/components/auth/form/oidc-jwt.hbs
  ui/app/components/auth/form/okta.hbs
  ui/app/components/auth/form/saml.hbs
  ui/app/components/auth/namespace-input.hbs
  ui/app/components/auth/tabs.hbs
  ui/app/components/generate-credentials-totp.hbs
  ui/app/components/secret-list/totp-list-item.hbs
  ui/app/components/totp-edit.hbs
  ui/app/components/totp/key-create-toggle-groups.hbs
  ui/app/components/totp/key-create.hbs
  ui/app/components/totp/key-details.hbs
  ui/app/components/totp/key-qr-code.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30508 Backport of [DOCS] Add more missing redirect into release/1.19.x
  website/redirects.js
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30496 VAULT-35396 CE changes
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  http/sys_config_state_test.go
  vault/core.go
  vault/expiration.go
  vault/observations/observations_ce.go
  vault/observations/observations_consts.go
  vault/testing.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30513 Backport 30497 to 1.16.x
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30514 backport 30497 to 1.18.x
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30509 Move fetching unauthenticated mounts to the route
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/form/base.hbs
  ui/app/components/auth/form/base.ts
  ui/app/components/auth/form/oidc-jwt.hbs
  ui/app/components/auth/form/okta.hbs
  ui/app/components/auth/form/saml.hbs
  ui/app/components/auth/namespace-input.hbs
  ui/app/components/auth/page.js
  ui/app/components/auth/tabs.hbs
  ui/app/components/auth/tabs.ts
  ui/app/routes/vault/cluster/auth.js
  ui/app/templates/vault/cluster/auth.hbs
  ui/app/utils/supported-login-methods.ts
  ui/tests/acceptance/oidc-provider-test.js
  ui/tests/acceptance/wrapped-token-test.js
  ui/tests/integration/components/auth/form-template-test.js
  ui/types/vault/auth/form.d.ts
  ui/types/vault/services/auth.d.ts
Labels: pr/no-changelog, hashicorp-contributed-pr

#30493 Replace e.keyCode with e.key
  changelog/30493.txt
  ui/app/components/console/command-input.js
  ui/app/components/console/ui-panel.js
  ui/app/components/role-edit.js
  ui/app/components/secret-create-or-update.js
  ui/app/components/transit-edit.js
  ui/app/lib/console-helpers.ts
  ui/app/services/console.js
  ui/lib/core/addon/components/navigate-input.js
  ui/lib/core/addon/utils/key-codes.js
  ui/lib/core/addon/utils/keys.js
  ui/lib/kubernetes/addon/components/page/roles.js
  ui/lib/kv/addon/components/kv-list-filter.js
  ui/tests/pages/components/console/ui-panel.js
Labels: ui, hashicorp-contributed-pr

#29907 Backport of Add web engineering to the CODEOWNERS file for website tooling, but not content. into release/1.19.x
  CODEOWNERS
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30522 [UI] API Client Update - Sync
  ui/api-client/dist/esm/models/EntityAliasesCreateDuplicatesRequest.d.ts
  ui/api-client/dist/esm/models/EntityAliasesCreateDuplicatesRequest.js
  ui/api-client/dist/esm/models/SystemListSyncAssociationsResponse.d.ts
  ui/api-client/dist/esm/models/SystemListSyncAssociationsResponse.js
  ui/api-client/dist/esm/models/SystemListSyncDestinationsResponse.d.ts
  ui/api-client/dist/esm/models/SystemListSyncDestinationsResponse.js
  ui/api-client/dist/esm/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.d.ts
  ui/api-client/dist/esm/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.js
  ui/api-client/dist/models/EntityAliasesCreateDuplicatesRequest.d.ts
  ui/api-client/dist/models/EntityAliasesCreateDuplicatesRequest.js
  ui/api-client/dist/models/SystemListSyncAssociationsResponse.d.ts
  ui/api-client/dist/models/SystemListSyncAssociationsResponse.js
  ui/api-client/dist/models/SystemListSyncDestinationsResponse.d.ts
  ui/api-client/dist/models/SystemListSyncDestinationsResponse.js
  ui/api-client/dist/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.d.ts
  ui/api-client/dist/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.js
  ui/api-client/src/models/EntityAliasesCreateDuplicatesRequest.ts
  ui/api-client/src/models/SystemListSyncAssociationsResponse.ts
  ui/api-client/src/models/SystemListSyncDestinationsResponse.ts
  ui/api-client/src/models/SystemReadSyncDestinationsTypeNameAssociationsResponse.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30490 [VAULT-34216] UI: Namespace picker feature branch
  changelog/30490.txt
  ui/app/components/namespace-picker.hbs
  ui/app/components/namespace-picker.js
  ui/app/components/namespace-picker.ts
  ui/app/components/sidebar/frame.hbs
  ui/app/styles/components/namespace-picker.scss
  ui/app/styles/core.scss
  ui/app/styles/helper-classes/layout.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/styles/utils/_size_variables.scss
  ui/app/templates/components/namespace-picker.hbs
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/helpers/commands.js
  ui/tests/helpers/namespace-picker.js
  ui/tests/integration/components/namespace-picker-test.js
  ui/tests/integration/components/sidebar/frame-test.js
  ui/types/vault/services/namespace.d.ts
Labels: ui, hashicorp-contributed-pr

#30521 UI: Implement `Auth::FormTemplate`
  ui/app/components/auth/form/oidc-jwt.ts
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/app/components/splash-page.hbs
  ui/app/routes/vault/cluster/auth.js
  ui/app/styles/helper-classes/layout.scss
  ui/app/templates/components/mfa/mfa-form.hbs
  ui/app/templates/components/okta-number-challenge.hbs
  ui/app/templates/vault/cluster/auth.hbs
  ui/app/templates/vault/cluster/mfa-setup.hbs
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/acceptance/enterprise-oidc-namespace-test.js
  ui/tests/acceptance/jwt-auth-method-test.js
  ui/tests/acceptance/managed-namespace-test.js
  ui/tests/acceptance/mfa-login-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/oidc-provider-test.js
  ui/tests/acceptance/redirect-to-test.js
  ui/tests/acceptance/reset-password-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/integration/components/auth/form/oidc-jwt-test.js
  ui/tests/integration/components/auth/login-form-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/tests/integration/components/splash-page-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#30517 Fix Firefox headless test
  ui/app/components/sidebar/nav/access.hbs
  ui/app/controllers/vault/cluster/secrets/backends.js
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/integration/components/json-editor-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30494 VAULT-35788: Fix startup failure when using config directory rather than file
  command/server.go
  internalshared/configutil/merge.go
  internalshared/configutil/merge_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30354 VAULT-35384 Add new telemetry metrics for HTTP response status codes
  changelog/30354.txt
  http/cors.go
  http/handler.go
  http/logical.go
  http/sys_feature_flags.go
  http/sys_health.go
  http/sys_metrics.go
  sdk/go.mod
  sdk/go.sum
  sdk/logical/response_util.go
  vault/logical_system.go
Labels: hashicorp-contributed-pr

#30532 Add RotationManager stubs to the mock plugin
  sdk/plugin/mock/backend.go
  sdk/plugin/mock/path_config.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30526 Vault-34683: Block counters api until loading of clientIDs to memory is complete during setup CE changes
  vault/activity_log_testonly_oss_test.go
  vault/activity_log_util.go
  vault/external_tests/activity_testonly/activity_testonly_oss_test.go
  vault/logical_system_activity.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30531 Backport 1.19.x: Fix headless tests
  ui/app/components/sidebar/nav/access.hbs
  ui/app/controllers/vault/cluster/secrets/backends.js
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/tests/acceptance/auth/mfa-test.js
  ui/tests/acceptance/oidc-auth-method-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/json-editor-test.js
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#30527 Delete old auth components
  CODEOWNERS
  ui/app/components/auth-form-options.js
  ui/app/components/auth-form.js
  ui/app/components/auth-jwt.js
  ui/app/components/auth-saml.hbs
  ui/app/components/auth-saml.js
  ui/app/styles/components/auth-form.scss
  ui/app/styles/components/login-form.scss
  ui/app/styles/core.scss
  ui/app/templates/components/auth-form-options.hbs
  ui/app/templates/components/auth-form.hbs
  ui/app/templates/components/auth-jwt.hbs
  ui/tests/integration/components/auth-form-test.js
  ui/tests/integration/components/auth-jwt-test.js
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/unit/components/auth-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30524 [UI] Ember Data Migration - Sync Overview/Destinations
  ui/app/app.js
  ui/app/services/capabilities.ts
  ui/app/utils/constants/capabilities.ts
  ui/lib/config-ui/addon/components/messages/page/list.hbs
  ui/lib/config-ui/addon/routes/messages/message/details.js
  ui/lib/core/addon/components/page/error.hbs
  ui/lib/core/addon/components/page/error.ts
  ui/lib/core/addon/helpers/has-capability.ts
  ui/lib/core/addon/helpers/sync-destinations.ts
  ui/lib/core/addon/utils/capabilities.ts
  ui/lib/core/addon/utils/paginate-list.ts
  ui/lib/sync/addon/components/secrets/page/destinations.hbs
  ui/lib/sync/addon/components/secrets/page/destinations.ts
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/engine.js
  ui/lib/sync/addon/routes/secrets/destinations/create/destination.ts
  ui/lib/sync/addon/routes/secrets/destinations/index.ts
  ui/lib/sync/addon/routes/secrets/overview.ts
  ui/lib/sync/addon/templates/secrets/destinations/index.hbs
  ui/lib/sync/addon/templates/secrets/overview.hbs
  ui/lib/sync/addon/utils/api-method-resolver.ts
  ui/lib/sync/addon/utils/api-transforms.ts
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/api/error-response.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/config-ui/messages/page/list-test.js
  ui/tests/integration/components/page/error-test.js
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
  ui/tests/unit/helpers/has-capability-test.js
  ui/tests/unit/services/api-test.js
  ui/tests/unit/services/capabilities-test.js
  ui/types/vault/helpers/sync-destinations.d.ts
  ui/types/vault/helpers/sync-destinations.ts
  ui/types/vault/sync.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29085 Backport of [DOCS] SEO updates for Auth pages into release/1.18.x
  website/content/docs/auth/approle/approle-pattern.mdx
  website/content/docs/auth/approle/index.mdx
  website/content/docs/auth/jwt/index.mdx
  website/content/docs/auth/jwt/oidc-providers/adfs.mdx
  website/content/docs/auth/jwt/oidc-providers/auth0.mdx
  website/content/docs/auth/jwt/oidc-providers/azuread.mdx
  website/content/docs/auth/jwt/oidc-providers/forgerock.mdx
  website/content/docs/auth/jwt/oidc-providers/gitlab.mdx
  website/content/docs/auth/jwt/oidc-providers/google.mdx
  website/content/docs/auth/jwt/oidc-providers/ibmisam.mdx
  website/content/docs/auth/jwt/oidc-providers/index.mdx
  website/content/docs/auth/jwt/oidc-providers/keycloak.mdx
  website/content/docs/auth/jwt/oidc-providers/kubernetes.mdx
  website/content/docs/auth/jwt/oidc-providers/okta.mdx
  website/content/docs/auth/jwt/oidc-providers/secureauth.mdx
  website/content/docs/auth/login-mfa/faq.mdx
  website/content/docs/auth/login-mfa/index.mdx
  website/content/docs/auth/saml/adfs.mdx
  website/content/docs/auth/saml/index.mdx
  website/content/docs/auth/saml/link-vault-group-to-ad.mdx
  website/content/docs/auth/saml/troubleshoot-adfs/index.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29236 Backport of [DOCS] Update the PKI secrets engine docs title & description into release/1.18.x
  website/content/docs/secrets/pki/cieps.mdx
  website/content/docs/secrets/pki/cmpv2.mdx
  website/content/docs/secrets/pki/considerations.mdx
  website/content/docs/secrets/pki/est.mdx
  website/content/docs/secrets/pki/index.mdx
  website/content/docs/secrets/pki/quick-start-intermediate-ca.mdx
  website/content/docs/secrets/pki/quick-start-root-ca.mdx
  website/content/docs/secrets/pki/rotation-primitives.mdx
  website/content/docs/secrets/pki/setup.mdx
  website/content/docs/secrets/pki/troubleshooting-acme.mdx
  website/content/partials/x509-sha1-deprecation.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30542 UI, Storage, and Replicated Mount Metrics
  vault/core_metrics.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30543 Update vault-plugin-auth-azure to v0.20.4
  changelog/30543.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#30546 [UI] Fixes Capabilities Issues in Custom Messages
  ui/lib/config-ui/addon/routes/messages/index.js
  ui/lib/config-ui/addon/templates/messages/index.hbs
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30545 Backport of Update vault-plugin-auth-azure to v0.20.4 into release/1.19.x
  changelog/30543.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30547 Docs for Phase 1 Census Metrics
  website/content/docs/license/product-usage-reporting.mdx
Labels: docs, pr/no-changelog

#30537 Update `with` query param functionality
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/login-form.hbs
  ui/app/components/auth/login-form.js
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/app/components/auth/single-mount.hbs
  ui/app/components/auth/tabs.hbs
  ui/app/controllers/vault/cluster/auth.js
  ui/app/routes/vault/cluster/auth.js
  ui/app/routes/vault/cluster/logout.js
  ui/app/templates/vault/cluster/auth.hbs
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/acceptance/enterprise-namespaces-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/types/vault/auth/form.d.ts
Labels: pr/no-changelog, hashicorp-contributed-pr

#30505 Backport of [DOCS] Add hcp info to EKM steps into release/1.19.x
  website/content/docs/platform/mssql/installation.mdx
Labels: hashicorp-contributed-pr

#30525 Flaky test and info-table-row test selectors
  ui/app/components/dashboard/quick-actions-card.hbs
  ui/app/components/database-role-edit.hbs
  ui/app/templates/components/database-connection.hbs
  ui/app/templates/components/secret-create-or-update.hbs
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/info-table-row.hbs
  ui/tests/acceptance/dashboard-test.js
  ui/tests/acceptance/enterprise-kmip-test.js
  ui/tests/acceptance/mfa-method-test.js
  ui/tests/acceptance/oidc-config/clients-test.js
  ui/tests/acceptance/oidc-config/providers-scopes-test.js
  ui/tests/acceptance/pki/pki-engine-workflow-test.js
  ui/tests/acceptance/replication-nav-test.js
  ui/tests/acceptance/secrets/backend/database/secret-test.js
  ui/tests/acceptance/secrets/backend/database/workflow-test.js
  ui/tests/acceptance/secrets/backend/engines-test.js
  ui/tests/acceptance/secrets/backend/kv/secret-test.js
  ui/tests/acceptance/secrets/backend/ssh/roles-test.js
  ui/tests/acceptance/settings-test.js
  ui/tests/acceptance/transit-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/kv/kv-selectors.js
  ui/tests/helpers/pki/pki-selectors.ts
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/helpers/secret-engine/secret-engine-selectors.ts
  ui/tests/integration/components/config-ui/messages/page/details-test.js
  ui/tests/integration/components/dashboard/quick-actions-card-test.js
  ui/tests/integration/components/database-role-edit-test.js
  ui/tests/integration/components/info-table-row-test.js
  ui/tests/integration/components/keymgmt/provider-edit-test.js
  ui/tests/integration/components/kubernetes/page/credentials-test.js
  ui/tests/integration/components/kv/kv-paths-card-test.js
  ui/tests/integration/components/ldap/page/configuration-test.js
  ui/tests/integration/components/ldap/page/library/check-out-test.js
  ui/tests/integration/components/ldap/page/library/details/configuration-test.js
  ui/tests/integration/components/ldap/page/role/credentials-test.js
  ui/tests/integration/components/mfa-login-enforcement-form-test.js
  ui/tests/integration/components/pki/page/pki-certificate-details-test.js
  ui/tests/integration/components/pki/page/pki-configuration-details-test.js
  ui/tests/integration/components/pki/page/pki-issuer-edit-test.js
  ui/tests/integration/components/pki/page/pki-tidy-auto-settings-test.js
  ui/tests/integration/components/pki/parsed-certificate-info-rows-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-issuer-details-test.js
  ui/tests/integration/components/pki/pki-sign-intermediate-form-test.js
  ui/tests/integration/components/secret-edit-test.js
  ui/tests/integration/components/secrets-engine-mount-config-test.js
  ui/tests/pages/secrets/backend/configuration.js
  ui/tests/pages/secrets/backend/database/connection.js
  ui/tests/pages/secrets/backend/database/role.js
  ui/tests/pages/secrets/backend/kv/edit-secret.js
  ui/tests/pages/secrets/backends.js
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30502 VAULT-34680: Removing estimates from counters api: Handle ephemeral clients
  vault/activity_log.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30560 UI: Add param check to redirect hook
  ui/app/routes/vault/cluster/auth.js
  ui/tests/acceptance/auth/auth-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30554 [UI] Ember Data Migration - Sync Details/Secrets
  ui/app/utils/constants/capabilities.ts
  ui/lib/sync/addon/components/secrets/destination-header.hbs
  ui/lib/sync/addon/components/secrets/destination-header.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/details.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/details.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/destination/secrets.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.hbs
  ui/lib/sync/addon/routes/secrets/destinations/destination.ts
  ui/lib/sync/addon/routes/secrets/destinations/destination/edit.ts
  ui/lib/sync/addon/routes/secrets/destinations/destination/secrets.ts
  ui/lib/sync/addon/templates/secrets/destinations/destination/details.hbs
  ui/lib/sync/addon/templates/secrets/destinations/destination/secrets.hbs
  ui/mirage/factories/sync-destination.js
  ui/mirage/handlers/sync.js
  ui/tests/helpers/sync/setup-hooks.js
  ui/tests/helpers/sync/setup-models.js
  ui/tests/integration/components/sync/secrets/destination-header-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/details-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/secrets-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
  ui/types/vault/sync.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30550 Backport 1.19.x: Replace e.keyCode with e.key
  changelog/30493.txt
  ui/app/components/console/command-input.js
  ui/app/components/console/ui-panel.js
  ui/app/components/role-edit.js
  ui/app/components/secret-create-or-update.js
  ui/app/components/transit-edit.js
  ui/app/lib/console-helpers.ts
  ui/app/services/console.js
  ui/lib/core/addon/components/navigate-input.js
  ui/lib/core/addon/utils/key-codes.js
  ui/lib/core/addon/utils/keys.js
  ui/lib/kubernetes/addon/components/page/roles.js
  ui/lib/kv/addon/components/kv-list-filter.js
  ui/tests/pages/components/console/ui-panel.js
Labels: ui, backport, hashicorp-contributed-pr

#30556 VAULT-35079: Scaffolding for recover operations on backends
  sdk/logical/logical.go
  sdk/logical/request.go
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/translation.go
  sdk/plugin/pb/translation_test.go
  vault/router.go
  vault/router_test.go
  vault/router_testing.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30565 VAULT-35082: Recovery policy capability
  vault/acl.go
  vault/acl_test.go
  vault/logical_system.go
  vault/logical_system_test.go
  vault/policy.go
  vault/policy_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30563 UI: Move preselected auth type logic to Auth::FormTemplate
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/page-test.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#30523 Vault/on openshift
  website/content/docs/deploy/kubernetes/helm/openshift.mdx
Labels: docs, website, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30538 [UI] VAULT-35614 review reporting phase 1 dashboard design changes
  ui/app/components/usage/page.ts
  ui/tests/integration/components/usage/page-test.js
  ui/tests/integration/components/usage/page/index-test.js
  ui/vault-reporting/declarations/components/vault-reporting/base/title-row.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/base/title-row.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/cluster-replication.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/cluster-replication.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/counter.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/counter.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/dashboard/export.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/filter-bar.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/filter-bar.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/global-lease.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/global-lease.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/horizontal-bar-chart.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/horizontal-bar-chart.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/views/dashboard.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/views/dashboard.d.ts.map
  ui/vault-reporting/declarations/components/vault-reporting/views/secret-inventory.d.ts
  ui/vault-reporting/declarations/components/vault-reporting/views/secret-inventory.d.ts.map
  ui/vault-reporting/declarations/services/reporting-analytics.d.ts
  ui/vault-reporting/declarations/services/reporting-analytics.d.ts.map
  ui/vault-reporting/declarations/types/index.d.ts
  ui/vault-reporting/declarations/types/index.d.ts.map
  ui/vault-reporting/declarations/utils/cel.d.ts
  ui/vault-reporting/declarations/utils/cel.d.ts.map
  ui/vault-reporting/dist/components/vault-reporting/base/title-row.js.map
  ui/vault-reporting/dist/components/vault-reporting/cluster-replication.js
  ui/vault-reporting/dist/components/vault-reporting/cluster-replication.js.map
  ui/vault-reporting/dist/components/vault-reporting/counter.js
  ui/vault-reporting/dist/components/vault-reporting/counter.js.map
  ui/vault-reporting/dist/components/vault-reporting/dashboard/export.js
  ui/vault-reporting/dist/components/vault-reporting/dashboard/export.js.map
  ui/vault-reporting/dist/components/vault-reporting/global-lease.js
  ui/vault-reporting/dist/components/vault-reporting/global-lease.js.map
  ui/vault-reporting/dist/components/vault-reporting/horizontal-bar-chart.js
  ui/vault-reporting/dist/components/vault-reporting/horizontal-bar-chart.js.map
  ui/vault-reporting/dist/components/vault-reporting/views/dashboard.js
  ui/vault-reporting/dist/components/vault-reporting/views/dashboard.js.map
  ui/vault-reporting/dist/styles/vault-reporting.css
  ui/vault-reporting/dist/types/index.js.map
Labels: pr/no-changelog, hashicorp-contributed-pr

#30566 Refactor security-scan workflow
  .github/workflows/security-scan.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30488 UI: CE Datepicker
  changelog/30488.txt
  ui/app/components/clients/date-range.hbs
  ui/app/components/clients/date-range.ts
  ui/app/components/clients/page-header.hbs
  ui/app/components/clients/page-header.js
  ui/app/components/clients/page/counts.ts
  ui/app/styles/helper-classes/layout.scss
  ui/mirage/handlers/clients.js
  ui/tests/acceptance/clients/counts/overview-test.js
  ui/tests/integration/components/clients/date-range-test.js
  ui/tests/integration/components/clients/page/counts-test.js
Labels: hashicorp-contributed-pr

#30569 Backport of Add RotationManager stubs to the mock plugin into release/1.19.x
  sdk/plugin/mock/backend.go
  sdk/plugin/mock/path_config.go
Labels: hashicorp-contributed-pr

#30548 UI: Updating visibility attr on auth config to be a toggle with direct login link
  ui/app/components/auth-config-form/options.hbs
  ui/app/components/auth-config-form/options.js
  ui/app/models/mount-config.js
  ui/tests/acceptance/auth/test-helper.js
  ui/tests/integration/components/auth-config-form/options-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30568 Backport of Vault/on openshift into release/1.19.x
  website/content/docs/deploy/kubernetes/helm/openshift.mdx
Labels: hashicorp-contributed-pr

#30567 VAULT-35081: Extract query parameters for snapshot read/recover
  http/handler.go
  http/handler_test.go
  http/logical.go
  http/logical_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30580 UI: Update template helpers and cleanup component args
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/mounts-display.hbs
  ui/app/components/auth/page.hbs
  ui/app/components/auth/page.js
  ui/app/components/auth/single-mount.hbs
  ui/app/components/auth/tabs.hbs
  ui/app/components/auth/tabs.ts
  ui/app/helpers/auth-display-name.ts
  ui/app/routes/vault/cluster/auth.js
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/types/vault/auth/form.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30486 Fixing link to static role documentation
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.19.x

#30518 VAULT-35783: create activity specific metrics reference page in telemetry docs
  website/content/docs/internals/telemetry/metrics/activity.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30447 VAULT-35628 Add group_by and secondary_rate to RLQ API
  vault/external_tests/quotas/quotas_test.go
  vault/logical_system_quotas.go
  vault/quotas/quotas.go
  vault/quotas/quotas_rate_limit.go
  vault/quotas/quotas_rate_limit_test.go
  vault/quotas/quotas_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30583 Update vault-plugin-auth-cf to v0.20.1
  changelog/30583.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#30581 Backport of Fixing link to static role documentation into release/1.19.x
  website/content/docs/secrets/aws.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30586 backport: 1.19.x: Update vault-plugin-auth-cf to v0.20.1
  changelog/30586.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#30571 [VAULT-35871] UI: Address design UI feedback on namespace picker
  ui/app/components/namespace-picker.hbs
  ui/app/components/namespace-picker.ts
  ui/app/styles/components/namespace-picker.scss
  ui/app/styles/core.scss
  ui/app/styles/helper-classes/spacing.scss
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30561 VAULT-34848: Deprecate sys/internal/counters/tokens endpoint
  changelog/30561.txt
  vault/counters.go
  vault/counters_test.go
  vault/logical_system.go
  vault/logical_system_paths.go
Labels: pr/no-milestone, hashicorp-contributed-pr

#30541 Dependency bumps part 1
  ui/app/lib/path-to-tree.js
  ui/config/deprecation-workflow.js
  ui/package.json
  ui/tests/unit/lib/path-to-tree-test.js
  ui/yarn.lock
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30588 Phase 2 Census Usage Metrics
  vault/testing.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30596 Update go version to 1.24.3
  .go-version
  builtin/logical/pki/backend_test.go
  builtin/logical/pki/path_roles_test.go
  builtin/logical/pki/path_root.go
  changelog/_go-ver-1194.txt
  go.mod
  sdk/go.mod
  sdk/helper/certutil/helpers.go
  sdk/plugin/grpc_system.go
  vault/auth_test.go
  vault/mount_test.go
Labels: hashicorp-contributed-pr

#30598 Revert partial test changes for skipping FIPS tests for unsupported SHA3 hashes
  sdk/helper/keysutil/policy_test.go
Labels: test, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30396 VAULT-35385 docs for response_status_code metric
  website/content/docs/internals/telemetry/metrics/core-system.mdx
  website/content/partials/telemetry-metrics/vault/core/response_status_code.mdx
Labels: pr/no-changelog, hashicorp-contributed-pr

#30600 [UI] Remove vault-reporting from stylelint
  ui/.stylelintignore
Labels: pr/no-changelog, hashicorp-contributed-pr

#30601 Remove FIPS build tag from command/server_test.go
  command/server_test.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30345 [VAULT-34873] UI: improve `FormField` test coverage for fields migrated to HDS
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/lib/core/addon/components/text-file.hbs
  ui/tests/helpers/config-ui/message-selectors.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/integration/components/kubernetes/page/configure-test.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
  ui/tests/integration/components/pki/pki-generate-csr-test.js
  ui/tests/integration/components/pki/pki-key-form-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
  ui/tests/integration/components/text-file-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#30603 Changelog for the addition of X25519/ML-KEM in Go TLS.
  changelog/30603.txt
Labels: hashicorp-contributed-pr, backport/1.19.x

#30605 Backport of Changelog for the addition of X25519/ML-KEM in Go TLS. into release/1.19.x
  changelog/30603.txt
Labels: hashicorp-contributed-pr

#30519 Update Docs For Bound Audience Explanation
  website/content/api-docs/auth/jwt.mdx
  website/content/docs/auth/jwt/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30602 Backport of Remove FIPS build tag from command/server_test.go into release/1.19.x
  command/server_test.go
Labels: backport, test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30594 Dependency bump 2
  ui/lint-staged.config.mjs
  ui/package.json
  ui/scripts/list-templates.js
  ui/tests/integration/components/path-filter-config-list-test.js
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30595 Add fixes for processing InTune SCEP messages within our PKCS7 library
  helper/pkcs7/decrypt.go
  helper/pkcs7/decrypt_test.go
  helper/pkcs7/pkcs7.go
  helper/pkcs7/testdata/intune-pkcs7-sample.msg
  helper/pkcs7/x509_workaround.go
  helper/pkcs7/x509_workaround_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30555 [VAULT-34808] UI: move the `radio` block in `FormField` under the HDS block
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/components/form-field.js
  ui/tests/acceptance/secrets/backend/totp/key-test.js
  ui/tests/acceptance/sync/secrets/destinations-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/helpers/sync/sync-selectors.js
  ui/tests/integration/components/form-field-test.js
  ui/tests/integration/components/kubernetes/page/role/create-and-edit-test.js
  ui/tests/integration/components/ldap/page/library/create-and-edit-test.js
  ui/tests/integration/components/mfa/method-form-test.js
  ui/tests/integration/components/oidc/client-form-test.js
  ui/tests/integration/components/totp/key-form-test.js
  ui/tests/pages/components/form-field.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, hds-service

#30604 Vault 34685: Add telemetry metric vault.client.billing_period.activity CE
  vault/activity_log_testonly_oss_test.go
  vault/activity_log_util.go
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30491 Vault 34685: Add telemetry metric vault.client.billing_period.activity docs
  website/content/docs/internals/telemetry/metrics/activity.mdx
  website/content/docs/internals/telemetry/metrics/all.mdx
  website/content/partials/telemetry-metrics/vault/client/billing_period/activity.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30623 VAULT-34562: Add required CE stubs
  vault/core.go
  vault/core_stubs_oss.go
  vault/core_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30572 Docs: Removing estimates for current month from counters api
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/concepts/client-count/counting.mdx
  website/content/partials/counters-api-new-clients-behavior-change.mdx
  website/content/partials/counters-api-wait-warning.mdx
  website/content/partials/faq/client-count/upgrading.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30616 [DOCS] Remove the out-dated statement about HCP Terraform
  website/content/docs/secrets/terraform.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30622 Docs for Phase 2 Census Usage metrics
  website/content/docs/license/product-usage-reporting.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30630 [Docs] Update the tutorial links
  website/content/docs/plugins/index.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/mongodb.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30620 [UI] Ember Data Migration - Sync Destination Create/Edit
  ui/app/forms/form.ts
  ui/app/forms/sync/aws-sm.ts
  ui/app/forms/sync/azure-kv.ts
  ui/app/forms/sync/gcp-sm.ts
  ui/app/forms/sync/gh.ts
  ui/app/forms/sync/resolver.ts
  ui/app/forms/sync/shared.ts
  ui/app/forms/sync/vercel-project.ts
  ui/app/utils/forms/field-group.ts
  ui/app/utils/forms/field.ts
  ui/lib/core/addon/helpers/sync-destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations.ts
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.hbs
  ui/lib/sync/addon/components/secrets/page/destinations/create-and-edit.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/details.ts
  ui/lib/sync/addon/components/secrets/page/overview.ts
  ui/lib/sync/addon/routes/secrets/destinations/create/destination.ts
  ui/lib/sync/addon/routes/secrets/destinations/destination/edit.ts
  ui/lib/sync/addon/templates/secrets/destinations/create/destination.hbs
  ui/lib/sync/addon/templates/secrets/destinations/destination/edit.hbs
  ui/lib/sync/addon/utils/api-method-resolver.ts
  ui/lib/sync/addon/utils/api-transforms.ts
  ui/tests/acceptance/sync/secrets/destination-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/sync/secrets/page/destinations-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/create-and-edit-test.js
  ui/types/vault/helpers/sync-destinations.d.ts
  ui/types/vault/sync.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30615 VAULT-35080: Snapshot ID context conversion for GRPC plugins
  sdk/plugin/context.go
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_backend_test.go
  sdk/plugin/grpc_storage.go
  sdk/plugin/mock/backend.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30626 VAULT-35396 CE changes for SDK observation update
  sdk/framework/backend.go
  sdk/logical/logical.go
  sdk/logical/observations.go
  sdk/plugin/grpc_backend_client.go
  sdk/plugin/grpc_backend_server.go
  sdk/plugin/grpc_observations.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/plugin/pb/backend_grpc.pb.go
  vault/auth.go
  vault/mount.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30634 [UI] Ember Data Migration - Sync Cleanup
  ui/api-client/.openapi-generator/FILES
  ui/api-client/dist/apis/SystemApi.d.ts
  ui/api-client/dist/apis/SystemApi.js
  ui/api-client/dist/esm/apis/SystemApi.d.ts
  ui/api-client/dist/esm/apis/SystemApi.js
  ui/api-client/dist/esm/models/index.d.ts
  ui/api-client/dist/esm/models/index.js
  ui/api-client/dist/models/index.d.ts
  ui/api-client/dist/models/index.js
  ui/api-client/src/apis/SystemApi.ts
  ui/api-client/src/models/index.ts
  ui/lib/sync/addon/components/secrets/page/destinations/destination/sync.ts
  ui/lib/sync/addon/components/secrets/sync-activation-modal.ts
  ui/lib/sync/addon/routes/secrets/destinations/create/destination.ts
  ui/lib/sync/addon/templates/secrets/destinations/destination/sync.hbs
  ui/lib/sync/package.json
  ui/tests/acceptance/sync/secrets/overview-test.js
  ui/tests/integration/components/sync/secrets/page/destinations/destination/sync-test.js
  ui/tests/integration/components/sync/secrets/page/overview-test.js
  ui/tests/integration/components/sync/secrets/sync-activation-modal-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30644 test: fix CompilePlugin test helper
  helper/testhelpers/pluginhelpers/pluginhelpers.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30642 Address SAML flaky test
  ui/app/components/sidebar/user-menu.hbs
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/acceptance/cluster-test.js
  ui/tests/acceptance/mfa-setup-test.js
  ui/tests/acceptance/reset-password-test.js
  ui/tests/acceptance/saml-auth-method-test.js
  ui/tests/helpers/general-selectors.ts
  ui/tests/integration/components/sidebar/user-menu-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30647 [VAULT-35165] CE changes for development cluster setting
  sdk/helper/consts/replication.go
  vault/census.go
  vault/census_manager.go
  vault/core.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30646 VAULT-36174: code-checker: Configure git with the ELEVATED_GITHUB_TOKEN
  .github/workflows/code-checker.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30529 VAULT-35369: Loaded snapshots CE
  helper/testhelpers/teststorage/teststorage.go
  physical/raft/fsm.go
  physical/raft/raft.go
  physical/raft/snapshot.go
  physical/raft/snapshot_test.go
  vault/barrier_access.go
  vault/external_tests/raft/raft_test.go
  vault/raft.go
  vault/raft_test.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30649 do not fail to start if missing mlock config on systems that do not support mlock
  command/server.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30629 Backport of [DOCS] Remove the out-dated statement about HCP Terraform into release/1.19.x
  website/content/docs/secrets/terraform.mdx
Labels: hashicorp-contributed-pr

#30631 Backport of [Docs] Update the tutorial links into release/1.19.x
  website/content/docs/plugins/index.mdx
  website/content/docs/secrets/databases/index.mdx
  website/content/docs/secrets/databases/mongodb.mdx
Labels: hashicorp-contributed-pr

#30639 Added Docs for Phase 3 Usage Metrics
  website/content/docs/license/product-usage-reporting.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr

#30593 Correct syntax errors
  website/content/docs/concepts/seal.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.19.x

#30653 Backport of Correct syntax errors into release/1.19.x
  website/content/docs/concepts/seal.mdx
Labels: hashicorp-contributed-pr

#30650 VAULT-36174: pipeline(go): deal with relative path issues in cache restore
  .github/actions/set-up-go/action.yml
  scripts/go-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30645 [VAULT-36201] pipeline(git): add Go git client
  .golangci.yml
  tools/pipeline/internal/pkg/git/apply.go
  tools/pipeline/internal/pkg/git/branch.go
  tools/pipeline/internal/pkg/git/checkout.go
  tools/pipeline/internal/pkg/git/cherry-pick.go
  tools/pipeline/internal/pkg/git/client.go
  tools/pipeline/internal/pkg/git/clone.go
  tools/pipeline/internal/pkg/git/commit.go
  tools/pipeline/internal/pkg/git/fetch.go
  tools/pipeline/internal/pkg/git/merge.go
  tools/pipeline/internal/pkg/git/opts_test.go
  tools/pipeline/internal/pkg/git/pull.go
  tools/pipeline/internal/pkg/git/push.go
  tools/pipeline/internal/pkg/git/rebase.go
  tools/pipeline/internal/pkg/git/reset.go
  tools/pipeline/internal/pkg/git/rm.go
  tools/pipeline/internal/pkg/git/show.go
  tools/pipeline/internal/pkg/git/status.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30648 Backport of VAULT-36174: code-checker: Configure git with the ELEVATED_GITHUB_TOKEN into release/1.19.x
  .github/workflows/code-checker.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30654 Backport of VAULT-36174: pipeline(go): deal with relative path issues in cache restore into release/1.19.x
  .github/actions/set-up-go/action.yml
  scripts/go-helper.sh
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30628 write known issues for follower nodes failure to extract ent plugins
  website/content/docs/commands/plugin/register.mdx
  website/content/docs/plugins/register.mdx
  website/content/docs/updates/important-changes.mdx
  website/content/docs/updates/release-notes.mdx
Labels: docs, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30652 UI: Tidy up TOTP logic
  ui/app/components/generate-credentials-totp.hbs
  ui/app/components/generate-credentials-totp.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30656 Update CHANGELOG.md for 1.19.4
  CHANGELOG.md
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30660 UI: Make single method views consistent, add max width
  ui/app/components/auth/form-template.hbs
  ui/app/components/auth/form-template.ts
  ui/app/components/auth/mounts-display.hbs
  ui/app/components/auth/page.ts
  ui/app/components/auth/tabs.hbs
  ui/app/models/role-jwt.js
  ui/app/styles/core/columns.scss
  ui/mirage/scenarios/custom-login.js
  ui/tests/acceptance/auth/auth-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/integration/components/auth/form-template-test.js
  ui/tests/integration/components/auth/page-test.js
  ui/tests/unit/models/role-jwt-test.js
  ui/types/vault/auth/form.d.ts
  ui/types/vault/services/auth.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30167 Fix broken link in the Web REPL help commands
  changelog/30167.txt
  ui/app/templates/components/console/log-help.hbs
Labels: backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30668 Revert "PostgreSQL backend passwordless authentication in cloud"
  changelog/30564.txt
  go.mod
  go.sum
  physical/postgresql/postgresql.go
  physical/postgresql/postgresql_test.go
  sdk/helper/docker/testhelpers.go
  vault/external_tests/seal_binary/seal_docker_util.go
  website/content/docs/configuration/storage/postgresql.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30670 Sidebranch: fix console help link
  changelog/30670.txt
  ui/app/templates/components/console/log-help.hbs
Labels: ui, hashicorp-contributed-pr, backport/1.19.x

#30662 Counters API: Add note regarding custom contracts
  website/content/api-docs/system/internal-counters.mdx
  website/content/partials/counters-api-custom-contract-note.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30664 Added docs for metadata I missed
  website/content/docs/license/product-usage-reporting.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30671 Backport of Sidebranch: fix console help link into release/1.19.x
  changelog/30670.txt
  ui/app/templates/components/console/log-help.hbs
Labels: ui, backport, hashicorp-contributed-pr

#30659 [VAULT-35162] Development Cluster setting docs
  changelog/30659.txt
  website/content/docs/configuration/reporting.mdx
  website/content/docs/license/product-usage-reporting.mdx
  website/content/docs/license/utilization/auto-reporting.mdx
  website/content/docs/license/utilization/manual-reporting.mdx
Labels: hashicorp-contributed-pr

#30661 Backport of write known issues for follower nodes failure to extract ent plugins into release/1.19.x
  website/content/docs/commands/plugin/register.mdx
  website/content/docs/plugins/register.mdx
  website/content/docs/updates/important-changes.mdx
  website/content/docs/updates/release-notes.mdx
Labels: hashicorp-contributed-pr

#30506 UI: Vault update client count charts to show new clients only
  changelog/30506.txt
  ui/app/components/clients/activity.ts
  ui/app/components/clients/attribution.hbs
  ui/app/components/clients/attribution.js
  ui/app/components/clients/chart-container.hbs
  ui/app/components/clients/charts/vertical-bar-stacked.ts
  ui/app/components/clients/page-header.hbs
  ui/app/components/clients/page-header.js
  ui/app/components/clients/page/acme.hbs
  ui/app/components/clients/page/acme.ts
  ui/app/components/clients/page/counts.hbs
  ui/app/components/clients/page/counts.ts
  ui/app/components/clients/page/overview.hbs
  ui/app/components/clients/page/sync.hbs
  ui/app/components/clients/page/sync.ts
  ui/app/components/clients/page/token.hbs
  ui/app/components/clients/running-total.hbs
  ui/app/components/clients/running-total.ts
  ui/app/routes/vault/cluster/clients/counts.ts
  ui/app/styles/components/chart-container.scss
  ui/app/styles/core/charts-lineal.scss
  ui/app/styles/core/charts.scss
  ui/app/utils/chart-helpers.js
  ui/lib/core/addon/utils/client-count-utils.ts
  ui/tests/acceptance/clients/counts-test.js
  ui/tests/acceptance/clients/counts/acme-test.js
  ui/tests/integration/components/clients/attribution-test.js
  ui/tests/integration/components/clients/page/acme-test.js
  ui/tests/integration/components/clients/page/counts-test.js
  ui/tests/integration/components/clients/page/overview-test.js
  ui/tests/integration/components/clients/page/sync-test.js
  ui/tests/integration/components/clients/page/token-test.js
  ui/tests/integration/components/clients/running-total-test.js
  ui/tests/integration/utils/client-count-utils-test.js
Labels: ui, hashicorp-contributed-pr

#30676 Fix heading level (h2 --> h3)
  website/content/api-docs/secret/identity/group.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30677 Backport of Fix heading level (h2 --> h3) into release/1.19.x
  website/content/api-docs/secret/identity/group.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30393 UI: Create engine list view into separate component
  ui/app/components/secret-engine/list.hbs
  ui/app/components/secret-engine/list.ts
  ui/app/controllers/vault/cluster/secrets/backends.js
  ui/app/templates/vault/cluster/secrets/backends.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/tests/acceptance/secret-engine-list-view-test.js
  ui/tests/integration/components/list-test.js
  ui/tests/pages/secrets/backend/database/connection.js
  ui/types/vault/models/secret-engine.d.ts
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#30641 OpenAPI Patch Endpoints
  sdk/framework/openapi.go
  sdk/framework/openapi_test.go
  sdk/framework/testdata/operations.json
  vault/logical_system.go
Labels: pr/no-changelog, go, hashicorp-contributed-pr

#30477 Terraform secret engine docs - support multiple team tokens
  website/content/docs/secrets/terraform.mdx
Labels: docs, pr/no-changelog, pr/no-milestone

#30674 Vault-35523 add autopilot metrics
  vault/core_metrics.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30679 Fix auth flaky test
  ui/app/components/section-tabs.hbs
  ui/app/helpers/supported-managed-auth-backends.js
  ui/app/templates/components/generated-item-list.hbs
  ui/app/templates/vault/cluster/access/method/section.hbs
  ui/app/templates/vault/cluster/access/methods.hbs
  ui/tests/acceptance/access/methods-test.js
  ui/tests/acceptance/auth/auth-list-test.js
  ui/tests/acceptance/settings/auth/configure/section-test.js
  ui/tests/acceptance/settings/auth/enable-test.js
  ui/tests/acceptance/sidebar-nav-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/general-selectors.ts
  ui/tests/pages/settings/auth/configure/section.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#30658 [VAULT-36202] pipeline(releases): add `releases list active-versions` command
  .github/actions/create-dynamic-config/action.yml
  .release/versions.hcl
  tools/pipeline/internal/cmd/generate_enos_dynamic_config.go
  tools/pipeline/internal/cmd/github.go
  tools/pipeline/internal/cmd/github_list_changed_files.go
  tools/pipeline/internal/cmd/github_list_runs.go
  tools/pipeline/internal/cmd/releases.go
  tools/pipeline/internal/cmd/releases_list.go
  tools/pipeline/internal/cmd/releases_list_active_versions.go
  tools/pipeline/internal/cmd/releases_list_versions.go
  tools/pipeline/internal/cmd/root.go
  tools/pipeline/internal/pkg/changed/checkers.go
  tools/pipeline/internal/pkg/changed/checkers_test.go
  tools/pipeline/internal/pkg/changed/file.go
  tools/pipeline/internal/pkg/generate/enos_dynamic_config_test.go
  tools/pipeline/internal/pkg/github/list_changed_files.go
  tools/pipeline/internal/pkg/releases/list_active_versions.go
  tools/pipeline/internal/pkg/releases/list_active_versions_test.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/ent/1.17.x+ent, backport/1.19.x, backport/ent/1.18.x+ent

#30682 docs: remove venafi plugin documentation
  website/content/docs/secrets/venafi.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, backport/1.19.x

#30640 UI: Update custom login to use api instead of mirage
  ui/lib/config-ui/addon/components/login-settings/page/details.hbs
  ui/lib/config-ui/addon/components/login-settings/page/details.js
  ui/lib/config-ui/addon/components/login-settings/page/list.hbs
  ui/lib/config-ui/addon/components/login-settings/page/list.js
  ui/lib/config-ui/addon/engine.js
  ui/lib/config-ui/addon/routes/login-settings/index.js
  ui/lib/config-ui/addon/routes/login-settings/rule/details.js
  ui/tests/acceptance/config-ui/login-settings-test.js
  ui/tests/acceptance/config-ui/login-settings/login-settings-test.js
  ui/tests/helpers/config-ui/message-selectors.ts
  ui/tests/unit/services/custom-login-test.js
Labels: ui, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30690 [VAULT-35075] Add API paths for loaded snap
  http/handler.go
  http/logical.go
  vault/external_tests/raft/raft_test.go
  vault/logical_system_raft.go
  vault/raft.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30695 Backport of [DOCS] Replace with link to changelog in github into release/1.19.x
  website/content/docs/updates/changelog.mdx
  website/data/docs-nav-data.json
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30633 VAULT-35628: evaluate entity-based and collective group_by RLQ modes
  http/util.go
  http/util_oss.go
  vault/quotas/quotas.go
  vault/quotas/quotas_rate_limit.go
  vault/quotas/quotas_rate_limit_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30270 docs/vault-helm: install the chart in a non-default namespace
  website/content/docs/deploy/kubernetes/helm/openshift.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30689 [Docs] Minor format fixes
  website/content/docs/configuration/programmatic-management.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#30697 Backport of [Docs] Minor format fixes into release/1.19.x
  website/content/docs/configuration/programmatic-management.mdx
Labels: hashicorp-contributed-pr

#30691 Backport of docs: remove venafi plugin documentation into release/1.19.x
  website/content/docs/secrets/venafi.mdx
  website/data/docs-nav-data.json
Labels: hashicorp-contributed-pr

#30698 VAULT-35628: add missing change to fix ce-ent diff
  vault/quotas/quotas_rate_limit.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30683 Add enterprise configuration to optionally remove irrevocable leases
  command/server.go
  command/server/config.go
  command/server/config_test_helpers.go
  command/server/test-fixtures/config.hcl
  command/server/test-fixtures/config.hcl.json
  command/server/test-fixtures/config2.hcl
  command/server/test-fixtures/config3.hcl
  command/server/test-fixtures/config5.hcl
  http/sys_config_state_test.go
  vault/core.go
  vault/expiration.go
  vault/expiration_ce.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#30591 VAULT-36166 Deprecate counters/tokens api in Docs
  website/content/api-docs/system/internal-counters.mdx
  website/content/docs/updates/deprecation.mdx
  website/content/partials/deprecation/internal-counters-tokens-api.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#30692 [VAULT-36271] UI: Add refresh namespaces button and breadcrumb to manage namespace page
  changelog/30692.txt
  ui/app/controllers/vault/cluster/access/namespaces/index.js
  ui/app/templates/vault/cluster/access/namespaces/index.hbs
  ui/tests/acceptance/access/namespaces/index-test.js
Labels: ui, hashicorp-contributed-pr

#30655 Backport of [VAULT-36201] pipeline(git): add Go git client into release/1.19.x
  tools/pipeline/internal/pkg/git/apply.go
  tools/pipeline/internal/pkg/git/branch.go
  tools/pipeline/internal/pkg/git/checkout.go
  tools/pipeline/internal/pkg/git/cherry-pick.go
  tools/pipeline/internal/pkg/git/client.go
  tools/pipeline/internal/pkg/git/clone.go
  tools/pipeline/internal/pkg/git/commit.go
  tools/pipeline/internal/pkg/git/fetch.go
  tools/pipeline/internal/pkg/git/merge.go
  tools/pipeline/internal/pkg/git/opts_test.go
  tools/pipeline/internal/pkg/git/pull.go
  tools/pipeline/internal/pkg/git/push.go
  tools/pipeline/internal/pkg/git/rebase.go
  tools/pipeline/internal/pkg/git/reset.go
  tools/pipeline/internal/pkg/git/rm.go
  tools/pipeline/internal/pkg/git/show.go
  tools/pipeline/internal/pkg/git/status.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr
