Repository hashicorp/vault, pull requests merged in 2025-02, with the labels that each got.

#29479 refactor database plugin SDK
  sdk/database/dbplugin/plugin.go
  sdk/database/dbplugin/v5/grpc_client.go
  sdk/database/dbplugin/v5/grpc_client_oss.go
  sdk/database/dbplugin/v5/grpc_client_oss_test.go
  sdk/database/dbplugin/v5/grpc_client_test.go
  sdk/database/dbplugin/v5/grpc_database_plugin.go
  sdk/database/dbplugin/v5/grpc_database_plugin_oss.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/database/dbplugin/v5/grpc_server_oss.go
  sdk/database/dbplugin/v5/grpc_server_oss_test.go
  sdk/database/dbplugin/v5/grpc_server_test.go
  sdk/database/dbplugin/v5/plugin_client.go
  sdk/database/dbplugin/v5/plugin_client_oss.go
  sdk/database/dbplugin/v5/plugin_factory.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29402 Update go-kms-wrapping wrapper dependencies, adding ParsePaths support for sensitive values.
  changelog/29402.txt
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  website/content/docs/configuration/seal/alicloudkms.mdx
  website/content/docs/configuration/seal/awskms.mdx
  website/content/docs/configuration/seal/azurekeyvault.mdx
  website/content/docs/configuration/seal/gcpckms.mdx
  website/content/docs/configuration/seal/index.mdx
  website/content/docs/configuration/seal/ocikms.mdx
  website/content/docs/configuration/seal/pkcs11.mdx
  website/content/docs/configuration/seal/transit.mdx
Labels: hashicorp-contributed-pr

#29416 UI: Fix token renewal breaking policy checks
  changelog/29416.txt
  ui/app/services/auth.js
  ui/tests/acceptance/auth-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
Labels: hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent

#29487 docs: fix include syntax in upgrade guides
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29486 Backport of UI: Fix token renewal breaking policy checks into release/1.18.x
  changelog/29416.txt
  ui/app/services/auth.js
  ui/tests/acceptance/auth-test.js
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
Labels: ui, hashicorp-contributed-pr

#29489 backport: 1.18.x: docs: fix include syntax in upgrade guides
  website/content/docs/upgrading/upgrade-to-1.16.x.mdx
  website/content/docs/upgrading/upgrade-to-1.17.x.mdx
  website/content/docs/upgrading/upgrade-to-1.18.x.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29491 docs: backport: 1.18.x: fix build
  website/content/partials/known-issues/aws-auth-external-id.mdx
  website/content/partials/known-issues/duplicate-hsm-key.mdx
  website/content/partials/known-issues/sync-activation-flags-cache-not-updated.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29490 UI: backport auth test helpers
  ui/tests/helpers/auth/auth-form-selectors.ts
  ui/tests/helpers/auth/auth-helpers.ts
Labels: ui, hashicorp-contributed-pr, backport/ent/1.17.x+ent

#29492 ignore database_ent.proto from buf linter
  buf.yaml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29484 Backport of refactor database plugin SDK into release/1.18.x
  sdk/database/dbplugin/plugin.go
  sdk/database/dbplugin/v5/grpc_client.go
  sdk/database/dbplugin/v5/grpc_client_oss.go
  sdk/database/dbplugin/v5/grpc_client_oss_test.go
  sdk/database/dbplugin/v5/grpc_client_test.go
  sdk/database/dbplugin/v5/grpc_database_plugin.go
  sdk/database/dbplugin/v5/grpc_database_plugin_oss.go
  sdk/database/dbplugin/v5/grpc_server.go
  sdk/database/dbplugin/v5/grpc_server_oss.go
  sdk/database/dbplugin/v5/grpc_server_oss_test.go
  sdk/database/dbplugin/v5/grpc_server_test.go
  sdk/database/dbplugin/v5/plugin_client.go
  sdk/database/dbplugin/v5/plugin_client_oss.go
  sdk/database/dbplugin/v5/plugin_factory.go
  sdk/helper/pluginutil/run_config.go
  sdk/helper/pluginutil/run_config_stubs_oss.go
Labels: hashicorp-contributed-pr

#29493 Backport of ignore database_ent.proto from buf linter into release/1.18.x
  buf.yaml
Labels: hashicorp-contributed-pr

#29483 Fix group creation forwarding
  vault/identity_store.go
  vault/identity_store_groups.go
  vault/identity_store_structs.go
  vault/identity_store_util.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29445 Backport of Move all pki-verification calls from sdk-Verify() to pki-specific into release/1.18.x
  builtin/logical/pki/cert_util_test.go
  builtin/logical/pki/issuing/cert_verify.go
  builtin/logical/pki/issuing/issuing_stubs_oss.go
  builtin/logical/pki/path_issue_sign.go
  changelog/29342.txt
  go.mod
  go.sum
  sdk/go.mod
  sdk/go.sum
  sdk/helper/certutil/cert_verification.go
  sdk/helper/certutil/certutil_test.go
  sdk/helper/certutil/helpers.go
  sdk/helper/certutil/types.go
Labels: hashicorp-contributed-pr

#29482 Clean up on Azure configuration
  ui/app/components/secret-engine/configure-wif.ts
  ui/app/models/azure/config.js
  ui/app/models/gcp/config.js
  ui/tests/acceptance/secrets/backend/azure/azure-configuration-test.js
  ui/tests/helpers/secret-engine/secret-engine-helpers.js
  ui/tests/integration/components/secret-engine/configure-wif-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29499 Update azure key vault wrapper
  changelog/29499.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29501 Update go-secure-stdlib/cryptoutil
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29060 CLI: add an option for renew command fail on non-fulfillable request…
  changelog/29060.txt
  command/token_renew.go
  command/token_renew_test.go
  website/content/docs/commands/token/renew.mdx
Labels: enhancement, core/cli

#29502 Missed updating go-secure-stdlib in sdk :(
  sdk/go.mod
  sdk/go.sum
Labels: pr/no-changelog, hashicorp-contributed-pr

#29420 Backport of add docs for missing accessor flag in token renew command into release/1.18.x
  website/content/docs/commands/token/renew.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29471 identity (CE): Persist conflict resolution after rename
  vault/core.go
  vault/core_test.go
  vault/identity_store_conflicts.go
  vault/identity_store_conflicts_test.go
  vault/identity_store_test.go
  vault/identity_store_test_stubs_oss.go
  vault/identity_store_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29508 Docs: API: Raft snapshot configuration updates
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29506 Undo additions to the barrier encryption count if persisting those encryptions fails
  changelog/29506.txt
  vault/barrier_aes_gcm.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29510 Backport of Undo additions to the barrier encryption count if persisting those encryptions fails into release/1.18.x
  changelog/29506.txt
  vault/barrier_aes_gcm.go
Labels: hashicorp-contributed-pr

#29511 Backport of azure key vault wrapper MSI fix to 1.18.x
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29513 fix jsdoc typo
  ui/lib/core/addon/components/kv-object-editor.js
Labels: pr/no-changelog, hashicorp-contributed-pr

#29494 add stubs oss for entSetExternalPluginConfig()
  vault/auth.go
  vault/mount.go
  vault/mount_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29515 Docs: API: Manual backport of API docs raft auto snapshot updates
  website/content/api-docs/system/storage/raftautosnapshots.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29516 add EntStaticSystemView to StaticSystemView and its ce stubs
  sdk/logical/system_view.go
  sdk/logical/system_view_stubs_oss.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29514 Backport of add stubs oss for entSetExternalPluginConfig() into release/1.18.x
  vault/auth.go
  vault/mount.go
  vault/mount_util.go
Labels: hashicorp-contributed-pr

#29518 Backport of add EntStaticSystemView to StaticSystemView and its ce stubs into release/1.18.x
  sdk/logical/system_view.go
  sdk/logical/system_view_stubs_oss.go
Labels: hashicorp-contributed-pr

#29522 Add missing parameter signature_bits to the generate root PKI API docs
  website/content/api-docs/secret/pki/index.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29528 Update vault-plugin-auth-cf to v0.20.0
  changelog/29528.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29475 UI: Remove custom tag class and replace with Hds::Badge
  ui/app/components/dashboard/secrets-engines-card.hbs
  ui/app/components/policy-form.hbs
  ui/app/styles/components/namespace-reminder.scss
  ui/app/styles/core.scss
  ui/app/styles/core/element-styling.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/templates/components/identity/item-alias/alias-details.hbs
  ui/app/templates/components/identity/item-aliases.hbs
  ui/app/templates/components/identity/item-groups.hbs
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/app/templates/components/mfa/mfa-login-enforcement-form.hbs
  ui/app/templates/components/secret-list/database-list-item.hbs
  ui/app/templates/components/secret-list/ssh-role-item.hbs
  ui/app/templates/vault/cluster/access/identity/aliases/index.hbs
  ui/app/templates/vault/cluster/access/identity/show.hbs
  ui/app/templates/vault/cluster/policies/index.hbs
  ui/app/templates/vault/cluster/policy/edit.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/lib/core/addon/components/info-table-item-array.hbs
  ui/lib/core/addon/components/info-table-item-array.js
  ui/lib/core/addon/components/namespace-reminder.hbs
  ui/lib/core/addon/components/policy-example.hbs
  ui/lib/core/addon/components/replication-header.hbs
  ui/lib/core/addon/components/search-select.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/kv/addon/components/kv-page-header.hbs
  ui/lib/pki/addon/components/page/pki-issuer-list.hbs
  ui/lib/pki/addon/components/page/pki-key-list.hbs
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-info-table-rows.hbs
  ui/lib/replication/addon/templates/mode.hbs
  ui/tests/acceptance/mfa-method-test.js
  ui/tests/integration/components/info-table-item-array-test.js
  ui/tests/integration/components/pki/page/pki-issuer-rotate-root-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.18.x

#29525 UI: Use timestamp.now() in custom messages
  ui/app/models/config-ui/message.js
  ui/lib/config-ui/addon/components/messages/page/create-and-edit.js
  ui/tests/integration/components/config-ui/messages/page/create-and-edit-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.18.x

#29498 UI: Fix updating static roles via role edit page on UI
  changelog/29498.txt
  ui/app/adapters/database/role.js
  ui/tests/integration/components/database-role-edit-test.js
Labels: ui, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29536 Backport of UI: Fix updating static roles via role edit page on UI into release/1.18.x
  changelog/29498.txt
  ui/app/adapters/database/role.js
  ui/tests/integration/components/database-role-edit-test.js
Labels: hashicorp-contributed-pr

#29474 Backport of VAULT-21474 Run oidcPeriodicFunc for each namespace id store into release/1.18.x
  changelog/29312.txt
  vault/identity_store.go
  vault/identity_store_oidc.go
  vault/identity_store_oidc_test.go
  website/content/docs/enterprise/namespaces/namespace-limits.mdx
Labels: hashicorp-contributed-pr

#29537 db: honor static role TTL across restarts when skip import rotation i…
  builtin/logical/database/path_creds_create.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rotation_test.go
  changelog/29537.txt
Labels: hashicorp-contributed-pr, backport/1.18.x

#29540 Backport of db: honor static role TTL across restarts when skip import rotation i… into release/1.18.x
  builtin/logical/database/path_creds_create.go
  builtin/logical/database/path_roles.go
  builtin/logical/database/path_roles_test.go
  builtin/logical/database/rotation_test.go
  changelog/29537.txt
Labels: hashicorp-contributed-pr

#29497 Automated rotate root support for AWS Auth and Secrets
  builtin/credential/aws/backend.go
  builtin/credential/aws/backend_test.go
  builtin/credential/aws/path_config_client.go
  builtin/credential/aws/path_config_client_test.go
  builtin/credential/aws/path_config_rotate_root.go
  builtin/credential/aws/path_login_test.go
  builtin/logical/aws/backend.go
  builtin/logical/aws/backend_test.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/aws/path_config_root_test.go
  builtin/logical/aws/path_config_rotate_root.go
  builtin/logical/aws/secret_access_keys_test.go
  changelog/29497.txt
  sdk/helper/automatedrotationutil/fields.go
  sdk/helper/automatedrotationutil/fields_test.go
  sdk/plugin/grpc_system.go
  sdk/plugin/pb/backend.pb.go
  sdk/plugin/pb/backend.proto
  sdk/rotation/rotation_job.go
  sdk/rotation/rotation_job_test.go
  sdk/rotation/schedule.go
  vault/rotation_stubs_oss.go
Labels: hashicorp-contributed-pr

#29548 update vault auth submodules to api/v1.16.0
  api/auth/approle/go.mod
  api/auth/approle/go.sum
  api/auth/aws/go.mod
  api/auth/aws/go.sum
  api/auth/azure/go.mod
  api/auth/azure/go.sum
  api/auth/gcp/go.mod
  api/auth/gcp/go.sum
  api/auth/kubernetes/go.mod
  api/auth/kubernetes/go.sum
  api/auth/ldap/go.mod
  api/auth/ldap/go.sum
  api/auth/userpass/go.mod
  api/auth/userpass/go.sum
  builtin/logical/pki/metadata.pb.go
  go.mod
  helper/forwarding/types.pb.go
  helper/identity/mfa/types.pb.go
  helper/identity/types.pb.go
  helper/storagepacker/types.pb.go
  physical/raft/types.pb.go
  sdk/database/dbplugin/database.pb.go
  sdk/database/dbplugin/v5/proto/database.pb.go
  sdk/helper/clientcountutil/generation/generate_data.pb.go
  sdk/helper/pluginutil/multiplexing.pb.go
  sdk/logical/event.pb.go
  sdk/logical/identity.pb.go
  sdk/logical/plugin.pb.go
  sdk/logical/version.pb.go
  sdk/plugin/pb/backend.pb.go
  vault/activity/activity_log.pb.go
  vault/hcp_link/proto/link_control/link_control.pb.go
  vault/hcp_link/proto/meta/meta.pb.go
  vault/hcp_link/proto/node_status/status.pb.go
  vault/request_forwarding_service.pb.go
  vault/seal/multi_wrap_value.pb.go
  vault/tokens/token.pb.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29550 use new sdk and api versions
  go.mod
Labels: pr/no-changelog, hashicorp-contributed-pr

#29551 Update vault-plugin-secrets-openldap to v0.14.5
  changelog/29551.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29553 Update vault-plugin-auth-jwt to v0.23.0
  changelog/29553.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29554 Update vault-plugin-database-snowflake to v0.13.0
  changelog/29554.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29556 Backport of Update vault-plugin-secrets-openldap to v0.14.5 into release/1.18.x
  changelog/29551.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29543 Update vault-plugin-database-couchbase to v0.13.0
  changelog/29543.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29557 Add automated root rotation support to DB Secrets
  builtin/credential/aws/path_config_client.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/database/backend.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_rotate_credentials.go
  changelog/29497.txt
  changelog/29557.txt
  sdk/helper/automatedrotationutil/fields.go
  sdk/helper/automatedrotationutil/fields_test.go
  sdk/rotation/rotation_job.go
Labels: hashicorp-contributed-pr

#29542 Update vault-plugin-database-elasticsearch to v0.17.0
  changelog/29542.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29526 Backport of Add missing parameter signature_bits to the generate root PKI API docs into release/1.18.x
  website/content/api-docs/secret/pki/index.mdx
Labels: backport, docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29555 Backport 1.18.x - UI: Remove custom tag class and replace with Hds::Badge
  ui/app/components/dashboard/secrets-engines-card.hbs
  ui/app/components/policy-form.hbs
  ui/app/styles/components/namespace-reminder.scss
  ui/app/styles/core.scss
  ui/app/styles/core/element-styling.scss
  ui/app/styles/core/tag.scss
  ui/app/styles/helper-classes/spacing.scss
  ui/app/templates/components/identity/item-alias/alias-details.hbs
  ui/app/templates/components/identity/item-aliases.hbs
  ui/app/templates/components/identity/item-groups.hbs
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/app/templates/components/mfa/mfa-login-enforcement-form.hbs
  ui/app/templates/components/secret-list/database-list-item.hbs
  ui/app/templates/components/secret-list/ssh-role-item.hbs
  ui/app/templates/vault/cluster/access/identity/aliases/index.hbs
  ui/app/templates/vault/cluster/access/identity/show.hbs
  ui/app/templates/vault/cluster/policies/index.hbs
  ui/app/templates/vault/cluster/policy/edit.hbs
  ui/app/templates/vault/cluster/policy/show.hbs
  ui/lib/core/addon/components/info-table-item-array.hbs
  ui/lib/core/addon/components/info-table-item-array.js
  ui/lib/core/addon/components/namespace-reminder.hbs
  ui/lib/core/addon/components/policy-example.hbs
  ui/lib/core/addon/components/replication-header.hbs
  ui/lib/core/addon/components/search-select.hbs
  ui/lib/core/addon/components/secret-list-header.hbs
  ui/lib/kv/addon/components/kv-page-header.hbs
  ui/lib/pki/addon/components/page/pki-issuer-list.hbs
  ui/lib/pki/addon/components/page/pki-key-list.hbs
  ui/lib/pki/addon/components/pki-generate-csr.hbs
  ui/lib/pki/addon/components/pki-generate-root.hbs
  ui/lib/pki/addon/components/pki-info-table-rows.hbs
  ui/lib/replication/addon/templates/mode.hbs
  ui/tests/acceptance/mfa-method-test.js
  ui/tests/integration/components/info-table-item-array-test.js
  ui/tests/integration/components/pki/page/pki-issuer-rotate-root-test.js
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#29563 update version on release branch
  version/VERSION
Labels: pr/no-changelog, hashicorp-contributed-pr

#29564 bump version
  version/VERSION
Labels: pr/no-changelog, hashicorp-contributed-pr

#29565 add 1.19.x to versions
  .release/versions.hcl
Labels: pr/no-changelog, hashicorp-contributed-pr

#29559 Fix issue caused by group-creation forwarding.
  vault/identity_store_conflicts.go
  vault/identity_store_conflicts_test.go
  vault/identity_store_group_aliases.go
  vault/identity_store_test.go
  vault/identity_store_util.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29571 Backport of Update vault-plugin-auth-jwt to v0.23.0 into release/1.19.x
  changelog/29553.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29560 Fix failing AWS configuration test
  ui/app/serializers/aws/root-config.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29573 Backport of Update vault-plugin-database-couchbase to v0.13.0 into release/1.19.x
  changelog/29543.txt
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#29575 Backport of Update vault-plugin-secrets-terraform to v0.11.0 into release/1.19.x
  changelog/29541.txt
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#29577 Docs: Automatic cluster upgrades Autopilot note
  website/content/docs/enterprise/automated-upgrades.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29578 Docs: add a note for quorum size scaling
  website/content/docs/internals/integrated-storage.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x

#29580 Backport of Docs: Automatic cluster upgrades Autopilot note into release/1.18.x
  website/content/docs/enterprise/automated-upgrades.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29579 Backport of Fix failing AWS configuration test into release/1.19.x
  ui/app/serializers/aws/root-config.js
  ui/tests/acceptance/secrets/backend/aws/aws-configuration-test.js
Labels: ui, backport, pr/no-changelog, hashicorp-contributed-pr

#29583 Update vault-plugin-secrets-mongodbatlas to v0.14.0
  changelog/29583.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29562 VAULT-33603: normalize start time in export api
  changelog/29562.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core.go
  vault/core_util.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29582 Update vault-plugin-database-elasticsearch to v0.17.0 (#29542)
  changelog/29542.txt
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#29584 Update vault-plugin-database-mongodbatlas to v0.14.0
  changelog/29584.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29590 Backport of Update vault-plugin-database-mongodbatlas to v0.14.0 into release/1.19.x
  changelog/29584.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29576 Backport Automated Root Rotation support for DB secrets to 1.19.x
  builtin/credential/aws/path_config_client.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/database/backend.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  builtin/logical/database/path_rotate_credentials.go
  changelog/29497.txt
  changelog/29557.txt
  sdk/helper/automatedrotationutil/fields.go
  sdk/helper/automatedrotationutil/fields_test.go
  sdk/rotation/rotation_job.go
Labels: hashicorp-contributed-pr

#29585 Backport of Update vault-plugin-secrets-mongodbatlas to v0.14.0 into release/1.19.x
  changelog/29583.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29592 Update vault-plugin-secrets-kubernetes to v0.10.0
  changelog/29592.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29591 Update vault-plugin-auth-gcp to v0.20.0
  changelog/29591.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29594 Update vault-plugin-database-redis-elasticache to v0.6.0
  changelog/29594.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29597 Update vault-plugin-database-redis to v0.5.0
  changelog/29597.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29599 Backport of Update vault-plugin-database-redis to v0.5.0 into release/1.19.x
  changelog/29597.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29586 Backport of VAULT-33603: normalize start time in export api into release/1.18.x
  changelog/29562.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core.go
  vault/core_util.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr

#29587 Backport of VAULT-33603: normalize start time in export api into release/1.19.x
  changelog/29562.txt
  vault/activity_log.go
  vault/activity_log_test.go
  vault/core.go
  vault/core_util.go
  vault/external_tests/activity_testonly/activity_testonly_test.go
Labels: hashicorp-contributed-pr

#29598 Update vault-plugin-secrets-gcp to v0.21.0
  changelog/29598.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29600 Backport of Update vault-plugin-secrets-gcp to v0.21.0 into release/1.19.x
  changelog/29598.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29524 Revert "Add docs for new iteration of ent operator import feature (#29406)"
  website/content/docs/commands/operator/import.mdx
  website/content/docs/import/awssm.mdx
  website/content/docs/import/azurekv.mdx
  website/content/docs/import/gcpsm.mdx
  website/content/docs/import/index.mdx
  website/content/docs/import/mappings.mdx
  website/content/docs/import/vault.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.19.x

#29604 Add underlining support for the PKI Enterprise SCEP work
  builtin/logical/pki/cert_util.go
  builtin/logical/pki/issuing/signing_utils.go
  builtin/logical/pki/parsing/asn1.go
  builtin/logical/pki/parsing/asn1_test.go
  helper/pkcs7/decrypt.go
  helper/pkcs7/encrypt.go
  helper/pkcs7/encrypt_test.go
  helper/pkcs7/pkcs7.go
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29606 Update vault-plugin-auth-azure to v0.20.0
  changelog/29606.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29607 Backport of Update vault-plugin-secrets-openldap to v0.15.0 into release/1.19.x
  changelog/29605.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29609 Backport of Update vault-plugin-auth-azure to v0.20.0 into release/1.19.x
  changelog/29606.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29612 Update vault-plugin-secrets-gcpkms to v0.20.0
  changelog/29612.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29613 Update vault-plugin-auth-alicloud to v0.20.0
  changelog/29613.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29614 Update vault-plugin-secrets-kv to v0.21.0
  changelog/29614.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#29602 Backport of Revert "Add docs for new iteration of ent operator import feature (#29406)" into release/1.19.x
  website/content/docs/commands/operator/import.mdx
  website/content/docs/import/awssm.mdx
  website/content/docs/import/azurekv.mdx
  website/content/docs/import/gcpsm.mdx
  website/content/docs/import/index.mdx
  website/content/docs/import/mappings.mdx
  website/content/docs/import/vault.mdx
  website/data/docs-nav-data.json
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29610 Fix OpenApi test for GCP Auth
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29621 Backport of Fix OpenApi test for GCP Auth into release/1.19.x
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: backport, pr/no-changelog, hashicorp-contributed-pr

#29619 Update vault-plugin-auth-kubernetes to v0.21.0
  changelog/29619.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr

#27413 TOTP secrets in the web UI
  ui/app/adapters/totp.js
  ui/app/components/generate-credentials-totp.js
  ui/app/components/generate-credentials.js
  ui/app/components/secret-list/totp-list-item.js
  ui/app/components/totp-edit.js
  ui/app/helpers/supported-secret-backends.js
  ui/app/models/totp.js
  ui/app/routes/vault/cluster/secrets/backend/credentials.js
  ui/app/routes/vault/cluster/secrets/backend/list.js
  ui/app/routes/vault/cluster/secrets/backend/secret-edit.js
  ui/app/serializers/totp.js
  ui/app/styles/components/generate-credentials-totp.scss
  ui/app/styles/core.scss
  ui/app/templates/components/generate-credentials-totp.hbs
  ui/app/templates/components/secret-list/totp-list-item.hbs
  ui/app/templates/components/totp-edit.hbs
  ui/app/templates/vault/cluster/secrets/backend/credentials.hbs
  ui/lib/core/addon/components/form-field.hbs
  ui/lib/core/addon/helpers/options-for-backend.js
Labels: ui, pr/no-changelog, pr/no-milestone

#29535 Add support code for auth/ldap root autorotation
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_config.go
  builtin/credential/ldap/path_config_rotate_root.go
  changelog/29535.txt
  website/content/api-docs/auth/ldap.mdx
Labels: hashicorp-contributed-pr, backport/1.19.x

#29622 Backport of Add support code for auth/ldap root autorotation into release/1.19.x
  builtin/credential/ldap/backend.go
  builtin/credential/ldap/backend_test.go
  builtin/credential/ldap/path_config.go
  builtin/credential/ldap/path_config_rotate_root.go
  changelog/29535.txt
  website/content/api-docs/auth/ldap.mdx
Labels: hashicorp-contributed-pr

#29618 CE changes for VAULT-33452
  changelog/29618.txt
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/eventbus/filter.go
  vault/eventbus/filter_test.go
Labels: hashicorp-contributed-pr, backport/1.19.x

#29623 Fix OpenAPI test Azure Auth
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29593 Backport of Update vault-plugin-secrets-kubernetes to v0.10.0 into release/1.19.x
  changelog/29592.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29631 Backport of Fix OpenAPI test Azure Auth into release/1.19.x
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: ui, backport, hashicorp-contributed-pr

#29632 backport secrets engine plugin updates for gcpkms and vault-plugin-secrets-kv
  changelog/29612.txt
  changelog/29614.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29634 Fix rotation manager plugin logs in case of storage errors
  builtin/credential/aws/path_config_client.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/database/path_config_connection.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29628 Backport of Update vault-plugin-auth-kubernetes to v0.21.0 into release/1.19.x
  changelog/29619.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29620 Backport of update vault-plugin-auth-oci to v0.18.0 into release/1.19.x
  changelog/29620.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29636 Backport of Fix rotation manager plugin logs in case of storage errors into release/1.19.x
  builtin/credential/aws/path_config_client.go
  builtin/logical/aws/path_config_root.go
  builtin/logical/database/path_config_connection.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29639 Update vault-plugin-secrets-azure to v0.21.0
  changelog/29639.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29641 Backport of Update vault-plugin-secrets-azure to v0.21.0 into release/1.19.x
  changelog/29639.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29638 Backport of Update vault-plugin-auth-oci to v0.18.0 into release/1.19.x
  changelog/29620.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29644 Backport of UI: update openapi for auth-config/ldap model into release/1.19.x
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: hashicorp-contributed-pr

#29626 Backport of CE changes for VAULT-33452 into release/1.19.x
  changelog/29618.txt
  vault/eventbus/bus.go
  vault/eventbus/bus_test.go
  vault/eventbus/filter.go
  vault/eventbus/filter_test.go
Labels: hashicorp-contributed-pr

#29643 Backport of Update vault-plugin-auth-kerberos to v0.14.0 into release/1.19.x
  changelog/29617.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29648 Update vault-plugin-secrets-ad to v0.20.1
  changelog/29648.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29645 Add support for cross account management of static roles in AWS Secrets
  builtin/logical/aws/backend.go
  builtin/logical/aws/client.go
  builtin/logical/aws/client_ce.go
  builtin/logical/aws/iam_policies.go
  builtin/logical/aws/path_config_rotate_root.go
  builtin/logical/aws/path_static_roles.go
  builtin/logical/aws/path_static_roles_ce.go
  builtin/logical/aws/path_static_roles_test.go
  builtin/logical/aws/path_user.go
  builtin/logical/aws/rotation.go
  builtin/logical/aws/rotation_test.go
  builtin/logical/aws/secret_access_keys.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29650 Backport of Update vault-plugin-secrets-ad to v0.20.1 into release/1.19.x
  changelog/29648.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr

#29625 Backport of UI: MFA methods now display namespace_path instead of namespace_id into release/1.19.x
  changelog/29588.txt
  ui/app/models/mfa-method.js
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/mirage/factories/mfa-duo-method.js
  ui/mirage/factories/mfa-okta-method.js
  ui/mirage/factories/mfa-pingid-method.js
  ui/mirage/factories/mfa-totp-method.js
  ui/tests/acceptance/mfa-login-enforcement-test.js
  ui/tests/acceptance/mfa-method-test.js
Labels: ui, backport, hashicorp-contributed-pr

#29624 Backport of UI: MFA methods now display namespace_path instead of namespace_id into release/1.18.x
  changelog/29588.txt
  ui/app/models/mfa-method.js
  ui/app/templates/components/mfa/method-list-item.hbs
  ui/mirage/factories/mfa-duo-method.js
  ui/mirage/factories/mfa-okta-method.js
  ui/mirage/factories/mfa-pingid-method.js
  ui/mirage/factories/mfa-totp-method.js
  ui/tests/acceptance/mfa-login-enforcement-test.js
  ui/tests/acceptance/mfa-method-test.js
Labels: ui, backport, hashicorp-contributed-pr

#29652 Backport of Add support for cross account management of static roles in AWS Secrets into release/1.19.x
  builtin/logical/aws/backend.go
  builtin/logical/aws/client.go
  builtin/logical/aws/client_ce.go
  builtin/logical/aws/iam_policies.go
  builtin/logical/aws/path_config_rotate_root.go
  builtin/logical/aws/path_static_roles.go
  builtin/logical/aws/path_static_roles_ce.go
  builtin/logical/aws/path_static_roles_test.go
  builtin/logical/aws/path_user.go
  builtin/logical/aws/rotation.go
  builtin/logical/aws/rotation_test.go
  builtin/logical/aws/secret_access_keys.go
Labels: hashicorp-contributed-pr

#29655 Backport of [VAULT-21282] Bump raft-autopilot dependency to v0.3.0 into release/1.18.x
  go.mod
  go.sum
Labels: pr/no-milestone, hashicorp-contributed-pr

#29657 Backport of [VAULT-21282] Add a changelog entry for the updated Raft Autopilot reconciliation logic into release/1.18.x
  changelog/29306.txt
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29659 [VAULT-21282] Expose NetworkLayer on a TestClusterCore via a convenience method for testing purposes
  vault/testing.go
Labels: test, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29660 Update Go to 1.23.6 on main
  .go-version
  changelog/_go-ver-120.txt
Labels: pr/no-milestone, hashicorp-contributed-pr

#29661 Update Go to 1.23.6 on 1.19
  .go-version
  changelog/_go-ver-1190.txt
Labels: hashicorp-contributed-pr

#29662 Update Go to 1.23.6 on 1.18.x
  .go-version
  changelog/_go-ver-1185.txt
Labels: hashicorp-contributed-pr

#29667 Remove the Dashboard Survey Link
  ui/app/components/dashboard/overview.hbs
  ui/app/components/dashboard/survey-link-text.hbs
  ui/tests/integration/components/dashboard/overview-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29669 🧹 on policy upload file view
  ui/app/components/policy-form.hbs
  ui/tests/integration/components/policy-form-test.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr

#29633 UI: adding skip import rotation field when creating static roles
  changelog/29633.txt
  ui/app/models/database/role.js
  ui/app/utils/model-helpers/database-helpers.js
  ui/tests/integration/components/database-role-edit-test.js
Labels: ui, hashicorp-contributed-pr

#29463 VAULT-33601: fixing enos vault-radar failure
  enos/enos-scenario-seal-ha.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29519 database: fix reload to not fail early
  builtin/logical/database/path_config_connection.go
  changelog/29519.txt
  vault/external_tests/plugin/external_plugin_test.go
Labels: hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29230 VAULT-33401 - update security-scan.hcl
  .release/security-scan.hcl
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent

#29687 changelog update for 1.19.0-rc1
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29680 Fix bug with merging vault agent configs that set template_config
  changelog/29680.txt
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template-min-no-auth.hcl
Labels: pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29696 [DOCS] Add missing '**' to bold text
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
Labels: docs, pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, backport/1.18.x, backport/1.19.x

#29699 Backport of [DOCS] Add missing '**' to bold text into release/1.18.x
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
Labels: hashicorp-contributed-pr

#29700 Backport of [DOCS] Add missing '**' to bold text into release/1.19.x
  website/content/docs/secrets/kv/kv-v2/random-string.mdx
Labels: hashicorp-contributed-pr

#29677 UI: Add KV view for wrap tool
  changelog/29677.txt
  ui/app/components/tools/wrap.hbs
  ui/app/components/tools/wrap.js
  ui/tests/integration/components/tools/wrap-test.js
Labels: ui, hashicorp-contributed-pr

#29709 Backport of Small fixes on UX of Automated Root Rotation parameters into release/1.19.x
  builtin/logical/aws/path_config_root_test.go
  builtin/logical/database/backend_test.go
  builtin/logical/database/path_config_connection.go
  sdk/helper/automatedrotationutil/fields.go
  sdk/helper/automatedrotationutil/fields_test.go
  sdk/plugin/grpc_system.go
  sdk/rotation/rotation_job.go
Labels: pr/no-changelog, hashicorp-contributed-pr

#29697 Backport of Fix bug with merging vault agent configs that set template_config into release/1.18.x
  changelog/29680.txt
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template-min-no-auth.hcl
Labels: pr/no-milestone, hashicorp-contributed-pr

#29698 Backport of Fix bug with merging vault agent configs that set template_config into release/1.19.x
  changelog/29680.txt
  command/agent/config/config.go
  command/agent/config/config_test.go
  command/agent/config/test-fixtures/config-template-min-no-auth.hcl
Labels: pr/no-milestone, hashicorp-contributed-pr

#29708 Update CHANGELOG.md for 1.18.5, 1.17.12, 1.16.16
  CHANGELOG.md
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29711 Fix formatting issue in Go changelog on 1.19
  changelog/_go-ver-1190.txt
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29712 Fix formatting issue in Go changelogs on 1.18
  changelog/_go-ver-1183.txt
  changelog/_go-ver-1185.txt
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29710 Fix some formatting issues for Go changelogs
  changelog/_go-ver-1190.txt
  changelog/_go-ver-1200.txt
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr

#29476 VAULT-33693 actions: fix push event PR labels
  .github/actions/metadata/action.yml
Labels: pr/no-changelog, pr/no-milestone, hashicorp-contributed-pr, build/all, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29721 Update GRPC functions to send rotation window and period as seconds explicitly
  sdk/plugin/grpc_system.go
Labels: pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29723 Backport of Update GRPC functions to send rotation window and period as seconds explicitly into release/1.19.x
  sdk/plugin/grpc_system.go
Labels: hashicorp-contributed-pr

#29722 UI: update openapi for auth-config/azure, auth-config/ldap and auth-config/gcp
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/1.19.x

#29728 Update vault-plugin-auth-azure to v0.20.1
  changelog/29728.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29729 Update vault-plugin-secrets-azure to v0.21.1
  changelog/29729.txt
  go.mod
  go.sum
Labels: dependencies, hashicorp-contributed-pr, backport/1.19.x

#29719 [VAULT-33968] UI: Update HDS
  ui/package.json
  ui/tests/acceptance/enterprise-kmip-test.js
  ui/yarn.lock
Labels: pr/no-changelog, hashicorp-contributed-pr

#29724 UI: dependency bump for dompurify
  ui/package.json
  ui/yarn.lock
Labels: ui, pr/no-changelog, hashicorp-contributed-pr, backport/ent/1.16.x+ent, backport/1.18.x, backport/ent/1.17.x+ent, backport/1.19.x

#29725 Backport of UI: update openapi for auth-config/azure, auth-config/ldap and auth-config/gcp into release/1.19.x
  ui/tests/helpers/openapi/expected-auth-attrs.js
Labels: ui, backport, hashicorp-contributed-pr

#29730 Backport of Update vault-plugin-secrets-openldap to v0.15.1 into release/1.19.x
  changelog/29727.txt
  go.mod
  go.sum
Labels: hashicorp-contributed-pr
